<?php
/**
 * tools/lib/repair01_w7_contracts.php — عقودُ الأثرِ لأحداثِ الصيانةِ والترحيل
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **حدثٌ بلا عقدِ أثرٍ مسجَّلٍ لا يُنفَّذ** (§٥ · §٧): العقدُ يحمل المصدرَ
 *   والمحفِّزَ والحمولةَ الدنيا و**كلَّ مستهلكٍ فعليٍّ بالاسم** وأثرَ كلٍّ منهم
 *   والشروطَ المسبقةَ وسياسةَ الإعادةِ ومفتاحَ منعِ التكرارِ وسلوكَ الفشلِ
 *   والتعويض.
 *
 * ◆ **والمستهلكُ يُسمَّى ولا يُعمَّم**: «كلُّ المستهلكين» ليست قائمةَ مستهلكين.
 *
 * ◆ **ومستهلكانِ من مستهلكي هذه الأحداثِ حيّانِ مقيسانِ لا مُعلَنانِ فقط**:
 *   `RiskSignalEngine::sg01` يقرأ `mnt_breakdown` (ثلاثةُ أعطالٍ في تسعين يومًا)
 *   و`sg02` يقرأ `mnt_order.downtime_hours` — فأثرُ «المخاطرُ تقرأ المحفِّز»
 *   في رحلةِ §18 **صفٌّ في `risk_signals` يُعَدّ** لا دعوى.
 * ═══════════════════════════════════════════════════════════════════════════
 */
if (!defined('EMS_CLI')) { define('EMS_CLI', true); }

function repair01_w7_contract_narrative()
{
    return array(

    /* ══ 14 إدارة الصيانة · دورةُ العطل ══════════════════════════════════ */
    'mnt.breakdown.received' => array(
        'name' => 'استلامُ بلاغٍ فنّيّ',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/breakdown_intake.php · MaintenanceCycleService::receiveBreakdown',
        'trigger' => 'بلاغ انشا في مركز البلاغات ووصل الصيانة محالا — والصيانة لا تنشئ بلاغا موازيا',
        'payload' => 'company_id · breakdown_id · code · equipment_id · project_id · reported_by · report_datetime · is_stopped',
        'pre' => 'معدة قائمة في نطاق الكيان · كود بلاغ لا يتكرر في الكيان · جهة مبلغة معروفة',
        'idem' => 'w7:brk:{breakdown_id} — والمفتاح (كيان × كود البلاغ) يمنع بلاغين للواقعة نفسها',
        'effect' => 'operational',
        'consumers' => array(
            'mnt_order @ 14 إدارة الصيانة',
            'risk_signals @ 09 إدارة المخاطر',
            'tickets @ 10 إدارة البلاغات',
        ),
        'effects' => array(
            'mnt_order ⇐ يفتح محل امر العمل ولا امر بلا بلاغ او خطة او تفتيش · دليل: MEASURED (mnt_order.breakdown_id)',
            'risk_signals ⇐ RiskSignalEngine::sg01 يعد ثلاثة اعطال في تسعين يوما ويرفع اشارة · دليل: MEASURED (sg01)',
            'tickets ⇐ التذكرة الاصل تتابع حالتها ولا تقفل قبل امر العمل · دليل: MEASURED (tickets.linked_ref_table)',
        ),
        'fail' => 'فشل النشر لا يمنع الاستلام — الصف في mnt_breakdown هو الحقيقة والحدث اشعارها؛ ويعاد النشر بالمفتاح نفسه بلا تكرار',
        'comp' => 'لا محو: البلاغ يغلق بسببه المكتوب ولا يحذف — والاغلاق دليل يراجع',
        'src' => 'W07 §٥ · MNT-04 البلاغ الفني واستقبال العطل',
    ),
    'mnt.order.opened' => array(
        'name' => 'فتحُ أمرِ عمل',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/orders.php · MaintenanceCycleService::openOrder',
        'trigger' => 'الصيانة تفتح امر عمل على بلاغ او خطة وقائية او امر تفتيش — والتصنيف يقرا من سجل السلامة لا يكتب يدا',
        'payload' => 'company_id · order_id · code · equipment_id · failure_kind · safety_severity · safety_rule_ref · ops_impact · downtime_hours',
        'pre' => 'معدة قائمة · كود امر لا يتكرر في الكيان · منشئ معروف · عتبة الاثر التشغيلي مسجلة في repair01_w7_thresholds (والا رد 503)',
        'idem' => 'w7:ord:{order_id} — والمفتاح (كيان × كود الامر)',
        'effect' => 'operational',
        'consumers' => array(
            'equipments @ 04 إدارة الأسطول والأصول',
            'risk_signals @ 09 إدارة المخاطر',
            'mnt_part_request @ 14 إدارة الصيانة',
            'work_items @ 00 مساحة عملي',
        ),
        'effects' => array(
            'equipments ⇐ الحرج للسلامة يقفل تشغيل الاصل فورا الى prohibited · دليل: MEASURED (equipments.w7_readiness_state)',
            'risk_signals ⇐ RiskSignalEngine::sg02 يقرا downtime_hours ويرفع اشارة عند تجاوز حدها · دليل: MEASURED (sg02)',
            'mnt_part_request ⇐ يفتح محل طلب الصرف ولا صرف لامر مقفل · دليل: MEASURED (ORDER_CLOSED_NO_ISSUE)',
            'work_items ⇐ بند عمل للفني المكلف بمهلته · دليل: DECLARED_ACTIVE',
        ),
        'fail' => 'فشل النشر لا يلغي الامر — والصف في mnt_order دليل قائم يعاد نشره بمفتاحه',
        'comp' => 'لا تعديل رجعي على التصنيف: التصعيد واقعة بفاعلها وسببها (severity_override_by) والتخفيض مردود',
        'src' => 'W07 §٥ · MNT-07 أمر العمل · DEC-OPEN-12',
    ),
    'mnt.order.locked_out' => array(
        'name' => 'إيقافُ التشغيلِ ومنعُه',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/orders.php · MaintenanceCycleService::lockout',
        'trigger' => 'امر عمل صنف حرجا للسلامة — والقرار يوجب ايقافا ومنع تشغيل قبل الاصلاح لا بعده',
        'payload' => 'company_id · order_id · equipment_id · lockout_at · lockout_by',
        'pre' => 'امر عمل قائم · قاعدة سلامة توجب المنع في mnt_safety_rule.requires_lockout',
        'idem' => 'w7:lock:{order_id} — والقفل واقعة واحدة لكل امر',
        'effect' => 'operational',
        'consumers' => array(
            'equipments @ 04 إدارة الأسطول والأصول',
            'timesheet @ 11 إدارة التشغيل',
            'risk_escalations @ 09 إدارة المخاطر',
        ),
        'effects' => array(
            'equipments ⇐ حالة الجاهزية تصير prohibited ولا تشغل المعدة · دليل: MEASURED (w7_readiness_rule)',
            'timesheet ⇐ التشغيل يقرا حظر المعدة فلا تسند لوردية · دليل: DECLARED_ACTIVE',
            'risk_escalations ⇐ القيادة ترى تصعيدا على واقعة سلامة حرجة · دليل: MEASURED (risk_escalations.reason_ar)',
        ),
        'fail' => 'فشل النشر لا يرفع القفل — القفل في lockout_state هو الحقيقة',
        'comp' => 'لا رفع للقفل الا بشهادة عودة معتمدة (released) — ولا رفع يدوي',
        'src' => 'W07 §٥ · DEC-OPEN-12 اعادة الخدمة للحرج للسلامة',
    ),
    'mnt.order.severity_escalated' => array(
        'name' => 'تصعيدُ تصنيفِ السلامة',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/orders.php · MaintenanceCycleService::escalateSeverity',
        'trigger' => 'الفني او مهندس الصيانة او مسؤول السلامة يرى ان استمرار التشغيل غير امن — والحكم يرفع التصنيف حتى تتم مراجعته',
        'payload' => 'company_id · order_id · from_severity · to_severity · severity_override_by · severity_override_reason',
        'pre' => 'امر عمل قائم · فاعل معروف · سبب مكتوب · والتصنيف الجديد اعلى من القائم (SEVERITY_DOWNGRADE_FORBIDDEN)',
        'idem' => 'w7:sev:{order_id}:{to_severity} — والتصعيد الى الدرجة نفسها لا يتكرر',
        'effect' => 'operational',
        'consumers' => array(
            'mnt_return_cert @ 14 إدارة الصيانة',
            'equipments @ 04 إدارة الأسطول والأصول',
            'risk_signals @ 09 إدارة المخاطر',
        ),
        'effects' => array(
            'mnt_return_cert ⇐ الشهادة تصير واجبة ومعتمدها مخول فني لا المشغل · دليل: MEASURED (chk_mrc_signer)',
            'equipments ⇐ القفل يصير واجبا فتحظر المعدة · دليل: MEASURED (lockout)',
            'risk_signals ⇐ اشارة مخاطر على حكم سلامة مرفوع · دليل: DECLARED_ACTIVE',
        ),
        'fail' => 'فشل النشر لا ينقض التصعيد — والعمودان في mnt_order دليل قائم',
        'comp' => 'لا نقض: مراجعة الحكم قرار مسجل في سجل المخاطر لا تعديل في الشاشة',
        'src' => 'W07 §٥ · DEC-OPEN-12 ④ قائمة المكونات ليست الحكم وحدها',
    ),
    'mnt.parts.requested' => array(
        'name' => 'طلبُ صرفِ قطعٍ لأمرِ عمل',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/part_requests.php · MaintenanceCycleService::requestParts',
        'trigger' => 'الصيانة تطلب صرف قطع لامر مفتوح — والمخازن تصرف بسندها',
        'payload' => 'company_id · request_id · req_no · order_id · lines_count · priority · custodian_id · warehouse_ref',
        'pre' => 'امر عمل قائم وغير مقفل (ORDER_CLOSED_NO_ISSUE) · رقم طلب لا يتكرر في الكيان',
        'idem' => 'w7:preq:{request_id} — والمفتاح (كيان × رقم الطلب)',
        'effect' => 'operational',
        'consumers' => array(
            'stock_move @ 17 إدارة المخازن',
            'mnt_order_part @ 14 إدارة الصيانة',
            'mnt_return_cert @ 14 إدارة الصيانة',
        ),
        'effects' => array(
            'stock_move ⇐ المخازن تصرف بسند وترجع رقمه — ولا صرف بلا سند · دليل: MEASURED (chk_mpr_issue)',
            'mnt_order_part ⇐ البنود المصروفة تقيد على الامر وتقرا تكلفتها · دليل: MEASURED (mnt_order_part.subtotal)',
            'mnt_return_cert ⇐ التكلفة الفعلية في الشهادة تجمع القطع المصروفة · دليل: MEASURED (deriveOrderCost)',
        ),
        'fail' => 'فشل النشر لا يلغي الطلب — والصف في mnt_part_request دليل قائم',
        'comp' => 'لا محو: الطلب يرفض بسببه المكتوب او يلغى بحالته — ولا يحذف',
        'src' => 'W07 §٥ · MNT-10 طلب صرف القطع',
    ),
    'mnt.external.referred' => array(
        'name' => 'إحالةٌ خارجيةٌ أو مطالبةُ ضمان',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/external_repairs.php · MaintenanceCycleService::referExternal',
        'trigger' => 'الصيانة تحيل عملا الى جهة خارجية بعقدها او تفتح مطالبة ضمان على مورد المعدة بمرجع عقده',
        'payload' => 'company_id · line_id · order_id · line_kind · vendor_id · contract_ref · scope_ar · estimated_cost',
        'pre' => 'امر عمل قائم · ومطالبة الضمان بمرجع عقد مكتوب (WARRANTY_WITHOUT_CONTRACT_REF)',
        'idem' => 'w7:ext:{line_id} — والسطر واقعة بذاتها',
        'effect' => 'financial',
        'consumers' => array(
            'suppliers @ 02 إدارة الموردين',
            'fin_financial_events @ 05 الإدارة المالية',
            'mnt_return_cert @ 14 إدارة الصيانة',
        ),
        'effects' => array(
            'suppliers ⇐ التزام على المورد بعقده وحدوده — والمطالبة تقيد عليه · دليل: DECLARED_ACTIVE',
            'fin_financial_events ⇐ المالية تقيد التكلفة الخارجية بمصدرها ولا تكتبها الصيانة · دليل: DECLARED_ACTIVE',
            'mnt_return_cert ⇐ التكلفة الفعلية تجمع الخارجي مع العمالة والقطع · دليل: MEASURED (deriveOrderCost)',
        ),
        'fail' => 'فشل النشر لا يلغي الاحالة — والصف في mnt_external_repair دليل قائم',
        'comp' => 'لا محو: الاحالة تلغى بحالتها ونتيجة المطالبة تكتب ولا تمحى',
        'src' => 'W07 §٥ · MNT-11 الإصلاح الخارجي ومطالبات الضمان',
    ),

    /* ══ الإقفالُ والجاهزية ═════════════════════════════════════════════ */
    'mnt.return_cert.issued' => array(
        'name' => 'إصدارُ شهادةِ إعادةِ خدمة',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/return_to_service.php · MaintenanceCycleService::issueCert',
        'trigger' => 'الاصلاح انجز فنيا واختباره موثق — والشهادة تصدر لمن يوجبها تصنيفه لا لكل امر',
        'payload' => 'company_id · cert_id · cert_no · order_id · equipment_id · safety_severity · test_performed · test_result · meter_at_close · valid_days',
        'pre' => 'امر عمل منجز فنيا work_end (ORDER_WORK_NOT_COMPLETE) · تصنيف فوق البسيط (CERT_NOT_REQUIRED_FOR_MINOR) · الحرج مقفل التشغيل (LOCKOUT_REQUIRED_BEFORE_CERT) · نافذة صلاحية مسجلة (والا رد 503)',
        'idem' => 'w7:cert:{cert_id} — والمفتاح (كيان × رقم الشهادة)',
        'effect' => 'operational',
        'consumers' => array(
            'mnt_order @ 14 إدارة الصيانة',
            'equipments @ 04 إدارة الأسطول والأصول',
            'mnt_repeat_repair @ 14 إدارة الصيانة',
        ),
        'effects' => array(
            'mnt_order ⇐ الامر ينتظر الاعتماد ولا يقفل باصدار الشهادة وحده · دليل: MEASURED (state)',
            'equipments ⇐ لا عودة للخدمة بشهادة غير معتمدة — والمحاولة ترد NO_RETURN_WITHOUT_APPROVED_CERT · دليل: MEASURED (returnToService)',
            'mnt_repeat_repair ⇐ نافذة قياس التكرار تفتح بتاريخ الانجاز الفني · دليل: MEASURED (within_validity)',
        ),
        'fail' => 'فشل النشر لا يلغي الشهادة — والصف في mnt_return_cert مستند صادر يعاد نشره بمفتاحه',
        'comp' => 'لا محو: الشهادة ترفض بسببها او تخلفها شهادة اخرى (superseded_by) — والمستند الرسمي لا يحذف',
        'src' => 'W07 §٥ · MNT-14 الإقفال وشهادة إعادة الخدمة',
    ),
    'mnt.return_cert.approved' => array(
        'name' => 'اعتمادُ شهادةِ إعادةِ الخدمة',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/return_to_service.php · MaintenanceCycleService::approveCert',
        'trigger' => 'مدير الصيانة او المخول الفني يعتمد الشهادة — وهنا وحدها تعود المعدة للخدمة',
        'payload' => 'company_id · cert_id · order_id · equipment_id · approved_by · approved_at · valid_until · new_readiness_state',
        'pre' => 'شهادة بحالة submitted · معتمد غير منشئها (SOD_SELF_APPROVAL) · نتيجة اختبار غير مخفقة (TEST_FAILED_NO_RETURN) · والحرج للسلامة يعتمده مخول فني (SAFETY_CRITICAL_NEEDS_TECHNICAL_AUTHORITY)',
        'idem' => 'w7:certok:{cert_id} — والاعتماد واقعة واحدة والنداء الثاني يعيد الحالة بلا اثر',
        'effect' => 'operational',
        'consumers' => array(
            'equipments @ 04 إدارة الأسطول والأصول',
            'mnt_order @ 14 إدارة الصيانة',
            'asset_readiness @ 04 إدارة الأسطول والأصول',
            'mnt_kpi_period @ 14 إدارة الصيانة',
        ),
        'effects' => array(
            'equipments ⇐ حالة الجاهزية والقيود التشغيلية تكتب من الشهادة والقفل يرفع · دليل: MEASURED (w7_cert_id)',
            'mnt_order ⇐ الامر يقفل بالشهادة ومرجعها يكتب فيه · دليل: MEASURED (readiness_cert_ref)',
            'asset_readiness ⇐ الجاهزية الشهرية المشتقة تتغير بعودة الاصل · دليل: MEASURED (AssetLifecycleService)',
            'mnt_kpi_period ⇐ متوسط زمن الاصلاح ونسبة الالتزام يعاد اشتقاقهما · دليل: MEASURED (kpiFormula)',
        ),
        'fail' => 'فشل النشر لا ينقض الاعتماد — والاثر واقع في equipments و mnt_order قبل النشر',
        'comp' => 'لا نقض: شهادة جديدة تخلف القديمة (superseded) ولا يعاد فتح الامر بمحو الشهادة',
        'src' => 'W07 §٥ · MNT-14 · DEC-OPEN-12 اعادة الخدمة',
    ),
    'mnt.equipment.returned_to_service' => array(
        'name' => 'عودةُ المعدّةِ للخدمة',
        'unit' => '04 إدارة الأسطول والأصول',
        'screen' => 'Maintenance/return_to_service.php · MaintenanceCycleService::returnToService',
        'trigger' => 'شهادة معتمدة تعيد المعدة — والحالة الفنية ملك الاسطول والكتابة فيها اثر الشهادة لا فعل الصيانة',
        'payload' => 'company_id · equipment_id · cert_id · new_readiness_state · operating_limits',
        'pre' => 'شهادة بحالة approved حصرا (NO_RETURN_WITHOUT_APPROVED_CERT) · وقيد التشغيل مكتوب اذا كانت العودة مقيدة (chk_eq_w7_limits)',
        'idem' => 'w7:rts:{cert_id} — والعودة واقعة واحدة لكل شهادة',
        'effect' => 'operational',
        'consumers' => array(
            'timesheet @ 11 إدارة التشغيل',
            'asset_readiness @ 04 إدارة الأسطول والأصول',
            'ops_stop_register @ 11 إدارة التشغيل',
            'transfer_orders @ 15 إدارة النقل والترحيل',
        ),
        'effects' => array(
            'timesheet ⇐ التشغيل يعيد اسناد المعدة لوردية بقيودها المكتوبة · دليل: MEASURED (w7_operating_limits)',
            'asset_readiness ⇐ الجاهزية المشتقة تعود وترتفع بانتهاء ساعات التوقف · دليل: MEASURED (asset_readiness)',
            'ops_stop_register ⇐ واقعة التوقف تقفل بقرارها ولا تبقى مفتوحة · دليل: MEASURED (decision)',
            'transfer_orders ⇐ المعدة العائدة تصير قابلة للترحيل — ولا ترحيل لمحظورة · دليل: DECLARED_ACTIVE',
        ),
        'fail' => 'فشل النشر لا يعيد المعدة الى الحظر — والحالة في equipments هي الحقيقة',
        'comp' => 'لا رجوع: تدهور جديد يفتح امر عمل جديدا وواقعة تكرار — لا يعدل الصف القديم',
        'src' => 'W07 §٥ · MNT-14 · FLEET-16 الحالة الفنية الراهنة',
    ),
    'mnt.repeat_repair.opened' => array(
        'name' => 'فتحُ واقعةِ إعادةِ إصلاح',
        'unit' => '14 إدارة الصيانة',
        'screen' => 'Maintenance/repeat_repairs.php · MaintenanceCycleService::recordRepeat',
        'trigger' => 'العطل تكرر على العقدة نفسها — والتكرار خلال صلاحية الشهادة يفتح تحليل السبب الجذري',
        'payload' => 'company_id · repeat_id · equipment_id · origin_order_id · origin_cert_id · tree_node · repeat_date · days_since_cert · within_validity · rca_trigger',
        'pre' => 'امر اصلي قائم · وواقعة واحدة لكل (امر اصلي × يوم تكرار) · والصلاحية تقرا من الشهادة لا تدخل',
        'idem' => 'w7:rep:{repeat_id} — والمفتاح (كيان × امر اصلي × تاريخ التكرار)',
        'effect' => 'operational',
        'consumers' => array(
            'mnt_order @ 14 إدارة الصيانة',
            'risk_signals @ 09 إدارة المخاطر',
            'mnt_kpi_period @ 14 إدارة الصيانة',
            'suppliers @ 02 إدارة الموردين',
        ),
        'effects' => array(
            'mnt_order ⇐ امر جديد يفتح على العقدة نفسها ويربط بالواقعة · دليل: MEASURED (new_order_id)',
            'risk_signals ⇐ RiskSignalEngine::sg01 يقرا تكرار الاعطال على المعدة ويرفع اشارة · دليل: MEASURED (sg01)',
            'mnt_kpi_period ⇐ متوسط الزمن بين الاعطال ينخفض ويظهر في مؤشر الفترة · دليل: MEASURED (kpiFormula)',
            'suppliers ⇐ التكرار داخل الضمان يفتح مطالبة على مورد المعدة · دليل: DECLARED_ACTIVE',
        ),
        'fail' => 'فشل النشر لا يلغي الواقعة — والصف في mnt_repeat_repair دليل يراجع',
        'comp' => 'لا محو: التحليل يغلق بسببه الجذري وقراره — والاغلاق بلا سبب مردود (chk_mrr_close)',
        'src' => 'W07 §٥ · MNT-15 سجل إعادة الإصلاح',
    ),

    /* ══ 15 إدارة النقل والترحيل ═════════════════════════════════════════ */
    'trp.request.submitted' => array(
        'name' => 'رفعُ طلبِ ترحيل',
        'unit' => '15 إدارة النقل والترحيل',
        'screen' => 'Transport/transfer_requests.php · TransferCycleService::openRequest',
        'trigger' => 'جهة طالبة ترفع طلب ترحيل — والنقل يملك الامر والتنفيذ ولا ترحيل معدة بلا امر نقل',
        'payload' => 'company_id · request_id · code · source_module · project_id · requested_by · priority',
        'pre' => 'كود طلب لا يتكرر في الكيان · جهة طالبة معروفة',
        'idem' => 'w7:treq:{request_id} — والمفتاح (كيان × كود الطلب)',
        'effect' => 'operational',
        'consumers' => array(
            'transfer_orders @ 15 إدارة النقل والترحيل',
            'equipments @ 04 إدارة الأسطول والأصول',
        ),
        'effects' => array(
            'transfer_orders ⇐ يفتح محل الامر ولا امر بلا طلب يسبقه · دليل: MEASURED (transfer_orders.request_id)',
            'equipments ⇐ الاسطول يرى ان المعدة مرشحة للحركة · دليل: DECLARED_ACTIVE',
        ),
        'fail' => 'فشل النشر لا يلغي الطلب — والصف في transfer_requests دليل قائم',
        'comp' => 'لا محو: الطلب يرفض بحالته او يحول الى امر — ولا يحذف',
        'src' => 'W07 §٥ · TRP-02 طلب الترحيل',
    ),
    'trp.order.opened' => array(
        'name' => 'فتحُ أمرِ ترحيل',
        'unit' => '15 إدارة النقل والترحيل',
        'screen' => 'Transport/transfer_order_form.php · TransferCycleService::openOrder',
        'trigger' => 'النقل يحول الطلب الى امر بوسيلته وسائقه ومساره — وهوية المعدة تبقى عند الاسطول',
        'payload' => 'company_id · order_id · order_no · request_id · direction · carrier_type · driver_id · route · distance_km · cost_bearer',
        'pre' => 'رقم امر لا يتكرر في الكيان · وقاعدة المتحمل من العقد',
        'idem' => 'w7:tord:{order_id} — والمفتاح (كيان × رقم الامر)',
        'effect' => 'operational',
        'consumers' => array(
            'transfer_permits @ 15 إدارة النقل والترحيل',
            'trp_origin_handover @ 15 إدارة النقل والترحيل',
            'trp_trip_leg @ 15 إدارة النقل والترحيل',
            'fleet_equipment_history @ 04 إدارة الأسطول والأصول',
        ),
        'effects' => array(
            'transfer_permits ⇐ يفتح محل التصاريح ولا مغادرة بتصريح منته · دليل: MEASURED (PERMIT_EXPIRED)',
            'trp_origin_handover ⇐ يفتح محل بنود التجهيز ولا مغادرة قبل اكتمالها · دليل: MEASURED (HANDOVER_INCOMPLETE)',
            'trp_trip_leg ⇐ يفتح محل مراحل الرحلة بمركباتها وسائقيها · دليل: MEASURED (uq_ttl)',
            'fleet_equipment_history ⇐ حركة الموقع تسجل ولا ينشا اصل جديد بالانتقال · دليل: DECLARED_ACTIVE',
        ),
        'fail' => 'فشل النشر لا يلغي الامر — والصف في transfer_orders دليل قائم',
        'comp' => 'لا محو: الامر يلغى بحالته cancelled بسببه — ولا يحذف',
        'src' => 'W07 §٥ · TRP-04 أمر الترحيل',
    ),
    'trp.order.departure_authorized' => array(
        'name' => 'الإذنُ بالمغادرة',
        'unit' => '15 إدارة النقل والترحيل',
        'screen' => 'Transport/transfer_origin_handover.php · TransferCycleService::authorizeDeparture',
        'trigger' => 'اكتمل التجهيز وصلحت التصاريح — والاذن بوابة Fail-Closed لا خطوة اجرائية',
        'payload' => 'company_id · order_id · permits_checked · handover_items · departure_date',
        'pre' => 'تصاريح غير منتهية بسماح السجل W7_PERMIT_EXPIRY_GRACE_DAYS (PERMIT_EXPIRED) · وبنود تجهيز بدات ولا بند معلق او مخفق (HANDOVER_NOT_STARTED · HANDOVER_INCOMPLETE)',
        'idem' => 'w7:dep:{order_id} — والاذن واقعة واحدة لكل امر',
        'effect' => 'operational',
        'consumers' => array(
            'transfer_orders @ 15 إدارة النقل والترحيل',
            'trp_trip_leg @ 15 إدارة النقل والترحيل',
            'risk_signals @ 09 إدارة المخاطر',
        ),
        'effects' => array(
            'transfer_orders ⇐ المرحلة تتقدم الى ready ولا تتقدم بالتعديل اليدوي · دليل: MEASURED (stage)',
            'trp_trip_leg ⇐ المرحلة الاولى تصير قابلة للبدء · دليل: MEASURED (startLeg)',
            'risk_signals ⇐ تقييم مخاطر المسار المرتفع يرفع اشارة قبل المغادرة · دليل: DECLARED_ACTIVE',
        ),
        'fail' => 'فشل النشر لا يمنع المغادرة — والمرحلة في transfer_orders هي الحقيقة',
        'comp' => 'لا نقض: منع المغادرة بعد الاذن حدث ايقاف مسجل لا محو للاذن',
        'src' => 'W07 §٥ · TRP-05 · TRP-06 بوابتا المغادرة',
    ),
    'trp.order.arrived' => array(
        'name' => 'محضرُ الاستلامِ وقراءةُ العدّاد',
        'unit' => '15 إدارة النقل والترحيل',
        'screen' => 'Transport/transfer_arrival.php · TransferCycleService::recordArrival',
        'trigger' => 'الحمولة وصلت وسلمت بمحضر — وقراءة العداد عند الاستلام الزامية',
        'payload' => 'company_id · order_id · doc_id · doc_ref · delivered_at · witness_name · meter_reading · equipment_id',
        'pre' => 'امر ترحيل قائم · مرجع محضر مكتوب · قراءة عداد موجودة (METER_REQUIRED)',
        'idem' => 'w7:arr:{order_id} — والمفتاح (امر × مرجع المحضر)',
        'effect' => 'operational',
        'consumers' => array(
            'meter_readings @ 04 إدارة الأسطول والأصول',
            'trp_closure @ 15 إدارة النقل والترحيل',
            'trp_damage_claim @ 15 إدارة النقل والترحيل',
            'transfer_orders @ 15 إدارة النقل والترحيل',
        ),
        'effects' => array(
            'meter_readings ⇐ القراءة تقيد في كرت المعدة بمصدر transfer — ومصدر حقيقة العداد واحد · دليل: MEASURED (meter_readings.source)',
            'trp_closure ⇐ يفتح محل الاقفال ولا اقفال قبل المحضر · دليل: MEASURED (NO_CLOSURE_WITHOUT_DELIVERY_DOC)',
            'trp_damage_claim ⇐ التلف الموثق في المحضر يفتح مطالبة على المتسبب · دليل: MEASURED (incident_ref)',
            'transfer_orders ⇐ المرحلة تتقدم الى arrived · دليل: MEASURED (stage)',
        ),
        'fail' => 'فشل النشر لا يلغي المحضر — والصف في transfer_delivery_docs مستند صادر',
        'comp' => 'لا محو: خطا القراءة يصحح بقراءة جديدة في سلسلتها ولا يمحى ماض (MeterReadingService)',
        'src' => 'W07 §٥ · TRP-09 محضر الاستلام وقراءة العدّاد',
    ),
    'trp.damage_claim.opened' => array(
        'name' => 'فتحُ مطالبةِ تلفٍ أو حادث',
        'unit' => '15 إدارة النقل والترحيل',
        'screen' => 'Transport/transfer_damage_claims.php · TransferCycleService::openClaim',
        'trigger' => 'تلف موثق في المحضر او حادث رحلة — والمطالبة على المتسبب بقاعدة المتحمل من العقد',
        'payload' => 'company_id · claim_id · claim_no · order_id · incident_ref · damage_desc · liable_party · liable_rule · claim_amount · claim_route',
        'pre' => 'امر ترحيل قائم · مرجع واقعة ووصف تلف مكتوبان (CLAIM_WITHOUT_INCIDENT_EVIDENCE) · والمتحمل المحدد بقاعدة عقد (LIABLE_WITHOUT_CONTRACT_RULE)',
        'idem' => 'w7:clm:{claim_id} — والمفتاح (كيان × رقم المطالبة)',
        'effect' => 'financial',
        'consumers' => array(
            'fin_financial_events @ 05 الإدارة المالية',
            'suppliers @ 02 إدارة الموردين',
            'risk_incidents @ 09 إدارة المخاطر',
            'trp_closure @ 15 إدارة النقل والترحيل',
        ),
        'effects' => array(
            'fin_financial_events ⇐ المالية تقيد الذمة على المتحمل بقاعدة العقد · دليل: DECLARED_ACTIVE',
            'suppliers ⇐ الناقل المتعاقد يحمل قيمة التسوية على حسابه · دليل: DECLARED_ACTIVE',
            'risk_incidents ⇐ حادث الرحلة واقعة مخاطر تسجل وتحلل · دليل: DECLARED_ACTIVE',
            'trp_closure ⇐ الاقفال يقرا المطالبات القائمة على الامر · دليل: MEASURED (order_id)',
        ),
        'fail' => 'فشل النشر لا يلغي المطالبة — والصف في trp_damage_claim دليل قائم',
        'comp' => 'لا محو: المطالبة ترفض بسببها او تسوى بقرارها وقيمتها — ولا تحذف',
        'src' => 'W07 §٥ · TRP-10 مطالبات التلف والحوادث',
    ),
    'trp.order.closure_submitted' => array(
        'name' => 'رفعُ إقفالِ أمرِ ترحيل',
        'unit' => '15 إدارة النقل والترحيل',
        'screen' => 'Transport/transfer_closure.php · TransferCycleService::closeOrder',
        'trigger' => 'المحضر وقع والبنود اكتملت — والاقفال حبة مستقلة عن بنود التكلفة',
        'payload' => 'company_id · closure_id · order_id · delivery_doc_id · cost_lines_count · total_cost · bearer_split · meter_posted',
        'pre' => 'محضر استلام قائم (NO_CLOSURE_WITHOUT_DELIVERY_DOC) · منشئ معروف · والتكلفة تشتق من البنود ولا تدخل',
        'idem' => 'w7:tclo:{closure_id} — والمفتاح (كيان × امر الترحيل)',
        'effect' => 'financial',
        'consumers' => array(
            'transfer_cost_lines @ 15 إدارة النقل والترحيل',
            'fin_financial_events @ 05 الإدارة المالية',
            'trp_kpi_period @ 15 إدارة النقل والترحيل',
        ),
        'effects' => array(
            'transfer_cost_lines ⇐ البنود تقرا ويعاد جمعها في الاقفال ولا تكتب منه · دليل: MEASURED (derivation_rule)',
            'fin_financial_events ⇐ الاحالة للمالية بمرجعها والقيد عندها لا هنا · دليل: DECLARED_ACTIVE',
            'trp_kpi_period ⇐ نسبة المقفلة وتكلفة الكيلومتر يعاد اشتقاقهما · دليل: MEASURED (deriveCost)',
        ),
        'fail' => 'فشل النشر لا يلغي الاقفال — والصف في trp_closure دليل قائم',
        'comp' => 'لا محو: الاقفال يرفض بسببه او يعاد فتحه بسبب مكتوب (chk_tcl_reop)',
        'src' => 'W07 §٥ · TRP-12 إقفال أمر الترحيل',
    ),
    'trp.order.closed' => array(
        'name' => 'اعتمادُ الإقفالِ وإقفالُ الأمر',
        'unit' => '15 إدارة النقل والترحيل',
        'screen' => 'Transport/transfer_closure.php · TransferCycleService::approveClosure',
        'trigger' => 'المعتمد يعتمد الاقفال — والامر يقفل هنا لا بعد البنود',
        'payload' => 'company_id · closure_id · order_id · approved_by · approved_at · total_cost · meter_posted',
        'pre' => 'اقفال بحالة submitted · معتمد غير منشئه (SOD_SELF_APPROVAL) · وقراءة العداد مرحلة الى كرت المعدة (METER_NOT_POSTED)',
        'idem' => 'w7:tcls:{closure_id} — والاعتماد واقعة واحدة والنداء الثاني يعيد الحالة',
        'effect' => 'financial',
        'consumers' => array(
            'transfer_orders @ 15 إدارة النقل والترحيل',
            'fin_financial_events @ 05 الإدارة المالية',
            'equipments @ 04 إدارة الأسطول والأصول',
            'trp_kpi_period @ 15 إدارة النقل والترحيل',
        ),
        'effects' => array(
            'transfer_orders ⇐ المرحلة تصير closed ولا تتراجع (STAGE_BACKWARD_FORBIDDEN) · دليل: MEASURED (stage)',
            'fin_financial_events ⇐ التكلفة المعتمدة تحال للقيد بمرجعها · دليل: DECLARED_ACTIVE',
            'equipments ⇐ موقع المعدة الجديد يثبت وقراءة عدادها مرحلة · دليل: MEASURED (meter_posted)',
            'trp_kpi_period ⇐ تقرير الفترة يعاد اشتقاقه بالامر المقفل · دليل: MEASURED (orders_closed)',
        ),
        'fail' => 'فشل النشر لا ينقض الاعتماد — والمرحلة في transfer_orders هي الحقيقة',
        'comp' => 'اعادة الفتح حالة بسببها المكتوب لا محو للاعتماد',
        'src' => 'W07 §٥ · TRP-12 · TRP-13',
    ),
    );
}
