<?php
/**
 * tools/specs/dep01_sales.php — مواصفةُ `DEP-01` المبيعاتُ التعاقديةُ والعقود (GOV_EXEC §5)
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **سبعُ حبّاتٍ قائمةٌ تُستكمل ولا تُستنسَخ**: `activities` ·
 *   `fin_precontract_review` · `contractequipments` (بنودُ العقد) · `contracts`
 *   (مصفوفةُ الالتزاماتِ حبّتُها **العقدُ نفسُه** فلا جدولَ ثانيَ لها) ·
 *   `contract_monthly_plan` · `contract_commitments` · `contract_amendments` ·
 *   `monthly_performance`.
 *
 * ◆ **وسطحٌ واحدٌ جديدٌ بحبّةٍ لا مالكَ لها**: «الحاويات الشهرية والفاقد» —
 *   حبّتُها **دورةُ التزامٍ × شهر** وكلُّ حقولِها مشتقّةٌ أو مستوردةٌ إلّا
 *   ثلاثةً، فطبيعتُها `read` بنصِّ §19، ونسبُها مكتوبٌ في تعليقِ الجدول:
 *   `op_containers` سعةً و`monthly_performance` تنفيذًا.
 *
 * ⛔ **والفاقدُ لا يُرحَّل**: عمودُه مُعلَنٌ بذلك في تعليقِه — فالقاعدةُ في
 *   المخطَّطِ لا في ذاكرةِ من يقرأ.
 */
return array(
    'dept'    => 'DEP-01',
    'dept_ar' => 'إدارة المبيعات التعاقدية والعقود',
    'unit'    => 'إدارة المبيعات التعاقدية والعقود',
    'role_id' => 12,
    'dir'     => 'contracts',
    'neighbor_route' => 'contracts/contracts.php',
    'screens' => array(

array(
    'code' => 'sal_activities', 'file' => 'sales_activities.php', 'placement_id' => 5,
    'surface' => 'الأنشطة والمتابعات', 'title' => 'الأنشطة والمتابعات', 'icon' => 'fa fa-list-check',
    'table' => 'activities', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'خط الأنابيب', 'sort_no' => 2,
    'grain' => 'نشاطٌ أو متابعةٌ واحدةٌ على عميلٍ أو فرصةٍ أو عقد',
    'target_ref' => 'DEP-01·5·الانشطه والمتابعات',
    'intro' => 'أنشطةُ البيعِ ومتابعاتُها بنتيجتِها ومسؤولِها وإجرائِها التالي وتاريخِه',
    'rule'  => 'كلُّ نشاطٍ بإجراءٍ تالٍ وتاريخِه — والمتابعةُ بلا إجراءٍ تالٍ لا تُقفل خطًّا',
    'empty' => 'لا نشاطَ مسجَّلٌ بعد',
    'where' => 'is_deleted = 0',
    'order' => 'activity_date DESC, id DESC',
    'create' => array('activity_date', 'client_no', 'client_name', 'project_no',
                      'opportunity_no', 'contract_ref', 'activity_type', 'subject', 'outcome',
                      'next_action', 'next_action_date'),
    'keys' => array('activity_code', 'activity_date', 'client_no', 'client_name', 'project_no',
                    'opportunity_no', 'contract_ref', 'activity_type', 'subject', 'outcome',
                    'assigned_user_id', 'next_action', 'next_action_date', 'notes',
                    'container_key', 'evidence_level', 'retro_value_basis'),
    'types' => array('next_action_date' => 'DATE NULL DEFAULT NULL',
                     'client_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'project_no' => 'VARCHAR(60) NULL DEFAULT NULL'),
),
array(
    'code' => 'sal_precontract', 'file' => 'precontract_review.php', 'placement_id' => 10,
    'surface' => 'مراجعة ما قبل العقد', 'title' => 'مراجعة ما قبل العقد', 'icon' => 'fa fa-magnifying-glass-chart',
    'table' => 'fin_precontract_review', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'العرض والتفاوض', 'sort_no' => 4,
    'grain' => 'مراجعةُ ما قبلَ العقدِ واحدةٌ لعرضٍ واحد',
    'target_ref' => 'DEP-01·10·مراجعه ما قبل العقد',
    'intro' => 'مراجعةُ العرضِ قبلَ التوقيع: النطاقُ والأسعارُ والكمياتُ والضماناتُ والمخاطرُ التجارية',
    'rule'  => 'الجاهزيةُ للتوقيعِ لا تُعلَن وملاحظةٌ مفتوحةٌ قائمة — والمعتمِدُ مسمًّى',
    'empty' => 'لا مراجعةَ ما قبلَ عقدٍ مسجَّلةٌ بعد',
    'order' => 'id DESC',
    'create' => array('offer_id', 'client_no', 'client_name', 'project_no', 'final_offer_match',
                      'scope_review', 'prices_review', 'quantities_review', 'currency_ref',
                      'payment_terms', 'advance_terms', 'guarantee_terms', 'penalty_terms',
                      'client_obligations', 'commercial_risks', 'open_notes', 'sign_readiness',
                      'closed_date', 'contract_ref'),
    'keys' => array('review_code', 'offer_id', 'client_no', 'client_name', 'project_no',
                    'final_offer_match', 'scope_review', 'prices_review', 'quantities_review',
                    'currency_ref', 'payment_terms', 'advance_terms', 'guarantee_terms',
                    'penalty_terms', 'client_obligations', 'commercial_risks', 'open_notes',
                    'sign_readiness', 'closed_date', 'decided_by', 'contract_ref', 'notes',
                    'container_key', 'evidence_level', 'retro_value_basis'),
    'types' => array('client_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'project_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'closed_date' => 'DATE NULL DEFAULT NULL'),
    'dc' => array('prices_review' => 'DC-2', 'payment_terms' => 'DC-2',
                  'guarantee_terms' => 'DC-3', 'penalty_terms' => 'DC-3',
                  'client_obligations' => 'DC-3'),
),
array(
    'code' => 'sal_contract_lines', 'file' => 'contract_commercial_lines.php', 'placement_id' => 12,
    'surface' => 'بنود العقد والالتزام التجاري', 'title' => 'بنود العقد والالتزام التجاري',
    'icon' => 'fa fa-list-ol',
    'table' => 'contractequipments', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التعاقد والالتزام', 'sort_no' => 2,
    'grain' => 'بندُ بيعٍ واحدٌ في عقدٍ واحد',
    'target_ref' => 'DEP-01·12·بنود العقد والالتزام التجاري',
    'intro' => 'بنودُ العقدِ بوحدةِ قياسِها وأساسِها الشهريِّ ومستهدفِها وسعرِ وحدتِها ونسختِه',
    'rule'  => 'نصُّ السعرِ كما ورد بالمصدرِ يُحفَظ — والسعرُ المُطبَّقُ نسخةٌ لها سريان (§18)',
    'empty' => 'لا بندَ عقدٍ مسجَّلٌ بعد',
    'pk_code' => array('line_code', 'CLN'),
    'create' => array('contract_id', 'client_no', 'client_name', 'business_model', 'equip_type',
                      'equip_unit', 'equip_count', 'monthly_unit_basis', 'equip_monthly_target',
                      'equip_price_currency', 'equip_price', 'price_version_from', 'price_state',
                      'pricing_basis', 'price_source_text', 'shortfall_rule', 'mix_valid_from',
                      'container_key', 'target_source'),
    'keys' => array('line_code', 'contract_id', 'client_no', 'client_name', 'business_model',
                    'equip_type', 'equip_unit', 'equip_count', 'monthly_unit_basis',
                    'equip_monthly_target', 'equip_price_currency', 'equip_price',
                    'price_version_from', 'price_state', 'pricing_basis', 'price_source_text',
                    'shortfall_rule', 'mix_valid_from', 'container_key', 'target_source', 'notes'),
    'types' => array('client_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'monthly_unit_basis' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'price_version_from' => 'DATE NULL DEFAULT NULL',
                     'mix_valid_from' => 'DATE NULL DEFAULT NULL'),
    'dc' => array('equip_price' => 'DC-2', 'pricing_basis' => 'DC-2', 'price_state' => 'DC-2'),
),
array(
    'code' => 'sal_obligation_matrix', 'file' => 'contract_obligation_matrix.php', 'placement_id' => 13,
    'surface' => 'مصفوفة الالتزامات', 'title' => 'مصفوفة الالتزامات', 'icon' => 'fa fa-table-cells-large',
    'table' => 'contracts', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التعاقد والالتزام', 'sort_no' => 3,
    'grain' => 'عقدٌ واحدٌ — مصفوفةُ التزاماتِه سطرٌ واحد',
    'target_ref' => 'DEP-01·13·مصفوفه الالتزامات',
    'intro' => 'من يتحمّل ماذا في عقدِ العميل، وما الذي سكت عنه العقدُ صراحةً',
    'rule'  => 'حبّةُ المصفوفةِ **العقدُ نفسُه** فلا جدولَ ثانيَ له (§7) — والمسكوتُ عنه يُكتب مسكوتًا عنه لا فارغًا',
    'empty' => 'لا عقدَ مسجَّلٌ بعد',
    'where' => 'is_deleted = 0',
    'create' => array('client_no', 'client_name', 'business_model', 'obl_fuel', 'obl_oils',
                      'obl_maintenance', 'obl_spare_parts', 'obl_operators', 'obl_housing',
                      'obl_mobilization', 'obl_demobilization', 'obl_insurance', 'obl_damage',
                      'obl_waiting', 'obl_breakdown', 'obl_violations', 'obl_min_hours',
                      'obl_operating_guarantee', 'obl_site_schedule', 'obl_violation_deduction',
                      'obl_unpaid_stoppage', 'obl_termination', 'obl_renewal',
                      'obl_governing_law', 'obl_specific_bearing', 'obl_specific_terms',
                      'obl_silent_items'),
    'keys' => array('contract_code', 'client_no', 'client_name', 'business_model',
                    'contract_status', 'contract_evidence_level', 'obl_fuel', 'obl_oils',
                    'obl_maintenance', 'obl_spare_parts', 'obl_operators', 'obl_housing',
                    'obl_mobilization', 'obl_demobilization', 'obl_insurance', 'obl_damage',
                    'obl_waiting', 'obl_breakdown', 'obl_violations', 'obl_min_hours',
                    'obl_operating_guarantee', 'obl_site_schedule', 'obl_violation_deduction',
                    'obl_unpaid_stoppage', 'obl_termination', 'obl_renewal', 'obl_governing_law',
                    'obl_specific_bearing', 'obl_specific_terms', 'obl_silent_items',
                    'obl_fill_state', 'obl_evidence_level', 'obl_source_text',
                    'obl_derivation_basis', 'obl_notes'),
    'types' => array('client_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'contract_code' => 'VARCHAR(60) NULL DEFAULT NULL'),
    'dc' => array('obl_governing_law' => 'DC-3', 'obl_termination' => 'DC-3',
                  'obl_renewal' => 'DC-3', 'obl_specific_terms' => 'DC-3'),
),
array(
    'code' => 'sal_baseline_targets', 'file' => 'contract_baseline_targets.php', 'placement_id' => 14,
    'surface' => 'خط الأساس والمستهدفات', 'title' => 'خط الأساس والمستهدفات', 'icon' => 'fa fa-bullseye',
    'table' => 'contract_monthly_plan', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التعاقد والالتزام', 'sort_no' => 4,
    'grain' => 'عقدٌ × بندٌ × شهرٌ — سطرُ مستهدفٍ واحد',
    'target_ref' => 'DEP-01·14·خط الاساس والمستهدفات',
    'intro' => 'مستهدفاتُ الأشهرِ لكلِّ بندٍ بنسخةِ خطّتِها ومصدرِ مستهدفِها',
    'rule'  => 'نسخةُ الخطّةِ تُعلَن ولا تُدهَس — والمستهدفُ بمصدرِه لا بتقديرٍ (§18)',
    'empty' => 'لا سطرَ مستهدفٍ مسجَّلٌ بعد',
    'order' => 'period_month DESC, id DESC',
    'pk_code' => array('row_code', 'CBT'),
    'create' => array('container_key', 'contract_id', 'client_no', 'client_name',
                      'business_model', 'renewal_no', 'month_no', 'month_start', 'month_end',
                      'line_ref', 'unit_basis', 'line_monthly_target', 'full_monthly_target',
                      'uom_ref', 'plan_version', 'target_source'),
    'keys' => array('row_code', 'container_key', 'contract_id', 'client_no', 'client_name',
                    'business_model', 'renewal_no', 'month_no', 'month_start', 'month_end',
                    'line_ref', 'machines_count', 'unit_basis', 'line_monthly_target',
                    'full_monthly_target', 'uom_ref', 'plan_version', 'target_source', 'notes'),
    'types' => array('client_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'month_start' => 'DATE NULL DEFAULT NULL',
                     'month_end' => 'DATE NULL DEFAULT NULL',
                     'machines_count' => 'DECIMAL(12,3) NULL DEFAULT NULL',
                     'unit_basis' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'line_monthly_target' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'full_monthly_target' => 'DECIMAL(18,3) NULL DEFAULT NULL'),
),
array(
    'code' => 'sal_coverage_cycles', 'file' => 'contract_coverage_cycles.php', 'placement_id' => 15,
    'surface' => 'التغطية التعاقدية — دورات الالتزام', 'title' => 'التغطية التعاقدية — دورات الالتزام',
    'icon' => 'fa fa-arrows-spin',
    'table' => 'contract_commitments', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التعاقد والالتزام', 'sort_no' => 5,
    'grain' => 'دورةُ التزامٍ واحدةٌ على عقد',
    'target_ref' => 'DEP-01·15·التغطيه التعاقديه — دورات الالتزام',
    'intro' => 'دوراتُ الالتزامِ بسعتِها ومنفَّذِها وفجوةِ تغطيتِها ونسختِها السابقةِ وما تغيّر',
    'rule'  => 'فتحُ حاويةٍ جديدةٍ بسببٍ من قائمتِه — والنسخةُ السابقةُ تبقى بنصِّها (§18)',
    'empty' => 'لا دورةَ التزامٍ مسجَّلةٌ بعد',
    'where' => 'is_deleted = 0',
    'order' => 'valid_from DESC, id DESC',
    'create' => array('contract_ref', 'client_no', 'client_name', 'business_model',
                      'contract_no', 'renewal_no', 'cycle_kind', 'contractual_from',
                      'contractual_to', 'cycle_months', 'cycle_capacity', 'uom_ref',
                      'recorded_monthly_plan', 'executed_qty', 'measured_qty', 'coverage_gap',
                      'cycle_state', 'evidence_level', 'source_cycle_state', 'previous_version',
                      'version_kind', 'changed_vs_previous', 'cycle_pattern', 'measure_unit',
                      'slot_monthly_basis', 'min_guarantee', 'billing_threshold',
                      'new_container_reason'),
    'keys' => array('container_key', 'contract_ref', 'client_no', 'client_name',
                    'business_model', 'contract_no', 'renewal_no', 'cycle_kind',
                    'contractual_from', 'contractual_to', 'executive_from', 'executive_to',
                    'cycle_months', 'cycle_capacity', 'uom_ref', 'elapsed_target',
                    'recorded_monthly_plan', 'executed_qty', 'measured_qty', 'achievement_pct',
                    'coverage_gap', 'cycle_state', 'evidence_level', 'cycle_notes',
                    'source_cycle_state', 'previous_version', 'version_kind',
                    'changed_vs_previous', 'change_events_count', 'trips_derived',
                    'operating_hours_derived', 'cycle_pattern', 'measure_unit',
                    'contracted_machines_count', 'slot_monthly_basis', 'min_guarantee',
                    'billing_threshold', 'new_container_reason'),
    'types' => array('client_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'contractual_from' => 'DATE NULL DEFAULT NULL',
                     'contractual_to' => 'DATE NULL DEFAULT NULL',
                     'executive_from' => 'DATE NULL DEFAULT NULL',
                     'executive_to' => 'DATE NULL DEFAULT NULL',
                     'cycle_months' => 'DECIMAL(8,2) NULL DEFAULT NULL',
                     'cycle_capacity' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'elapsed_target' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'executed_qty' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'measured_qty' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'achievement_pct' => 'DECIMAL(8,2) NULL DEFAULT NULL',
                     'coverage_gap' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'change_events_count' => 'INT NULL DEFAULT NULL',
                     'trips_derived' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'operating_hours_derived' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'contracted_machines_count' => 'DECIMAL(12,3) NULL DEFAULT NULL',
                     'min_guarantee' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'billing_threshold' => 'DECIMAL(18,3) NULL DEFAULT NULL'),
    'dc' => array('min_guarantee' => 'DC-2', 'billing_threshold' => 'DC-2'),
),
array(
    'code' => 'sal_monthly_container', 'file' => 'monthly_containers_loss.php', 'placement_id' => 16,
    'surface' => 'الحاويات الشهرية والفاقد', 'title' => 'الحاويات الشهرية والفاقد',
    'icon' => 'fa fa-boxes-packing',
    'table' => 'sal_monthly_container', 'table_mode' => 'create', 'nature' => 'read',
    'group' => 'التعاقد والالتزام', 'sort_no' => 6,
    'grain' => 'دورةُ التزامٍ × شهرٌ — سطرُ حاويةٍ واحد',
    'target_ref' => 'DEP-01·16·الحاويات الشهريه والفاقد',
    'intro' => 'سعةُ الشهرِ ومنقضيه ومنفَّذه ونسبةُ تحققِه والفاقدُ الذي لا يُرحَّل',
    'rule'  => 'الفاقدُ لا يُرحَّل — والقاعدةُ في تعليقِ العمودِ لا في ذاكرةِ من يقرأ · وكلُّ حقلٍ مشتقٌّ فالسطحُ إسقاط (§19)',
    'empty' => 'لا سطرَ حاويةٍ شهريةٍ محسوبٌ بعد',
    'keys' => array('row_code', 'container_key', 'cycle_month_no', 'month_start', 'month_end',
                    'line_type', 'uom_ref', 'monthly_capacity_target', 'slot_monthly_basis',
                    'contract_units_count', 'elapsed_at_measure', 'executed_actual',
                    'achievement_pct', 'coverage_gap', 'loss_not_carried', 'partial_month_prorated',
                    'cycle_month_state'),
    'types' => array('month_start' => 'DATE NULL DEFAULT NULL',
                     'month_end' => 'DATE NULL DEFAULT NULL',
                     'cycle_month_no' => 'INT NULL DEFAULT NULL',
                     'monthly_capacity_target' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'slot_monthly_basis' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'contract_units_count' => 'DECIMAL(12,3) NULL DEFAULT NULL',
                     'elapsed_at_measure' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'executed_actual' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'achievement_pct' => 'DECIMAL(8,2) NULL DEFAULT NULL',
                     'coverage_gap' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'loss_not_carried' => 'DECIMAL(18,3) NULL DEFAULT NULL'),
),
array(
    'code' => 'sal_monthly_perf', 'file' => 'monthly_sales_performance.php', 'placement_id' => 17,
    'surface' => 'الأداء والمبيعات الشهرية', 'title' => 'الأداء والمبيعات الشهرية',
    'icon' => 'fa fa-chart-column',
    'table' => 'monthly_performance', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'الأداء والتحصيل', 'sort_no' => 1,
    'grain' => 'عقدٌ × بندٌ × شهرٌ — سطرُ أداءٍ ومبيعاتٍ واحد',
    'target_ref' => 'DEP-01·17·الاداء والمبيعات الشهريه',
    'intro' => 'المنفَّذُ والمنجزُ والإيرادُ المحسوبُ والمفوترُ وغيرُ المطالَبِ به شهرًا بشهر',
    'rule'  => 'الإيرادُ يُحسب من الكميةِ والسعرِ ولا يُدخَل — والمنفَّذُ غيرُ المفوترِ يُعرَض ولا يُطوى',
    'empty' => 'لا سطرَ أداءٍ شهريٍّ مسجَّلٌ بعد',
    'order' => 'period DESC, id DESC',
    'pk_code' => array('row_code', 'MSP'),
    'create' => array('container_key', 'contract_ref', 'client_no', 'client_name',
                      'business_model', 'renewal_no', 'month_no', 'month_from', 'month_to',
                      'line_ref', 'monthly_target', 'uom_ref', 'executed_achievement',
                      'measured_achievement', 'statement_source', 'unbilled_executed',
                      'unclaimed_revenue', 'invoice_ref', 'contract_currency',
                      'revenue_columns_state'),
    'keys' => array('row_code', 'container_key', 'contract_ref', 'client_no', 'client_name',
                    'business_model', 'renewal_no', 'month_no', 'month_from', 'month_to',
                    'line_ref', 'machines_count', 'monthly_target', 'executed_qty', 'uom_ref',
                    'operating_hours', 'trips_count', 'deducted_standby', 'deducted_work',
                    'added_work', 'added_standby', 'measured_qty', 'executed_achievement',
                    'measured_achievement', 'computed_revenue_usd', 'computed_revenue_sdg',
                    'statement_source', 'perf_notes', 'billed_qty', 'billed_usd',
                    'unbilled_executed', 'unclaimed_revenue', 'invoice_ref',
                    'contract_currency', 'revenue_columns_state'),
    'types' => array('client_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'month_from' => 'DATE NULL DEFAULT NULL',
                     'month_to' => 'DATE NULL DEFAULT NULL',
                     'machines_count' => 'DECIMAL(12,3) NULL DEFAULT NULL',
                     'monthly_target' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'executed_qty' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'measured_qty' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'operating_hours' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'trips_count' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'deducted_standby' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'deducted_work' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'added_work' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'added_standby' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'computed_revenue_usd' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'computed_revenue_sdg' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'billed_qty' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'billed_usd' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'unbilled_executed' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'unclaimed_revenue' => 'DECIMAL(18,2) NULL DEFAULT NULL'),
    'dc' => array('computed_revenue_usd' => 'DC-2', 'computed_revenue_sdg' => 'DC-2',
                  'billed_usd' => 'DC-2', 'unclaimed_revenue' => 'DC-2'),
),
array(
    'code' => 'sal_amendments', 'file' => 'contract_amendments_renewal.php', 'placement_id' => 19,
    'surface' => 'الملحقات والتجديد والإغلاق', 'title' => 'الملحقات والتجديد والإغلاق',
    'icon' => 'fa fa-file-pen',
    'table' => 'contract_amendments', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'الأداء والتحصيل', 'sort_no' => 3,
    'grain' => 'ملحقٌ أو تجديدٌ أو إغلاقٌ واحدٌ على عقد',
    'target_ref' => 'DEP-01·19·الملحقات والتجديد والاغلاق',
    'intro' => 'وثائقُ الملحقاتِ والتجديدِ والإغلاقِ بسريانِها التعاقديِّ والتنفيذيِّ وأثرِها على دوراتِ الالتزام',
    'rule'  => 'الملحقُ بعدَ الاعتمادِ لا يُدهَس — يُقيَّد وثيقةً جديدةً بأثرِها (الدستور §Amendment)',
    'empty' => 'لا ملحقَ مسجَّلٌ بعد',
    'where' => 'is_deleted = 0',
    'order' => 'amend_date DESC, id DESC',
    'create' => array('contract_id', 'client_no', 'client_name', 'doc_no', 'renewal_cycle',
                      'container_key', 'doc_text_adaptation', 'event_adaptation', 'signed_on',
                      'contractual_from', 'contractual_to', 'doc_target', 'uom_ref',
                      'cycles_effect', 'evidence_level', 'doc_state'),
    'keys' => array('amendment_code', 'contract_id', 'client_no', 'client_name', 'doc_no',
                    'renewal_cycle', 'container_key', 'doc_text_adaptation', 'event_adaptation',
                    'signed_on', 'contractual_from', 'contractual_to', 'executive_from',
                    'executive_to', 'doc_target', 'uom_ref', 'cycles_effect', 'evidence_level',
                    'doc_state', 'amend_notes'),
    'types' => array('client_no' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'signed_on' => 'DATE NULL DEFAULT NULL',
                     'contractual_from' => 'DATE NULL DEFAULT NULL',
                     'contractual_to' => 'DATE NULL DEFAULT NULL',
                     'executive_from' => 'DATE NULL DEFAULT NULL',
                     'executive_to' => 'DATE NULL DEFAULT NULL',
                     'doc_target' => 'DECIMAL(18,3) NULL DEFAULT NULL'),
),

));
