<?php
/**
 * tools/specs/dep02_suppliers.php — مواصفةُ `DEP-02` الموردون (GOV_EXEC §5)
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **الجداولُ العشرةُ قائمةٌ سلفًا** من هجرةِ `2027_12_07_repair01_sup_guide_tables`
 *   — لكنَّ أعمدتَها **مولَّدةٌ باسمٍ مبهم** (`c5` · `offer_22` · `month_14`):
 *   حقلُ الورقةِ في تعليقِ العمودِ ولا أثرَ له في اسمِه، فلا يُقرأ السطرُ إلا
 *   بقاموس. **والجداولُ فارغةٌ ولا كاتبَ لها** (فُتِّش: لا مرجعَ في شجرةِ
 *   الإنتاج غير هجرتِها) ⇒ **فالتسميةُ تُصحَّح**: تُنشأ الأعمدةُ المسمّاةُ
 *   وتُسقَط المبهمةُ، **والعكسُ يعيدها بتعريفِها الحرفيِّ المنتزَعِ من المخطَّط**.
 *   ⛔ ولا تُمسّ الأعمدةُ المسمّاةُ سلفًا (`no_supplier` · `date_offer` …) —
 *   فالتصحيحُ يطال المبهمَ وحدَه.
 */
return array(
    'dept'    => 'DEP-02',
    'dept_ar' => 'إدارة الموردين',
    'unit'    => 'إدارة الموردين',
    'role_id' => 2,
    'dir'     => 'suppliers',
    'neighbor_route' => 'suppliers/supplierscontracts.php',
    'screens' => array(

array(
    'code' => 'sup_offers', 'file' => 'supplier_offers.php', 'placement_id' => 27,
    'surface' => 'عروض الموردين والتفاوض', 'title' => 'عروض الموردين والتفاوض',
    'icon' => 'fa fa-comments-dollar',
    'table' => 'sup_offer_supplier_negotiation', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'التعاقد', 'sort_no' => 3,
    'grain' => 'عرضُ مورِّدٍ واحدٌ بنسختِه',
    'target_ref' => 'DEP-02·7·عروض الموردين والتفاوض',
    'intro' => 'عروضُ الموردين ونسخُ التفاوضِ عليها: ما تغيّر ومن اقترحه ومتى',
    'rule'  => 'كلُّ نسخةٍ تُقيَّد بأساسِها وبما تغيّر — ولا تُدهَس نسخةٌ سابقةٌ (§18)',
    'empty' => 'لا عرضَ مورِّدٍ مسجَّلٌ بعد',
    'order' => 'date_offer DESC, id DESC',
    'pk_code' => array('offer_code', 'SOF'),
    'create' => array('code_contract_supplier', 'no_supplier', 'name_supplier', 'business_model',
                      'offer_kind', 'version_no', 'base_version', 'changed_what', 'proposed_by',
                      'change_date', 'negotiation_state', 'currency_ref', 'payment_terms',
                      'execution_site', 'date_offer', 'competing_offers', 'required_guarantees'),
    'drop_cols' => array('c5', 'c8', 'c9', 'c10', 'c15', 'c16', 'c17', 'c18', 'c19', 'offer_22', 'offer_23'),
    'keys' => array('offer_code', 'code_contract_supplier', 'no_supplier', 'name_supplier',
                    'business_model', 'offer_kind', 'version_no', 'base_version', 'changed_what',
                    'proposed_by', 'change_date', 'negotiation_state', 'offered_line_types',
                    'line_count', 'offered_monthly_quota', 'min_unit_price', 'max_unit_price',
                    'currency_ref', 'payment_terms', 'execution_site', 'date_offer',
                    'offer_precedes', 'competing_offers', 'required_guarantees', 'record_basis',
                    'derivation_rule', 'confidence', 'needs_review', 'data_state', 'src_ref',
                    'notes'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'name_supplier' => 'VARCHAR(255) NULL DEFAULT NULL',
                     'min_unit_price' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'max_unit_price' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'offered_monthly_quota' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'line_count' => 'INT NULL DEFAULT NULL',
                     'version_no' => 'VARCHAR(40) NULL DEFAULT NULL',
                     'date_offer' => 'DATE NULL DEFAULT NULL'),
    'dc' => array('min_unit_price' => 'DC-2', 'max_unit_price' => 'DC-2',
                  'payment_terms' => 'DC-2', 'required_guarantees' => 'DC-3'),
),
array(
    'code' => 'sup_responsibility', 'file' => 'supplier_responsibility_matrix.php', 'placement_id' => 30,
    'surface' => 'مصفوفة المسؤوليات والتكاليف', 'title' => 'مصفوفة المسؤوليات والتكاليف',
    'icon' => 'fa fa-table-list',
    'table' => 'sup_responsibility', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التعاقد', 'sort_no' => 6,
    'grain' => 'مصفوفةُ مسؤولياتٍ واحدةٌ لعقدِ مورِّد',
    'target_ref' => 'DEP-02·10·مصفوفه المسؤوليات والتكاليف',
    'intro' => 'من يتحمّل ماذا في عقدِ المورِّد: الوقودُ والزيوتُ والصيانةُ والمشغّلُ والترحيلُ والتأمين',
    'rule'  => 'كلُّ بندٍ يُحسم بمرجعٍ من نصِّ العقدِ أو ملحقِه — والفراغُ ليس حكمًا',
    'empty' => 'لا مصفوفةَ معبَّأةٌ بعد',
    'pk_code' => array('matrix_code', 'SRM'),
    'create' => array('no_supplier', 'name_supplier', 'business_model', 'doc_adaptation',
                      'evidence_level', 'fuel', 'oils', 'maintenance', 'spare_parts',
                      'operator', 'housing_food', 'mobilization', 'demobilization', 'damage',
                      'waiting', 'stoppage', 'breakdown', 'insurance', 'violations',
                      'ref_contract_annex', 'filled_by', 'fill_date'),
    'drop_cols' => array('c4', 'c5', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'migration_14',
                         'c15', 'c16', 'c17', 'c18', 'c19', 'c20', 'c22', 'c24'),
    'keys' => array('matrix_code', 'no_supplier', 'name_supplier', 'business_model',
                    'doc_adaptation', 'evidence_level', 'fuel', 'oils', 'maintenance',
                    'spare_parts', 'operator', 'housing_food', 'mobilization', 'demobilization',
                    'damage', 'waiting', 'stoppage', 'breakdown', 'insurance', 'violations',
                    'decided_items_count', 'fill_state', 'ref_contract_annex', 'filled_by',
                    'fill_date', 'data_state', 'notes'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'name_supplier' => 'VARCHAR(255) NULL DEFAULT NULL',
                     'decided_items_count' => 'INT NULL DEFAULT NULL',
                     'fill_date' => 'DATE NULL DEFAULT NULL'),
),
array(
    'code' => 'sup_quota_dist', 'file' => 'supplier_quota_distribution.php', 'placement_id' => 31,
    'surface' => 'الخانات المكافئة وتوزيع الحصص', 'title' => 'الخانات المكافئة وتوزيع الحصص',
    'icon' => 'fa fa-scale-unbalanced',
    'table' => 'sup_slot_allocation_quota', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التشغيل', 'sort_no' => 1,
    'grain' => 'سطرُ توزيعِ حصّةٍ لمورِّدٍ في دورةِ التزامٍ سنوية',
    'target_ref' => 'DEP-02·11·الخانات المكافئه وتوزيع الحصص',
    'intro' => 'الوحداتُ التعاقديةُ المكافئةُ والممنوحةُ لكلِّ مورِّدٍ وفارقُ أكبرِ البواقي',
    'rule'  => 'الممنوحُ أعدادٌ صحيحةٌ والمكافئُ يُشتقّ — والفرقُ يُعرَض ولا يُسوّى بالكتابة',
    'empty' => 'لا سطرَ توزيعٍ مسجَّلٌ بعد',
    'pk_code' => array('dist_row_code', 'SQD'),
    'drop_cols' => array('c10', 'unit_11', 'c13', 'c14', 'c17', 'month_7'),
    'create' => array('granted_units', 'supplier_class', 'shared_slot_member', 'valid_from',
                      'dist_decision_ref', 'dist_state'),
    'keys' => array('dist_row_code', 'obligation_cycle_key', 'supplier_no_ref', 'supplier_name_ref',
                    'line_type_ref', 'monthly_unit_base', 'avg_monthly_executed',
                    'equivalent_units', 'granted_units', 'largest_remainder_gap',
                    'excess_machines', 'supplier_class', 'shared_slot_member',
                    'shared_contribution_pct', 'contractual_machines', 'actual_machines',
                    'contractual_vs_actual_gap', 'valid_from', 'dist_decision_ref', 'dist_state'),
    'types' => array('monthly_unit_base' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'avg_monthly_executed' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'equivalent_units' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'granted_units' => 'INT NULL DEFAULT NULL',
                     'largest_remainder_gap' => 'DECIMAL(18,4) NULL DEFAULT NULL',
                     'excess_machines' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'contractual_machines' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'actual_machines' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'contractual_vs_actual_gap' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'valid_from' => 'DATE NULL DEFAULT NULL'),
),
array(
    'code' => 'sup_handover', 'file' => 'supplier_slot_handover.php', 'placement_id' => 33,
    'surface' => 'سجل تسليم الخانات', 'title' => 'سجل تسليم الخانات', 'icon' => 'fa fa-people-arrows',
    'table' => 'sup_handover_slot', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التشغيل', 'sort_no' => 3,
    'grain' => 'إشغالُ وحدةٍ تعاقديةٍ واحدةٍ في مدّة',
    'target_ref' => 'DEP-02·13·سجل تسليم الخانات',
    'intro' => 'إشغالُ الوحداتِ التعاقديةِ ومن سلّمها لمن ومدّةُ إشغالِه وتحققُه',
    'rule'  => 'الشغورُ يحتاج توثيقًا ومبرِّرًا — والتناوبُ يُقسَم بنسبةِ مساهمةٍ مشتقّة',
    'empty' => 'لا إشغالَ مسجَّلٌ بعد',
    'pk_code' => array('occupancy_code', 'SHS'),
    'create' => array('no_supplier', 'occupancy_kind', 'from_date', 'to_date',
                      'documented_vacancy', 'vacancy_reason', 'decision_ref', 'occupancy_state'),
    'drop_cols' => array('date_9', 'c10', 'c12', 'supplier_15', 'c16', 'c17', 'c18', 'c20'),
    'keys' => array('occupancy_code', 'unit_code_ref', 'obligation_cycle_key', 'line_type_ref',
                    'no_supplier', 'supplier_name_ref', 'occupancy_kind', 'from_date', 'to_date',
                    'occupancy_months', 'period_target', 'period_executed', 'period_achievement',
                    'handing_supplier', 'receiving_supplier', 'documented_vacancy',
                    'vacancy_reason', 'rotation_contribution_pct', 'decision_ref',
                    'occupancy_state'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'from_date' => 'DATE NULL DEFAULT NULL', 'to_date' => 'DATE NULL DEFAULT NULL',
                     'occupancy_months' => 'DECIMAL(8,2) NULL DEFAULT NULL',
                     'period_target' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'period_executed' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'period_achievement' => 'DECIMAL(8,2) NULL DEFAULT NULL'),
),
array(
    'code' => 'sup_unit_equip', 'file' => 'supplier_unit_equipment.php', 'placement_id' => 34,
    'surface' => 'توزيع الوحدات التعاقدية على المعدات', 'title' => 'توزيع الوحدات التعاقدية على المعدات',
    'icon' => 'fa fa-truck-field',
    'table' => 'sup_allocation_unit_equipment', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التشغيل', 'sort_no' => 4,
    'grain' => 'إسنادُ معدّةٍ واحدةٍ إلى وحدةٍ تعاقديةٍ في مدّة',
    'target_ref' => 'DEP-02·14·توزيع الوحدات التعاقديه علي المعدات',
    'intro' => 'أيُّ معدّةٍ تشغل أيَّ وحدةٍ تعاقديةٍ ومتى وبأيِّ دورٍ وأثرُ ذلك على المنفَّذ',
    'rule'  => 'المنفَّذُ وساعاتُ المورِّدِ تُشتقّان من التشغيلِ — ولا تُدخَلان هنا',
    'empty' => 'لا إسنادَ مسجَّلٌ بعد',
    'pk_code' => array('assign_code', 'SUE'),
    'create' => array('slot_code', 'code_contract_supplier', 'no_supplier', 'equipment_code',
                      'line_type', 'plate_as_written', 'unit_type', 'from_date', 'to_date',
                      'assign_kind', 'unit_role', 'change_reason', 'readiness_event_ref',
                      'agreed_monthly_hours', 'mine_site', 'continuity', 'operating_status',
                      'assign_state'),
    'drop_cols' => array('c8', 'no_9', 'no_12', 'c14', 'c17', 'c18', 'type_19', 'c21', 'c23',
                         'c24', 'c25', 'c27', 'c29', 'c30', 'c34'),
    'keys' => array('assign_code', 'slot_code', 'code_contract_supplier', 'no_supplier',
                    'equipment_code', 'line_type', 'plate_as_written', 'plate_prefix',
                    'plate_number', 'unit_type', 'obligation_cycle_key', 'client_no',
                    'client_name', 'business_model', 'machine_no_client_contract',
                    'machine_no_supplier_contract', 'from_date', 'to_date', 'assign_kind',
                    'unit_role', 'change_reason', 'readiness_event_ref', 'active_months',
                    'work_days', 'executed_in_quota_unit', 'supplier_total_hours',
                    'agreed_monthly_hours', 'mine_site', 'continuity', 'operating_status',
                    'supplier_due_ref', 'supplier_contract_as_source', 'machine_assign_count',
                    'assign_state', 'notes'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'equipment_code' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'from_date' => 'DATE NULL DEFAULT NULL', 'to_date' => 'DATE NULL DEFAULT NULL',
                     'active_months' => 'DECIMAL(8,2) NULL DEFAULT NULL',
                     'work_days' => 'INT NULL DEFAULT NULL',
                     'executed_in_quota_unit' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'supplier_total_hours' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'agreed_monthly_hours' => 'DECIMAL(14,2) NULL DEFAULT NULL',
                     'supplier_due_ref' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'machine_assign_count' => 'INT NULL DEFAULT NULL'),
    'dc' => array('supplier_due_ref' => 'DC-2'),
),
array(
    'code' => 'sup_readiness', 'file' => 'supplier_readiness_reserve.php', 'placement_id' => 35,
    'surface' => 'الجاهزية والإحلال والاحتياط', 'title' => 'الجاهزية والإحلال والاحتياط',
    'icon' => 'fa fa-shuffle',
    'table' => 'sup_replacement_reserve', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التشغيل', 'sort_no' => 5,
    'grain' => 'حدثُ جاهزيةٍ أو إحلالٍ واحدٌ على وحدةٍ تعاقدية',
    'target_ref' => 'DEP-02·15·الجاهزيه والاحلال والاحتياط',
    'intro' => 'أحداثُ الجاهزيةِ والإحلالِ والاحتياطِ بقيمةِ ما قبلَها وما بعدَها ومستندِها',
    'rule'  => 'الحدثُ يُقيَّد بقيمتَيه قبلَ وبعد — فالتاريخُ يُقرأ ولا يُستنتَج (§18)',
    'empty' => 'لا حدثَ جاهزيةٍ مسجَّلٌ بعد',
    'order' => 'date DESC, id DESC',
    'pk_code' => array('event_code', 'SRR'),
    'create' => array('slot_code', 'business_model', 'no_month', 'event_date', 'event_name',
                      'unit_type', 'no_supplier', 'name_supplier', 'equipment_code',
                      'counterparty', 'from_reserve', 'value_before', 'value_after', 'doc_ref'),
    'drop_cols' => array('c4', 'c5', 'c8', 'c13', 'c14', 'c15', 'c16'),
    'keys' => array('event_code', 'obligation_cycle_key', 'slot_code', 'membership_test',
                    'business_model', 'no_month', 'event_date', 'event_name', 'unit_type',
                    'no_supplier', 'name_supplier', 'equipment_code', 'counterparty',
                    'from_reserve', 'value_before', 'value_after', 'name_doc', 'date_doc',
                    'doc_ref', 'notes'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'name_supplier' => 'VARCHAR(255) NULL DEFAULT NULL',
                     'no_month' => 'VARCHAR(20) NULL DEFAULT NULL',
                     'event_date' => 'DATE NULL DEFAULT NULL',
                     'equipment_code' => 'VARCHAR(60) NULL DEFAULT NULL'),
),
array(
    'code' => 'sup_onbehalf', 'file' => 'supplier_onbehalf_advances.php', 'placement_id' => 39,
    'surface' => 'النيابية والسلف والخصومات', 'title' => 'النيابية والسلف والخصومات',
    'icon' => 'fa fa-hand-holding-dollar',
    'table' => 'sup_onbehalf_advance_deduction', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'المالية', 'sort_no' => 1,
    'grain' => 'واقعةُ نيابةٍ أو سلفةٍ واحدةٌ على مورِّد',
    'target_ref' => 'DEP-02·19·النيابيه والسلف والخصومات',
    'intro' => 'ما دُفع نيابةً عن المورِّدِ ومن قدَّمه ومن دفعه ومن يتحمّله اقتصاديًّا',
    'rule'  => 'سلسلةُ النيابةِ ثلاثيّةٌ — Provided/Paid/Bearer — والمسترَدُّ والمتبقّي يُشتقّان',
    'empty' => 'لا واقعةَ نيابةٍ مسجَّلةٌ بعد',
    'order' => 'date DESC, id DESC',
    'pk_code' => array('onbehalf_code', 'SOB'),
    'create' => array('date', 'no_supplier', 'name_supplier', 'code_contract_supplier',
                      'unit_or_equipment_code', 'onbehalf_kind', 'operator_code', 'description',
                      'amount', 'currency_ref', 'provided_by', 'paid_by',
                      'economic_cost_bearer', 'recoverable', 'doc_evidence', 'disburse_approver',
                      'chain_state', 'offset_settlement_ref'),
    'drop_cols' => array('code_8', 'c9', 'c11', 'c15', 'amount_20', 'c21'),
    'keys' => array('onbehalf_code', 'date', 'no_supplier', 'name_supplier',
                    'code_contract_supplier', 'unit_or_equipment_code', 'onbehalf_kind',
                    'operator_code', 'description', 'amount', 'currency_ref', 'provided_by',
                    'paid_by', 'economic_cost_bearer', 'recoverable', 'doc_evidence',
                    'disburse_approver', 'chain_state', 'offset_settlement_ref',
                    'recovered_amount', 'remaining_amount', 'source_text', 'source_row_ref',
                    'data_state', 'notes'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'name_supplier' => 'VARCHAR(255) NULL DEFAULT NULL',
                     'recovered_amount' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'remaining_amount' => 'DECIMAL(18,2) NULL DEFAULT NULL'),
    'dc' => array('amount' => 'DC-2', 'recovered_amount' => 'DC-2', 'remaining_amount' => 'DC-2',
                  'economic_cost_bearer' => 'DC-2'),
),
array(
    'code' => 'sup_slot_closure', 'file' => 'supplier_slot_closure.php', 'placement_id' => 41,
    'surface' => 'الإقفال التعاقدي للوحدات التعاقدية', 'title' => 'الإقفال التعاقدي للوحدات التعاقدية',
    'icon' => 'fa fa-lock',
    'table' => 'sup_closure', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'المالية', 'sort_no' => 3,
    'grain' => 'إقفالٌ تعاقديٌّ واحدٌ لوحدةٍ تعاقديةٍ في فترة',
    'target_ref' => 'DEP-02·21·الاقفال التعاقدي للوحدات التعاقديه',
    'intro' => 'إقفالُ الوحدةِ التعاقديةِ للفترة: المتعاقدُ عليه والمنفَّذُ المعتمَدُ والفجوةُ ونسبةُ التحقق',
    'rule'  => 'الفجوةُ والقيمةُ التقديريةُ تُشتقّان من الأساسِ والسعرِ — ولا تُدخَلان',
    'empty' => 'لا إقفالَ تعاقديٌّ مسجَّلٌ بعد',
    'pk_code' => array('slot_close_code', 'SCC'),
    'create' => array('slot_code', 'code_contract_supplier', 'no_supplier', 'name_supplier',
                      'business_model', 'line_type', 'uom', 'period_kind', 'period_start',
                      'period_end', 'currency_ref', 'unit_state', 'monthly_close_ref',
                      'reviewer', 'approved_at'),
    'drop_cols' => array('c6', 'c8', 'c10', 'c11', 'c13', 'month_14', 'c15', 'c20', 'c22', 'c23', 'c24'),
    'keys' => array('slot_close_code', 'slot_code', 'code_contract_supplier', 'no_supplier',
                    'name_supplier', 'business_model', 'line_type', 'uom', 'period_kind',
                    'period_start', 'period_end', 'period_end_month_tag', 'period_months',
                    'contracted_monthly_base', 'contracted_for_period', 'approved_executed',
                    'gap_or_surplus', 'achievement_pct', 'months_with_performance',
                    'last_unit_activity', 'supplier_unit_price', 'currency_ref',
                    'estimated_period_value', 'unit_state', 'closure_state', 'monthly_close_ref',
                    'created_by', 'reviewer', 'approved_by', 'approved_at', 'record_basis',
                    'derivation_rule', 'data_state', 'notes'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'name_supplier' => 'VARCHAR(255) NULL DEFAULT NULL',
                     'period_start' => 'DATE NULL DEFAULT NULL',
                     'period_end' => 'DATE NULL DEFAULT NULL',
                     'period_months' => 'DECIMAL(8,2) NULL DEFAULT NULL',
                     'contracted_monthly_base' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'contracted_for_period' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'approved_executed' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'gap_or_surplus' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'achievement_pct' => 'DECIMAL(8,2) NULL DEFAULT NULL',
                     'months_with_performance' => 'INT NULL DEFAULT NULL'),
    'dc' => array('supplier_unit_price' => 'DC-2', 'estimated_period_value' => 'DC-2'),
),
array(
    'code' => 'sup_pay_alloc', 'file' => 'supplier_payment_allocation.php', 'placement_id' => 44,
    'surface' => 'تخصيص الدفع على الإقفالات', 'title' => 'تخصيص الدفع على الإقفالات',
    'icon' => 'fa fa-money-check',
    'table' => 'sup_allocation_payment_closure', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'المالية', 'sort_no' => 6,
    'grain' => 'تخصيصُ دفعةٍ واحدةٍ على إقفالٍ واحد',
    'target_ref' => 'DEP-02·24·تخصيص الدفع علي الاقفالات',
    'intro' => 'أيُّ مبلغٍ من طلبِ دفعٍ خُصِّص على أيِّ إقفالٍ وبأيِّ قاعدة',
    'rule'  => 'تجاوزُ صافي الشهرِ عَلَمٌ مشتقٌّ يُرفع ولا يُطفأ يدويًّا',
    'empty' => 'لا تخصيصَ دفعٍ مسجَّلٌ بعد',
    'order' => 'date_allocation DESC, id DESC',
    'pk_code' => array('alloc_code', 'SPA'),
    'create' => array('no_payment', 'no_supplier', 'no_closure', 'currency_ref',
                      'allocated_amount', 'date_allocation', 'allocation_rule'),
    'drop_cols' => array('c5'),
    'keys' => array('alloc_code', 'no_payment', 'no_supplier', 'no_closure', 'currency_ref',
                    'allocated_amount', 'date_allocation', 'allocation_rule', 'data_state',
                    'net_month_exceeded_flag'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'no_payment' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'no_closure' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'allocated_amount' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'date_allocation' => 'DATE NULL DEFAULT NULL'),
    'dc' => array('allocated_amount' => 'DC-2'),
),
array(
    'code' => 'sup_docs_guarantees', 'file' => 'supplier_docs_guarantees.php', 'placement_id' => 51,
    'surface' => 'سجل المستندات والضمانات', 'title' => 'سجل المستندات والضمانات',
    'icon' => 'fa fa-shield-halved',
    'table' => 'sup_doc_guarantee', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'المرجعيات', 'sort_no' => 1,
    'grain' => 'مستندٌ أو ضمانٌ واحدٌ لمورِّدٍ أو عقد',
    'target_ref' => 'DEP-02·31·سجل المستندات والضمانات',
    'intro' => 'مستنداتُ الموردين وضماناتُهم بنطاقِها وحالتِها وتاريخِ انتهائِها',
    'rule'  => 'المنتهي يوقف الأهليّةَ بأثرِه — والنطاقُ يُصرَّح عقدًا أو مورِّدًا لا يُظَنّ',
    'empty' => 'لا مستندَ مسجَّلٌ بعد',
    'order' => 'date_expiry ASC, id DESC',
    'pk_code' => array('doc_code', 'SDG'),
    'create' => array('type_doc', 'ref', 'no_supplier', 'name_supplier',
                      'doc_scope', 'doc_state', 'date_expiry'),
    'drop_cols' => array('c7'),
    'keys' => array('doc_code', 'type_doc', 'ref', 'no_supplier', 'name_supplier',
                    'doc_scope', 'doc_state', 'date_expiry', 'record_basis',
                    'source', 'data_state', 'notes'),
    'types' => array('no_supplier' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'name_supplier' => 'VARCHAR(255) NULL DEFAULT NULL'),
    'dc' => array('type_doc' => 'DC-3', 'doc_state' => 'DC-3'),
),

));
