<?php
/**
 * tools/specs/dep04_fleet.php — مواصفةُ بناءِ `DEP-04` الأسطولُ والأصول (GOV_EXEC §5)
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **حكمُ كلِّ سطحٍ مكتوبٌ هنا لا مولَّد**: أيُّ جدولٍ يملك حبّتَه، وأيُّ مفتاحٍ
 *   إنجليزيٍّ يقابل حقلَ الورقةِ العربيَّ **بترتيبِها لا بترتيبٍ آخر**. والاسمُ
 *   العربيُّ **لا يُكتب هنا مطلقًا** — يُقرأ من `repair01_fields` حرفًا، فلا
 *   نسختان تنجرفان (م 119 · درسُ «مصدرُ الحقيقةِ الواحد»).
 *
 * ◆ **ولا جدولَ موازٍ**: كلُّ حبّةٍ لها مالكٌ قائمٌ ⇒ `extend` لا `create`
 *   (`equipments` · `equipment_documents` · `fleet_equipment_component` ·
 *   `fleet_equipment_history` · `fleet_depreciation_profile` · `equipments_types`
 *   · `mnt_breakdown`). والدستورُ §7: «لا مصدرَ موازٍ».
 *
 * ◆ **وسطحُ إدارةٍ أخرى يُقرأ ولا يُكتب**: «سجل الأعطال والتوقفات» حبّتُه
 *   `mnt_breakdown` **مملوكةٌ للصيانة** — فالشاشةُ هنا `read` بلا فعلِ كتابةٍ
 *   واحد، فيبقى `UNCONTRACTED_CROSS_DOMAIN_WRITE = 0` (§17).
 *
 * ◆ **و«السجل اليومي للتشغيل» ليس التايم شيت**: حبّةُ التايم شيت
 *   **تشغيلةُ وحدةٍ** (`timesheet.operator` مُعرِّفُ تشغيلةٍ لا أصل — حكمُ W05
 *   المسجَّل)، وحبّةُ هذا السطحِ **أصلٌ × يومٌ × وردية**. فحبّتان لا حبّةٌ
 *   مكرَّرة، والنسبُ مكتوبٌ في تعليقِ الجدول.
 */
return array(
    'dept'    => 'DEP-04',
    'dept_ar' => 'إدارة الأسطول والأصول',
    'unit'    => 'إدارة الأسطول والأصول',
    'role_id' => 3,
    'dir'     => 'fleet',
    'neighbor_route' => 'fleet/asset_intake.php',
    'screens' => array(

/* ═══ أ · التعريف والسياسات ═══════════════════════════════════════════════ */
array(
    'code' => 'flt_power_sources', 'file' => 'power_sources.php', 'placement_id' => 77,
    'surface' => 'مصادر القدرة', 'title' => 'مصادر القدرة', 'icon' => 'fa fa-bolt',
    'table' => 'flt_power_source', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'أ · التعريف والسياسات', 'sort_no' => 1,
    'grain' => 'مصدرُ قدرةٍ واحدٌ — سطرٌ لكلِّ مصدر',
    'target_ref' => 'DEP-04·1·مصادر القدره',
    'intro' => 'مصادرُ القدرةِ وسياستُها: ما يُرسمَل وما يُهلَك وما يدخل سجلَّ الأسطول',
    'rule'  => 'مالكُ الحقيقةِ الماليةِ والتشغيليةِ مسمًّى لكلِّ مصدرٍ — ولا مصدرَ بلا مستندٍ حاكم',
    'empty' => 'لا مصدرَ قدرةٍ مسجَّلٌ بعدُ — سجّلِ الأولَ من نموذجِ الأفعالِ أعلاه',
    'pk_code' => array('source_code', 'PWS'),
    'create' => array('source_name', 'definition', 'is_capitalized', 'has_depreciation',
                      'in_fleet_register', 'governing_doc', 'accounting_ref',
                      'financial_owner', 'operational_owner', 'count_uom'),
    'keys' => array('source_code', 'source_name', 'definition', 'is_capitalized',
                    'has_depreciation', 'in_fleet_register', 'governing_doc', 'accounting_ref',
                    'financial_owner', 'operational_owner', 'current_count', 'count_uom'),
),
array(
    'code' => 'flt_class_dir', 'file' => 'classification_directory.php', 'placement_id' => 78,
    'surface' => 'دليل الترميز والتصنيف', 'title' => 'دليل الترميز والتصنيف', 'icon' => 'fa fa-barcode',
    'table' => 'equipments_types', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'أ · التعريف والسياسات', 'sort_no' => 2,
    'grain' => 'نوعُ معدّةٍ واحدٌ — سطرٌ لكلِّ رمزِ تصنيف',
    'target_ref' => 'DEP-04·2·دليل الترميز والتصنيف',
    'intro' => 'رمزُ التصنيفِ واسمُه بلغتَيه وفئتُه الرئيسيةُ والفرعيةُ وفئتُه المحاسبية',
    'rule'  => 'الترميزُ مصدرٌ واحدٌ لكلِّ الأسطح — ولا قائمةَ أنواعٍ ثانيةٌ تُنشأ',
    'empty' => 'لا نوعَ مسجَّلٌ بعدُ في دليلِ الترميز',
    'keys' => array('class_code', 'type_en', 'type', 'main_category', 'sub_category',
                    'policy_note', 'ifrs_class'),
    'dc' => array('ifrs_class' => 'DC-2'),
),

/* ═══ ب · دخول الأصل ═════════════════════════════════════════════════════ */
array(
    'code' => 'flt_inspection_card', 'file' => 'inspection_card.php', 'placement_id' => 82,
    'surface' => 'بطاقة التفتيش', 'title' => 'بطاقة التفتيش', 'icon' => 'fa fa-clipboard-check',
    'table' => 'flt_inspection_card', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'ب · دخول الأصل', 'sort_no' => 4,
    'grain' => 'بطاقةُ تفتيشٍ واحدةٌ — أصلٌ × أمرُ تفتيش',
    'target_ref' => 'DEP-04·6·بطاقه التفتيش',
    'intro' => 'نتيجةُ التفتيشِ عنصرًا عنصرًا: المحركُ والهيدروليكُ والفرامل — وأثرُها على الحالةِ الفنية',
    'rule'  => 'البطاقةُ تتبع أمرَ تفتيشٍ قائمًا — والنتيجةُ تُغيِّر الحالةَ الفنيةَ بمرجعِها لا بلا سند',
    'empty' => 'لا بطاقةَ تفتيشٍ مسجَّلةٌ بعدُ — البطاقةُ تُفتح على أمرِ تفتيشٍ قائم',
    'pk_code' => array('card_no', 'INSP'),
    'create' => array('order_ref', 'asset_code', 'inspector', 'start_date', 'meter_reading',
                      'inspection_result', 'technical_notes', 'resulting_action'),
    'keys' => array('card_no', 'order_ref', 'asset_code', 'inspection_type', 'inspector',
                    'executor_party', 'start_date', 'start_time', 'end_date', 'end_time',
                    'location', 'project_ref', 'meter_reading', 'last_meter', 'hours_since_last',
                    'engine_state', 'hydraulic_state', 'transmission_state', 'electrical_state',
                    'brakes_state', 'tires_tracks_state', 'body_state', 'cabin_state',
                    'safety_state', 'leaks_state', 'type_specific_items', 'change_vs_last',
                    'change_desc', 'operator_at_event', 'operator_liability', 'investigation_ref',
                    'inspection_result', 'technical_notes', 'resulting_action', 'work_order_no',
                    'breakdown_ref', 'technical_state_effect', 'report_attachment',
                    'photos_attachment', 'created_by', 'created_at', 'reviewer', 'review_date',
                    'approved_by', 'approved_at', 'record_basis', 'src_ref', 'data_state'),
    'types' => array('asset_code' => 'VARCHAR(80) NULL DEFAULT NULL',
                     'hours_since_last' => 'DECIMAL(12,2) NULL DEFAULT NULL'),
),
array(
    'code' => 'flt_asset_card', 'file' => 'asset_card.php', 'placement_id' => 83,
    'surface' => 'كرت الأصل', 'title' => 'كرت الأصل', 'icon' => 'fa fa-id-card',
    'table' => 'equipments', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'ب · دخول الأصل', 'sort_no' => 5,
    'grain' => 'أصلٌ واحدٌ — سطرٌ لكلِّ معدّة',
    'target_ref' => 'DEP-04·7·كرت الاصل',
    'intro' => 'الكرتُ سجلُّ الأصلِ الجامعُ: هويتُه وملكيتُه وتواريخُه وعدّادُه وحجيةُ ملفِّه',
    'rule'  => 'الكرتُ مصدرُ الحقيقةِ للأصل — والمستوردُ من إدارةٍ أخرى يُقرأ ولا يُحرَّر هنا',
    'empty' => 'لا أصلَ مسجَّلٌ بعدُ في سجلِّ الأسطول',
    'keys' => array('code', 'class_code', 'old_code_main', 'old_code_alt', 'project_asset_code',
                    'power_source_code', 'source_type', 'purchase_state', 'actual_owner_name',
                    'owner_type', 'supplier_code', 'supplier_contract_ref', 'finance_ref',
                    'name', 'manufacturer', 'model', 'manufacturing_year', 'capacity',
                    'operating_category', 'ifrs_class', 'chassis_number', 'chassis_state',
                    'engine_no', 'plate_no', 'sticker_no', 'parent_asset_code', 'link_type',
                    'purchase_date', 'receipt_date', 'entry_date', 'entry_basis',
                    'first_operation_site', 'availability_state', 'technical_class',
                    'current_project', 'current_location', 'operating_party', 'current_unit_key',
                    'opening_meter', 'last_meter_reading', 'last_meter_date', 'operating_hours',
                    'meter_source', 'capacity_ref', 'exit_date', 'exit_reason', 'exit_record_ref',
                    'evidence_level', 'file_completeness_pct', 'missing_links',
                    'verification_state', 'exception_flag', 'confidence_grade', 'created_by',
                    'created_at', 'reviewer', 'card_approved_by', 'card_approved_at',
                    'record_basis', 'card_src_ref', 'card_data_state', 'general_notes'),
    'types' => array('missing_links' => 'VARCHAR(500) NULL DEFAULT NULL',
                     'capacity_ref' => 'VARCHAR(120) NULL DEFAULT NULL'),
    'dc' => array('finance_ref' => 'DC-2', 'ifrs_class' => 'DC-2', 'purchase_state' => 'DC-2'),
),
array(
    'code' => 'flt_asset_docs', 'file' => 'asset_documents.php', 'placement_id' => 84,
    'surface' => 'مستندات الأصل', 'title' => 'مستندات الأصل', 'icon' => 'fa fa-folder-open',
    'table' => 'equipment_documents', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'ب · دخول الأصل', 'sort_no' => 6,
    'grain' => 'مستندٌ واحدٌ لأصلٍ واحد',
    'target_ref' => 'DEP-04·8·مستندات الاصل',
    'intro' => 'مستنداتُ الأصلِ بتواريخِ إصدارِها وانتهائِها ومسؤولِ تجديدِها',
    'rule'  => 'الإلزاميُّ منها شرطُ تشغيل — والمنتهي يوقف الأهليةَ بأثرِه لا بتذكيرٍ فقط',
    'empty' => 'لا مستندَ مسجَّلٌ لهذا الأصلِ بعد',
    'where' => "subject_type = 'equipment' AND is_deleted = 0",
    'keys' => array('doc_id', 'subject_id', 'doc_type', 'is_mandatory', 'issuer', 'doc_no',
                    'issue_date', 'expiry_date', 'days_to_expiry', 'status', 'coverage_value',
                    'bearer_party', 'storage_place', 'file_ref', 'renewal_owner', 'created_by',
                    'created_at', 'reviewer', 'approved_by', 'approved_at', 'record_basis',
                    'src_ref', 'data_state', 'note'),
    'dc' => array('coverage_value' => 'DC-2', 'bearer_party' => 'DC-3'),
),
array(
    'code' => 'flt_components', 'file' => 'asset_components.php', 'placement_id' => 86,
    'surface' => 'المكونات والملحقات', 'title' => 'المكونات والملحقات', 'icon' => 'fa fa-puzzle-piece',
    'table' => 'fleet_equipment_component', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'ب · دخول الأصل', 'sort_no' => 8,
    'grain' => 'مكوّنٌ واحدٌ على أصلٍ واحد',
    'target_ref' => 'DEP-04·10·المكونات والملحقات',
    'intro' => 'مكوناتُ الأصلِ وملحقاتُه بعمرِها المتوقَّعِ ونسبةِ استهلاكِها وقرارِ رسملتِها',
    'rule'  => 'المكوّنُ المرسمَلُ يحتاج مرجعَ قرارٍ — والفكُّ بسببِه ونقلُه إلى أصلٍ مسمًّى',
    'empty' => 'لا مكوّنَ مسجَّلٌ بعد',
    'pk_code' => array('component_code', 'CMP'),
    'create' => array('equipment_id', 'component_type', 'description', 'manufacturer',
                      'serial_no', 'install_date', 'meter_at_install', 'expected_life_hours'),
    'keys' => array('component_code', 'equipment_id', 'component_type', 'description',
                    'manufacturer', 'serial_no', 'install_date', 'meter_at_install',
                    'expected_life_hours', 'current_meter', 'component_hours', 'consumption_pct',
                    'replace_date', 'removal_reason', 'moved_to_asset', 'work_order_ref',
                    'is_capitalized', 'capitalization_ref', 'created_by', 'created_at',
                    'reviewer', 'approved_by', 'approved_at', 'record_basis', 'src_ref',
                    'data_state', 'notes'),
    'types' => array('expected_life_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL'),
    'dc' => array('is_capitalized' => 'DC-2', 'capitalization_ref' => 'DC-2'),
),

/* ═══ د · الحركة والاستخدام ═══════════════════════════════════════════════ */
array(
    'code' => 'flt_daily_log', 'file' => 'daily_operating_log.php', 'placement_id' => 90,
    'surface' => 'السجل اليومي للتشغيل', 'title' => 'السجل اليومي للتشغيل', 'icon' => 'fa fa-calendar-day',
    'table' => 'flt_daily_operating_log', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'د · الحركة والاستخدام', 'sort_no' => 2,
    'grain' => 'أصلٌ × يومٌ × وردية — سطرٌ واحد',
    'target_ref' => 'DEP-04·14·السجل اليومي للتشغيل',
    'intro' => 'يومُ الأصلِ بالساعاتِ والعدّادِ وثمانيةِ أبوابِ التوقفِ بمسمّياتِها',
    'rule'  => 'حبّتُه أصلٌ لا تشغيلةُ وحدة — والتايم شيت حبّةٌ أخرى لا نسخةٌ منه (حكمُ W05)',
    'empty' => 'لا يومَ تشغيلٍ مسجَّلٌ بعدُ لهذا الأصل',
    'pk_code' => array('log_code', 'DOL'),
    'create' => array('asset_code', 'log_date', 'shift', 'operator_no', 'meter_start',
                      'meter_end', 'work_hours', 'standby_hours', 'data_entry_by'),
    'keys' => array('log_code', 'asset_code', 'log_date', 'shift', 'operator_no', 'unit_key',
                    'project_ref', 'site_ref', 'meter_start', 'meter_end', 'meter_diff',
                    'work_hours', 'standby_hours', 'stop_maintenance', 'stop_operational',
                    'stop_no_operator', 'stop_site_client', 'stop_fuel', 'stop_transfer',
                    'stop_parts_wait', 'stop_other', 'stop_total', 'day_total_hours',
                    'tons_moved', 'meters_done', 'fuel_issued', 'breakdown_ref', 'data_entry_by',
                    'confidence_grade', 'approval_state', 'created_by', 'created_at', 'reviewer',
                    'review_date', 'approved_by', 'approved_at', 'record_basis', 'src_ref',
                    'data_state'),
    'types' => array('work_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'standby_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL'),
),

/* ═══ هـ · الرقابة الفنية ═══════════════════════════════════════════════ */
array(
    'code' => 'flt_tech_state', 'file' => 'technical_state.php', 'placement_id' => 92,
    'surface' => 'الحالة الفنية', 'title' => 'الحالة الفنية', 'icon' => 'fa fa-gauge-high',
    'table' => 'flt_technical_state', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'هـ · الرقابة الفنية', 'sort_no' => 1,
    'grain' => 'أصلٌ واحدٌ — حالتُه الفنيةُ الجاريةُ سطرٌ واحد',
    'target_ref' => 'DEP-04·16·الحاله الفنيه',
    'intro' => 'التصنيفُ الفنيُّ للأصلِ بمؤشراتِه: الجاهزيةُ والأعطالُ والتكلفةُ إلى القيمة',
    'rule'  => 'المرشَّحةُ للاستبدالِ تحتاج مبرِّرًا مكتوبًا وقرارَ إدارةٍ — ولا ترشيحَ صامت',
    'empty' => 'لا حالةَ فنيةٌ مقيَّدةٌ بعدُ لأيِّ أصل',
    'create' => array('asset_code', 'technical_class', 'last_assessment_date', 'class_reason',
                      'required_action', 'replacement_candidate', 'candidacy_reason'),
    'keys' => array('asset_code', 'technical_class', 'last_assessment_date',
                    'last_inspection_ref', 'operating_age_years', 'accumulated_hours',
                    'capacity_consumption_pct', 'failures_12m', 'downtime_hours_12m',
                    'readiness_pct', 'maintenance_cost_total', 'cost_to_value_pct',
                    'class_reason', 'required_action', 'replacement_candidate',
                    'candidacy_reason', 'management_decision', 'created_by', 'created_at',
                    'reviewer', 'approved_by', 'approved_at', 'record_basis', 'src_ref',
                    'data_state'),
    'types' => array('downtime_hours_12m' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'failures_12m' => 'INT NULL DEFAULT NULL'),
    'dc' => array('maintenance_cost_total' => 'DC-2', 'cost_to_value_pct' => 'DC-2'),
),
array(
    'code' => 'flt_state_history', 'file' => 'state_change_log.php', 'placement_id' => 93,
    'surface' => 'سجل تغير الحالة', 'title' => 'سجل تغير الحالة', 'icon' => 'fa fa-clock-rotate-left',
    'table' => 'fleet_equipment_history', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'هـ · الرقابة الفنية', 'sort_no' => 2,
    'grain' => 'واقعةُ تغيُّرِ حالةٍ واحدةٌ على أصل',
    'target_ref' => 'DEP-04·17·سجل تغير الحاله',
    'intro' => 'كلُّ تحوّلِ حالةٍ بسببِه وواقعتِه ومدةِ الحالةِ السابقة — تاريخٌ لا يُدهَس',
    'rule'  => 'السجلُّ إلحاقيٌّ: الحالةُ الجديدةُ صفٌّ جديدٌ والقديمةُ تبقى (§18 Current vs History)',
    'empty' => 'لا واقعةَ تغيُّرِ حالةٍ مسجَّلةٌ بعد',
    'order' => 'event_date DESC, id DESC',
    'pk_code' => array('change_no', 'CHG'),
    'keys' => array('change_no', 'equipment_id', 'change_seq', 'event_date', 'change_time',
                    'event_type', 'from_value', 'to_value', 'change_reason', 'cause_event',
                    'prev_state_days', 'meter_reading', 'changed_by_name', 'approved_by',
                    'created_by', 'created_at', 'reviewer', 'approved_at', 'record_basis',
                    'src_ref', 'data_state'),
),
array(
    'code' => 'flt_breakdown_log', 'file' => 'breakdown_log.php', 'placement_id' => 94,
    'surface' => 'سجل الأعطال والتوقفات', 'title' => 'سجل الأعطال والتوقفات', 'icon' => 'fa fa-triangle-exclamation',
    'table' => 'mnt_breakdown', 'table_mode' => 'extend', 'nature' => 'read',
    'group' => 'هـ · الرقابة الفنية', 'sort_no' => 3,
    'grain' => 'عطلٌ واحدٌ على أصلٍ واحد',
    'target_ref' => 'DEP-04·18·سجل الاعطال والتوقفات',
    'intro' => 'أعطالُ الأسطولِ ونوافذُ توقفِها وتشخيصُها وسببُها الجذريُّ والطرفُ المتحمِّل',
    'rule'  => 'حبّةُ العطلِ مملوكةٌ للصيانة — فهذه الشاشةُ تقرأ ولا تكتب (§17)',
    'empty' => 'لا عطلَ مسجَّلٌ بعدُ على أصولِ الأسطول',
    'where' => 'is_deleted = 0',
    'order' => 'report_datetime DESC, id DESC',
    'keys' => array('code', 'equipment_id', 'failure_start_date', 'failure_start_time',
                    'discovery_source', 'report_ref', 'reported_by', 'operator_at_failure',
                    'site_location', 'project_id', 'unit_key', 'meter_reading', 'description',
                    'failure_code_id', 'severity', 'is_stopped', 'downtime_start',
                    'referred_to_maintenance', 'referral_date', 'order_id', 'diagnosis',
                    'root_cause', 'return_service_date', 'return_service_ref', 'downtime_end',
                    'downtime_hours', 'operator_liability', 'investigation_ref', 'bearer_party',
                    'state', 'created_by', 'created_at', 'reviewer', 'review_date',
                    'approved_by', 'approved_at', 'record_basis', 'src_ref', 'data_state'),
    'types' => array('downtime_start' => 'DATETIME NULL DEFAULT NULL',
                     'downtime_end' => 'DATETIME NULL DEFAULT NULL'),
),

/* ═══ ز · الاستثناءات والقرارات ═══════════════════════════════════════════ */
array(
    'code' => 'flt_exceptions', 'file' => 'exception_register.php', 'placement_id' => 99,
    'surface' => 'سجل الاستثناءات', 'title' => 'سجل الاستثناءات', 'icon' => 'fa fa-circle-exclamation',
    'table' => 'flt_exception_register', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ز · الاستثناءات والقرارات', 'sort_no' => 1,
    'grain' => 'استثناءٌ واحدٌ بأصولِه المتأثرة',
    'target_ref' => 'DEP-04·23·سجل الاستثناءات',
    'intro' => 'استثناءاتُ الأسطولِ بخطورتِها وإجرائِها الموصى ومسؤولِها وتاريخِ استحقاقِها',
    'rule'  => 'لا استثناءَ يُغلَق بلا نصِّ «كيف حُسم» ومعتمِدٍ مسمًّى',
    'empty' => 'لا استثناءَ مسجَّلٌ بعد',
    'pk_code' => array('exception_no', 'EXC'),
    'create' => array('exception_type', 'description', 'affected_assets', 'severity',
                      'recommended_action', 'owner_name', 'accounting_legal_impact',
                      'state', 'due_date'),
    'keys' => array('exception_no', 'exception_type', 'description', 'affected_assets',
                    'severity', 'recommended_action', 'owner_name', 'accounting_legal_impact',
                    'state', 'due_date', 'closed_date', 'resolution', 'approved_by'),
),
array(
    'code' => 'flt_ext_auditor', 'file' => 'external_auditor_notes.php', 'placement_id' => 100,
    'surface' => 'ملاحظات المراجع الخارجي', 'title' => 'ملاحظات المراجع الخارجي', 'icon' => 'fa fa-user-shield',
    'table' => 'flt_external_auditor_note', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ز · الاستثناءات والقرارات', 'sort_no' => 2,
    'grain' => 'ملاحظةُ مراجعٍ خارجيٍّ واحدةٌ',
    'target_ref' => 'DEP-04·24·ملاحظات المراجع الخارجي',
    'intro' => 'ملاحظاتُ المراجعِ الخارجيِّ على الأسطولِ بإجرائِها ومسؤولِها المقترحِ وتاريخِها المستهدَف',
    'rule'  => 'الملاحظةُ تبقى مفتوحةً حتى يُسجَّل إجراؤها — ولا تُطوى بلا أثر',
    'empty' => 'لا ملاحظةَ مراجعٍ خارجيٍّ مسجَّلةٌ بعد',
    'create' => array('item_no', 'severity', 'category', 'item_or_asset', 'problem_desc',
                      'required_action', 'proposed_owner', 'target_date', 'accounting_impact'),
    'keys' => array('item_no', 'severity', 'category', 'item_or_asset', 'problem_desc',
                    'required_action', 'proposed_owner', 'target_date', 'accounting_impact'),
    'dc' => array('accounting_impact' => 'DC-2'),
),
array(
    'code' => 'flt_src_conflicts', 'file' => 'source_conflicts.php', 'placement_id' => 101,
    'surface' => 'التضاربات بين المصادر', 'title' => 'التضاربات بين المصادر', 'icon' => 'fa fa-code-compare',
    'table' => 'flt_source_conflict', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ز · الاستثناءات والقرارات', 'sort_no' => 3,
    'grain' => 'تضاربٌ واحدٌ بين مصدرَين على عينٍ واحدة',
    'target_ref' => 'DEP-04·25·التضاربات بين المصادر',
    'intro' => 'موضعُ التضاربِ ومصدراه وقيمتاهما والفرقُ والترجيحُ والتصحيحُ المطلوب',
    'rule'  => 'الترجيحُ يُكتب بسندِه — ولا يُحسَم تضاربٌ اجتهادًا بلا مصدرٍ حاكم (§2)',
    'empty' => 'لا تضاربَ مسجَّلٌ بين المصادرِ بعد',
    'create' => array('asset_code', 'conflict_point', 'source_one', 'value_one', 'source_two',
                      'value_two', 'difference', 'preference', 'required_fix', 'severity'),
    'keys' => array('asset_code', 'conflict_point', 'source_one', 'value_one', 'source_two',
                    'value_two', 'difference', 'preference', 'required_fix', 'severity'),
),
array(
    'code' => 'flt_open_points', 'file' => 'open_points.php', 'placement_id' => 102,
    'surface' => 'النقاط غير المحسومة', 'title' => 'النقاط غير المحسومة', 'icon' => 'fa fa-circle-question',
    'table' => 'flt_open_point', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ز · الاستثناءات والقرارات', 'sort_no' => 4,
    'grain' => 'نقطةٌ واحدةٌ غيرُ محسومةٍ بمصدرِها وصفِّها',
    'target_ref' => 'DEP-04·26·النقاط غير المحسومه',
    'intro' => 'كلُّ نقطةٍ لم تحسمْها المصادرُ بموضعِها في الشيتِ والصفِّ والحقلِ المتأثر',
    'rule'  => 'النقطةُ لا تُغلَق إلا بقرارٍ معتمَدٍ ومرجعِ مستندٍ وتاريخِ حسمٍ (§8)',
    'empty' => 'لا نقطةَ غيرَ محسومةٍ مسجَّلةٌ بعد',
    'pk_code' => array('point_no', 'PNT'),
    'create' => array('source', 'sheet_name', 'row_no', 'asset_code', 'operation_code',
                      'affected_field', 'current_value', 'problem_type', 'note_text',
                      'severity', 'responsible_party', 'required_action', 'state'),
    'keys' => array('point_no', 'source', 'sheet_name', 'row_no', 'asset_code',
                    'operation_code', 'financier', 'finance_type', 'affected_field',
                    'current_value', 'problem_type', 'note_text', 'severity',
                    'responsible_party', 'required_action', 'state', 'approved_decision',
                    'document_ref', 'approved_by', 'resolved_date'),
    'types' => array('current_value' => 'VARCHAR(255) NULL DEFAULT NULL'),
),
array(
    'code' => 'flt_mgmt_decisions', 'file' => 'management_decisions.php', 'placement_id' => 103,
    'surface' => 'حزمة القرارات الإدارية', 'title' => 'حزمة القرارات الإدارية', 'icon' => 'fa fa-gavel',
    'table' => 'flt_management_decision', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ز · الاستثناءات والقرارات', 'sort_no' => 5,
    'grain' => 'قرارٌ إداريٌّ واحدٌ بخيارَيه',
    'target_ref' => 'DEP-04·27·حزمه القرارات الاداريه',
    'intro' => 'القرارُ المطلوبُ ودليلُه وخياراه وأثرُ كلٍّ والتوصيةُ الفنيةُ ومهلتُه',
    'rule'  => 'الخياران بأثرَيهما مكتوبان قبلَ القرار — ولا قرارَ بلا معتمِدٍ وتاريخ',
    'empty' => 'لا قرارَ إداريٌّ مسجَّلٌ بعد',
    'pk_code' => array('decision_no', 'DEC'),
    'create' => array('requested_decision', 'evidence_current_state', 'option_a', 'option_b',
                      'technical_recommendation', 'owner_name', 'deadline'),
    'keys' => array('decision_no', 'requested_decision', 'evidence_current_state', 'option_a',
                    'option_b', 'technical_recommendation', 'owner_name', 'deadline',
                    'approved_decision', 'decision_date', 'approved_by'),
),

/* ═══ اللوحة — خارج الدورة ═══════════════════════════════════════════════ */
array(
    'code' => 'flt_board', 'file' => 'fleet_board.php', 'placement_id' => 105,
    'surface' => 'لوحة الأسطول', 'title' => 'لوحة الأسطول', 'icon' => 'fa fa-chart-line',
    'table' => 'flt_dashboard_kpi', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'اللوحة — خارج الدورة (Overview)', 'sort_no' => 1,
    'grain' => 'مؤشرٌ واحدٌ في لوحةِ الأسطول',
    'target_ref' => 'DEP-04·29·لوحه الاسطول',
    'intro' => 'مؤشراتُ الأسطولِ بقيمِها ووحداتِها وشيتِها المصدرِ وحدِّها المقبول',
    'rule'  => 'اللوحةُ إسقاطٌ لا مصدرَ حقيقة — ولكلِّ مؤشرٍ شيتُه المصدرُ مسمًّى (§19)',
    'empty' => 'لا مؤشرَ معرَّفٌ بعدُ في لوحةِ الأسطول',
    'create' => array('indicator', 'uom', 'source_sheet', 'acceptable_limit'),
    'keys' => array('indicator', 'value', 'uom', 'source_sheet', 'acceptable_limit', 'state'),
    'types' => array('acceptable_limit' => 'VARCHAR(120) NULL DEFAULT NULL',
                     'value' => 'DECIMAL(18,2) NULL DEFAULT NULL'),
),

/* ═══ ط · المرجعيات والمصالحة ═══════════════════════════════════════════ */
array(
    'code' => 'flt_life_reference', 'file' => 'asset_life_reference.php', 'placement_id' => 107,
    'surface' => 'مرجع العمر الإنتاجي بالساعات', 'title' => 'مرجع العمر الإنتاجي بالساعات', 'icon' => 'fa fa-hourglass-half',
    'table' => 'fleet_depreciation_profile', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'ط · المرجعيات والمصالحة', 'sort_no' => 1,
    'grain' => 'فئةُ أصولٍ واحدةٌ — عمرُها الإنتاجيُّ وطريقةُ إهلاكِها',
    'target_ref' => 'DEP-04·31·مرجع العمر الانتاجي بالساعات',
    'intro' => 'العمرُ الإنتاجيُّ لكلِّ فئةٍ وطريقةُ إهلاكِها ونسبةُ قيمتِها المتبقيةِ ومصدرُها المعياري',
    'rule'  => 'القيمُ من السياسةِ المعتمَدةِ لا من الشاشة — والمصدرُ المعياريُّ مكتوبٌ لكلِّ فئة (§7)',
    'empty' => 'لا فئةَ مرجعيّةٌ مسجَّلةٌ بعد',
    'where' => 'is_deleted = 0',
    'keys' => array('code', 'asset_category', 'method', 'useful_life', 'salvage_pct',
                    'rate_basis', 'standard_source', 'notes'),
    'dc' => array('method' => 'DC-2', 'useful_life' => 'DC-2', 'salvage_pct' => 'DC-2'),
),
array(
    'code' => 'flt_use_right_ranges', 'file' => 'use_right_ranges.php', 'placement_id' => 108,
    'surface' => 'نطاقات حق الاستخدام', 'title' => 'نطاقات حق الاستخدام', 'icon' => 'fa fa-arrows-left-right-to-line',
    'table' => 'flt_use_right_range', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ط · المرجعيات والمصالحة', 'sort_no' => 2,
    'grain' => 'نطاقُ ترقيمٍ واحدٌ لحالةِ ملكية',
    'target_ref' => 'DEP-04·32·نطاقات حق الاستخدام',
    'intro' => 'نطاقاتُ الترقيمِ لكلِّ حالةِ ملكيةٍ — من وإلى وشرحُ النطاق',
    'rule'  => 'النطاقُ يفصل حالاتِ الملكيةِ بالترقيمِ — ولا تداخلَ بين نطاقَين',
    'empty' => 'لا نطاقَ مسجَّلٌ بعد',
    'create' => array('ownership_state', 'range_from', 'range_to', 'explanation'),
    'keys' => array('ownership_state', 'range_from', 'range_to', 'explanation'),
    'types' => array('range_from' => 'VARCHAR(80) NULL DEFAULT NULL',
                     'range_to' => 'VARCHAR(80) NULL DEFAULT NULL'),
),
array(
    'code' => 'flt_code_recon', 'file' => 'code_reconciliation.php', 'placement_id' => 109,
    'surface' => 'مصالحة مطابقة الأكواد', 'title' => 'مصالحة مطابقة الأكواد', 'icon' => 'fa fa-right-left',
    'table' => 'flt_code_reconciliation', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ط · المرجعيات والمصالحة', 'sort_no' => 3,
    'grain' => 'كودٌ موحَّدٌ واحدٌ مقابلَ أكوادِه القديمة',
    'target_ref' => 'DEP-04·33·مصالحه مطابقه الاكواد',
    'intro' => 'جسرُ الكودِ الموحَّدِ الجديدِ بالأكوادِ القديمةِ ونظامِها المصدرِ وحالةِ مطابقتِها',
    'rule'  => 'كلُّ مطابقةٍ بمن طابَقها وتاريخِها — ولا مطابقةَ بلا شاهد',
    'empty' => 'لا مطابقةَ أكوادٍ مسجَّلةٌ بعد',
    'create' => array('unified_code', 'old_code_main', 'old_code_alt', 'asset_name',
                      'source_system', 'match_state', 'match_notes', 'matched_by_name',
                      'match_date'),
    'keys' => array('unified_code', 'old_code_main', 'old_code_alt', 'asset_name',
                    'source_system', 'match_state', 'match_notes', 'matched_by_name',
                    'match_date'),
),
array(
    'code' => 'flt_numbering_bridge', 'file' => 'numbering_bridge.php', 'placement_id' => 110,
    'surface' => 'مصالحة جسر الترقيم', 'title' => 'مصالحة جسر الترقيم', 'icon' => 'fa fa-bridge',
    'table' => 'flt_numbering_bridge', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ط · المرجعيات والمصالحة', 'sort_no' => 4,
    'grain' => 'لوحةٌ واحدةٌ بأكوادِها القديمةِ والحالية',
    'target_ref' => 'DEP-04·34·مصالحه جسر الترقيم',
    'intro' => 'اللوحةُ الواحدةُ وأكوادُها القديمةُ والحاليةُ وقرارُ توحيدِها',
    'rule'  => 'لوحةٌ بأكثرَ من كودٍ حيٍّ حالةُ مطابقةٍ مفتوحةٌ حتى يُعتمَد كودٌ واحد',
    'empty' => 'لا لوحةَ مسجَّلةٌ في جسرِ الترقيمِ بعد',
    'create' => array('plate_no', 'old_codes', 'old_codes_count', 'current_code',
                      'equipment_type', 'owner_supplier', 'hours_done', 'match_state',
                      'approved_code', 'unification_decision'),
    'keys' => array('plate_no', 'old_codes', 'old_codes_count', 'current_code',
                    'current_codes_count', 'equipment_type', 'owner_supplier', 'hours_done',
                    'match_state', 'approved_code', 'unification_decision'),
    'types' => array('hours_done' => 'DECIMAL(12,2) NULL DEFAULT NULL'),
),
array(
    'code' => 'flt_owner_recon', 'file' => 'owner_reconciliation.php', 'placement_id' => 111,
    'surface' => 'مصالحة الأسطول بالملاك', 'title' => 'مصالحة الأسطول بالملاك', 'icon' => 'fa fa-handshake',
    'table' => 'flt_owner_reconciliation', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ط · المرجعيات والمصالحة', 'sort_no' => 5,
    'grain' => 'معدّةٌ واحدةٌ مقابلَ مالكِها ومورِّدِها',
    'target_ref' => 'DEP-04·35·مصالحه الاسطول بالملاك',
    'intro' => 'كلُّ معدّةٍ بمورِّدِها ومالكِها الحقيقيِّ وساعاتِها وعقودِها ودوراتِ التزامِها',
    'rule'  => 'المالكُ الحقيقيُّ غيرُ المورِّدِ أحيانًا — والفرقُ يُكتب لا يُطوى',
    'empty' => 'لا مصالحةَ ملّاكٍ مسجَّلةٌ بعد',
    'create' => array('equipment_code', 'equipment_type', 'plate_no', 'supplier_no',
                      'supplier_name', 'supplier_type', 'supplier_nature', 'real_owner_name',
                      'owner_phone', 'old_code', 'chassis_no', 'notes'),
    'keys' => array('equipment_code', 'equipment_type', 'plate_no', 'supplier_no',
                    'supplier_name', 'supplier_type', 'supplier_nature', 'real_owner_name',
                    'owner_phone', 'old_code', 'first_operation', 'last_operation',
                    'months_count', 'hours_done', 'contracts_count', 'commitment_cycles',
                    'supplier_assets_registered', 'chassis_no', 'service_entry_date', 'notes'),
    'types' => array('first_operation' => 'DATE NULL DEFAULT NULL',
                     'last_operation' => 'DATE NULL DEFAULT NULL',
                     'hours_done' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'supplier_assets_registered' => 'VARCHAR(255) NULL DEFAULT NULL'),
    'dc' => array('contracts_count' => 'DC-3', 'real_owner_name' => 'DC-3'),
),
array(
    'code' => 'flt_reg_op_recon', 'file' => 'register_operation_recon.php', 'placement_id' => 112,
    'surface' => 'مصالحة السجل بالتشغيل', 'title' => 'مصالحة السجل بالتشغيل', 'icon' => 'fa fa-scale-balanced',
    'table' => 'flt_register_operation_recon', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ط · المرجعيات والمصالحة', 'sort_no' => 6,
    'grain' => 'أصلٌ واحدٌ — ساعاتُ سجلِّه مقابلَ ساعاتِ تشغيلِه',
    'target_ref' => 'DEP-04·36·مصالحه السجل بالتشغيل',
    'intro' => 'فرقُ الساعاتِ بين سجلِّ الأسطولِ والتايم شيت وتفسيرُه أصلًا أصلًا',
    'rule'  => 'الفرقُ يُفسَّر ولا يُسوّى بالكتابةِ على أحدِ المصدرَين (§17 · §18)',
    'empty' => 'لا مصالحةَ سجلٍّ بتشغيلٍ مسجَّلةٌ بعد',
    'create' => array('asset_code', 'unified_desc', 'class_code', 'ownership_type',
                      'operating_state', 'register_hours', 'intersection_state',
                      'timesheet_hours', 'timesheet_supplier', 'hours_diff', 'diff_explanation'),
    'keys' => array('asset_code', 'unified_desc', 'class_code', 'ownership_type',
                    'operating_state', 'register_hours', 'intersection_state',
                    'timesheet_hours', 'timesheet_supplier', 'first_operation',
                    'last_operation', 'commitment_cycles', 'hours_diff', 'diff_explanation'),
    'types' => array('first_operation' => 'DATE NULL DEFAULT NULL',
                     'last_operation' => 'DATE NULL DEFAULT NULL',
                     'register_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'timesheet_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'hours_diff' => 'DECIMAL(12,2) NULL DEFAULT NULL'),
),
array(
    'code' => 'flt_financed_recon', 'file' => 'financed_asset_recon.php', 'placement_id' => 113,
    'surface' => 'مصالحة الأعيان الممولة', 'title' => 'مصالحة الأعيان الممولة', 'icon' => 'fa fa-money-check-dollar',
    'table' => 'flt_financed_asset_recon', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'ط · المرجعيات والمصالحة', 'sort_no' => 7,
    'grain' => 'عينٌ ممولةٌ واحدةٌ مقابلَ كودِها بالأسطول',
    'target_ref' => 'DEP-04·37·مصالحه الاعيان المموله',
    'intro' => 'العينُ الممولةُ وكودُها المطابقُ بالأسطولِ ونوعُ تمويلِها وقرارُ تكويدِها',
    'rule'  => 'كودُ التمويلِ وكودُ الأسطولِ يلتقيان بقرارِ تكويدٍ مكتوبٍ لا بتخمين',
    'empty' => 'لا عينَ ممولةٌ مصالَحةٌ بعد',
    'create' => array('finance_asset_code', 'fleet_matched_code', 'classification', 'asset_type',
                      'finance_type', 'owner_financier', 'match_state', 'approved_code',
                      'coding_decision'),
    'keys' => array('finance_asset_code', 'fleet_matched_code', 'classification', 'asset_type',
                    'finance_type', 'owner_financier', 'match_state', 'approved_code',
                    'coding_decision'),
    'dc' => array('finance_type' => 'DC-2', 'owner_financier' => 'DC-2'),
),

));
