<?php
/**
 * tools/specs/dep11_operations.php — مواصفةُ `DEP-11` التشغيل (GOV_EXEC §5)
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **«قرارات التوقف» تُبنى هنا كتابةً** — `ops_stop_register` **مملوكةٌ
 *   للتشغيل**: السلطةُ والقرارُ والمتحمِّلُ أعمدتُها. وقد بُني عليها في
 *   `DEP-12` سطحٌ `read` بلا فعلِ كتابةٍ واحد، فالمالكُ واحدٌ والقارئُ يقرأ (§17).
 *
 * ◆ **وثلاثُ حبّاتٍ قائمةٍ تُستكمل**: `daily_plan_lines` (احتياجُ الغدِ
 *   وتوزيعُ الموارد) · `shift_period_logs` (توزيعُ زمنِ الورديةِ وحالاتُه) ·
 *   `ops_stop_register`.
 *
 * ◆ **و«توزيع زمن الوردية» بلا فعلِ تسجيلٍ**: فتراتُ الورديةِ **يكتبها محرّكُ
 *   الورديةِ** من التايم شيت ومن سجلِّ التوقّف — والشاشةُ تعرضها بأسبابِها
 *   الثلاثةِ وأثرِها. ⛔ ولا يُفتح لها بابُ إدخالٍ يدويٍّ يوازي المحرّك.
 */
return array(
    'dept'    => 'DEP-11',
    'dept_ar' => 'إدارة التشغيل',
    'unit'    => 'إدارة التشغيل',
    'role_id' => 1,
    'dir'     => 'operations',
    'neighbor_route' => 'operations/monthly_plan.php',
    'screens' => array(

array(
    'code' => 'ops_room', 'file' => 'ops_room.php', 'placement_id' => 239,
    'surface' => 'غرفة العمليات', 'title' => 'غرفة العمليات', 'icon' => 'fa fa-tower-broadcast',
    'table' => 'ops_room_kpi', 'table_mode' => 'create', 'nature' => 'read',
    'group' => 'اللوحة — خارج الدورة (Overview)', 'sort_no' => 1,
    'grain' => 'مؤشرُ غرفةِ عملياتٍ واحدٌ في فترة',
    'target_ref' => 'DEP-11·1·غرفه العمليات',
    'intro' => 'مؤشراتُ التشغيلِ الحيّةُ بحدودِها المضبوطةِ واتجاهِ وتيرتِها ومسؤولِ انحرافِها',
    'rule'  => 'كلُّ حقلٍ مشتقٌّ أو مستورَد — والغرفةُ إسقاطٌ لا مصدرَ حقيقة (§19)',
    'empty' => 'لا مؤشرَ محسوبٌ بعد',
    'keys' => array('kpi_id', 'kpi_ref', 'value', 'uom', 'period_ref', 'source_ref',
                    'control_limit', 'state', 'trend', 'deviation_owner', 'updated_on'),
    'types' => array('kpi_id' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'value' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'control_limit' => 'VARCHAR(120) NULL DEFAULT NULL',
                     'updated_on' => 'DATETIME NULL DEFAULT NULL'),
),
array(
    'code' => 'ops_seasonal', 'file' => 'ops_seasonal_factors.php', 'placement_id' => 240,
    'surface' => 'الخطة الموسمية ومعاملاتها', 'title' => 'الخطة الموسمية ومعاملاتها',
    'icon' => 'fa fa-cloud-sun-rain',
    'table' => 'ops_seasonal_factor', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'التخطيط والتوزيع', 'sort_no' => 1,
    'grain' => 'معاملُ معايرةٍ موسميٌّ واحدٌ في مدّة',
    'target_ref' => 'DEP-11·2·الخطه الموسميه ومعاملاتها',
    'intro' => 'معاملاتُ معايرةِ الخطّةِ بالمواسمِ ونطاقِ تطبيقِها وأساسِ احتسابِها',
    'rule'  => 'المعامِلُ يُعاير الخطّةَ ولا يُعاير المنفَّذ — وأساسُ احتسابِه مكتوبٌ لا مفترَض',
    'empty' => 'لا معاملَ موسميٌّ مسجَّلٌ بعد',
    'order' => 'from_date DESC, id DESC',
    'pk_code' => array('factor_code', 'OSF'),
    'create' => array('season', 'from_date', 'to_date', 'business_model', 'calibration_factor',
                      'calc_basis', 'apply_scope', 'factor_state'),
    'keys' => array('factor_code', 'season', 'from_date', 'to_date', 'business_model',
                    'calibration_factor', 'calc_basis', 'apply_scope', 'factor_state',
                    'created_by', 'created_at', 'data_state', 'src_ref'),
    'types' => array('calibration_factor' => 'DECIMAL(10,4) NULL DEFAULT NULL'),
),
array(
    'code' => 'ops_tomorrow', 'file' => 'ops_tomorrow_dispatch.php', 'placement_id' => 242,
    'surface' => 'احتياج الغد وتوزيع الموارد', 'title' => 'احتياج الغد وتوزيع الموارد',
    'icon' => 'fa fa-calendar-plus',
    'table' => 'daily_plan_lines', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'التخطيط والتوزيع', 'sort_no' => 3,
    'grain' => 'سطرُ توزيعِ معدّةٍ ومشغّلٍ على جبهةٍ ليومٍ ووردية',
    'target_ref' => 'DEP-11·4·احتياج الغد وتوزيع الموارد',
    'intro' => 'توزيعُ الغدِ: أيُّ معدّةٍ لأيِّ جبهةٍ بأيِّ مشغّلٍ وأيِّ وردية',
    'rule'  => 'حاجبُ الصيانةِ الحرجةِ وتأهيلُ المشغّلِ ورخصتُه تُقرأ من مصادرِها — ولا توزيعَ يتجاوزها',
    'empty' => 'لا سطرَ توزيعٍ مسجَّلٌ بعد',
    'order' => 'plan_day DESC, id DESC',
    'pk_code' => array('row_code', 'OTD'),
    'create' => array('plan_day', 'project_ref', 'work_zone', 'equipment_id', 'shift_no',
                      'operator_employee_id', 'zone_daily_target', 'row_state'),
    'keys' => array('row_code', 'plan_day', 'project_ref', 'site_ref', 'work_zone',
                    'zone_supervisor', 'equipment_id', 'equipment_type', 'equipment_tech_state',
                    'critical_maint_block', 'shift_no', 'operator_employee_id',
                    'operator_qualified', 'operator_license_valid', 'dispatch_conflict',
                    'zone_daily_target', 'row_state', 'created_by', 'created_at', 'reviewer',
                    'approved_by', 'approved_at', 'data_state', 'src_ref'),
    'types' => array('plan_day' => 'DATE NULL DEFAULT NULL',
                     'project_ref' => 'VARCHAR(60) NULL DEFAULT NULL',
                     'zone_daily_target' => 'DECIMAL(18,3) NULL DEFAULT NULL'),
),
array(
    'code' => 'ops_move_order', 'file' => 'ops_resource_move_orders.php', 'placement_id' => 243,
    'surface' => 'طلب وقرار حركة الموارد', 'title' => 'طلب وقرار حركة الموارد',
    'icon' => 'fa fa-truck-arrow-right',
    'table' => 'ops_resource_move_order', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'التخطيط والتوزيع', 'sort_no' => 4,
    'grain' => 'أمرُ حركةِ موردٍ واحدٌ من موقعٍ إلى موقع',
    'target_ref' => 'DEP-11·5·طلب وقرار حركه الموارد',
    'intro' => 'طلبُ نقلِ معدّةٍ أو مشغّلٍ بسببِه وأثرِه على خطّةِ الشهرِ وأمرِ ترحيلِه المتفرِّع',
    'rule'  => 'ما يحتاج ترحيلًا يتفرّع منه أمرُ ترحيلٍ بمرجعِه — ولا حركةَ صامتة',
    'empty' => 'لا أمرَ حركةٍ مسجَّلٌ بعد',
    'order' => 'order_date DESC, id DESC',
    'pk_code' => array('order_no', 'ORM'),
    'create' => array('order_date', 'resource_kind', 'resource_ref', 'move_reason',
                      'requested_exec_date', 'month_plan_effect', 'needs_transfer_order',
                      'order_state'),
    'keys' => array('order_no', 'order_date', 'resource_kind', 'resource_ref', 'from_project',
                    'from_site', 'to_project', 'to_site', 'move_reason', 'requested_exec_date',
                    'month_plan_effect', 'needs_transfer_order', 'transfer_order_ref',
                    'order_state', 'created_by', 'created_at', 'reviewer', 'approved_by',
                    'approved_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'ops_shift_time', 'file' => 'ops_shift_time_states.php', 'placement_id' => 245,
    'surface' => 'توزيع زمن الوردية وحالاته', 'title' => 'توزيع زمن الوردية وحالاته',
    'icon' => 'fa fa-hourglass-half',
    'table' => 'shift_period_logs', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'اليوم التشغيلي', 'sort_no' => 2,
    'grain' => 'فترةُ زمنٍ واحدةٌ داخلَ ورديةٍ بحالتِها',
    'target_ref' => 'DEP-11·7·توزيع زمن الورديه وحالاته',
    'intro' => 'زمنُ الورديةِ مقسَّمًا فتراتٍ بحالاتِها وأسبابِ توقفِها الثلاثةِ وأثرِ كلٍّ',
    'rule'  => 'الفتراتُ يكتبها محرّكُ الورديةِ من التايم شيت وسجلِّ التوقّف — ولا بابَ إدخالٍ يوازيه',
    'empty' => 'لا فترةَ ورديةٍ مسجَّلةٌ بعد',
    'order' => 'work_date DESC, log_id DESC',
    'keys' => array('log_id', 'daily_log_ref', 'period_no', 'time_state', 'from_time', 'to_time',
                    'duration_mins', 'stop_reason_code', 'stop_reason_l2', 'stop_reason_l3',
                    'stop_owner', 'client_obligation_ref', 'billing_effect',
                    'supplier_unit_effect', 'operator_wage_effect', 'stop_decision_required',
                    'stop_decision_no', 'field_note', 'created_by', 'created_at', 'data_state',
                    'src_ref'),
    'types' => array('from_time' => 'TIME NULL DEFAULT NULL', 'to_time' => 'TIME NULL DEFAULT NULL',
                     'duration_mins' => 'DECIMAL(10,2) NULL DEFAULT NULL'),
),
array(
    'code' => 'ops_stop_decisions', 'file' => 'ops_stop_decisions.php', 'placement_id' => 247,
    'surface' => 'قرارات التوقف', 'title' => 'قرارات التوقف', 'icon' => 'fa fa-gavel',
    'table' => 'ops_stop_register', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'الانحراف والاستثناء', 'sort_no' => 1,
    'grain' => 'قرارُ توقّفٍ واحدٌ على واقعةِ توقّف',
    'target_ref' => 'DEP-11·9·قرارات التوقف',
    'intro' => 'قراراتُ التوقّفِ بمهلتِها الإلزاميةِ ومبرِّرِها وأثرِها على الجاهزية',
    'rule'  => 'حبّةُ التوقّفِ مملوكةٌ للتشغيلِ — والقرارُ يُتَّخذ هنا وحدَه ويُقرأ عند غيرِه (§17)',
    'empty' => 'لا قرارَ توقّفٍ مسجَّلٌ بعد',
    'order' => 'stop_date DESC, id DESC',
    'pk_code' => array('decision_no', 'OSD'),
    'create' => array('event_date', 'stop_period_ref', 'equipment_id', 'site_id',
                      'stop_reason_ref', 'resp_party', 'decision', 'decision_reason',
                      'readiness_effect', 'decision_effective_date', 'decision_state'),
    'keys' => array('decision_no', 'event_date', 'stop_period_ref', 'equipment_id', 'site_id',
                    'stop_reason_ref', 'resp_party', 'accumulated_stop_hours', 'mandatory_sla',
                    'sla_elapsed', 'decision', 'decision_reason', 'readiness_effect',
                    'decision_effective_date', 'decision_state', 'created_by', 'created_at',
                    'reviewer', 'approved_by', 'approved_at', 'data_state', 'src_ref'),
    'types' => array('event_date' => 'DATE NULL DEFAULT NULL',
                     'accumulated_stop_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'mandatory_sla' => 'VARCHAR(80) NULL DEFAULT NULL',
                     'decision_effective_date' => 'DATE NULL DEFAULT NULL'),
),
array(
    'code' => 'ops_deviation', 'file' => 'ops_deviation_escalation.php', 'placement_id' => 249,
    'surface' => 'تقرير الانحراف والتصعيد', 'title' => 'تقرير الانحراف والتصعيد',
    'icon' => 'fa fa-arrow-trend-down',
    'table' => 'ops_deviation_report', 'table_mode' => 'create', 'nature' => 'read',
    'group' => 'الإقفال والتقارير', 'sort_no' => 1,
    'grain' => 'سطرُ انحرافٍ واحدٌ لمشروعٍ ومعدّةٍ في فترة',
    'target_ref' => 'DEP-11·11·تقرير الانحراف والتصعيد',
    'intro' => 'الفجوةُ بين المخطّطِ المعايَرِ والمنفَّذِ المعتمَدِ والوتيرةُ المطلوبةُ للحاق',
    'rule'  => 'كلُّ حقلٍ مشتقٌّ أو مستورَد — والتقريرُ إسقاطٌ لا مصدرَ حقيقة (§19)',
    'empty' => 'لا سطرَ انحرافٍ محسوبٌ بعد',
    'keys' => array('row_code', 'period_ref', 'project_ref', 'equipment_ref', 'calibrated_plan',
                    'approved_executed', 'gap', 'deviation_pct', 'control_limit',
                    'limit_exceeded', 'catchup_rate', 'top_three_reasons', 'deviation_owner',
                    'escalation_state'),
    'types' => array('calibrated_plan' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'approved_executed' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'gap' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'control_limit' => 'VARCHAR(120) NULL DEFAULT NULL',
                     'catchup_rate' => 'DECIMAL(18,3) NULL DEFAULT NULL'),
),

));
