<?php
/**
 * tools/specs/dep13_workforce.php — مواصفةُ `DEP-13` القوى التشغيلية (GOV_EXEC §5)
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **ولا سجلَّ ثالثًا للإنسان** — حكمُ `W03` المسجَّل: `persons` سجلٌّ ثانٍ
 *   للإنسانِ ومداه متداخل. فسطحُ «سجل الأفراد التشغيليين» **يُبنى فوق
 *   `equipment_operators`** — وهي بحبّتِها سجلُّ الفردِ التشغيليِّ برخصتِه
 *   وفئاتِ تشغيلِه وحالتِه، مربوطةً بـ`employees` بمعرِّفِه — **ولا جدولَ رابعًا**.
 *
 * ◆ **وستُّ حبّاتٍ قائمةٍ تُستكمل**: `worker_qualification` · `worker_movement` ·
 *   `operator_rotations` · `worker_settlement` · `worker_evaluation` ·
 *   `worker_contract`.
 *
 * ◆ **وثلاثةُ أسطحٍ كلُّ حقولِها مشتقّةٌ أو مستوردة** (لا حقلَ إدخالٍ واحد):
 *   «عقود المشاريع المرجعية» · «أداء الأفراد التشغيلي» · «لوحة القوى» —
 *   فطبيعتُها `read` بنصِّ §19: إسقاطٌ لا مصدرَ حقيقة.
 */
return array(
    'dept'    => 'DEP-13',
    'dept_ar' => 'إدارة القوى التشغيلية',
    'unit'    => 'إدارة القوى التشغيلية',
    'role_id' => 27,
    'dir'     => 'workforce',
    'neighbor_route' => 'workforce/workforce_requirement.php',
    'screens' => array(

array(
    'code' => 'wf_board', 'file' => 'wf_board.php', 'placement_id' => 270,
    'surface' => 'لوحة القوى التشغيلية', 'title' => 'لوحة القوى التشغيلية', 'icon' => 'fa fa-users-gear',
    'table' => 'wf_dashboard_kpi', 'table_mode' => 'create', 'nature' => 'read',
    'group' => 'اللوحة — خارج الدورة (Overview)', 'sort_no' => 1,
    'grain' => 'مؤشرٌ واحدٌ من مؤشراتِ القوى',
    'target_ref' => 'DEP-13·1·لوحه القوي التشغيليه',
    'intro' => 'مؤشراتُ القوى التشغيليةِ بفئاتِها وقيمِها وحالاتِها',
    'rule'  => 'كلُّ حقلٍ هنا مشتقٌّ أو مستورَد — فاللوحةُ إسقاطٌ ولا تُحرَّر (§19)',
    'empty' => 'لا مؤشرَ محسوبٌ بعد',
    'keys' => array('kpi_id', 'kpi_ref', 'category', 'value', 'uom', 'state', 'updated_on'),
    'types' => array('value' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'updated_on' => 'DATETIME NULL DEFAULT NULL',
                     'kpi_id' => 'VARCHAR(60) NULL DEFAULT NULL'),
),
array(
    'code' => 'wf_nomination', 'file' => 'wf_nomination.php', 'placement_id' => 273,
    'surface' => 'الترشيح والاختيار للتغطية', 'title' => 'الترشيح والاختيار للتغطية',
    'icon' => 'fa fa-user-check',
    'table' => 'wf_nomination', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'الاحتياج والتغطية', 'sort_no' => 3,
    'grain' => 'ترشيحُ فردٍ واحدٍ على احتياجٍ واحد',
    'target_ref' => 'DEP-13·4·الترشيح والاختيار للتغطيه',
    'intro' => 'ترشيحُ الأفرادِ لتغطيةِ الاحتياجِ بفحصِ تأهيلِهم ورخصِهم ونتيجةِ اختبارِهم',
    'rule'  => 'فحصُ التأهيلِ والرخصةِ يُشتقَّان من سجلَّيهما — ولا قرارَ ترشيحٍ يتجاوزهما',
    'empty' => 'لا ترشيحَ مسجَّلٌ بعد',
    'pk_code' => array('nomination_no', 'WFN'),
    'create' => array('requirement_ref', 'person_ref', 'nomination_source',
                      'interview_result', 'decision', 'nomination_state'),
    'keys' => array('nomination_no', 'requirement_ref', 'person_ref', 'category_ref',
                    'nomination_source', 'prequal_check', 'license_check', 'interview_result',
                    'decision', 'contract_ref', 'nomination_state', 'created_by', 'created_at',
                    'data_state', 'src_ref'),
),
array(
    'code' => 'wf_project_contracts', 'file' => 'wf_project_contracts_ref.php', 'placement_id' => 274,
    'surface' => 'عقود المشاريع المرجعية', 'title' => 'عقود المشاريع المرجعية',
    'icon' => 'fa fa-file-contract',
    'table' => 'worker_contract', 'table_mode' => 'extend', 'nature' => 'read',
    'group' => 'الاحتياج والتغطية', 'sort_no' => 4,
    'grain' => 'عقدُ مشروعٍ واحدٌ لفردٍ واحد',
    'target_ref' => 'DEP-13·5·عقود المشاريع المرجعيه',
    'intro' => 'عقودُ المشاريعِ مرجعًا: مدّتُها ومحفِّزُ انتهائِها وحالتُها',
    'rule'  => 'كلُّ حقلٍ مشتقٌّ أو مستورَد — والعقدُ يُحرَّر عند مالكِه لا هنا (§17 · §19)',
    'empty' => 'لا عقدَ مشروعٍ مسجَّلٌ بعد',
    'order' => 'date_start DESC, id DESC',
    'keys' => array('row_code', 'person_ref', 'project_contract_ref', 'project_ref',
                    'valid_from', 'valid_to', 'end_trigger', 'contract_state'),
    'types' => array('valid_from' => 'DATE NULL DEFAULT NULL',
                     'valid_to' => 'DATE NULL DEFAULT NULL'),
),
array(
    'code' => 'wf_taxonomy', 'file' => 'wf_taxonomy.php', 'placement_id' => 275,
    'surface' => 'تصنيف الفئات التشغيلية — Workforce Taxonomy',
    'title' => 'تصنيف الفئات التشغيلية', 'icon' => 'fa fa-sitemap',
    'table' => 'wf_category', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'التأهيل والجاهزية', 'sort_no' => 1,
    'grain' => 'فئةٌ تشغيليةٌ واحدة',
    'target_ref' => 'DEP-13·6·تصنيف الفئات التشغيليه — Workforce Taxonomy',
    'intro' => 'الفئاتُ التشغيليةُ بعائلاتِها الوظيفيةِ ومتطلباتِ مصفوفتِها المرجعية',
    'rule'  => 'العائلةُ الوظيفيةُ تُشتقُّ من الهيكلِ النافذِ — ولا فئةَ توازي مسمًّى وظيفيًّا بلا حكم',
    'empty' => 'لا فئةَ تشغيليةٌ مسجَّلةٌ بعد',
    'pk_code' => array('category_code', 'WFC'),
    'create' => array('category_name', 'equipment_applies', 'title_examples', 'category_state'),
    'keys' => array('category_code', 'category_name', 'job_family', 'org_structure_ref',
                    'equipment_applies', 'matrix_requirements', 'title_examples',
                    'category_state', 'created_by', 'created_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'wf_person_register', 'file' => 'wf_person_register.php', 'placement_id' => 276,
    'surface' => 'سجل الأفراد التشغيليين', 'title' => 'سجل الأفراد التشغيليين', 'icon' => 'fa fa-id-badge',
    'table' => 'equipment_operators', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التأهيل والجاهزية', 'sort_no' => 2,
    'grain' => 'فردٌ تشغيليٌّ واحدٌ — سطرٌ لكلِّ موظّفٍ في فئةٍ تشغيلية',
    'target_ref' => 'DEP-13·7·سجل الافراد التشغيليين',
    'intro' => 'الأفرادُ التشغيليون بفئاتِهم وتبعيّتِهم ورخصِهم وأنواعِ المعداتِ المؤهَّلين عليها',
    'rule'  => 'الاسمُ ورقمُ الموظفِ يُقرآن من الموارد — ولا سجلَّ ثالثًا للإنسان (حكم W03)',
    'empty' => 'لا فردَ تشغيليٌّ مسجَّلٌ بعد',
    'pk_code' => array('person_code', 'WFP'),
    'create' => array('wf_category', 'affiliation', 'distribution_track', 'employee_id',
                      'license_type', 'license_expiry_date', 'status'),
    'keys' => array('person_code', 'person_name', 'wf_category', 'affiliation',
                    'distribution_track', 'employee_id', 'license_type', 'license_expiry_date',
                    'qualified_equipment_types', 'current_site', 'current_allocation',
                    'rotation_pattern', 'status', 'created_by', 'created_at', 'reviewer',
                    'approved_by', 'approved_at', 'data_state', 'src_ref'),
    'types' => array('license_expiry_date' => 'DATE NULL DEFAULT NULL'),
),
array(
    'code' => 'wf_qualifications', 'file' => 'wf_qualifications.php', 'placement_id' => 277,
    'surface' => 'التأهيل والشهادات', 'title' => 'التأهيل والشهادات', 'icon' => 'fa fa-certificate',
    'table' => 'worker_qualification', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التأهيل والجاهزية', 'sort_no' => 3,
    'grain' => 'تأهيلٌ واحدٌ لفردٍ واحد',
    'target_ref' => 'DEP-13·8·التاهيل والشهادات',
    'intro' => 'شهاداتُ التأهيلِ بجهاتِها ومستوياتِها وتواريخِ انتهائِها ونتيجةِ اختبارِها العملي',
    'rule'  => 'حالةُ التأهيلِ تُشتقُّ من تاريخِ الانتهاءِ ولا تُكتب — والمنتهي لا يؤهِّل',
    'empty' => 'لا تأهيلَ مسجَّلٌ بعد',
    'order' => 'expiry_date DESC, id DESC',
    'pk_code' => array('qual_code', 'WFQ'),
    'create' => array('employee_id', 'equipment_type', 'proficiency_level', 'issuer',
                      'certificate_no', 'expiry_date', 'practical_test_result'),
    'keys' => array('qual_code', 'employee_id', 'equipment_type', 'proficiency_level',
                    'issuer', 'certificate_no', 'expiry_date', 'practical_test_result',
                    'qual_state', 'created_by', 'created_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'wf_qual_matrix', 'file' => 'wf_qualification_matrix.php', 'placement_id' => 278,
    'surface' => 'مصفوفة التأهيل والجاهزية', 'title' => 'مصفوفة التأهيل والجاهزية',
    'icon' => 'fa fa-table-cells',
    'table' => 'wf_qualification_matrix', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'التأهيل والجاهزية', 'sort_no' => 4,
    'grain' => 'قاعدةُ تأهيلٍ واحدةٌ لنوعٍ أو فئة',
    'target_ref' => 'DEP-13·9·مصفوفه التاهيل والجاهزيه',
    'intro' => 'المصفوفةُ المرجعيةُ: أدنى تأهيلٍ ورخصةٍ وفحصٍ طبيٍّ لكلِّ نوعٍ أو فئة',
    'rule'  => 'المصفوفةُ تُحكم التخصيصَ ولا تُتجاوز إلا باستثناءِ إشرافٍ مسجَّل',
    'empty' => 'لا قاعدةَ مسجَّلةٌ بعد',
    'pk_code' => array('rule_code', 'WFM'),
    'create' => array('type_or_category', 'min_proficiency', 'required_license',
                      'medical_required', 'recert_period', 'supervised_exception', 'rule_state'),
    'keys' => array('rule_code', 'type_or_category', 'min_proficiency', 'required_license',
                    'medical_required', 'recert_period', 'supervised_exception', 'rule_state',
                    'created_by', 'created_at', 'data_state', 'src_ref'),
    'types' => array('recert_period' => 'VARCHAR(80) NULL DEFAULT NULL'),
),
array(
    'code' => 'wf_allocation', 'file' => 'wf_project_allocation.php', 'placement_id' => 279,
    'surface' => 'التخصيص للمشروع', 'title' => 'التخصيص للمشروع', 'icon' => 'fa fa-diagram-project',
    'table' => 'wf_project_allocation', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'التخصيص والحركة', 'sort_no' => 1,
    'grain' => 'تخصيصُ فردٍ واحدٍ لمشروعٍ واحدٍ في مدّة',
    'target_ref' => 'DEP-13·10·التخصيص للمشروع',
    'intro' => 'تخصيصُ الفردِ للمشروعِ بمدّتِه ووحدةِ سكنِه وفحصَي تأهيلِه وعقدِه',
    'rule'  => 'لا تخصيصَ بلا فحصِ تأهيلٍ نافذٍ وعقدِ مشروعٍ ساري — والفحصان يُشتقّان',
    'empty' => 'لا تخصيصَ مسجَّلٌ بعد',
    'pk_code' => array('allocation_no', 'WFA'),
    'create' => array('requirement_ref', 'person_ref', 'from_date', 'to_date',
                      'allocation_state'),
    'keys' => array('allocation_no', 'requirement_ref', 'person_ref', 'qualification_check',
                    'project_contract_check', 'project_ref', 'site_ref', 'from_date', 'to_date',
                    'housing_unit_ref', 'allocation_state', 'created_by', 'created_at',
                    'reviewer', 'approved_by', 'approved_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'wf_shift_assign', 'file' => 'wf_equipment_shift_assignment.php', 'placement_id' => 280,
    'surface' => 'تخصيص المعدة والوردية', 'title' => 'تخصيص المعدة والوردية', 'icon' => 'fa fa-user-gear',
    'table' => 'wf_equipment_shift_assignment', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'التخصيص والحركة', 'sort_no' => 2,
    'grain' => 'تكليفُ فردٍ على معدّةٍ في وردية',
    'target_ref' => 'DEP-13·11·تخصيص المعده والورديه',
    'intro' => 'تكليفُ الفردِ بمعدّةٍ في وردية، بفحصِ المصفوفةِ وبديلِه المعتمَد',
    'rule'  => 'فحصُ المصفوفةِ شرطُ التكليفِ — ولا تكليفَ يخالف أدنى تأهيلِ النوع',
    'empty' => 'لا تكليفَ مسجَّلٌ بعد',
    'pk_code' => array('assignment_no', 'WFS'),
    'create' => array('allocation_ref', 'person_ref', 'equipment_ref', 'shift', 'from_date',
                      'to_date', 'end_reason', 'assignment_state'),
    'keys' => array('assignment_no', 'allocation_ref', 'person_ref', 'equipment_ref',
                    'equipment_type', 'matrix_check', 'shift', 'from_date', 'to_date',
                    'approved_backup', 'end_reason', 'assignment_state', 'created_by',
                    'created_at', 'reviewer', 'approved_by', 'approved_at', 'data_state',
                    'src_ref'),
),
array(
    'code' => 'wf_daily_presence', 'file' => 'wf_daily_presence.php', 'placement_id' => 281,
    'surface' => 'الحركة والتواجد اليومي', 'title' => 'الحركة والتواجد اليومي', 'icon' => 'fa fa-person-walking',
    'table' => 'worker_movement', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التخصيص والحركة', 'sort_no' => 3,
    'grain' => 'سطرُ حركةٍ أو تواجدٍ ليومٍ واحدٍ لفرد',
    'target_ref' => 'DEP-13·12·الحركه والتواجد اليومي',
    'intro' => 'حركةُ الأفرادِ وتواجدُهم يومًا بيوم بوسيلةِ انتقالِهم ومرجعِ أمرِ نقلِهم',
    'rule'  => 'التواجدُ بالموقعِ يُقرأ من الموقعِ ولا يُكتب هنا — والحركةُ بأمرِها لا بلا سند',
    'empty' => 'لا سطرَ حركةٍ مسجَّلٌ بعد',
    'order' => 'departure_date DESC, id DESC',
    'pk_code' => array('row_code', 'WFD'),
    'create' => array('row_date', 'person_ref', 'row_kind', 'presence_state', 'transport_mode'),
    'keys' => array('row_code', 'row_date', 'person_ref', 'row_kind', 'presence_state',
                    'span_from', 'span_to', 'transport_mode', 'transfer_order_ref',
                    'site_presence', 'row_state', 'created_by', 'created_at', 'data_state',
                    'src_ref'),
    'types' => array('span_from' => 'VARCHAR(80) NULL DEFAULT NULL',
                     'span_to' => 'VARCHAR(80) NULL DEFAULT NULL'),
),
array(
    'code' => 'wf_rotation', 'file' => 'wf_rotation_backup.php', 'placement_id' => 282,
    'surface' => 'التناوب والبدلاء', 'title' => 'التناوب والبدلاء', 'icon' => 'fa fa-rotate',
    'table' => 'operator_rotations', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التخصيص والحركة', 'sort_no' => 4,
    'grain' => 'دورةُ تناوبٍ واحدةٌ لفردٍ واحد',
    'target_ref' => 'DEP-13·13·التناوب والبدلاء',
    'intro' => 'دوراتُ التناوبِ بإجازاتِها وبدلائِها المكلَّفين وفحصِ تأهيلِ البديل',
    'rule'  => 'البديلُ لا يُكلَّف بلا فحصِ تأهيلٍ — وأثرُ التغطيةِ يُقرأ ولا يُقدَّر',
    'empty' => 'لا دورةَ تناوبٍ مسجَّلةٌ بعد',
    'pk_code' => array('cycle_code', 'WFR'),
    'create' => array('person_ref', 'rotation_pattern', 'cycle_start_date', 'leave_start',
                      'leave_end', 'leave_type', 'swap_state', 'cycle_state'),
    'keys' => array('cycle_code', 'person_ref', 'rotation_pattern', 'cycle_start_date',
                    'leave_start', 'leave_end', 'leave_type', 'assigned_backup',
                    'backup_qual_check', 'swap_state', 'coverage_effect', 'cycle_state',
                    'created_by', 'created_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'wf_performance', 'file' => 'wf_performance.php', 'placement_id' => 283,
    'surface' => 'أداء الأفراد التشغيلي', 'title' => 'أداء الأفراد التشغيلي', 'icon' => 'fa fa-chart-line',
    'table' => 'worker_evaluation', 'table_mode' => 'extend', 'nature' => 'read',
    'group' => 'الأداء والتسوية', 'sort_no' => 1,
    'grain' => 'أداءُ فردٍ واحدٍ في فترةٍ واحدة',
    'target_ref' => 'DEP-13·14·اداء الافراد التشغيلي',
    'intro' => 'أداءُ الفردِ بالساعاتِ والوحداتِ المعتمَدةِ وأيامِ ميدانِه ووقائعِ فترتِه',
    'rule'  => 'كلُّ حقلٍ مشتقٌّ أو مستورَد — فالسطحُ إسقاطٌ ولا يُحرَّر (§19)',
    'empty' => 'لا سطرَ أداءٍ محسوبٌ بعد',
    'order' => 'period DESC, id DESC',
    'keys' => array('row_code', 'period_ref', 'person_ref', 'category_ref', 'approved_hours',
                    'approved_units', 'field_days', 'shift_compliance', 'period_incidents',
                    'performance_index'),
    'types' => array('approved_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'approved_units' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'field_days' => 'INT NULL DEFAULT NULL',
                     'performance_index' => 'DECIMAL(8,2) NULL DEFAULT NULL'),
),
array(
    'code' => 'wf_settlement', 'file' => 'wf_settlement.php', 'placement_id' => 284,
    'surface' => 'التسوية ونهاية التخصيص', 'title' => 'التسوية ونهاية التخصيص',
    'icon' => 'fa fa-file-circle-check',
    'table' => 'worker_settlement', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'الأداء والتسوية', 'sort_no' => 2,
    'grain' => 'تسويةُ نهايةِ تخصيصٍ واحدةٌ لفرد',
    'target_ref' => 'DEP-13·15·التسويه ونهايه التخصيص',
    'intro' => 'تسويةُ نهايةِ التخصيصِ بإخلاءِ السكنِ والعُهدِ المردودةِ والمعلَّقةِ وأساسِ المستحق',
    'rule'  => 'العهدةُ المعلَّقةُ تمنع الإقفال — والمستحقُّ أساسُه مشتقٌّ لا مُدخَل',
    'empty' => 'لا تسويةَ مسجَّلةٌ بعد',
    'pk_code' => array('settlement_no', 'WFT'),
    'create' => array('allocation_ref', 'person_ref', 'settlement_state'),
    'keys' => array('settlement_no', 'allocation_ref', 'person_ref', 'end_reason',
                    'housing_cleared', 'custody_returned', 'custody_pending', 'due_basis',
                    'paying_party', 'hr_clearance_ref', 'settlement_state', 'created_by',
                    'created_at', 'data_state', 'src_ref'),
    'dc' => array('due_basis' => 'DC-2', 'paying_party' => 'DC-2'),
),
array(
    'code' => 'wf_incidents', 'file' => 'wf_field_incidents.php', 'placement_id' => 286,
    'surface' => 'وقائع الميدان والإحالة التأديبية', 'title' => 'وقائع الميدان والإحالة التأديبية',
    'icon' => 'fa fa-triangle-exclamation',
    'table' => 'wf_field_incident', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'الأداء والتسوية', 'sort_no' => 4,
    'grain' => 'واقعةُ ميدانٍ واحدةٌ على فردٍ واحد',
    'target_ref' => 'DEP-13·17·وقائع الميدان والاحاله التاديبيه',
    'intro' => 'وقائعُ الميدانِ بأدلّتِها وجهةِ إحالتِها ومرجعِ قضيّتِها أو تسويةِ مورِّدِها',
    'rule'  => 'الإحالةُ تُشتقُّ من التبعيّةِ — والموظفُ إلى الموارد والمورِّدُ إلى تسويتِه',
    'empty' => 'لا واقعةَ ميدانٍ مسجَّلةٌ بعد',
    'pk_code' => array('incident_no', 'WFI'),
    'create' => array('incident_date', 'person_ref', 'incident_type', 'incident_desc',
                      'evidence_ref', 'incident_state'),
    'keys' => array('incident_no', 'incident_date', 'person_ref', 'affiliation_ref',
                    'incident_type', 'incident_desc', 'evidence_ref', 'referred_to',
                    'case_ref', 'supplier_settlement_ref', 'incident_state', 'created_by',
                    'created_at', 'data_state', 'src_ref'),
),

));
