<?php
/**
 * tools/specs/dep12_site.php — مواصفةُ بناءِ `DEP-12` إدارةُ الموقع (GOV_EXEC §5)
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **الحبّاتُ القائمةُ تُستكمل ولا تُستنسخ**: `sites` · `site_day` ·
 *   `site_day_shift` مبنيّةٌ سلفًا بحبّاتِها — فالأسطحُ الثلاثةُ تُبنى فوقَها
 *   (`extend`) لا فوقَ جداولَ موازية.
 *
 * ◆ **وسطحان حبّتُهما عند إدارةٍ أخرى** فيُقرآن ولا يُكتبان (§17):
 *   · «قرار الاستعداد أو التعطل» ⇐ `ops_stop_register` **مملوكةٌ للتشغيل**
 *     (السلطةُ والقرارُ والمتحمِّلُ أعمدتُها) — والموقعُ يراها ولا يقرّرها.
 *   · «صرف المشتريات الميدانية من العهدة» ⇐ `tre_petty_expense` **مملوكةٌ
 *     للخزينة** — العهدةُ عهدتُها والتسويةُ عندها.
 *
 * ◆ **وثلاثةُ أسطحٍ مشروطةُ الانطباق** بنصِّ الورقة («بحسب انطباق الشركة»):
 *   التجهيزُ والجاهزيةُ · الإيقافُ المؤقت · الإغلاقُ والتسريح. **وتُبنى**:
 *   §16 من الأمرِ يقول «وبناءُ المحرّكِ لا يتوقّف على قيمةٍ لم تُحسم»،
 *   والانطباقُ حكمُ تشغيلٍ لا شرطُ بناء.
 */
return array(
    'dept'    => 'DEP-12',
    'dept_ar' => 'إدارة الموقع',
    'unit'    => 'إدارة الموقع',
    'role_id' => 6,
    'dir'     => 'operations',
    'neighbor_route' => 'operations/site_gate_equip.php',
    'screens' => array(

array(
    'code' => 'site_board', 'file' => 'site_board.php', 'placement_id' => 251,
    'surface' => 'لوحة الموقع', 'title' => 'لوحة الموقع', 'icon' => 'fa fa-chart-simple',
    'table' => 'site_dashboard_kpi', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'اللوحة — خارج الدورة (Overview)', 'sort_no' => 1,
    'grain' => 'مؤشرٌ واحدٌ لموقعٍ واحد',
    'target_ref' => 'DEP-12·1·لوحه الموقع',
    'intro' => 'مؤشراتُ الموقعِ بقيمِها وحالاتِها وآخرِ تحديثٍ لكلٍّ',
    'rule'  => 'اللوحةُ إسقاطٌ لا مصدرَ حقيقة — ومصدرُ كلِّ مؤشرٍ من كتلوجِ المؤشرات (§19)',
    'empty' => 'لا مؤشرَ معرَّفٌ بعدُ للموقع',
    'create' => array('site_ref', 'kpi_ref', 'uom'),
    'keys' => array('kpi_id', 'site_ref', 'kpi_ref', 'value', 'uom', 'state', 'updated_on'),
    'types' => array('value' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'updated_on' => 'DATETIME NULL DEFAULT NULL',
                     'kpi_id' => 'VARCHAR(60) NULL DEFAULT NULL'),
),
array(
    'code' => 'site_register', 'file' => 'site_register.php', 'placement_id' => 252,
    'surface' => 'سجل المواقع وحدودها', 'title' => 'سجل المواقع وحدودها', 'icon' => 'fa fa-map-location-dot',
    'table' => 'sites', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التأسيس', 'sort_no' => 1,
    'grain' => 'موقعٌ واحدٌ بحدودِه',
    'target_ref' => 'DEP-12·2·سجل المواقع وحدودها',
    'intro' => 'المواقعُ بمشاريعِها وحدودِها وجبهاتِ عملِها وطاقتِها الاستيعابية',
    'rule'  => 'الموقعُ مصدرُ حقيقةٍ واحدٌ — والمشروعُ والعقدُ يُقرآن ولا يُحرَّران هنا',
    'empty' => 'لا موقعَ مسجَّلٌ بعد',
    'where' => 'is_deleted = 0',
    'pk_code' => array('site_code', 'SITE'),
    'create' => array('name', 'project_id', 'region', 'coordinates', 'work_zones',
                      'responsible_employee_id', 'shifts_count', 'equipment_capacity', 'status'),
    'keys' => array('site_code', 'name', 'project_id', 'project_name', 'client_contract_code',
                    'region', 'coordinates', 'work_zones', 'responsible_employee_id',
                    'shifts_count', 'equipment_capacity', 'housing_facilities', 'status',
                    'created_by', 'created_at', 'reviewer', 'approved_by', 'approved_at',
                    'data_state', 'src_ref'),
    'types' => array('shifts_count' => 'VARCHAR(40) NULL DEFAULT NULL',
                     'equipment_capacity' => 'VARCHAR(120) NULL DEFAULT NULL'),
),
array(
    'code' => 'site_readiness', 'file' => 'site_readiness_items.php', 'placement_id' => 253,
    'surface' => 'تجهيز الموقع والجاهزية — بحسب انطباق الشركة',
    'title' => 'تجهيز الموقع والجاهزية', 'icon' => 'fa fa-helmet-safety',
    'table' => 'site_readiness_item', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'التأسيس', 'sort_no' => 2,
    'grain' => 'بندُ تجهيزٍ واحدٌ على موقعٍ واحد',
    'target_ref' => 'DEP-12·3·تجهيز الموقع والجاهزيه — بحسب انطباق الشركه',
    'intro' => 'بنودُ تجهيزِ الموقعِ ومسؤولوها ونتائجُها وإعلانُ الجاهزية',
    'rule'  => 'انطباقُ السطحِ حكمُ تشغيلٍ لا شرطُ بناء (§16) — ولا جاهزيةَ تُعلَن ببندٍ مفتوح',
    'empty' => 'لا بندَ تجهيزٍ مسجَّلٌ بعد',
    'pk_code' => array('item_code', 'SRD'),
    'create' => array('site_ref', 'readiness_item', 'owner_ref', 'result', 'item_state'),
    'keys' => array('item_code', 'site_ref', 'readiness_item', 'owner_ref', 'completion_ref',
                    'result', 'completion_date', 'readiness_declaration', 'item_state',
                    'created_by', 'created_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'site_day_open', 'file' => 'site_day_open.php', 'placement_id' => 255,
    'surface' => 'فتح يوم الموقع', 'title' => 'فتح يوم الموقع', 'icon' => 'fa fa-door-open',
    'table' => 'site_day', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'اليوم الميداني', 'sort_no' => 1,
    'grain' => 'موقعٌ × يومٌ — سطرٌ واحد',
    'target_ref' => 'DEP-12·5·فتح يوم الموقع',
    'intro' => 'افتتاحُ يومِ الموقعِ بحضورِ معداتِه ومشغّليه وحالةِ طقسِه',
    'rule'  => 'اليومُ لا يُفتح مرّتَين — والمتخلّفُ يُكتب ولا يُسكَت عنه',
    'empty' => 'لا يومَ موقعٍ مفتوحٌ بعد',
    'order' => 'day_date DESC, id DESC',
    'pk_code' => array('day_code', 'SDY'),
    'create' => array('site_id', 'day_date', 'shift', 'supervisor_id', 'equipment_absent',
                      'operators_absent', 'substitutes_activated', 'weather_state', 'opening_note'),
    'keys' => array('day_code', 'site_id', 'day_date', 'shift', 'supervisor_id',
                    'received_distribution', 'equipment_present', 'equipment_absent',
                    'operators_present', 'operators_absent', 'substitutes_activated',
                    'weather_state', 'opening_note', 'state', 'created_by', 'created_at',
                    'data_state', 'source_ref'),
),
array(
    'code' => 'site_day_units', 'file' => 'site_day_units.php', 'placement_id' => 257,
    'surface' => 'تسجيل وحدات اليوم', 'title' => 'تسجيل وحدات اليوم', 'icon' => 'fa fa-list-check',
    'table' => 'site_day_unit', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'اليوم الميداني', 'sort_no' => 2,
    'grain' => 'سطرُ وحدةٍ منجزةٍ في يومِ موقعٍ',
    'target_ref' => 'DEP-12·7·تسجيل وحدات اليوم',
    'intro' => 'الوحداتُ المقيسةُ في يومِ الموقعِ بمعدّتِها ومشغّلِها ووسيلةِ قياسِها',
    'rule'  => 'الكميةُ تُقاس بوسيلةٍ مسمّاةٍ ومرجعٍ ميدانيّ — ولا وحدةَ بلا مصدرِ قياس',
    'empty' => 'لا وحدةَ مسجَّلةٌ بعدُ لهذا اليوم',
    'pk_code' => array('row_code', 'SDU'),
    'create' => array('day_ref', 'equipment_ref', 'measured_qty', 'measure_method', 'field_ref'),
    'keys' => array('row_code', 'day_ref', 'equipment_ref', 'operator_ref', 'work_zone',
                    'unit_type', 'measured_qty', 'measure_method', 'field_ref', 'recorded_at',
                    'offline_recorded', 'row_state', 'created_by', 'created_at', 'data_state',
                    'src_ref'),
    'types' => array('measured_qty' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'recorded_at' => 'DATETIME NULL DEFAULT NULL'),
),
array(
    'code' => 'site_day_shifts', 'file' => 'site_day_shifts.php', 'placement_id' => 256,
    'surface' => 'ورديات اليوم', 'title' => 'ورديات اليوم', 'icon' => 'fa fa-clock',
    'table' => 'site_day_shift', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التنفيذ اليومي', 'sort_no' => 1,
    'grain' => 'ورديةٌ واحدةٌ في يومِ موقع',
    'target_ref' => 'DEP-12·6·ورديات اليوم',
    'intro' => 'ورديّاتُ اليومِ بمشرفيها وحالةِ السلامةِ فيها وسريانِ تصاريحِ العمل',
    'rule'  => 'حالةُ HSE وStop-Work تُقرآن من مصدرِهما — والوردياتُ لا تُغلق بتصريحٍ منتهٍ',
    'empty' => 'لا ورديةَ مسجَّلةٌ بعد',
    'pk_code' => array('shift_code', 'SSH'),
    'create' => array('day_id', 'shift', 'supervisor_id', 'hse_state', 'state'),
    'keys' => array('shift_code', 'day_id', 'shift', 'supervisor_id', 'span_text', 'hse_state',
                    'permits_valid', 'unsafe_conditions', 'stop_work', 'state', 'created_by',
                    'created_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'site_stop_decision', 'file' => 'site_stop_decision.php', 'placement_id' => 264,
    'surface' => 'قرار الاستعداد أو التعطل', 'title' => 'قرار الاستعداد أو التعطل',
    'icon' => 'fa fa-circle-pause',
    'table' => 'ops_stop_register', 'table_mode' => 'extend', 'nature' => 'read',
    'group' => 'التنفيذ اليومي', 'sort_no' => 2,
    'grain' => 'واقعةُ توقّفٍ واحدةٌ على معدّةٍ في وردية',
    'target_ref' => 'DEP-12·14·قرار الاستعداد او التعطل',
    'intro' => 'تصنيفُ التوقّفِ ومتحمِّلُه وأثرُه على الفوترةِ والوحدةِ التعاقدية',
    'rule'  => 'حبّةُ التوقّفِ مملوكةٌ للتشغيلِ وسلطتُها فيه — فهذه الشاشةُ تقرأ ولا تكتب (§17)',
    'empty' => 'لا واقعةَ توقّفٍ مسجَّلةٌ بعد',
    'order' => 'stop_date DESC, id DESC',
    'keys' => array('stop_code', 'stop_date', 'equipment_id', 'shift', 'hours', 'ops_state',
                    'reason_tree_ref', 'resp_party', 'billing_effect', 'contract_unit_effect',
                    'decision_doc', 'decided_by', 'ops_endorsement', 'decision', 'created_by',
                    'created_at', 'reviewer', 'approved_by', 'approved_at', 'data_state',
                    'src_ref'),
    'types' => array('stop_code' => 'VARCHAR(60) NULL DEFAULT NULL'),
),
array(
    'code' => 'site_day_approval', 'file' => 'site_day_approval.php', 'placement_id' => 258,
    'surface' => 'محضر اعتماد الموقع', 'title' => 'محضر اعتماد الموقع', 'icon' => 'fa fa-file-signature',
    'table' => 'site_day_approval', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'الاعتماد الميداني', 'sort_no' => 1,
    'grain' => 'محضرُ اعتمادٍ واحدٌ ليومِ موقع',
    'target_ref' => 'DEP-12·8·محضر اعتماد الموقع',
    'intro' => 'محضرُ اعتمادِ سجلاتِ اليومِ بإقرارِ «حدثت فعلًا» وتوقيعِ مدير الموقع',
    'rule'  => 'المرفوضُ بسببٍ مكتوب — ولا اعتمادَ بلا إقرارٍ صريحٍ وتوقيع',
    'empty' => 'لا محضرَ اعتمادٍ مسجَّلٌ بعد',
    'pk_code' => array('minutes_no', 'SDA'),
    'create' => array('day_ref', 'site_ref', 'records_modified', 'records_rejected',
                      'reject_reason', 'happened_declaration', 'site_manager_signature'),
    'keys' => array('minutes_no', 'day_ref', 'site_ref', 'day_date_ref', 'records_count',
                    'records_matched', 'records_modified', 'records_rejected', 'reject_reason',
                    'happened_declaration', 'site_manager_signature', 'pdf_export',
                    'minutes_state', 'created_by', 'created_at', 'reviewer', 'approved_by',
                    'approved_at', 'data_state', 'src_ref'),
    'types' => array('records_modified' => 'INT NULL DEFAULT NULL',
                     'records_rejected' => 'INT NULL DEFAULT NULL'),
),
array(
    'code' => 'site_shift_handover', 'file' => 'site_shift_handover.php', 'placement_id' => 259,
    'surface' => 'محضر تسليم واستلام الورديات', 'title' => 'محضر تسليم واستلام الورديات',
    'icon' => 'fa fa-right-left',
    'table' => 'site_shift_handover', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'الاعتماد الميداني', 'sort_no' => 2,
    'grain' => 'محضرُ تسليمٍ واحدٌ بين وردِيَّتَين',
    'target_ref' => 'DEP-12·9·محضر تسليم واستلام الورديات',
    'intro' => 'تسليمُ الورديةِ بمعداتِها العاملةِ والمتوقفةِ وعُهدِها وملاحظاتِها المرحَّلة',
    'rule'  => 'الملاحظةُ المفتوحةُ تُرحَّل ولا تُطوى — والعدّاداتُ تُقرأ عند التسليم',
    'empty' => 'لا محضرَ تسليمٍ مسجَّلٌ بعد',
    'pk_code' => array('minutes_no', 'SHO'),
    'create' => array('site_ref', 'handover_date', 'shift_out', 'shift_in', 'custody_handed',
                      'open_notes_carried', 'meter_readings', 'signature_out', 'signature_in'),
    'keys' => array('minutes_no', 'site_ref', 'handover_date', 'shift_out', 'supervisor_out',
                    'shift_in', 'supervisor_in', 'equipment_running', 'equipment_stopped',
                    'custody_handed', 'open_notes_carried', 'meter_readings', 'signature_out',
                    'signature_in', 'minutes_state', 'created_by', 'created_at', 'data_state',
                    'src_ref'),
),
array(
    'code' => 'site_state_request', 'file' => 'site_state_requests.php', 'placement_id' => 260,
    'surface' => 'طلبات تغيير الحالة ومعالجة المتعثر', 'title' => 'طلبات تغيير الحالة ومعالجة المتعثر',
    'icon' => 'fa fa-arrows-rotate',
    'table' => 'site_state_change_request', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'المعالجة الميدانية', 'sort_no' => 1,
    'grain' => 'طلبُ تغييرِ حالةٍ واحدٌ على عنصرٍ واحد',
    'target_ref' => 'DEP-12·10·طلبات تغيير الحاله ومعالجه المتعثر',
    'intro' => 'طلبُ تحويلِ حالةِ عنصرٍ ميدانيٍّ بسببِه ودليلِه وأولويتِه',
    'rule'  => 'الجهةُ المالكةُ للقرارِ تُشتقُّ من نوعِ الطلبِ — ولا حالةَ تتحوّل بلا طلبٍ مقيَّد',
    'empty' => 'لا طلبَ تغييرِ حالةٍ مسجَّلٌ بعد',
    'pk_code' => array('request_no', 'SSR'),
    'create' => array('site_ref', 'request_date', 'request_type', 'target_state', 'reason',
                      'priority', 'evidence_ref'),
    'keys' => array('request_no', 'site_ref', 'request_date', 'request_type', 'subject_ref',
                    'current_state', 'target_state', 'reason', 'priority', 'evidence_ref',
                    'decision_owner', 'ticket_ref', 'request_state', 'created_by', 'created_at',
                    'data_state', 'src_ref'),
),
array(
    'code' => 'site_request_items', 'file' => 'site_request_items.php', 'placement_id' => 261,
    'surface' => 'بنود طلب الموقع', 'title' => 'بنود طلب الموقع', 'icon' => 'fa fa-list-ol',
    'table' => 'site_request_item', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'المعالجة الميدانية', 'sort_no' => 2,
    'grain' => 'بندُ صنفٍ واحدٌ في طلبِ موقع',
    'target_ref' => 'DEP-12·11·بنود طلب الموقع',
    'intro' => 'بنودُ طلبِ الموقعِ بكمياتِها والمستلَمِ تراكميًّا والمتبقّي',
    'rule'  => 'المتبقّي يُشتقُّ من المطلوبِ والمستلَمِ ولا يُكتب — والبندُ ابنُ طلبِه',
    'empty' => 'لا بندَ مسجَّلٌ بعد',
    'pk_code' => array('item_code', 'SRI'),
    'create' => array('request_ref', 'item_ref', 'requested_qty', 'item_state'),
    'keys' => array('item_code', 'request_ref', 'item_ref', 'requested_qty', 'uom',
                    'received_cumulative', 'remaining', 'item_state', 'created_by', 'created_at',
                    'data_state', 'src_ref'),
    'types' => array('requested_qty' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'received_cumulative' => 'DECIMAL(18,3) NULL DEFAULT NULL',
                     'remaining' => 'DECIMAL(18,3) NULL DEFAULT NULL'),
),
array(
    'code' => 'site_supply_request', 'file' => 'site_supply_requests.php', 'placement_id' => 262,
    'surface' => 'طلبات الموقع للصرف والاستلام', 'title' => 'طلبات الموقع للصرف والاستلام',
    'icon' => 'fa fa-truck-ramp-box',
    'table' => 'site_supply_request', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'المعالجة الميدانية', 'sort_no' => 3,
    'grain' => 'طلبُ صرفٍ واحدٌ من موقعٍ إلى مخزن',
    'target_ref' => 'DEP-12·12·طلبات الموقع للصرف والاستلام',
    'intro' => 'طلباتُ الموقعِ من المخازنِ بمبرِّرها ومستلِمِ عهدتِها ومطابقةِ استلامِها',
    'rule'  => 'سندُ الصرفِ يُقرأ من المخازنِ ولا يُنشأ هنا — والمطابقةُ حكمٌ مكتوب',
    'empty' => 'لا طلبَ صرفٍ مسجَّلٌ بعد',
    'pk_code' => array('request_no', 'SSQ'),
    'create' => array('site_ref', 'request_date', 'request_type', 'items_text', 'quantities',
                      'justification', 'actual_receipt_date', 'receipt_match'),
    'keys' => array('request_no', 'site_ref', 'request_date', 'request_type', 'warehouse_ref',
                    'items_text', 'quantities', 'justification', 'custody_receiver',
                    'issue_voucher_ref', 'actual_receipt_date', 'receipt_match', 'request_state',
                    'created_by', 'created_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'site_request_batch', 'file' => 'site_request_batches.php', 'placement_id' => 263,
    'surface' => 'دفعات استلام طلب الموقع', 'title' => 'دفعات استلام طلب الموقع',
    'icon' => 'fa fa-boxes-stacked',
    'table' => 'site_request_batch', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'المعالجة الميدانية', 'sort_no' => 4,
    'grain' => 'دفعةُ استلامٍ واحدةٌ على طلبِ موقع',
    'target_ref' => 'DEP-12·13·دفعات استلام طلب الموقع',
    'intro' => 'دفعاتُ الاستلامِ على الطلبِ الواحدِ بتسلسلِها وسندِ صرفِها ومطابقتِها',
    'rule'  => 'الطلبُ يُستلَم دفعاتٍ — وكلُّ دفعةٍ بسندِها ومطابقتِها لا بجمعٍ في آخرِه',
    'empty' => 'لا دفعةَ استلامٍ مسجَّلةٌ بعد',
    'pk_code' => array('batch_code', 'SRB'),
    'create' => array('request_ref', 'batch_seq', 'receipt_date', 'batch_match', 'batch_state'),
    'keys' => array('batch_code', 'request_ref', 'batch_seq', 'issue_voucher_ref',
                    'received_items', 'receipt_date', 'custody_receiver', 'batch_match',
                    'batch_state', 'created_by', 'created_at', 'data_state', 'src_ref'),
),
array(
    'code' => 'site_field_expense', 'file' => 'site_field_expense.php', 'placement_id' => 265,
    'surface' => 'صرف المشتريات الميدانية من العهدة', 'title' => 'صرف المشتريات الميدانية من العهدة',
    'icon' => 'fa fa-receipt',
    'table' => 'tre_petty_expense', 'table_mode' => 'extend', 'nature' => 'read',
    'group' => 'المعالجة الميدانية', 'sort_no' => 5,
    'grain' => 'صرفٌ ميدانيٌّ واحدٌ من عهدةٍ واحدة',
    'target_ref' => 'DEP-12·15·صرف المشتريات الميدانيه من العهده',
    'intro' => 'المصروفُ الميدانيُّ من العهدةِ بمبرِّرِه ومستندِه ومورِّدِه المحلّي',
    'rule'  => 'حبّةُ العهدةِ مملوكةٌ للخزينةِ والتسويةُ عندها — فهذه الشاشةُ تقرأ ولا تكتب (§17)',
    'empty' => 'لا صرفَ ميدانيٌّ مسجَّلٌ بعد',
    'order' => 'expense_date DESC, id DESC',
    'pk_code' => array('expense_no', 'SFE'),
    'keys' => array('expense_no', 'custody_id', 'site_ref', 'expense_date', 'expense_item',
                    'description', 'amount', 'currency_ref', 'field_justification', 'doc_ref',
                    'local_supplier', 'charged_to', 'over_limit', 'override_approval_ref',
                    'treasury_settlement_ref', 'state', 'created_by', 'created_at', 'reviewer',
                    'approved_by', 'approved_at', 'data_state', 'src_ref'),
    'dc' => array('amount' => 'DC-2', 'charged_to' => 'DC-2', 'treasury_settlement_ref' => 'DC-2'),
),
array(
    'code' => 'site_day_close', 'file' => 'site_day_close_report.php', 'placement_id' => 266,
    'surface' => 'تقرير إقفال يوم الموقع', 'title' => 'تقرير إقفال يوم الموقع',
    'icon' => 'fa fa-file-circle-check',
    'table' => 'site_day_close_report', 'table_mode' => 'create', 'nature' => 'read',
    'group' => 'الإقفال والسجلات', 'sort_no' => 1,
    'grain' => 'تقريرُ إقفالٍ واحدٌ ليومِ موقع',
    'target_ref' => 'DEP-12·16·تقرير اقفال يوم الموقع',
    'intro' => 'إقفالُ اليومِ بملخّصِ حضورِه وساعاتِه وسلامتِه وبلاغاتِه ومحاضرِه',
    'rule'  => 'التقريرُ إسقاطٌ من يومِ الموقعِ ووردياتِه — لا مصدرَ حقيقةٍ ولا يُحرَّر (§19)',
    'empty' => 'لا تقريرَ إقفالٍ مولَّدٌ بعد',
    'keys' => array('report_code', 'site_ref', 'report_date', 'attendance_summary',
                    'equipment_worked', 'units_approved', 'actual_hours', 'stop_hours',
                    'hse_state', 'incidents', 'stop_work_events', 'permits_validity',
                    'day_tickets', 'day_minutes', 'signed_pdf_ref', 'day_state'),
    'types' => array('actual_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'stop_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'report_date' => 'DATE NULL DEFAULT NULL'),
),
array(
    'code' => 'site_suspension', 'file' => 'site_suspension.php', 'placement_id' => 267,
    'surface' => 'الإيقاف المؤقت للموقع — بحسب انطباق الشركة',
    'title' => 'الإيقاف المؤقت للموقع', 'icon' => 'fa fa-circle-stop',
    'table' => 'site_suspension', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'الإقفال والسجلات', 'sort_no' => 2,
    'grain' => 'قرارُ إيقافٍ مؤقّتٍ واحدٌ لموقع',
    'target_ref' => 'DEP-12·17·الايقاف المؤقت للموقع — بحسب انطباق الشركه',
    'intro' => 'إيقافُ الموقعِ مؤقّتًا بسببِه ومدّتِه وأثرِه على المواردِ والعقد',
    'rule'  => 'أثرُ العقدِ يُقرأ من التعاقدِ ولا يُقدَّر — والاستئنافُ بمحضرٍ لا بصمت',
    'empty' => 'لا قرارَ إيقافٍ مؤقّتٍ مسجَّلٌ بعد',
    'pk_code' => array('decision_no', 'SSP'),
    'create' => array('site_ref', 'suspension_reason', 'from_date', 'expected_duration',
                      'decision_state'),
    'keys' => array('decision_no', 'site_ref', 'suspension_reason', 'from_date',
                    'expected_duration', 'resource_effect', 'contract_effect',
                    'parties_notified', 'resumption_minutes', 'decision_state', 'created_by',
                    'created_at', 'reviewer', 'approved_by', 'approved_at', 'data_state',
                    'src_ref'),
    'types' => array('expected_duration' => 'VARCHAR(80) NULL DEFAULT NULL'),
),
array(
    'code' => 'site_closure', 'file' => 'site_closure_items.php', 'placement_id' => 268,
    'surface' => 'إغلاق الموقع وتسريحه — بحسب انطباق الشركة',
    'title' => 'إغلاق الموقع وتسريحه', 'icon' => 'fa fa-flag-checkered',
    'table' => 'site_closure_item', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'الإقفال والسجلات', 'sort_no' => 3,
    'grain' => 'بندُ إغلاقٍ واحدٌ على موقعٍ واحد',
    'target_ref' => 'DEP-12·18·اغلاق الموقع وتسريحه — بحسب انطباق الشركه',
    'intro' => 'بنودُ إغلاقِ الموقعِ وتسريحِه ونتائجُها ومحضرُ التسليمِ النهائي',
    'rule'  => 'لا إغلاقَ بمحضرٍ نهائيٍّ وبندٌ واحدٌ مفتوح',
    'empty' => 'لا بندَ إغلاقٍ مسجَّلٌ بعد',
    'pk_code' => array('item_code', 'SCL'),
    'create' => array('site_ref', 'closure_item', 'owner_ref', 'result', 'item_state'),
    'keys' => array('item_code', 'site_ref', 'closure_item', 'owner_ref', 'completion_ref',
                    'result', 'final_handover_minutes', 'item_state', 'created_by', 'created_at',
                    'data_state', 'src_ref'),
),
array(
    'code' => 'site_ref_registry', 'file' => 'site_reference_registry.php', 'placement_id' => 269,
    'surface' => 'سجلات الموقع المرجعية', 'title' => 'سجلات الموقع المرجعية', 'icon' => 'fa fa-book',
    'table' => 'site_reference_registry', 'table_mode' => 'create', 'nature' => 'read',
    'group' => 'الإقفال والسجلات', 'sort_no' => 4,
    'grain' => 'سطرُ مرجعٍ واحدٌ يخدم الموقع',
    'target_ref' => 'DEP-12·19·سجلات الموقع المرجعيه',
    'intro' => 'المراجعُ التي يقرؤها الموقعُ بمالكِ كلٍّ ونطاقِ الاطّلاعِ عليه',
    'rule'  => 'المرجعُ يُقرأ عند مالكِه — والسطرُ هنا دالٌّ لا نسخة (§17 · §19)',
    'empty' => 'لا مرجعَ مسجَّلٌ بعد',
    'keys' => array('row_code', 'reference_type', 'reference_ref', 'reference_owner',
                    'last_updated_on', 'access_scope'),
    'types' => array('last_updated_on' => 'DATETIME NULL DEFAULT NULL'),
),

));
