<?php
/**
 * tools/specs/dep14_maintenance.php — مواصفةُ `DEP-14` الصيانة (GOV_EXEC §5)
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **شجرةُ الأعطالِ مبنيّةٌ سلفًا**: `failure_codes` (402 صفًّا) تحمل الهرمَ
 *   الثلاثيَّ (نوعُ الحدثِ ← الفئةُ الرئيسيةُ ← الفرعيةُ ← التفصيل)، و
 *   `unified_fault_taxonomy` **منظرٌ عليها لا جدولٌ ثانٍ**. فالسطحُ يُبنى
 *   فوقَها وتُستكمل بآثارِها الثلاثةِ (الفوترةُ ووحدةُ المورِّدِ وأجرُ المشغّل)
 *   وبحكمِ إيقافِها الجاهزية — ⛔ ولا تُنشأ شجرةٌ رابعة.
 *
 * ◆ **وأربعُ حبّاتٍ قائمةٍ تُستكمل**: `mnt_inspection` · `mnt_order` ·
 *   `mnt_order_labor` · `mnt_return_cert`.
 *
 * ◆ **وسطحان بحبّةٍ لا مالكَ لها**: تقطيعُ مسؤوليةِ التوقّفِ (قطاعٌ من واقعةِ
 *   توقّف) وطلبُ الفحصِ والتشخيصِ (فحصٌ يسبق أمرَ العمل).
 */
return array(
    'dept'    => 'DEP-14',
    'dept_ar' => 'إدارة الصيانة',
    'unit'    => 'إدارة الصيانة',
    'role_id' => 13,
    'dir'     => 'maintenance',
    'neighbor_route' => 'maintenance/breakdown_intake.php',
    'screens' => array(

array(
    'code' => 'mnt_fault_tree', 'file' => 'fault_tree.php', 'placement_id' => 288,
    'surface' => 'شجرة الأعطال المرجعية', 'title' => 'شجرة الأعطال المرجعية', 'icon' => 'fa fa-network-wired',
    'table' => 'failure_codes', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'التأسيس المرجعي', 'sort_no' => 1,
    'grain' => 'عقدةُ عطلٍ واحدةٌ في الشجرةِ المرجعية',
    'target_ref' => 'DEP-14·2·شجره الاعطال المرجعيه',
    'intro' => 'شجرةُ الأعطالِ بمستوياتِها وآثارِها: الفوترةُ ووحدةُ المورِّدِ وأجرُ المشغّلِ وإيقافُ الجاهزية',
    'rule'  => 'الشجرةُ مصدرٌ واحدٌ لكلِّ الأسطح — و`unified_fault_taxonomy` منظرٌ عليها لا جدولٌ ثانٍ (§7)',
    'empty' => 'لا عقدةَ عطلٍ مسجَّلةٌ بعد',
    'order' => 'full_code ASC, id ASC',
    'create' => array('full_code', 'node_level', 'parent_node', 'failure_detail', 'node_desc',
                      'billing_effect', 'supplier_unit_effect', 'operator_wage_effect',
                      'stops_readiness', 'status'),
    'keys' => array('full_code', 'node_level', 'parent_node', 'failure_detail', 'node_desc',
                    'billing_effect', 'supplier_unit_effect', 'operator_wage_effect',
                    'stops_readiness', 'status', 'created_by', 'created_at', 'data_state',
                    'src_ref'),
    'dc' => array('billing_effect' => 'DC-2', 'supplier_unit_effect' => 'DC-2'),
),
array(
    'code' => 'mnt_fleet_inspections', 'file' => 'fleet_inspection_orders.php', 'placement_id' => 291,
    'surface' => 'أوامر التفتيش الواردة من الأسطول', 'title' => 'أوامر التفتيش الواردة من الأسطول',
    'icon' => 'fa fa-inbox',
    'table' => 'mnt_inspection', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'دورة العطل', 'sort_no' => 2,
    'grain' => 'أمرُ تفتيشٍ واحدٌ واردٌ من الأسطول',
    'target_ref' => 'DEP-14·5·اوامر التفتيش الوارده من الاسطول',
    'intro' => 'أوامرُ التفتيشِ الواردةُ من الأسطولِ بفاحصِها وموعدِ تنفيذِها ونتيجتِها وبطاقتِها المعادة',
    'rule'  => 'أمرُ التفتيشِ يُنشَأ عند الأسطولِ ويُنفَّذ هنا — والبطاقةُ تعود إليه بمرجعِها (§17)',
    'empty' => 'لا أمرَ تفتيشٍ واردٌ بعد',
    'where' => 'is_deleted = 0',
    'order' => 'scheduled_date DESC, id DESC',
    'pk_code' => array('row_code', 'MFI'),
    'create' => array('fleet_order_ref', 'equipment_id', 'scheduled_date', 'overall_result',
                      'returned_card_ref', 'row_state'),
    'keys' => array('row_code', 'fleet_order_ref', 'equipment_id', 'inspection_type',
                    'inspector_id', 'scheduled_date', 'completed_at', 'overall_result',
                    'returned_card_ref', 'row_state', 'created_by', 'created_at', 'data_state',
                    'src_ref'),
),
array(
    'code' => 'mnt_downtime_seg', 'file' => 'downtime_segments.php', 'placement_id' => 292,
    'surface' => 'تقطيع مسؤولية التوقف', 'title' => 'تقطيع مسؤولية التوقف', 'icon' => 'fa fa-scissors',
    'table' => 'mnt_downtime_segment', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'دورة العطل', 'sort_no' => 3,
    'grain' => 'قطاعُ مسؤوليةٍ واحدٌ داخلَ واقعةِ توقّف',
    'target_ref' => 'DEP-14·6·تقطيع مسؤوليه التوقف',
    'intro' => 'تقسيمُ زمنِ التوقّفِ قطاعاتٍ بمالكِ كلٍّ ونسبتِه وإقرارِه أو تنازعِه',
    'rule'  => 'المتنازَعُ عليه يُحسَم بحكمِ مديرِ التشغيلِ — ولا نسبةَ تُحمَّل بلا إقرارٍ أو حكم',
    'empty' => 'لا قطاعَ توقّفٍ مسجَّلٌ بعد',
    'pk_code' => array('segment_code', 'MDS'),
    'create' => array('stop_event_ref', 'equipment_ref', 'segment_seq', 'segment_kind',
                      'segment_reason', 'owner_ack', 'segment_state'),
    'keys' => array('segment_code', 'stop_event_ref', 'equipment_ref', 'segment_seq',
                    'segment_kind', 'segment_owner', 'segment_start', 'segment_end',
                    'segment_duration', 'segment_share_pct', 'segment_reason', 'owner_ack',
                    'is_disputed', 'ops_manager_ruling', 'recurrence_case_ref', 'segment_state',
                    'created_by', 'created_at', 'data_state', 'src_ref'),
    'types' => array('segment_seq' => 'INT NULL DEFAULT NULL',
                     'segment_start' => 'DATETIME NULL DEFAULT NULL',
                     'segment_end' => 'DATETIME NULL DEFAULT NULL',
                     'segment_duration' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'segment_share_pct' => 'DECIMAL(8,2) NULL DEFAULT NULL'),
),
array(
    'code' => 'mnt_diagnosis', 'file' => 'diagnosis_requests.php', 'placement_id' => 293,
    'surface' => 'طلب الفحص والتشخيص', 'title' => 'طلب الفحص والتشخيص', 'icon' => 'fa fa-stethoscope',
    'table' => 'mnt_diagnosis_request', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'دورة العطل', 'sort_no' => 4,
    'grain' => 'فحصٌ وتشخيصٌ واحدٌ يسبق أمرَ عمل',
    'target_ref' => 'DEP-14·7·طلب الفحص والتشخيص',
    'intro' => 'الفحصُ والتشخيصُ بعقدةِ الشجرةِ النهائيةِ والقطعِ المتوقَّعةِ وزمنِ الإصلاحِ التقديري',
    'rule'  => 'عقدةُ الشجرةِ النهائيةُ من الشجرةِ المرجعيةِ وحدَها — ولا أمرَ عملٍ بلا تشخيصٍ مقيَّد',
    'empty' => 'لا طلبَ فحصٍ مسجَّلٌ بعد',
    'order' => 'inspect_date DESC, id DESC',
    'pk_code' => array('diagnosis_no', 'MDR'),
    'create' => array('intake_ref', 'equipment_ref', 'inspector_ref', 'inspect_date',
                      'meter_at_inspect', 'final_tree_node', 'diagnosis_desc', 'expected_parts',
                      'estimated_repair_time', 'repair_place', 'needs_warranty_supplier',
                      'inspect_result'),
    'keys' => array('diagnosis_no', 'intake_ref', 'equipment_ref', 'inspector_ref',
                    'inspect_date', 'meter_at_inspect', 'final_tree_node', 'diagnosis_desc',
                    'expected_parts', 'estimated_repair_time', 'repair_place',
                    'needs_warranty_supplier', 'inspect_result', 'created_by', 'created_at',
                    'data_state', 'src_ref'),
    'types' => array('estimated_repair_time' => 'DECIMAL(10,2) NULL DEFAULT NULL'),
),
array(
    'code' => 'mnt_work_order', 'file' => 'work_orders.php', 'placement_id' => 294,
    'surface' => 'أمر العمل', 'title' => 'أمر العمل', 'icon' => 'fa fa-screwdriver-wrench',
    'table' => 'mnt_order', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'دورة العطل', 'sort_no' => 5,
    'grain' => 'أمرُ عملٍ واحدٌ على معدّة',
    'target_ref' => 'DEP-14·8·امر العمل',
    'intro' => 'أوامرُ العملِ بمصدرِها وأولويتِها وفنيِّها وزمنِها المخطَّطِ وتكلفةِ قطعِها التقديرية',
    'rule'  => 'الأمرُ يتبع تشخيصًا مقيَّدًا — وعمالتُه تفصَّل في سطحِها لا في سطرِه',
    'empty' => 'لا أمرَ عملٍ مسجَّلٌ بعد',
    'where' => 'is_deleted = 0',
    'order' => 'created_at DESC, id DESC',
    'create' => array('open_date', 'source', 'diagnosis_ref', 'equipment_id', 'maint_type',
                      'priority', 'workshop', 'planned_time', 'target_finish_date', 'state',
                      'reviewer', 'approved_at'),
    'keys' => array('code', 'open_date', 'source', 'diagnosis_ref', 'equipment_id',
                    'equipment_type_ref', 'site_ref', 'tree_node_ref', 'maint_type', 'priority',
                    'workshop', 'technician_id', 'order_labor_summary', 'meter_at_open',
                    'planned_time', 'target_finish_date', 'accumulated_downtime_hours',
                    'estimated_parts_cost', 'state', 'created_by', 'created_at', 'reviewer',
                    'approved_by', 'approved_at', 'data_state', 'src_ref'),
    'types' => array('open_date' => 'DATE NULL DEFAULT NULL',
                     'planned_time' => 'DECIMAL(10,2) NULL DEFAULT NULL',
                     'target_finish_date' => 'DATE NULL DEFAULT NULL',
                     'accumulated_downtime_hours' => 'DECIMAL(12,2) NULL DEFAULT NULL',
                     'estimated_parts_cost' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'meter_at_open' => 'DECIMAL(12,2) NULL DEFAULT NULL'),
    'dc' => array('estimated_parts_cost' => 'DC-2'),
),
array(
    'code' => 'mnt_order_labor', 'file' => 'work_order_labor.php', 'placement_id' => 295,
    'surface' => 'عمالة أمر العمل', 'title' => 'عمالة أمر العمل', 'icon' => 'fa fa-user-gear',
    'table' => 'mnt_order_labor', 'table_mode' => 'extend', 'nature' => 'register',
    'group' => 'دورة العطل', 'sort_no' => 6,
    'grain' => 'سطرُ عمالةِ فنيٍّ واحدٍ على أمرِ عملٍ في يوم',
    'target_ref' => 'DEP-14·9·عماله امر العمل',
    'intro' => 'ساعاتُ الفنيين على أمرِ العملِ بأدوارِهم وملاحظاتِهم الفنية',
    'rule'  => 'العمالةُ تفصَّل هنا ويُلخَّص مجموعُها في الأمرِ — ولا يُدخَل المجموعُ يدويًّا',
    'empty' => 'لا سطرَ عمالةٍ مسجَّلٌ بعد',
    'order' => 'id DESC',
    'pk_code' => array('row_code', 'MOL'),
    'create' => array('order_id', 'employee_id', 'role', 'labor_date', 'hours', 'tech_note',
                      'row_state'),
    'keys' => array('row_code', 'order_id', 'employee_id', 'role', 'labor_date', 'hours',
                    'tech_note', 'row_state', 'created_by', 'created_at', 'data_state', 'src_ref'),
    'types' => array('labor_date' => 'DATE NULL DEFAULT NULL'),
),
array(
    'code' => 'mnt_return_cert', 'file' => 'return_to_service_cert.php', 'placement_id' => 301,
    'surface' => 'الإقفال وشهادة إعادة الخدمة', 'title' => 'الإقفال وشهادة إعادة الخدمة',
    'icon' => 'fa fa-certificate',
    'table' => 'mnt_return_cert', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'الإقفال والجاهزية', 'sort_no' => 1,
    'grain' => 'شهادةُ إعادةِ خدمةٍ واحدةٌ لأمرِ عمل',
    'target_ref' => 'DEP-14·15·الاقفال وشهاده اعاده الخدمه',
    'intro' => 'إقفالُ أمرِ العملِ بشهادةِ إعادةِ الخدمةِ واختبارِها ونتيجتِها وقيودِ التشغيلِ بعدها',
    'rule'  => 'الحالةُ الفنيةُ الجديدةُ لا تُعلَن إلا باختبارٍ منفَّذٍ ونتيجتِه — والقيودُ تُكتب لا تُفترَض',
    'empty' => 'لا شهادةَ إعادةِ خدمةٍ مسجَّلةٌ بعد',
    'order' => 'id DESC',
    'create' => array('order_id', 'equipment_id', 'tech_complete_date', 'test_performed',
                      'test_result', 'meter_at_close', 'new_readiness_state', 'operating_limits',
                      'cert_validity', 'signed_by', 'state', 'reviewed_by', 'approved_at'),
    'keys' => array('cert_no', 'order_id', 'equipment_id', 'tech_complete_date',
                    'test_performed', 'test_result', 'meter_at_close', 'downtime_hours',
                    'actual_cost', 'new_readiness_state', 'operating_limits', 'cert_validity',
                    'signed_by', 'state', 'created_by', 'created_at', 'reviewed_by',
                    'approved_by', 'approved_at', 'data_state', 'src_ref'),
    'types' => array('cert_validity' => 'VARCHAR(80) NULL DEFAULT NULL'),
    'dc' => array('actual_cost' => 'DC-2'),
),

));
