<?php
/**
 * tools/specs/exceo_leadership.php — مواصفةُ `EX-CEO` مساحةُ الرئيس (GOV_EXEC §5 · §6)
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **مساحةُ القيادةِ ليست إدارةً عادية** (§6): إسقاطاتٌ وأسطحُ قرار — **ولا
 *   مصدرَ حقيقةِ معاملاتٍ جديد**. فالاعتماداتُ الماليةُ واعتماداتُ الوثائقِ
 *   حقولُها **مشتقّةٌ كلُّها** من المعاملةِ الأصليّةِ عند إدارتِها، ولا يُكتب
 *   في هذه الأسطحِ إلا **القرارُ وشروطُه وتاريخُه** — وهو أثرُ القيادةِ نفسِها.
 *
 * ◆ **وثلاثُ حبّاتٍ قائمةٍ تُستكمل**: `exec_approvals` (الاعتماداتُ الماليّة) ·
 *   `exec_contract_signings` (اعتماداتُ العقودِ والوثائق) · `exec_assignments`
 *   (التكليفاتُ والإناباتُ المؤقتة).
 *
 * ◆ **وسطحان بحبّةٍ لا مالكَ لها**: ملاحظاتُ مراجعةِ الوثيقةِ قبلَ التوقيع
 *   (ملاحظةٌ على وثيقةٍ) واجتماعاتُ الإدارةِ العليا (اجتماعٌ واحد).
 */
return array(
    'dept'    => 'EX-CEO',
    'dept_ar' => 'مساحة الرئيس التنفيذي',
    'unit'    => 'مساحة الرئيس التنفيذي',
    'role_id' => 9,
    'dir'     => 'portal',
    'neighbor_route' => 'portal/exec_contract_registry.php',
    'screens' => array(

array(
    'code' => 'exec_fin_approvals', 'file' => 'exec_financial_approvals.php', 'placement_id' => 1879,
    'surface' => 'الاعتمادات المالية', 'title' => 'الاعتمادات المالية', 'icon' => 'fa fa-file-invoice-dollar',
    'table' => 'exec_approvals', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'صناديق القرار', 'sort_no' => 2,
    'grain' => 'بندُ اعتمادٍ ماليٍّ واحدٌ مرفوعٌ للرئيس',
    'target_ref' => 'EX-CEO·9·الاعتمادات الماليه',
    'intro' => 'الاعتماداتُ الماليةُ المرفوعةُ: قاعدةُ المصفوفةِ المفعِّلةُ والمستوياتُ السابقةُ وقرارُ الرئيسِ بشروطِه',
    'rule'  => 'كلُّ حقلٍ يصف المعاملةَ مشتقٌّ من إدارتِها — والمكتوبُ هنا القرارُ وشروطُه وتاريخُه وحدَها (§6)',
    'empty' => 'لا بندَ اعتمادٍ ماليٍّ مرفوعٌ بعد',
    'order' => 'received_date DESC, id DESC',
    'pk_code' => array('item_code', 'EFA'),
    'create' => array('ceo_decision', 'decision_conditions', 'decision_date'),
    'keys' => array('item_code', 'item_category', 'item_kind', 'source_dept', 'txn_ref',
                    'amount', 'currency', 'project_ref', 'budget_status', 'matrix_rule_ref',
                    'prior_levels', 'deputy_recommendation', 'finance_review_status',
                    'risk_level', 'ceo_decision', 'decision_conditions', 'decision_date',
                    'created_by', 'created_at', 'data_state', 'src_ref'),
    'types' => array('decision_date' => 'DATE NULL DEFAULT NULL',
                     'project_ref' => 'VARCHAR(120) NULL DEFAULT NULL'),
    'dc' => array('amount' => 'DC-2', 'budget_status' => 'DC-2', 'finance_review_status' => 'DC-2'),
),
array(
    'code' => 'exec_doc_approvals', 'file' => 'exec_document_approvals.php', 'placement_id' => 1880,
    'surface' => 'اعتمادات العقود والوثائق', 'title' => 'اعتمادات العقود والوثائق',
    'icon' => 'fa fa-file-signature',
    'table' => 'exec_contract_signings', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'صناديق القرار', 'sort_no' => 3,
    'grain' => 'وثيقةٌ واحدةٌ معروضةٌ لتوقيعِ الرئيس',
    'target_ref' => 'EX-CEO·10·اعتمادات العقود والوثائق',
    'intro' => 'الوثائقُ المعروضةُ للتوقيعِ بمراجعاتِها القانونيةِ والماليةِ والالتزاميةِ واستثناءاتِها',
    'rule'  => 'حالةُ التوقيعِ وحدَها تُكتب هنا — وكلُّ ما عداها مشتقٌّ من الوثيقةِ عند مالكِها (§6)',
    'empty' => 'لا وثيقةٌ معروضةٌ للتوقيعِ بعد',
    'order' => 'signing_date DESC, id DESC',
    'pk_code' => array('document_ref', 'EDA'),
    'create' => array('ceo_signature_status', 'delegation_ref'),
    'keys' => array('document_ref', 'document_type', 'owning_department', 'counterparty_ref',
                    'doc_value', 'doc_currency', 'doc_term', 'key_obligations',
                    'legal_review_status', 'financial_review_status', 'compliance_status',
                    'previous_approvals', 'doc_exceptions', 'final_document_link',
                    'ceo_signature_status', 'delegation_ref', 'created_by', 'created_at',
                    'data_state', 'src_ref'),
    'types' => array('doc_value' => 'DECIMAL(18,2) NULL DEFAULT NULL'),
    'dc' => array('doc_value' => 'DC-2', 'legal_review_status' => 'DC-3',
                  'compliance_status' => 'DC-3', 'key_obligations' => 'DC-3'),
),
array(
    'code' => 'exec_doc_review_notes', 'file' => 'exec_doc_review_notes.php', 'placement_id' => 1881,
    'surface' => 'ملاحظات مراجعة الوثيقة قبل التوقيع', 'title' => 'ملاحظات مراجعة الوثيقة قبل التوقيع',
    'icon' => 'fa fa-triangle-exclamation',
    'table' => 'exec_doc_review_note', 'table_mode' => 'create', 'nature' => 'document',
    'group' => 'صناديق القرار', 'sort_no' => 4,
    'grain' => 'ملاحظةُ مراجعةٍ واحدةٌ على وثيقةٍ قبلَ توقيعِها',
    'target_ref' => 'EX-CEO·11·ملاحظات مراجعه الوثيقه قبل التوقيع',
    'intro' => 'ملاحظاتُ المراجعينَ قبلَ التوقيعِ بدرجتِها وقيمتِها المعرَّضةِ وهل تحجب الاعتماد',
    'rule'  => 'الملاحظةُ الحاجبةُ تمنع التوقيعَ حتى تُقفَل بمستندِ معالجتِها — ولا توقيعَ فوقَ حاجب',
    'empty' => 'لا ملاحظةَ مراجعةٍ مسجَّلةٌ بعد',
    'order' => 'observed_date DESC, id DESC',
    'pk_code' => array('note_no', 'EDN'),
    'create' => array('document_ref', 'entity_ref', 'observed_date', 'observer_party',
                      'note_kind', 'note_grade', 'note_desc', 'potential_impact',
                      'value_at_risk', 'blocks_approval', 'required_action', 'action_deadline',
                      'action_document', 'note_state'),
    'keys' => array('note_no', 'document_ref', 'entity_ref', 'observed_date', 'observer_party',
                    'note_kind', 'note_grade', 'affected_clause', 'note_desc',
                    'potential_impact', 'value_at_risk', 'currency_ref', 'blocks_approval',
                    'required_action', 'action_owner', 'action_deadline', 'action_document',
                    'closed_date', 'note_state', 'created_by', 'created_at', 'data_state',
                    'src_ref'),
    'types' => array('value_at_risk' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'action_deadline' => 'DATE NULL DEFAULT NULL'),
    'dc' => array('value_at_risk' => 'DC-2', 'note_kind' => 'DC-3'),
),
array(
    'code' => 'exec_assignments', 'file' => 'exec_temp_assignments.php', 'placement_id' => 1892,
    'surface' => 'التكليفات والإنابات المؤقتة', 'title' => 'التكليفات والإنابات المؤقتة',
    'icon' => 'fa fa-user-clock',
    'table' => 'exec_assignments', 'table_mode' => 'extend', 'nature' => 'document',
    'group' => 'القرار والحوكمة العليا', 'sort_no' => 4,
    'grain' => 'تكليفٌ أو إنابةٌ مؤقّتةٌ واحدةٌ لشخصٍ في مدّة',
    'target_ref' => 'EX-CEO·22·التكليفات والانابات المؤقته',
    'intro' => 'التكليفاتُ والإناباتُ بصلاحياتِها وسقفِ اعتمادِها وما لا تشمله ومدّتِها',
    'rule'  => 'الإنابةُ بسقفٍ مكتوبٍ وما لا تشمله مكتوبٌ صراحةً — والفراغُ ليس تفويضًا',
    'empty' => 'لا تكليفَ مؤقّتٌ مسجَّلٌ بعد',
    'order' => 'effective_from DESC, id DESC',
    'pk_code' => array('assignment_code', 'ETA'),
    'create' => array('entity_ref', 'assignment_kind', 'assignee_person_ref', 'position_scope',
                      'granted_authorities', 'approval_cap', 'assignment_allowance',
                      'excluded_scope', 'from_date', 'to_date', 'assignment_state'),
    'keys' => array('assignment_code', 'entity_ref', 'assignment_kind', 'assignee_person_ref',
                    'position_scope', 'granted_authorities', 'approval_cap',
                    'assignment_allowance', 'excluded_scope', 'from_date', 'to_date',
                    'governance_registry_ref', 'assignment_state', 'created_by', 'created_at',
                    'data_state', 'src_ref'),
    'types' => array('approval_cap' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'assignment_allowance' => 'DECIMAL(18,2) NULL DEFAULT NULL',
                     'from_date' => 'DATE NULL DEFAULT NULL', 'to_date' => 'DATE NULL DEFAULT NULL'),
    'dc' => array('approval_cap' => 'DC-2', 'assignment_allowance' => 'DC-2',
                  'granted_authorities' => 'DC-3', 'excluded_scope' => 'DC-3'),
),
array(
    'code' => 'exec_meetings', 'file' => 'exec_leadership_meetings.php', 'placement_id' => 1894,
    'surface' => 'اجتماعات الإدارة العليا', 'title' => 'اجتماعات الإدارة العليا', 'icon' => 'fa fa-users-line',
    'table' => 'exec_meeting', 'table_mode' => 'create', 'nature' => 'register',
    'group' => 'القرار والحوكمة العليا', 'sort_no' => 6,
    'grain' => 'اجتماعُ إدارةٍ عليا واحدٌ',
    'target_ref' => 'EX-CEO·24·اجتماعات الاداره العليا',
    'intro' => 'اجتماعاتُ الإدارةِ العليا بجداولِ أعمالِها ووثائقِها وحالةِ محاضرِها',
    'rule'  => 'قراراتُ الاجتماعِ تُقيَّد في سطحِها ومحضرُه لا يُغلَق بلا حالةٍ مسجَّلة',
    'empty' => 'لا اجتماعَ مسجَّلٌ بعد',
    'order' => 'meeting_date DESC, id DESC',
    'pk_code' => array('meeting_code', 'EMT'),
    'create' => array('meeting_type', 'meeting_date', 'chair_ref', 'participants', 'agenda',
                      'documents', 'minutes_status'),
    'keys' => array('meeting_code', 'meeting_type', 'meeting_date', 'chair_ref', 'participants',
                    'agenda', 'documents', 'minutes_status', 'created_by', 'created_at',
                    'data_state', 'src_ref'),
    'types' => array('meeting_date' => 'DATE NULL DEFAULT NULL'),
),

));
