<?php
/**
 * fields_exceo.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'EX-CEO',
'screens' => array(

array(
    'req' => 'CEO-01', 'route' => 'Portal/exec_command_board.php',
    'table' => 'exec_board_kpi',
    'anchor' => '<table id="emsList_exec_board_kpi"',
    'rows' => "ems_w14_guide_rows('exec_board_kpi')",
    'grid_id' => 'emsList_exec_board_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة القيادة التنفيذية',
    'create' => true,
    'grain' => 'مؤشر واحد للوحة القيادة',
    'map' => array(
        'معرف المؤشر' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'الكيان' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'المحور' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'كود المؤشر KPI Catalog' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المؤشر' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'النطاق' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع النطاق' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة/العملة' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'المستهدف' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'الانحراف' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'الاتجاه' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المالكة' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'رابط النزول للمصدر' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-02', 'route' => 'Portal/exec_org_projects.php',
    'table' => 'exec_org_project',
    'anchor' => '<table id="emsList_exec_org_project"',
    'rows' => "ems_w14_guide_rows('exec_org_project')",
    'grid_id' => 'emsList_exec_org_project', 'empty' => 'لا سطر مسجل بعد في الادارات والمشروعات',
    'create' => true,
    'grain' => 'ادارة او مشروع واحد',
    'map' => array(
        'معرف البطاقة' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'نوع البطاقة' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'Department_ID/Project_ID' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'التبعية التنظيمية' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'Head المسؤول' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'Overall_Status' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'KPI_Status' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'Open_Requests' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'Pending_Approvals' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'Critical_Issues' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'Overdue_Actions' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'Budget_Status' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'Compliance_Status' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'Last_Daily_Report' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'Last_Weekly_Report' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'Last_Monthly_Close' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'رابط النزول' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-03', 'route' => 'Portal/exec_daily_report.php',
    'table' => 'exec_daily_report',
    'anchor' => '<table id="emsList_exec_daily_report"',
    'rows' => "ems_w14_guide_rows('exec_daily_report')",
    'grid_id' => 'emsList_exec_daily_report', 'empty' => 'لا سطر مسجل بعد في التقرير اليومي التنفيذي',
    'create' => true,
    'grain' => 'تقرير يوم واحد',
    'map' => array(
        'معرف السطر' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'المشروع' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'الخطة اليومية' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'المنفذ' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة الإنجاز' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'ساعات تشغيل المعدات' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي ساعات التوقف' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'عدد أنواع التوقف تفصيلها ر03-2' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'المعدات العاملة' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'المعدات المتوقفة' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'الأعطال الحرجة' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'القوى الموجودة' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'النقص' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'إصابات مضيعة للوقت LTI' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'حوادث عالية الجهد HiPo' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'أحداث إيقاف العمل Stop-Work' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'الحوادث البيئية' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'البلاغات الحرجة' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'الترحيلات المهمة' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'المواد الحرجة' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'عدد القرارات المطلوبة تفصيلها ر03-3' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الانحرافات الحرجة تفصيلها ر03-3' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'رابط النزول للسجل الأصلي' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-04', 'route' => 'Portal/exec_daily_stops.php',
    'table' => 'exec_daily_stop',
    'anchor' => '<table id="emsList_exec_daily_stop"',
    'rows' => "ems_w14_guide_rows('exec_daily_stop')",
    'grid_id' => 'emsList_exec_daily_stop', 'empty' => 'لا سطر مسجل بعد في تفصيل توقفات اليوم',
    'create' => true,
    'grain' => 'توقف واحد في يوم',
    'map' => array(
        'معرف السطر' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'معرف سطر اليوم' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'المشروع' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'نوع التوقف' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'ساعات النوع' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'مسؤول التوقف' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'أثر الفوترة' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع السجل الأصلي' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-05', 'route' => 'Portal/exec_daily_deviations.php',
    'table' => 'exec_daily_deviation',
    'anchor' => '<table id="emsList_exec_daily_deviation"',
    'rows' => "ems_w14_guide_rows('exec_daily_deviation')",
    'grid_id' => 'emsList_exec_daily_deviation', 'empty' => 'لا سطر مسجل بعد في انحرافات وقرارات اليوم',
    'create' => true,
    'grain' => 'انحراف واحد في يوم',
    'map' => array(
        'معرف البند' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'معرف سطر اليوم' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'نوع البند' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'المشروع' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'الوصف' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'المسؤول' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع الأصلي' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'الإجراء المقرر Decision Event' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'موعد الحل Decision Event' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-06', 'route' => 'Portal/exec_weekly_report.php',
    'table' => 'exec_weekly_report',
    'anchor' => '<table id="emsList_exec_weekly_report"',
    'rows' => "ems_w14_guide_rows('exec_weekly_report')",
    'grid_id' => 'emsList_exec_weekly_report', 'empty' => 'لا سطر مسجل بعد في التقرير الاسبوعي التنفيذي',
    'create' => true,
    'grain' => 'تقرير اسبوع واحد',
    'map' => array(
        'معرف السطر' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'الأسبوع' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'المحور' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'هذا الأسبوع' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'الأسبوع السابق' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'المستهدف' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'الانحراف' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'الاتجاه Trend' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'توقع الأسبوع القادم Forecast' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'التوقع مقابل الميزانية' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'عدد القرارات غير المنفذة' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الاجتماع المتفرع' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-07', 'route' => 'Portal/exec_monthly_pack.php',
    'table' => 'exec_monthly_pack',
    'anchor' => '<table id="emsList_exec_monthly_pack"',
    'rows' => "ems_w14_guide_rows('exec_monthly_pack')",
    'grid_id' => 'emsList_exec_monthly_pack', 'empty' => 'لا سطر مسجل بعد في التقرير الشهري التنفيذي',
    'create' => true,
    'grain' => 'حزمة شهر واحد',
    'map' => array(
        'معرف السطر' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'الشهر' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'المحور' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'البند' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'الفعلي' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'المستهدف' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'الانحراف' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'الاتجاه' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'توقع الشهر الكامل' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'Outlook 60/90 يوما' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'Forecast vs Budget' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'بند النظرة الأمامية' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'مراجعة النائب المختص' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة تنفيذية Decision Event' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'القرار/الإجراء المتفرع' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-08', 'route' => 'Portal/ceo_unified_queue.php',
    'table' => 'exec_request_queue',
    'anchor' => '<table id="emsList_exec_request_queue"',
    'rows' => "ems_w14_guide_rows('exec_request_queue')",
    'grid_id' => 'emsList_exec_request_queue', 'empty' => 'لا سطر مسجل بعد في جميع الطلبات المرفوعة',
    'create' => true,
    'grain' => 'طلب واحد مرفوع',
    'map' => array(
        'Request_ID' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Department' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Screen' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'Request_Type' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'Request_Title' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'Requested_By' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'Requested_Date' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'Amount' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
        'Currency' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'Project' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'Priority' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_Level' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'Previous_Approvals' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'سقف الإدارة المصدر' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'مقدار التجاوز عن السقف' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الرفع للأعلى' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'Current_Approval_Level' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'Required_By' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'Supporting_Documents' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'Recommendation' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'CEO_Decision' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'Decision_Conditions' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'Decision_Date' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-12', 'route' => 'Portal/exec_contract_registry.php',
    'table' => 'exec_contract_registry',
    'anchor' => '<table id="emsList_exec_contract_registry"',
    'rows' => "ems_w14_guide_rows('exec_contract_registry')",
    'grid_id' => 'emsList_exec_contract_registry', 'empty' => 'لا سطر مسجل بعد في سجل العقود الموحد',
    'create' => true,
    'grain' => 'عقد واحد في السجل الموحد',
    'map' => array(
        'معرف السطر' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'نوع العقد' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المالكة' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد في مصدره' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'الكيان' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'الطرف الآخر' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'سريان من' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'إلى' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'أيام حتى الانتهاء' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الالتزامات الحرجة القائمة' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الكفالات والضمانات المرتبطة' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العقد' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع التوقيع' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'رابط النزول للسجل الأصلي' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-13', 'route' => 'Portal/exec_redline_breaches.php',
    'table' => 'exec_redline_breach',
    'anchor' => '<table id="emsList_exec_redline_breach"',
    'rows' => "ems_w14_guide_rows('exec_redline_breach')",
    'grid_id' => 'emsList_exec_redline_breach', 'empty' => 'لا سطر مسجل بعد في تجاوزات الخطوط الحمراء',
    'create' => true,
    'grain' => 'تجاوز خط احمر واحد',
    'map' => array(
        'Exception_ID' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Department' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Record' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'Rule_Breached' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'Red_Line_Type' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'Severity' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'Financial_Exposure' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'Operational_Exposure' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'Legal_Exposure' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
        'Compliance_Exposure' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'Waivability_Type' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'Requested_Exception' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'Business_Justification' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'Department_Recommendation' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'Deputy_Recommendation' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'Escalation_To' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'CEO_Decision' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'Conditions' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'Valid_From' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
        'Valid_To' => '+g171:VARCHAR(190) NULL DEFAULT NULL',
        'Evidence' => '+g172:VARCHAR(190) NULL DEFAULT NULL',
        'Closure' => '+g173:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g174:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g175:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g176:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g177:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-14', 'route' => 'Portal/exec_reserved_matters.php',
    'table' => 'exec_reserved_matter',
    'anchor' => '<table id="emsList_exec_reserved_matter"',
    'rows' => "ems_w14_guide_rows('exec_reserved_matter')",
    'grid_id' => 'emsList_exec_reserved_matter', 'empty' => 'لا سطر مسجل بعد في المسائل المحجوزة',
    'create' => true,
    'grain' => 'مسالة محجوزة واحدة',
    'map' => array(
        'معرف المسألة' => '+g178:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المسألة' => '+g179:VARCHAR(190) NULL DEFAULT NULL',
        'الأساس في وثائق الشركة' => '+g180:VARCHAR(190) NULL DEFAULT NULL',
        'السلطة المخولة' => '+g181:VARCHAR(190) NULL DEFAULT NULL',
        'هل تحال بالكامل أم برأي الرئيس؟' => '+g182:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الوارد' => '+g183:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المصدر' => '+g184:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة/الأثر' => '+g185:VARCHAR(190) NULL DEFAULT NULL',
        'رأي الرئيس المرفوع' => '+g186:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإحالة' => '+g187:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الجهة الحاكمة' => '+g188:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ القرار' => '+g189:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المسألة' => '+g190:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g191:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g192:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g193:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g194:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g195:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g196:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g197:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-15', 'route' => 'Portal/exec_critical_exceptions.php',
    'table' => 'exec_critical_exception',
    'anchor' => '<table id="emsList_exec_critical_exception"',
    'rows' => "ems_w14_guide_rows('exec_critical_exception')",
    'grid_id' => 'emsList_exec_critical_exception', 'empty' => 'لا سطر مسجل بعد في الاستثناءات الحرجة',
    'create' => true,
    'grain' => 'استثناء حرج واحد',
    'map' => array(
        'معرف البند' => '+g198:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الاستثناء' => '+g199:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المصدر' => '+g200:VARCHAR(190) NULL DEFAULT NULL',
        'قاعدة المنع/السياسة' => '+g201:VARCHAR(190) NULL DEFAULT NULL',
        'المبرر' => '+g202:VARCHAR(190) NULL DEFAULT NULL',
        'المدة المطلوبة' => '+g203:VARCHAR(190) NULL DEFAULT NULL',
        'رأي الحوكمة' => '+g204:VARCHAR(190) NULL DEFAULT NULL',
        'رأي النائب المختص' => '+g205:VARCHAR(190) NULL DEFAULT NULL',
        'التعرض المقدر' => '+g206:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_Appetite_Status' => '+g207:VARCHAR(190) NULL DEFAULT NULL',
        'القرار' => '+g208:VARCHAR(190) NULL DEFAULT NULL',
        'قبول المخاطرة موثق؟' => '+g209:VARCHAR(190) NULL DEFAULT NULL',
        'شروط إضافية' => '+g210:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البند' => '+g211:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g212:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g213:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g214:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g215:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-16', 'route' => 'Portal/ceo_assurance_box.php',
    'table' => 'exec_assurance_report',
    'anchor' => '<table id="emsList_exec_assurance_report"',
    'rows' => "ems_w14_guide_rows('exec_assurance_report')",
    'grid_id' => 'emsList_exec_assurance_report', 'empty' => 'لا سطر مسجل بعد في صندوق التاكيد المستقل',
    'create' => true,
    'grain' => 'تقرير تاكيد مستقل واحد',
    'map' => array(
        'معرف الوارد' => '+g216:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع التقرير/الملاحظة' => '+g217:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الوارد' => '+g218:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة الخاضعة' => '+g219:VARCHAR(190) NULL DEFAULT NULL',
        'الرأي العام' => '+g220:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الملاحظات الحرجة' => '+g221:VARCHAR(190) NULL DEFAULT NULL',
        'المتأخرة' => '+g222:VARCHAR(190) NULL DEFAULT NULL',
        'المتكررة' => '+g223:VARCHAR(190) NULL DEFAULT NULL',
        'التعرض المقدر' => '+g224:VARCHAR(190) NULL DEFAULT NULL',
        'توصية المراجعة' => '+g225:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الرئيس' => '+g226:VARCHAR(190) NULL DEFAULT NULL',
        'المكلف بالتنفيذ' => '+g227:VARCHAR(190) NULL DEFAULT NULL',
        'مهلة التنفيذ' => '+g228:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المتابعة ر15' => '+g229:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الوارد' => '+g230:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g231:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g232:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g233:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g234:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-17', 'route' => 'Portal/exec_escalations.php',
    'table' => 'exec_escalation',
    'anchor' => '<table id="emsList_exec_escalation"',
    'rows' => "ems_w14_guide_rows('exec_escalation')",
    'grid_id' => 'emsList_exec_escalation', 'empty' => 'لا سطر مسجل بعد في التصعيدات العليا',
    'create' => true,
    'grain' => 'تصعيد واحد',
    'map' => array(
        'معرف التصعيد' => '+g235:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الوصول' => '+g236:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر التصعيد' => '+g237:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع الأصلي' => '+g238:VARCHAR(190) NULL DEFAULT NULL',
        'المسار المقطوع' => '+g239:VARCHAR(190) NULL DEFAULT NULL',
        'ملخص الحالة' => '+g240:VARCHAR(190) NULL DEFAULT NULL',
        'الأثر الجاري' => '+g241:VARCHAR(190) NULL DEFAULT NULL',
        'القرار' => '+g242:VARCHAR(190) NULL DEFAULT NULL',
        'المكلف بالتنفيذ' => '+g243:VARCHAR(190) NULL DEFAULT NULL',
        'مهلة التنفيذ' => '+g244:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التصعيد' => '+g245:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g246:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g247:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g248:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g249:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-18', 'route' => 'Portal/exec_crisis_command.php',
    'table' => 'exec_crisis_case',
    'anchor' => '<table id="emsList_exec_crisis_case"',
    'rows' => "ems_w14_guide_rows('exec_crisis_case')",
    'grid_id' => 'emsList_exec_crisis_case', 'empty' => 'لا سطر مسجل بعد في قيادة الازمات والطوارئ',
    'create' => true,
    'grain' => 'حالة ازمة واحدة',
    'map' => array(
        'Crisis_ID' => '+g250:VARCHAR(190) NULL DEFAULT NULL',
        'Type' => '+g251:VARCHAR(190) NULL DEFAULT NULL',
        'Severity' => '+g252:VARCHAR(190) NULL DEFAULT NULL',
        'Site/Project' => '+g253:VARCHAR(190) NULL DEFAULT NULL',
        'Declared_At' => '+g254:VARCHAR(190) NULL DEFAULT NULL',
        'Incident_Commander مرجع القائد' => '+g255:VARCHAR(190) NULL DEFAULT NULL',
        'People_Impact' => '+g256:VARCHAR(190) NULL DEFAULT NULL',
        'Operational_Impact' => '+g257:VARCHAR(190) NULL DEFAULT NULL',
        'Financial_Impact' => '+g258:VARCHAR(190) NULL DEFAULT NULL',
        'Legal_Regulatory_Impact' => '+g259:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الحدث الأصلي' => '+g260:VARCHAR(190) NULL DEFAULT NULL',
        'Immediate_Actions Decision Event' => '+g261:VARCHAR(190) NULL DEFAULT NULL',
        'Decisions_Required' => '+g262:VARCHAR(190) NULL DEFAULT NULL',
        'Next_Update_At' => '+g263:VARCHAR(190) NULL DEFAULT NULL',
        'External_Communication_Status' => '+g264:VARCHAR(190) NULL DEFAULT NULL',
        'Current_Status' => '+g265:VARCHAR(190) NULL DEFAULT NULL',
        'Stand_Down_Date' => '+g266:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g267:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g268:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g269:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g270:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-19', 'route' => 'Portal/exec_strategic_decisions.php',
    'table' => 'exec_strategic_decision',
    'anchor' => '<table id="emsList_exec_strategic_decision"',
    'rows' => "ems_w14_guide_rows('exec_strategic_decision')",
    'grid_id' => 'emsList_exec_strategic_decision', 'empty' => 'لا سطر مسجل بعد في القرارات الاستراتيجية',
    'create' => true,
    'grain' => 'قرار استراتيجي واحد',
    'map' => array(
        'Decision_ID' => '+g271:VARCHAR(190) NULL DEFAULT NULL',
        'الكيان' => '+g272:VARCHAR(190) NULL DEFAULT NULL',
        'نوع القرار' => '+g273:VARCHAR(190) NULL DEFAULT NULL',
        'Proposal_Source' => '+g274:VARCHAR(190) NULL DEFAULT NULL',
        'Business_Case' => '+g275:VARCHAR(190) NULL DEFAULT NULL',
        'الخيارات المطروحة' => '+g276:VARCHAR(190) NULL DEFAULT NULL',
        'الخيار المختار' => '+g277:VARCHAR(190) NULL DEFAULT NULL',
        'مبرر الاختيار' => '+g278:VARCHAR(190) NULL DEFAULT NULL',
        'Financial_Impact' => '+g279:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_Assessment' => '+g280:VARCHAR(190) NULL DEFAULT NULL',
        'Legal_Review_Status' => '+g281:VARCHAR(190) NULL DEFAULT NULL',
        'Finance_Review_Status' => '+g282:VARCHAR(190) NULL DEFAULT NULL',
        'Compliance_Review_Status' => '+g283:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_Review_Status' => '+g284:VARCHAR(190) NULL DEFAULT NULL',
        'Relevant_Deputy_Recommendation' => '+g285:VARCHAR(190) NULL DEFAULT NULL',
        'فحص اكتمال بوابة المراجعات' => '+g286:VARCHAR(190) NULL DEFAULT NULL',
        'Recommendation' => '+g287:VARCHAR(190) NULL DEFAULT NULL',
        'Decision' => '+g288:VARCHAR(190) NULL DEFAULT NULL',
        'Effective_Date' => '+g289:VARCHAR(190) NULL DEFAULT NULL',
        'Owner مرجع مالك التنفيذ' => '+g290:VARCHAR(190) NULL DEFAULT NULL',
        'Milestones' => '+g291:VARCHAR(190) NULL DEFAULT NULL',
        'Follow_Up' => '+g292:VARCHAR(190) NULL DEFAULT NULL',
        'Closure' => '+g293:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g294:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g295:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g296:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g297:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g298:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g299:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g300:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-20', 'route' => 'Portal/project_charter.php',
    'table' => 'exec_project_charters',
    'anchor' => '<table id="emsList_exec_project_charters"',
    'rows' => "ems_w14_guide_rows('exec_project_charters')",
    'grid_id' => 'emsList_exec_project_charters', 'empty' => 'لا سطر مسجل بعد في ميثاق المشروع',
    'map' => array(
        'رقم القرار' => 'decision_no',
        'الكيان' => '+g301:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المشروع' => '+g302:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g303:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد' => '+g304:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع أو المواقع' => 'sites_text',
        'نموذج العمل' => '+g305:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة العمل' => 'work_unit',
        'الكمية المتعاقدة' => 'contracted_qty',
        'تاريخ البدء المخطط' => 'planned_start',
        'المدة' => '+g306:VARCHAR(190) NULL DEFAULT NULL',
        'المعدات المطلوبة' => 'equipment_needed',
        'المشغلون المطلوبون' => 'operators_needed',
        'مصدر المعدات' => 'equipment_source',
        'احتياج التمويل' => 'financing_need',
        'مركز التكلفة' => 'cost_center',
        'مدير الموقع المعين' => 'site_manager',
        'صلاحياته الممنوحة' => '+g307:VARCHAR(190) NULL DEFAULT NULL',
        'إفادة التشغيل' => 'cert_operations',
        'إفادة المبيعات' => 'cert_sales',
        'إفادة القوى' => 'cert_workforce',
        'إفادة المالية' => 'cert_finance',
        'إفادة الأسطول' => 'cert_fleet',
        'إفادة التمويل' => 'cert_financing',
        'اكتمال الإفادات الست' => '+g308:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الفتح' => '+g309:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ القرار' => '+g310:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الميثاق' => '+g311:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g312:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g313:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g314:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => 'approver_name',
        'تاريخ الاعتماد' => 'approval_date',
        'حالة البيانات' => '+g315:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g316:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-23', 'route' => 'Portal/exec_leadership_appointments.php',
    'table' => 'exec_leadership_appointment',
    'anchor' => '<table id="emsList_exec_leadership_appointment"',
    'rows' => "ems_w14_guide_rows('exec_leadership_appointment')",
    'grid_id' => 'emsList_exec_leadership_appointment', 'empty' => 'لا سطر مسجل بعد في موافقات التعيين القيادية',
    'create' => true,
    'grain' => 'موافقة تعيين واحدة',
    'map' => array(
        'رقم الطلب' => '+g317:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الطلب' => '+g318:VARCHAR(190) NULL DEFAULT NULL',
        'المسمى القيادي من الهيكل' => '+g319:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة التنظيمية' => '+g320:VARCHAR(190) NULL DEFAULT NULL',
        'المرشح/المعني' => '+g321:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الشخص بالموارد' => '+g322:VARCHAR(190) NULL DEFAULT NULL',
        'سقف الاعتماد الممنوح' => '+g323:VARCHAR(190) NULL DEFAULT NULL',
        'بدل التكليف' => '+g324:VARCHAR(190) NULL DEFAULT NULL',
        'إفصاح طرف ذي علاقة' => '+g325:VARCHAR(190) NULL DEFAULT NULL',
        'مراجعة الموارد البشرية' => '+g326:VARCHAR(190) NULL DEFAULT NULL',
        'مراجعة الحوكمة' => '+g327:VARCHAR(190) NULL DEFAULT NULL',
        'قاعدة AAM المفعلة' => '+g328:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الرئيس' => '+g329:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الإحالة للسلطة المحجوزة' => '+g330:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ النفاذ' => '+g331:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الطلب' => '+g332:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g333:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g334:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g335:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g336:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g337:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g338:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g339:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-25', 'route' => 'Portal/exec_meeting_decisions.php',
    'table' => 'exec_meeting_decision',
    'anchor' => '<table id="emsList_exec_meeting_decision"',
    'rows' => "ems_w14_guide_rows('exec_meeting_decision')",
    'grid_id' => 'emsList_exec_meeting_decision', 'empty' => 'لا سطر مسجل بعد في قرارات الاجتماعات',
    'create' => true,
    'grain' => 'قرار اجتماع واحد',
    'map' => array(
        'Decision_ID' => '+g340:VARCHAR(190) NULL DEFAULT NULL',
        'Meeting_ID' => '+g341:VARCHAR(190) NULL DEFAULT NULL',
        'Topic' => '+g342:VARCHAR(190) NULL DEFAULT NULL',
        'Decision' => '+g343:VARCHAR(190) NULL DEFAULT NULL',
        'Owner مرجع مسؤول التنفيذ' => '+g344:VARCHAR(190) NULL DEFAULT NULL',
        'Department مرجع الإدارة' => '+g345:VARCHAR(190) NULL DEFAULT NULL',
        'Due_Date' => '+g346:VARCHAR(190) NULL DEFAULT NULL',
        'Priority' => '+g347:VARCHAR(190) NULL DEFAULT NULL',
        'Status' => '+g348:VARCHAR(190) NULL DEFAULT NULL',
        'Evidence يرفقه المنفذ' => '+g349:VARCHAR(190) NULL DEFAULT NULL',
        'Closed_Date' => '+g350:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g351:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g352:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g353:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g354:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'CEO-26', 'route' => 'Portal/exec_actions_followup.php',
    'table' => 'exec_action_followup',
    'anchor' => '<table id="emsList_exec_action_followup"',
    'rows' => "ems_w14_guide_rows('exec_action_followup')",
    'grid_id' => 'emsList_exec_action_followup', 'empty' => 'لا سطر مسجل بعد في متابعة القرارات التنفيذية',
    'create' => true,
    'grain' => 'قرار تنفيذي متابع',
    'map' => array(
        'Action_ID' => '+g355:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر القرار' => '+g356:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع الأصلي' => '+g357:VARCHAR(190) NULL DEFAULT NULL',
        'الموضوع' => '+g358:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة' => '+g359:VARCHAR(190) NULL DEFAULT NULL',
        'المسؤول' => '+g360:VARCHAR(190) NULL DEFAULT NULL',
        'Due_Date' => '+g361:VARCHAR(190) NULL DEFAULT NULL',
        'Priority' => '+g362:VARCHAR(190) NULL DEFAULT NULL',
        'Status' => '+g363:VARCHAR(190) NULL DEFAULT NULL',
        'أيام التأخير' => '+g364:VARCHAR(190) NULL DEFAULT NULL',
        'Evidence' => '+g365:VARCHAR(190) NULL DEFAULT NULL',
        'Closure' => '+g366:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
