<?php
/**
 * fields_dep_15.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-15',
'screens' => array(

array(
    'req' => 'TRP-04', 'route' => 'Transport/transfer_order_form.php',
    'table' => 'trp_transfer_order_form',
    'anchor' => '<table id="emsList_trp_transfer_order_form"',
    'rows' => "ems_w14_guide_rows('trp_transfer_order_form')",
    'grid_id' => 'emsList_trp_transfer_order_form', 'empty' => 'لا سطر مسجل بعد في أمر الترحيل',
    'create' => true,
    'grain' => 'أمر الترحيل',
    'map' => array(
        'رقم الأمر' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الأمر' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الطلب' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الحمولة' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'من موقع' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'إلى موقع' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'المسافة التقديرية' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'وسيلة النقل' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'الناقل' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'عقد الناقل' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'السائق' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'رخصة السائق سارية؟' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'المسار المقرر' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ المغادرة المخطط' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الوصول المخطط' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'التصاريح المطلوبة' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الأمر' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-03', 'route' => 'Transport/transfer_fleet.php',
    'table' => 'trp_transfer_fleet',
    'anchor' => '<table id="emsList_trp_transfer_fleet"',
    'rows' => "ems_w14_guide_rows('trp_transfer_fleet')",
    'grid_id' => 'emsList_trp_transfer_fleet', 'empty' => 'لا سطر مسجل بعد في اللوابد والمركبات الناقلة',
    'create' => true,
    'grain' => 'اللوابد والمركبات الناقلة',
    'map' => array(
        'كود الناقلة' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'النوع' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'رقم اللوحة' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'المالك' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المورد عند التأجير' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'السعة الوزنية (طن)' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'الطول والعرض المسموحان' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'عدد المحاور' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'رخصة السير وانتهاؤها' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'تأمين البضاعة وانتهاؤه' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'تصاريح المسار السارية' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'فحص المطابقة مع الحمولة' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الناقلة' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-08', 'route' => 'Transport/transfer_in_transit.php',
    'table' => 'trp_transfer_in_transit',
    'anchor' => '<table id="emsList_trp_transfer_in_transit"',
    'rows' => "ems_w14_guide_rows('trp_transfer_in_transit')",
    'grid_id' => 'emsList_trp_transfer_in_transit', 'empty' => 'لا سطر مسجل بعد في تتبع الرحلة وأحداثها',
    'create' => true,
    'grain' => 'تتبع الرحلة وأحداثها',
    'map' => array(
        'معرف الحدث' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الحدث' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الحدث' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع الجغرافي' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'قراءة عداد الناقل' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة الحدث' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'مرفق/صورة' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'مسجل دون اتصال؟' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-01', 'route' => 'Transport/transfer_dashboard.php',
    'table' => 'trp_dashboard_kpi',
    'anchor' => '<table id="emsList_trp_dashboard_kpi"',
    'rows' => "ems_w14_guide_rows('trp_dashboard_kpi')",
    'grid_id' => 'emsList_trp_dashboard_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة النقل والترحيل',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة النقل والترحيل',
    'map' => array(
        'معرف المؤشر' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر KPI Catalog' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-02', 'route' => 'Transport/transfer_requests.php',
    'table' => 'trp_transfer_requests',
    'anchor' => '<table id="emsList_trp_transfer_requests"',
    'rows' => "ems_w14_guide_rows('trp_transfer_requests')",
    'grid_id' => 'emsList_trp_transfer_requests', 'empty' => 'لا سطر مسجل بعد في طلب الترحيل',
    'create' => true,
    'grain' => 'طلب الترحيل',
    'map' => array(
        'رقم الطلب' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الطلب' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة الطالبة' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع أمر نقل الموارد' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الحمولة' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة/الصنف' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'الوزن/الأبعاد' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'من موقع' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'إلى موقع' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ المطلوب' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات التحميل' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الطلب' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-07', 'route' => 'Transport/transfer_trip_legs.php',
    'table' => 'trp_transfer_trip_legs',
    'anchor' => '<table id="emsList_trp_transfer_trip_legs"',
    'rows' => "ems_w14_guide_rows('trp_transfer_trip_legs')",
    'grid_id' => 'emsList_trp_transfer_trip_legs', 'empty' => 'لا سطر مسجل بعد في مراحل الرحلة',
    'create' => true,
    'grain' => 'مراحل الرحلة',
    'map' => array(
        'معرف المرحلة' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل المرحلة' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'من نقطة' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'إلى نقطة' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'الناقلة المكلفة' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'السائق' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'المسافة المقدرة' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'بدء المرحلة' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'انتهاء المرحلة' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'تسليم المرحلة للتالية' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'أحداث المرحلة' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المرحلة' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-10', 'route' => 'Transport/transfer_damage_claims.php',
    'table' => 'trp_transfer_damage_claims',
    'anchor' => '<table id="emsList_trp_transfer_damage_claims"',
    'rows' => "ems_w14_guide_rows('trp_transfer_damage_claims')",
    'grid_id' => 'emsList_trp_transfer_damage_claims', 'empty' => 'لا سطر مسجل بعد في مطالبات التلف والحوادث',
    'create' => true,
    'grain' => 'مطالبات التلف والحوادث',
    'map' => array(
        'رقم المطالبة' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الواقعة' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'وصف التلف' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'المتسبب المرجح' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة المطالبة المقدرة' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'مستندات الإثبات' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'مسار المطالبة' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'قرار التسوية' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة التسوية' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المطالبة' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-12', 'route' => 'Transport/transfer_closure.php',
    'table' => 'trp_transfer_closure',
    'anchor' => '<table id="emsList_trp_transfer_closure"',
    'rows' => "ems_w14_guide_rows('trp_transfer_closure')",
    'grid_id' => 'emsList_trp_transfer_closure', 'empty' => 'لا سطر مسجل بعد في إقفال أمر الترحيل',
    'create' => true,
    'grain' => 'إقفال أمر الترحيل',
    'map' => array(
        'معرف الإقفال' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'فحص محضر الاستلام' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'عدد بنود التكلفة' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي التكلفة' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'التوزيع بالمتحمل' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'ترحيل قراءة العداد' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'الإحالة للمالية' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة الإقفال' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإقفال' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-05', 'route' => 'Transport/transfer_permits.php',
    'table' => 'trp_transfer_permits',
    'anchor' => '<table id="emsList_trp_transfer_permits"',
    'rows' => "ems_w14_guide_rows('trp_transfer_permits')",
    'grid_id' => 'emsList_trp_transfer_permits', 'empty' => 'لا سطر مسجل بعد في تصاريح المسار والحمولة',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في تصاريح المسار والحمولة',
    'map' => array(
        'معرف التصريح' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'نوع التصريح' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة المصدرة' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'رقم التصريح' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإصدار' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الانتهاء' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'نطاق التصريح' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'الرسوم' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'مرفق التصريح' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التصريح' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-06', 'route' => 'Transport/transfer_origin_handover.php',
    'table' => 'trp_transfer_origin_handover',
    'anchor' => '<table id="emsList_trp_transfer_origin_handover"',
    'rows' => "ems_w14_guide_rows('trp_transfer_origin_handover')",
    'grid_id' => 'emsList_trp_transfer_origin_handover', 'empty' => 'لا سطر مسجل بعد في تجهيز المغادرة والتسليم الأصلي',
    'create' => true,
    'grain' => 'تجهيز المغادرة والتسليم الأصلي',
    'map' => array(
        'معرف البند' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'بند التجهيز' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
        'المنفذ' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'النتيجة' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'محضر التسليم الأصلي' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'صور حالة ما قبل النقل' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'تقييم مخاطر المسار' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الإنجاز' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البند' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRP-13', 'route' => 'Transport/transfer_orders_report.php',
    'table' => 'trp_transfer_orders_report',
    'anchor' => '<table id="emsList_trp_transfer_orders_report"',
    'rows' => "ems_w14_guide_rows('trp_transfer_orders_report')",
    'grid_id' => 'emsList_trp_transfer_orders_report', 'empty' => 'لا سطر مسجل بعد في تقرير أوامر الترحيل',
    'create' => true,
    'grain' => 'تقرير أوامر الترحيل',
    'map' => array(
        'معرف السطر' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الأوامر' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'منها مقفلة' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'متوسط زمن الرحلة' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'الالتزام بالمواعيد' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'حوادث وتلفيات' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي التكلفة' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'تكلفة الكيلومتر' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'التوزيع بالوسيلة' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
