<?php
/**
 * fields_dep10.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-10',
'screens' => array(

array(
    'req' => 'TKT-04', 'route' => 'Tickets/ticket_contextual_open.php',
    'table' => 'tkt_ticket_contextual_open',
    'anchor' => '<table id="emsList_tkt_ticket_contextual_open"',
    'rows' => "ems_w14_guide_rows('tkt_ticket_contextual_open')",
    'grid_id' => 'emsList_tkt_ticket_contextual_open', 'empty' => 'لا سطر مسجل بعد في الإبلاغ السياقي من داخل الشاشة',
    'create' => true,
    'grain' => 'الإبلاغ السياقي من داخل الشاشة',
    'map' => array(
        'رقم البلاغ' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'الشاشة المصدر' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'مسار الشاشة' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع السجل المفتوح' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المالكة للشاشة' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'صفته وقت الإبلاغ' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الإبلاغ' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'فئة المشكلة' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'طبيعتها' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية المقترحة' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'وصف موجز' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'مرفق اختياري' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'تصنيف آلي مقترح' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المستقبلة' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر البلاغ' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البلاغ' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-06', 'route' => 'Tickets/ticket_form.php',
    'table' => 'tkt_ticket_form',
    'anchor' => '<table id="emsList_tkt_ticket_form"',
    'rows' => "ems_w14_guide_rows('tkt_ticket_form')",
    'grid_id' => 'emsList_tkt_ticket_form', 'empty' => 'لا سطر مسجل بعد في تسجيل البلاغ',
    'create' => true,
    'grain' => 'تسجيل البلاغ',
    'map' => array(
        'رقم البلاغ' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'وقت التسجيل' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'قناة التسجيل' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'Reporter_ID' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'Reporter_Name' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'Reporter_Department' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'Reporter_Entity' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'Reporter_Contact' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'Subject_Type' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'Subject_ID' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'Subject_Name' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'Subject_Owning_Department' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'الفئة' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'الطبيعة' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى السرية' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'وصف البلاغ' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'المرفقات' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'Ticket_Owner' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'Assigned_Department' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'Resolution_Owner' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'مهلة المعالجة' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البلاغ' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-13', 'route' => 'Tickets/tkt_verification.php',
    'table' => 'tkt_verification',
    'anchor' => '<table id="emsList_tkt_verification"',
    'rows' => "ems_w14_guide_rows('tkt_verification')",
    'grid_id' => 'emsList_tkt_verification', 'empty' => 'لا سطر مسجل بعد في التحقق من المعالجة وإغلاق البلاغ',
    'map' => array(
        'معرف الإغلاق' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'ملخص المعالجة' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'Resolved في' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'نوع التحقق' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'تأكيد المبلغ' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'تقييم الرضا' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الإغلاق' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'البلاغ الأصل عند التكرار' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الإلغاء' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الإغلاق' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإغلاق' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-11', 'route' => 'Tickets/tkt_escalation.php',
    'table' => 'tkt_escalation',
    'anchor' => '<table id="emsList_tkt_escalation"',
    'rows' => "ems_w14_guide_rows('tkt_escalation')",
    'grid_id' => 'emsList_tkt_escalation', 'empty' => 'لا سطر مسجل بعد في تصعيد البلاغ',
    'create' => true,
    'grain' => 'تصعيد البلاغ',
    'map' => array(
        'معرف التصعيد' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'المهلة الأصلية' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'التجاوز' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'المستوى' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'المخطر' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'وقت التصعيد' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'الاستجابة' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الاستجابة' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التصعيد' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-02', 'route' => 'Tickets/tickets_list.php',
    'table' => 'tkt_tickets_list',
    'anchor' => '<table id="emsList_tkt_tickets_list"',
    'rows' => "ems_w14_guide_rows('tkt_tickets_list')",
    'grid_id' => 'emsList_tkt_tickets_list', 'empty' => 'لا سطر مسجل بعد في صندوق بلاغات الإدارة',
    'create' => true,
    'grain' => 'صندوق بلاغات الإدارة',
    'map' => array(
        'معرف السطر' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'نطاق العرض' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التسجيل' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'الفئة' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'محل البلاغ' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'المكلف' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'الكيان المنشأ في إدارتنا' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'مهلة SLA' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي/التأخير' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى التصعيد' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'ينتظر تحققا؟' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البلاغ' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-09', 'route' => 'Tickets/tkt_resolution_actions.php',
    'table' => 'tkt_resolution_actions',
    'anchor' => '<table id="emsList_tkt_resolution_actions"',
    'rows' => "ems_w14_guide_rows('tkt_resolution_actions')",
    'grid_id' => 'emsList_tkt_resolution_actions', 'empty' => 'لا سطر مسجل بعد في إجراءات معالجة البلاغ',
    'create' => true,
    'grain' => 'إجراءات معالجة البلاغ',
    'map' => array(
        'معرف الإجراء' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل الإجراء' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'المكلف' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'الإجراء المتخذ' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الإجراء في شاشة الإدارة' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'نتيجة الإجراء' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'سبب التعليق' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'مدة التعليق' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الإجراء' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-03', 'route' => 'Tickets/ticket_sla_config.php',
    'table' => 'tkt_ticket_sla_config',
    'anchor' => '<table id="emsList_tkt_ticket_sla_config"',
    'rows' => "ems_w14_guide_rows('tkt_ticket_sla_config')",
    'grid_id' => 'emsList_tkt_ticket_sla_config', 'empty' => 'لا سطر مسجل بعد في مصفوفة مهل المعالجة للبلاغات',
    'create' => true,
    'grain' => 'مصفوفة مهل المعالجة للبلاغات',
    'map' => array(
        'معرف السطر' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'نوع البلاغ' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المسؤولة' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'Response SLA' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'Resolution SLA' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'سلم التصعيد' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'سريان المصفوفة' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-12', 'route' => 'Tickets/tkt_reopen.php',
    'table' => 'tkt_reopen',
    'anchor' => '<table id="emsList_tkt_reopen"',
    'rows' => "ems_w14_guide_rows('tkt_reopen')",
    'grid_id' => 'emsList_tkt_reopen', 'empty' => 'لا سطر مسجل بعد في إعادة فتح البلاغ',
    'map' => array(
        'معرف الإعادة' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل الإعادة' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'طالب الإعادة' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الإعادة' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الإغلاق السابق' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الإعادة' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'المسار بعد الإعادة' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-07', 'route' => 'Tickets/tkt_routing.php',
    'table' => 'tkt_routing',
    'anchor' => '<table id="emsList_tkt_routing"',
    'rows' => "ems_w14_guide_rows('tkt_routing')",
    'grid_id' => 'emsList_tkt_routing', 'empty' => 'لا سطر مسجل بعد في تاريخ توجيه البلاغ',
    'create' => true,
    'grain' => 'تاريخ توجيه البلاغ',
    'map' => array(
        'معرف التوجيه' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل التوجيه' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'نوع التوجيه' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'من إدارة' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'إلى إدارة' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف قبل' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف بعد' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'سبب التصحيح' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'أثر المهلة' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'وقت التوجيه' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-10', 'route' => 'Tickets/tkt_communications.php',
    'table' => 'tkt_communications',
    'anchor' => '<table id="emsList_tkt_communications"',
    'rows' => "ems_w14_guide_rows('tkt_communications')",
    'grid_id' => 'emsList_tkt_communications', 'empty' => 'لا سطر مسجل بعد في مراسلات البلاغ',
    'create' => true,
    'grain' => 'مراسلات البلاغ',
    'map' => array(
        'معرف التواصل' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'الاتجاه' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'الطرف' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
        'القناة' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'ملخص التواصل' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'ضمن مستوى السرية' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
        'وقت التواصل' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-01', 'route' => 'Tickets/gov_dept_crp.php',
    'table' => 'tkt_dashboard_kpi',
    'anchor' => '<table id="emsList_tkt_dashboard_kpi"',
    'rows' => "ems_w14_guide_rows('tkt_dashboard_kpi')",
    'grid_id' => 'emsList_tkt_dashboard_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة مركز البلاغات',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة مركز البلاغات',
    'map' => array(
        'معرف المؤشر' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-05', 'route' => 'Tickets/tkt_subject_types.php',
    'table' => 'tkt_subject_types',
    'anchor' => '<table id="emsList_tkt_subject_types"',
    'rows' => "ems_w14_guide_rows('tkt_subject_types')",
    'grid_id' => 'emsList_tkt_subject_types', 'empty' => 'لا سطر مسجل بعد في أنواع محل البلاغ المعتمدة',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في أنواع محل البلاغ المعتمدة',
    'map' => array(
        'كود النوع' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'اسم النوع' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'السجل المرجعي' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح الربط' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المالكة' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'أمثلة' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'حالة النوع' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g171:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TKT-08', 'route' => 'Tickets/tkt_assignment.php',
    'table' => 'tkt_assignment',
    'anchor' => '<table id="emsList_tkt_assignment"',
    'rows' => "ems_w14_guide_rows('tkt_assignment')",
    'grid_id' => 'emsList_tkt_assignment', 'empty' => 'لا سطر مسجل بعد في تاريخ إسناد البلاغ',
    'create' => true,
    'grain' => 'تاريخ إسناد البلاغ',
    'map' => array(
        'معرف الإسناد' => '+g172:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g173:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل الإسناد' => '+g174:VARCHAR(190) NULL DEFAULT NULL',
        'المكلف' => '+g175:VARCHAR(190) NULL DEFAULT NULL',
        'صفة المكلف' => '+g176:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الإسناد' => '+g177:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الاستلام' => '+g178:VARCHAR(190) NULL DEFAULT NULL',
        'سبب التغيير' => '+g179:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإسناد' => '+g180:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g181:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g182:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g183:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g184:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
