<?php
/**
 * fields_dep06.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-06',
'screens' => array(

array(
    'req' => 'TRS-08', 'route' => 'Finance/tre_payment_queue.php',
    'table' => 'tre_payment_queue',
    'anchor' => '<table id="emsList_tre_payment_queue"',
    'rows' => "ems_w14_guide_rows('tre_payment_queue')",
    'grid_id' => 'emsList_tre_payment_queue', 'empty' => 'لا سطر مسجل بعد في مدفوعات معتمدة بانتظار التنفيذ',
    'create' => true,
    'grain' => 'مدفوعات معتمدة بانتظار التنفيذ',
    'map' => array(
        'رقم الطلب' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الطلب' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة الطالبة' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المستفيد' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'المستفيد' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'الموجب المعتمد' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'فحص البوابة' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الطلب' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر التمويل المستخدم' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'فحص إتاحة المصدر' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'طريقة الدفع' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاستحقاق' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الطلب' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-09', 'route' => 'Finance/tre_pay_batch.php',
    'table' => 'tre_pay_batch',
    'anchor' => '<table id="emsList_tre_pay_batch"',
    'rows' => "ems_w14_guide_rows('tre_pay_batch')",
    'grid_id' => 'emsList_tre_pay_batch', 'empty' => 'لا سطر مسجل بعد في أمر الدفع والتنفيذ',
    'create' => true,
    'grain' => 'أمر الدفع والتنفيذ',
    'map' => array(
        'رقم الأمر' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الطلب' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'فحص اكتمال الاعتماد' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'المستفيد' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'الوعاء الصارف' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'فحص رصيد الوعاء' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع الأول' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع الثاني' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'فحص سريان التفويض' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع التنفيذ البنكي' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التنفيذ' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'انعكاس الذمم' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الأمر' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-02', 'route' => 'Finance/tre_vessels.php',
    'table' => 'tre_vessels',
    'anchor' => '<table id="emsList_tre_vessels"',
    'rows' => "ems_w14_guide_rows('tre_vessels')",
    'grid_id' => 'emsList_tre_vessels', 'empty' => 'لا سطر مسجل بعد في الحسابات البنكية والصناديق',
    'create' => true,
    'grain' => 'الحسابات البنكية والصناديق',
    'map' => array(
        'كود الوعاء' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الوعاء' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الوعاء' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'البنك/الموقع' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الحساب' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'المفوضون بالتوقيع' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع التفويض' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'حد الصندوق' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'أمين الصندوق' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'الرصيد الدفتري' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الوعاء' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-12', 'route' => 'Finance/tre_fx_deals.php',
    'table' => 'tre_fx_deals',
    'anchor' => '<table id="emsList_tre_fx_deals"',
    'rows' => "ems_w14_guide_rows('tre_fx_deals')",
    'grid_id' => 'emsList_tre_fx_deals', 'empty' => 'لا سطر مسجل بعد في تنفيذ عمليات الصرف الأجنبي',
    'create' => true,
    'grain' => 'تنفيذ عمليات الصرف الأجنبي',
    'map' => array(
        'رقم الصفقة' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التنفيذ' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'العملة المشتراة' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'العملة المدفوعة' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ المشترى' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الصفقة' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'المكافئ' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'السعر المرجعي م09' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'الفرق عن المرجعي' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'جهة التنفيذ' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'الغرض' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الحركة' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الصفقة' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-06', 'route' => 'Finance/tre_instruments.php',
    'table' => 'tre_instruments',
    'anchor' => '<table id="emsList_tre_instruments"',
    'rows' => "ems_w14_guide_rows('tre_instruments')",
    'grid_id' => 'emsList_tre_instruments', 'empty' => 'لا سطر مسجل بعد في سجل الأدوات المالية',
    'create' => true,
    'grain' => 'سجل الأدوات المالية',
    'map' => array(
        'معرف الأداة' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'الاتجاه' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الأداة' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأداة' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'البنك المسحوب عليه' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الأداة' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'الطرف' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاستحقاق' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع الموجب' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'الوعاء' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الأداة' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-15', 'route' => 'Finance/tre_guarantees.php',
    'table' => 'tre_guarantees',
    'anchor' => '<table id="emsList_tre_guarantees"',
    'rows' => "ems_w14_guide_rows('tre_guarantees')",
    'grid_id' => 'emsList_tre_guarantees', 'empty' => 'لا سطر مسجل بعد في خطابات الضمان والاعتمادات المستندية',
    'create' => true,
    'grain' => 'خطابات الضمان والاعتمادات المستندية',
    'map' => array(
        'معرف الأداة' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'النوع' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'المستفيد' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'العقد المرتبط' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة الغطاء النقدي' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'التسهيل المستخدم' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإصدار' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الانتهاء' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'التمديدات' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع ح04 النظامي' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الأداة' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-17', 'route' => 'Finance/tre_petty_cash.php',
    'table' => 'tre_petty_cash',
    'anchor' => '<table id="emsList_tre_petty_cash"',
    'rows' => "ems_w14_guide_rows('tre_petty_cash')",
    'grid_id' => 'emsList_tre_petty_cash', 'empty' => 'لا سطر مسجل بعد في عهد النثرية وتسويتها',
    'create' => true,
    'grain' => 'عهد النثرية وتسويتها',
    'map' => array(
        'معرف العهدة' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'أمين العهدة' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'حد العهدة' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الفتح' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'السقف الزمني' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'المصروف الموثق' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'المستندات المرفقة' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التسوية' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'نتيجة التسوية' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'التجديد' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العهدة' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-10', 'route' => 'Finance/tre_cash_moves.php',
    'table' => 'tre_cash_moves',
    'anchor' => '<table id="emsList_tre_cash_moves"',
    'rows' => "ems_w14_guide_rows('tre_cash_moves')",
    'grid_id' => 'emsList_tre_cash_moves', 'empty' => 'لا سطر مسجل بعد في حركة الخزينة والصناديق',
    'create' => true,
    'grain' => 'حركة الخزينة والصناديق',
    'map' => array(
        'معرف الحركة' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'الوعاء' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الحركة' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'الوعاء المقابل' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع الموجب' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'الرصيد بعد الحركة' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الحركة' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-07', 'route' => 'Finance/tre_allocations.php',
    'table' => 'tre_allocations',
    'anchor' => '<table id="emsList_tre_allocations"',
    'rows' => "ems_w14_guide_rows('tre_allocations')",
    'grid_id' => 'emsList_tre_allocations', 'empty' => 'لا سطر مسجل بعد في تخصيص التحصيل على الفواتير',
    'create' => true,
    'grain' => 'تخصيص التحصيل على الفواتير',
    'map' => array(
        'معرف التخصيص' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'معرف التحصيل' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الفاتورة' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الفاتورة' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'المخصص عليها' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي بعده' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الفاتورة بعده' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-11', 'route' => 'Finance/tre_transfers.php',
    'table' => 'tre_transfers',
    'anchor' => '<table id="emsList_tre_transfers"',
    'rows' => "ems_w14_guide_rows('tre_transfers')",
    'grid_id' => 'emsList_tre_transfers', 'empty' => 'لا سطر مسجل بعد في التحويلات بين الحسابات',
    'create' => true,
    'grain' => 'التحويلات بين الحسابات',
    'map' => array(
        'رقم التحويل' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'من وعاء' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'إلى وعاء' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'الغرض' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع تفويض الموقع' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع التنفيذ البنكي' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'تأكيد الوصول' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التحويل' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g171:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-18', 'route' => 'Finance/tre_cash_count.php',
    'table' => 'tre_cash_count',
    'anchor' => '<table id="emsList_tre_cash_count"',
    'rows' => "ems_w14_guide_rows('tre_cash_count')",
    'grid_id' => 'emsList_tre_cash_count', 'empty' => 'لا سطر مسجل بعد في الجرد النقدي للخزائن',
    'map' => array(
        'معرف الجلسة' => '+g172:VARCHAR(190) NULL DEFAULT NULL',
        'الصندوق' => '+g173:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الجرد' => '+g174:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الجرد' => '+g175:VARCHAR(190) NULL DEFAULT NULL',
        'لجنة الجرد' => '+g176:VARCHAR(190) NULL DEFAULT NULL',
        'الرصيد الدفتري' => '+g177:VARCHAR(190) NULL DEFAULT NULL',
        'العد الفعلي' => '+g178:VARCHAR(190) NULL DEFAULT NULL',
        'الفرق' => 'action_ref',
        'تفصيل الفئات النقدية' => '+g179:VARCHAR(190) NULL DEFAULT NULL',
        'معالجة الفرق' => '+g180:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الجلسة' => '+g181:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g182:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g183:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g184:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g185:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-13', 'route' => 'Finance/bank_reconciliation_fin.php',
    'table' => 'tre_bank_reconciliation_fin',
    'anchor' => '<table id="emsList_tre_bank_reconciliation_fin"',
    'rows' => "ems_w14_guide_rows('tre_bank_reconciliation_fin')",
    'grid_id' => 'emsList_tre_bank_reconciliation_fin', 'empty' => 'لا سطر مسجل بعد في المطابقة البنكية',
    'create' => true,
    'grain' => 'المطابقة البنكية',
    'map' => array(
        'معرف المطابقة' => '+g186:VARCHAR(190) NULL DEFAULT NULL',
        'الحساب البنكي' => '+g187:VARCHAR(190) NULL DEFAULT NULL',
        'الشهر' => '+g188:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد الكشف البنكي' => '+g189:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد الدفتر' => '+g190:VARCHAR(190) NULL DEFAULT NULL',
        'الفرق' => '+g191:VARCHAR(190) NULL DEFAULT NULL',
        'بنود الفروق' => '+g192:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الفرق' => '+g193:VARCHAR(190) NULL DEFAULT NULL',
        'معالجة الفرق' => '+g194:VARCHAR(190) NULL DEFAULT NULL',
        'الفرق المتبقي' => '+g195:VARCHAR(190) NULL DEFAULT NULL',
        'مرفق الكشف' => '+g196:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المطابقة' => '+g197:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g198:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g199:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g200:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g201:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-03', 'route' => 'Finance/tre_beneficiary.php',
    'table' => 'tre_beneficiary',
    'anchor' => '<table id="emsList_tre_beneficiary"',
    'rows' => "ems_w14_guide_rows('tre_beneficiary')",
    'grid_id' => 'emsList_tre_beneficiary', 'empty' => 'لا سطر مسجل بعد في سجل المستفيدين والتحقق',
    'create' => true,
    'grain' => 'سجل المستفيدين والتحقق',
    'map' => array(
        'معرف المستفيد' => '+g202:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المستفيد' => '+g203:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المستفيد' => '+g204:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الحساب/IBAN' => '+g205:VARCHAR(190) NULL DEFAULT NULL',
        'البنك' => '+g206:VARCHAR(190) NULL DEFAULT NULL',
        'وثيقة التحقق' => '+g207:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التحقق' => '+g208:VARCHAR(190) NULL DEFAULT NULL',
        'محقق مستقل' => '+g209:VARCHAR(190) NULL DEFAULT NULL',
        'تغيير حساب معلق؟' => '+g210:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التحقق' => '+g211:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g212:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g213:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g214:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g215:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'TRS-01', 'route' => 'Finance/tre_liquidity_board.php',
    'table' => 'tre_dashboard_kpi',
    'anchor' => '<table id="emsList_tre_dashboard_kpi"',
    'rows' => "ems_w14_guide_rows('tre_dashboard_kpi')",
    'grid_id' => 'emsList_tre_dashboard_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة الخزينة والسيولة',
    'create' => true,
    'grain' => 'مؤشر سيولة واحد',
    'map' => array(
        'معرف المؤشر' => '+g216:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر KPI Catalog' => '+g217:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g218:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g219:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g220:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g221:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
