<?php
/**
 * fields_dep14b.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-14',
'screens' => array(

array(
    'req' => 'MNT-04', 'route' => 'Maintenance/breakdown_intake.php',
    'table' => 'mnt_breakdown_intake',
    'anchor' => '<table id="emsList_mnt_breakdown_intake"',
    'rows' => "ems_w14_guide_rows('mnt_breakdown_intake')",
    'grid_id' => 'emsList_mnt_breakdown_intake', 'empty' => 'لا سطر مسجل بعد في البلاغ الفني واستقبال العطل',
    'create' => true,
    'grain' => 'البلاغ الفني واستقبال العطل',
    'map' => array(
        'معرف الاستقبال' => 'g1',
        'رقم البلاغ' => 'g2',
        'تاريخ البلاغ' => 'g3',
        'المبلغ' => 'g4',
        'كود المعدة' => 'g5',
        'الموقع' => 'g6',
        'وصف العطل' => 'g7',
        'عقدة الشجرة المبدئية' => 'g8',
        'درجة الخطورة' => 'g9',
        'المعدة متوقفة؟' => 'g10',
        'أثر الإيقاف' => 'g11',
        'قرار الاستقبال' => 'g12',
        'رقم طلب الفحص المتفرع' => 'g13',
        'حالة الاستقبال' => 'g14',
        'شدة العطل الفني' => 'g15',
        'مدة التوقف' => 'g16',
        'الأثر التشغيلي' => 'g17',
        'قابلية المنع' => 'g18',
        'التكرار' => 'g19',
        'أداء الاستجابة' => 'g20',
        'سبب التأخير' => 'g21',
        'سلسلة المسؤولية' => 'g22',
        'وقت توقف المعدة' => 'g23',
        'وقت إبلاغ المشغل' => 'g24',
        'وقت استلام الصيانة' => 'g25',
        'وقت بدء التشخيص' => 'g26',
        'وقت انتهاء التشخيص' => 'g27',
        'وقت طلب القطعة' => 'g28',
        'وقت توفر القطعة' => 'g29',
        'وقت وصولها للموقع' => 'g30',
        'وقت حضور الفني' => 'g31',
        'وقت بدء الإصلاح' => 'g32',
        'وقت انتهاء الإصلاح' => 'g33',
        'وقت الاختبار' => 'g34',
        'وقت التصديق' => 'g35',
        'وقت عودة المعدة للخدمة' => 'g36',
        'إجمالي التوقف' => 'g37',
        'زمن الإصلاح الفعلي' => 'g38',
        'المنشئ' => 'g39',
        'تاريخ الإنشاء' => 'g40',
        'حالة البيانات' => 'g41',
        'مرجع المصدر' => 'g42',
    ),
),

array(
    'req' => 'MNT-03', 'route' => 'Maintenance/workshop.php',
    'table' => 'mnt_workshop',
    'anchor' => '<table id="emsList_mnt_workshop"',
    'rows' => "ems_w14_guide_rows('mnt_workshop')",
    'grid_id' => 'emsList_mnt_workshop', 'empty' => 'لا سطر مسجل بعد في الورش والفنيون',
    'create' => true,
    'grain' => 'الورش والفنيون',
    'map' => array(
        'كود القدرة' => 'g43',
        'النوع' => 'g44',
        'الاسم' => 'g45',
        'الموقع' => 'g46',
        'التخصصات' => 'g47',
        'مستوى الفني' => 'g48',
        'الشهادات وصلاحيتها' => 'g49',
        'الطاقة اليومية (ساعات/أوامر)' => 'g50',
        'متاح الآن؟' => 'g51',
        'التبعية' => 'g52',
        'مرجع العقد عند الخارجي' => 'g53',
        'حالة القدرة' => 'g54',
        'المنشئ' => 'g55',
        'تاريخ الإنشاء' => 'g56',
        'حالة البيانات' => 'g57',
        'مرجع المصدر' => 'g58',
    ),
),

array(
    'req' => 'MNT-10', 'route' => 'maintenance/work_orders.php',
    'table' => 'mnt_order_line',
    'anchor' => '<table id="emsList_mnt_order_line"',
    'rows' => "ems_w14_guide_rows('mnt_order_line')",
    'grid_id' => 'emsList_mnt_order_line', 'empty' => 'لا سطر مسجل بعد في أمر العمل',
    'create' => true,
    'grain' => 'بند واحد في امر عمل — سجل ابن',
    'map' => array(
        'معرف البند' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل البند' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'نوع البند' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'كود الصنف' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'الوصف' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المطلوبة' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المصروفة' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'رقم سند الصرف' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'جهة الخدمة الخارجية' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'التكلفة' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'ضمان مورد؟' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البند' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-13', 'route' => 'Maintenance/preventive_plans.php',
    'table' => 'mnt_preventive_plans',
    'anchor' => '<table id="emsList_mnt_preventive_plans"',
    'rows' => "ems_w14_guide_rows('mnt_preventive_plans')",
    'grid_id' => 'emsList_mnt_preventive_plans', 'empty' => 'لا سطر مسجل بعد في الخطة الوقائية بالساعات',
    'create' => true,
    'grain' => 'الخطة الوقائية بالساعات',
    'map' => array(
        'معرف السطر' => 'g76',
        'كود المعدة' => 'g77',
        'نوع المعدة' => 'g78',
        'مصدر الفاصل' => 'g79',
        'دورة الوقائية' => 'g80',
        'فاصل الأصل المخصص' => 'g81',
        'ساعات الدورة' => 'g82',
        'قراءة آخر وقائية' => 'g83',
        'قراءة العداد الحالية' => 'g84',
        'المتبقي للاستحقاق' => 'g85',
        'تاريخ الاستحقاق المتوقع' => 'g86',
        'بنود الدورة القياسية' => 'g87',
        'حالة الاستحقاق' => 'g88',
        'رقم الأمر المتولد' => 'g89',
        'المنشئ' => 'g90',
        'تاريخ الإنشاء' => 'g91',
        'حالة البيانات' => 'g92',
        'مرجع المصدر' => 'g93',
    ),
),

array(
    'req' => 'MNT-01', 'route' => 'Maintenance/dashboard_mnt.php',
    'table' => 'mnt_dashboard_kpi',
    'anchor' => '<table id="emsList_mnt_dashboard_kpi"',
    'rows' => "ems_w14_guide_rows('mnt_dashboard_kpi')",
    'grid_id' => 'emsList_mnt_dashboard_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة الصيانة والجاهزية',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة الصيانة والجاهزية',
    'map' => array(
        'معرف المؤشر' => 'g94',
        'المؤشر KPI Catalog' => 'g95',
        'القيمة' => 'g96',
        'الوحدة' => 'g97',
        'الحد المقبول' => 'g98',
        'الحالة' => 'g99',
        'آخر تحديث' => 'g100',
    ),
),

array(
    'req' => 'MNT-16', 'route' => 'Maintenance/repeat_repairs.php',
    'table' => 'mnt_repeat_repairs',
    'anchor' => '<table id="emsList_mnt_repeat_repairs"',
    'rows' => "ems_w14_guide_rows('mnt_repeat_repairs')",
    'grid_id' => 'emsList_mnt_repeat_repairs', 'empty' => 'لا سطر مسجل بعد في سجل إعادة الإصلاح',
    'create' => true,
    'grain' => 'سجل إعادة الإصلاح',
    'map' => array(
        'معرف الواقعة' => 'g101',
        'كود المعدة' => 'g102',
        'رقم الأمر الأصلي' => 'g103',
        'عقدة الشجرة' => 'g104',
        'تاريخ التكرار' => 'g105',
        'المدة منذ الشهادة' => 'g106',
        'ضمن صلاحية الشهادة؟' => 'g107',
        'تحليل السبب الجذري RCA' => 'g108',
        'رقم الأمر الجديد' => 'g109',
        'محفز RCA' => 'g110',
        'القرار' => 'g111',
        'حالة الواقعة' => 'g112',
        'المنشئ' => 'g113',
        'تاريخ الإنشاء' => 'g114',
        'حالة البيانات' => 'g115',
        'مرجع المصدر' => 'g116',
    ),
),

array(
    'req' => 'MNT-14', 'route' => 'Maintenance/daily_care.php',
    'table' => 'mnt_daily_care',
    'anchor' => '<table id="emsList_mnt_daily_care"',
    'rows' => "ems_w14_guide_rows('mnt_daily_care')",
    'grid_id' => 'emsList_mnt_daily_care', 'empty' => 'لا سطر مسجل بعد في العناية اليومية والتشحيم',
    'map' => array(
        'معرف السطر' => 'g117',
        'التاريخ' => 'g118',
        'كود المعدة' => 'g119',
        'قائمة العناية للنوع' => 'checklist_ref',
        'المهمة' => 'g120',
        'المنفذ' => 'g121',
        'النتيجة' => 'g122',
        'ملاحظة غير طبيعية' => 'g123',
        'بلاغ متفرع' => 'breakdown_id',
        'حالة السطر' => 'g124',
        'المنشئ' => 'g125',
        'تاريخ الإنشاء' => 'g126',
        'حالة البيانات' => 'g127',
        'مرجع المصدر' => 'g128',
    ),
),

array(
    'req' => 'MNT-17', 'route' => 'Maintenance/mnt_kpis.php',
    'table' => 'mnt_kpis',
    'anchor' => '<table id="emsList_mnt_kpis"',
    'rows' => "ems_w14_guide_rows('mnt_kpis')",
    'grid_id' => 'emsList_mnt_kpis', 'empty' => 'لا سطر مسجل بعد في مؤشرات الصيانة الدورية',
    'create' => true,
    'grain' => 'مؤشرات الصيانة الدورية',
    'map' => array(
        'معرف السطر' => 'g129',
        'الفترة' => 'g130',
        'النطاق' => 'g131',
        'المعدة/النوع' => 'g132',
        'عدد الأعطال' => 'g133',
        'متوسط الزمن بين الأعطال' => 'g134',
        'متوسط زمن الإصلاح' => 'g135',
        'نسبة الجاهزية' => 'g136',
        'أوامر الوقائية المنفذة' => 'g137',
        'الالتزام بالوقائية' => 'g138',
        'تكلفة الصيانة للساعة' => 'g139',
    ),
),

array(
    'req' => 'MNT-11', 'route' => 'Maintenance/part_requests.php',
    'table' => 'mnt_part_requests',
    'anchor' => '<table id="emsList_mnt_part_requests"',
    'rows' => "ems_w14_guide_rows('mnt_part_requests')",
    'grid_id' => 'emsList_mnt_part_requests', 'empty' => 'لا سطر مسجل بعد في طلب صرف القطع لأمر العمل',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في طلب صرف القطع لأمر العمل',
    'map' => array(
        'رقم الطلب' => 'g140',
        'رقم الأمر' => 'g141',
        'تاريخ الطلب' => 'g142',
        'المخزن' => 'g143',
        'البنود المطلوبة' => 'g144',
        'الأولوية' => 'g145',
        'مستلم العهدة' => 'g146',
        'رقم سند الصرف' => 'g147',
        'مطابقة الاستلام' => 'g148',
        'حالة الطلب' => 'g149',
        'المنشئ' => 'g150',
        'تاريخ الإنشاء' => 'g151',
        'حالة البيانات' => 'g152',
        'مرجع المصدر' => 'g153',
    ),
),

array(
    'req' => 'MNT-12', 'route' => 'Maintenance/external_repairs.php',
    'table' => 'mnt_external_repairs',
    'anchor' => '<table id="emsList_mnt_external_repairs"',
    'rows' => "ems_w14_guide_rows('mnt_external_repairs')",
    'grid_id' => 'emsList_mnt_external_repairs', 'empty' => 'لا سطر مسجل بعد في الإصلاح الخارجي ومطالبات الضمان',
    'create' => true,
    'grain' => 'الإصلاح الخارجي ومطالبات الضمان',
    'map' => array(
        'معرف السطر' => 'g154',
        'رقم الأمر' => 'g155',
        'النوع' => 'g156',
        'الجهة الخارجية/المورد' => 'g157',
        'مرجع العقد/الضمان' => 'g158',
        'نطاق العمل' => 'g159',
        'التكلفة المقدرة' => 'g160',
        'التكلفة الفعلية' => 'g161',
        'نتيجة المطالبة' => 'g162',
        'محضر الاستلام' => 'g163',
        'حالة السطر' => 'g164',
        'المنشئ' => 'g165',
        'تاريخ الإنشاء' => 'g166',
        'حالة البيانات' => 'g167',
        'مرجع المصدر' => 'g168',
    ),
),

),
);
