<?php
/**
 * fields_dep17.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-17',
'screens' => array(

array(
    'req' => 'WH-08', 'route' => 'Procurement/wh_hazmat.php',
    'table' => 'wh_hazmat',
    'anchor' => '<table id="emsList_wh_hazmat"',
    'rows' => "ems_w14_guide_rows('wh_hazmat')",
    'grid_id' => 'emsList_wh_hazmat', 'empty' => 'لا سطر مسجل بعد في ضوابط المواد الخطرة والمتفجرات',
    'create' => true,
    'grain' => 'ضوابط المواد الخطرة والمتفجرات',
    'map' => array(
        'معرف السطر' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'كود الصنف' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'فئة الخطورة' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'التصريح النظامي' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'موقع العزل' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'أمين العهدة المخول' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'تتبع الدفعة إلزامي؟' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'سلطة الصرف' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'رقابة مزدوجة؟' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'قيد الصلاحية' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'مسار الإتلاف' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الضوابط' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'WH-19', 'route' => 'Procurement/wh_month_close.php',
    'table' => 'wh_month_close',
    'anchor' => '<table id="emsList_wh_month_close"',
    'rows' => "ems_w14_guide_rows('wh_month_close')",
    'grid_id' => 'emsList_wh_month_close', 'empty' => 'لا سطر مسجل بعد في الإقفال الشهري للمخازن',
    'create' => true,
    'grain' => 'الإقفال الشهري للمخازن',
    'map' => array(
        'معرف الإقفال' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'الشهر' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'المخزن' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'سندات إدخال الشهر' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'سندات صرف الشهر' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'تحويلات الشهر' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'فروق جرد مسواة' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'عهد مفتوحة مرحلة' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة المخزون الختامية' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'مطابقة المالية' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإقفال' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'WH-02', 'route' => 'Procurement/warehouses.php',
    'table' => 'wh_warehouses',
    'anchor' => '<table id="emsList_wh_warehouses"',
    'rows' => "ems_w14_guide_rows('wh_warehouses')",
    'grid_id' => 'emsList_wh_warehouses', 'empty' => 'لا سطر مسجل بعد في سجل المخازن وأنواعها',
    'create' => true,
    'grain' => 'سجل المخازن وأنواعها',
    'map' => array(
        'كود المخزن' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المخزن' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المخزن' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'الأمين النافذ اليوم' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'أسلوب العهدة' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'ترخيص خاص' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'سعة التخزين' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'ضوابط السلامة' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المخزن' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'WH-09', 'route' => 'Procurement/wh_issue_requests.php',
    'table' => 'wh_issue_requests',
    'anchor' => '<table id="emsList_wh_issue_requests"',
    'rows' => "ems_w14_guide_rows('wh_issue_requests')",
    'grid_id' => 'emsList_wh_issue_requests', 'empty' => 'لا سطر مسجل بعد في طلبات الصرف الواردة',
    'create' => true,
    'grain' => 'طلبات الصرف الواردة',
    'map' => array(
        'رقم الطلب' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الورود' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة الطالبة' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الصرف' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع الموجب' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'فحص المرجع' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'البنود المطلوبة' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'فحص الرصيد' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'قرار المخزن' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الطلب' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'WH-10', 'route' => 'Procurement/wh_issue_requests.php',
    'table' => 'wh_issue_request_lines',
    'anchor' => '<table id="emsList_wh_issue_request_lines"',
    'rows' => "ems_w14_guide_rows('wh_issue_request_lines')",
    'grid_id' => 'emsList_wh_issue_request_lines', 'empty' => 'لا سطر مسجل بعد في طلبات الصرف الواردة',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في طلبات الصرف الواردة',
    'map' => array(
        'معرف البند' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الطلب' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'كود الصنف' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المطلوبة' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المعتمدة' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'المصروف تراكميا' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البند' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'WH-16', 'route' => 'Procurement/wh_count.php',
    'table' => 'wh_count',
    'anchor' => '<table id="emsList_wh_count"',
    'rows' => "ems_w14_guide_rows('wh_count')",
    'grid_id' => 'emsList_wh_count', 'empty' => 'لا سطر مسجل بعد في الجرد ومعالجة الفروقات',
    'create' => true,
    'grain' => 'الجرد ومعالجة الفروقات',
    'map' => array(
        'معرف الجلسة' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'المخزن' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'أسلوب الجرد' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الجرد' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'لجنة الجرد' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الأصناف المجرودة' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'بنود الفروق تفصيلها خ10-2' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع التحقيق' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الجلسة' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'WH-14', 'route' => 'Procurement/wh_transfer.php',
    'table' => 'wh_transfer',
    'anchor' => '<table id="emsList_wh_transfer"',
    'rows' => "ems_w14_guide_rows('wh_transfer')",
    'grid_id' => 'emsList_wh_transfer', 'empty' => 'لا سطر مسجل بعد في التحويل بين المخازن',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في التحويل بين المخازن',
    'map' => array(
        'رقم الأمر' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الأمر' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'من مخزن' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'إلى مخزن' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'عدد البنود تفصيلها خ09-2' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'مبرر التحويل' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'وسيلة النقل' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'سند الخروج' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'سند الاستلام' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'مطابقة الاستلام' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الأمر' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'WH-07', 'route' => 'Procurement/stock_proc.php',
    'table' => 'wh_stock_proc',
    'anchor' => '<table id="emsList_wh_stock_proc"',
    'rows' => "ems_w14_guide_rows('wh_stock_proc')",
    'grid_id' => 'emsList_wh_stock_proc', 'empty' => 'لا سطر مسجل بعد في أرصدة المخزون بحالاتها',
    'create' => true,
    'grain' => 'أرصدة المخزون بحالاتها',
    'map' => array(
        'معرف السطر' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'كود الصنف' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'المخزن' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الرصيد' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'متوسط التكلفة' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'آخر حركة' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'تحت الحد الأدنى؟' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
