<?php
/**
 * fields_dep11.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-11',
'screens' => array(

array(
    'req' => 'OPS-06', 'route' => 'Timesheet/timesheet.php',
    'table' => 'ops_timesheet',
    'anchor' => '<table id="emsList_ops_timesheet"',
    'rows' => "ems_w14_guide_rows('ops_timesheet')",
    'grid_id' => 'emsList_ops_timesheet', 'empty' => 'لا سطر مسجل بعد في سجل ساعات التشغيل اليومي',
    'create' => true,
    'grain' => 'سجل ساعات التشغيل اليومي',
    'map' => array(
        'معرف السجل' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'يوم التشغيل' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المعدة' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'المورد المقدم' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المشروع' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة عقد المشروع' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح الحاوية السنوية' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الحاوية الشهرية' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'كود الخانة ونوع الإشغال' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'وسم خارج النافذة التعاقدية' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع الحالي' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'منطقة العمل' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'كود المشغل' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'الوردية' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'سبب تعديل الافتراضي' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'الساعات المتاحة' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المنفذة' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة القياس' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'قراءة العداد أول الوردية' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'قراءة العداد آخر الوردية' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'ساعات العداد' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الفعلي' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الاستعداد' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي التوقف' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'تجاوز الطاقة؟' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'سبب التجاوز' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع الميداني' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المزامنة' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السجل' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'OPS-03', 'route' => 'Operations/monthly_plan.php',
    'table' => 'ops_monthly_plan',
    'anchor' => '<table id="emsList_ops_monthly_plan"',
    'rows' => "ems_w14_guide_rows('ops_monthly_plan')",
    'grid_id' => 'emsList_ops_monthly_plan', 'empty' => 'لا سطر مسجل بعد في الخطة الشهرية للتشغيل',
    'create' => true,
    'grain' => 'الخطة الشهرية للتشغيل',
    'map' => array(
        'معرف سطر الخطة' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'شهر الخطة' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المشروع' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المشروع' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'كود عقد العميل' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المعدة' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'المستهدف التعاقدي' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'مستهدف الخطة' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة القياس' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'أيام العمل المخططة' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'ورديات اليوم' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'الساعات المتاحة/وردية' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'معامل الموسم' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'المستهدف المعاير بالموسم' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'مبرر الفارق عن التعاقدي' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'OPS-08', 'route' => 'Approvals/hours_approval.php',
    'table' => 'ops_hours_approval',
    'anchor' => '<table id="emsList_ops_hours_approval"',
    'rows' => "ems_w14_guide_rows('ops_hours_approval')",
    'grid_id' => 'emsList_ops_hours_approval', 'empty' => 'لا سطر مسجل بعد في اعتماد الوحدات',
    'create' => true,
    'grain' => 'اعتماد الوحدات',
    'map' => array(
        'معرف الدفعة' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'يوم الاعتماد' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'نطاق الدفعة' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'عدد السجلات' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'سجلات بتجاوز طاقة' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'سجلات ناقصة السبب' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'مرحلة الاعتماد' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'معتمد الموقع' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'معتمد الأطراف' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'معتمد العقود' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'نتيجة المطابقة' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'سجلات مستثناة' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الاستثناء' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الدفعة' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'OPS-12', 'route' => 'Operations/monthly_close.php',
    'table' => 'ops_monthly_close',
    'anchor' => '<table id="emsList_ops_monthly_close"',
    'rows' => "ems_w14_guide_rows('ops_monthly_close')",
    'grid_id' => 'emsList_ops_monthly_close', 'empty' => 'لا سطر مسجل بعد في الإقفال الشهري للتشغيل',
    'create' => true,
    'grain' => 'الإقفال الشهري للتشغيل',
    'map' => array(
        'معرف الإقفال' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'شهر الإقفال' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'أيام الشهر' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'أيام معتمدة كاملا' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'أيام ناقصة' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'سجلات معلقة' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'قرارات توقف مفتوحة' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الوحدات المعتمدة' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي ساعات الفعلي' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي التوقف' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة تحقق الخطة' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'قائمة الاستثناءات المرحلة' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإقفال' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'OPS-10', 'route' => 'Workforce/worker_worklog.php',
    'table' => 'ops_worker_worklog',
    'anchor' => '<table id="emsList_ops_worker_worklog"',
    'rows' => "ems_w14_guide_rows('ops_worker_worklog')",
    'grid_id' => 'emsList_ops_worker_worklog', 'empty' => 'لا سطر مسجل بعد في سجل الأحداث التشغيلية',
    'create' => true,
    'grain' => 'سجل الأحداث التشغيلية',
    'map' => array(
        'معرف الحدث' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الحدث' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الحدث' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'مصدره' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'المشروع' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'المعدة' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'ملخص الحدث' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع السجل الأصلي' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'درجة الأهمية' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
