<?php
/**
 * fields_dep03.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-03',
'screens' => array(

array(
    'req' => 'FIN-01', 'route' => 'Financing/financiers_registry.php',
    'table' => 'fin_financier',
    'anchor' => '<table id="emsList_fin_financiers">',
    'rows' => "ems_w14_guide_rows('fin_financier')",
    'grid_id' => 'emsList_fin_financiers', 'empty' => 'لا ممول مسجل بعد',
    'create' => true,
    'grain' => 'ممول واحد',
    'map' => array(
        'كود الممول' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الممول بالمصدر (ل02)' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم القانوني' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الممول' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف العلائقي' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'شريحة الأهمية' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'الدولة' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'السجل التجاري' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التأهيل والعناية' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'العملات' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'نماذج التمويل المقبولة' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'بداية العلاقة' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'آخر نشاط' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'مدة العلاقة (سنة)' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العلاقة' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'مدير العلاقة' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'هاتف المسؤول' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'بريد المسؤول' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'اتفاقية إطارية' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'سقف التمويل المعتمد' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'عدد العمليات' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'رأس المال الممول $' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'رأس المال الممول QAR' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'رأس المال الممول SDG' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'الرصيد القائم $' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'الأرباح التعاقدية $' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'الحجية' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-02', 'route' => 'Financing/fin_financier_contacts.php',
    'table' => 'fin_financier_contact',
    'anchor' => '<table id="emsList_fin_contacts">',
    'rows' => "ems_w14_guide_rows('fin_financier_contact')",
    'grid_id' => 'emsList_fin_contacts', 'empty' => 'لا جهة اتصال مسجلة بعد',
    'map' => array(
        'كود الجهة' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'الدور' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'مفوض توقيع؟' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'الهاتف' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'البريد' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'سريان من' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'إلى' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-04', 'route' => 'Financing/fin_needs.php',
    'table' => 'fin_funding_need',
    'anchor' => '<table id="emsList_fin_needs"',
    'rows' => "ems_w14_guide_rows('fin_funding_need')",
    'grid_id' => 'emsList_fin_needs', 'empty' => 'لا حاجة تمويل مسجلة بعد',
    'map' => array(
        'كود الحاجة' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'كود العملية الناتجة' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'Selected_Financier_ID نتيجة لاحقة بعد العروض والاختيار' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'Requesting_Department الإدارة الطالبة' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'Requested_By الطالب' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'Required_By_Date' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'Priority' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'Need_Approval اعتماد الحاجة' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'Approved_Amount' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'الأصل المطلوب' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'كود العين' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة (من العملية)' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج التمويل' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'Need_Date' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'Need_Must_Precede' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'المشروع/عقد العميل' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الحاجة' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'Record_Basis' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'Derivation_Rule' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'Confidence' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'Needs_Review' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-05', 'route' => 'Financing/fin_offers.php',
    'table' => 'fin_funding_offer',
    'anchor' => '<table id="emsList_fin_offers"',
    'rows' => "ems_w14_guide_rows('fin_funding_offer')",
    'grid_id' => 'emsList_fin_offers', 'empty' => 'لا عرض تمويل مسجل بعد',
    'map' => array(
        'كود العرض' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'كود الحاجة' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'كود العملية الناتجة' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'صفة العرض' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'رقم النسخة' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'النسخة الأساس' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'ما الذي تغير عن سابقتها' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'من اقترح التغيير' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التغيير' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التفاوض' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج التمويل' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'رأس المال' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة الأرباح %' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الأرباح' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'المقدم' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'المدة (شهر)' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الأقساط' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة القسط' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'الضمانات' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ العرض' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'Offer_Must_Precede' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'عروض المنافسين' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'Record_Basis' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'Derivation_Rule' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'Confidence' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'Needs_Review' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-06', 'route' => 'Financing/fin_precontract_review.php',
    'table' => 'fin_precontract_review',
    'anchor' => '<table id="emsList_fin_prereview">',
    'rows' => "ems_w14_guide_rows('fin_precontract_review')",
    'grid_id' => 'emsList_fin_prereview', 'empty' => 'لا مراجعة مسجلة بعد',
    'map' => array(
        'كود المراجعة' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الحاجة + العرض المختار + مسودة العقد' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => 'client_name',
        'واقعة الاختيار والتعاقد' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'أهلية الممول (KYC/سجل)' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'اكتمال المستندات' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'مراجعة النموذج' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'مراجعة رأس المال والعائد' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'مراجعة السداد والملكية' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'الضمانات' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'المعالجة المحاسبية المطلوبة' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'Review_Must_Precede' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'Record_Basis' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
        'Derivation_Rule' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'Confidence' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'Needs_Review' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => 'notes',
    ),
),

array(
    'req' => 'FIN-07', 'route' => 'Financing/fin_contracts.php',
    'table' => 'fin_finance_contract',
    'anchor' => '<table id="emsList_fin_contracts"',
    'rows' => "ems_w14_guide_rows('fin_finance_contract')",
    'grid_id' => 'emsList_fin_contracts', 'empty' => 'لا عقد تمويل مسجل بعد',
    'map' => array(
        'كود العقد' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر العقد' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد بالمصدر' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع الخارجي (رقم عقد الممول)' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'الكيان المتعاقد (الشركة)' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'رقم النسخة' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التوقيع' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج التمويل' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'رأس المال' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'بداية العقد' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'آخر حركة' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'المدة (شهر)' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'النهاية التعاقدية' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المستند' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المراجعة القانونية' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الاعتماد' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'من اعتمد' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع آخر ملحق نافذ' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
        'آلية الإنهاء/الإقفال' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'عدد العمليات تحته' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العقد' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'الحجية' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-08', 'route' => 'Financing/fin_contract_terms.php',
    'table' => 'fin_contract_term',
    'anchor' => '<table id="emsList_fin_terms">',
    'rows' => "ems_w14_guide_rows('fin_contract_term')",
    'grid_id' => 'emsList_fin_terms', 'empty' => 'لا بند مسجل بعد',
    'map' => array(
        'كود العقد' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'كود العملية' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج التمويل' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'سريان من' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'رأس المال' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة المقدم %' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة المقدم' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة الأرباح %' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الأرباح التعاقدية' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'رسوم إدارية' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'رسوم تأمين' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'المدة (شهر)' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'نظام الأقساط' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الأقساط' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة القسط' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'تحويل الملكية في نهاية التمويل التفصيل' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'حفظ مستندات الملكية التفصيل' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'الحجية' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g171:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g172:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g173:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-09', 'route' => 'Financing/fin_covenants.php',
    'table' => 'fin_contract_covenant',
    'anchor' => '<table id="emsList_fin_covenants"',
    'rows' => "ems_w14_guide_rows('fin_contract_covenant')",
    'grid_id' => 'emsList_fin_covenants', 'empty' => 'لا التزام تمويلي مسجل بعد',
    'map' => array(
        'كود العقد' => '+g174:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g175:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g176:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج التمويل' => '+g177:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+g178:VARCHAR(190) NULL DEFAULT NULL',
        'توفير رأس المال' => '+g179:VARCHAR(190) NULL DEFAULT NULL',
        'توقيت إتاحة التمويل' => '+g180:VARCHAR(190) NULL DEFAULT NULL',
        'اختيار الأصل' => '+g181:VARCHAR(190) NULL DEFAULT NULL',
        'اختيار البائع' => '+g182:VARCHAR(190) NULL DEFAULT NULL',
        'دفع قيمة الأصل للبائع' => '+g183:VARCHAR(190) NULL DEFAULT NULL',
        'التسليم والاستلام' => '+g184:VARCHAR(190) NULL DEFAULT NULL',
        'الفحص والقبول' => '+g185:VARCHAR(190) NULL DEFAULT NULL',
        'تسجيل الأصل' => '+g186:VARCHAR(190) NULL DEFAULT NULL',
        'الترخيص' => '+g187:VARCHAR(190) NULL DEFAULT NULL',
        'التأمين' => '+g188:VARCHAR(190) NULL DEFAULT NULL',
        'رسوم التأمين' => '+g189:VARCHAR(190) NULL DEFAULT NULL',
        'الضرائب والرسوم' => '+g190:VARCHAR(190) NULL DEFAULT NULL',
        'التشغيل' => '+g191:VARCHAR(190) NULL DEFAULT NULL',
        'الصيانة' => '+g192:VARCHAR(190) NULL DEFAULT NULL',
        'قطع الغيار' => '+g193:VARCHAR(190) NULL DEFAULT NULL',
        'مخاطر الهلاك والتلف' => '+g194:VARCHAR(190) NULL DEFAULT NULL',
        'حفظ مستندات الملكية' => '+g195:VARCHAR(190) NULL DEFAULT NULL',
        'الضمانات والرهن' => '+g196:VARCHAR(190) NULL DEFAULT NULL',
        'مسؤولية التعطل وعدم الانتفاع' => '+g197:VARCHAR(190) NULL DEFAULT NULL',
        'تحويل الملكية في نهاية التمويل' => '+g198:VARCHAR(190) NULL DEFAULT NULL',
        'التسوية المبكرة' => '+g199:VARCHAR(190) NULL DEFAULT NULL',
        'رسوم التمويل الإدارية' => '+g200:VARCHAR(190) NULL DEFAULT NULL',
        'الإخطارات' => '+g201:VARCHAR(190) NULL DEFAULT NULL',
        'توفير المستندات' => '+g202:VARCHAR(190) NULL DEFAULT NULL',
        'إجراءات الإقفال' => '+g203:VARCHAR(190) NULL DEFAULT NULL',
        'تفصيل الحسم (المرجع بسجل البنود)' => '+g204:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الالتزامات المحسومة' => '+g205:VARCHAR(190) NULL DEFAULT NULL',
        'حالة اكتمال المصفوفة' => '+g206:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد/المادة' => '+g207:VARCHAR(190) NULL DEFAULT NULL',
        'المعبئ' => '+g208:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التعبئة' => '+g209:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g210:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-10', 'route' => 'Financing/operation_profile.php',
    'table' => 'financing_operations',
    'anchor' => '<table id="emsList_fin_ops">',
    'rows' => "ems_w14_guide_rows('financing_operations')",
    'grid_id' => 'emsList_fin_ops', 'empty' => 'لا عملية تمويل مسجلة بعد',
    'map' => array(
        'كود العملية' => '+g211:VARCHAR(190) NULL DEFAULT NULL',
        'كود العملية بالمصدر (ل03)' => '+g212:VARCHAR(190) NULL DEFAULT NULL',
        'كود العقد' => '+g213:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g214:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g215:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج التمويل' => '+g216:VARCHAR(190) NULL DEFAULT NULL',
        'النموذج الاقتصادي (المصدر)' => '+g217:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g218:VARCHAR(190) NULL DEFAULT NULL',
        'تصنيف العين' => '+g219:VARCHAR(190) NULL DEFAULT NULL',
        'نوع العين' => '+g220:VARCHAR(190) NULL DEFAULT NULL',
        'كود العين' => '+g221:VARCHAR(190) NULL DEFAULT NULL',
        'أول حركة' => '+g222:VARCHAR(190) NULL DEFAULT NULL',
        'آخر حركة' => '+g223:VARCHAR(190) NULL DEFAULT NULL',
        'رأس المال المعتمد' => '+g224:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر رأس المال' => '+g225:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة شراء العين' => 'purchase_value',
        'نسبة الممول في الأصل' => '+g226:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة المقدم' => '+g227:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة المقدم' => '+g228:VARCHAR(190) NULL DEFAULT NULL',
        'إضافة رأس مال' => '+g229:VARCHAR(190) NULL DEFAULT NULL',
        'رسوم إدارية' => '+g230:VARCHAR(190) NULL DEFAULT NULL',
        'رسوم تأمين' => '+g231:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة الأرباح' => '+g232:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الأرباح التعاقدية' => '+g233:VARCHAR(190) NULL DEFAULT NULL',
        'APR (المصدر)' => '+g234:VARCHAR(190) NULL DEFAULT NULL',
        'المدة (شهر)' => '+g235:VARCHAR(190) NULL DEFAULT NULL',
        'نظام الأقساط' => '+g236:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الأقساط' => '+g237:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة القسط' => '+g238:VARCHAR(190) NULL DEFAULT NULL',
        'الاستحقاق بالدفتر' => '+g239:VARCHAR(190) NULL DEFAULT NULL',
        'الدفعات بالدفتر' => '+g240:VARCHAR(190) NULL DEFAULT NULL',
        'صفوف الدفتر' => '+g241:VARCHAR(190) NULL DEFAULT NULL',
        'عدد تغيرات العقد' => '+g242:VARCHAR(190) NULL DEFAULT NULL',
        'حالة اكتمال البيانات (المصدر)' => '+g243:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة التشغيلية' => '+g244:VARCHAR(190) NULL DEFAULT NULL',
        'الحجية' => '+g245:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g246:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g247:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g248:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة اكتمال الدورة المستندية' => '+g249:VARCHAR(190) NULL DEFAULT NULL',
        'حلقات الدورة المفقودة' => '+g250:VARCHAR(190) NULL DEFAULT NULL',
        'Asset_Sourcing_Mode' => '+g251:VARCHAR(190) NULL DEFAULT NULL',
        'استثناء التسلسل' => '+g252:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-14', 'route' => 'Financing/fin_financier_dues.php',
    'table' => 'fin_financier_due',
    'anchor' => '<table id="emsList_fin_dues">',
    'rows' => "ems_w14_guide_rows('fin_financier_due')",
    'grid_id' => 'emsList_fin_dues', 'empty' => 'لا استحقاق مسجل بعد',
    'create' => true,
    'grain' => 'استحقاق ممول لفترة',
    'map' => array(
        'كود الاستحقاق' => '+g253:VARCHAR(190) NULL DEFAULT NULL',
        'كود العملية' => '+g254:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g255:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g256:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g257:VARCHAR(190) NULL DEFAULT NULL',
        'المستحق حتى الأفق' => '+g258:VARCHAR(190) NULL DEFAULT NULL',
        'المدفوع (الدفتر)' => '+g259:VARCHAR(190) NULL DEFAULT NULL',
        'صافي المستحق غير المسدد' => '+g260:VARCHAR(190) NULL DEFAULT NULL',
        'أساس الاحتساب' => '+g261:VARCHAR(190) NULL DEFAULT NULL',
        'Record_Basis' => '+g262:VARCHAR(190) NULL DEFAULT NULL',
        'Derivation_Rule' => '+g263:VARCHAR(190) NULL DEFAULT NULL',
        'Confidence' => '+g264:VARCHAR(190) NULL DEFAULT NULL',
        'Needs_Review' => '+g265:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g266:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g267:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g268:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-15', 'route' => 'Financing/fin_contract_close.php',
    'table' => 'fin_contract_close',
    'anchor' => '<table id="emsList_fin_cclose">',
    'rows' => "ems_w14_guide_rows('fin_contract_close')",
    'grid_id' => 'emsList_fin_cclose', 'empty' => 'لا اقفال تعاقدي مسجل بعد',
    'map' => array(
        'Close_ID' => '+g269:VARCHAR(190) NULL DEFAULT NULL',
        'FOP_ID' => '+g270:VARCHAR(190) NULL DEFAULT NULL',
        'FCON_ID' => 'close_code',
        'Financier_ID' => '+g271:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g272:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الفترة' => '+g273:VARCHAR(190) NULL DEFAULT NULL',
        'بداية الفترة' => '+g274:VARCHAR(190) NULL DEFAULT NULL',
        'نهاية الفترة' => '+g275:VARCHAR(190) NULL DEFAULT NULL',
        'شهر نهاية الفترة (وسم)' => '+g276:VARCHAR(190) NULL DEFAULT NULL',
        'Monthly_Close_ID' => '+g277:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد أصل افتتاحي' => '+g278:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد عائد افتتاحي' => '+g279:VARCHAR(190) NULL DEFAULT NULL',
        'أصل مستحق بالفترة' => '+g280:VARCHAR(190) NULL DEFAULT NULL',
        'عائد مستحق بالفترة' => '+g281:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي مستحق الفترة' => '+g282:VARCHAR(190) NULL DEFAULT NULL',
        'رسوم مستحقة' => '+g283:VARCHAR(190) NULL DEFAULT NULL',
        'تعديلات معتمدة ±' => '+g284:VARCHAR(190) NULL DEFAULT NULL',
        'مدفوعات مخصصة للفترة' => '+g285:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد أصل ختامي' => '+g286:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد عائد ختامي' => '+g287:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الرصيد الختامي' => '+g288:VARCHAR(190) NULL DEFAULT NULL',
        'المتأخر من الفترة' => '+g289:VARCHAR(190) NULL DEFAULT NULL',
        'أيام التأخير' => '+g290:VARCHAR(190) NULL DEFAULT NULL',
        'الاستحقاق التالي' => '+g291:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإقفال' => '+g292:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g293:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g294:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g295:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g296:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع كشف الحساب' => '+g297:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g298:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g299:VARCHAR(190) NULL DEFAULT NULL',
        'اختبار الترحيل (Opening=Closing السابق)' => '+g300:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-16', 'route' => 'Financing/fin_monthly_close.php',
    'table' => 'fin_monthly_close_stmt',
    'anchor' => '<table id="emsList_fin_mclose">',
    'rows' => "ems_w14_guide_rows('fin_monthly_close_stmt')",
    'grid_id' => 'emsList_fin_mclose', 'empty' => 'لا اقفال شهري مسجل بعد',
    'create' => true,
    'grain' => 'اقفال شهري لعقد تمويل',
    'map' => array(
        'Monthly_Close_ID' => '+g301:VARCHAR(190) NULL DEFAULT NULL',
        'FOP_ID' => '+g302:VARCHAR(190) NULL DEFAULT NULL',
        'FCON_ID' => '+g303:VARCHAR(190) NULL DEFAULT NULL',
        'Financier_ID' => '+g304:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g305:VARCHAR(190) NULL DEFAULT NULL',
        'الشهر المحاسبي (Calendar Month)' => '+g306:VARCHAR(190) NULL DEFAULT NULL',
        'بداية الشهر' => '+g307:VARCHAR(190) NULL DEFAULT NULL',
        'نهاية الشهر' => '+g308:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد أول الشهر' => '+g309:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الإقفالات التعاقدية بالشهر' => '+g310:VARCHAR(190) NULL DEFAULT NULL',
        'الإقفالات التعاقدية (مراجع)' => '+g311:VARCHAR(190) NULL DEFAULT NULL',
        'المستحق خلال الشهر' => '+g312:VARCHAR(190) NULL DEFAULT NULL',
        'المدفوعات الفعلية خلال الشهر' => '+g313:VARCHAR(190) NULL DEFAULT NULL',
        'المخصص خلال الشهر' => '+g314:VARCHAR(190) NULL DEFAULT NULL',
        'دفعات مقدمة/غير مخصصة' => '+g315:VARCHAR(190) NULL DEFAULT NULL',
        'المتأخر خلال الشهر' => '+g316:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد آخر الشهر' => '+g317:VARCHAR(190) NULL DEFAULT NULL',
        'اختبار الترحيل الشهري' => '+g318:VARCHAR(190) NULL DEFAULT NULL',
        'مطابقة كشف الممول' => '+g319:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإقفال الشهري' => '+g320:VARCHAR(190) NULL DEFAULT NULL',
        'المعد' => '+g321:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g322:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g323:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g324:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g325:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g326:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-17', 'route' => 'Financing/fin_payment_orders.php',
    'table' => 'fin_payment_order',
    'anchor' => '<table id="emsList_fin_orders">',
    'rows' => "ems_w14_guide_rows('fin_payment_order')",
    'grid_id' => 'emsList_fin_orders', 'empty' => 'لا امر دفع مسجل بعد',
    'map' => array(
        'كود السداد' => '+g327:VARCHAR(190) NULL DEFAULT NULL',
        'كود العملية' => '+g328:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g329:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ المدفوع (مجمع)' => '+g330:VARCHAR(190) NULL DEFAULT NULL',
        'عدد صفوف الدفتر' => '+g331:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g332:VARCHAR(190) NULL DEFAULT NULL',
        'كود أمر الدفع' => '+g333:VARCHAR(190) NULL DEFAULT NULL',
        'معتمد الأمر' => '+g334:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع البنكي' => '+g335:VARCHAR(190) NULL DEFAULT NULL',
        'أمر الدفع' => '+g336:VARCHAR(190) NULL DEFAULT NULL',
        'الحجية' => '+g337:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g338:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g339:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g340:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الطلب' => '+g341:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ المطلوب' => '+g342:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ المعتمد' => '+g343:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الأمر' => '+g344:VARCHAR(190) NULL DEFAULT NULL',
        'معتمد الأمر (مستقبلي)' => '+g345:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التنفيذ الفعلي' => '+g346:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ المنفذ' => '+g347:VARCHAR(190) NULL DEFAULT NULL',
        'البنك/طريقة السداد' => '+g348:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الخزينة/المالية' => 'treasury_ref',
        'حالة المطابقة' => '+g349:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-18', 'route' => 'Financing/fin_payment_allocation.php',
    'table' => 'fin_payment_allocation',
    'anchor' => '<table id="emsList_fin_alloc">',
    'rows' => "ems_w14_guide_rows('fin_payment_allocation')",
    'grid_id' => 'emsList_fin_alloc', 'empty' => 'لا تخصيص سداد مسجل بعد',
    'map' => array(
        'كود التخصيص' => '+g350:VARCHAR(190) NULL DEFAULT NULL',
        'Payment_ID' => 'order_id',
        'FOP_ID' => '+g351:VARCHAR(190) NULL DEFAULT NULL',
        'FINS_ID' => '+g352:VARCHAR(190) NULL DEFAULT NULL',
        'Contractual_Close_ID' => '+g353:VARCHAR(190) NULL DEFAULT NULL',
        'Monthly_Close_ID' => '+g354:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المكون' => '+g355:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g356:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ المخصص' => '+g357:VARCHAR(190) NULL DEFAULT NULL',
        'Outstanding قبل' => '+g358:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التخصيص' => '+g359:VARCHAR(190) NULL DEFAULT NULL',
        'قاعدة التخصيص' => '+g360:VARCHAR(190) NULL DEFAULT NULL',
        'علم تجاوز' => '+g361:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g362:VARCHAR(190) NULL DEFAULT NULL',
        'اختبار Σ لكل دفعة' => '+g363:VARCHAR(190) NULL DEFAULT NULL',
        'اختبار ≤ المستحق' => '+g364:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-20', 'route' => 'Financing/fin_capital_balance.php',
    'table' => 'fin_capital_balance',
    'anchor' => '<table id="emsList_fin_capital">',
    'rows' => "ems_w14_guide_rows('fin_capital_balance')",
    'grid_id' => 'emsList_fin_capital', 'empty' => 'لا رصيد مسجل بعد',
    'create' => true,
    'grain' => 'رصيد راس مال لعملية تمويل',
    'map' => array(
        'كود العملية' => '+g365:VARCHAR(190) NULL DEFAULT NULL',
        'كود الممول' => '+g366:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الممول (بحث)' => '+g367:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g368:VARCHAR(190) NULL DEFAULT NULL',
        'رأس المال المعتمد' => '+g369:VARCHAR(190) NULL DEFAULT NULL',
        'المسدد من الأصل' => '+g370:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي من الأصل' => '+g371:VARCHAR(190) NULL DEFAULT NULL',
        'العائد التعاقدي' => '+g372:VARCHAR(190) NULL DEFAULT NULL',
        'المدفوع للعائد' => '+g373:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي من العائد' => '+g374:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي المدفوع (الدفتر)' => '+g375:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الالتزام المتبقي' => '+g376:VARCHAR(190) NULL DEFAULT NULL',
        'آخر حركة' => '+g377:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة المالية' => '+g378:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-23', 'route' => 'Financing/asset_disposal.php',
    'table' => 'fin_asset_disposal',
    'anchor' => '<table id="emsList_fin_disposal">',
    'rows' => "ems_w14_guide_rows('fin_asset_disposal')",
    'grid_id' => 'emsList_fin_disposal', 'empty' => 'لا انتقال ملكية مسجل بعد',
    'create' => true,
    'grain' => 'انتقال ملكية اصل واحد',
    'map' => array(
        'كود الانتقال' => '+g379:VARCHAR(190) NULL DEFAULT NULL',
        'النطاق' => '+g380:VARCHAR(190) NULL DEFAULT NULL',
        'FOP_ID' => '+g381:VARCHAR(190) NULL DEFAULT NULL',
        'FCON_ID' => '+g382:VARCHAR(190) NULL DEFAULT NULL',
        'Financier_ID' => '+g383:VARCHAR(190) NULL DEFAULT NULL',
        'كود العين/الآلية' => '+g384:VARCHAR(190) NULL DEFAULT NULL',
        'ترتيب الانتقال' => '+g385:VARCHAR(190) NULL DEFAULT NULL',
        'من (المالك السابق)' => '+g386:VARCHAR(190) NULL DEFAULT NULL',
        'إلى (المالك الجديد)' => '+g387:VARCHAR(190) NULL DEFAULT NULL',
        'الحصة %' => '+g388:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => '+g389:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة البيع' => '+g390:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g391:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الخروج' => '+g392:VARCHAR(190) NULL DEFAULT NULL',
        'المستند' => '+g393:VARCHAR(190) NULL DEFAULT NULL',
        'الاعتماد' => '+g394:VARCHAR(190) NULL DEFAULT NULL',
        'الحجية' => '+g395:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g396:VARCHAR(190) NULL DEFAULT NULL',
        'Source_Row_Ref' => '+g397:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g398:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-24', 'route' => 'Financing/fin_final_close.php',
    'table' => 'fin_final_close',
    'anchor' => '<table id="emsList_fin_fclose">',
    'rows' => "ems_w14_guide_rows('fin_final_close')",
    'grid_id' => 'emsList_fin_fclose', 'empty' => 'لا اقفال نهائي مسجل بعد',
    'map' => array(
        'كود العملية' => '+g399:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g400:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي من الأصل' => '+g401:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي من العائد' => '+g402:VARCHAR(190) NULL DEFAULT NULL',
        'استحقاقات مفتوحة' => '+g403:VARCHAR(190) NULL DEFAULT NULL',
        'انحرافات غير محسومة (مرجع ت22)' => '+g404:VARCHAR(190) NULL DEFAULT NULL',
        'حكم الملكية (مرجع ت12/ت23)' => '+g405:VARCHAR(190) NULL DEFAULT NULL',
        'تسوية مبكرة (FSET)' => '+g406:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإقفال' => '+g407:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g408:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ طلب الإقفال' => '+g409:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإقفال الفعلي' => '+g410:VARCHAR(190) NULL DEFAULT NULL',
        'آخر إقفال دوري' => '+g411:VARCHAR(190) NULL DEFAULT NULL',
        'آخر دفعة ومرجعها' => '+g412:VARCHAR(190) NULL DEFAULT NULL',
        'اكتمال نقل الملكية' => '+g413:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع مستند الملكية' => '+g414:VARCHAR(190) NULL DEFAULT NULL',
        'إخلاء الطرف/شهادة الإقفال' => '+g415:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g416:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g417:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g418:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-26', 'route' => 'Financing/fin_ref_dictionary.php',
    'table' => 'fin_ref_list',
    'anchor' => '<table id="emsList_fin_ref">',
    'rows' => "ems_w14_guide_rows('fin_ref_list')",
    'grid_id' => 'emsList_fin_ref', 'empty' => 'لا مفردة مرجعية مسجلة بعد',
    'map' => array(
        'USD' => '+g419:VARCHAR(190) NULL DEFAULT NULL',
        'مرابحة' => '+g420:VARCHAR(190) NULL DEFAULT NULL',
        'CONFIRMED_DOCUMENT' => '+g421:VARCHAR(190) NULL DEFAULT NULL',
        'Open' => '+g422:VARCHAR(190) NULL DEFAULT NULL',
        'High' => '+g423:VARCHAR(190) NULL DEFAULT NULL',
        'SUPPLIER' => '+g424:VARCHAR(190) NULL DEFAULT NULL',
        'على الشركة' => '+g425:VARCHAR(190) NULL DEFAULT NULL',
        'بنك' => '+g426:VARCHAR(190) NULL DEFAULT NULL',
        'نشط' => '+g427:VARCHAR(190) NULL DEFAULT NULL',
        'مكتمل' => '+g428:VARCHAR(190) NULL DEFAULT NULL',
        'مطروحة' => '+g429:VARCHAR(190) NULL DEFAULT NULL',
        'مستلم' => '+g430:VARCHAR(190) NULL DEFAULT NULL',
        'معتمد' => '+g431:VARCHAR(190) NULL DEFAULT NULL',
        'نافذ' => '+g432:VARCHAR(190) NULL DEFAULT NULL',
        'مستحق تاريخيا' => '+g433:VARCHAR(190) NULL DEFAULT NULL',
        'Direct' => '+g434:VARCHAR(190) NULL DEFAULT NULL',
        'إعادة جدولة' => '+g435:VARCHAR(190) NULL DEFAULT NULL',
        'على الممول' => '+g436:VARCHAR(190) NULL DEFAULT NULL',
        'مقفلة مغطاة' => '+g437:VARCHAR(190) NULL DEFAULT NULL',
        'مؤهلة للإقفال' => '+g438:VARCHAR(190) NULL DEFAULT NULL',
        'الشيت' => '+g439:VARCHAR(190) NULL DEFAULT NULL',
        'الحقل' => '+g440:VARCHAR(190) NULL DEFAULT NULL',
        'النوع' => '+g441:VARCHAR(190) NULL DEFAULT NULL',
        'تصنيف الفراغ (ما يعنيه الفراغ)' => '+g442:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-27', 'route' => 'Financing/fin_migration_map.php',
    'table' => 'fin_migration_map',
    'anchor' => '<table id="emsList_fin_migmap">',
    'rows' => "ems_w14_guide_rows('fin_migration_map')",
    'grid_id' => 'emsList_fin_migmap', 'empty' => 'لا سطر ترحيل مسجل بعد',
    'create' => true,
    'grain' => 'سطر خريطة ترحيل',
    'map' => array(
        '#' => 'id',
        'النطاق' => '+g443:VARCHAR(190) NULL DEFAULT NULL',
        'المصدر/الشيت السابق' => '+g444:VARCHAR(190) NULL DEFAULT NULL',
        'العمود/الوصف' => '+g445:VARCHAR(190) NULL DEFAULT NULL',
        'الوجهة/القرار' => '+g446:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف' => '+g447:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة' => '+g448:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'FIN-28', 'route' => 'Financing/fin_close_audit.php',
    'table' => 'fin_close_audit',
    'anchor' => '<table id="emsList_fin_audit">',
    'rows' => "ems_w14_guide_rows('fin_close_audit')",
    'grid_id' => 'emsList_fin_audit', 'empty' => 'لا بند مراجعة مسجل بعد',
    'create' => true,
    'grain' => 'بند مراجعة اغلاق',
    'map' => array(
        'القسم' => '+g449:VARCHAR(190) NULL DEFAULT NULL',
        'البند' => '+g450:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة/النتيجة' => '+g451:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g452:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة' => '+g453:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
