<?php
/**
 * fields_dep05.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-05',
'screens' => array(

array(
    'req' => 'ACC-17', 'route' => 'Finance/acc_adjustments.php',
    'table' => 'fina_acc_adjustments',
    'anchor' => '<table id="emsList_acc_adjustments"',
    'rows' => "ems_w14_guide_rows('fina_acc_adjustments')",
    'grid_id' => 'emsList_acc_adjustments', 'empty' => 'لا سطر مسجل بعد في الاستحقاقات والمقدَّمات والمخصصات',
    'create' => true,
    'grain' => 'الاستحقاقات والمقدَّمات والمخصصات',
    'map' => array(
        'معرف السطر' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'النوع' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'كود الحساب' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'مركز التكلفة' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'الأساس/المستند' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'جدول الاستهلاك/العكس' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'القيد المتولد' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'قيد العكس التالي' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-25', 'route' => 'Finance/acc_reopen_governance.php',
    'table' => 'fina_acc_reopen_governance',
    'anchor' => '<table id="emsList_acc_reopen_governance"',
    'rows' => "ems_w14_guide_rows('fina_acc_reopen_governance')",
    'grid_id' => 'emsList_acc_reopen_governance', 'empty' => 'لا سطر مسجل بعد في حوكمة إعادة فتح الفترات',
    'create' => true,
    'grain' => 'حوكمة إعادة فتح الفترات',
    'map' => array(
        'رقم الطلب' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة المستهدفة' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'مبرر إعادة الفتح' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدات المفتوحة' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'النطاق الزمني للفتح' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع اعتماد AAM' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'القيود الموسومة بعد الفتح' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'إعادة الإقفال' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الطلب' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-23', 'route' => 'Finance/periods_fin.php',
    'table' => 'fina_periods_fin',
    'anchor' => '<table id="emsList_fina_periods_fin"',
    'rows' => "ems_w14_guide_rows('fina_periods_fin')",
    'grid_id' => 'emsList_fina_periods_fin', 'empty' => 'لا سطر مسجل بعد في التقويم المحاسبي للفترات',
    'create' => true,
    'grain' => 'التقويم المحاسبي للفترات',
    'map' => array(
        'معرف الفترة' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'الشهر' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'قيود الفترة' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'قيود معلقة' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'مطابقة المخازن' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'مطابقة الخزينة' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'الإقفالات التشغيلية الواردة' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'فروق معالجة' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الإقفال' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'قرار إعادة الفتح' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الفترة' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-21', 'route' => 'Finance/acc_trial_balance.php',
    'table' => 'fina_acc_trial_balance',
    'anchor' => '<table id="emsList_acc_trial_balance"',
    'rows' => "ems_w14_guide_rows('fina_acc_trial_balance')",
    'grid_id' => 'emsList_acc_trial_balance', 'empty' => 'لا سطر مسجل بعد في ميزان المراجعة',
    'create' => true,
    'grain' => 'ميزان المراجعة',
    'map' => array(
        'معرف السطر' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'كود الحساب' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'اسم الحساب' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد افتتاحي مدين' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد افتتاحي دائن' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'حركة مدينة' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'حركة دائنة' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'ختامي مدين' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'ختامي دائن' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'التوازن الكلي' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-13', 'route' => 'FinRequests/effect_map.php',
    'table' => 'fina_effect_map',
    'anchor' => '<table id="emsList_fina_effect_map"',
    'rows' => "ems_w14_guide_rows('fina_effect_map')",
    'grid_id' => 'emsList_fina_effect_map', 'empty' => 'لا سطر مسجل بعد في تتبّع الأثر من الواقعة إلى القيد',
    'create' => true,
    'grain' => 'تتبّع الأثر من الواقعة إلى القيد',
    'map' => array(
        'معرف السطر' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'الواقعة الأصلية' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المصدر' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'الحدث الناشر' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'قاعدة الأثر بمصفوفة التكامل' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'القيد المتولد' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ القيد' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الأثر' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'زمن التأخر بين الواقعة والقيد' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الاتساق' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المعالجة' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-15', 'route' => 'Finance/acc_credit_control.php',
    'table' => 'fina_acc_credit_control',
    'anchor' => '<table id="emsList_acc_credit_control"',
    'rows' => "ems_w14_guide_rows('fina_acc_credit_control')",
    'grid_id' => 'emsList_acc_credit_control', 'empty' => 'لا سطر مسجل بعد في الرقابة الائتمانية وحدود العملاء',
    'create' => true,
    'grain' => 'الرقابة الائتمانية وحدود العملاء',
    'map' => array(
        'معرف السطر' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'الحد الائتماني المعتمد' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع اعتماد الحد' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'المستهلك' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'المتاح' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'تجاوز؟' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'إجراء التجاوز' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الحد' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-18', 'route' => 'Finance/tax_fin.php',
    'table' => 'fina_tax_fin',
    'anchor' => '<table id="emsList_fina_tax_fin"',
    'rows' => "ems_w14_guide_rows('fina_tax_fin')",
    'grid_id' => 'emsList_fina_tax_fin', 'empty' => 'لا سطر مسجل بعد في الضرائب والقيمة المضافة',
    'create' => true,
    'grain' => 'الضرائب والقيمة المضافة',
    'map' => array(
        'معرف الإقرار' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الضريبة' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'ضريبة المخرجات' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'ضريبة المدخلات' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'الصافي المستحق' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاستحقاق النظامي' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع التقديم بالحوكمة' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع السداد بالخزينة' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإقرار' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-22', 'route' => 'Finance/acc_closing_checklist.php',
    'table' => 'fina_closing_checklist',
    'anchor' => '<table id="emsList_acc_closing_checklist"',
    'rows' => "ems_w14_guide_rows('fina_closing_checklist')",
    'grid_id' => 'emsList_acc_closing_checklist', 'empty' => 'لا سطر مسجل بعد في قائمة إقفال الفترة',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في قائمة إقفال الفترة',
    'map' => array(
        'معرف البند' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'بند الفحص' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'المسؤول' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الإنجاز' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'النتيجة' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'استثناء موثق' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الإنجاز' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البند' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-03', 'route' => 'Finance/acc_cost_centers.php',
    'table' => 'fina_acc_cost_centers',
    'anchor' => '<table id="emsList_acc_cost_centers"',
    'rows' => "ems_w14_guide_rows('fina_acc_cost_centers')",
    'grid_id' => 'emsList_acc_cost_centers', 'empty' => 'لا سطر مسجل بعد في مراكز التكلفة',
    'create' => true,
    'grain' => 'مراكز التكلفة',
    'map' => array(
        'كود المركز' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المركز' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'المركز الأب' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المركز' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع المربوط' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'مسؤول المركز' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المركز' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-20', 'route' => 'Finance/acc_reconciliations.php',
    'table' => 'fina_reconciliations',
    'anchor' => '<table id="emsList_acc_reconciliations"',
    'rows' => "ems_w14_guide_rows('fina_reconciliations')",
    'grid_id' => 'emsList_acc_reconciliations', 'empty' => 'لا سطر مسجل بعد في مطابقات الحسابات',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في مطابقات الحسابات',
    'map' => array(
        'معرف المطابقة' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'كود الحساب الرقابي' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد الأستاذ' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'رصيد المصدر التفصيلي' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'المصدر' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'الفرق' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'بنود الفروق' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الفرق' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'معالجة الفرق' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'الفرق المتبقي' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المطابقة' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-14', 'route' => 'Contracts/collections.php',
    'table' => 'fina_collections',
    'anchor' => '<table id="emsList_fina_collections"',
    'rows' => "ems_w14_guide_rows('fina_collections')",
    'grid_id' => 'emsList_fina_collections', 'empty' => 'لا سطر مسجل بعد في ذمم العملاء وأعمارها',
    'create' => true,
    'grain' => 'ذمم العملاء وأعمارها',
    'map' => array(
        'معرف السطر' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المشروع' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الذمة' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
        'شريحة العمر' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الشريحة' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التحصيل' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
        'إتاحة النقد للاستخدام' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحصيل' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'إجراء المطالبة' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-01', 'route' => 'Finance/cfo_daily_board_fin.php',
    'table' => 'fina_dashboard_kpi',
    'anchor' => '<table id="emsList_exec_board_kpi"',
    'rows' => "ems_w14_guide_rows('fina_dashboard_kpi')",
    'grid_id' => 'emsList_exec_board_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة المالية',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة المالية',
    'map' => array(
        'معرف المؤشر' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر KPI Catalog' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-09', 'route' => 'Finance/dues_fin.php',
    'table' => 'fina_dues',
    'anchor' => '<table id="emsList_tre_payment_queue"',
    'rows' => "ems_w14_guide_rows('fina_dues')",
    'grid_id' => 'emsList_tre_payment_queue', 'empty' => 'لا سطر مسجل بعد في فواتير الموردين والمستحقات',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في فواتير الموردين والمستحقات',
    'map' => array(
        'معرف الاستحقاق' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
        'رقم فاتورة المورد' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر الاستحقاق' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'فحص البوابة' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الاستحقاق' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'الضريبة' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاستحقاق' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'المسدد' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي' => '+g171:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الاستحقاق' => '+g172:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g173:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g174:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g175:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g176:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g177:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g178:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-11', 'route' => 'Finance/journal_form_fin.php',
    'table' => 'fina_journal_form_fin',
    'anchor' => '<table id="emsList_fina_journal_form_fin"',
    'rows' => "ems_w14_guide_rows('fina_journal_form_fin')",
    'grid_id' => 'emsList_fina_journal_form_fin', 'empty' => 'لا سطر مسجل بعد في القيود اليومية',
    'create' => true,
    'grain' => 'القيود اليومية',
    'map' => array(
        'رقم القيد' => '+g179:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ القيد' => '+g180:VARCHAR(190) NULL DEFAULT NULL',
        'المصدر' => '+g181:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الحدث' => '+g182:VARCHAR(190) NULL DEFAULT NULL',
        'الوصف' => '+g183:VARCHAR(190) NULL DEFAULT NULL',
        'عدد أسطر القيد تفصيلها م06-2' => '+g184:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي المدين' => '+g185:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الدائن' => '+g186:VARCHAR(190) NULL DEFAULT NULL',
        'التوازن' => '+g187:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g188:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الصرف' => '+g189:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g190:VARCHAR(190) NULL DEFAULT NULL',
        'قيد عكسي ل' => '+g191:VARCHAR(190) NULL DEFAULT NULL',
        'حالة القيد' => '+g192:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g193:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g194:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g195:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g196:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g197:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g198:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g199:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-06', 'route' => 'Finance/currencies_fin.php',
    'table' => 'fina_currencies',
    'anchor' => '<table id="emsList_sup_contract_line"',
    'rows' => "ems_w14_guide_rows('fina_currencies')",
    'grid_id' => 'emsList_sup_contract_line', 'empty' => 'لا سطر مسجل بعد في أسعار الصرف',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في أسعار الصرف',
    'map' => array(
        'معرف السطر' => '+g200:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g201:VARCHAR(190) NULL DEFAULT NULL',
        'مقابل' => '+g202:VARCHAR(190) NULL DEFAULT NULL',
        'نوع السعر' => '+g203:VARCHAR(190) NULL DEFAULT NULL',
        'السعر' => '+g204:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ السريان' => '+g205:VARCHAR(190) NULL DEFAULT NULL',
        'المصدر/التوثيق' => '+g206:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g207:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g208:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g209:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g210:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g211:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'ACC-24', 'route' => 'Finance/financial_statements_fin.php',
    'table' => 'fina_financial_statements_fin',
    'anchor' => '<table id="emsList_fina_financial_statements_fin"',
    'rows' => "ems_w14_guide_rows('fina_financial_statements_fin')",
    'grid_id' => 'emsList_fina_financial_statements_fin', 'empty' => 'لا سطر مسجل بعد في القوائم المالية',
    'create' => true,
    'grain' => 'القوائم المالية',
    'map' => array(
        'معرف السطر' => '+g212:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g213:VARCHAR(190) NULL DEFAULT NULL',
        'القائمة' => '+g214:VARCHAR(190) NULL DEFAULT NULL',
        'البند' => '+g215:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g216:VARCHAR(190) NULL DEFAULT NULL',
        'فترة المقارنة' => '+g217:VARCHAR(190) NULL DEFAULT NULL',
        'التغير' => '+g218:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة إفصاح' => '+g219:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
