<?php
/**
 * fields_dep09.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-09',
'screens' => array(

array(
    'req' => 'RSK-03', 'route' => 'Risk/risk_register.php',
    'table' => 'rsk_risk_register',
    'anchor' => '<table id="emsList_rsk_risk_register"',
    'rows' => "ems_w14_guide_rows('rsk_risk_register')",
    'grid_id' => 'emsList_rsk_risk_register', 'empty' => 'لا سطر مسجل بعد في سجل المخاطر المؤسسي',
    'create' => true,
    'grain' => 'سجل المخاطر المؤسسي',
    'map' => array(
        'Risk_ID' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'عنوان الخطر' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'عقدة التصنيف' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'العائلة' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر التحديد' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح الحدث/السجل الأصلي' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'الكيان المتأثر' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الكيان' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة التشغيلية المتأثرة' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'وصف الخطر' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_Owner' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التحديد' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تقييم' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'المستوى المتبقي الحالي' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الخطر' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'RSK-04', 'route' => 'Risk/risk_events.php',
    'table' => 'rsk_risk_events',
    'anchor' => '<table id="emsList_risk_events"',
    'rows' => "ems_w14_guide_rows('rsk_risk_events')",
    'grid_id' => 'emsList_risk_events', 'empty' => 'لا سطر مسجل بعد في أحداث المخاطر والخسائر',
    'create' => true,
    'grain' => 'أحداث المخاطر والخسائر',
    'map' => array(
        'معرف الحدث' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_ID' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر الحدث' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح السجل الأصلي' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'قراءة الحدث' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'السبب من مصدره' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة المتسببة' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'المدة/الحجم' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'الأثر الإنتاجي' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'الأثر المالي' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'الأثر التعاقدي' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'تكرار السبب' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'قاعدة الخطر المتحققة' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الحدث' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'RSK-07', 'route' => 'Risk/risk_treatments.php',
    'table' => 'rsk_risk_treatments',
    'anchor' => '<table id="emsList_rsk_risk_treatments"',
    'rows' => "ems_w14_guide_rows('rsk_risk_treatments')",
    'grid_id' => 'emsList_rsk_risk_treatments', 'empty' => 'لا سطر مسجل بعد في خطط معالجة المخاطر',
    'create' => true,
    'grain' => 'خطط معالجة المخاطر',
    'map' => array(
        'معرف الإجراء' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_ID' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'مسار المعالجة' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'وصف الإجراء' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'المالك' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة المنفذة' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'Due_Date' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'المستوى المستهدف بعد الإجراء' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'أيام التأخير' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'دليل الإنجاز' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'إعادة التقييم بعده' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإجراء' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'RSK-10', 'route' => 'Risk/risk_escalations.php',
    'table' => 'rsk_risk_escalations',
    'anchor' => '<table id="emsList_risk_escalations"',
    'rows' => "ems_w14_guide_rows('rsk_risk_escalations')",
    'grid_id' => 'emsList_risk_escalations', 'empty' => 'لا سطر مسجل بعد في تصعيدات المخاطر',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في تصعيدات المخاطر',
    'map' => array(
        'معرف التصعيد' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_ID' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'مسبب التصعيد' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'المستوى' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'المخطر' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'وقت التصعيد' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'الاستجابة/القرار' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع قيادة ر11' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التصعيد' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'RSK-12', 'route' => 'Risk/risk_closure.php',
    'table' => 'rsk_risk_closure',
    'anchor' => '<table id="emsList_risk_closure"',
    'rows' => "ems_w14_guide_rows('rsk_risk_closure')",
    'grid_id' => 'emsList_risk_closure', 'empty' => 'لا سطر مسجل بعد في سجل الإغلاق والأدلة',
    'create' => true,
    'grain' => 'سجل الإغلاق والأدلة',
    'map' => array(
        'معرف الإغلاق' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'Risk_ID' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'أساس الإغلاق' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع إعادة التقييم الختامية' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'المستوى المتبقي عند الإغلاق' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع القبول الرسمي' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'دليل الإغلاق' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإغلاق' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'إعادة فتح؟' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإغلاق' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'RSK-13', 'route' => 'Risk/risk_reports.php',
    'table' => 'rsk_risk_reports',
    'anchor' => '<table id="emsList_rsk_risk_reports"',
    'rows' => "ems_w14_guide_rows('rsk_risk_reports')",
    'grid_id' => 'emsList_rsk_risk_reports', 'empty' => 'لا سطر مسجل بعد في تقارير المخاطر الدورية',
    'create' => true,
    'grain' => 'تقارير المخاطر الدورية',
    'map' => array(
        'معرف السطر' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'الدورية' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'العائلة' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'البند' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'الاتجاه' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'يستلزم قرارا؟' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الخطر' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'RSK-02', 'route' => 'Risk/risk_taxonomy.php',
    'table' => 'rsk_risk_taxonomy',
    'anchor' => '<table id="emsList_risk_taxonomy"',
    'rows' => "ems_w14_guide_rows('rsk_risk_taxonomy')",
    'grid_id' => 'emsList_risk_taxonomy', 'empty' => 'لا سطر مسجل بعد في تصنيف المخاطر',
    'create' => true,
    'grain' => 'تصنيف المخاطر',
    'map' => array(
        'كود العقدة' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'العائلة' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'الفئة' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الخطر' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'أمثلة نموذجية' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر الحدث الأصلي' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'مقياس الأثر المعتمد' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العقدة' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
