<?php
/**
 * fields_dep07.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-07',
'screens' => array(

array(
    'req' => 'HR-17', 'route' => 'Employees/hr_disciplinary.php',
    'table' => 'hr_disciplinary',
    'anchor' => '<table id="emsList_hr_disciplinary"',
    'rows' => "ems_w14_guide_rows('hr_disciplinary')",
    'grid_id' => 'emsList_hr_disciplinary', 'empty' => 'لا سطر مسجل بعد في القضايا التأديبية والتحقيق',
    'create' => true,
    'grain' => 'القضايا التأديبية والتحقيق',
    'map' => array(
        'رقم القضية' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر الواقعة' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الإحالة' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'وصف الواقعة' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الواقعة' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'المحقق المكلف' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'محضر التحقيق' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'أقوال الموظف' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'لجنة القرار' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'القرار' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع اللائحي' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الجزاء المالي' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'Deduction_Reference الناتج' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'اعتراض الموظف' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'حالة القضية' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-04', 'route' => 'Workforce/recruitment_pipeline.php',
    'table' => 'hr_recruitment_pipeline',
    'anchor' => '<table id="emsList_hr_recruitment_pipeline"',
    'rows' => "ems_w14_guide_rows('hr_recruitment_pipeline')",
    'grid_id' => 'emsList_hr_recruitment_pipeline', 'empty' => 'لا سطر مسجل بعد في التوظيف من الشاغر إلى المباشرة',
    'create' => true,
    'grain' => 'التوظيف من الشاغر إلى المباشرة',
    'map' => array(
        'رقم الشاغر' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الفتح' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة الطالبة' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'المسمى الوظيفي' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الشاغر' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'عدد المطلوبين' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'اشتراطات الشاغر' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'المرحلة' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'المرشحون' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'المرشح المقبول' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'نتيجة الاختبار العملي' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'العرض المقدم' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ المباشرة' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الشاغر' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-24', 'route' => 'Workforce/hr_workforce_report.php',
    'table' => 'hr_workforce_report',
    'anchor' => '<table id="emsList_hr_workforce_report"',
    'rows' => "ems_w14_guide_rows('hr_workforce_report')",
    'grid_id' => 'emsList_hr_workforce_report', 'empty' => 'لا سطر مسجل بعد في تقرير القوى العاملة',
    'create' => true,
    'grain' => 'تقرير القوى العاملة',
    'map' => array(
        'معرف السطر' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الموظفين' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'منهم مشروعيون' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'مباشرون جدد' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'منتهية خدمتهم' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'معدل الدوران' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة الغياب' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'ساعات إضافية' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'كلفة العمالة' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-12', 'route' => 'Employees/hr_job_movements.php',
    'table' => 'hr_job_movements',
    'anchor' => '<table id="emsList_hr_job_movements"',
    'rows' => "ems_w14_guide_rows('hr_job_movements')",
    'grid_id' => 'emsList_hr_job_movements', 'empty' => 'لا سطر مسجل بعد في الحركات الوظيفية',
    'create' => true,
    'grain' => 'الحركات الوظيفية',
    'map' => array(
        'رقم الحركة' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الحركة' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'من منصب/وحدة' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'إلى منصب/وحدة' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'الموجب/المرجع' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'أثر الأجر' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ النفاذ' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الحركة' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-22', 'route' => 'Workforce/payroll_lines.php',
    'table' => 'hr_payroll_lines',
    'anchor' => '<table id="emsList_payroll_lines"',
    'rows' => "ems_w14_guide_rows('hr_payroll_lines')",
    'grid_id' => 'emsList_payroll_lines', 'empty' => 'لا سطر مسجل بعد في أسطر مسيّر الرواتب',
    'create' => true,
    'grain' => 'أسطر مسيّر الرواتب',
    'map' => array(
        'معرف السطر' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'معرف المسير' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'الأساسي' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'البدلات' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'حافز الإنتاج من أساس القوى' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'الخصومات بمرجع ب08' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'التأمينات بمرجع ب08-2' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'أقساط السلف بمرجع ب08-3' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'الصافي' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-21', 'route' => 'Workforce/payroll_runs.php',
    'table' => 'hr_payroll_runs',
    'anchor' => '<table id="emsList_hr_payroll_runs"',
    'rows' => "ems_w14_guide_rows('hr_payroll_runs')",
    'grid_id' => 'emsList_hr_payroll_runs', 'empty' => 'لا سطر مسجل بعد في مسيّر الرواتب',
    'create' => true,
    'grain' => 'مسيّر الرواتب',
    'map' => array(
        'معرف المسير' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'الشهر' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'نطاق المسير' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الموظفين' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الأساسي' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي البدلات' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'حوافز الإنتاج' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'أساس القوى للمشغلين' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الخصومات' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'صافي المسير' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'الإحالة للمالية' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'الإحالة للخزينة' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المسير' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-16', 'route' => 'Employees/hr_performance.php',
    'table' => 'hr_performance',
    'anchor' => '<table id="emsList_hr_performance"',
    'rows' => "ems_w14_guide_rows('hr_performance')",
    'grid_id' => 'emsList_hr_performance', 'empty' => 'لا سطر مسجل بعد في تقييم الأداء الوظيفي',
    'create' => true,
    'grain' => 'تقييم الأداء الوظيفي',
    'map' => array(
        'معرف التقييم' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'دورة التقييم' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'المقيم' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'مدخل أداء القوى و13' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'الدرجة' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'نقاط القوة' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'فرص التحسين' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'خطة التطوير' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'اعتماد المدير' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'إقرار الموظف' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التقييم' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-11', 'route' => 'Workforce/project_contracts.php',
    'table' => 'hr_project_contracts',
    'anchor' => '<table id="emsList_hr_project_contracts"',
    'rows' => "ems_w14_guide_rows('hr_project_contracts')",
    'grid_id' => 'emsList_hr_project_contracts', 'empty' => 'لا سطر مسجل بعد في عقود المشاريع المؤقتة',
    'create' => true,
    'grain' => 'عقود المشاريع المؤقتة',
    'map' => array(
        'معرف السطر' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'معرف العقد' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'Project_ID المشروع الرابط الأساسي' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'احتياج التوظيف المرجعي' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'عقد المورد محفزا لا رابطا' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'محفز الانتهاء المتفق' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'محفز الانتهاء الواقع' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الوقوع' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'فترة الإخطار' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع التصفية' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التصفية' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-15', 'route' => 'Employees/hr_training.php',
    'table' => 'hr_training',
    'anchor' => '<table id="emsList_hr_training"',
    'rows' => "ems_w14_guide_rows('hr_training')",
    'grid_id' => 'emsList_hr_training', 'empty' => 'لا سطر مسجل بعد في التدريب والكفاءة',
    'create' => true,
    'grain' => 'التدريب والكفاءة',
    'map' => array(
        'معرف السجل' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'البرنامج' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'نوع التدريب' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإتمام' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'النتيجة' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
        'صلاحية الشهادة' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'إلزامي؟' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السجل' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-19', 'route' => 'Employees/hr_benefits.php',
    'table' => 'hr_benefits',
    'anchor' => '<table id="emsList_hr_benefits"',
    'rows' => "ems_w14_guide_rows('hr_benefits')",
    'grid_id' => 'emsList_hr_benefits', 'empty' => 'لا سطر مسجل بعد في المزايا والتأمينات',
    'create' => true,
    'grain' => 'المزايا والتأمينات',
    'map' => array(
        'معرف السطر' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الميزة' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة/الوثيقة' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'حصة الشركة' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'حصة الموظف' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'من تاريخ' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'إلى تاريخ' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المسير' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-07', 'route' => 'Employees/employees.php',
    'table' => 'hr_employees',
    'anchor' => '<table id="emsList_hr_employees"',
    'rows' => "ems_w14_guide_rows('hr_employees')",
    'grid_id' => 'emsList_hr_employees', 'empty' => 'لا سطر مسجل بعد في سجل الموظفين',
    'create' => true,
    'grain' => 'سجل الموظفين',
    'map' => array(
        'رقم الموظف' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم الرباعي' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'الرقم الوطني' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الميلاد' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'النوع' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة الاجتماعية' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'المؤهل' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
        'المسمى الوظيفي' => '+g171:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة' => '+g172:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g173:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ المباشرة' => '+g174:VARCHAR(190) NULL DEFAULT NULL',
        'مشغل تشغيلي؟' => '+g175:VARCHAR(190) NULL DEFAULT NULL',
        'كود المشغل بالقوى' => '+g176:VARCHAR(190) NULL DEFAULT NULL',
        'بيانات التواصل' => '+g177:VARCHAR(190) NULL DEFAULT NULL',
        'شخص الطوارئ' => '+g178:VARCHAR(190) NULL DEFAULT NULL',
        'الحساب البنكي' => '+g179:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الخدمة' => '+g180:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g181:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g182:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g183:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g184:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g185:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g186:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g187:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-13', 'route' => 'Operations/attendance.php',
    'table' => 'hr_attendance',
    'anchor' => '<table id="emsList_hr_attendance"',
    'rows' => "ems_w14_guide_rows('hr_attendance')",
    'grid_id' => 'emsList_hr_attendance', 'empty' => 'لا سطر مسجل بعد في الحضور والانصراف',
    'create' => true,
    'grain' => 'الحضور والانصراف',
    'map' => array(
        'معرف السجل' => '+g188:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g189:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => '+g190:VARCHAR(190) NULL DEFAULT NULL',
        'رمز الحالة' => '+g191:VARCHAR(190) NULL DEFAULT NULL',
        'ساعات إضافية' => '+g192:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المأمورية' => '+g193:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الإجازة' => '+g194:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر التسجيل' => '+g195:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة' => '+g196:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السجل' => '+g197:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g198:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g199:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g200:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g201:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-05', 'route' => 'Workforce/rec_applications.php',
    'table' => 'hr_rec_applications',
    'anchor' => '<table id="emsList_rec_applications"',
    'rows' => "ems_w14_guide_rows('hr_rec_applications')",
    'grid_id' => 'emsList_rec_applications', 'empty' => 'لا سطر مسجل بعد في طلبات الترشح',
    'create' => true,
    'grain' => 'طلبات الترشح',
    'map' => array(
        'معرف الترشح' => '+g202:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الشاغر' => '+g203:VARCHAR(190) NULL DEFAULT NULL',
        'المرشح' => '+g204:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر الترشح' => '+g205:VARCHAR(190) NULL DEFAULT NULL',
        'المؤهل' => '+g206:VARCHAR(190) NULL DEFAULT NULL',
        'الخبرة' => '+g207:VARCHAR(190) NULL DEFAULT NULL',
        'نتيجة الفرز الأولي' => '+g208:VARCHAR(190) NULL DEFAULT NULL',
        'المرحلة الحالية' => '+g209:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الترشح' => '+g210:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g211:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g212:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g213:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g214:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-09', 'route' => 'Employees/hr_onboarding.php',
    'table' => 'hr_onboarding',
    'anchor' => '<table id="emsList_hr_onboarding"',
    'rows' => "ems_w14_guide_rows('hr_onboarding')",
    'grid_id' => 'emsList_hr_onboarding', 'empty' => 'لا سطر مسجل بعد في التهيئة والمباشرة',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في التهيئة والمباشرة',
    'map' => array(
        'معرف التهيئة' => '+g215:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g216:VARCHAR(190) NULL DEFAULT NULL',
        'بند التهيئة' => '+g217:VARCHAR(190) NULL DEFAULT NULL',
        'المسؤول' => '+g218:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الإنجاز' => '+g219:VARCHAR(190) NULL DEFAULT NULL',
        'النتيجة' => '+g220:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنجاز' => '+g221:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البند' => '+g222:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g223:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g224:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g225:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g226:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-01', 'route' => 'Employees/hr_board.php',
    'table' => 'hr_dashboard_kpi',
    'anchor' => '<table id="emsList_hr_board"',
    'rows' => "ems_w14_guide_rows('hr_dashboard_kpi')",
    'grid_id' => 'emsList_hr_board', 'empty' => 'لا سطر مسجل بعد في لوحة الموارد البشرية',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة الموارد البشرية',
    'map' => array(
        'معرف المؤشر' => '+g227:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر KPI Catalog' => '+g228:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g229:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة' => '+g230:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g231:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g232:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-06', 'route' => 'Workforce/rec_stages.php',
    'table' => 'hr_rec_stages',
    'anchor' => '<table id="emsList_rec_stages"',
    'rows' => "ems_w14_guide_rows('hr_rec_stages')",
    'grid_id' => 'emsList_rec_stages', 'empty' => 'لا سطر مسجل بعد في مراحل التوظيف',
    'create' => true,
    'grain' => 'مراحل التوظيف',
    'map' => array(
        'معرف السطر' => '+g233:VARCHAR(190) NULL DEFAULT NULL',
        'معرف الترشح' => '+g234:VARCHAR(190) NULL DEFAULT NULL',
        'المرحلة' => '+g235:VARCHAR(190) NULL DEFAULT NULL',
        'المقيم' => '+g236:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => '+g237:VARCHAR(190) NULL DEFAULT NULL',
        'النتيجة' => '+g238:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة التقييم' => '+g239:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g240:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g241:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g242:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g243:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g244:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-08', 'route' => 'Employees/hr_employee_documents.php',
    'table' => 'hr_employee_documents',
    'anchor' => '<table id="emsList_hr_employee_documents"',
    'rows' => "ems_w14_guide_rows('hr_employee_documents')",
    'grid_id' => 'emsList_hr_employee_documents', 'empty' => 'لا سطر مسجل بعد في مستندات الموظف',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في مستندات الموظف',
    'map' => array(
        'معرف المستند' => '+g245:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g246:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المستند' => '+g247:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المستند' => '+g248:VARCHAR(190) NULL DEFAULT NULL',
        'جهة الإصدار' => '+g249:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإصدار' => '+g250:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الانتهاء' => '+g251:VARCHAR(190) NULL DEFAULT NULL',
        'إلزامي؟' => '+g252:VARCHAR(190) NULL DEFAULT NULL',
        'المرفق' => '+g253:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المستند' => '+g254:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g255:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g256:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g257:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g258:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-10', 'route' => 'Employees/employee_contracts.php',
    'table' => 'hr_employee_contracts',
    'anchor' => '<table id="emsList_scr_project_contracts"',
    'rows' => "ems_w14_guide_rows('hr_employee_contracts')",
    'grid_id' => 'emsList_scr_project_contracts', 'empty' => 'لا سطر مسجل بعد في عقود الموظفين',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في عقود الموظفين',
    'map' => array(
        'معرف العقد' => '+g259:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g260:VARCHAR(190) NULL DEFAULT NULL',
        'فئة العقد' => '+g261:VARCHAR(190) NULL DEFAULT NULL',
        'نوع العقد' => '+g262:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج الأجر' => '+g263:VARCHAR(190) NULL DEFAULT NULL',
        'الأجر الأساسي' => '+g264:VARCHAR(190) NULL DEFAULT NULL',
        'البدلات' => '+g265:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g266:VARCHAR(190) NULL DEFAULT NULL',
        'من تاريخ' => '+g267:VARCHAR(190) NULL DEFAULT NULL',
        'إلى تاريخ' => '+g268:VARCHAR(190) NULL DEFAULT NULL',
        'فترة التجربة' => '+g269:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المشروع' => '+g270:VARCHAR(190) NULL DEFAULT NULL',
        'مرفق العقد الموقع' => '+g271:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العقد' => '+g272:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g273:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g274:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g275:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g276:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g277:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g278:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g279:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'HR-14', 'route' => 'Workforce/worker_leave_absence.php',
    'table' => 'hr_worker_leave_absence',
    'anchor' => '<table id="emsList_hr_worker_leave_absence"',
    'rows' => "ems_w14_guide_rows('hr_worker_leave_absence')",
    'grid_id' => 'emsList_hr_worker_leave_absence', 'empty' => 'لا سطر مسجل بعد في الإجازات والغياب',
    'create' => true,
    'grain' => 'الإجازات والغياب',
    'map' => array(
        'رقم الطلب' => '+g280:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الموظف' => '+g281:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الإجازة' => '+g282:VARCHAR(190) NULL DEFAULT NULL',
        'من تاريخ' => '+g283:VARCHAR(190) NULL DEFAULT NULL',
        'إلى تاريخ' => '+g284:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الأيام' => '+g285:VARCHAR(190) NULL DEFAULT NULL',
        'الرصيد قبل' => '+g286:VARCHAR(190) NULL DEFAULT NULL',
        'الرصيد بعد' => '+g287:VARCHAR(190) NULL DEFAULT NULL',
        'البديل المكلف' => '+g288:VARCHAR(190) NULL DEFAULT NULL',
        'مرفق مساند' => '+g289:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع دورة التناوب' => '+g290:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الطلب' => '+g291:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g292:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g293:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g294:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g295:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g296:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g297:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g298:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
