<?php
/**
 * fields_dep_01.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-01',
'screens' => array(

array(
    'req' => 'SAL-11', 'route' => 'Contracts/contracts.php',
    'table' => 'sal_contracts',
    'anchor' => '<table id="emsList_sal_contracts"',
    'rows' => "ems_w14_guide_rows('sal_contracts')",
    'grid_id' => 'emsList_sal_contracts', 'empty' => 'لا سطر مسجل بعد في سجل عقود المشاريع',
    'create' => true,
    'grain' => 'سجل عقود المشاريع',
    'map' => array(
        'كود العقد' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'اسم العميل (بحث)' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المشروع' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العقد بالمنظومة' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل الشركة' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'توقيع الوثيقة' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'البداية التعاقدية' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'النهاية التعاقدية' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'البداية التنفيذية' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'النهاية التنفيذية' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العقد' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'عدد دورات الالتزام (التجديدات)' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدات المتعاقدة الحالية' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'السعة الشهرية الحالية' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'حالة خط الأساس' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'الحجية/مصدر التوثيق' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'أساس التسعير (كما ورد)' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الوحدة (كما ورد)' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'الضريبة' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'الدفع والفوترة' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'الوديعة/الدفعة المقدمة' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'الوقود' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'السكن والإعاشة' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'الصيانة وقطع الغيار' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'التأمين' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'المشغلون' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'النقل والتعبئة' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'الحد الأدنى للساعات' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'ضمان التشغيل' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'جدول عمل الموقع' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'خصم ساعات المخالفة' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'التوقف غير المدفوع' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'الإنهاء' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'التجديد' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'القانون الحاكم' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'المسؤول التجاري' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الخدمة المقدمة' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'أساس التعاقد (الوحدة)' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'مكان إبرام العقد (مؤكد)' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'المكان المرجح تاريخيا' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'أساس المكان المرجح' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى حجية المكان المرجح' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة كما وردت بالمصدر' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'أساس تعديل الحالة' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج التسعير' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة الفوترة' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'الحد الأدنى (كمية)' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'دورية الحد الأدنى' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المضمونة' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'عتبة الفوترة' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'متحمل العجز' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'قاعدة العجز' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'بنية السعر' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'عدد النسخ/المكونات السعرية' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع تسعيري' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-06', 'route' => 'Opportunities/client_need_rfq.php',
    'table' => 'sal_client_need_rfq',
    'anchor' => '<table id="emsList_sal_client_need_rfq"',
    'rows' => "ems_w14_guide_rows('sal_client_need_rfq')",
    'grid_id' => 'emsList_sal_client_need_rfq', 'empty' => 'لا سطر مسجل بعد في احتياج العميل وطلب العرض',
    'create' => true,
    'grain' => 'احتياج العميل وطلب العرض',
    'map' => array(
        'رقم الطلب' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'اسم العميل (بحث)' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المشروع' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الفرصة' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الطلب' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'نطاق الطلب' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'الخدمة المطلوبة' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل المطلوب' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية/الحجم المطلوب' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'أنواع الآليات المطلوبة' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الآليات' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'المدة (أشهر)' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'البداية المتوقعة' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'النهاية المتوقعة' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'أساس البداية المتوقعة' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'أساس النهاية المتوقعة' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'حالة بيانات التواريخ' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'المتطلبات التجارية الأساسية' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاستلام' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'موعد الرد بالعرض' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد الناتج' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح دورة الالتزام المصدر' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'أساس القيمة الرجعية' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-01', 'route' => 'Clients/clients.php',
    'table' => 'sal_clients',
    'anchor' => '<table id="emsList_sal_clients"',
    'rows' => "ems_w14_guide_rows('sal_clients')",
    'grid_id' => 'emsList_sal_clients', 'empty' => 'لا سطر مسجل بعد في سجل العملاء',
    'create' => true,
    'grain' => 'سجل العملاء',
    'map' => array(
        'رقم العميل' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم القانوني' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم المختصر' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'تصنيف العميل' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'أساس التصنيف' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العميل' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'القطاع' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'الدولة' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'المدينة/المنطقة' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'رقم التسجيل' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'الرقم الضريبي' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'مالك الحساب' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر التعرف' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'درجة الأولوية' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف الائتماني' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'حد الائتمان ($)' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'حد الائتمان (ج.س)' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'شروط الدفع الافتراضية' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ أول تعامل' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'عدد العقود' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'العقود الجارية' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'آخر نشاط تنفيذي' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'نماذج التعامل' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'أنواع الخدمات' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'العملات المتعامل بها' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'دورية الفوترة بالمصدر' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'عدد المشاريع' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى حجية بيانات العميل' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-08', 'route' => 'Clients/quotation_lines.php',
    'table' => 'sal_quotation_lines',
    'anchor' => '<table id="emsList_sal_quotation_lines"',
    'rows' => "ems_w14_guide_rows('sal_quotation_lines')",
    'grid_id' => 'emsList_sal_quotation_lines', 'empty' => 'لا سطر مسجل بعد في بنود العروض',
    'create' => true,
    'grain' => 'بنود العروض',
    'map' => array(
        'رقم البند' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العرض' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'نوع البند' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الخدمة' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المعدة/البند' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'عدد المعدات' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'أساس الوحدة الشهري' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'المدة (أشهر)' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية/المستهدف' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة القياس' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الوحدة' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'سريان النسخة السعرية' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'أساس السعر' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'الضريبة كما وردت' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'نص السعر كما ورد بالمصدر' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات تجارية' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح دورة الالتزام المصدر' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'أساس القيمة الرجعية' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-09', 'route' => 'Clients/quotation_negotiation.php',
    'table' => 'sal_quotation_negotiation',
    'anchor' => '<table id="emsList_sal_quotation_negotiation"',
    'rows' => "ems_w14_guide_rows('sal_quotation_negotiation')",
    'grid_id' => 'emsList_sal_quotation_negotiation', 'empty' => 'لا سطر مسجل بعد في التفاوض ومراجعات العرض',
    'create' => true,
    'grain' => 'التفاوض ومراجعات العرض',
    'map' => array(
        'رقم الواقعة' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'نوع السجل' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العرض' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'دورة الالتزام الجديدة' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'دورة الالتزام السابقة' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
        'نطاق المقارنة' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'نوع التغيير' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
        'قبل' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'بعد' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'الأثر التجاري' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'الوثيقة المرجعية' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'السبب/الدليل' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'الطرف الطالب' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح دورة الالتزام المصدر' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'أساس القيمة الرجعية' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-18', 'route' => 'Contracts/claims.php',
    'table' => 'sal_claims',
    'anchor' => '<table id="emsList_sal_claims"',
    'rows' => "ems_w14_guide_rows('sal_claims')",
    'grid_id' => 'emsList_sal_claims', 'empty' => 'لا سطر مسجل بعد في المطالبات والتسليم للمالية',
    'create' => true,
    'grain' => 'المطالبات والتسليم للمالية',
    'map' => array(
        'رقم المطالبة' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح دورة الالتزام' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'كود العقد' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'اسم العميل (بحث)' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة من' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'إلى' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المنجزة المرجعية' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'الاستحقاق المحسوب ($)' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
        'الاستحقاق المحسوب (ج.س)' => '+g171:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة المطالب بها ($)' => '+g172:VARCHAR(190) NULL DEFAULT NULL',
        'المطالب بها (ج.س)' => '+g173:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع القياس/المستخلص' => '+g174:VARCHAR(190) NULL DEFAULT NULL',
        'حالة اعتماد العميل' => '+g175:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التسليم للمالية' => '+g176:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الفاتورة' => '+g177:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المتابعة' => '+g178:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g179:VARCHAR(190) NULL DEFAULT NULL',
        'المفوتر للعميل ($)' => '+g180:VARCHAR(190) NULL DEFAULT NULL',
        'مستحق غير مطالب به ($)' => '+g181:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التحصيل' => '+g182:VARCHAR(190) NULL DEFAULT NULL',
        'أساس حالة التحصيل' => '+g183:VARCHAR(190) NULL DEFAULT NULL',
        'دليل القياس/التسوية بالمصدر' => '+g184:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+g185:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-07', 'route' => 'Clients/quotations.php',
    'table' => 'sal_quotations',
    'anchor' => '<table id="emsList_sal_quotations"',
    'rows' => "ems_w14_guide_rows('sal_quotations')",
    'grid_id' => 'emsList_sal_quotations', 'empty' => 'لا سطر مسجل بعد في سجل العروض',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في سجل العروض',
    'map' => array(
        'رقم العرض الداخلي' => '+g186:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الفرصة' => '+g187:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الطلب' => '+g188:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g189:VARCHAR(190) NULL DEFAULT NULL',
        'اسم العميل (بحث)' => '+g190:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المشروع' => '+g191:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العرض الرسمي' => '+g192:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإصدار' => '+g193:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإرسال' => '+g194:VARCHAR(190) NULL DEFAULT NULL',
        'أساس التاريخ' => '+g195:VARCHAR(190) NULL DEFAULT NULL',
        'النسخة' => '+g196:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+g197:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g198:VARCHAR(190) NULL DEFAULT NULL',
        'مدة السريان' => '+g199:VARCHAR(190) NULL DEFAULT NULL',
        'شروط الدفع/الفوترة' => '+g200:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العرض' => '+g201:VARCHAR(190) NULL DEFAULT NULL',
        'رد العميل' => '+g202:VARCHAR(190) NULL DEFAULT NULL',
        'حالة القرار' => '+g203:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ القرار' => '+g204:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة العرض ($)' => '+g205:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة العرض (ج.س)' => '+g206:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد الناتج' => '+g207:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g208:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح دورة الالتزام المصدر' => '+g209:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+g210:VARCHAR(190) NULL DEFAULT NULL',
        'أساس القيمة الرجعية' => '+g211:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-03', 'route' => 'Projects/projects.php',
    'table' => 'sal_projects',
    'anchor' => '<table id="emsList_sal_projects"',
    'rows' => "ems_w14_guide_rows('sal_projects')",
    'grid_id' => 'emsList_sal_projects', 'empty' => 'لا سطر مسجل بعد في سجل المشاريع',
    'create' => true,
    'grain' => 'سجل المشاريع',
    'map' => array(
        'رقم المشروع' => '+g212:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g213:VARCHAR(190) NULL DEFAULT NULL',
        'اسم العميل (بحث)' => '+g214:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المشروع' => '+g215:VARCHAR(190) NULL DEFAULT NULL',
        'الوصف' => '+g216:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع (نطاق تنفيذ)' => '+g217:VARCHAR(190) NULL DEFAULT NULL',
        'القطاع' => '+g218:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المشروع' => '+g219:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ البداية' => '+g220:VARCHAR(190) NULL DEFAULT NULL',
        'المسؤول التجاري' => '+g221:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة التقديرية ($)' => '+g222:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة التقديرية (ج.س)' => '+g223:VARCHAR(190) NULL DEFAULT NULL',
        'عدد العقود' => '+g224:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g225:VARCHAR(190) NULL DEFAULT NULL',
        'كود المشروع لدى العميل' => '+g226:VARCHAR(190) NULL DEFAULT NULL',
        'الإقليم/الولاية' => '+g227:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل مشروع العميل' => '+g228:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الخدمة' => '+g229:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+g230:VARCHAR(190) NULL DEFAULT NULL',
        'أساس التسمية والحدود' => '+g231:VARCHAR(190) NULL DEFAULT NULL',
        'قاعدة التجميع' => '+g232:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+g233:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-02', 'route' => 'Clients/client_contacts.php',
    'table' => 'sal_client_contacts',
    'anchor' => '<table id="emsList_sal_client_contacts"',
    'rows' => "ems_w14_guide_rows('sal_client_contacts')",
    'grid_id' => 'emsList_sal_client_contacts', 'empty' => 'لا سطر مسجل بعد في جهات اتصال العملاء',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في جهات اتصال العملاء',
    'map' => array(
        'رقم جهة الاتصال' => '+g234:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+g235:VARCHAR(190) NULL DEFAULT NULL',
        'اسم العميل (بحث)' => '+g236:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم' => '+g237:VARCHAR(190) NULL DEFAULT NULL',
        'المسمى الوظيفي' => '+g238:VARCHAR(190) NULL DEFAULT NULL',
        'الهاتف' => '+g239:VARCHAR(190) NULL DEFAULT NULL',
        'البريد' => '+g240:VARCHAR(190) NULL DEFAULT NULL',
        'دوره في القرار' => '+g241:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g242:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+g243:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g244:VARCHAR(190) NULL DEFAULT NULL',
        'أثر البحث في المصادر' => '+g245:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SAL-20', 'route' => 'Contracts/commercial_board.php',
    'table' => 'sal_commercial_board',
    'anchor' => '<table id="emsList_sal_commercial_board"',
    'rows' => "ems_w14_guide_rows('sal_commercial_board')",
    'grid_id' => 'emsList_sal_commercial_board', 'empty' => 'لا سطر مسجل بعد في لوحة المبيعات',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة المبيعات',
    'map' => array(
        'البيان' => '+g246:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g247:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة/العملة' => '+g248:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة' => '+g249:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر الرسم 1 نسبة التحقق التعاقدي حسب نموذج العمل' => '+g250:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
