<?php
/**
 * fields_dep16.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-16',
'screens' => array(

array(
    'req' => 'PRC-13', 'route' => 'Procurement/proc_po_amendments.php',
    'table' => 'prc_proc_po_amendments',
    'anchor' => '<table id="emsList_prc_proc_po_amendments"',
    'rows' => "ems_w14_guide_rows('prc_proc_po_amendments')",
    'grid_id' => 'emsList_prc_proc_po_amendments', 'empty' => 'لا سطر مسجل بعد في استثناءات الشراء وتعديلات الأوامر',
    'create' => true,
    'grain' => 'استثناءات الشراء وتعديلات الأوامر',
    'map' => array(
        'معرف السطر' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'النوع' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر/الطلب' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'المبرر' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'قاعدة AAM المفعلة' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'مسار الموافقة' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الاعتماد' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'الأثر المالي' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'بنود متأثرة' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-08', 'route' => 'Procurement/proc_offers.php',
    'table' => 'prc_proc_offers',
    'anchor' => '<table id="emsList_prc_proc_offers"',
    'rows' => "ems_w14_guide_rows('prc_proc_offers')",
    'grid_id' => 'emsList_prc_proc_offers', 'empty' => 'لا سطر مسجل بعد في عروض الموردين المستلمة',
    'create' => true,
    'grain' => 'عروض الموردين المستلمة',
    'map' => array(
        'معرف العرض' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'رقم طلب العروض' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاستلام' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة العرض' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'مدة التوريد' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'شروط الدفع المعروضة' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'صلاحية العرض' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'التقييم الفني' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات الفحص' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'الترتيب المالي' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العرض' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-10', 'route' => 'Procurement/proc_award_minutes.php',
    'table' => 'prc_proc_award_minutes',
    'anchor' => '<table id="emsList_prc_proc_award_minutes"',
    'rows' => "ems_w14_guide_rows('prc_proc_award_minutes')",
    'grid_id' => 'emsList_prc_proc_award_minutes', 'empty' => 'لا سطر مسجل بعد في محضر المقارنة والترسية',
    'create' => true,
    'grain' => 'محضر المقارنة والترسية',
    'map' => array(
        'رقم المحضر' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'رقم طلب العروض' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'العروض المقارنة' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'جدول المقارنة' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'العرض المرسى عليه' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الترسية' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'مبرر الاختيار' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'تفصيل المبرر' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'أعضاء اللجنة' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الترسية' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-16', 'route' => 'Procurement/proc_supplier_eval.php',
    'table' => 'prc_proc_supplier_eval',
    'anchor' => '<table id="emsList_prc_proc_supplier_eval"',
    'rows' => "ems_w14_guide_rows('prc_proc_supplier_eval')",
    'grid_id' => 'emsList_prc_proc_supplier_eval', 'empty' => 'لا سطر مسجل بعد في تقييم أداء التوريد',
    'create' => true,
    'grain' => 'تقييم أداء التوريد',
    'map' => array(
        'معرف السطر' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الأوامر' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'قيمتها' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'الالتزام بالمواعيد' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
        'متوسط التأخير' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة رفض الفحص' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'فروق المطابقة' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر المركب' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف الناتج' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-04', 'route' => 'Procurement/proc_packages.php',
    'table' => 'prc_proc_packages',
    'anchor' => '<table id="emsList_prc_proc_packages"',
    'rows' => "ems_w14_guide_rows('prc_proc_packages')",
    'grid_id' => 'emsList_prc_proc_packages', 'empty' => 'لا سطر مسجل بعد في تجميع الطلبات وخطة الشراء',
    'create' => true,
    'grain' => 'تجميع الطلبات وخطة الشراء',
    'map' => array(
        'معرف الحزمة' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'فترة التجميع' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'نطاق الحزمة' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'الطلبات المضمومة' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'عدد البنود' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'التقدير الإجمالي' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'مبرر التمرير المنفرد' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'قناة الشراء' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الحزمة' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-14', 'route' => 'Procurement/proc_delivery_track.php',
    'table' => 'prc_proc_delivery_track',
    'anchor' => '<table id="emsList_prc_proc_delivery_track"',
    'rows' => "ems_w14_guide_rows('prc_proc_delivery_track')",
    'grid_id' => 'emsList_prc_proc_delivery_track', 'empty' => 'لا سطر مسجل بعد في متابعة التوريد والاستلام',
    'create' => true,
    'grain' => 'متابعة التوريد والاستلام',
    'map' => array(
        'معرف السطر' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الحدث' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الحدث' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المشمولة' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'رقم سند الإدخال' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'نتيجة الفحص' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'أيام التأخير' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'إخطار المورد' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-11', 'route' => 'Procurement/orders_proc.php',
    'table' => 'prc_orders_proc',
    'anchor' => '<table id="emsList_prc_orders_proc"',
    'rows' => "ems_w14_guide_rows('prc_orders_proc')",
    'grid_id' => 'emsList_prc_orders_proc', 'empty' => 'لا سطر مسجل بعد في أوامر الشراء',
    'create' => true,
    'grain' => 'أوامر الشراء',
    'map' => array(
        'رقم الأمر' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الأمر' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المحضر' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'عقد إطاري مرجعي' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'عدد البنود تفصيلها ش07-2' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة الإجمالية' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الدفع' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الاستلام' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
        'مكان التسليم' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التوريد المتفق' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'غرامة التأخير' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الأمر' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-07', 'route' => 'Procurement/proc_rfq.php',
    'table' => 'prc_proc_rfq',
    'anchor' => '<table id="emsList_prc_proc_rfq"',
    'rows' => "ems_w14_guide_rows('prc_proc_rfq')",
    'grid_id' => 'emsList_prc_proc_rfq', 'empty' => 'لا سطر مسجل بعد في دعوات الموردين للعروض',
    'create' => true,
    'grain' => 'دعوات الموردين للعروض',
    'map' => array(
        'معرف الدعوة' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'معرف RFQ' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الدعوة' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
        'تأكيد الاستلام' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
        'الاستجابة' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العرض الوارد' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الدعوة' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-09', 'route' => 'Procurement/proc_offers.php',
    'table' => 'prc_offer_compare',
    'anchor' => '<table id="emsList_prc_offer_compare"',
    'rows' => "ems_w14_guide_rows('prc_offer_compare')",
    'grid_id' => 'emsList_prc_offer_compare', 'empty' => 'لا سطر مسجل بعد في عروض الموردين المستلمة',
    'create' => true,
    'grain' => 'عروض الموردين المستلمة',
    'map' => array(
        'معرف السطر' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'معرف العرض' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع بند الطلب' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'كود الصنف' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الوحدة المعروض' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'مدة التوريد للبند' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'بديل مقترح؟' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة فنية' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'ترتيب البند ماليا' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-02', 'route' => 'Procurement/requests_proc.php',
    'table' => 'prc_requests',
    'anchor' => '<table id="emsList_prc_requests"',
    'rows' => "ems_w14_guide_rows('prc_requests')",
    'grid_id' => 'emsList_prc_requests', 'empty' => 'لا سطر مسجل بعد في طلبات الشراء',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في طلبات الشراء',
    'map' => array(
        'رقم الطلب' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الطلب' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة الطالبة' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر الاحتياج' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف التشغيلي' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'المشروع المحمل' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'مركز التكلفة' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
        'عدد البنود تفصيلها ش02-2' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ المطلوب' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'التقدير المبدئي' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الطلب' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-05', 'route' => 'Procurement/proc_packages.php',
    'table' => 'prc_package_lines',
    'anchor' => '<table id="emsList_prc_package_lines"',
    'rows' => "ems_w14_guide_rows('prc_package_lines')",
    'grid_id' => 'emsList_prc_package_lines', 'empty' => 'لا سطر مسجل بعد في تجميع الطلبات وخطة الشراء',
    'create' => true,
    'grain' => 'تجميع الطلبات وخطة الشراء',
    'map' => array(
        'معرف العضوية' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'معرف الحزمة' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'رقم طلب الشراء' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'بنود الطلب المشمولة' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الضم' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العضوية' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-01', 'route' => 'Procurement/dashboard_proc.php',
    'table' => 'prc_dashboard_kpi',
    'anchor' => '<table id="emsList_prc_dashboard_kpi"',
    'rows' => "ems_w14_guide_rows('prc_dashboard_kpi')",
    'grid_id' => 'emsList_prc_dashboard_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة المشتريات',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة المشتريات',
    'map' => array(
        'معرف المؤشر' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر KPI Catalog' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g169:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة' => '+g170:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g171:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g172:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'PRC-15', 'route' => 'Procurement/po_match.php',
    'table' => 'proc_order',
    'anchor' => '<table id="emsList_proc_order"',
    'rows' => "ems_w14_guide_rows('proc_order')",
    'grid_id' => 'emsList_proc_order', 'empty' => 'لا سطر مسجل بعد في مطابقة الفاتورة الثلاثية',
    'map' => array(
        'رقم المطابقة' => '+g173:VARCHAR(190) NULL DEFAULT NULL',
        'رقم فاتورة المورد' => 'invoice_no',
        'رقم المورد' => '+g174:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g175:VARCHAR(190) NULL DEFAULT NULL',
        'سندات الإدخال' => '+g176:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الفاتورة' => 'invoice_amount',
        'قيمة الأمر' => '+g177:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة المستلم' => '+g178:VARCHAR(190) NULL DEFAULT NULL',
        'تصنيف الفرق' => '+g179:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة الفرق' => '+g180:VARCHAR(190) NULL DEFAULT NULL',
        'تفسير الفرق' => '+g181:VARCHAR(190) NULL DEFAULT NULL',
        'نتيجة المطابقة' => '+g182:VARCHAR(190) NULL DEFAULT NULL',
        'الإحالة للمالية' => '+g183:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المطابقة' => '+g184:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g185:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g186:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+g187:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+g188:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+g189:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g190:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g191:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
