<?php
/**
 * fields_dep02_guide.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-02',
'screens' => array(

array(
    'req' => 'SUP-03', 'route' => 'Suppliers/supplier_qualification.php',
    'table' => 'sup_qualification_legal_credit',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_qualification_legal_credit')",
    'grid_id' => 'emsList_sup_qualification', 'empty' => 'لا قيد تاهيل مسجل بعد',
    'map' => array(
        'رقم القيد' => 'id',
        'رقم المورد' => 'no_supplier',
        'اسم المورد (بحث)' => 'name_supplier',
        'نوع الوثيقة' => 'type',
        'رقم الوثيقة' => 'no',
        'جهة الإصدار' => 'issue',
        'تاريخ الإصدار' => 'date_issue',
        'تاريخ الانتهاء' => 'date_expiry',
        'حالة التحقق' => 'verify',
        'تاريخ التحقق' => 'date_verify',
        'المتحقق' => 'verifier',
        'اسم البنك' => 'name_bank',
        'الفرع' => 'branch',
        'رقم الحساب' => 'no_account',
        'اسم صاحب الحساب' => 'name_account',
        'مطابقة الاسم للمورد؟' => 'name',
        'علم حساب طرف ثالث' => 'account',
        'مستند تفويض الطرف الثالث' => 'doc_delegation',
        'حد التعامل الشهري $' => 'month',
        'حد التعامل ج.س' => 'c20',
        'شروط سداد افتراضية' => 'c21',
        'التصنيف الائتماني الداخلي' => 'credit',
        'أساس التصنيف' => 'c23',
        'مستوى الحجية' => '+authority_level:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+data_state:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => 'notes',
    ),
),

array(
    'req' => 'SUP-16', 'route' => 'Suppliers/supplier_targets.php',
    'table' => 'sup_target_supplier',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_target_supplier')",
    'grid_id' => 'emsList_sup_targets', 'empty' => 'لا مستهدف مسجل بعد',
    'map' => array(
        'رقم السطر' => 'id',
        'كود الوحدة التعاقدية' => 'slot_id',
        'رقم المورد' => 'no_supplier',
        'اسم المورد (بحث)' => 'name_supplier',
        'كود عقد المورد' => 'code_contract_supplier',
        'نموذج العمل' => 'c6',
        'نوع الآلية/البند' => 'type_line',
        'رقم الشهر' => 'no_month',
        'من' => 'c9',
        'إلى' => 'c10',
        'وحدة القياس' => 'c11',
        'خانات الشهر' => 'slot_month',
        'قيمة الوحدة التعاقدية (الجزئي أيامه/30)' => 'c13',
        'مستهدف الشهر' => 'target_month',
        'المنفذ بالشهر' => 'month',
        'نسبة تحقق الشهر' => 'verify_month',
        'علم شهر بلا تنفيذ' => 'month_17',
        'المستهدف المنقضي' => 'target',
        'نسخة الخطة' => 'c19',
        'مصدر المستهدف' => 'source_target',
        'ملاحظات' => 'notes',
    ),
),

array(
    'req' => 'SUP-18', 'route' => 'Suppliers/shares_coverage.php',
    'table' => 'sup_deficit_surplus',
    'anchor' => '<table class="table table-striped" data-no-dt>',
    'rows' => "ems_w14_guide_rows('sup_deficit_surplus')",
    'grid_id' => 'emsList_sup_coverage', 'empty' => 'لا قياس تغطية مسجل بعد',
    'map' => array(
        'معرف السطر' => 'id_1',
        'مفتاح دورة الالتزام' => 'role_obligation',
        'رقم فترة الالتزام' => 'no_role_obligation',
        'نوع الآلية/البند' => 'type_line',
        'سعة فترة الالتزام' => 'role_obligation_5',
        'مجموع مستهدفات الوحدات التعاقدية' => 'target_unit',
        'مجموع المنفذ' => 'c7',
        'نسبة التحقق' => 'verify',
        'مجموع عجز المقصرين' => 'deficit',
        'مجموع فائض المتجاوزين' => 'surplus',
        'نسبة التغطية بينهما' => 'c11',
        'عدد الموردين العاجزين' => 'count_supplier',
        'عدد المتجاوزين' => 'count',
        'أشهر متتالية بلا تغطية' => 'c14',
        'فجوة الالتزام النهائية' => 'c15',
        'إشارة إنذار' => 'c16',
        'مرجع الخطر المتفرع' => 'ref',
    ),
),

array(
    'req' => 'SUP-23', 'route' => 'Suppliers/supplier_payment_requests.php',
    'table' => 'sup_payment_disburse',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_payment_disburse')",
    'grid_id' => 'emsList_sup_payreq', 'empty' => 'لا طلب دفع مسجل بعد',
    'map' => array(
        'رقم الطلب' => 'id',
        'التاريخ' => 'date',
        'رقم المورد' => 'no_supplier',
        'الجهة المستفيدة' => 'c4',
        'طريقة الدفع' => 'payment',
        'اسم البنك' => 'name_bank',
        'رقم الحساب' => 'no_account',
        'اسم صاحب الحساب' => 'name_account',
        'علم طرف ثالث' => 'c9',
        'مرجع تفويض الطرف الثالث (م03)' => 'ref_delegation',
        'العميل/المشروع' => 'project',
        'نظام التقسيم' => 'c12',
        'مرجع التسوية (م17)' => 'ref',
        'المستلم ج.س (لاستحقاق الجنيه)' => 'c14',
        'المستلم بالجنيه (مدولر)' => 'c15',
        'سعر الصرف (مصدره وتاريخه)' => 'disburse_source_date',
        'المستلم الكلي $' => 'c17',
        'مفتاح شهر الصرف (YYYYMM)' => 'month_disburse',
        'شهر الاستحقاق المسدد (كما ورد)' => 'month_entitlement',
        'الإقفال المخصص' => 'closure',
        'حالة التخصيص' => 'allocation',
        'حالة الطلب' => 'c22',
        'حالة الصرف (قراءة)' => 'disburse',
        'تاريخ الصرف' => 'date_disburse',
        'مرجع الصرف' => 'ref_disburse',
        'سياق الآلية (إن ورد)' => 'c26',
        'طبيعة الدفعة (مستخرجة)' => 'payment_27',
        'البيان (مصدر)' => 'source',
        'ملاحظات' => 'notes',
        'المنشئ' => '+creator_name:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+reviewer_name:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+approver_name:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-25', 'route' => 'Suppliers/supplier_aging.php',
    'table' => 'sup_aging_obligation',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_aging_obligation')",
    'grid_id' => 'emsList_sup_aging', 'empty' => 'لا رصيد مسجل بعد',
    'map' => array(
        'كود الرصيد' => 'id',
        'التسلسل الزمني للمورد' => 'c2',
        'رقم المورد' => 'no_supplier',
        'اسم المورد (بحث)' => 'name_supplier',
        'العملة' => 'c5',
        'إجمالي الاستحقاق' => 'entitlement',
        'إجمالي المدفوع' => 'c7',
        'الرصيد القائم' => 'balance',
        'آخر شهر حركة' => 'month',
        'عمر الرصيد (يوما)' => 'balance_10',
        'شريحة العمر' => 'c11',
        'حالة الرصيد' => 'balance_12',
        'حالة المورد (م01)' => 'supplier',
        'التزام قادم ≤30 يوما' => 'c14',
        'التزام قادم 31 60' => 'c15',
        'التزام قادم 61 90' => 'c16',
        'إجراء التحصيل/السداد المقترح' => 'c17',
        'المسؤول' => 'c18',
        'Record_Basis' => '+record_basis:VARCHAR(190) NULL DEFAULT NULL',
        'Derivation_Rule' => '+derivation_rule:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+data_state:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => 'notes',
    ),
),

array(
    'req' => 'SUP-28', 'route' => 'Suppliers/supplier_contract_events.php',
    'table' => 'sup_close',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_close')",
    'grid_id' => 'emsList_sup_events', 'empty' => 'لا واقعة اغلاق مسجلة بعد',
    'map' => array(
        'رقم القيد' => 'id',
        'كود عقد المورد' => 'code_contract_supplier',
        'نوع وثيقة الإغلاق' => 'type_close',
        'رقم النسخة' => 'no',
        'ما الذي تغير' => 'c5',
        'سريان من' => 'c6',
        'تاريخ التوقيع' => 'date',
        'الحالة' => 'c8',
        'مرجع تسوية الإغلاق (م17)' => 'ref_close',
        'إخلاء الطرف' => 'c10',
        'المستند' => 'doc',
        'ملاحظات' => 'notes',
    ),
),

array(
    'req' => 'SUP-31', 'route' => 'Suppliers/supplier_ref_lists.php',
    'table' => 'sup_list_ref',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_list_ref')",
    'grid_id' => 'emsList_sup_reflists', 'empty' => 'لا قائمة مرجعية مسجلة بعد',
    'map' => array(
        'نموذج العمل' => '+business_model:VARCHAR(160) NULL DEFAULT NULL',
        'وحدة القياس' => 'c2',
        'العملة' => 'c3',
        'نوع الآلية/البند' => 'type_line',
        'بادئة النوع (v4)' => 'type',
        'تصنيف المورد' => 'supplier',
        'فئة مصدر القدرة' => 'source',
        'طبيعة المورد' => 'supplier_8',
        'حالة المورد' => 'supplier_9',
        'أساس اشتقاق الحالة' => 'c10',
        'نوع التفويض' => 'type_delegation',
        'نوع الوثيقة' => 'type_12',
        'حالة التحقق' => 'verify',
        'نوع الوحدة التعاقدية' => 'type_14',
        'التصنيف (استمرارية)' => 'c15',
        'الدور (أساسية/احتياطية)' => 'role',
        'نوع الإسناد' => 'type_17',
        'الحدث' => 'c18',
        'حالة العقد' => 'contract',
        'تكييف الوثيقة' => 'c20',
        'مستوى الحجية' => '+authority_level:VARCHAR(190) NULL DEFAULT NULL',
        'حجية الحصة (المصدر)' => 'source_22',
        'كود الالتزام' => 'code_obligation',
        'أطراف الثلاثية' => 'c24',
        'طرف الالتزام (م09)' => 'obligation',
        'قابل للاسترداد؟' => 'c26',
        'نوع الواقعة النيابية' => 'type_onbehalf',
        'حالة السلسلة النيابية' => 'onbehalf',
        'حالة الاستحقاق' => 'entitlement',
        'حالة التسوية' => 'c30',
        'نظام التقسيم' => 'c31',
        'طريقة الدفع' => 'payment',
        'حالة الطلب' => 'c33',
        'حالة الصرف' => 'disburse',
        'نوع الجزاء/المطالبة' => 'type_penalty',
        'نوع وثيقة الإغلاق' => 'type_close',
        'التصنيف الاستراتيجي' => 'c37',
        'مصدر القدرة' => 'source_38',
        'قرار الترحيل' => 'migration',
        'جاهزية التوقيع' => 'c40',
        'نتيجة الفحص' => 'c41',
        'حالة الحصة' => 'c42',
        'الوضع التشغيلي' => 'c43',
        'الاستمرارية' => 'c44',
        'طريقة الربط بالحصة' => 'c45',
        'طبيعة علاقة المورد بالمعدة' => 'supplier_46',
        'معالجة الاستعداد والتوقف (قاعدة)' => 'c47',
    ),
),

array(
    'req' => 'SUP-33', 'route' => 'Suppliers/supplier_inference_rules.php',
    'table' => 'sup_dictionary_rule_derivation',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_dictionary_rule_derivation')",
    'grid_id' => 'emsList_sup_rules', 'empty' => 'لا قاعدة استنتاج مسجلة بعد',
    'map' => array(
        'كود القاعدة' => '+code_rule:VARCHAR(60) NULL DEFAULT NULL',
        'الحقل/المخرج' => 'c2',
        'القيم الممكنة' => 'c3',
        'قاعدة الاشتقاق' => 'c4',
        'الشيت المطبق فيه' => 'c5',
        'القيد/التحذير' => 'c6',
        'تصنيف الحجية' => '+authority_class:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-34', 'route' => 'Suppliers/supplier_data_dictionary.php',
    'table' => 'sup_dictionary_migration',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_dictionary_migration')",
    'grid_id' => 'emsList_sup_dict', 'empty' => 'لا مفردة قاموس مسجلة بعد',
    'map' => array(
        'الاسم التقني' => '+name_technical:VARCHAR(160) NULL DEFAULT NULL',
        'التسمية العربية' => 'c2',
        'الكيان' => 'c3',
        'الشيت' => 'c4',
        'نوع البيانات' => 'type',
        'إلزامي؟' => 'c6',
        'المفتاح' => 'c7',
        'القيم المسموحة (قائمة م24)' => 'c8',
        'مصدر الحقيقة/المالك' => 'source_owner',
        'حالة البيانات' => '+data_state:VARCHAR(190) NULL DEFAULT NULL',
        'تصنيف الفراغ (ما يعنيه الفراغ)' => 'c11',
        'ملاحظات' => 'notes',
    ),
),

array(
    'req' => 'SUP-35', 'route' => 'Suppliers/supplier_migration_trace.php',
    'table' => 'sup_trace_migration',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_trace_migration')",
    'grid_id' => 'emsList_sup_trace', 'empty' => 'لا قيد تتبع مسجل بعد',
    'map' => array(
        'رقم القيد' => 'id',
        'ملف المصدر' => 'source',
        'شيت المصدر' => 'source_3',
        'العمود' => 'c4',
        'Source_Row_Ref' => '+source_row_ref:VARCHAR(190) NULL DEFAULT NULL',
        'الكيان الهدف' => 'c6',
        'الشيت الهدف' => 'c7',
        'معرف السجل الهدف' => 'id_8',
        'قرار الترحيل' => 'migration',
        'التحويل المطبق' => 'c10',
        'حالة الترحيل' => 'migration_11',
        'تاريخ الترحيل' => 'date_migration',
        'المدقق' => 'c13',
        'ملاحظة' => 'c14',
    ),
),

array(
    'req' => 'SUP-36', 'route' => 'Suppliers/supplier_migration_map.php',
    'table' => 'sup_migration',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_migration')",
    'grid_id' => 'emsList_sup_migmap', 'empty' => 'لا سطر خريطة ترحيل مسجل بعد',
    'map' => array(
        '#' => 'id',
        'الاتجاه' => 'c2',
        'ملف/شيت المصدر' => 'source',
        'العمود/الحقل' => 'c4',
        'الوجهة/المصدر' => 'source_5',
        'قرار الترحيل' => 'migration',
        'ملاحظة' => 'c7',
    ),
),

array(
    'req' => 'SUP-37', 'route' => 'Suppliers/supplier_review_report.php',
    'table' => 'sup_report_accept',
    'anchor' => '<table class="ems-data-table">',
    'rows' => "ems_w14_guide_rows('sup_report_accept')",
    'grid_id' => 'emsList_sup_review', 'empty' => 'لا بند مراجعة مسجل بعد',
    'map' => array(
        'القسم' => '+section:VARCHAR(160) NULL DEFAULT NULL',
        'البند' => 'line',
        'القيمة/النتيجة' => 'c3',
        'الحالة' => 'c4',
        'ملاحظة' => 'c5',
    ),
),

),
);
