<?php
/**
 * fields_dep02_rest.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-02',
'screens' => array(

array(
    'req' => 'SUP-01', 'route' => 'Suppliers/suppliers.php',
    'table' => 'suppliers',
    'anchor' => '<table id="emsList_sup_register">',
    'rows' => "ems_w14_guide_rows('suppliers')",
    'grid_id' => 'emsList_sup_register', 'empty' => 'لا مورد مسجل بعد',
    'map' => array(
        'رقم المورد' => '+c1:VARCHAR(190) NULL DEFAULT NULL',
        'التسلسل الزمني للتعامل' => '+c2:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم القانوني' => '+c3:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم المختصر' => '+c4:VARCHAR(190) NULL DEFAULT NULL',
        'المرادف القديم' => '+c5:VARCHAR(190) NULL DEFAULT NULL',
        'تصنيف المورد' => '+c6:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المورد (مصدر)' => 'supplier_type',
        'مصدر القيد' => '+c7:VARCHAR(190) NULL DEFAULT NULL',
        'فئة مصدر القدرة' => '+c8:VARCHAR(190) NULL DEFAULT NULL',
        'نمط التعاقد' => '+c9:VARCHAR(190) NULL DEFAULT NULL',
        'طبيعة المورد (مالك/وسيط)' => '+c10:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المورد' => '+c11:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ آخر نشاط تشغيلي' => '+c12:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ آخر حركة مالية' => '+c13:VARCHAR(190) NULL DEFAULT NULL',
        'أشهر منذ آخر نشاط' => '+c14:VARCHAR(190) NULL DEFAULT NULL',
        'دليل آخر نشاط' => '+c15:VARCHAR(190) NULL DEFAULT NULL',
        'أساس الحالة' => '+c16:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ أول تعامل' => '+c17:VARCHAR(190) NULL DEFAULT NULL',
        'الدولة' => '+c18:VARCHAR(190) NULL DEFAULT NULL',
        'المدينة' => '+c19:VARCHAR(190) NULL DEFAULT NULL',
        'السجل التجاري' => '+c20:VARCHAR(190) NULL DEFAULT NULL',
        'الرقم الضريبي' => 'tax_number',
        'نماذج التعامل' => '+c21:VARCHAR(190) NULL DEFAULT NULL',
        'العملات المتعامل بها' => '+c22:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الحصص' => '+c23:VARCHAR(190) NULL DEFAULT NULL',
        'عدد المعدات المسندة' => '+c24:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التأهيل (م03)' => '+c25:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف الاستراتيجي (م20)' => '+c26:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+c27:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر التوثيق' => '+c28:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c29:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-02', 'route' => 'Suppliers/supplier_contacts.php',
    'table' => 'sup_contact_delegate',
    'anchor' => '<table id="emsList_sup_contacts">',
    'rows' => "ems_w14_guide_rows('sup_contact_delegate')",
    'grid_id' => 'emsList_sup_contacts', 'empty' => 'لا جهة اتصال مسجلة بعد',
    'create' => true,
    'grain' => 'جهة اتصال واحدة لمورد',
    'map' => array(
        'رقم الجهة' => '+c30:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+c31:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c32:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم' => '+c33:VARCHAR(190) NULL DEFAULT NULL',
        'الصفة/الدور' => '+c34:VARCHAR(190) NULL DEFAULT NULL',
        'نوع التفويض' => '+c35:VARCHAR(190) NULL DEFAULT NULL',
        'مستند التفويض' => '+c36:VARCHAR(190) NULL DEFAULT NULL',
        'سريان التفويض من' => '+c37:VARCHAR(190) NULL DEFAULT NULL',
        'إلى' => '+c38:VARCHAR(190) NULL DEFAULT NULL',
        'الهاتف الأساسي' => '+c39:VARCHAR(190) NULL DEFAULT NULL',
        'هاتف بديل' => '+c40:VARCHAR(190) NULL DEFAULT NULL',
        'البريد' => '+c41:VARCHAR(190) NULL DEFAULT NULL',
        'حالة جهة الاتصال' => '+c42:VARCHAR(190) NULL DEFAULT NULL',
        'الحجية' => '+c43:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+c44:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c45:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-04', 'route' => 'Suppliers/equipment_plan.php',
    'table' => 'sup_equipment_available',
    'anchor' => '<table id="emsList_sup_equipplan">',
    'rows' => "ems_w14_guide_rows('sup_equipment_available')",
    'grid_id' => 'emsList_sup_equipplan', 'empty' => 'لا معدة متاحة مسجلة بعد',
    'create' => true,
    'grain' => 'معدة واحدة متاحة لمورد',
    'map' => array(
        'كود المعدة' => '+c46:VARCHAR(190) NULL DEFAULT NULL',
        'التسلسل الزمني للإسناد' => '+c47:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+c48:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c49:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الآلية/البند' => '+c50:VARCHAR(190) NULL DEFAULT NULL',
        'بادئة النوع (v4)' => '+c51:VARCHAR(190) NULL DEFAULT NULL',
        'رقم اللوحة (كما ورد)' => '+c52:VARCHAR(190) NULL DEFAULT NULL',
        'رمز اللوحة' => '+c53:VARCHAR(190) NULL DEFAULT NULL',
        'رقم اللوحة (رقمي)' => '+c54:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الشاسي' => '+c55:VARCHAR(190) NULL DEFAULT NULL',
        'سنة الصنع' => '+c56:VARCHAR(190) NULL DEFAULT NULL',
        'الملكية' => '+c57:VARCHAR(190) NULL DEFAULT NULL',
        'المالك القانوني للمعدة' => '+c58:VARCHAR(190) NULL DEFAULT NULL',
        'هاتف المالك' => '+c59:VARCHAR(190) NULL DEFAULT NULL',
        'صفة المورد تجاه المعدة' => '+c60:VARCHAR(190) NULL DEFAULT NULL',
        'مستند حق التقديم (نوع/رقم/تاريخ/جهة)' => '+c61:VARCHAR(190) NULL DEFAULT NULL',
        'حالة التحقق من الصفة' => '+c62:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التحقق' => '+c63:VARCHAR(190) NULL DEFAULT NULL',
        'المتحقق' => '+c64:VARCHAR(190) NULL DEFAULT NULL',
        'مخاطر الصفة' => '+c65:VARCHAR(190) NULL DEFAULT NULL',
        'وسم «لا ترسمل»' => '+c66:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المعدة' => '+c67:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ أول إسناد' => '+c68:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ آخر إسناد' => '+c69:VARCHAR(190) NULL DEFAULT NULL',
        'أشهر منذ آخر نشاط' => '+c70:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الوحدات التعاقدية التي خدمها' => '+c71:VARCHAR(190) NULL DEFAULT NULL',
        'آخر عميل خدمه' => '+c72:VARCHAR(190) NULL DEFAULT NULL',
        'أساس حالة المعدة' => '+c73:VARCHAR(190) NULL DEFAULT NULL',
        'علم تعارض الحالة' => '+c74:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الحالة' => '+c75:VARCHAR(190) NULL DEFAULT NULL',
        'معدة مساندة؟' => '+c76:VARCHAR(190) NULL DEFAULT NULL',
        'مرادفات أكواد قديمة' => '+c77:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر التوثيق' => '+c78:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c79:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-06', 'route' => 'Suppliers/rfq_requests.php',
    'table' => 'sup_rfq_review',
    'anchor' => '<table id="emsList_sup_rfq">',
    'rows' => "ems_w14_guide_rows('sup_rfq_review')",
    'grid_id' => 'emsList_sup_rfq', 'empty' => 'لا ترشيح مسجل بعد',
    'create' => true,
    'grain' => 'ترشيح واحد بمراجعة تعاقده',
    'map' => array(
        'رقم الترشيح' => '+c80:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الاحتياج' => '+c81:VARCHAR(190) NULL DEFAULT NULL',
        'كود العقد' => '+c82:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+c83:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c84:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الآلية/البند' => '+c85:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة المعروضة' => '+c86:VARCHAR(190) NULL DEFAULT NULL',
        'السعر المعروض' => '+c87:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+c88:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ العرض' => '+c89:VARCHAR(190) NULL DEFAULT NULL',
        'فحص التأهيل القانوني' => '+c90:VARCHAR(190) NULL DEFAULT NULL',
        'فحص الحساب البنكي' => '+c91:VARCHAR(190) NULL DEFAULT NULL',
        'فحص تعارض المصالح' => '+c92:VARCHAR(190) NULL DEFAULT NULL',
        'فحص السقف الائتماني' => '+c93:VARCHAR(190) NULL DEFAULT NULL',
        'فحص الهامش (ضمن الحد)' => '+c94:VARCHAR(190) NULL DEFAULT NULL',
        'فحص توافق الحصة مع الاحتياج' => '+c95:VARCHAR(190) NULL DEFAULT NULL',
        'استثناء معتمد (مرجع)' => '+c96:VARCHAR(190) NULL DEFAULT NULL',
        'جاهزية التوقيع' => '+c97:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+c98:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+c99:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+c100:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ المراجعة' => '+c101:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الترشيح' => '+c102:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الاختيار/الاستبعاد' => '+c103:VARCHAR(190) NULL DEFAULT NULL',
        'كود عقد المورد الناتج' => '+c104:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+c105:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c106:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-08', 'route' => 'Suppliers/supplierscontracts.php',
    'table' => 'sup_contract_register',
    'anchor' => '<table id="emsList_sup_contracts">',
    'rows' => "ems_w14_guide_rows('sup_contract_register')",
    'grid_id' => 'emsList_sup_contracts', 'empty' => 'لا عقد مورد مسجل بعد',
    'create' => true,
    'grain' => 'عقد مورد واحد',
    'map' => array(
        'كود عقد المورد' => '+c107:VARCHAR(190) NULL DEFAULT NULL',
        'التسلسل الزمني للعقد' => '+c108:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+c109:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c110:VARCHAR(190) NULL DEFAULT NULL',
        'كود العقد (العميل)' => '+c111:VARCHAR(190) NULL DEFAULT NULL',
        'رقم العميل' => '+c112:VARCHAR(190) NULL DEFAULT NULL',
        'اسم العميل (بحث)' => '+c113:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+c114:VARCHAR(190) NULL DEFAULT NULL',
        'رقم عقد المورد (رتبة الانضمام)' => '+c115:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل عقد المورد بالشركة' => '+c116:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح دورة الالتزام' => '+c117:VARCHAR(190) NULL DEFAULT NULL',
        'استثناء تسوية فقط؟' => '+c118:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع اعتماد الاستثناء' => '+c119:VARCHAR(190) NULL DEFAULT NULL',
        'توقيع الوثيقة' => '+c120:VARCHAR(190) NULL DEFAULT NULL',
        'البداية التعاقدية (مستنتجة)' => '+c121:VARCHAR(190) NULL DEFAULT NULL',
        'النهاية التعاقدية (مستنتجة)' => '+c122:VARCHAR(190) NULL DEFAULT NULL',
        'أساس استنتاج المدة' => '+c123:VARCHAR(190) NULL DEFAULT NULL',
        'البداية التنفيذية' => '+c124:VARCHAR(190) NULL DEFAULT NULL',
        'النهاية التنفيذية' => '+c125:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الانضمام (أول يوم عمل)' => '+c126:VARCHAR(190) NULL DEFAULT NULL',
        'حالة العقد' => '+c127:VARCHAR(190) NULL DEFAULT NULL',
        'أساس حالة العقد' => '+c128:VARCHAR(190) NULL DEFAULT NULL',
        'تعارض مع حالة عقد العميل' => '+c129:VARCHAR(190) NULL DEFAULT NULL',
        'تكييف الوثيقة' => '+c130:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الحجية' => '+c131:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+c132:VARCHAR(190) NULL DEFAULT NULL',
        'شروط السداد' => '+c133:VARCHAR(190) NULL DEFAULT NULL',
        'موقع التنفيذ/المنجم' => '+c134:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة الشهرية التعاقدية' => '+c135:VARCHAR(190) NULL DEFAULT NULL',
        'قيمة العقد التقديرية' => '+c136:VARCHAR(190) NULL DEFAULT NULL',
        'عدد البنود' => '+c137:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الوحدات التعاقدية المسندة' => '+c138:VARCHAR(190) NULL DEFAULT NULL',
        'نسخة العقد الحالية' => '+c139:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع آخر ملحق (م21)' => '+c140:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الإغلاق' => '+c141:VARCHAR(190) NULL DEFAULT NULL',
        'علم انتهاء قبل عقد العميل' => '+c142:VARCHAR(190) NULL DEFAULT NULL',
        'حلقات الحجية المتوفرة (من 20)' => '+c143:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة اكتمال الملف المستندي' => '+c144:VARCHAR(190) NULL DEFAULT NULL',
        'الحلقات المفقودة' => '+c145:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+c146:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c147:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+c148:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+c149:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+c150:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد الداخلي' => '+c151:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-09', 'route' => 'Suppliers/supplier_contract_lines.php',
    'table' => 'sup_contract_line',
    'anchor' => '<table id="emsList_sup_lines">',
    'rows' => "ems_w14_guide_rows('sup_contract_line')",
    'grid_id' => 'emsList_sup_lines', 'empty' => 'لا بند عقد مسجل بعد',
    'create' => true,
    'grain' => 'بند واحد في عقد مورد',
    'map' => array(
        'رقم البند' => '+c152:VARCHAR(190) NULL DEFAULT NULL',
        'كود عقد المورد' => '+c153:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+c154:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c155:VARCHAR(190) NULL DEFAULT NULL',
        'رقم بند عقد العميل المقابل' => '+c156:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+c157:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الآلية/البند' => '+c158:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة القياس' => '+c159:VARCHAR(190) NULL DEFAULT NULL',
        'الحصة الشهرية المتعاقدة' => '+c160:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الوحدة الأساسي' => '+c161:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الوحدة الإضافي' => '+c162:VARCHAR(190) NULL DEFAULT NULL',
        'سعر السداد ≤15 يوما' => '+c163:VARCHAR(190) NULL DEFAULT NULL',
        'سعر السداد 15 45' => '+c164:VARCHAR(190) NULL DEFAULT NULL',
        'سعر السداد >45' => '+c165:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ الشهري الأساسي' => '+c166:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الورديات' => '+c167:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+c168:VARCHAR(190) NULL DEFAULT NULL',
        'سريان التركيبة من' => '+c169:VARCHAR(190) NULL DEFAULT NULL',
        'إلى' => '+c170:VARCHAR(190) NULL DEFAULT NULL',
        'Pricing_Model' => '+c171:VARCHAR(190) NULL DEFAULT NULL',
        'Billing_UOM' => '+c172:VARCHAR(190) NULL DEFAULT NULL',
        'Minimum_Qty (أساس الوحدة التعاقدية)' => '+c173:VARCHAR(190) NULL DEFAULT NULL',
        'Minimum_Period' => '+c174:VARCHAR(190) NULL DEFAULT NULL',
        'Guaranteed_Qty' => '+c175:VARCHAR(190) NULL DEFAULT NULL',
        'Threshold_Qty' => '+c176:VARCHAR(190) NULL DEFAULT NULL',
        'Shortfall_Bearer' => '+c177:VARCHAR(190) NULL DEFAULT NULL',
        'Pricing_Reference' => '+c178:VARCHAR(190) NULL DEFAULT NULL',
        'النسخة السعرية' => '+c179:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البند' => '+c180:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر السعر/الحجية' => '+c181:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c182:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-20', 'route' => 'Suppliers/supplier_entitlements.php',
    'table' => 'sup_entitlement',
    'anchor' => '<table id="emsList_sup_entitle">',
    'rows' => "ems_w14_guide_rows('sup_entitlement')",
    'grid_id' => 'emsList_sup_entitle', 'empty' => 'لا استحقاق مسجل بعد',
    'create' => true,
    'grain' => 'استحقاق مورد لشهر',
    'map' => array(
        'رقم الاستحقاق' => '+c183:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة (شهر)' => '+c184:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+c185:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c186:VARCHAR(190) NULL DEFAULT NULL',
        'كود عقد المورد' => '+c187:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البند' => '+c188:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة القياس' => '+c189:VARCHAR(190) NULL DEFAULT NULL',
        'مفتاح الشهر (YYYYMM)' => '+c190:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الآلية/البند' => '+c191:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدات المعتمدة' => '+c192:VARCHAR(190) NULL DEFAULT NULL',
        'الاتفاق الشهري $' => '+c193:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الساعة $ (مطبق)' => '+c194:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الإضافية $ (مطبق)' => '+c195:VARCHAR(190) NULL DEFAULT NULL',
        'سعر الساعة ج.س (مطبق)' => '+c196:VARCHAR(190) NULL DEFAULT NULL',
        'سعر طن ويست (مطبق)' => '+c197:VARCHAR(190) NULL DEFAULT NULL',
        'سعر طن خام (مطبق)' => '+c198:VARCHAR(190) NULL DEFAULT NULL',
        'سعر متر تفجير (مطبق)' => '+c199:VARCHAR(190) NULL DEFAULT NULL',
        'سعر متر G.C (مطبق)' => '+c200:VARCHAR(190) NULL DEFAULT NULL',
        'مستحق الساعات $' => '+c201:VARCHAR(190) NULL DEFAULT NULL',
        'مستحق الساعات ج.س' => '+c202:VARCHAR(190) NULL DEFAULT NULL',
        'مبلغ الإضافية $' => '+c203:VARCHAR(190) NULL DEFAULT NULL',
        'مستحق الأطنان $' => '+c204:VARCHAR(190) NULL DEFAULT NULL',
        'مستحق تفجير $' => '+c205:VARCHAR(190) NULL DEFAULT NULL',
        'مستحق G.C $' => '+c206:VARCHAR(190) NULL DEFAULT NULL',
        '(−) الخصومات' => '+c207:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الاستحقاق $' => '+c208:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي الاستحقاق ج.س' => '+c209:VARCHAR(190) NULL DEFAULT NULL',
        'المستلم الكلي $ (مصدر)' => '+c210:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي $ (مصدر)' => '+c211:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي ج.س (مصدر)' => '+c212:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الاستحقاق' => '+c213:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإثبات' => '+c214:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الأداء (م14)' => '+c215:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر السعر' => '+c216:VARCHAR(190) NULL DEFAULT NULL',
        'البيان (مصدر)' => '+c217:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c218:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-26', 'route' => 'Suppliers/supplier_violations.php',
    'table' => 'sup_violations',
    'anchor' => '<table id="emsList_sup_viol">',
    'rows' => "ems_w14_guide_rows('sup_violations')",
    'grid_id' => 'emsList_sup_viol', 'empty' => 'لا مخالفة مسجلة بعد',
    'map' => array(
        'رقم القيد' => '+c219:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => '+c220:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+c221:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c222:VARCHAR(190) NULL DEFAULT NULL',
        'كود عقد المورد' => '+c223:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الجزاء/المطالبة' => '+c224:VARCHAR(190) NULL DEFAULT NULL',
        'الوصف' => '+c225:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع التعاقدي (بند)' => '+c226:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ/الأثر' => '+c227:VARCHAR(190) NULL DEFAULT NULL',
        'العملة' => '+c228:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+c229:VARCHAR(190) NULL DEFAULT NULL',
        'القرار' => '+c230:VARCHAR(190) NULL DEFAULT NULL',
        'معتمد القرار' => '+c231:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع الخصم بالتسوية (م17)' => '+c232:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+c233:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c234:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-27', 'route' => 'Suppliers/supplier_evaluation.php',
    'table' => 'supplier_evaluations',
    'anchor' => '<table id="emsList_sup_eval">',
    'rows' => "ems_w14_guide_rows('supplier_evaluations')",
    'grid_id' => 'emsList_sup_eval', 'empty' => 'لا تقييم مسجل بعد',
    'map' => array(
        'رقم المورد' => '+c235:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c236:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+c237:VARCHAR(190) NULL DEFAULT NULL',
        'عقود نشطة' => '+c238:VARCHAR(190) NULL DEFAULT NULL',
        'عقود منتهية بلا إغلاق' => '+c239:VARCHAR(190) NULL DEFAULT NULL',
        'حصص (خانات)' => '+c240:VARCHAR(190) NULL DEFAULT NULL',
        'معدات مسندة' => '+c241:VARCHAR(190) NULL DEFAULT NULL',
        'انكشاف الاستحقاق $' => '+c242:VARCHAR(190) NULL DEFAULT NULL',
        'المدفوع $' => '+c243:VARCHAR(190) NULL DEFAULT NULL',
        'الرصيد المستحق $' => '+c244:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة التركز من محفظة الاستحقاق' => '+c245:VARCHAR(190) NULL DEFAULT NULL',
        'Σ المستهدف (تجميعي عبر الوحدات)' => '+c246:VARCHAR(190) NULL DEFAULT NULL',
        'Σ المنفذ (تجميعي)' => '+c247:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة تحقق الحصص' => '+c248:VARCHAR(190) NULL DEFAULT NULL',
        'Σ مخصومة عمل (ساعات)' => '+c249:VARCHAR(190) NULL DEFAULT NULL',
        'معدل الخصومات' => '+c250:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة معدات غير متحقق الصفة' => '+c251:VARCHAR(190) NULL DEFAULT NULL',
        'موردون بديلون لأضيق نوع' => '+c252:VARCHAR(190) NULL DEFAULT NULL',
        'عقود تنتهي قبل عقد العميل' => '+c253:VARCHAR(190) NULL DEFAULT NULL',
        'تصنيف المخاطرة المركب' => '+c254:VARCHAR(190) NULL DEFAULT NULL',
        'درجة المخاطرة' => '+c255:VARCHAR(190) NULL DEFAULT NULL',
        'الالتزام بالمواعيد %' => '+c256:VARCHAR(190) NULL DEFAULT NULL',
        'جودة المعدات (1 5)' => '+c257:VARCHAR(190) NULL DEFAULT NULL',
        'الاستجابة للبلاغات' => '+c258:VARCHAR(190) NULL DEFAULT NULL',
        'التصنيف الاستراتيجي' => '+c259:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات الأداء' => '+c260:VARCHAR(190) NULL DEFAULT NULL',
        'المقيم' => '+c261:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التقييم' => '+c262:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الاعتماد' => '+c263:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-29', 'route' => 'Suppliers/supplier_capacity_integration.php',
    'table' => 'supplier_capacity',
    'anchor' => '<table id="emsList_sup_capacity">',
    'rows' => "ems_w14_guide_rows('supplier_capacity')",
    'grid_id' => 'emsList_sup_capacity', 'empty' => 'لا مصدر قدرة مسجل بعد',
    'map' => array(
        'رقم السطر' => '+c264:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر القدرة' => '+c265:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع (كود عقد مورد / كود أصل)' => '+c266:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الآلية/البند' => '+c267:VARCHAR(190) NULL DEFAULT NULL',
        'الطاقة الشهرية' => '+c268:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة القياس' => '+c269:VARCHAR(190) NULL DEFAULT NULL',
        'تكلفة الوحدة (قراءة)' => '+c270:VARCHAR(190) NULL DEFAULT NULL',
        'نظام المصدر' => '+c271:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+c272:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+c273:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة الفصل' => '+c274:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-30', 'route' => 'Suppliers/supplier_board.php',
    'table' => 'sup_dashboard_kpi',
    'anchor' => '<table id="emsList_sup_board">',
    'rows' => "ems_w14_guide_rows('sup_dashboard_kpi')",
    'grid_id' => 'emsList_sup_board', 'empty' => 'لا مؤشر معرف بعد',
    'create' => true,
    'grain' => 'مؤشر واحد للوحة الموردين',
    'map' => array(
        'المؤشر' => '+c275:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+c276:VARCHAR(190) NULL DEFAULT NULL',
        'المعادلة/المصدر' => '+c277:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+c278:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة' => '+c279:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'SUP-17', 'route' => 'Suppliers/supplier_performance_entries.php',
    'table' => 'sup_performance_unit',
    'anchor' => '<table id="emsList_sup_perf">',
    'rows' => "ems_w14_guide_rows('sup_performance_unit')",
    'grid_id' => 'emsList_sup_perf', 'empty' => 'لا سطر اداء مسجل بعد',
    'create' => true,
    'grain' => 'سطر اداء لوحدة تعاقدية في شهر',
    'map' => array(
        'رقم السطر' => '+c280:VARCHAR(190) NULL DEFAULT NULL',
        'كود الوحدة التعاقدية' => '+c281:VARCHAR(190) NULL DEFAULT NULL',
        'كود عقد المورد' => '+c282:VARCHAR(190) NULL DEFAULT NULL',
        'رقم المورد' => '+c283:VARCHAR(190) NULL DEFAULT NULL',
        'اسم المورد (بحث)' => '+c284:VARCHAR(190) NULL DEFAULT NULL',
        'نموذج العمل' => '+c285:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الشهر' => '+c286:VARCHAR(190) NULL DEFAULT NULL',
        'من' => '+c287:VARCHAR(190) NULL DEFAULT NULL',
        'إلى' => '+c288:VARCHAR(190) NULL DEFAULT NULL',
        'وحدة القياس' => '+c289:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الآلية/البند' => '+c290:VARCHAR(190) NULL DEFAULT NULL',
        'رمز الآلية (مصدر)' => '+c291:VARCHAR(190) NULL DEFAULT NULL',
        'رقم اللوحة' => '+c292:VARCHAR(190) NULL DEFAULT NULL',
        'ساعات الاتفاق (متعاقد)' => '+c293:VARCHAR(190) NULL DEFAULT NULL',
        'أطنان متفق عليها' => '+c294:VARCHAR(190) NULL DEFAULT NULL',
        'أمتار متفق عليها' => '+c295:VARCHAR(190) NULL DEFAULT NULL',
        'المنفذ (الأساس)' => '+c296:VARCHAR(190) NULL DEFAULT NULL',
        'ساعات أساسية (مصدر)' => '+c297:VARCHAR(190) NULL DEFAULT NULL',
        'أطنان ويست' => '+c298:VARCHAR(190) NULL DEFAULT NULL',
        'أطنان خام' => '+c299:VARCHAR(190) NULL DEFAULT NULL',
        'أمتار تفجير' => '+c300:VARCHAR(190) NULL DEFAULT NULL',
        'أمتار G.C' => '+c301:VARCHAR(190) NULL DEFAULT NULL',
        'مضافة عمل' => '+c302:VARCHAR(190) NULL DEFAULT NULL',
        'مستند المضافة عمل' => '+c303:VARCHAR(190) NULL DEFAULT NULL',
        'مضافة تعطل' => '+c304:VARCHAR(190) NULL DEFAULT NULL',
        'مضافة استعداد' => '+c305:VARCHAR(190) NULL DEFAULT NULL',
        'مستند المضافة استعداد' => '+c306:VARCHAR(190) NULL DEFAULT NULL',
        'مخصومة استعداد' => '+c307:VARCHAR(190) NULL DEFAULT NULL',
        'مخصومة عمل' => '+c308:VARCHAR(190) NULL DEFAULT NULL',
        'سبب الخصم' => '+c309:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع قرار الخصم' => '+c310:VARCHAR(190) NULL DEFAULT NULL',
        'معتمد التسوية' => '+c311:VARCHAR(190) NULL DEFAULT NULL',
        'الساعات الفعلية' => '+c312:VARCHAR(190) NULL DEFAULT NULL',
        'الساعات الكلية' => '+c313:VARCHAR(190) NULL DEFAULT NULL',
        'صافي وحدات المورد المعتمدة' => '+c314:VARCHAR(190) NULL DEFAULT NULL',
        'منجزة العميل (قراءة)' => '+c315:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاعتماد' => '+c316:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر البيان' => '+c317:VARCHAR(190) NULL DEFAULT NULL',
        'طريقة الربط بالحصة' => '+c318:VARCHAR(190) NULL DEFAULT NULL',
        'حالة المورد وقت القيد' => '+c319:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظات' => '+c320:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+c321:VARCHAR(190) NULL DEFAULT NULL',
        'المراجع' => '+c322:VARCHAR(190) NULL DEFAULT NULL',
        'المعتمد' => '+c323:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
