<?php
/**
 * fields_dep14.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'DEP-14',
'screens' => array(

array(
    'req' => 'MNT-04', 'route' => 'Maintenance/breakdown_intake.php',
    'table' => 'mnt_breakdown_intake',
    'anchor' => '<table id="emsList_mnt_breakdown_intake"',
    'rows' => "ems_w14_guide_rows('mnt_breakdown_intake')",
    'grid_id' => 'emsList_mnt_breakdown_intake', 'empty' => 'لا سطر مسجل بعد في البلاغ الفني واستقبال العطل',
    'create' => true,
    'grain' => 'البلاغ الفني واستقبال العطل',
    'map' => array(
        'معرف الاستقبال' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'رقم البلاغ' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ البلاغ' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'المبلغ' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'وصف العطل' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'عقدة الشجرة المبدئية' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'درجة الخطورة' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'المعدة متوقفة؟' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'أثر الإيقاف' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'قرار الاستقبال' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'رقم طلب الفحص المتفرع' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الاستقبال' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'شدة العطل الفني' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'مدة التوقف' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
        'الأثر التشغيلي' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'قابلية المنع' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'التكرار' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'أداء الاستجابة' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
        'سبب التأخير' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'سلسلة المسؤولية' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'وقت توقف المعدة' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'وقت إبلاغ المشغل' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'وقت استلام الصيانة' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'وقت بدء التشخيص' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'وقت انتهاء التشخيص' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'وقت طلب القطعة' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'وقت توفر القطعة' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'وقت وصولها للموقع' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
        'وقت حضور الفني' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'وقت بدء الإصلاح' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'وقت انتهاء الإصلاح' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'وقت الاختبار' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'وقت التصديق' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'وقت عودة المعدة للخدمة' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'إجمالي التوقف' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'زمن الإصلاح الفعلي' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-03', 'route' => 'Maintenance/workshop.php',
    'table' => 'mnt_workshop',
    'anchor' => '<table id="emsList_mnt_workshop"',
    'rows' => "ems_w14_guide_rows('mnt_workshop')",
    'grid_id' => 'emsList_mnt_workshop', 'empty' => 'لا سطر مسجل بعد في الورش والفنيون',
    'create' => true,
    'grain' => 'الورش والفنيون',
    'map' => array(
        'كود القدرة' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'النوع' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'الاسم' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'الموقع' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'التخصصات' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'مستوى الفني' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'الشهادات وصلاحيتها' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'الطاقة اليومية (ساعات/أوامر)' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'متاح الآن؟' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
        'التبعية' => '+g52:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد عند الخارجي' => '+g53:VARCHAR(190) NULL DEFAULT NULL',
        'حالة القدرة' => '+g54:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g55:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g56:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g57:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g58:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-10', 'route' => 'maintenance/work_orders.php',
    'table' => 'mnt_work_orders',
    'anchor' => '<table id="emsList_mnt_work_orders"',
    'rows' => "ems_w14_guide_rows('mnt_work_orders')",
    'grid_id' => 'emsList_mnt_work_orders', 'empty' => 'لا سطر مسجل بعد في أمر العمل',
    'create' => true,
    'grain' => 'أمر العمل',
    'map' => array(
        'معرف البند' => '+g59:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g60:VARCHAR(190) NULL DEFAULT NULL',
        'تسلسل البند' => '+g61:VARCHAR(190) NULL DEFAULT NULL',
        'نوع البند' => '+g62:VARCHAR(190) NULL DEFAULT NULL',
        'كود الصنف' => '+g63:VARCHAR(190) NULL DEFAULT NULL',
        'الوصف' => '+g64:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المطلوبة' => '+g65:VARCHAR(190) NULL DEFAULT NULL',
        'الكمية المصروفة' => '+g66:VARCHAR(190) NULL DEFAULT NULL',
        'رقم سند الصرف' => '+g67:VARCHAR(190) NULL DEFAULT NULL',
        'جهة الخدمة الخارجية' => '+g68:VARCHAR(190) NULL DEFAULT NULL',
        'التكلفة' => '+g69:VARCHAR(190) NULL DEFAULT NULL',
        'ضمان مورد؟' => '+g70:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البند' => '+g71:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g72:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g73:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g74:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g75:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-13', 'route' => 'Maintenance/preventive_plans.php',
    'table' => 'mnt_preventive_plans',
    'anchor' => '<table id="emsList_mnt_preventive_plans"',
    'rows' => "ems_w14_guide_rows('mnt_preventive_plans')",
    'grid_id' => 'emsList_mnt_preventive_plans', 'empty' => 'لا سطر مسجل بعد في الخطة الوقائية بالساعات',
    'create' => true,
    'grain' => 'الخطة الوقائية بالساعات',
    'map' => array(
        'معرف السطر' => '+g76:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة' => '+g77:VARCHAR(190) NULL DEFAULT NULL',
        'نوع المعدة' => '+g78:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر الفاصل' => '+g79:VARCHAR(190) NULL DEFAULT NULL',
        'دورة الوقائية' => '+g80:VARCHAR(190) NULL DEFAULT NULL',
        'فاصل الأصل المخصص' => '+g81:VARCHAR(190) NULL DEFAULT NULL',
        'ساعات الدورة' => '+g82:VARCHAR(190) NULL DEFAULT NULL',
        'قراءة آخر وقائية' => '+g83:VARCHAR(190) NULL DEFAULT NULL',
        'قراءة العداد الحالية' => '+g84:VARCHAR(190) NULL DEFAULT NULL',
        'المتبقي للاستحقاق' => '+g85:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الاستحقاق المتوقع' => '+g86:VARCHAR(190) NULL DEFAULT NULL',
        'بنود الدورة القياسية' => '+g87:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الاستحقاق' => '+g88:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر المتولد' => '+g89:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g90:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g91:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g92:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g93:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-01', 'route' => 'Maintenance/dashboard_mnt.php',
    'table' => 'mnt_dashboard_kpi',
    'anchor' => '<table id="emsList_mnt_dashboard_kpi"',
    'rows' => "ems_w14_guide_rows('mnt_dashboard_kpi')",
    'grid_id' => 'emsList_mnt_dashboard_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة الصيانة والجاهزية',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة الصيانة والجاهزية',
    'map' => array(
        'معرف المؤشر' => '+g94:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر KPI Catalog' => '+g95:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g96:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة' => '+g97:VARCHAR(190) NULL DEFAULT NULL',
        'الحد المقبول' => '+g98:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g99:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g100:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-16', 'route' => 'Maintenance/repeat_repairs.php',
    'table' => 'mnt_repeat_repairs',
    'anchor' => '<table id="emsList_mnt_repeat_repairs"',
    'rows' => "ems_w14_guide_rows('mnt_repeat_repairs')",
    'grid_id' => 'emsList_mnt_repeat_repairs', 'empty' => 'لا سطر مسجل بعد في سجل إعادة الإصلاح',
    'create' => true,
    'grain' => 'سجل إعادة الإصلاح',
    'map' => array(
        'معرف الواقعة' => '+g101:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة' => '+g102:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر الأصلي' => '+g103:VARCHAR(190) NULL DEFAULT NULL',
        'عقدة الشجرة' => '+g104:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ التكرار' => '+g105:VARCHAR(190) NULL DEFAULT NULL',
        'المدة منذ الشهادة' => '+g106:VARCHAR(190) NULL DEFAULT NULL',
        'ضمن صلاحية الشهادة؟' => '+g107:VARCHAR(190) NULL DEFAULT NULL',
        'تحليل السبب الجذري RCA' => '+g108:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر الجديد' => '+g109:VARCHAR(190) NULL DEFAULT NULL',
        'محفز RCA' => '+g110:VARCHAR(190) NULL DEFAULT NULL',
        'القرار' => '+g111:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الواقعة' => '+g112:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g113:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g114:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g115:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g116:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-14', 'route' => 'Maintenance/daily_care.php',
    'table' => 'mnt_daily_care',
    'anchor' => '<table id="emsList_mnt_daily_care"',
    'rows' => "ems_w14_guide_rows('mnt_daily_care')",
    'grid_id' => 'emsList_mnt_daily_care', 'empty' => 'لا سطر مسجل بعد في العناية اليومية والتشحيم',
    'map' => array(
        'معرف السطر' => '+g117:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => '+g118:VARCHAR(190) NULL DEFAULT NULL',
        'كود المعدة' => '+g119:VARCHAR(190) NULL DEFAULT NULL',
        'قائمة العناية للنوع' => 'checklist_ref',
        'المهمة' => '+g120:VARCHAR(190) NULL DEFAULT NULL',
        'المنفذ' => '+g121:VARCHAR(190) NULL DEFAULT NULL',
        'النتيجة' => '+g122:VARCHAR(190) NULL DEFAULT NULL',
        'ملاحظة غير طبيعية' => '+g123:VARCHAR(190) NULL DEFAULT NULL',
        'بلاغ متفرع' => 'breakdown_id',
        'حالة السطر' => '+g124:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g125:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g126:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g127:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g128:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-17', 'route' => 'Maintenance/mnt_kpis.php',
    'table' => 'mnt_kpis',
    'anchor' => '<table id="emsList_mnt_kpis"',
    'rows' => "ems_w14_guide_rows('mnt_kpis')",
    'grid_id' => 'emsList_mnt_kpis', 'empty' => 'لا سطر مسجل بعد في مؤشرات الصيانة الدورية',
    'create' => true,
    'grain' => 'مؤشرات الصيانة الدورية',
    'map' => array(
        'معرف السطر' => '+g129:VARCHAR(190) NULL DEFAULT NULL',
        'الفترة' => '+g130:VARCHAR(190) NULL DEFAULT NULL',
        'النطاق' => '+g131:VARCHAR(190) NULL DEFAULT NULL',
        'المعدة/النوع' => '+g132:VARCHAR(190) NULL DEFAULT NULL',
        'عدد الأعطال' => '+g133:VARCHAR(190) NULL DEFAULT NULL',
        'متوسط الزمن بين الأعطال' => '+g134:VARCHAR(190) NULL DEFAULT NULL',
        'متوسط زمن الإصلاح' => '+g135:VARCHAR(190) NULL DEFAULT NULL',
        'نسبة الجاهزية' => '+g136:VARCHAR(190) NULL DEFAULT NULL',
        'أوامر الوقائية المنفذة' => '+g137:VARCHAR(190) NULL DEFAULT NULL',
        'الالتزام بالوقائية' => '+g138:VARCHAR(190) NULL DEFAULT NULL',
        'تكلفة الصيانة للساعة' => '+g139:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-11', 'route' => 'Maintenance/part_requests.php',
    'table' => 'mnt_part_requests',
    'anchor' => '<table id="emsList_mnt_part_requests"',
    'rows' => "ems_w14_guide_rows('mnt_part_requests')",
    'grid_id' => 'emsList_mnt_part_requests', 'empty' => 'لا سطر مسجل بعد في طلب صرف القطع لأمر العمل',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في طلب صرف القطع لأمر العمل',
    'map' => array(
        'رقم الطلب' => '+g140:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g141:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الطلب' => '+g142:VARCHAR(190) NULL DEFAULT NULL',
        'المخزن' => '+g143:VARCHAR(190) NULL DEFAULT NULL',
        'البنود المطلوبة' => '+g144:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية' => '+g145:VARCHAR(190) NULL DEFAULT NULL',
        'مستلم العهدة' => '+g146:VARCHAR(190) NULL DEFAULT NULL',
        'رقم سند الصرف' => '+g147:VARCHAR(190) NULL DEFAULT NULL',
        'مطابقة الاستلام' => '+g148:VARCHAR(190) NULL DEFAULT NULL',
        'حالة الطلب' => '+g149:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g150:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g151:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g152:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g153:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'MNT-12', 'route' => 'Maintenance/external_repairs.php',
    'table' => 'mnt_external_repairs',
    'anchor' => '<table id="emsList_mnt_external_repairs"',
    'rows' => "ems_w14_guide_rows('mnt_external_repairs')",
    'grid_id' => 'emsList_mnt_external_repairs', 'empty' => 'لا سطر مسجل بعد في الإصلاح الخارجي ومطالبات الضمان',
    'create' => true,
    'grain' => 'الإصلاح الخارجي ومطالبات الضمان',
    'map' => array(
        'معرف السطر' => '+g154:VARCHAR(190) NULL DEFAULT NULL',
        'رقم الأمر' => '+g155:VARCHAR(190) NULL DEFAULT NULL',
        'النوع' => '+g156:VARCHAR(190) NULL DEFAULT NULL',
        'الجهة الخارجية/المورد' => '+g157:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع العقد/الضمان' => '+g158:VARCHAR(190) NULL DEFAULT NULL',
        'نطاق العمل' => '+g159:VARCHAR(190) NULL DEFAULT NULL',
        'التكلفة المقدرة' => '+g160:VARCHAR(190) NULL DEFAULT NULL',
        'التكلفة الفعلية' => '+g161:VARCHAR(190) NULL DEFAULT NULL',
        'نتيجة المطالبة' => '+g162:VARCHAR(190) NULL DEFAULT NULL',
        'محضر الاستلام' => '+g163:VARCHAR(190) NULL DEFAULT NULL',
        'حالة السطر' => '+g164:VARCHAR(190) NULL DEFAULT NULL',
        'المنشئ' => '+g165:VARCHAR(190) NULL DEFAULT NULL',
        'تاريخ الإنشاء' => '+g166:VARCHAR(190) NULL DEFAULT NULL',
        'حالة البيانات' => '+g167:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع المصدر' => '+g168:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
