<?php
/**
 * fields_exdvp.php — مواصفةٌ مولَّدةٌ من `tools/govui_field_map_probe.php`
 * ◆ الخريطةُ من **تعليقاتِ أعمدةِ المخطَّطِ نفسِها** لا من نسخٍ بيد.
 * ⛔ وتُراجَع قبل التطبيق: عمودٌ اقتُرح بتغطيةٍ جزئيّةٍ قد يخطئ الحقل.
 */
return array(

'dept' => 'EX-DVP',
'screens' => array(

array(
    'req' => 'VP-03', 'route' => 'Portal/vp_daily_report.php',
    'table' => 'exec_daily_report',
    'anchor' => '<table id="emsList_vp_daily_report"',
    'rows' => "ems_w14_guide_rows('exec_daily_report')",
    'grid_id' => 'emsList_vp_daily_report', 'empty' => 'لا سطر مسجل بعد في التقرير اليومي للنائب',
    'map' => array(
        'معرف السطر' => 'g35',
        'Deputy_Role' => '+g1:VARCHAR(190) NULL DEFAULT NULL',
        'ضمن Scope؟' => '+g2:VARCHAR(190) NULL DEFAULT NULL',
        'التاريخ' => 'g36',
        'المشروع' => 'g37',
        'الموقع' => 'g38',
        'الخطة اليومية' => 'g39',
        'المنفذ' => 'g40',
        'نسبة الإنجاز' => 'g41',
        'ساعات تشغيل المعدات' => 'g42',
        'إجمالي ساعات التوقف' => 'g43',
        'عدد أنواع التوقف تفصيلها ر03-2' => 'g44',
        'المعدات العاملة' => 'g45',
        'المعدات المتوقفة' => 'g46',
        'الأعطال الحرجة' => 'g47',
        'القوى الموجودة' => 'g48',
        'النقص' => 'g49',
        'إصابات مضيعة للوقت LTI' => 'g50',
        'حوادث عالية الجهد HiPo' => 'g51',
        'أحداث إيقاف العمل Stop-Work' => 'g52',
        'الحوادث البيئية' => 'g53',
        'البلاغات الحرجة' => 'g54',
        'الترحيلات المهمة' => 'g55',
        'المواد الحرجة' => 'g56',
        'عدد القرارات المطلوبة تفصيلها ر03-3' => 'g57',
        'عدد الانحرافات الحرجة تفصيلها ر03-3' => 'g58',
        'رابط النزول للسجل الأصلي' => 'g59',
    ),
),

array(
    'req' => 'VP-06', 'route' => 'Portal/vp_approval_inbox.php',
    'table' => 'exec_request_queue',
    'anchor' => '<table id="emsList_exec_request_queue"',
    'rows' => "ems_w14_guide_rows('exec_request_queue')",
    'grid_id' => 'emsList_exec_request_queue', 'empty' => 'لا سطر مسجل بعد في صندوق اعتمادات النائب',
    'map' => array(
        'Request_ID' => 'g108',
        'Source_Department' => 'g109',
        'Request_Type' => 'g111',
        'Deputy_Role' => '+g3:VARCHAR(190) NULL DEFAULT NULL',
        'Approval_Scope' => '+g4:VARCHAR(190) NULL DEFAULT NULL',
        'Amount' => 'g115',
        'Currency' => 'g116',
        'Previous_Approval' => 'g120',
        'Recommendation' => 'g127',
        'Documents' => 'g126',
        'Risk' => 'g119',
        'Status' => '+g5:VARCHAR(190) NULL DEFAULT NULL',
        'Deputy_Decision' => '+g6:VARCHAR(190) NULL DEFAULT NULL',
        'Conditions' => 'g129',
        'Decision_Date' => 'g130',
        'المنشئ' => 'g131',
        'تاريخ الإنشاء' => 'g132',
        'حالة البيانات' => 'g133',
        'مرجع المصدر' => 'g134',
    ),
),

array(
    'req' => 'VP-11', 'route' => 'Portal/vp_actions_followup.php',
    'table' => 'exec_action_followup',
    'anchor' => '<table id="emsList_exec_action_followup"',
    'rows' => "ems_w14_guide_rows('exec_action_followup')",
    'grid_id' => 'emsList_exec_action_followup', 'empty' => 'لا سطر مسجل بعد في متابعة قرارات النائب',
    'map' => array(
        'Action_ID' => 'g355',
        'Deputy_Role' => '+g7:VARCHAR(190) NULL DEFAULT NULL',
        'مصدر القرار' => 'g356',
        'الموضوع' => 'g358',
        'الإدارة' => 'g359',
        'المسؤول' => 'g360',
        'Due_Date' => 'g361',
        'Priority' => 'g362',
        'Status' => 'g363',
        'أيام التأخير' => 'g364',
        'Evidence' => 'g365',
        'Closure' => 'g366',
    ),
),

array(
    'req' => 'VP-02', 'route' => 'Portal/vp_departments.php',
    'table' => 'exec_org_project',
    'anchor' => '<table id="emsList_exec_org_project"',
    'rows' => "ems_w14_guide_rows('exec_org_project')",
    'grid_id' => 'emsList_exec_org_project', 'empty' => 'لا سطر مسجل بعد في الإدارات — نطاقي والشركة',
    'map' => array(
        'معرف البطاقة' => 'g17',
        'وضع العرض' => '+g8:VARCHAR(190) NULL DEFAULT NULL',
        'Deputy_Role' => '+g9:VARCHAR(190) NULL DEFAULT NULL',
        'الإدارة' => '+g10:VARCHAR(190) NULL DEFAULT NULL',
        'التبعية التنظيمية' => 'g21',
        'ضمن نطاقي؟' => '+g11:VARCHAR(190) NULL DEFAULT NULL',
        'خارج النطاق قراءة فقط' => '+g12:VARCHAR(190) NULL DEFAULT NULL',
        'KPI' => 'g24',
        'Pending_Requests' => '+g13:VARCHAR(190) NULL DEFAULT NULL',
        'Overdue_Actions' => 'g28',
        'Critical_Risks' => '+g14:VARCHAR(190) NULL DEFAULT NULL',
        'Budget_Status' => 'g29',
        'Daily_Report_Status' => 'g31',
        'Monthly_Close_Status' => 'g33',
        'Compliance_Status' => 'g30',
        'رابط النزول' => 'g34',
    ),
),

array(
    'req' => 'VP-04', 'route' => 'Portal/vp_weekly_report.php',
    'table' => 'exec_weekly_report',
    'anchor' => '<table id="emsList_vp_weekly_report"',
    'rows' => "ems_w14_guide_rows('exec_weekly_report')",
    'grid_id' => 'emsList_vp_weekly_report', 'empty' => 'لا سطر مسجل بعد في مراجعة الأداء الأسبوعية',
    'map' => array(
        'معرف السطر' => 'g80',
        'Deputy_Role' => '+g15:VARCHAR(190) NULL DEFAULT NULL',
        'الأسبوع' => 'g81',
        'المحور' => 'g82',
        'المؤشر' => 'g83',
        'هذا الأسبوع' => 'g84',
        'السابق' => 'g85',
        'المستهدف' => 'g86',
        'الانحراف' => 'g87',
        'الاتجاه' => 'g88',
        'توقع الأسبوع القادم' => 'g89',
        'Deputy_Action المتفرع' => '+g16:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'VP-05', 'route' => 'Portal/vp_monthly_review.php',
    'table' => 'exec_monthly_pack',
    'anchor' => '<table id="emsList_vp_monthly_review"',
    'rows' => "ems_w14_guide_rows('exec_monthly_pack')",
    'grid_id' => 'emsList_vp_monthly_review', 'empty' => 'لا سطر مسجل بعد في المراجعة الشهرية للنائب',
    'map' => array(
        'معرف السطر' => 'g93',
        'Deputy_Role' => '+g17:VARCHAR(190) NULL DEFAULT NULL',
        'الشهر' => 'g94',
        'المحور' => 'g95',
        'البند' => 'g96',
        'الفعلي' => 'g97',
        'المستهدف' => 'g98',
        'الانحراف' => 'g99',
        'توقع الشهر الكامل' => 'g101',
        'مراجعة النائب Decision Event' => '+g18:VARCHAR(190) NULL DEFAULT NULL',
        'اكتملت المراجعة؟' => '+g19:VARCHAR(190) NULL DEFAULT NULL',
        'انعكس في حزمة الرئيس' => '+g20:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'VP-12', 'route' => 'Portal/exec_delegations.php',
    'table' => 'dvp_delegations',
    'anchor' => '<table id="emsList_exec_delegations"',
    'rows' => "ems_w14_guide_rows('dvp_delegations')",
    'grid_id' => 'emsList_exec_delegations', 'empty' => 'لا سطر مسجل بعد في الإنابات والتفويضات',
    'create' => true,
    'grain' => 'الإنابات والتفويضات',
    'map' => array(
        'Delegation_ID' => '+g21:VARCHAR(190) NULL DEFAULT NULL',
        'Delegate_From' => '+g22:VARCHAR(190) NULL DEFAULT NULL',
        'Delegate_To' => '+g23:VARCHAR(190) NULL DEFAULT NULL',
        'Scope' => '+g24:VARCHAR(190) NULL DEFAULT NULL',
        'From_Date' => '+g25:VARCHAR(190) NULL DEFAULT NULL',
        'To_Date' => '+g26:VARCHAR(190) NULL DEFAULT NULL',
        'Approval_Level' => '+g27:VARCHAR(190) NULL DEFAULT NULL',
        'Exclusions' => '+g28:VARCHAR(190) NULL DEFAULT NULL',
        'Status' => '+g29:VARCHAR(190) NULL DEFAULT NULL',
        'مرجع سجل الحوكمة' => '+g30:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'VP-10', 'route' => 'Portal/vp_pending_actions.php',
    'table' => 'dvp_vp_pending_actions',
    'anchor' => '<table id="emsList_dvp_vp_pending_actions"',
    'rows' => "ems_w14_guide_rows('dvp_vp_pending_actions')",
    'grid_id' => 'emsList_dvp_vp_pending_actions', 'empty' => 'لا سطر مسجل بعد في الإجراءات والقرارات المطلوبة مني',
    'create' => true,
    'grain' => 'الإجراءات والقرارات المطلوبة مني',
    'map' => array(
        'معرف البند' => '+g31:VARCHAR(190) NULL DEFAULT NULL',
        'Deputy_Role' => '+g32:VARCHAR(190) NULL DEFAULT NULL',
        'المصدر' => '+g33:VARCHAR(190) NULL DEFAULT NULL',
        'نوع الفعل' => '+g34:VARCHAR(190) NULL DEFAULT NULL',
        'المرجع' => '+g35:VARCHAR(190) NULL DEFAULT NULL',
        'المهلة' => '+g36:VARCHAR(190) NULL DEFAULT NULL',
        'أيام التأخير' => '+g37:VARCHAR(190) NULL DEFAULT NULL',
        'الأولوية' => '+g38:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g39:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

array(
    'req' => 'VP-01', 'route' => 'Portal/vp_dashboard.php',
    'table' => 'dvp_dashboard_kpi',
    'anchor' => '<table id="emsList_dvp_dashboard_kpi"',
    'rows' => "ems_w14_guide_rows('dvp_dashboard_kpi')",
    'grid_id' => 'emsList_dvp_dashboard_kpi', 'empty' => 'لا سطر مسجل بعد في لوحة النائب',
    'create' => true,
    'grain' => 'لا سطر مسجل بعد في لوحة النائب',
    'map' => array(
        'معرف المؤشر' => '+g40:VARCHAR(190) NULL DEFAULT NULL',
        'Deputy_Role' => '+g41:VARCHAR(190) NULL DEFAULT NULL',
        'المحور' => '+g42:VARCHAR(190) NULL DEFAULT NULL',
        'ضمن Default Scope؟' => '+g43:VARCHAR(190) NULL DEFAULT NULL',
        'المؤشر' => '+g44:VARCHAR(190) NULL DEFAULT NULL',
        'القيمة' => '+g45:VARCHAR(190) NULL DEFAULT NULL',
        'الوحدة/العملة' => '+g46:VARCHAR(190) NULL DEFAULT NULL',
        'المستهدف' => '+g47:VARCHAR(190) NULL DEFAULT NULL',
        'الانحراف' => '+g48:VARCHAR(190) NULL DEFAULT NULL',
        'الحالة' => '+g49:VARCHAR(190) NULL DEFAULT NULL',
        'رابط النزول' => '+g50:VARCHAR(190) NULL DEFAULT NULL',
        'آخر تحديث' => '+g51:VARCHAR(190) NULL DEFAULT NULL',
    ),
),

),
);
