-- نسخةُ ما قبل التهيئة — 2026-07-29 10:28:26

UPDATE equipment_documents SET expiry_date='1980-03-25', status='منتهية' WHERE doc_id=1;
UPDATE equipment_documents SET expiry_date='1989-06-19', status='منتهية' WHERE doc_id=2;
UPDATE equipment_documents SET expiry_date='2025-09-11', status='منتهية' WHERE doc_id=3;
UPDATE equipment_documents SET expiry_date='2022-06-13', status='منتهية' WHERE doc_id=4;
UPDATE equipment_documents SET expiry_date='2019-11-23', status='منتهية' WHERE doc_id=5;
UPDATE equipment_documents SET expiry_date='2022-10-14', status='منتهية' WHERE doc_id=6;
UPDATE equipment_documents SET expiry_date='0001-01-01', status='منتهية' WHERE doc_id=7;
UPDATE equipment_documents SET expiry_date='0001-01-01', status='منتهية' WHERE doc_id=8;
UPDATE equipment_documents SET expiry_date='0001-01-01', status='منتهية' WHERE doc_id=9;
UPDATE equipment_documents SET expiry_date=NULL, status='سارية' WHERE doc_id=10;
UPDATE equipment_documents SET expiry_date='2026-05-01', status='منتهية' WHERE doc_id=11;
UPDATE equipment_documents SET expiry_date='2026-05-07', status='منتهية' WHERE doc_id=12;
UPDATE equipment_documents SET expiry_date='2025-12-31', status='منتهية' WHERE doc_id=13;
UPDATE equipment_documents SET expiry_date='2007-11-30', status='منتهية' WHERE doc_id=16;
UPDATE equipment_documents SET expiry_date='2002-05-10', status='منتهية' WHERE doc_id=17;
UPDATE equipment_documents SET expiry_date='1981-02-24', status='منتهية' WHERE doc_id=18;
UPDATE equipment_documents SET expiry_date='2021-11-25', status='منتهية' WHERE doc_id=19;
UPDATE equipment_documents SET expiry_date='2000-06-04', status='منتهية' WHERE doc_id=20;
UPDATE equipment_documents SET expiry_date='1989-04-14', status='منتهية' WHERE doc_id=21;
UPDATE equipment_documents SET expiry_date='1978-05-27', status='منتهية' WHERE doc_id=22;
UPDATE equipment_documents SET expiry_date='2010-11-17', status='منتهية' WHERE doc_id=23;
UPDATE equipment_documents SET expiry_date='2009-10-06', status='منتهية' WHERE doc_id=24;
UPDATE equipment_documents SET expiry_date='1996-09-28', status='منتهية' WHERE doc_id=25;
UPDATE equipment_documents SET expiry_date='2018-04-20', status='منتهية' WHERE doc_id=26;
UPDATE equipment_documents SET expiry_date='1972-09-05', status='منتهية' WHERE doc_id=27;
UPDATE equipment_documents SET expiry_date='2008-01-15', status='منتهية' WHERE doc_id=28;
UPDATE equipment_documents SET expiry_date='2013-09-28', status='منتهية' WHERE doc_id=29;
UPDATE equipment_documents SET expiry_date='2012-10-17', status='منتهية' WHERE doc_id=30;
UPDATE equipment_documents SET expiry_date='1983-04-25', status='منتهية' WHERE doc_id=31;
UPDATE equipment_documents SET expiry_date='1977-11-21', status='منتهية' WHERE doc_id=32;
UPDATE equipment_documents SET expiry_date='2024-01-06', status='منتهية' WHERE doc_id=33;
UPDATE equipment_documents SET expiry_date='2021-01-18', status='منتهية' WHERE doc_id=34;
UPDATE equipment_documents SET expiry_date='1987-07-27', status='منتهية' WHERE doc_id=35;
UPDATE equipment_documents SET expiry_date='1982-06-13', status='منتهية' WHERE doc_id=36;
UPDATE equipment_documents SET expiry_date='2002-07-04', status='منتهية' WHERE doc_id=37;
UPDATE equipment_documents SET expiry_date='2026-05-03', status='منتهية' WHERE doc_id=38;
UPDATE equipment_documents SET expiry_date='2026-05-03', status='منتهية' WHERE doc_id=39;
UPDATE equipment_documents SET expiry_date='2026-05-03', status='منتهية' WHERE doc_id=40;
UPDATE equipment_documents SET expiry_date='2027-01-01', status='سارية' WHERE doc_id=41;
UPDATE `equipment_operators` SET `license_expiry_date`='2007-11-30' WHERE `employee_id`=1;
UPDATE `equipment_operators` SET `license_expiry_date`='2002-05-10' WHERE `employee_id`=2;
UPDATE `equipment_operators` SET `license_expiry_date`='1981-02-24' WHERE `employee_id`=3;
UPDATE `equipment_operators` SET `license_expiry_date`='2021-11-25' WHERE `employee_id`=4;
UPDATE `equipment_operators` SET `license_expiry_date`='2000-06-04' WHERE `employee_id`=5;
UPDATE `equipment_operators` SET `license_expiry_date`='1989-04-14' WHERE `employee_id`=6;
UPDATE `equipment_operators` SET `license_expiry_date`='1978-05-27' WHERE `employee_id`=7;
UPDATE `equipment_operators` SET `license_expiry_date`='2010-11-17' WHERE `employee_id`=8;
UPDATE `equipment_operators` SET `license_expiry_date`='2009-10-06' WHERE `employee_id`=9;
UPDATE `equipment_operators` SET `license_expiry_date`='1996-09-28' WHERE `employee_id`=10;
UPDATE `equipment_operators` SET `license_expiry_date`='2018-04-20' WHERE `employee_id`=11;
UPDATE `equipment_operators` SET `license_expiry_date`='1972-09-05' WHERE `employee_id`=12;
UPDATE `equipment_operators` SET `license_expiry_date`='2008-01-15' WHERE `employee_id`=13;
UPDATE `equipment_operators` SET `license_expiry_date`='2013-09-28' WHERE `employee_id`=14;
UPDATE `equipment_operators` SET `license_expiry_date`='2012-10-17' WHERE `employee_id`=15;
UPDATE `equipment_operators` SET `license_expiry_date`='1983-04-25' WHERE `employee_id`=16;
UPDATE `equipment_operators` SET `license_expiry_date`='1977-11-21' WHERE `employee_id`=17;
UPDATE `equipment_operators` SET `license_expiry_date`='2024-01-06' WHERE `employee_id`=18;
UPDATE `equipment_operators` SET `license_expiry_date`='2021-01-18' WHERE `employee_id`=19;
UPDATE `equipment_operators` SET `license_expiry_date`='1987-07-27' WHERE `employee_id`=20;
UPDATE `equipment_operators` SET `license_expiry_date`='1982-06-13' WHERE `employee_id`=21;
UPDATE `equipment_operators` SET `license_expiry_date`='2002-07-04' WHERE `employee_id`=22;
UPDATE `equipment_operators` SET `license_expiry_date`='2026-05-03' WHERE `employee_id`=23;
UPDATE `equipment_operators` SET `license_expiry_date`='2026-05-03' WHERE `employee_id`=24;
UPDATE `equipment_operators` SET `license_expiry_date`='2026-05-03' WHERE `employee_id`=25;
UPDATE `equipment_operators` SET `license_expiry_date`='2027-01-01' WHERE `employee_id`=26;
UPDATE `equipment_operators` SET `license_expiry_date`=NULL WHERE `employee_id`=54;
UPDATE `equipment_operators` SET `license_expiry_date`=NULL WHERE `employee_id`=55;
UPDATE `equipment_operators` SET `license_expiry_date`=NULL WHERE `employee_id`=56;
UPDATE `equipment_operators` SET `license_expiry_date`=NULL WHERE `employee_id`=57;
UPDATE `employees` SET `license_expiry_date`='2007-11-30' WHERE `id`=1;
UPDATE `employees` SET `license_expiry_date`='2002-05-10' WHERE `id`=2;
UPDATE `employees` SET `license_expiry_date`='1981-02-24' WHERE `id`=3;
UPDATE `employees` SET `license_expiry_date`='2021-11-25' WHERE `id`=4;
UPDATE `employees` SET `license_expiry_date`='2000-06-04' WHERE `id`=5;
UPDATE `employees` SET `license_expiry_date`='1989-04-14' WHERE `id`=6;
UPDATE `employees` SET `license_expiry_date`='1978-05-27' WHERE `id`=7;
UPDATE `employees` SET `license_expiry_date`='2010-11-17' WHERE `id`=8;
UPDATE `employees` SET `license_expiry_date`='2009-10-06' WHERE `id`=9;
UPDATE `employees` SET `license_expiry_date`='1996-09-28' WHERE `id`=10;
UPDATE `employees` SET `license_expiry_date`='2018-04-20' WHERE `id`=11;
UPDATE `employees` SET `license_expiry_date`='1972-09-05' WHERE `id`=12;
UPDATE `employees` SET `license_expiry_date`='2008-01-15' WHERE `id`=13;
UPDATE `employees` SET `license_expiry_date`='2013-09-28' WHERE `id`=14;
UPDATE `employees` SET `license_expiry_date`='2012-10-17' WHERE `id`=15;
UPDATE `employees` SET `license_expiry_date`='1983-04-25' WHERE `id`=16;
UPDATE `employees` SET `license_expiry_date`='1977-11-21' WHERE `id`=17;
UPDATE `employees` SET `license_expiry_date`='2024-01-06' WHERE `id`=18;
UPDATE `employees` SET `license_expiry_date`='2021-01-18' WHERE `id`=19;
UPDATE `employees` SET `license_expiry_date`='1987-07-27' WHERE `id`=20;
UPDATE `employees` SET `license_expiry_date`='1982-06-13' WHERE `id`=21;
UPDATE `employees` SET `license_expiry_date`='2002-07-04' WHERE `id`=22;
UPDATE `employees` SET `license_expiry_date`='2026-05-03' WHERE `id`=23;
UPDATE `employees` SET `license_expiry_date`='2026-05-03' WHERE `id`=24;
UPDATE `employees` SET `license_expiry_date`='2026-05-03' WHERE `id`=25;
UPDATE `employees` SET `license_expiry_date`='2027-01-01' WHERE `id`=26;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=27;
UPDATE `employees` SET `license_expiry_date`='2016-02-09' WHERE `id`=28;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=34;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=35;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=36;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=37;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=38;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=39;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=40;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=41;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=42;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=43;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=44;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=45;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=46;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=47;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=48;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=49;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=50;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=51;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=52;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=53;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=54;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=55;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=56;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=57;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=58;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=59;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=60;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=61;
UPDATE `employees` SET `license_expiry_date`=NULL WHERE `id`=62;
UPDATE `equipments` SET `license_expiry_date`='1980-03-25' WHERE `id`=1;
UPDATE `equipments` SET `license_expiry_date`='1989-06-19' WHERE `id`=2;
UPDATE `equipments` SET `license_expiry_date`='2025-09-11' WHERE `id`=3;
UPDATE `equipments` SET `license_expiry_date`='2022-06-13' WHERE `id`=4;
UPDATE `equipments` SET `license_expiry_date`='2019-11-23' WHERE `id`=5;
UPDATE `equipments` SET `license_expiry_date`='2022-10-14' WHERE `id`=6;
UPDATE `equipments` SET `license_expiry_date`='0001-01-01' WHERE `id`=7;
UPDATE `equipments` SET `license_expiry_date`='0001-01-01' WHERE `id`=8;
UPDATE `equipments` SET `license_expiry_date`='0001-01-01' WHERE `id`=9;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=10;
UPDATE `equipments` SET `license_expiry_date`='2026-05-01' WHERE `id`=11;
UPDATE `equipments` SET `license_expiry_date`='2026-05-07' WHERE `id`=12;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=13;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=14;
UPDATE `equipments` SET `license_expiry_date`='2025-12-31' WHERE `id`=18;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=19;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=20;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=21;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=22;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=23;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=24;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=25;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=26;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=71;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=72;
UPDATE `equipments` SET `license_expiry_date`=NULL WHERE `id`=281;
