#!/bin/bash
# سكريبت التثبيت والإعداد لميزة إيقاف المشغلين والآليات

echo "=================================="
echo "إعداد نظام الموافقات لإيقاف المشغلين والآليات"
echo "=================================="
echo ""

echo "✓ تم إضافة الملفات التالية:"
echo "  1. Drivers/deactivate_driver_handler.php - معالج طلب إيقاف المشغل"
echo "  2. Drivers/deactivate_driver_modals.html - نماذج UI لإيقاف المشغل"
echo "  3. Equipments/deactivate_equipment_handler.php - معالج طلب إيقاف الآلية"  
echo "  4. Equipments/deactivate_equipment_modals.html - نماذج UI لإيقاف الآلية"
echo ""

echo "✓ تم تحديث الملفات التالية:"
echo "  1. sidebar.php - إضافة روابط 'طلبات الموافقات' لـ Role 3 و 4"
echo "  2. database/approval_workflow.sql - إضافة قواعد الموافقة الجديدة"
echo ""

echo "📋 الخطوات التالية يجب أن تُنفذ يدويًا:"
echo ""
echo "1️⃣ تحديث Drivers/drivers.php:"
echo "   - أضف: <?php include 'deactivate_driver_modals.html'; ?> في النهاية"
echo "   - أضف أزرار في جدول المشغلين:"
echo "     <button class='btn btn-warning deactivateDriverBtn' "
echo "             data-id='<?php echo \$driver[\"id\"]; ?>'"
echo "             data-name='<?php echo \$driver[\"name\"]; ?>'"
echo "             data-code='<?php echo \$driver[\"driver_code\"]; ?>'"  
echo "             data-status='<?php echo \$driver[\"driver_status\"]; ?>'>"
echo "        <i class='fas fa-ban'></i> إيقاف"
echo "     </button>"
echo ""

echo "2️⃣ تحديث Equipments/equipments.php:"
echo "   - أضف: <?php include 'deactivate_equipment_modals.html'; ?> في النهاية"
echo "   - أضف أزرار في جدول الآليات:"
echo "     <button class='btn btn-warning deactivateEquipmentBtn'"
echo "             data-id='<?php echo \$equipment[\"id\"]; ?>'"
echo "             data-code='<?php echo \$equipment[\"code\"]; ?>'"
echo "             data-name='<?php echo \$equipment[\"name\"]; ?>'"
echo "             data-status='<?php echo \$equipment[\"availability_status\"]; ?>'>"
echo "        <i class='fas fa-ban'></i> إيقاف"
echo "     </button>"
echo ""

echo "3️⃣ تشغيل SQL الجديد (في قاعدة البيانات):"
echo "   - انسخ محتوى database/approval_workflow.sql"
echo "   - أو شغل setup_approval_workflow.php"
echo ""

echo "✅ المتطلبات:"
echo "   - يجب أن تكون هناك طاولات approval_requests و approval_steps"
echo "   - يجب أن تكون approval_workflow.php موجودة في includes/"
echo ""

echo "📞 الأدوار المسؤولة:"
echo "   - مدير الحركة والتشغيل (Role 10): يقدم طلبات الإيقاف"
echo "   - مدير المشغلين (Role 3): يوافق على إيقاف المشغلين"
echo "   - مدير الأسطول (Role 4): يوافق على إيقاف الآليات"
echo ""

echo "=================================="
echo "تم الإعداد بنجاح ✓"
echo "=================================="
