-- إعادة التسمية النصية (مصفوفة دليل تجربة المستخدم) — 2026-07-24 11:00
-- كل UPDATE محروسٌ بالاسم القديم: صفر تطابق = صفر تعديل (يُكشف في التحقق).
START TRANSACTION;
UPDATE `modules` SET `name`='سجل النشاط' WHERE `id`=12 AND `name`='سجل النشاطات';
UPDATE `modules` SET `name`='أنشطة العملاء' WHERE `id`=77 AND `name`='الأنشطة التجارية';
UPDATE `modules` SET `name`='العملاء' WHERE `id`=1 AND `name`='حالة العملاء';
UPDATE `modules` SET `name`='العملاء' WHERE `id`=35 AND `name`='إدارة العملاء';
UPDATE `modules` SET `name`='ملاحق العقود وتجديداتها' WHERE `id`=84 AND `name`='الملاحق والتجديدات';
UPDATE `modules` SET `name`='التزامات العقود' WHERE `id`=127 AND `name`='التزامات العقد';
UPDATE `modules` SET `name`='سجل حركة العقد' WHERE `id`=85 AND `name`='سجل الأحداث التعاقدية';
UPDATE `modules` SET `name`='قوائم ونماذج التسعير' WHERE `id`=81 AND `name`='نماذج التسعير';
UPDATE `modules` SET `name`='كتالوج المنتجات والخدمات' WHERE `id`=82 AND `name`='المنتجات والخدمات';
UPDATE `modules` SET `name`='عروض الأسعار' WHERE `id`=80 AND `name`='العروض';
UPDATE `modules` SET `name`='جاهزية العروض' WHERE `id`=129 AND `name`='فحص الجاهزية';
UPDATE `modules` SET `name`='العقود' WHERE `id`=20 AND `name`='إدارة العقود';
UPDATE `modules` SET `name`='العقود' WHERE `id`=37 AND `name`='إدارة العقود';
UPDATE `modules` SET `name`='ملف عقد المشروع' WHERE `id`=21 AND `name`='تفاصيل عقد المشاريع';
UPDATE `modules` SET `name`='ملف عقد الموظف' WHERE `id`=63 AND `name`='تفاصيل عقد الموظف';
UPDATE `modules` SET `name`='الأدوار الوظيفية' WHERE `id`=58 AND `name`='أدوار الموظفين';
UPDATE `modules` SET `name`='الموظفون' WHERE `id`=7 AND `name`='علاقات الموظفين';
UPDATE `modules` SET `name`='المشغّلون والسائقون' WHERE `id`=59 AND `name`='السائقون والمشغّلون';
UPDATE `modules` SET `name`='المعدات' WHERE `id`=8 AND `name`='إدارة المعدات';
UPDATE `modules` SET `name`='أنواع المعدات' WHERE `id`=5 AND `name`='شاشة انواع المعدات';
UPDATE `modules` SET `name`='إعداد الإهلاك' WHERE `id`=41 AND `name`='ملف الإهلاك المالي';
UPDATE `modules` SET `name`='الأنواع والموديلات' WHERE `id`=40 AND `name`='سجل النوع والموديل';
UPDATE `modules` SET `name`='تصنيفات الأعطال' WHERE `id`=38 AND `name`='تصنيف الاعطال';
UPDATE `modules` SET `name`='مكتب المحاسب' WHERE `id`=117 AND `name`='مكتب محاسب الإدارة';
UPDATE `modules` SET `name`='زمن دورة الطلبات' WHERE `id`=121 AND `name`='لوحة زمن الدورة';
UPDATE `modules` SET `name`='موافقات إدارتي' WHERE `id`=116 AND `name`='صندوق طلبات الإدارة';
UPDATE `modules` SET `name`='سجل الحركة المالية' WHERE `id`=119 AND `name`='خريطة تفريع الأثر';
UPDATE `modules` SET `name`='الطلبات المالية' WHERE `id`=118 AND `name`='بوابة الطلبات المالية';
UPDATE `modules` SET `name`='قواعد توجيه الطلبات' WHERE `id`=120 AND `name`='توجيه الطلبات المالية';
UPDATE `modules` SET `name`='الأصول والإهلاك' WHERE `id`=101 AND `name`='الأصول الثابتة والإهلاك';
UPDATE `modules` SET `name`='الميزانية والانحراف' WHERE `id`=89 AND `name`='الميزانيات والانحراف';
UPDATE `modules` SET `name`='لوحة المدير المالي' WHERE `id`=104 AND `name`='لوحة المدير المالي اليومية';
UPDATE `modules` SET `name`='الذمم والتحصيل' WHERE `id`=90 AND `name`='الذمم والمستحقات';
UPDATE `modules` SET `name`='المعاملات المالية' WHERE `id`=86 AND `name`='الأحداث المالية';
UPDATE `modules` SET `name`='استقبال معاملات الإدارات' WHERE `id`=98 AND `name`='استيراد أحداث الإدارات';
UPDATE `modules` SET `name`='القيود اليومية' WHERE `id`=88 AND `name`='القيود المالية';
UPDATE `modules` SET `name`='قواعد مخصص الصيانة' WHERE `id`=126 AND `name`='مخصّص الصيانة (المروحة)';
UPDATE `modules` SET `name`='قواعد مستحقات المشغّلين' WHERE `id`=128 AND `name`='مستحق المشغّل (المروحة)';
UPDATE `modules` SET `name`='إقفال الفترات' WHERE `id`=93 AND `name`='الفترات والإقفال';
UPDATE `modules` SET `name`='الضرائب والقيمة المضافة' WHERE `id`=102 AND `name`='الضرائب / القيمة المضافة';
UPDATE `modules` SET `name`='مطابقة الوحدات اليومية' WHERE `id`=105 AND `name`='كشف الوحدات والتطابق';
UPDATE `modules` SET `name`='متابعة الانحراف' WHERE `id`=125 AND `name`='مراقبة الانحراف والمعالجة';
UPDATE `modules` SET `name`='الفحص الفني اليومي' WHERE `id`=44 AND `name`='التفتيش الفني';
UPDATE `modules` SET `name`='الصيانة الوقائية' WHERE `id`=45 AND `name`='الخطة الوقائية';
UPDATE `modules` SET `name`='الفرص البيعية' WHERE `id`=66 AND `name`='مسار الفرص';
UPDATE `modules` SET `name`='صرف المخزون والعهدة' WHERE `id`=73 AND `name`='الصرف والعهدة';
UPDATE `modules` SET `name`='البيانات المرجعية' WHERE `id`=76 AND `name`='بيانات مرجعية';
UPDATE `modules` SET `name`='الاستلام المؤقت' WHERE `id`=71 AND `name`='عهدة الاستلام المؤقت';
UPDATE `modules` SET `name`='حدود إعادة الطلب' WHERE `id`=74 AND `name`='قواعد إعادة الطلب';
UPDATE `modules` SET `name`='المخزون' WHERE `id`=72 AND `name`='المخزون التشغيلي';
UPDATE `modules` SET `name`='موردو المشتريات' WHERE `id`=75 AND `name`='الموردون التشغيليون';
UPDATE `modules` SET `name`='المشاريع' WHERE `id`=2 AND `name`='حالة المشاريع';
UPDATE `modules` SET `name`='المشاريع' WHERE `id`=36 AND `name`='إدارة المبيعات';
UPDATE `modules` SET `name`='مركز التقارير' WHERE `id`=4 AND `name`='شاشة التقارير';
UPDATE `modules` SET `name`='مركز التقارير' WHERE `id`=6 AND `name`='شاشة التقارير';
UPDATE `modules` SET `name`='مركز التقارير' WHERE `id`=28 AND `name`='التقارير';
UPDATE `modules` SET `name`='مركز التقارير' WHERE `id`=31 AND `name`='التقارير';
UPDATE `modules` SET `name`='مركز التقارير' WHERE `id`=32 AND `name`='التقارير';
UPDATE `modules` SET `name`='صلاحيات الأدوار' WHERE `id`=123 AND `name`='إدارة صلاحيات الأدوار';
UPDATE `modules` SET `name`='الأدوار' WHERE `id`=124 AND `name`='إدارة الأدوار';
UPDATE `modules` SET `name`='الموردون' WHERE `id`=22 AND `name`='علاقات الموردين';
UPDATE `modules` SET `name`='ملف عقد المورد' WHERE `id`=26 AND `name`='تفاصيل عقد المورد';
UPDATE `modules` SET `name`='تصنيفات الأعطال والبلاغات' WHERE `id`=131 AND `name`='التصنيف الفنّي للبلاغات';
UPDATE `modules` SET `name`='أداء البلاغات' WHERE `id`=137 AND `name`='لوحة متابعة البلاغات';
UPDATE `modules` SET `name`='تسجيل بلاغ' WHERE `id`=133 AND `name`='استمارة بلاغ';
UPDATE `modules` SET `name`='البلاغات الدورية' WHERE `id`=136 AND `name`='القوالب الدورية';
UPDATE `modules` SET `name`='أزمنة الاستجابة والإنجاز' WHERE `id`=134 AND `name`='سياسات الاستحقاق (SLA)';
UPDATE `modules` SET `name`='إعداد أنواع البلاغات' WHERE `id`=130 AND `name`='أنواع البلاغات والتوجيه';
UPDATE `modules` SET `name`='قواعد تحميل تكلفة الترحيل' WHERE `id`=109 AND `name`='قواعد المتحمِّل';
UPDATE `modules` SET `name`='موافقات الترحيل' WHERE `id`=111 AND `name`='طلبات الترحيل';
UPDATE `modules` SET `name`='إعدادات الترحيل' WHERE `id`=108 AND `name`='أنواع الترحيل';
UPDATE `modules` SET `name`='المواقع' WHERE `id`=110 AND `name`='إعداد المواقع';
UPDATE `modules` SET `name`='السكن والإعاشة' WHERE `id`=52 AND `name`='وحدات السكن';
UPDATE `modules` SET `name`='تقييم الأداء' WHERE `id`=53 AND `name`='تقييم العاملين';
UPDATE `modules` SET `name`='تنقلات العاملين' WHERE `id`=51 AND `name`='التحرّك والنقل';
UPDATE `modules` SET `name`='السجل التشغيلي للعامل' WHERE `id`=47 AND `name`='سجل العامل التشغيلي';
UPDATE `modules` SET `name`='تسويات العاملين' WHERE `id`=54 AND `name`='تسوية العاملين';
UPDATE `modules` SET `name`='سجل الأحداث التشغيلية' WHERE `id`=56 AND `name`='السجل التشغيلي';
UPDATE `modules` SET `name`='احتياج القوى والتخطيط' WHERE `id`=55 AND `name`='الاحتياج والتخطيط';
UPDATE `modules` SET `name`='المعاونون' WHERE `id`=61 AND `name`='إدارة المعاونين الشاملة';
UPDATE `modules` SET `name`='مشرفو الموردين' WHERE `id`=14 AND `name`='إدارة مشرفي الموردين';
UPDATE `modules` SET `name`='الصلاحيات' WHERE `id`=3 AND `name`='إدارة الصلاحيات';
UPDATE `modules` SET `name`='متابعة المشروع' WHERE `id`=34 AND `name`='حالة المشروع';
UPDATE `modules` SET `name`='الورديات' WHERE `id`=30 AND `name`='إدارة الورديات';
UPDATE `modules` SET `name`='توزيع المشغّلين' WHERE `id`=29 AND `name`='توزيع المشغلين';
UPDATE `modules` SET `name`='الإعدادات' WHERE `id`=24 AND `name`='الاعدادات';
COMMIT;
