-- التراجع الكامل عن إعادة التسمية — يعيد أسماء 2026-07-24
START TRANSACTION;
UPDATE `modules` SET `name`='سجل النشاطات' WHERE `id`=12 AND `name`='سجل النشاط';
UPDATE `modules` SET `name`='الأنشطة التجارية' WHERE `id`=77 AND `name`='أنشطة العملاء';
UPDATE `modules` SET `name`='حالة العملاء' WHERE `id`=1 AND `name`='العملاء';
UPDATE `modules` SET `name`='إدارة العملاء' WHERE `id`=35 AND `name`='العملاء';
UPDATE `modules` SET `name`='الملاحق والتجديدات' WHERE `id`=84 AND `name`='ملاحق العقود وتجديداتها';
UPDATE `modules` SET `name`='التزامات العقد' WHERE `id`=127 AND `name`='التزامات العقود';
UPDATE `modules` SET `name`='سجل الأحداث التعاقدية' WHERE `id`=85 AND `name`='سجل حركة العقد';
UPDATE `modules` SET `name`='نماذج التسعير' WHERE `id`=81 AND `name`='قوائم ونماذج التسعير';
UPDATE `modules` SET `name`='المنتجات والخدمات' WHERE `id`=82 AND `name`='كتالوج المنتجات والخدمات';
UPDATE `modules` SET `name`='العروض' WHERE `id`=80 AND `name`='عروض الأسعار';
UPDATE `modules` SET `name`='فحص الجاهزية' WHERE `id`=129 AND `name`='جاهزية العروض';
UPDATE `modules` SET `name`='إدارة العقود' WHERE `id`=20 AND `name`='العقود';
UPDATE `modules` SET `name`='إدارة العقود' WHERE `id`=37 AND `name`='العقود';
UPDATE `modules` SET `name`='تفاصيل عقد المشاريع' WHERE `id`=21 AND `name`='ملف عقد المشروع';
UPDATE `modules` SET `name`='تفاصيل عقد الموظف' WHERE `id`=63 AND `name`='ملف عقد الموظف';
UPDATE `modules` SET `name`='أدوار الموظفين' WHERE `id`=58 AND `name`='الأدوار الوظيفية';
UPDATE `modules` SET `name`='علاقات الموظفين' WHERE `id`=7 AND `name`='الموظفون';
UPDATE `modules` SET `name`='السائقون والمشغّلون' WHERE `id`=59 AND `name`='المشغّلون والسائقون';
UPDATE `modules` SET `name`='إدارة المعدات' WHERE `id`=8 AND `name`='المعدات';
UPDATE `modules` SET `name`='شاشة انواع المعدات' WHERE `id`=5 AND `name`='أنواع المعدات';
UPDATE `modules` SET `name`='ملف الإهلاك المالي' WHERE `id`=41 AND `name`='إعداد الإهلاك';
UPDATE `modules` SET `name`='سجل النوع والموديل' WHERE `id`=40 AND `name`='الأنواع والموديلات';
UPDATE `modules` SET `name`='تصنيف الاعطال' WHERE `id`=38 AND `name`='تصنيفات الأعطال';
UPDATE `modules` SET `name`='مكتب محاسب الإدارة' WHERE `id`=117 AND `name`='مكتب المحاسب';
UPDATE `modules` SET `name`='لوحة زمن الدورة' WHERE `id`=121 AND `name`='زمن دورة الطلبات';
UPDATE `modules` SET `name`='صندوق طلبات الإدارة' WHERE `id`=116 AND `name`='موافقات إدارتي';
UPDATE `modules` SET `name`='خريطة تفريع الأثر' WHERE `id`=119 AND `name`='سجل الحركة المالية';
UPDATE `modules` SET `name`='بوابة الطلبات المالية' WHERE `id`=118 AND `name`='الطلبات المالية';
UPDATE `modules` SET `name`='توجيه الطلبات المالية' WHERE `id`=120 AND `name`='قواعد توجيه الطلبات';
UPDATE `modules` SET `name`='الأصول الثابتة والإهلاك' WHERE `id`=101 AND `name`='الأصول والإهلاك';
UPDATE `modules` SET `name`='الميزانيات والانحراف' WHERE `id`=89 AND `name`='الميزانية والانحراف';
UPDATE `modules` SET `name`='لوحة المدير المالي اليومية' WHERE `id`=104 AND `name`='لوحة المدير المالي';
UPDATE `modules` SET `name`='الذمم والمستحقات' WHERE `id`=90 AND `name`='الذمم والتحصيل';
UPDATE `modules` SET `name`='الأحداث المالية' WHERE `id`=86 AND `name`='المعاملات المالية';
UPDATE `modules` SET `name`='استيراد أحداث الإدارات' WHERE `id`=98 AND `name`='استقبال معاملات الإدارات';
UPDATE `modules` SET `name`='القيود المالية' WHERE `id`=88 AND `name`='القيود اليومية';
UPDATE `modules` SET `name`='مخصّص الصيانة (المروحة)' WHERE `id`=126 AND `name`='قواعد مخصص الصيانة';
UPDATE `modules` SET `name`='مستحق المشغّل (المروحة)' WHERE `id`=128 AND `name`='قواعد مستحقات المشغّلين';
UPDATE `modules` SET `name`='الفترات والإقفال' WHERE `id`=93 AND `name`='إقفال الفترات';
UPDATE `modules` SET `name`='الضرائب / القيمة المضافة' WHERE `id`=102 AND `name`='الضرائب والقيمة المضافة';
UPDATE `modules` SET `name`='كشف الوحدات والتطابق' WHERE `id`=105 AND `name`='مطابقة الوحدات اليومية';
UPDATE `modules` SET `name`='مراقبة الانحراف والمعالجة' WHERE `id`=125 AND `name`='متابعة الانحراف';
UPDATE `modules` SET `name`='التفتيش الفني' WHERE `id`=44 AND `name`='الفحص الفني اليومي';
UPDATE `modules` SET `name`='الخطة الوقائية' WHERE `id`=45 AND `name`='الصيانة الوقائية';
UPDATE `modules` SET `name`='مسار الفرص' WHERE `id`=66 AND `name`='الفرص البيعية';
UPDATE `modules` SET `name`='الصرف والعهدة' WHERE `id`=73 AND `name`='صرف المخزون والعهدة';
UPDATE `modules` SET `name`='بيانات مرجعية' WHERE `id`=76 AND `name`='البيانات المرجعية';
UPDATE `modules` SET `name`='عهدة الاستلام المؤقت' WHERE `id`=71 AND `name`='الاستلام المؤقت';
UPDATE `modules` SET `name`='قواعد إعادة الطلب' WHERE `id`=74 AND `name`='حدود إعادة الطلب';
UPDATE `modules` SET `name`='المخزون التشغيلي' WHERE `id`=72 AND `name`='المخزون';
UPDATE `modules` SET `name`='الموردون التشغيليون' WHERE `id`=75 AND `name`='موردو المشتريات';
UPDATE `modules` SET `name`='حالة المشاريع' WHERE `id`=2 AND `name`='المشاريع';
UPDATE `modules` SET `name`='إدارة المبيعات' WHERE `id`=36 AND `name`='المشاريع';
UPDATE `modules` SET `name`='شاشة التقارير' WHERE `id`=4 AND `name`='مركز التقارير';
UPDATE `modules` SET `name`='شاشة التقارير' WHERE `id`=6 AND `name`='مركز التقارير';
UPDATE `modules` SET `name`='التقارير' WHERE `id`=28 AND `name`='مركز التقارير';
UPDATE `modules` SET `name`='التقارير' WHERE `id`=31 AND `name`='مركز التقارير';
UPDATE `modules` SET `name`='التقارير' WHERE `id`=32 AND `name`='مركز التقارير';
UPDATE `modules` SET `name`='إدارة صلاحيات الأدوار' WHERE `id`=123 AND `name`='صلاحيات الأدوار';
UPDATE `modules` SET `name`='إدارة الأدوار' WHERE `id`=124 AND `name`='الأدوار';
UPDATE `modules` SET `name`='علاقات الموردين' WHERE `id`=22 AND `name`='الموردون';
UPDATE `modules` SET `name`='تفاصيل عقد المورد' WHERE `id`=26 AND `name`='ملف عقد المورد';
UPDATE `modules` SET `name`='التصنيف الفنّي للبلاغات' WHERE `id`=131 AND `name`='تصنيفات الأعطال والبلاغات';
UPDATE `modules` SET `name`='لوحة متابعة البلاغات' WHERE `id`=137 AND `name`='أداء البلاغات';
UPDATE `modules` SET `name`='استمارة بلاغ' WHERE `id`=133 AND `name`='تسجيل بلاغ';
UPDATE `modules` SET `name`='القوالب الدورية' WHERE `id`=136 AND `name`='البلاغات الدورية';
UPDATE `modules` SET `name`='سياسات الاستحقاق (SLA)' WHERE `id`=134 AND `name`='أزمنة الاستجابة والإنجاز';
UPDATE `modules` SET `name`='أنواع البلاغات والتوجيه' WHERE `id`=130 AND `name`='إعداد أنواع البلاغات';
UPDATE `modules` SET `name`='قواعد المتحمِّل' WHERE `id`=109 AND `name`='قواعد تحميل تكلفة الترحيل';
UPDATE `modules` SET `name`='طلبات الترحيل' WHERE `id`=111 AND `name`='موافقات الترحيل';
UPDATE `modules` SET `name`='أنواع الترحيل' WHERE `id`=108 AND `name`='إعدادات الترحيل';
UPDATE `modules` SET `name`='إعداد المواقع' WHERE `id`=110 AND `name`='المواقع';
UPDATE `modules` SET `name`='وحدات السكن' WHERE `id`=52 AND `name`='السكن والإعاشة';
UPDATE `modules` SET `name`='تقييم العاملين' WHERE `id`=53 AND `name`='تقييم الأداء';
UPDATE `modules` SET `name`='التحرّك والنقل' WHERE `id`=51 AND `name`='تنقلات العاملين';
UPDATE `modules` SET `name`='سجل العامل التشغيلي' WHERE `id`=47 AND `name`='السجل التشغيلي للعامل';
UPDATE `modules` SET `name`='تسوية العاملين' WHERE `id`=54 AND `name`='تسويات العاملين';
UPDATE `modules` SET `name`='السجل التشغيلي' WHERE `id`=56 AND `name`='سجل الأحداث التشغيلية';
UPDATE `modules` SET `name`='الاحتياج والتخطيط' WHERE `id`=55 AND `name`='احتياج القوى والتخطيط';
UPDATE `modules` SET `name`='إدارة المعاونين الشاملة' WHERE `id`=61 AND `name`='المعاونون';
UPDATE `modules` SET `name`='إدارة مشرفي الموردين' WHERE `id`=14 AND `name`='مشرفو الموردين';
UPDATE `modules` SET `name`='إدارة الصلاحيات' WHERE `id`=3 AND `name`='الصلاحيات';
UPDATE `modules` SET `name`='حالة المشروع' WHERE `id`=34 AND `name`='متابعة المشروع';
UPDATE `modules` SET `name`='إدارة الورديات' WHERE `id`=30 AND `name`='الورديات';
UPDATE `modules` SET `name`='توزيع المشغلين' WHERE `id`=29 AND `name`='توزيع المشغّلين';
UPDATE `modules` SET `name`='الاعدادات' WHERE `id`=24 AND `name`='الإعدادات';
COMMIT;
