-- جدول ساعات الأعطال (يدعم تعدد الأعطال لكل تايم شيت)
CREATE TABLE IF NOT EXISTS `timesheet_failure_hours` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timesheet_id` int(11) NOT NULL,
  `operation_id` int(11) NOT NULL,
  `equipment_id` int(11) NOT NULL DEFAULT 0,
  `failure_code_id` int(11) NOT NULL,
  `equipment_type` tinyint(1) NOT NULL COMMENT '1=حفار,2=قلاب,3=خرامة',
  `event_type_code` varchar(20) NOT NULL,
  `event_type_name` varchar(150) NOT NULL,
  `main_category_code` varchar(20) NOT NULL,
  `main_category_name` varchar(200) NOT NULL,
  `sub_category` varchar(200) NOT NULL,
  `failure_detail` varchar(255) NOT NULL,
  `full_code` varchar(50) NOT NULL,
  `timesheet_date` date NOT NULL,
  `company_id` int(11) NOT NULL DEFAULT 0,
  `created_by` int(11) NOT NULL DEFAULT 0,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_timesheet_id` (`timesheet_id`),
  KEY `idx_operation_id` (`operation_id`),
  KEY `idx_equipment_id` (`equipment_id`),
  KEY `idx_failure_code_id` (`failure_code_id`),
  KEY `idx_full_code` (`full_code`),
  KEY `idx_timesheet_date` (`timesheet_date`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_lookup_report` (`company_id`, `timesheet_date`, `equipment_id`, `failure_code_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
