-- CMP-03 الموجة ٢ — تحرير بقية الشاشات من المخزن البيني (2026-08-06 · ق-15/ق-01)
-- ═══════════════════════════════════════════════════════════════════════════
-- لكل شاشةٍ جدولها الأصلي scr_* بأعمدةٍ دلاليةٍ مشتقةٍ من تسميات حقولها
-- (مولَّد بأداة tools/cmp03_wave2_generate.php — القاموس فيها).
-- DDL إضافي خالص: CREATE TABLE IF NOT EXISTS فقط — صفر ALTER على قائم.
-- التواريخ DATE والباقي VARCHAR (عرف جداول exec_* المرجعية) والبذور is_seed.

-- ── asset_recon.php ← Equipments/asset_recon.php ──
CREATE TABLE IF NOT EXISTS `scr_asset_recon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_minutes_doc` VARCHAR(300) DEFAULT NULL COMMENT 'رقم المحضر',
  `period_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الفترة',
  `code_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'كود المعدة',
  `hours_per_asset_log` VARCHAR(300) DEFAULT NULL COMMENT 'الساعات حسب سجل الأصول',
  `hours_per_timesheet` VARCHAR(300) DEFAULT NULL COMMENT 'الساعات حسب التايم شيت',
  `variance` VARCHAR(300) DEFAULT NULL COMMENT 'الفرق',
  `pct_variance` VARCHAR(300) DEFAULT NULL COMMENT 'نسبة الفرق',
  `classification_variance` VARCHAR(300) DEFAULT NULL COMMENT 'تصنيف الفرق',
  `explanation_variance` VARCHAR(300) DEFAULT NULL COMMENT 'تفسير الفرق',
  `correction_approved` VARCHAR(300) DEFAULT NULL COMMENT 'التصحيح المعتمد',
  `impact_correction_on_depreciation` VARCHAR(300) DEFAULT NULL COMMENT 'أثر التصحيح على الإهلاك',
  `matched_by` VARCHAR(300) DEFAULT NULL COMMENT 'طابقه',
  `approved_by` VARCHAR(300) DEFAULT NULL COMMENT 'اعتمده',
  `date_closing` DATE DEFAULT NULL COMMENT 'تاريخ الإقفال',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_asset_recon_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة asset_recon.php';

-- ── code_bridge.php ← Equipments/code_bridge.php ──
CREATE TABLE IF NOT EXISTS `scr_code_bridge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_bridge` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الجسر',
  `code_unified` VARCHAR(300) DEFAULT NULL COMMENT 'الكود الموحَّد',
  `name_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'اسم المعدة',
  `no_plate` VARCHAR(300) DEFAULT NULL COMMENT 'رقم اللوحة',
  `code_old` VARCHAR(300) DEFAULT NULL COMMENT 'الكود القديم',
  `code_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'كود المورد',
  `code_company_manufacturer` VARCHAR(300) DEFAULT NULL COMMENT 'كود الشركة المصنِّعة',
  `no_serial` VARCHAR(300) DEFAULT NULL COMMENT 'الرقم التسلسلي',
  `source_code` VARCHAR(300) DEFAULT NULL COMMENT 'مصدر الكود',
  `state_match` VARCHAR(300) DEFAULT NULL COMMENT 'حالة التطابق',
  `conflict_detected` VARCHAR(300) DEFAULT NULL COMMENT 'تعارض مكتشف',
  `description_conflict` VARCHAR(300) DEFAULT NULL COMMENT 'وصف التعارض',
  `decision_resolution` VARCHAR(300) DEFAULT NULL COMMENT 'قرار الفض',
  `date_link` DATE DEFAULT NULL COMMENT 'تاريخ الربط',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_code_bridge_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة code_bridge.php';

-- ── equipment_sourcing.php ← Equipments/equipment_sourcing.php ──
CREATE TABLE IF NOT EXISTS `scr_equipment_sourcing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `code_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'كود المعدة',
  `pattern_source` VARCHAR(300) DEFAULT NULL COMMENT 'نمط المصدر',
  `supplier_or_financier` VARCHAR(300) DEFAULT NULL COMMENT 'المورد أو الممول',
  `model_financing` VARCHAR(300) DEFAULT NULL COMMENT 'نموذج التمويل',
  `operation_financing` VARCHAR(300) DEFAULT NULL COMMENT 'عملية التمويل',
  `date_entry` DATE DEFAULT NULL COMMENT 'تاريخ الدخول',
  `date_transfer_ownership_expected` DATE DEFAULT NULL COMMENT 'تاريخ نقل الملكية المتوقع',
  `owner_legal_current` VARCHAR(300) DEFAULT NULL COMMENT 'المالك القانوني الحالي',
  `beneficiary_economic` VARCHAR(300) DEFAULT NULL COMMENT 'المنتفع الاقتصادي',
  `holder_depreciation` VARCHAR(300) DEFAULT NULL COMMENT 'حامل الإهلاك',
  `holder_maintenance` VARCHAR(300) DEFAULT NULL COMMENT 'حامل الصيانة',
  `holder_insurance` VARCHAR(300) DEFAULT NULL COMMENT 'حامل التأمين',
  `pledgee_warranty` VARCHAR(300) DEFAULT NULL COMMENT 'مرتهن الضمان',
  `value_asset` VARCHAR(300) DEFAULT NULL COMMENT 'قيمة الأصل',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `commitment_outstanding` VARCHAR(300) DEFAULT NULL COMMENT 'الالتزام القائم',
  `handling_accounting` VARCHAR(300) DEFAULT NULL COMMENT 'المعالجة المحاسبية',
  `grade_confidentiality` VARCHAR(300) DEFAULT NULL COMMENT 'درجة السرية',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_equipment_sourcing_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة equipment_sourcing.php';

-- ── fin_assets.php ← Equipments/fin_assets.php ──
CREATE TABLE IF NOT EXISTS `scr_fin_assets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_log` VARCHAR(300) DEFAULT NULL COMMENT 'رقم السجل',
  `code_asset_item` VARCHAR(300) DEFAULT NULL COMMENT 'كود العين',
  `type_asset` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الأصل',
  `operation_financing` VARCHAR(300) DEFAULT NULL COMMENT 'عملية التمويل',
  `financier_name` VARCHAR(300) DEFAULT NULL COMMENT 'الممول',
  `model_financing` VARCHAR(300) DEFAULT NULL COMMENT 'نموذج التمويل',
  `value_purchase` VARCHAR(300) DEFAULT NULL COMMENT 'قيمة الشراء',
  `capital_capital_financier` VARCHAR(300) DEFAULT NULL COMMENT 'رأس المال المموَّل',
  `date_link` DATE DEFAULT NULL COMMENT 'تاريخ الربط',
  `date_unlink_link` DATE DEFAULT NULL COMMENT 'تاريخ فك الربط',
  `in_active_fleet` VARCHAR(300) DEFAULT NULL COMMENT 'في الأسطول المشغَّل؟',
  `holder_depreciation` VARCHAR(300) DEFAULT NULL COMMENT 'حامل الإهلاك',
  `pledgee_warranty` VARCHAR(300) DEFAULT NULL COMMENT 'مرتهن الضمان',
  `grade_confidentiality` VARCHAR(300) DEFAULT NULL COMMENT 'درجة السرية',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_fin_assets_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة fin_assets.php';

-- ── fin_changes.php ← Financing/fin_changes.php ──
CREATE TABLE IF NOT EXISTS `scr_fin_changes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_minutes_doc` VARCHAR(300) DEFAULT NULL COMMENT 'رقم المحضر',
  `operation_financing` VARCHAR(300) DEFAULT NULL COMMENT 'عملية التمويل',
  `date_change` DATE DEFAULT NULL COMMENT 'تاريخ التغيير',
  `type_change` VARCHAR(300) DEFAULT NULL COMMENT 'نوع التغيير',
  `formula_before` VARCHAR(300) DEFAULT NULL COMMENT 'الصيغة قبل',
  `formula_after` VARCHAR(300) DEFAULT NULL COMMENT 'الصيغة بعد',
  `capital_before` VARCHAR(300) DEFAULT NULL COMMENT 'رأس المال قبل',
  `capital_after` VARCHAR(300) DEFAULT NULL COMMENT 'رأس المال بعد',
  `count_installments_before` VARCHAR(300) DEFAULT NULL COMMENT 'عدد الأقساط قبل',
  `count_installments_after` VARCHAR(300) DEFAULT NULL COMMENT 'عدد الأقساط بعد',
  `value_installment_before` VARCHAR(300) DEFAULT NULL COMMENT 'قيمة القسط قبل',
  `value_installment_after` VARCHAR(300) DEFAULT NULL COMMENT 'قيمة القسط بعد',
  `reason_change` VARCHAR(300) DEFAULT NULL COMMENT 'سبب التغيير',
  `doc_change` VARCHAR(300) DEFAULT NULL COMMENT 'مستند التغيير',
  `approved_by` VARCHAR(300) DEFAULT NULL COMMENT 'اعتمده',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_fin_changes_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة fin_changes.php';

-- ── fin_models.php ← Financing/fin_models.php ──
CREATE TABLE IF NOT EXISTS `scr_fin_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `code_model` VARCHAR(300) DEFAULT NULL COMMENT 'رمز النموذج',
  `name_model` VARCHAR(300) DEFAULT NULL COMMENT 'اسم النموذج',
  `owner_legal` VARCHAR(300) DEFAULT NULL COMMENT 'المالك القانوني',
  `beneficiary_economic` VARCHAR(300) DEFAULT NULL COMMENT 'المنتفع الاقتصادي',
  `recognition_accounting` VARCHAR(300) DEFAULT NULL COMMENT 'الاعتراف المحاسبي',
  `holder_depreciation` VARCHAR(300) DEFAULT NULL COMMENT 'حامل الإهلاك',
  `pledgee_warranty` VARCHAR(300) DEFAULT NULL COMMENT 'مرتهن الضمان',
  `handling_commitment` VARCHAR(300) DEFAULT NULL COMMENT 'معالجة الالتزام',
  `handling_return` VARCHAR(300) DEFAULT NULL COMMENT 'معالجة العائد',
  `ref_accounting` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع المحاسبي',
  `approved_by_auditor` VARCHAR(300) DEFAULT NULL COMMENT 'اعتمده المراجع',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_fin_models_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة fin_models.php';

-- ── ownership_links.php ← Financing/ownership_links.php ──
CREATE TABLE IF NOT EXISTS `scr_ownership_links` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_relation` VARCHAR(300) DEFAULT NULL COMMENT 'رقم العلاقة',
  `entity_owner` VARCHAR(300) DEFAULT NULL COMMENT 'الكيان المالك',
  `type_owner` VARCHAR(300) DEFAULT NULL COMMENT 'نوع المالك',
  `entity_owned` VARCHAR(300) DEFAULT NULL COMMENT 'الكيان المملوك',
  `type_ownership` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الملكية',
  `pct` VARCHAR(300) DEFAULT NULL COMMENT 'النسبة',
  `date_from` DATE DEFAULT NULL COMMENT 'من تاريخ',
  `date_to` DATE DEFAULT NULL COMMENT 'إلى تاريخ',
  `date_exit` DATE DEFAULT NULL COMMENT 'تاريخ التخارج',
  `owner_buyer` VARCHAR(300) DEFAULT NULL COMMENT 'المالك المشتري',
  `doc_exit` VARCHAR(300) DEFAULT NULL COMMENT 'مستند التخارج',
  `doc_ownership` VARCHAR(300) DEFAULT NULL COMMENT 'مستند الملكية',
  `completeness_ownership` VARCHAR(300) DEFAULT NULL COMMENT 'اكتمال الملكية',
  `active_pct_total` VARCHAR(300) DEFAULT NULL COMMENT 'مجموع النسب النشطة',
  `sum100_state` VARCHAR(300) DEFAULT NULL COMMENT 'حالة قيد المئة',
  `conflict_found_flag` VARCHAR(300) DEFAULT NULL COMMENT 'تضارب مصالح مكتشف؟',
  `recorded_by` VARCHAR(300) DEFAULT NULL COMMENT 'سجّلها',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_ownership_links_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة ownership_links.php';

-- ── access_review.php ← Governance/access_review.php ──
CREATE TABLE IF NOT EXISTS `scr_access_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_cycle` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الدورة',
  `period_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الفترة',
  `date_launch` DATE DEFAULT NULL COMMENT 'تاريخ الإطلاق',
  `dept_name` VARCHAR(300) DEFAULT NULL COMMENT 'الإدارة',
  `count_accounts_review` VARCHAR(300) DEFAULT NULL COMMENT 'عدد الحسابات المراجَعة',
  `confirmed` VARCHAR(300) DEFAULT NULL COMMENT 'المؤكَّدة',
  `required_revoke` VARCHAR(300) DEFAULT NULL COMMENT 'المطلوب سحبها',
  `revoked_auto` VARCHAR(300) DEFAULT NULL COMMENT 'المسحوبة آليًّا',
  `accounts_dormant` VARCHAR(300) DEFAULT NULL COMMENT 'الحسابات الخاملة',
  `disabled` VARCHAR(300) DEFAULT NULL COMMENT 'المعطَّلة',
  `conflicts_duties_detected` VARCHAR(300) DEFAULT NULL COMMENT 'تعارضات واجبات مكتشفة',
  `exceptions_standing` VARCHAR(300) DEFAULT NULL COMMENT 'استثناءات قائمة',
  `pct_response` VARCHAR(300) DEFAULT NULL COMMENT 'نسبة الاستجابة',
  `auditor_dept` VARCHAR(300) DEFAULT NULL COMMENT 'مراجع الإدارة',
  `date_closing` DATE DEFAULT NULL COMMENT 'تاريخ الإقفال',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_access_review_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة access_review.php';

-- ── break_glass.php ← Governance/break_glass.php ──
CREATE TABLE IF NOT EXISTS `scr_break_glass` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_request` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الطلب',
  `happened_at` VARCHAR(300) DEFAULT NULL COMMENT 'التاريخ والوقت',
  `requester_name_capacity_role` VARCHAR(300) DEFAULT NULL COMMENT 'الطالب — الاسم والصفة',
  `permission_required` VARCHAR(300) DEFAULT NULL COMMENT 'الصلاحية المطلوبة',
  `screen_or_action` VARCHAR(300) DEFAULT NULL COMMENT 'الشاشة أو الفعل',
  `reason_emergency` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الطوارئ',
  `impact_expected_if_not_granted` VARCHAR(300) DEFAULT NULL COMMENT 'الأثر المتوقع لو لم تُمنح',
  `approver_first` VARCHAR(300) DEFAULT NULL COMMENT 'الموافق الأول',
  `approver_second` VARCHAR(300) DEFAULT NULL COMMENT 'الموافق الثاني',
  `time_grant` VARCHAR(300) DEFAULT NULL COMMENT 'وقت المنح',
  `duration_permission` VARCHAR(300) DEFAULT NULL COMMENT 'مدة الصلاحية',
  `time_expiry` VARCHAR(300) DEFAULT NULL COMMENT 'وقت الانتهاء',
  `count_actions_executed_under_it` VARCHAR(300) DEFAULT NULL COMMENT 'عدد الأفعال المنفَّذة تحتها',
  `report_review` VARCHAR(300) DEFAULT NULL COMMENT 'تقرير المراجعة',
  `date_review` DATE DEFAULT NULL COMMENT 'تاريخ المراجعة',
  `result_review` VARCHAR(300) DEFAULT NULL COMMENT 'نتيجة المراجعة',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_break_glass_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة break_glass.php';

-- ── canonical_names.php ← Governance/canonical_names.php ──
CREATE TABLE IF NOT EXISTS `scr_canonical_names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_log` VARCHAR(300) DEFAULT NULL COMMENT 'رقم السجل',
  `type_entity` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الكيان',
  `name_approved` VARCHAR(300) DEFAULT NULL COMMENT 'الاسم المعتمد',
  `name_legal_full` VARCHAR(300) DEFAULT NULL COMMENT 'الاسم القانوني الكامل',
  `synonyms_registered` VARCHAR(300) DEFAULT NULL COMMENT 'المرادفات المسجَّلة',
  `count_synonyms` VARCHAR(300) DEFAULT NULL COMMENT 'عدد المرادفات',
  `name_in_log_commercial` VARCHAR(300) DEFAULT NULL COMMENT 'الاسم في السجل التجاري',
  `no_tax` VARCHAR(300) DEFAULT NULL COMMENT 'الرقم الضريبي',
  `code_entity_unified` VARCHAR(300) DEFAULT NULL COMMENT 'كود الكيان الموحَّد',
  `state_check` VARCHAR(300) DEFAULT NULL COMMENT 'حالة الفحص',
  `duplicate_detected` VARCHAR(300) DEFAULT NULL COMMENT 'تكرار مكتشف',
  `decision_merge` VARCHAR(300) DEFAULT NULL COMMENT 'قرار الدمج',
  `records_migrated` VARCHAR(300) DEFAULT NULL COMMENT 'السجلات المحوَّلة',
  `date_merge` DATE DEFAULT NULL COMMENT 'تاريخ الدمج',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_canonical_names_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة canonical_names.php';

-- ── doc_types.php ← Governance/doc_types.php ──
CREATE TABLE IF NOT EXISTS `scr_doc_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `code_type` VARCHAR(300) DEFAULT NULL COMMENT 'كود النوع',
  `name_doc` VARCHAR(300) DEFAULT NULL COMMENT 'اسم المستند',
  `dept_owning` VARCHAR(300) DEFAULT NULL COMMENT 'الإدارة المالكة',
  `pattern_numbering` VARCHAR(300) DEFAULT NULL COMMENT 'نمط الترقيم',
  `prefix_numbering` VARCHAR(300) DEFAULT NULL COMMENT 'بادئة الترقيم',
  `periodicity_sequence` VARCHAR(300) DEFAULT NULL COMMENT 'دورية التسلسل',
  `machine_state_linked` VARCHAR(300) DEFAULT NULL COMMENT 'آلة الحالة المرتبطة',
  `needs_approval_flag` VARCHAR(300) DEFAULT NULL COMMENT 'يحتاج اعتمادًا؟',
  `count_loops_approval` VARCHAR(300) DEFAULT NULL COMMENT 'عدد حلقات الاعتماد',
  `has_fin_impact_flag` VARCHAR(300) DEFAULT NULL COMMENT 'له أثر مالي؟',
  `reversible_flag` VARCHAR(300) DEFAULT NULL COMMENT 'قابل للعكس؟',
  `pattern_reversal` VARCHAR(300) DEFAULT NULL COMMENT 'نمط العكس',
  `duration_retention_statutory` VARCHAR(300) DEFAULT NULL COMMENT 'مدة الحفظ النظامية',
  `policy_archiving` VARCHAR(300) DEFAULT NULL COMMENT 'سياسة الأرشفة',
  `date_effective` DATE DEFAULT NULL COMMENT 'تاريخ السريان',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_doc_types_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة doc_types.php';

-- ── exceptions.php ← Governance/exceptions.php ──
CREATE TABLE IF NOT EXISTS `scr_exceptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_request` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الطلب',
  `date_request` DATE DEFAULT NULL COMMENT 'تاريخ الطلب',
  `protection_exempted` VARCHAR(300) DEFAULT NULL COMMENT 'الحماية المستثناة',
  `dept_requesting` VARCHAR(300) DEFAULT NULL COMMENT 'الإدارة الطالبة',
  `reason_exception` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الاستثناء',
  `docs_supporting` VARCHAR(300) DEFAULT NULL COMMENT 'المستندات المؤيدة',
  `grade_severity` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الخطورة',
  `impact_expected` VARCHAR(300) DEFAULT NULL COMMENT 'الأثر المتوقع',
  `scope_ref` VARCHAR(300) DEFAULT NULL COMMENT 'النطاق',
  `period_from` VARCHAR(300) DEFAULT NULL COMMENT 'المدة من',
  `period_to` VARCHAR(300) DEFAULT NULL COMMENT 'المدة إلى',
  `approvals_required` VARCHAR(300) DEFAULT NULL COMMENT 'الموافقات المطلوبة',
  `approvers` VARCHAR(300) DEFAULT NULL COMMENT 'الموافقون',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `count_times_usage` VARCHAR(300) DEFAULT NULL COMMENT 'عدد مرات الاستعمال',
  `date_expiry` DATE DEFAULT NULL COMMENT 'تاريخ الانتهاء',
  `decision_closing` VARCHAR(300) DEFAULT NULL COMMENT 'قرار الإقفال',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_exceptions_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة exceptions.php';

-- ── guards.php ← Governance/guards.php ──
CREATE TABLE IF NOT EXISTS `scr_guards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `code_guard` VARCHAR(300) DEFAULT NULL COMMENT 'رمز الحارس',
  `name_protection` VARCHAR(300) DEFAULT NULL COMMENT 'اسم الحماية',
  `category` VARCHAR(300) DEFAULT NULL COMMENT 'الصنف',
  `reason_classification` VARCHAR(300) DEFAULT NULL COMMENT 'سبب التصنيف',
  `screens_affected` VARCHAR(300) DEFAULT NULL COMMENT 'الشاشات المتأثرة',
  `actions_denied` VARCHAR(300) DEFAULT NULL COMMENT 'الأفعال الممنوعة',
  `message_denial` VARCHAR(300) DEFAULT NULL COMMENT 'رسالة المنع',
  `grade_severity` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الخطورة',
  `approvals_required_exception` VARCHAR(300) DEFAULT NULL COMMENT 'الموافقات المطلوبة للاستثناء',
  `state_flag` VARCHAR(300) DEFAULT NULL COMMENT 'حالة العلَم',
  `date_flip_flag` DATE DEFAULT NULL COMMENT 'تاريخ قلب العلَم',
  `classified_by` VARCHAR(300) DEFAULT NULL COMMENT 'صنّفها',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_guards_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة guards.php';

-- ── perm_explain.php ← Governance/perm_explain.php ──
CREATE TABLE IF NOT EXISTS `scr_perm_explain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `account_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الحساب',
  `screen_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الشاشة',
  `action_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الفعل',
  `result_final` VARCHAR(300) DEFAULT NULL COMMENT 'النتيجة النهائية',
  `grant_source_1` VARCHAR(300) DEFAULT NULL COMMENT 'مصدر المنح 1',
  `its_ruling` VARCHAR(300) DEFAULT NULL COMMENT 'حكمه',
  `grant_source_2` VARCHAR(300) DEFAULT NULL COMMENT 'مصدر المنح 2',
  `its_ruling_2` VARCHAR(300) DEFAULT NULL COMMENT 'حكمه',
  `source_denial` VARCHAR(300) DEFAULT NULL COMMENT 'مصدر المنع',
  `its_ruling_3` VARCHAR(300) DEFAULT NULL COMMENT 'حكمه',
  `rule_merge_applied` VARCHAR(300) DEFAULT NULL COMMENT 'قاعدة الدمج المطبَّقة',
  `scope_resulting` VARCHAR(300) DEFAULT NULL COMMENT 'النطاق الناتج',
  `cap_resulting` VARCHAR(300) DEFAULT NULL COMMENT 'السقف الناتج',
  `date_check` DATE DEFAULT NULL COMMENT 'تاريخ الفحص',
  `inspector_name` VARCHAR(300) DEFAULT NULL COMMENT 'الفاحص',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_perm_explain_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة perm_explain.php';

-- ── portal_users.php ← Governance/portal_users.php ──
CREATE TABLE IF NOT EXISTS `scr_portal_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `code_account` VARCHAR(300) DEFAULT NULL COMMENT 'كود الحساب',
  `type_party` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الطرف',
  `person_name` VARCHAR(300) DEFAULT NULL COMMENT 'الشخص',
  `capacity_role_at_entity` VARCHAR(300) DEFAULT NULL COMMENT 'الصفة لدى الكيان',
  `scope_visibility` VARCHAR(300) DEFAULT NULL COMMENT 'نطاق الرؤية',
  `actions_allowed` VARCHAR(300) DEFAULT NULL COMMENT 'الأفعال المسموحة',
  `actions_blocked` VARCHAR(300) DEFAULT NULL COMMENT 'الأفعال المحجوبة',
  `doc_authorization` VARCHAR(300) DEFAULT NULL COMMENT 'مستند التخويل',
  `last_entry` VARCHAR(300) DEFAULT NULL COMMENT 'آخر دخول',
  `date_expiry` DATE DEFAULT NULL COMMENT 'تاريخ الانتهاء',
  `created_by_f` VARCHAR(300) DEFAULT NULL COMMENT 'أنشأه',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_portal_users_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة portal_users.php';

-- ── sensitive_fields.php ← Governance/sensitive_fields.php ──
CREATE TABLE IF NOT EXISTS `scr_sensitive_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_policy` VARCHAR(300) DEFAULT NULL COMMENT 'رقم السياسة',
  `table_name` VARCHAR(300) DEFAULT NULL COMMENT 'الجدول',
  `field_name` VARCHAR(300) DEFAULT NULL COMMENT 'الحقل',
  `classification_sensitivity` VARCHAR(300) DEFAULT NULL COMMENT 'تصنيف الحساسية',
  `reason_classification` VARCHAR(300) DEFAULT NULL COMMENT 'سبب التصنيف',
  `from_visible_to` VARCHAR(300) DEFAULT NULL COMMENT 'من يراه',
  `policy_masking` VARCHAR(300) DEFAULT NULL COMMENT 'سياسة الإخفاء',
  `log_views_flag` VARCHAR(300) DEFAULT NULL COMMENT 'يُسجَّل الاطّلاع؟',
  `exportable_flag` VARCHAR(300) DEFAULT NULL COMMENT 'يُصدَّر؟',
  `basis_statutory` VARCHAR(300) DEFAULT NULL COMMENT 'الأساس النظامي',
  `date_effective` DATE DEFAULT NULL COMMENT 'تاريخ السريان',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_sensitive_fields_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة sensitive_fields.php';

-- ── state_machines.php ← Governance/state_machines.php ──
CREATE TABLE IF NOT EXISTS `scr_state_machines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `code_machine` VARCHAR(300) DEFAULT NULL COMMENT 'كود الآلة',
  `type_doc` VARCHAR(300) DEFAULT NULL COMMENT 'نوع المستند',
  `no_transition` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الانتقال',
  `from_state` VARCHAR(300) DEFAULT NULL COMMENT 'من حالة',
  `to_state` VARCHAR(300) DEFAULT NULL COMMENT 'إلى حالة',
  `action_triggering` VARCHAR(300) DEFAULT NULL COMMENT 'الفعل المُطلق',
  `code_action` VARCHAR(300) DEFAULT NULL COMMENT 'رمز الفعل',
  `authorized_role` VARCHAR(300) DEFAULT NULL COMMENT 'المخوَّل',
  `condition_pre` VARCHAR(300) DEFAULT NULL COMMENT 'الشرط المسبق',
  `guard_applied` VARCHAR(300) DEFAULT NULL COMMENT 'الحارس المطبَّق',
  `event_published` VARCHAR(300) DEFAULT NULL COMMENT 'الحدث المنشور',
  `reversible_flag` VARCHAR(300) DEFAULT NULL COMMENT 'قابل للعكس؟',
  `action_reversal` VARCHAR(300) DEFAULT NULL COMMENT 'فعل العكس',
  `date_effective` DATE DEFAULT NULL COMMENT 'تاريخ السريان',
  `version_no` VARCHAR(300) DEFAULT NULL COMMENT 'النسخة',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_state_machines_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة state_machines.php';

-- ── workshop.php ← Maintenance/workshop.php ──
CREATE TABLE IF NOT EXISTS `scr_workshop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_assignment` VARCHAR(300) DEFAULT NULL COMMENT 'رقم التكليف',
  `order_work` VARCHAR(300) DEFAULT NULL COMMENT 'أمر العمل',
  `technician_name` VARCHAR(300) DEFAULT NULL COMMENT 'الفني',
  `job_title` VARCHAR(300) DEFAULT NULL COMMENT 'الوظيفة',
  `specialty` VARCHAR(300) DEFAULT NULL COMMENT 'التخصص',
  `role_in_order` VARCHAR(300) DEFAULT NULL COMMENT 'الدور في الأمر',
  `date_start` DATE DEFAULT NULL COMMENT 'تاريخ البدء',
  `date_expiry` DATE DEFAULT NULL COMMENT 'تاريخ الانتهاء',
  `hours_actual` VARCHAR(300) DEFAULT NULL COMMENT 'الساعات الفعلية',
  `cost_hour` VARCHAR(300) DEFAULT NULL COMMENT 'تكلفة الساعة',
  `total_cost` VARCHAR(300) DEFAULT NULL COMMENT 'إجمالي التكلفة',
  `workshop_name` VARCHAR(300) DEFAULT NULL COMMENT 'الورشة',
  `assigned_by` VARCHAR(300) DEFAULT NULL COMMENT 'كلّفه',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_workshop_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة workshop.php';

-- ── attendance.php ← Operations/attendance.php ──
CREATE TABLE IF NOT EXISTS `scr_attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `month_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الشهر',
  `code_employee` VARCHAR(300) DEFAULT NULL COMMENT 'كود الموظف',
  `entry_date` VARCHAR(300) DEFAULT NULL COMMENT 'التاريخ',
  `code_state` VARCHAR(300) DEFAULT NULL COMMENT 'رمز الحالة',
  `description_state` VARCHAR(300) DEFAULT NULL COMMENT 'وصف الحالة',
  `time_entry` VARCHAR(300) DEFAULT NULL COMMENT 'وقت الدخول',
  `time_exit` VARCHAR(300) DEFAULT NULL COMMENT 'وقت الخروج',
  `hours_attendance` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات الدوام',
  `delay_minutes` VARCHAR(300) DEFAULT NULL COMMENT 'تأخير بالدقائق',
  `impact_salary` VARCHAR(300) DEFAULT NULL COMMENT 'أثر الراتب',
  `impact_incentive` VARCHAR(300) DEFAULT NULL COMMENT 'أثر الحافز',
  `impact_presence` VARCHAR(300) DEFAULT NULL COMMENT 'أثر التواجد',
  `impact_billing` VARCHAR(300) DEFAULT NULL COMMENT 'أثر الفوترة',
  `impact_due_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'أثر استحقاق المورد',
  `doc_supporting` VARCHAR(300) DEFAULT NULL COMMENT 'المستند المؤيد',
  `recorded_by` VARCHAR(300) DEFAULT NULL COMMENT 'سجّله',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_attendance_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة attendance.php';

-- ── equipment_quota.php ← Operations/equipment_quota.php ──
CREATE TABLE IF NOT EXISTS `scr_equipment_quota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_container` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الحاوية',
  `supplier_name` VARCHAR(300) DEFAULT NULL COMMENT 'المورد',
  `contract_client` VARCHAR(300) DEFAULT NULL COMMENT 'العقد العميل',
  `contract_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'عقد المورد',
  `model_work` VARCHAR(300) DEFAULT NULL COMMENT 'نموذج العمل',
  `unit_work` VARCHAR(300) DEFAULT NULL COMMENT 'وحدة العمل',
  `type_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'نوع المعدة',
  `code_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'كود المعدة',
  `role_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'دور المعدة',
  `share_supplier_total` VARCHAR(300) DEFAULT NULL COMMENT 'حصة المورد الكلية',
  `share_allocated_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'الحصة المخصَّصة للمعدة',
  `count_shifts` VARCHAR(300) DEFAULT NULL COMMENT 'عدد الورديات',
  `units_shift` VARCHAR(300) DEFAULT NULL COMMENT 'وحدات الوردية',
  `units_monthly_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'الوحدات الشهرية للمعدة',
  `total_shares_equipment_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'مجموع حصص معدات المورد',
  `supplier_share_remaining` VARCHAR(300) DEFAULT NULL COMMENT 'المتبقي من حصة المورد',
  `executed_actual` VARCHAR(300) DEFAULT NULL COMMENT 'المنفَّذ فعليًّا',
  `variance` VARCHAR(300) DEFAULT NULL COMMENT 'الفارق',
  `reason_variance` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الفارق',
  `date_effective` DATE DEFAULT NULL COMMENT 'تاريخ السريان',
  `date_expiry` DATE DEFAULT NULL COMMENT 'تاريخ الانتهاء',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_equipment_quota_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة equipment_quota.php';

-- ── monthly_close.php ← Operations/monthly_close.php ──
CREATE TABLE IF NOT EXISTS `scr_monthly_close` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_minutes_doc` VARCHAR(300) DEFAULT NULL COMMENT 'رقم المحضر',
  `month_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الشهر',
  `contract_ref` VARCHAR(300) DEFAULT NULL COMMENT 'العقد',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `unit_contractual` VARCHAR(300) DEFAULT NULL COMMENT 'الوحدة التعاقدية',
  `hours_contractual` VARCHAR(300) DEFAULT NULL COMMENT 'الساعات التعاقدية',
  `hours_per_our_log` VARCHAR(300) DEFAULT NULL COMMENT 'الساعات حسب سجلنا',
  `hours_client_approved` VARCHAR(300) DEFAULT NULL COMMENT 'الساعات المعتمدة من العميل',
  `variance` VARCHAR(300) DEFAULT NULL COMMENT 'الفرق',
  `reason_variance` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الفرق',
  `qty_executed` VARCHAR(300) DEFAULT NULL COMMENT 'الكمية المنفَّذة',
  `qty_approved` VARCHAR(300) DEFAULT NULL COMMENT 'الكمية المعتمدة',
  `value_due` VARCHAR(300) DEFAULT NULL COMMENT 'قيمة الاستحقاق',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `prepared_by` VARCHAR(300) DEFAULT NULL COMMENT 'أعدّه',
  `approved_by_operations` VARCHAR(300) DEFAULT NULL COMMENT 'اعتمده التشغيل',
  `approved_by_finance` VARCHAR(300) DEFAULT NULL COMMENT 'اعتمدته المالية',
  `date_closing` DATE DEFAULT NULL COMMENT 'تاريخ الإقفال',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `impact_grade` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الأثر',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_monthly_close_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة monthly_close.php';

-- ── production.php ← Operations/production.php ──
CREATE TABLE IF NOT EXISTS `scr_production` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_log` VARCHAR(300) DEFAULT NULL COMMENT 'رقم السجل',
  `entry_date` VARCHAR(300) DEFAULT NULL COMMENT 'التاريخ',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `contract_ref` VARCHAR(300) DEFAULT NULL COMMENT 'العقد',
  `line_contract` VARCHAR(300) DEFAULT NULL COMMENT 'بند العقد',
  `type_production` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الإنتاج',
  `front_work` VARCHAR(300) DEFAULT NULL COMMENT 'جبهة العمل',
  `point_unloading` VARCHAR(300) DEFAULT NULL COMMENT 'نقطة التفريغ',
  `method_measure` VARCHAR(300) DEFAULT NULL COMMENT 'طريقة القياس',
  `qty_per_our_log` VARCHAR(300) DEFAULT NULL COMMENT 'الكمية حسب سجلنا',
  `unit_measure` VARCHAR(300) DEFAULT NULL COMMENT 'وحدة القياس',
  `qty_client_approved` VARCHAR(300) DEFAULT NULL COMMENT 'الكمية المعتمدة من العميل',
  `variance` VARCHAR(300) DEFAULT NULL COMMENT 'الفرق',
  `reason_variance` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الفرق',
  `attached_doc` VARCHAR(300) DEFAULT NULL COMMENT 'المستند المرفق',
  `entered_by` VARCHAR(300) DEFAULT NULL COMMENT 'المُدخِل',
  `approved_client` VARCHAR(300) DEFAULT NULL COMMENT 'معتمد العميل',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `impact_grade` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الأثر',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_production_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة production.php';

-- ── shift_log.php ← Operations/shift_log.php ──
CREATE TABLE IF NOT EXISTS `scr_shift_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_log` VARCHAR(300) DEFAULT NULL COMMENT 'رقم السجل',
  `entry_date` VARCHAR(300) DEFAULT NULL COMMENT 'التاريخ',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `shift_name` VARCHAR(300) DEFAULT NULL COMMENT 'الوردية',
  `time_open` VARCHAR(300) DEFAULT NULL COMMENT 'وقت الفتح',
  `time_closing` VARCHAR(300) DEFAULT NULL COMMENT 'وقت الإقفال',
  `count_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'عدد المعدات',
  `count_operators_present` VARCHAR(300) DEFAULT NULL COMMENT 'عدد المشغّلين الحاضرين',
  `absent_count` VARCHAR(300) DEFAULT NULL COMMENT 'الغياب',
  `reading_meter_at_open` VARCHAR(300) DEFAULT NULL COMMENT 'قراءة العدّاد عند الفتح',
  `reading_meter_at_closing` VARCHAR(300) DEFAULT NULL COMMENT 'قراءة العدّاد عند الإقفال',
  `notes` VARCHAR(300) DEFAULT NULL COMMENT 'الملاحظات',
  `handed_by` VARCHAR(300) DEFAULT NULL COMMENT 'المسلِّم',
  `received_by` VARCHAR(300) DEFAULT NULL COMMENT 'المستلِم',
  `state_log` VARCHAR(300) DEFAULT NULL COMMENT 'حالة السجل',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_shift_log_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة shift_log.php';

-- ── site_gate_equip.php ← Operations/site_gate_equip.php ──
CREATE TABLE IF NOT EXISTS `scr_site_gate_equip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_permit` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الإذن',
  `type_permit` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الإذن',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `code_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'كود المعدة',
  `type_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'نوع المعدة',
  `source_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'مصدر المعدة',
  `party_escort` VARCHAR(300) DEFAULT NULL COMMENT 'الجهة المرافقة',
  `reason_movement` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الحركة',
  `doc_reference` VARCHAR(300) DEFAULT NULL COMMENT 'المستند المرجعي',
  `date_movement_planned` DATE DEFAULT NULL COMMENT 'تاريخ الحركة المخطط',
  `date_movement_actual` DATE DEFAULT NULL COMMENT 'تاريخ الحركة الفعلي',
  `reading_meter_at_movement` VARCHAR(300) DEFAULT NULL COMMENT 'قراءة العدّاد عند الحركة',
  `trip_haulage` VARCHAR(300) DEFAULT NULL COMMENT 'رحلة الترحيل',
  `state_readiness` VARCHAR(300) DEFAULT NULL COMMENT 'حالة الجاهزية',
  `state_documents` VARCHAR(300) DEFAULT NULL COMMENT 'حالة الوثائق',
  `approval_manager_site` VARCHAR(300) DEFAULT NULL COMMENT 'اعتماد مدير الموقع',
  `approval_manager_operations` VARCHAR(300) DEFAULT NULL COMMENT 'اعتماد مدير التشغيل',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_site_gate_equip_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة site_gate_equip.php';

-- ── site_gate_person.php ← Operations/site_gate_person.php ──
CREATE TABLE IF NOT EXISTS `scr_site_gate_person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_permit` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الإذن',
  `type_permit` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الإذن',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `code_operator` VARCHAR(300) DEFAULT NULL COMMENT 'كود المشغّل',
  `name_ar` VARCHAR(300) DEFAULT NULL COMMENT 'الاسم',
  `affiliation` VARCHAR(300) DEFAULT NULL COMMENT 'التبعية',
  `supplier_belongs_has` VARCHAR(300) DEFAULT NULL COMMENT 'المورد التابع له',
  `reason_movement` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الحركة',
  `cycle_rotation` VARCHAR(300) DEFAULT NULL COMMENT 'دورة التناوب',
  `date_start_work` DATE DEFAULT NULL COMMENT 'تاريخ بداية العمل',
  `date_end_work` DATE DEFAULT NULL COMMENT 'تاريخ نهاية العمل',
  `trip_entry_or_exit` VARCHAR(300) DEFAULT NULL COMMENT 'رحلة الدخول أو الخروج',
  `housing_allocated` VARCHAR(300) DEFAULT NULL COMMENT 'السكن المخصَّص',
  `state_license` VARCHAR(300) DEFAULT NULL COMMENT 'حالة الرخصة',
  `state_check_medical` VARCHAR(300) DEFAULT NULL COMMENT 'حالة الفحص الطبي',
  `attestation_security` VARCHAR(300) DEFAULT NULL COMMENT 'المصادقة الأمنية',
  `approval_manager_site` VARCHAR(300) DEFAULT NULL COMMENT 'اعتماد مدير الموقع',
  `approval_manager_operations` VARCHAR(300) DEFAULT NULL COMMENT 'اعتماد مدير التشغيل',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_site_gate_person_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة site_gate_person.php';

-- ── site_shift_plan.php ← Operations/site_shift_plan.php ──
CREATE TABLE IF NOT EXISTS `scr_site_shift_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_schedule` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الجدول',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `entry_date` VARCHAR(300) DEFAULT NULL COMMENT 'التاريخ',
  `shift_name` VARCHAR(300) DEFAULT NULL COMMENT 'الوردية',
  `time_from` VARCHAR(300) DEFAULT NULL COMMENT 'من الساعة',
  `time_to` VARCHAR(300) DEFAULT NULL COMMENT 'إلى الساعة',
  `code_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'كود المعدة',
  `type_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'نوع المعدة',
  `operator_assignee` VARCHAR(300) DEFAULT NULL COMMENT 'المشغّل المكلَّف',
  `operator_substitute` VARCHAR(300) DEFAULT NULL COMMENT 'المشغّل البديل',
  `check_qualification` VARCHAR(300) DEFAULT NULL COMMENT 'فحص التأهيل',
  `check_license` VARCHAR(300) DEFAULT NULL COMMENT 'فحص الرخصة',
  `check_readiness` VARCHAR(300) DEFAULT NULL COMMENT 'فحص الجاهزية',
  `front_work` VARCHAR(300) DEFAULT NULL COMMENT 'جبهة العمل',
  `target_production` VARCHAR(300) DEFAULT NULL COMMENT 'الهدف الإنتاجي',
  `window_maintenance` VARCHAR(300) DEFAULT NULL COMMENT 'نافذة الصيانة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_site_shift_plan_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة site_shift_plan.php';

-- ── site_work_calendar.php ← Operations/site_work_calendar.php ──
CREATE TABLE IF NOT EXISTS `scr_site_work_calendar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_schedule` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الجدول',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `project_name` VARCHAR(300) DEFAULT NULL COMMENT 'المشروع',
  `contract_ref` VARCHAR(300) DEFAULT NULL COMMENT 'العقد',
  `month_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الشهر',
  `week_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الأسبوع',
  `days_work_planned` VARCHAR(300) DEFAULT NULL COMMENT 'أيام العمل المخططة',
  `days_stoppage_planned` VARCHAR(300) DEFAULT NULL COMMENT 'أيام التوقف المخطط',
  `reason_stoppage` VARCHAR(300) DEFAULT NULL COMMENT 'سبب التوقف',
  `hours_operations_daily` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات التشغيل اليومية',
  `count_shifts` VARCHAR(300) DEFAULT NULL COMMENT 'عدد الورديات',
  `qty_target_monthly` VARCHAR(300) DEFAULT NULL COMMENT 'الكمية المستهدفة الشهرية',
  `qty_target_weekly` VARCHAR(300) DEFAULT NULL COMMENT 'الكمية المستهدفة الأسبوعية',
  `equipment_allocated` VARCHAR(300) DEFAULT NULL COMMENT 'المعدات المخصَّصة',
  `operators_required` VARCHAR(300) DEFAULT NULL COMMENT 'المشغّلون المطلوبون',
  `windows_preventive` VARCHAR(300) DEFAULT NULL COMMENT 'نوافذ الوقائية',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_site_work_calendar_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة site_work_calendar.php';

-- ── unbilled.php ← Operations/unbilled.php ──
CREATE TABLE IF NOT EXISTS `scr_unbilled` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_line` VARCHAR(300) DEFAULT NULL COMMENT 'رقم البند',
  `contract_ref` VARCHAR(300) DEFAULT NULL COMMENT 'العقد',
  `month_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الشهر',
  `unit_name` VARCHAR(300) DEFAULT NULL COMMENT 'الوحدة',
  `description_work` VARCHAR(300) DEFAULT NULL COMMENT 'وصف العمل',
  `qty` VARCHAR(300) DEFAULT NULL COMMENT 'الكمية',
  `amount` VARCHAR(300) DEFAULT NULL COMMENT 'القيمة',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `date_execution` DATE DEFAULT NULL COMMENT 'تاريخ التنفيذ',
  `reason_retention` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الاحتباس',
  `age_retention_days` VARCHAR(300) DEFAULT NULL COMMENT 'عمر الاحتباس بالأيام',
  `likelihood_approval` VARCHAR(300) DEFAULT NULL COMMENT 'احتمال الاعتماد',
  `procedure_followup` VARCHAR(300) DEFAULT NULL COMMENT 'إجراء المتابعة',
  `date_last_claim` DATE DEFAULT NULL COMMENT 'تاريخ آخر مطالبة',
  `responsible_name` VARCHAR(300) DEFAULT NULL COMMENT 'المسؤول',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `impact_grade` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الأثر',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_unbilled_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة unbilled.php';

-- ── unit_perf.php ← Operations/unit_perf.php ──
CREATE TABLE IF NOT EXISTS `scr_unit_perf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `month_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الشهر',
  `contract_ref` VARCHAR(300) DEFAULT NULL COMMENT 'العقد',
  `unit_contractual` VARCHAR(300) DEFAULT NULL COMMENT 'الوحدة التعاقدية',
  `code_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'كود المعدة',
  `hours_contractual` VARCHAR(300) DEFAULT NULL COMMENT 'الساعات التعاقدية',
  `hours_operations` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات التشغيل',
  `hours_standby_billable` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات الاستعداد المفوتر',
  `downtime_hours_client` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات التوقف — عميل',
  `downtime_hours_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات التوقف — مورد',
  `downtime_hours_ours` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات التوقف — نحن',
  `loss_not_executed` VARCHAR(300) DEFAULT NULL COMMENT 'فاقد غير منفَّذ',
  `stoppage_maintenance` VARCHAR(300) DEFAULT NULL COMMENT 'توقف صيانة',
  `stoppage_hr_hr` VARCHAR(300) DEFAULT NULL COMMENT 'توقف موارد بشرية',
  `stoppage_settlements` VARCHAR(300) DEFAULT NULL COMMENT 'توقف تسويات',
  `force_majeure` VARCHAR(300) DEFAULT NULL COMMENT 'قوة قاهرة',
  `maintenance_scheduled` VARCHAR(300) DEFAULT NULL COMMENT 'صيانة مجدولة',
  `total_downtime` VARCHAR(300) DEFAULT NULL COMMENT 'إجمالي التعطل',
  `main_bearing_party` VARCHAR(300) DEFAULT NULL COMMENT 'الطرف المتحمل الأغلب',
  `pct_readiness` VARCHAR(300) DEFAULT NULL COMMENT 'نسبة الجاهزية',
  `contract_shortfall` VARCHAR(300) DEFAULT NULL COMMENT 'العجز عن التعاقدي',
  `line_penalty` VARCHAR(300) DEFAULT NULL COMMENT 'بند الجزاء',
  `value_penalty` VARCHAR(300) DEFAULT NULL COMMENT 'قيمة الجزاء',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `impact_grade` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الأثر',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `version_rule_used` VARCHAR(300) DEFAULT NULL COMMENT 'نسخة القاعدة المستعملة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_unit_perf_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة unit_perf.php';

-- ── business_models.php ← Portal/business_models.php ──
CREATE TABLE IF NOT EXISTS `scr_business_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `code_model` VARCHAR(300) DEFAULT NULL COMMENT 'كود النموذج',
  `name_model` VARCHAR(300) DEFAULT NULL COMMENT 'اسم النموذج',
  `unit_work` VARCHAR(300) DEFAULT NULL COMMENT 'وحدة العمل',
  `unit_measure` VARCHAR(300) DEFAULT NULL COMMENT 'وحدة القياس',
  `method_measure_field` VARCHAR(300) DEFAULT NULL COMMENT 'طريقة القياس الميدانية',
  `doc_proving` VARCHAR(300) DEFAULT NULL COMMENT 'المستند المُثبت',
  `basis_pricing` VARCHAR(300) DEFAULT NULL COMMENT 'أساس التسعير',
  `types_equipment_applicable` VARCHAR(300) DEFAULT NULL COMMENT 'أنواع المعدات المنطبقة',
  `unit_meter_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'وحدة عدّاد المعدة',
  `unit_container_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'وحدة حاوية المورد',
  `unit_contracting_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'وحدة تعاقد المورد',
  `basis_due_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'أساس استحقاق المورد',
  `basis_wage_operator` VARCHAR(300) DEFAULT NULL COMMENT 'أساس أجر المشغّل',
  `cycle_closing` VARCHAR(300) DEFAULT NULL COMMENT 'دورة الإقفال',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `date_effective` DATE DEFAULT NULL COMMENT 'تاريخ السريان',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_business_models_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة business_models.php';

-- ── contract_review.php ← Portal/contract_review.php ──
CREATE TABLE IF NOT EXISTS `scr_contract_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_note` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الملاحظة',
  `contract_ref` VARCHAR(300) DEFAULT NULL COMMENT 'العقد',
  `date_observation` DATE DEFAULT NULL COMMENT 'تاريخ الرصد',
  `type_note` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الملاحظة',
  `grade_note` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الملاحظة',
  `line_affected` VARCHAR(300) DEFAULT NULL COMMENT 'البند المتأثر',
  `description_note` VARCHAR(300) DEFAULT NULL COMMENT 'وصف الملاحظة',
  `impact_potential` VARCHAR(300) DEFAULT NULL COMMENT 'الأثر المحتمل',
  `value_exposed` VARCHAR(300) DEFAULT NULL COMMENT 'القيمة المعرَّضة',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `party_observing` VARCHAR(300) DEFAULT NULL COMMENT 'الجهة الراصدة',
  `procedure_required` VARCHAR(300) DEFAULT NULL COMMENT 'الإجراء المطلوب',
  `responsible_name` VARCHAR(300) DEFAULT NULL COMMENT 'المسؤول',
  `deadline_handling` VARCHAR(300) DEFAULT NULL COMMENT 'مهلة المعالجة',
  `date_handling` DATE DEFAULT NULL COMMENT 'تاريخ المعالجة',
  `doc_handling` VARCHAR(300) DEFAULT NULL COMMENT 'مستند المعالجة',
  `blocks_approval_flag` VARCHAR(300) DEFAULT NULL COMMENT 'يحجب الاعتماد؟',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `date_closing` DATE DEFAULT NULL COMMENT 'تاريخ الإقفال',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_contract_review_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة contract_review.php';

-- ── founding_mode.php ← Portal/founding_mode.php ──
CREATE TABLE IF NOT EXISTS `scr_founding_mode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_mode` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الوضع',
  `date_open` DATE DEFAULT NULL COMMENT 'تاريخ الفتح',
  `reason_open` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الفتح',
  `scope_allowed` VARCHAR(300) DEFAULT NULL COMMENT 'النطاق المسموح',
  `tables_affected` VARCHAR(300) DEFAULT NULL COMMENT 'الجداول المتأثرة',
  `duration_authorized` VARCHAR(300) DEFAULT NULL COMMENT 'المدة المصرَّح بها',
  `date_close_planned` DATE DEFAULT NULL COMMENT 'تاريخ الإغلاق المخطط',
  `date_close_actual` DATE DEFAULT NULL COMMENT 'تاريخ الإغلاق الفعلي',
  `count_records_entered` VARCHAR(300) DEFAULT NULL COMMENT 'عدد السجلات المُدخَلة',
  `tag_records` VARCHAR(300) DEFAULT NULL COMMENT 'وسم السجلات',
  `entered_by_list` VARCHAR(300) DEFAULT NULL COMMENT 'المُدخِلون',
  `open_approver` VARCHAR(300) DEFAULT NULL COMMENT 'الموافق على الفتح',
  `close_approver` VARCHAR(300) DEFAULT NULL COMMENT 'الموافق على الإغلاق',
  `report_review_after_close` VARCHAR(300) DEFAULT NULL COMMENT 'تقرير المراجعة بعد الإغلاق',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_founding_mode_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة founding_mode.php';

-- ── release_stamp.php ← Portal/release_stamp.php ──
CREATE TABLE IF NOT EXISTS `scr_release_stamp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_release` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الإصدار',
  `fingerprint_release` VARCHAR(300) DEFAULT NULL COMMENT 'بصمة الإصدار',
  `date_publish` DATE DEFAULT NULL COMMENT 'تاريخ النشر',
  `type_release` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الإصدار',
  `screens_added` VARCHAR(300) DEFAULT NULL COMMENT 'الشاشات المضافة',
  `screens_modified` VARCHAR(300) DEFAULT NULL COMMENT 'الشاشات المعدَّلة',
  `columns_added` VARCHAR(300) DEFAULT NULL COMMENT 'الأعمدة المضافة',
  `actions_added` VARCHAR(300) DEFAULT NULL COMMENT 'الأفعال المضافة',
  `rules_changed` VARCHAR(300) DEFAULT NULL COMMENT 'القواعد المتغيرة',
  `migrations_executed` VARCHAR(300) DEFAULT NULL COMMENT 'الهجرات المنفَّذة',
  `report_completeness` VARCHAR(300) DEFAULT NULL COMMENT 'تقرير الاكتمال',
  `tests_passed` VARCHAR(300) DEFAULT NULL COMMENT 'الاختبارات المجتازة',
  `tests_failed` VARCHAR(300) DEFAULT NULL COMMENT 'الاختبارات الراسبة',
  `flag_rollback` VARCHAR(300) DEFAULT NULL COMMENT 'علَم الرجوع',
  `publisher_name_capacity_role` VARCHAR(300) DEFAULT NULL COMMENT 'الناشر — الاسم والصفة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_release_stamp_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة release_stamp.php';

-- ── consumption_rate.php ← Procurement/consumption_rate.php ──
CREATE TABLE IF NOT EXISTS `scr_consumption_rate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_log` VARCHAR(300) DEFAULT NULL COMMENT 'رقم السجل',
  `period_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الفترة',
  `code_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'كود المعدة',
  `type_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'نوع المعدة',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `unit_contractual` VARCHAR(300) DEFAULT NULL COMMENT 'الوحدة التعاقدية',
  `hours_operations` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات التشغيل',
  `category_consumption` VARCHAR(300) DEFAULT NULL COMMENT 'صنف الاستهلاك',
  `qty_disbursed` VARCHAR(300) DEFAULT NULL COMMENT 'الكمية المصروفة',
  `unit_name` VARCHAR(300) DEFAULT NULL COMMENT 'الوحدة',
  `rate_consumption_hour` VARCHAR(300) DEFAULT NULL COMMENT 'معدل الاستهلاك للساعة',
  `rate_reference_model` VARCHAR(300) DEFAULT NULL COMMENT 'المعدل المرجعي للموديل',
  `deviation` VARCHAR(300) DEFAULT NULL COMMENT 'الانحراف',
  `pct_deviation` VARCHAR(300) DEFAULT NULL COMMENT 'نسبة الانحراف',
  `threshold_anomaly` VARCHAR(300) DEFAULT NULL COMMENT 'حد الشذوذ',
  `state_anomaly` VARCHAR(300) DEFAULT NULL COMMENT 'حالة الشذوذ',
  `reason_probable` VARCHAR(300) DEFAULT NULL COMMENT 'السبب المرجَّح',
  `ticket_open` VARCHAR(300) DEFAULT NULL COMMENT 'البلاغ المفتوح',
  `cost_consumption` VARCHAR(300) DEFAULT NULL COMMENT 'تكلفة الاستهلاك',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_consumption_rate_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة consumption_rate.php';

-- ── transfer_fleet.php ← Transport/transfer_fleet.php ──
CREATE TABLE IF NOT EXISTS `scr_transfer_fleet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `code_carrier` VARCHAR(300) DEFAULT NULL COMMENT 'كود الناقل',
  `kind` VARCHAR(300) DEFAULT NULL COMMENT 'النوع',
  `description` VARCHAR(300) DEFAULT NULL COMMENT 'الوصف',
  `ownership_kind` VARCHAR(300) DEFAULT NULL COMMENT 'الملكية',
  `owner_name` VARCHAR(300) DEFAULT NULL COMMENT 'المالك',
  `capacity_max` VARCHAR(300) DEFAULT NULL COMMENT 'السعة القصوى',
  `no_plate` VARCHAR(300) DEFAULT NULL COMMENT 'رقم اللوحة',
  `license_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الرخصة',
  `date_expiry_license` DATE DEFAULT NULL COMMENT 'تاريخ انتهاء الرخصة',
  `insurance_ref` VARCHAR(300) DEFAULT NULL COMMENT 'التأمين',
  `date_expiry_insurance` DATE DEFAULT NULL COMMENT 'تاريخ انتهاء التأمين',
  `driver_assignee` VARCHAR(300) DEFAULT NULL COMMENT 'السائق المكلَّف',
  `tariff` VARCHAR(300) DEFAULT NULL COMMENT 'التعرفة',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_transfer_fleet_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة transfer_fleet.php';

-- ── transfer_permits.php ← Transport/transfer_permits.php ──
CREATE TABLE IF NOT EXISTS `scr_transfer_permits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_permit` VARCHAR(300) DEFAULT NULL COMMENT 'رقم التصريح',
  `order_haulage` VARCHAR(300) DEFAULT NULL COMMENT 'أمر الترحيل',
  `party_issuing` VARCHAR(300) DEFAULT NULL COMMENT 'الجهة المصدِرة',
  `type_permit` VARCHAR(300) DEFAULT NULL COMMENT 'نوع التصريح',
  `route_authorized` VARCHAR(300) DEFAULT NULL COMMENT 'المسار المصرَّح',
  `load_authorized` VARCHAR(300) DEFAULT NULL COMMENT 'الحمولة المصرَّحة',
  `weight_total` VARCHAR(300) DEFAULT NULL COMMENT 'الوزن الإجمالي',
  `date_release` DATE DEFAULT NULL COMMENT 'تاريخ الإصدار',
  `date_expiry` DATE DEFAULT NULL COMMENT 'تاريخ الانتهاء',
  `fees` VARCHAR(300) DEFAULT NULL COMMENT 'الرسوم',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `issued_by` VARCHAR(300) DEFAULT NULL COMMENT 'استخرجه',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_transfer_permits_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة transfer_permits.php';

-- ── deductions.php ← Workforce/deductions.php ──
CREATE TABLE IF NOT EXISTS `scr_deductions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_decision` VARCHAR(300) DEFAULT NULL COMMENT 'رقم القرار',
  `code_employee` VARCHAR(300) DEFAULT NULL COMMENT 'كود الموظف',
  `month_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الشهر',
  `type_deduction` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الخصم',
  `reason_deduction` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الخصم',
  `line_policy_reference` VARCHAR(300) DEFAULT NULL COMMENT 'بند السياسة المرجعي',
  `doc_supporting` VARCHAR(300) DEFAULT NULL COMMENT 'المستند المؤيد',
  `basis` VARCHAR(300) DEFAULT NULL COMMENT 'الأساس',
  `formula` VARCHAR(300) DEFAULT NULL COMMENT 'المعادلة',
  `value_deduction` VARCHAR(300) DEFAULT NULL COMMENT 'قيمة الخصم',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `pct_of_net` VARCHAR(300) DEFAULT NULL COMMENT 'نسبة من الصافي',
  `proposed_by` VARCHAR(300) DEFAULT NULL COMMENT 'اقترحه',
  `reviewed_by_hr` VARCHAR(300) DEFAULT NULL COMMENT 'راجعته الموارد',
  `approval_dept` VARCHAR(300) DEFAULT NULL COMMENT 'اعتماد الإدارة',
  `approval_financial` VARCHAR(300) DEFAULT NULL COMMENT 'الاعتماد المالي',
  `approval_dept_general` VARCHAR(300) DEFAULT NULL COMMENT 'اعتماد الإدارة العامة',
  `payroll_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المسيّر',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `impact_grade` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الأثر',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `version_rule_used` VARCHAR(300) DEFAULT NULL COMMENT 'نسخة القاعدة المستعملة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_deductions_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة deductions.php';

-- ── op_codes.php ← Workforce/op_codes.php ──
CREATE TABLE IF NOT EXISTS `scr_op_codes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `item_no` VARCHAR(300) DEFAULT NULL COMMENT 'الرقم',
  `state_no` VARCHAR(300) DEFAULT NULL COMMENT 'حالة الرقم',
  `operator_previous` VARCHAR(300) DEFAULT NULL COMMENT 'المشغّل السابق',
  `date_vacate` DATE DEFAULT NULL COMMENT 'تاريخ الإخلاء',
  `reason_vacate` VARCHAR(300) DEFAULT NULL COMMENT 'سبب الإخلاء',
  `duration_vacancy_days` VARCHAR(300) DEFAULT NULL COMMENT 'مدة الشغور بالأيام',
  `operator_new` VARCHAR(300) DEFAULT NULL COMMENT 'المشغّل الجديد',
  `date_allocation_new` DATE DEFAULT NULL COMMENT 'تاريخ التخصيص الجديد',
  `decision_dept` VARCHAR(300) DEFAULT NULL COMMENT 'قرار الإدارة',
  `allocated_by` VARCHAR(300) DEFAULT NULL COMMENT 'خصّصه',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_op_codes_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة op_codes.php';

-- ── op_monthly.php ← Workforce/op_monthly.php ──
CREATE TABLE IF NOT EXISTS `scr_op_monthly` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `month_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الشهر',
  `code_operator` VARCHAR(300) DEFAULT NULL COMMENT 'كود المشغّل',
  `equipment_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعدة',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `days_work` VARCHAR(300) DEFAULT NULL COMMENT 'أيام العمل',
  `days_leave` VARCHAR(300) DEFAULT NULL COMMENT 'أيام الإجازة',
  `days_absence` VARCHAR(300) DEFAULT NULL COMMENT 'أيام الغياب',
  `hours_operations` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات التشغيل',
  `hours_overtime` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات إضافية',
  `hours_standby` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات الاستعداد',
  `production_attributed` VARCHAR(300) DEFAULT NULL COMMENT 'الإنتاج المنسوب',
  `pct_achievement` VARCHAR(300) DEFAULT NULL COMMENT 'نسبة الإنجاز',
  `basis_incentive` VARCHAR(300) DEFAULT NULL COMMENT 'أساس الحافز',
  `value_incentive` VARCHAR(300) DEFAULT NULL COMMENT 'قيمة الحافز',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `approved_by` VARCHAR(300) DEFAULT NULL COMMENT 'اعتمده',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `impact_grade` VARCHAR(300) DEFAULT NULL COMMENT 'درجة الأثر',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `version_rule_used` VARCHAR(300) DEFAULT NULL COMMENT 'نسخة القاعدة المستعملة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_op_monthly_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة op_monthly.php';

-- ── op_qual.php ← Workforce/op_qual.php ──
CREATE TABLE IF NOT EXISTS `scr_op_qual` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_qualification` VARCHAR(300) DEFAULT NULL COMMENT 'رقم التأهيل',
  `code_operator` VARCHAR(300) DEFAULT NULL COMMENT 'كود المشغّل',
  `type_equipment` VARCHAR(300) DEFAULT NULL COMMENT 'نوع المعدة',
  `model_ref` VARCHAR(300) DEFAULT NULL COMMENT 'الموديل',
  `level_qualification` VARCHAR(300) DEFAULT NULL COMMENT 'مستوى التأهيل',
  `party_qualification` VARCHAR(300) DEFAULT NULL COMMENT 'جهة التأهيل',
  `no_certificate` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الشهادة',
  `date_release` DATE DEFAULT NULL COMMENT 'تاريخ الإصدار',
  `date_expiry` DATE DEFAULT NULL COMMENT 'تاريخ الانتهاء',
  `hours_experience_on_type` VARCHAR(300) DEFAULT NULL COMMENT 'ساعات الخبرة على النوع',
  `assessor_name` VARCHAR(300) DEFAULT NULL COMMENT 'المقيِّم',
  `date_last_evaluation` DATE DEFAULT NULL COMMENT 'تاريخ آخر تقييم',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_op_qual_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة op_qual.php';

-- ── project_contracts.php ← Workforce/project_contracts.php ──
CREATE TABLE IF NOT EXISTS `scr_project_contracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_contract` VARCHAR(300) DEFAULT NULL COMMENT 'رقم العقد',
  `category_contract` VARCHAR(300) DEFAULT NULL COMMENT 'فئة العقد',
  `contracted_with` VARCHAR(300) DEFAULT NULL COMMENT 'المتعاقَد معه',
  `affiliation` VARCHAR(300) DEFAULT NULL COMMENT 'التبعية',
  `supplier_linked` VARCHAR(300) DEFAULT NULL COMMENT 'المورد المرتبط',
  `contract_supplier` VARCHAR(300) DEFAULT NULL COMMENT 'عقد المورد',
  `project_name` VARCHAR(300) DEFAULT NULL COMMENT 'المشروع',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `position_title` VARCHAR(300) DEFAULT NULL COMMENT 'المسمى',
  `model_wage` VARCHAR(300) DEFAULT NULL COMMENT 'نموذج الأجر',
  `wage_monthly` VARCHAR(300) DEFAULT NULL COMMENT 'الأجر الشهري',
  `currency` VARCHAR(300) DEFAULT NULL COMMENT 'العملة',
  `date_start` DATE DEFAULT NULL COMMENT 'تاريخ البدء',
  `date_expiry_planned` DATE DEFAULT NULL COMMENT 'تاريخ الانتهاء المخطط',
  `end_trigger_1` VARCHAR(300) DEFAULT NULL COMMENT 'محفّز الانتهاء 1',
  `end_trigger_2` VARCHAR(300) DEFAULT NULL COMMENT 'محفّز الانتهاء 2',
  `end_trigger_3` VARCHAR(300) DEFAULT NULL COMMENT 'محفّز الانتهاء 3',
  `end_trigger_hit` VARCHAR(300) DEFAULT NULL COMMENT 'المحفّز الواقع',
  `date_expiry_actual` DATE DEFAULT NULL COMMENT 'تاريخ الانتهاء الفعلي',
  `expiry_alert_lead` VARCHAR(300) DEFAULT NULL COMMENT 'مهلة التنبيه قبل الانتهاء',
  `state_liquidation` VARCHAR(300) DEFAULT NULL COMMENT 'حالة التصفية',
  `permit_exit` VARCHAR(300) DEFAULT NULL COMMENT 'إذن الخروج',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_project_contracts_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة project_contracts.php';

-- ── rotation.php ← Workforce/rotation.php ──
CREATE TABLE IF NOT EXISTS `scr_rotation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL COMMENT 'الكيان المالك — EN-03',
  `no_cycle` VARCHAR(300) DEFAULT NULL COMMENT 'رقم الدورة',
  `code_operator` VARCHAR(300) DEFAULT NULL COMMENT 'كود المشغّل',
  `site_name` VARCHAR(300) DEFAULT NULL COMMENT 'الموقع',
  `equipment_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعدة',
  `pattern_rotation` VARCHAR(300) DEFAULT NULL COMMENT 'نمط التناوب',
  `type_leave` VARCHAR(300) DEFAULT NULL COMMENT 'نوع الإجازة',
  `date_entry` DATE DEFAULT NULL COMMENT 'تاريخ الدخول',
  `date_exit` DATE DEFAULT NULL COMMENT 'تاريخ الخروج',
  `days_work` VARCHAR(300) DEFAULT NULL COMMENT 'أيام العمل',
  `days_leave` VARCHAR(300) DEFAULT NULL COMMENT 'أيام الإجازة',
  `rotator_swapped` VARCHAR(300) DEFAULT NULL COMMENT 'المناوب المتبادل',
  `state_swap` VARCHAR(300) DEFAULT NULL COMMENT 'حالة التبادل',
  `date_swap_rotator` DATE DEFAULT NULL COMMENT 'تاريخ تبادل المناوب',
  `fallback_substitute` VARCHAR(300) DEFAULT NULL COMMENT 'البديل عند تعذّر التبادل',
  `trip_entry` VARCHAR(300) DEFAULT NULL COMMENT 'رحلة الدخول',
  `trip_exit` VARCHAR(300) DEFAULT NULL COMMENT 'رحلة الخروج',
  `balance_leave_before` VARCHAR(300) DEFAULT NULL COMMENT 'رصيد الإجازة قبل',
  `balance_leave_after` VARCHAR(300) DEFAULT NULL COMMENT 'رصيد الإجازة بعد',
  `scheduled_by` VARCHAR(300) DEFAULT NULL COMMENT 'جدولها',
  `status_label` VARCHAR(300) DEFAULT NULL COMMENT 'الحالة',
  `approver_name` VARCHAR(300) DEFAULT NULL COMMENT 'المعتمِد — الاسم والصفة',
  `approved_date` DATE DEFAULT NULL COMMENT 'تاريخ الاعتماد',
  `authority_ref` VARCHAR(300) DEFAULT NULL COMMENT 'مرجع التفويض',
  `parent_ref` VARCHAR(300) DEFAULT NULL COMMENT 'المرجع الأب',
  `attachment` VARCHAR(300) DEFAULT NULL COMMENT 'المرفق',
  `cost_center` VARCHAR(300) DEFAULT NULL COMMENT 'مركز التكلفة',
  `fx_rate_source` VARCHAR(300) DEFAULT NULL COMMENT 'سعر الصرف ومصدره',
  `status` VARCHAR(40) NOT NULL DEFAULT 'مسودة' COMMENT 'حالة الصف في دورته',
  `is_seed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'بذرة تجريبية — لا تنشر وقائع',
  `created_by` INT DEFAULT NULL,
  `created_by_name` VARCHAR(120) DEFAULT NULL COMMENT 'المُنشئ — الاسم والصفة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_rotation_live` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='CMP-03 موجة ٢: الجدول الأصلي لشاشة rotation.php';

