<?php
/**
 * هجرةُ شاشاتِ إدارةِ الموردين المنصوصةِ في الدليلِ المعماريّ
 * ═══════════════════════════════════════════════════════════════════════════
 * **مولَّدةٌ من الدليل**: `php tools/repair01_sup_build.php --apply`
 * ◆ ولكلِّ عمودٍ **تعليقٌ باسمِه العربيِّ المنصوص** — فالمعنى يسكن الجدولَ
 *   لا وثيقةً تتفرّق عنه.
 * ⛔ ولا يُنشأ جدولٌ موجود — `CREATE TABLE IF NOT EXISTS`.
 */
if (php_sapi_name() !== 'cli') { exit("CLI فقط\n"); }
error_reporting(E_ALL & ~E_DEPRECATED);
mb_internal_encoding('UTF-8');
$ROOT = dirname(dirname(__DIR__));
require_once $ROOT . '/includes/env.php';
$host = ems_env('DB_HOST'); $port = 3306;
if (strpos($host, ':') !== false) { list($host, $port) = explode(':', $host); $port = (int) $port; }
mysqli_report(MYSQLI_REPORT_OFF);
$u = ems_env('DB_MIGRATOR_USER') ?: ems_env('DB_USER');
$p = ems_env('DB_MIGRATOR_USER') ? ems_env('DB_MIGRATOR_PASS') : ems_env('DB_PASS');
$conn = new mysqli($host, $u, $p, ems_env('DB_NAME'), $port);
if ($conn->connect_errno) { exit("تعذّر الاتصال: {$conn->connect_error}\n"); }
$conn->set_charset('utf8mb4');
$n = 0;

/* التأهيل القانوني والائتماني — حبّة: سجل تأهيل قانوني وائتماني واحد لمورد */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_qualification_legal_credit` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الوثيقة',
  `no` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم الوثيقة',
  `issue` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'جهة الإصدار',
  `date_issue` DATE NULL COMMENT 'تاريخ الإصدار',
  `date_expiry` DATE NULL COMMENT 'تاريخ الانتهاء',
  `verify` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة التحقق',
  `date_verify` DATE NULL COMMENT 'تاريخ التحقق',
  `verifier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المتحقق',
  `name_bank` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'اسم البنك',
  `branch` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الفرع',
  `no_account` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم الحساب',
  `name_account` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'اسم صاحب الحساب',
  `name` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مطابقة الاسم للمورد؟',
  `account` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'علم حساب طرف ثالث',
  `doc_delegation` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مستند تفويض الطرف الثالث',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'حد التعامل الشهري $',
  `c20` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'حد التعامل ج.س',
  `c21` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'شروط سداد افتراضية',
  `credit` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التصنيف الائتماني الداخلي',
  `c23` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أساس التصنيف',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_qualification_legal__co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* احتياجات التغطية — حبّة: دورة التزام × نوع — جانب الطلب (قراءة مقيدة من المبيعات) */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_need` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `code_contract` INT NULL COMMENT 'كود العقد',
  `no_contract` INT NULL COMMENT 'رقم العقد (تسلسل العميل)',
  `no` INT NULL COMMENT 'رقم العميل',
  `name` INT NULL COMMENT 'اسم العميل (بحث)',
  `c6` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نموذج العمل',
  `key` INT NULL COMMENT 'مفتاح دورة الالتزام · Key',
  `no_role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'رقم التجديد (دورة الالتزام)',
  `type_role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع دورة الالتزام',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند',
  `c11` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'وحدة القياس',
  `slot` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'خانات العميل',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أساس الوحدة الشهري',
  `role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'أشهر دورة الالتزام',
  `role_obligation_target` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'سعة دورة الالتزام (المستهدف)',
  `target` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المستهدف المنقضي ◄',
  `c17` DECIMAL(18,2) NULL COMMENT 'سعر بيع الوحدة (قراءة) ◄',
  `c18` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'السريان التعاقدي من',
  `c19` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إلى',
  `allocation_need_source` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة توزيع الاحتياج (مصدر)',
  `supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المغطى بعقود الموردين ◄',
  `c22` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'فجوة التغطية ◄',
  `need` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الاحتياج',
  `quota_supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'Σ حصص الموردين (حي) ◄',
  `allocation` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'علم تجاوز التوزيع ◄',
  `unit_source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'فحص الوحدات التعاقدية (مصدر)',
  `slot_supplier_source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'خانات الموردين (مصدر)',
  `role_obligation_source` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'منفذ دورة الالتزام (مصدر) ◄',
  `verify_role_obligation` DECIMAL(9,4) NULL COMMENT 'نسبة تحقق دورة الالتزام (مصدر) ◄',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `contract` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة عقد العميل (قراءة من المبيعات) ◄',
  `c32` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'النهاية التنفيذية لعقد العميل ◄',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_need_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* عروض الموردين والتفاوض — حبّة: عرض مورد واحد بطبقة إصدارات */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_offer_supplier_negotiation` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `code_contract_supplier` INT NULL COMMENT 'كود عقد المورد (الناتج)',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `c5` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نموذج العمل',
  `offer` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'صفة العرض',
  `no` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم النسخة',
  `c8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'النسخة الأساس',
  `c9` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'ما الذي تغير عن سابقتها',
  `c10` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'من اقترح التغيير',
  `date` DATE NULL COMMENT 'تاريخ التغيير',
  `negotiation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة التفاوض',
  `line` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أنواع البنود المعروضة ◄',
  `count_line` INT NULL COMMENT 'عدد البنود ◄',
  `c15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إجمالي الحصة الشهرية المعروضة ◄',
  `c16` DECIMAL(18,2) NULL COMMENT 'أدنى سعر وحدة ◄',
  `c17` DECIMAL(18,2) NULL COMMENT 'أعلى سعر وحدة ◄',
  `c18` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العملة',
  `c19` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'شروط السداد المعروضة',
  `site` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'موقع التنفيذ',
  `date_offer` DATE NULL COMMENT 'تاريخ العرض',
  `offer_22` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العرض يسبق ◄',
  `offer_23` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'عروض منافسة قورنت',
  `guarantee` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الضمانات المطلوبة',
  `source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المصدر',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_offer_supplier_negot_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* مصفوفة المسؤوليات والتكاليف — حبّة: عقد واحد × مصفوفة المسؤوليات (كل التزام عمود ▼) */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_responsibility` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نموذج العمل',
  `c5` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'تكييف الوثيقة',
  `c7` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الوقود ▼',
  `c8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الزيوت ▼',
  `c9` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الصيانة ▼',
  `c10` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'قطع الغيار ▼',
  `c11` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المشغل (السائق) ▼',
  `c12` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'السكن والإعاشة ▼',
  `migration` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'ترحيل الذهاب ▼',
  `migration_14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'ترحيل العودة ▼',
  `c15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الضرر ▼',
  `c16` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الانتظار ▼',
  `c17` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التوقف ▼',
  `c18` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العطل ▼',
  `c19` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التأمين ▼',
  `c20` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المخالفات ▼',
  `count_line` INT NULL COMMENT 'عدد البنود المحددة ◄',
  `c22` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة تعبئة المصفوفة ◄',
  `ref_contract_annex` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المرجع (نص العقد/الملحق)',
  `c24` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المعبئ',
  `date` DATE NULL COMMENT 'تاريخ التعبئة',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_responsibility_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* الخانات المكافئة وتوزيع الحصص — حبّة: مورد × حاوية × نوع آلية — سطر استحقاق وتوزيع واحد */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_slot_allocation_quota` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'مفتاح دورة الالتزام السنوية ◄',
  `no_supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم المورد ◄',
  `name_supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'اسم المورد ◄',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند ◄',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أساس الوحدة التعاقدية الشهري ◄',
  `month_7` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'متوسط المنفذ الشهري ◄',
  `unit_entitlement` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الوحدات التعاقدية المكافئة (الاستحقاق) ◄',
  `unit` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الوحدات التعاقدية الممنوحة (أعدادا صحيحة)',
  `c10` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'فارق أكبر البواقي ◄',
  `unit_11` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'آليات زائدة عن الوحدات التعاقدية ◄',
  `supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'تصنيف المورد ▼',
  `c13` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'عضو خانة مشتركة؟ ▼',
  `c14` DECIMAL(9,4) NULL COMMENT 'نسبة المساهمة في الوحدة التعاقدية المشتركة',
  `target` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'آلات تعاقدية = المستهدف ÷ أساس الوحدة التعاقدية ◄',
  `target_supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'آلات واقعية = المستهدف ÷ إنتاجية آلة المورد ◄',
  `c17` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الفرق بين التعاقدي والواقعي ◄',
  `date` DATE NULL COMMENT 'ساري من تاريخ',
  `ref_allocation` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع قرار التوزيع',
  `allocation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة التوزيع ▼',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_slot_allocation_quot_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* حصص الموردين والوحدات التعاقدية — حبّة: وحدة تعاقدية واحدة بحصتها وهامشها */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_quota_supplier_unit` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `c2` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التسلسل الزمني للوحدة التعاقدية ◄',
  `no` INT NULL COMMENT 'رقم العميل',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نموذج العمل',
  `no_contract` INT NULL COMMENT 'رقم العقد',
  `no_role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'رقم التجديد (دورة الالتزام)',
  `key` INT NULL COMMENT 'مفتاح دورة الالتزام · Key',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `code_contract_supplier` INT NULL COMMENT 'كود عقد المورد',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند',
  `c12` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'وحدة القياس',
  `type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الوحدة التعاقدية',
  `c14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التصنيف (استمرارية)',
  `count_unit` INT NULL COMMENT 'عدد الوحدات التعاقدية للآلية',
  `role` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'الدور المستنتج',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أساس الوحدة التعاقدية الشهري ◄',
  `contract_supplier_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'أشهر عقد المورد بدورة الالتزام (كما ورد)',
  `c19` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أشهر منقضية ◄',
  `role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'أشهر دورة الالتزام (إجمالي) ◄',
  `month_21` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'وحدات-شهر ◄',
  `supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'حصة المورد ◄',
  `target_month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المستهدف الشهري',
  `equipment` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المعدات الأساسية المطلوبة',
  `c25` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الأساسية المتاحة ◄',
  `c26` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الاحتياطية ◄',
  `c27` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'فجوة الأساسية ◄',
  `c28` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أساسية نشطة (حي) ◄',
  `deficit_equipment` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'علم عجز معدات ◄',
  `equipment_30` DECIMAL(9,4) NULL COMMENT 'نسبة تغطية المعدات ◄',
  `approval_reserve` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الاعتماد على الاحتياطي ◄',
  `c32` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المنفذ ◄',
  `verify` DECIMAL(9,4) NULL COMMENT 'نسبة التحقق ◄',
  `c34` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'سريان الحصة من',
  `c35` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إلى',
  `supplier_36` DECIMAL(18,2) NULL COMMENT 'سعر وحدة المورد (م08) ◄',
  `c37` DECIMAL(18,2) NULL COMMENT 'سعر بيع الوحدة (قراءة) ◄',
  `c38` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'هامش الوحدة ◄',
  `c39` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'علم هامش سالب ◄',
  `c40` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الوحدة التعاقدية',
  `source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إجمالي التزام العميل (مصدر)',
  `obligation` DECIMAL(9,4) NULL COMMENT 'نسبة الحصة من الالتزام ◄',
  `deficit_surplus` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العجز / الفائض ◄',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `code_contract` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود العقد (قراءة) ◄',
  `c47` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'عملة البيع (قراءة) ◄',
  `c48` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'ملاءمة عملة الهامش ◄',
  `c49` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'علم حصة جارية بلا نشاط ◄',
  `c50` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'آخر نشاط بالوحدة التعاقدية ◄',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_quota_supplier_unit_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* سجل تسليم الخانات — حبّة: خانة × مورد × فترة إشغال — سطر إشغال واحد بتاريخيه */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_handover_slot` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `code_type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'كود الوحدة التعاقدية (بادئة النوع + تسلسل) ◄',
  `role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'مفتاح دورة الالتزام السنوية ◄',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند ◄',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'اسم المورد ◄',
  `type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الإشغال ▼',
  `date` DATE NULL COMMENT 'من تاريخ',
  `date_9` DATE NULL COMMENT 'إلى تاريخ',
  `c10` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أشهر الإشغال ◄',
  `target` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مستهدف الفترة (أساس الوحدة التعاقدية × أشهر الإشغال) ◄',
  `c12` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المنفذ في الفترة ◄',
  `verify` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'تحقق الفترة ◄',
  `supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المورد المسلم ◄',
  `supplier_15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المورد المتسلم ◄',
  `c16` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'شغور موثق؟ ▼',
  `c17` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مبرر الشغور',
  `c18` DECIMAL(9,4) NULL COMMENT 'نسبة المساهمة عند اجتماع متناوبين ◄',
  `ref` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع القرار',
  `c20` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الإشغال ▼',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_handover_slot_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* توزيع الوحدات التعاقدية على المعدات — حبّة: إسناد معدة واحد على وحدة تعاقدية */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_allocation_unit_equipment` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `slot_id` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود الوحدة التعاقدية · Slot_ID',
  `code_contract_supplier` INT NULL COMMENT 'كود عقد المورد',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `equipment_id` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود المعدة · Equipment_ID',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند',
  `no` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم اللوحة (كما ورد)',
  `c8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رمز اللوحة ◄',
  `no_9` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم اللوحة (رقمي) ◄',
  `type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الوحدة التعاقدية',
  `key` INT NULL COMMENT 'مفتاح دورة الالتزام · Key',
  `no_12` INT NULL COMMENT 'رقم العميل',
  `name` INT NULL COMMENT 'اسم العميل (بحث)',
  `c14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نموذج العمل',
  `no_contract` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم الآلية في عقد العميل',
  `no_contract_supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم الآلية في عقد المورد',
  `c17` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'من',
  `c18` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إلى',
  `type_19` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الإسناد',
  `role` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'الدور (أساسية/احتياطية)',
  `c21` TEXT NULL COMMENT 'سبب التغيير',
  `ref` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع حدث الجاهزية (م12)',
  `c23` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أشهر النشاط ◄',
  `c24` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أيام العمل ◄',
  `c25` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المنفذ بوحدة الحصة ◄',
  `supplier` INT NULL COMMENT 'ساعات المورد الكلية ◄',
  `c27` INT NULL COMMENT 'ساعات الاتفاق الشهرية',
  `site` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الموقع (المنجم)',
  `c29` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الاستمرارية',
  `c30` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الوضع التشغيلي',
  `supplier_ref` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مستحق المورد $ (مرجعي) ◄',
  `contract_supplier_source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'عقد المورد (كما بالمصدر)',
  `count` INT NULL COMMENT 'عدد إسنادات الآلية ◄',
  `c34` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الإسناد',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_allocation_unit_equi_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* الجاهزية والإحلال والاحتياط — حبّة: واقعة دخول/خروج جاهزية أو عضوية تناوب واحدة */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_replacement_reserve` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `key` INT NULL COMMENT 'مفتاح دورة الالتزام · Key',
  `slot_id` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود الوحدة التعاقدية · Slot_ID',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'اختبار الانتماء ◄',
  `c5` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نموذج العمل',
  `no_month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم الشهر',
  `date` DATE NULL COMMENT 'التاريخ',
  `c8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الحدث',
  `type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الوحدة التعاقدية',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `code` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود المعدة',
  `c13` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الطرف المقابل',
  `c14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'من الاحتياطي؟',
  `c15` DECIMAL(18,2) NULL COMMENT 'القيمة قبل',
  `c16` DECIMAL(18,2) NULL COMMENT 'القيمة بعد',
  `name_doc` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'اسم المستند ◄',
  `date_doc` DATE NULL COMMENT 'تاريخ المستند ◄',
  `doc_ref` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مستند/مرجع (كما ورد)',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_replacement_reserve_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* مستهدفات الموردين — حبّة: مستهدف شهري واحد — مشتق من السريان التعاقدي */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_target_supplier` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `slot_id` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود الوحدة التعاقدية · Slot_ID',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `code_contract_supplier` INT NULL COMMENT 'كود عقد المورد',
  `c6` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نموذج العمل',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند',
  `no_month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم الشهر',
  `c9` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'من',
  `c10` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إلى',
  `c11` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'وحدة القياس',
  `slot_month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'خانات الشهر',
  `c13` DECIMAL(18,2) NULL COMMENT 'قيمة الوحدة التعاقدية (الجزئي أيامه/30)',
  `target_month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مستهدف الشهر ◄',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المنفذ بالشهر ◄',
  `verify_month` DECIMAL(9,4) NULL COMMENT 'نسبة تحقق الشهر ◄',
  `month_17` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'علم شهر بلا تنفيذ ◄',
  `target` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المستهدف المنقضي ◄',
  `c19` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نسخة الخطة',
  `source_target` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مصدر المستهدف',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_target_supplier_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* قياس التغطية والعجز والفائض — حبّة: حاوية × نوع آلية × شهر — سطر تغطية واحد مشتق */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_deficit_surplus` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `id_1` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'معرف السطر ◄',
  `role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'مفتاح دورة الالتزام السنوية ◄',
  `no_role_obligation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'رقم دورة الالتزام الشهرية ◄',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند ◄',
  `role_obligation_5` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'سعة دورة الالتزام الشهرية ◄',
  `target_unit` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مجموع مستهدفات الوحدات التعاقدية ◄',
  `c7` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مجموع المنفذ ◄',
  `verify` DECIMAL(9,4) NULL COMMENT 'نسبة التحقق ◄',
  `deficit` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مجموع عجز المقصرين ◄',
  `surplus` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مجموع فائض المتجاوزين ◄',
  `c11` DECIMAL(9,4) NULL COMMENT 'نسبة التغطية بينهما ◄',
  `count_supplier` INT NULL COMMENT 'عدد الموردين العاجزين ◄',
  `count` INT NULL COMMENT 'عدد المتجاوزين ◄',
  `c14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أشهر متتالية بلا تغطية ◄',
  `c15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'فجوة التغطية النهائية ◄',
  `c16` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إشارة إنذار ▼',
  `ref` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع الخطر المتفرع ◄',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_deficit_surplus_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* النيابية والسلف والخصومات — حبّة: واقعة نيابية/سلفة/خصم واحدة */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_onbehalf_advance_deduction` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `date` DATE NULL COMMENT 'التاريخ',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `code_contract_supplier` INT NULL COMMENT 'كود عقد المورد',
  `code` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود الوحدة التعاقدية/المعدة (إن وجد)',
  `type_onbehalf` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الواقعة النيابية',
  `code_8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود المشغل E###',
  `c9` TEXT NULL COMMENT 'الوصف',
  `amount` DECIMAL(18,2) NULL COMMENT 'المبلغ',
  `c11` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العملة',
  `provided_by` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'Provided_By',
  `paid_by` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'Paid_By',
  `economic_cost_bearer` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'Economic_Cost_Bearer',
  `c15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'قابل للاسترداد؟',
  `doc` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المستند/الإثبات',
  `disburse` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'معتمد الصرف',
  `onbehalf` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة السلسلة النيابية',
  `ref` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع التسوية الخاصمة (م17)',
  `amount_20` DECIMAL(18,2) NULL COMMENT 'المبلغ المسترد ◄',
  `c21` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المتبقي ◄',
  `source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نص المصدر (بيان الأستاذ)',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_onbehalf_advance_ded_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* الإقفال التعاقدي للوحدات التعاقدية — حبّة: إقفال تعاقدي واحد: عقد × وحدة × فترة سريان × عملة */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_closure` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `slot_id` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود الوحدة التعاقدية · Slot_ID',
  `code_contract_supplier` INT NULL COMMENT 'كود عقد المورد',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `c6` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نموذج العمل',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند',
  `c8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'وحدة القياس',
  `type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الفترة',
  `c10` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'بداية الفترة',
  `c11` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نهاية الفترة',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'شهر نهاية الفترة (وسم) ◄',
  `c13` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أشهر الفترة ◄',
  `month_14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الأساس الشهري المتعاقد ◄',
  `c15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المتعاقد عليه للفترة ◄',
  `surplus` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الفجوة/الفائض ◄',
  `verify` DECIMAL(9,4) NULL COMMENT 'نسبة التحقق ◄',
  `performance` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أشهر بها أداء ◄',
  `c20` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'آخر نشاط بالوحدة التعاقدية ◄',
  `supplier` DECIMAL(18,2) NULL COMMENT 'سعر وحدة المورد (م08) ◄',
  `c22` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العملة',
  `c23` DECIMAL(18,2) NULL COMMENT 'قيمة الفترة التقديرية ◄',
  `c24` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الوحدة التعاقدية (م10)',
  `closure` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الإقفال التعاقدي ◄',
  `ref_closure_month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع الإقفال الشهري (م17)',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_closure_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* التسويات وكشف الحساب — حبّة: إقفال شهري/كشف حساب: مورد × شهر × عملة */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_account` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العملة',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الشهر',
  `month_6` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مفتاح الشهر',
  `balance` DECIMAL(18,2) NULL COMMENT 'رصيد افتتاحي ◄',
  `entitlement_month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'استحقاق الشهر ◄',
  `onbehalf` VARCHAR(160) NOT NULL DEFAULT '' COMMENT '(−) مستردات نيابية (م15) ◄',
  `advance` VARCHAR(160) NOT NULL DEFAULT '' COMMENT '(−) سلف ◄',
  `penalty` VARCHAR(160) NOT NULL DEFAULT '' COMMENT '(−) جزاءات (م19) ◄',
  `c12` VARCHAR(160) NOT NULL DEFAULT '' COMMENT '(±) تسويات معتمدة أخرى',
  `net_payable` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'صافي مستحق الشهر Net_Payable ◄',
  `month_14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المدفوع خلال الشهر ◄',
  `balance_15` DECIMAL(18,2) NULL COMMENT 'رصيد ختامي ◄',
  `closure` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الإقفال',
  `line` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مراجع البنود الخاصمة',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_account_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* طلبات الدفع وحالة الصرف — حبّة: طلب دفع/دفعة واحدة */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_payment_disburse` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `date` DATE NULL COMMENT 'التاريخ',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الجهة المستفيدة',
  `payment` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'طريقة الدفع',
  `name_bank` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'اسم البنك',
  `no_account` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم الحساب',
  `name_account` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'اسم صاحب الحساب',
  `c9` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'علم طرف ثالث',
  `ref_delegation` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع تفويض الطرف الثالث (م03)',
  `project` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العميل/المشروع',
  `c12` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نظام التقسيم',
  `ref` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع التسوية (م17)',
  `c14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المستلم ج.س (لاستحقاق الجنيه)',
  `c15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المستلم بالجنيه (مدولر)',
  `disburse_source_date` DATE NULL COMMENT 'سعر الصرف (مصدره وتاريخه)',
  `c17` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المستلم الكلي $ ◄',
  `month_disburse` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مفتاح شهر الصرف',
  `month_entitlement` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'شهر الاستحقاق المسدد (كما ورد)',
  `closure` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الإقفال المخصص ◄',
  `allocation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة التخصيص',
  `c22` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الطلب',
  `disburse` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الصرف (قراءة) ◄',
  `date_disburse` DATE NULL COMMENT 'تاريخ الصرف ◄',
  `ref_disburse` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع الصرف ◄',
  `c26` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'سياق الآلية (إن ورد)',
  `payment_27` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'طبيعة الدفعة (مستخرجة) ◄',
  `source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'البيان (مصدر)',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_payment_disburse_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* تخصيص الدفع على الإقفالات — حبّة: سطر تخصيص دفعة واحد على إقفال */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_allocation_payment_closure` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `no_payment` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم طلب الدفع',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `no_closure` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم الإقفال (م17)',
  `c5` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العملة',
  `amount` DECIMAL(18,2) NULL COMMENT 'المبلغ المخصص',
  `date_allocation` DATE NULL COMMENT 'تاريخ التخصيص',
  `allocation` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'قاعدة التخصيص',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'علم تجاوز صافي الشهر ◄',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_allocation_payment_c_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* أعمار الأرصدة والالتزامات — حبّة: مورد × عملة × شريحة تقادم */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_aging_obligation` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `c2` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التسلسل الزمني للمورد ◄',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `c5` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العملة',
  `entitlement` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إجمالي الاستحقاق ◄',
  `c7` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إجمالي المدفوع ◄',
  `balance` DECIMAL(18,2) NULL COMMENT 'الرصيد القائم ◄',
  `month` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'آخر شهر حركة ◄',
  `balance_10` DECIMAL(18,2) NULL COMMENT 'عمر الرصيد (يوما) ◄',
  `c11` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'شريحة العمر ◄',
  `balance_12` DECIMAL(18,2) NULL COMMENT 'حالة الرصيد ◄',
  `supplier` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة المورد (م01) ◄',
  `c14` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التزام قادم ≤30 يوما',
  `c15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التزام قادم 31–60',
  `c16` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التزام قادم 61–90',
  `c17` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إجراء التحصيل/السداد المقترح',
  `c18` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المسؤول',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_aging_obligation_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* الملاحق والتصفية والإغلاق — حبّة: واقعة ملحق أو تصفية أو إغلاق واحدة */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_close` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `code_contract_supplier` INT NULL COMMENT 'كود عقد المورد',
  `type_close` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع وثيقة الإغلاق',
  `no` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'رقم النسخة',
  `c5` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'ما الذي تغير',
  `c6` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'سريان من',
  `date` DATE NULL COMMENT 'تاريخ التوقيع',
  `c8` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'الحالة',
  `ref_close` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مرجع تسوية الإغلاق (م17)',
  `c10` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إخلاء الطرف',
  `doc` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المستند',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_close_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* القوائم المرجعية — حبّة: قائمة مرجعية واحدة (كل قائمة عمود) */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_list_ref` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `c2` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'وحدة القياس',
  `c3` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العملة',
  `type_line` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الآلية/البند',
  `type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'بادئة النوع',
  `supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'تصنيف المورد',
  `source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'فئة مصدر القدرة',
  `supplier_8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'طبيعة المورد',
  `supplier_9` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة المورد',
  `c10` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'أساس اشتقاق الحالة',
  `type_delegation` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع التفويض',
  `type_12` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الوثيقة',
  `verify` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة التحقق',
  `type_14` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الوحدة التعاقدية',
  `c15` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التصنيف (استمرارية)',
  `role` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'الدور (أساسية/احتياطية)',
  `type_17` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الإسناد',
  `c18` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الحدث',
  `contract` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة العقد',
  `c20` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'تكييف الوثيقة',
  `source_22` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'حجية الحصة (المصدر)',
  `code_obligation` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'كود الالتزام',
  `c24` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'أطراف الثلاثية',
  `obligation` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'طرف الالتزام (م09)',
  `c26` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'قابل للاسترداد؟',
  `type_onbehalf` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الواقعة النيابية',
  `onbehalf` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة السلسلة النيابية',
  `entitlement` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الاستحقاق',
  `c30` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة التسوية',
  `c31` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نظام التقسيم',
  `payment` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'طريقة الدفع',
  `c33` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الطلب',
  `disburse` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الصرف',
  `type_penalty` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع الجزاء/المطالبة',
  `type_close` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع وثيقة الإغلاق',
  `c37` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التصنيف الاستراتيجي',
  `source_38` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مصدر القدرة',
  `migration` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'قرار الترحيل',
  `c40` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'جاهزية التوقيع',
  `c41` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'نتيجة الفحص',
  `c42` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الحصة',
  `c43` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الوضع التشغيلي',
  `c44` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الاستمرارية',
  `c45` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'طريقة الربط بالحصة',
  `supplier_46` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'طبيعة علاقة المورد بالمعدة',
  `c47` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'معالجة الاستعداد والتوقف (قاعدة)',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_list_ref_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* سجل المستندات والضمانات — حبّة: مستند أو ضمان واحد */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_doc_guarantee` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `type_doc` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع المستند',
  `ref` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المرجع',
  `no_supplier` INT NULL COMMENT 'رقم المورد',
  `name_supplier` INT NULL COMMENT 'اسم المورد (بحث)',
  `contract_supplier` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'النطاق (عقد/مورد)',
  `c7` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'الحالة',
  `date_expiry` DATE NULL COMMENT 'تاريخ الانتهاء',
  `source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المصدر',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_doc_guarantee_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* قاموس قواعد الاستنتاج — حبّة: قاعدة استنتاج واحدة */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_dictionary_rule_derivation` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `c2` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الحقل/المخرج',
  `c3` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'القيم الممكنة',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'قاعدة الاشتقاق',
  `c5` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الشيت المطبق فيه',
  `c6` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'القيد/التحذير',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_dictionary_rule_deri_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* القاموس وخريطة الترحيل — حبّة: تعريف حقل واحد */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_dictionary_migration` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `c2` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التسمية العربية',
  `c3` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الكيان',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الشيت',
  `type` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'نوع البيانات',
  `c6` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'إلزامي؟',
  `c7` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المفتاح',
  `c8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'القيم المسموحة (قائمة م24)',
  `source_owner` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'مصدر الحقيقة/المالك',
  `c11` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'تصنيف الفراغ (ما يعنيه الفراغ) ◄',
  `notes` TEXT NULL COMMENT 'ملاحظات',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_dictionary_migration_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* تتبع التعبئة والترحيل — حبّة: تحويل ترحيل موثق واحد */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_trace_migration` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'ملف المصدر',
  `source_3` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'شيت المصدر',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العمود',
  `c6` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الكيان الهدف',
  `c7` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الشيت الهدف',
  `id_8` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'معرف السجل الهدف',
  `migration` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'قرار الترحيل',
  `c10` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'التحويل المطبق',
  `migration_11` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'حالة الترحيل',
  `date_migration` DATE NULL COMMENT 'تاريخ الترحيل',
  `c13` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'المدقق',
  `c14` TEXT NULL COMMENT 'ملاحظة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_trace_migration_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* خريطة الترحيل — حبّة: عمود مصدري واحد ومصيره */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_migration` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `c2` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الاتجاه',
  `source` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'ملف/شيت المصدر',
  `c4` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'العمود/الحقل',
  `source_5` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'الوجهة/المصدر',
  `migration` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'قرار الترحيل',
  `c7` TEXT NULL COMMENT 'ملاحظة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_migration_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

/* تقرير المراجعة والقبول — حبّة: بند مراجعة/قبول واحد */
$n += $conn->query("CREATE TABLE IF NOT EXISTS `sup_report_accept` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL DEFAULT 0 COMMENT 'بوابة المستأجر',
  `line` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'البند',
  `c3` DECIMAL(18,2) NULL COMMENT 'القيمة/النتيجة',
  `c4` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'الحالة',
  `c5` TEXT NULL COMMENT 'ملاحظة',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  KEY `ix_sup_report_accept_co` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci") ? 1 : 0;

printf("✔ جداولُ أُنشئت أو كانت قائمة: %d من 25\n", $n);
