<?php
/**
 * 2028_06_01_sheet_merge_fields.php — حقولُ «سجل حقول الورقة» تصير أعمدةً في جدولِ الشاشة
 * ═══════════════════════════════════════════════════════════════════════════
 * ◆ **القرار (المالك · 2026-09-07)**: بطاقةُ «سجل حقول الورقة» كانت جدولًا ثانيًا
 *   على الشاشةِ يقرأ **قوقعةً** خاصّةً به (‏`id · company_id · created_at ·
 *   created_by · updated_at` + `gN`) لا مفتاحَ لها إلى شيء، و**97 من 98 منها
 *   صفرُ صفّ**. فالحقلُ يُدمج في **جدولِ الشاشةِ الحقيقيِّ** ليحمل بياناتِه.
 *
 * ◆ **والاسمُ من المعنى لا من الرمز**: العمودُ الجديدُ يُسمّى بالإنجليزيةِ مشتقًّا
 *   من اسمِ الحقلِ العربيِّ في «02 · تتبع الحقول» (المعجم `tools/sheet_merge/
 *   glossary.json`)، **والاسمُ العربيُّ يُحفظ في `COMMENT` العمود** — فالجسرُ
 *   بين الورقةِ والمخطَّطِ يبقى مقروءًا من المخطَّطِ نفسِه لا من ملفٍّ جانبيّ.
 *
 * ◆ **ولا يُنشأ عمودٌ لحقلٍ له نظيرٌ بالاسمِ نفسِه**: خمسةَ عشرَ حقلًا وجدت
 *   عمودَها قائمًا في جدولِ الشاشة، **فتُغذّى منه** ولا يُصنَع لها توأم.
 *
 * ⛔ **والمدى محسوم**: خمسٌ وأربعون شاشةً **قُطع فيها جدولُها الحقيقيُّ بشاهدَين**
 *   (تسمية + استعلامُ الصفحةِ نفسِها). وما التبس جدولُه **لم يُمَسّ** —
 *   يبقى بطاقتُه كما هي حتى يُقرَّر (‏`docs/sheet_merge/DEFERRED_ar.md`).
 *
 * ◆ **إجراؤها متكرِّر**: العمودُ القائمُ يُتخطّى، فتشغيلُها مرّتَين لا يضرّ.
 * ═══════════════════════════════════════════════════════════════════════════
 */
if (php_sapi_name() !== 'cli') { exit("CLI \u{641}\u{642}\u{637}\n"); }
error_reporting(E_ALL & ~E_DEPRECATED & ~E_WARNING & ~E_NOTICE);
mb_internal_encoding('UTF-8');
mysqli_report(MYSQLI_REPORT_OFF);
$t0 = microtime(true);
$ROOT = dirname(dirname(__DIR__));
require_once $ROOT . '/includes/env.php';
$host = ems_env('DB_HOST'); $port = 3306;
if (strpos($host, ':') !== false) { list($host, $port) = explode(':', $host); $port = (int) $port; }
$u = ems_env('DB_MIGRATOR_USER') ?: ems_env('DB_USER');
$p = ems_env('DB_MIGRATOR_PASS'); if ($p === null || $p === '') { $p = ems_env('DB_PASS'); }
$conn = new mysqli($host, $u, $p, ems_env('DB_NAME'), $port);
if ($conn->connect_error) { exit('\u{62A}\u{639}\u{630}\u{631} \u{627}\u{644}\u{627}\u{62A}\u{635}\u{627}\u{644}: ' . $conn->connect_error . "\n"); }
$conn->set_charset('utf8mb4');

function ems_sm_cols(mysqli $c, $t) {
    $out = array();
    $r = $c->query("SHOW COLUMNS FROM `" . $c->real_escape_string($t) . "`");
    if ($r) { while ($x = $r->fetch_assoc()) { $out[strtolower($x['Field'])] = true; } }
    return $out;
}

/* الجدولُ ⇒ [اسمُ العمود، نوعُه، اسمُ الحقلِ العربيُّ كما في ورقةِ الدليل] */
$SPEC = array(
    'contracts' => array(
        array('client_name_search', 'VARCHAR(190) NULL DEFAULT NULL', 'اسم العميل (بحث)'),
        array('project_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المشروع'),
        array('system_contract_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم العقد بالمنظومة'),
        array('company_sequence', 'DECIMAL(18,2) NULL DEFAULT NULL', 'تسلسل الشركة'),
        array('document_signature', 'VARCHAR(190) NULL DEFAULT NULL', 'توقيع الوثيقة'),
        array('contractual_start', 'DATE NULL DEFAULT NULL', 'البداية التعاقدية'),
        array('contractual_end', 'DATE NULL DEFAULT NULL', 'النهاية التعاقدية'),
        array('execution_start', 'DATE NULL DEFAULT NULL', 'البداية التنفيذية'),
        array('execution_end', 'DATE NULL DEFAULT NULL', 'النهاية التنفيذية'),
        array('commitment_cycles_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'عدد دورات الالتزام (التجديدات)'),
        array('current_contracted_units', 'VARCHAR(190) NULL DEFAULT NULL', 'الوحدات المتعاقدة الحالية'),
        array('current_monthly_capacity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'السعة الشهرية الحالية'),
        array('evidence_source', 'VARCHAR(190) NULL DEFAULT NULL', 'الحجية/مصدر التوثيق'),
        array('currency', 'VARCHAR(190) NULL DEFAULT NULL', 'العملة'),
        array('pricing_basis_as_stated', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس التسعير (كما ورد)'),
        array('unit_price_as_stated', 'VARCHAR(190) NULL DEFAULT NULL', 'سعر الوحدة (كما ورد)'),
        array('tax', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الضريبة'),
        array('payment_and_billing', 'VARCHAR(190) NULL DEFAULT NULL', 'الدفع والفوترة'),
        array('deposit_or_advance', 'VARCHAR(190) NULL DEFAULT NULL', 'الوديعة/الدفعة المقدمة'),
        array('maintenance_and_spares', 'VARCHAR(190) NULL DEFAULT NULL', 'الصيانة وقطع الغيار'),
        array('transport_and_packing', 'VARCHAR(190) NULL DEFAULT NULL', 'النقل والتعبئة'),
        array('commercial_officer', 'VARCHAR(190) NULL DEFAULT NULL', 'المسؤول التجاري'),
        array('notes', 'VARCHAR(500) NULL DEFAULT NULL', 'ملاحظات'),
        array('provided_service_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع الخدمة المقدمة'),
        array('contracting_unit_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس التعاقد (الوحدة)'),
        array('contract_signing_place', 'VARCHAR(190) NULL DEFAULT NULL', 'مكان إبرام العقد (مؤكد)'),
        array('historically_likely_place', 'VARCHAR(190) NULL DEFAULT NULL', 'المكان المرجح تاريخيا'),
        array('likely_place_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس المكان المرجح'),
        array('likely_place_evidence_level', 'DECIMAL(18,2) NULL DEFAULT NULL', 'مستوى حجية المكان المرجح'),
        array('source_state_as_stated', 'VARCHAR(190) NULL DEFAULT NULL', 'الحالة كما وردت بالمصدر'),
        array('state_change_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس تعديل الحالة'),
        array('billing_unit', 'VARCHAR(60) NULL DEFAULT NULL', 'وحدة الفوترة'),
        array('min_quantity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الحد الأدنى (كمية)'),
        array('min_level_frequency', 'VARCHAR(190) NULL DEFAULT NULL', 'دورية الحد الأدنى'),
        array('guaranteed_quantity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الكمية المضمونة'),
        array('billing_threshold', 'DECIMAL(18,2) NULL DEFAULT NULL', 'عتبة الفوترة'),
        array('shortage_bearer', 'VARCHAR(190) NULL DEFAULT NULL', 'متحمل العجز'),
        array('shortage_rule', 'VARCHAR(190) NULL DEFAULT NULL', 'قاعدة العجز'),
        array('price_structure', 'VARCHAR(190) NULL DEFAULT NULL', 'بنية السعر'),
        array('price_versions_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'عدد النسخ/المكونات السعرية'),
        array('pricing_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع تسعيري'),
    ),
    'employee_contracts' => array(
        array('contract_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف العقد'),
        array('employee_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الموظف'),
        array('wage_model', 'VARCHAR(60) NULL DEFAULT NULL', 'نموذج الأجر'),
        array('basic_wage', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الأجر الأساسي'),
        array('allowances', 'VARCHAR(190) NULL DEFAULT NULL', 'البدلات'),
        array('date_from', 'DATE NULL DEFAULT NULL', 'من تاريخ'),
        array('date_to', 'DATE NULL DEFAULT NULL', 'إلى تاريخ'),
        array('project_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المشروع'),
        array('signed_contract_attachment', 'VARCHAR(500) NULL DEFAULT NULL', 'مرفق العقد الموقع'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'employees' => array(
        array('employee_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الموظف'),
        array('national_id', 'VARCHAR(190) NULL DEFAULT NULL', 'الرقم الوطني'),
        array('type', 'VARCHAR(190) NULL DEFAULT NULL', 'النوع'),
        array('marital_status', 'VARCHAR(60) NULL DEFAULT NULL', 'الحالة الاجتماعية'),
        array('commencement_date', 'DATE NULL DEFAULT NULL', 'تاريخ المباشرة'),
        array('is_operational_operator', 'TINYINT(1) NULL DEFAULT NULL', 'مشغل تشغيلي؟'),
        array('workforce_operator_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المشغل بالقوى'),
        array('contact_details', 'VARCHAR(500) NULL DEFAULT NULL', 'بيانات التواصل'),
        array('emergency_contact', 'VARCHAR(190) NULL DEFAULT NULL', 'شخص الطوارئ'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'exec_approvals' => array(
        array('request_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'Request_ID'),
        array('source_department', 'VARCHAR(190) NULL DEFAULT NULL', 'Source_Department'),
        array('request_type', 'VARCHAR(60) NULL DEFAULT NULL', 'Request_Type'),
        array('deputy_role', 'VARCHAR(190) NULL DEFAULT NULL', 'Deputy_Role'),
        array('approval_scope', 'VARCHAR(60) NULL DEFAULT NULL', 'Approval_Scope'),
        array('previous_approval', 'VARCHAR(190) NULL DEFAULT NULL', 'Previous_Approval'),
        array('recommendation', 'VARCHAR(190) NULL DEFAULT NULL', 'Recommendation'),
        array('documents', 'VARCHAR(190) NULL DEFAULT NULL', 'Documents'),
        array('risk', 'VARCHAR(190) NULL DEFAULT NULL', 'Risk'),
        array('deputy_decision', 'VARCHAR(60) NULL DEFAULT NULL', 'Deputy_Decision'),
        array('conditions', 'VARCHAR(190) NULL DEFAULT NULL', 'Conditions'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'fin_currencies' => array(
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('currency', 'VARCHAR(190) NULL DEFAULT NULL', 'العملة'),
        array('counterparty', 'VARCHAR(190) NULL DEFAULT NULL', 'مقابل'),
        array('effective_date', 'DATE NULL DEFAULT NULL', 'تاريخ السريان'),
        array('source_documentation', 'VARCHAR(190) NULL DEFAULT NULL', 'المصدر/التوثيق'),
        array('line_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة السطر'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'fin_dues' => array(
        array('due_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف الاستحقاق'),
        array('supplier_invoice_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم فاتورة المورد'),
        array('supplier_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المورد'),
        array('due_source', 'VARCHAR(190) NULL DEFAULT NULL', 'مصدر الاستحقاق'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
        array('gate_check', 'VARCHAR(60) NULL DEFAULT NULL', 'فحص البوابة'),
        array('tax', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الضريبة'),
        array('due_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الاستحقاق'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
    ),
    'fin_financial_periods' => array(
        array('period_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف الفترة'),
        array('month', 'VARCHAR(190) NULL DEFAULT NULL', 'الشهر'),
        array('period_entries', 'VARCHAR(190) NULL DEFAULT NULL', 'قيود الفترة'),
        array('pending_entries', 'VARCHAR(190) NULL DEFAULT NULL', 'قيود معلقة'),
        array('warehouse_match', 'VARCHAR(60) NULL DEFAULT NULL', 'مطابقة المخازن'),
        array('treasury_match', 'VARCHAR(60) NULL DEFAULT NULL', 'مطابقة الخزينة'),
        array('incoming_ops_closures', 'VARCHAR(190) NULL DEFAULT NULL', 'الإقفالات التشغيلية الواردة'),
        array('processing_variances', 'VARCHAR(190) NULL DEFAULT NULL', 'فروق معالجة'),
        array('closing_decision', 'VARCHAR(60) NULL DEFAULT NULL', 'قرار الإقفال'),
        array('reopen_decision', 'VARCHAR(60) NULL DEFAULT NULL', 'قرار إعادة الفتح'),
        array('period_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الفترة'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'fin_requests' => array(
        array('request_details', 'VARCHAR(500) NULL DEFAULT NULL', 'تفاصيل الطلب'),
        array('attachment', 'VARCHAR(190) NULL DEFAULT NULL', 'المرفق'),
        array('decision_owner_party', 'VARCHAR(190) NULL DEFAULT NULL', 'الجهة المالكة للقرار'),
        array('approval_route', 'VARCHAR(190) NULL DEFAULT NULL', 'مسار الاعتماد'),
        array('request_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الطلب'),
        array('party_decision', 'VARCHAR(60) NULL DEFAULT NULL', 'قرار الجهة'),
        array('decision_date', 'DATE NULL DEFAULT NULL', 'تاريخ القرار'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
    ),
    'housing_unit' => array(
        array('occupied_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'المشغولة'),
        array('vacant_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الشاغرة'),
        array('supervisor', 'VARCHAR(190) NULL DEFAULT NULL', 'المشرف'),
        array('maintenance_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الصيانة'),
        array('unit_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الوحدة'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'mnt_breakdown' => array(
        array('intake_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف الاستقبال'),
        array('report_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم البلاغ'),
        array('report_date', 'DATE NULL DEFAULT NULL', 'تاريخ البلاغ'),
        array('amount', 'DECIMAL(18,2) NULL DEFAULT NULL', 'المبلغ'),
        array('equipment_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المعدة'),
        array('location', 'VARCHAR(190) NULL DEFAULT NULL', 'الموقع'),
        array('fault_description', 'VARCHAR(500) NULL DEFAULT NULL', 'وصف العطل'),
        array('initial_tree_node', 'VARCHAR(190) NULL DEFAULT NULL', 'عقدة الشجرة المبدئية'),
        array('severity_degree', 'DECIMAL(18,2) NULL DEFAULT NULL', 'درجة الخطورة'),
        array('equipment_stopped', 'TINYINT(1) NULL DEFAULT NULL', 'المعدة متوقفة؟'),
        array('stoppage_impact', 'VARCHAR(190) NULL DEFAULT NULL', 'أثر الإيقاف'),
        array('intake_decision', 'VARCHAR(60) NULL DEFAULT NULL', 'قرار الاستقبال'),
        array('branched_inspection_req_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم طلب الفحص المتفرع'),
        array('intake_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الاستقبال'),
        array('fault_severity', 'VARCHAR(60) NULL DEFAULT NULL', 'شدة العطل الفني'),
        array('downtime_duration', 'DECIMAL(18,2) NULL DEFAULT NULL', 'مدة التوقف'),
        array('operational_impact', 'VARCHAR(190) NULL DEFAULT NULL', 'الأثر التشغيلي'),
        array('preventability', 'VARCHAR(190) NULL DEFAULT NULL', 'قابلية المنع'),
        array('recurrence', 'VARCHAR(190) NULL DEFAULT NULL', 'التكرار'),
        array('response_performance', 'VARCHAR(190) NULL DEFAULT NULL', 'أداء الاستجابة'),
        array('delay_reason', 'VARCHAR(500) NULL DEFAULT NULL', 'سبب التأخير'),
        array('chain_of_responsibility', 'VARCHAR(190) NULL DEFAULT NULL', 'سلسلة المسؤولية'),
        array('equipment_stop_time', 'DATETIME NULL DEFAULT NULL', 'وقت توقف المعدة'),
        array('operator_report_time', 'DATETIME NULL DEFAULT NULL', 'وقت إبلاغ المشغل'),
        array('maintenance_receipt_time', 'DATETIME NULL DEFAULT NULL', 'وقت استلام الصيانة'),
        array('diagnosis_start_time', 'DATETIME NULL DEFAULT NULL', 'وقت بدء التشخيص'),
        array('diagnosis_end_time', 'DATETIME NULL DEFAULT NULL', 'وقت انتهاء التشخيص'),
        array('part_request_time', 'DATETIME NULL DEFAULT NULL', 'وقت طلب القطعة'),
        array('part_available_time', 'DATETIME NULL DEFAULT NULL', 'وقت توفر القطعة'),
        array('site_arrival_time', 'DATETIME NULL DEFAULT NULL', 'وقت وصولها للموقع'),
        array('technician_arrival_time', 'DATETIME NULL DEFAULT NULL', 'وقت حضور الفني'),
        array('repair_start_time', 'DATETIME NULL DEFAULT NULL', 'وقت بدء الإصلاح'),
        array('repair_end_time', 'DATETIME NULL DEFAULT NULL', 'وقت انتهاء الإصلاح'),
        array('test_time', 'DATETIME NULL DEFAULT NULL', 'وقت الاختبار'),
        array('certification_time', 'DATETIME NULL DEFAULT NULL', 'وقت التصديق'),
        array('equipment_back_in_service_time', 'DATETIME NULL DEFAULT NULL', 'وقت عودة المعدة للخدمة'),
        array('downtime_total', 'DECIMAL(18,2) NULL DEFAULT NULL', 'إجمالي التوقف'),
        array('actual_repair_time', 'DATETIME NULL DEFAULT NULL', 'زمن الإصلاح الفعلي'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'mnt_daily_care' => array(
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('equipment_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المعدة'),
        array('care_checklist_for_type', 'VARCHAR(60) NULL DEFAULT NULL', 'قائمة العناية للنوع'),
        array('executor', 'VARCHAR(190) NULL DEFAULT NULL', 'المنفذ'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'mnt_external_repair' => array(
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('external_party_supplier', 'VARCHAR(190) NULL DEFAULT NULL', 'الجهة الخارجية/المورد'),
        array('contract_or_guarantee_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع العقد/الضمان'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'mnt_kpi_period' => array(
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('equipment_or_type', 'VARCHAR(60) NULL DEFAULT NULL', 'المعدة/النوع'),
        array('executed_preventive_orders', 'VARCHAR(190) NULL DEFAULT NULL', 'أوامر الوقائية المنفذة'),
        array('maintenance_cost_per_hour', 'VARCHAR(190) NULL DEFAULT NULL', 'تكلفة الصيانة للساعة'),
    ),
    'mnt_part_request' => array(
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('requested_items', 'VARCHAR(190) NULL DEFAULT NULL', 'البنود المطلوبة'),
        array('custody_receiver', 'VARCHAR(190) NULL DEFAULT NULL', 'مستلم العهدة'),
        array('issue_note_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم سند الصرف'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'mnt_repeat_repair' => array(
        array('event_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف الواقعة'),
        array('equipment_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المعدة'),
        array('original_order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر الأصلي'),
        array('within_certificate_validity', 'TINYINT(1) NULL DEFAULT NULL', 'ضمن صلاحية الشهادة؟'),
        array('root_cause_analysis', 'VARCHAR(500) NULL DEFAULT NULL', 'تحليل السبب الجذري RCA'),
        array('new_order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر الجديد'),
        array('decision', 'VARCHAR(190) NULL DEFAULT NULL', 'القرار'),
        array('event_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الواقعة'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'payroll_runs' => array(
        array('payroll_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف المسير'),
        array('payroll_scope', 'VARCHAR(60) NULL DEFAULT NULL', 'نطاق المسير'),
        array('employees_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'عدد الموظفين'),
        array('basic_total', 'DECIMAL(18,2) NULL DEFAULT NULL', 'إجمالي الأساسي'),
        array('allowances_total', 'DECIMAL(18,2) NULL DEFAULT NULL', 'إجمالي البدلات'),
        array('production_incentives', 'VARCHAR(190) NULL DEFAULT NULL', 'حوافز الإنتاج'),
        array('operator_workforce_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس القوى للمشغلين'),
        array('payroll_net', 'DECIMAL(18,2) NULL DEFAULT NULL', 'صافي المسير'),
        array('finance_referral', 'VARCHAR(190) NULL DEFAULT NULL', 'الإحالة للمالية'),
        array('treasury_referral', 'VARCHAR(190) NULL DEFAULT NULL', 'الإحالة للخزينة'),
        array('payroll_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة المسير'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'proc_award' => array(
        array('rfq_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم طلب العروض'),
        array('compared_offers', 'VARCHAR(190) NULL DEFAULT NULL', 'العروض المقارنة'),
        array('comparison_table', 'VARCHAR(190) NULL DEFAULT NULL', 'جدول المقارنة'),
        array('awarded_offer', 'VARCHAR(190) NULL DEFAULT NULL', 'العرض المرسى عليه'),
        array('award_value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'قيمة الترسية'),
        array('selection_justification', 'VARCHAR(500) NULL DEFAULT NULL', 'مبرر الاختيار'),
        array('justification_detail', 'VARCHAR(190) NULL DEFAULT NULL', 'تفصيل المبرر'),
        array('committee_members', 'VARCHAR(500) NULL DEFAULT NULL', 'أعضاء اللجنة'),
        array('award_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الترسية'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('approval_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاعتماد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'proc_delivery_event' => array(
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('covered_quantity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الكمية المشمولة'),
        array('grn_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم سند الإدخال'),
        array('inspection_result', 'VARCHAR(60) NULL DEFAULT NULL', 'نتيجة الفحص'),
        array('supplier_notification', 'VARCHAR(190) NULL DEFAULT NULL', 'إخطار المورد'),
        array('line_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة السطر'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'proc_hazmat_control' => array(
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('item_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود الصنف'),
        array('severity_category', 'VARCHAR(60) NULL DEFAULT NULL', 'فئة الخطورة'),
        array('statutory_permit', 'VARCHAR(190) NULL DEFAULT NULL', 'التصريح النظامي'),
        array('isolation_location', 'VARCHAR(190) NULL DEFAULT NULL', 'موقع العزل'),
        array('authorized_custodian', 'VARCHAR(190) NULL DEFAULT NULL', 'أمين العهدة المخول'),
        array('batch_tracking_required', 'TINYINT(1) NULL DEFAULT NULL', 'تتبع الدفعة إلزامي؟'),
        array('disbursement_authority', 'VARCHAR(190) NULL DEFAULT NULL', 'سلطة الصرف'),
        array('dual_control', 'TINYINT(1) NULL DEFAULT NULL', 'رقابة مزدوجة؟'),
        array('validity_constraint', 'VARCHAR(190) NULL DEFAULT NULL', 'قيد الصلاحية'),
        array('disposal_route', 'VARCHAR(190) NULL DEFAULT NULL', 'مسار الإتلاف'),
        array('controls_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الضوابط'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'proc_invoice_match' => array(
        array('match_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المطابقة'),
        array('supplier_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المورد'),
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('grn_notes', 'VARCHAR(500) NULL DEFAULT NULL', 'سندات الإدخال'),
        array('received_value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'قيمة المستلم'),
        array('variance_classification', 'VARCHAR(190) NULL DEFAULT NULL', 'تصنيف الفرق'),
        array('variance_value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'قيمة الفرق'),
        array('variance_explanation', 'VARCHAR(500) NULL DEFAULT NULL', 'تفسير الفرق'),
        array('finance_referral', 'VARCHAR(190) NULL DEFAULT NULL', 'الإحالة للمالية'),
        array('match_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة المطابقة'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'proc_issue_request' => array(
        array('item_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف البند'),
        array('request_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الطلب'),
        array('item_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود الصنف'),
        array('requested_quantity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الكمية المطلوبة'),
        array('approved_quantity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الكمية المعتمدة'),
        array('cumulative_spend', 'DECIMAL(18,2) NULL DEFAULT NULL', 'المصروف تراكميا'),
        array('remaining', 'DECIMAL(18,2) NULL DEFAULT NULL', 'المتبقي'),
        array('item_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البند'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
        array('arrival_date', 'DATE NULL DEFAULT NULL', 'تاريخ الورود'),
        array('issue_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع الصرف'),
        array('justifying_reference', 'VARCHAR(190) NULL DEFAULT NULL', 'المرجع الموجب'),
        array('reference_check', 'VARCHAR(60) NULL DEFAULT NULL', 'فحص المرجع'),
        array('requested_items', 'VARCHAR(190) NULL DEFAULT NULL', 'البنود المطلوبة'),
        array('balance_check', 'VARCHAR(60) NULL DEFAULT NULL', 'فحص الرصيد'),
        array('warehouse_decision', 'VARCHAR(60) NULL DEFAULT NULL', 'قرار المخزن'),
        array('request_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الطلب'),
    ),
    'proc_offer' => array(
        array('offer_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف العرض'),
        array('rfq_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم طلب العروض'),
        array('supplier_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المورد'),
        array('supplier_name', 'VARCHAR(190) NULL DEFAULT NULL', 'اسم المورد'),
        array('receipt_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاستلام'),
        array('offer_value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'قيمة العرض'),
        array('offered_payment_terms', 'VARCHAR(500) NULL DEFAULT NULL', 'شروط الدفع المعروضة'),
        array('offer_validity', 'VARCHAR(190) NULL DEFAULT NULL', 'صلاحية العرض'),
        array('technical_evaluation', 'VARCHAR(190) NULL DEFAULT NULL', 'التقييم الفني'),
        array('inspection_notes', 'VARCHAR(500) NULL DEFAULT NULL', 'ملاحظات الفحص'),
        array('financial_arrangement', 'VARCHAR(190) NULL DEFAULT NULL', 'الترتيب المالي'),
        array('offer_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة العرض'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('request_item_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع بند الطلب'),
        array('item_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود الصنف'),
        array('offered_unit_price', 'DECIMAL(18,2) NULL DEFAULT NULL', 'سعر الوحدة المعروض'),
        array('quantity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الكمية'),
        array('item_lead_time', 'DATETIME NULL DEFAULT NULL', 'مدة التوريد للبند'),
        array('alternative_proposed', 'TINYINT(1) NULL DEFAULT NULL', 'بديل مقترح؟'),
        array('technical_note', 'VARCHAR(500) NULL DEFAULT NULL', 'ملاحظة فنية'),
        array('item_financial_ranking', 'VARCHAR(190) NULL DEFAULT NULL', 'ترتيب البند ماليا'),
    ),
    'proc_order' => array(
        array('order_date', 'DATE NULL DEFAULT NULL', 'تاريخ الأمر'),
        array('minutes_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المحضر'),
        array('supplier_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المورد'),
        array('framework_contract_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'عقد إطاري مرجعي'),
        array('items_count_ref_sh07_2', 'VARCHAR(190) NULL DEFAULT NULL', 'عدد البنود تفصيلها ش07-2'),
        array('total_value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'القيمة الإجمالية'),
        array('delivery_place', 'VARCHAR(190) NULL DEFAULT NULL', 'مكان التسليم'),
        array('delay_penalty', 'DECIMAL(18,2) NULL DEFAULT NULL', 'غرامة التأخير'),
        array('order_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الأمر'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'proc_request' => array(
        array('requesting_party', 'VARCHAR(190) NULL DEFAULT NULL', 'الجهة الطالبة'),
        array('charged_project', 'VARCHAR(190) NULL DEFAULT NULL', 'المشروع المحمل'),
        array('items_count_ref_sh02_2', 'VARCHAR(190) NULL DEFAULT NULL', 'عدد البنود تفصيلها ش02-2'),
        array('required_date', 'DATE NULL DEFAULT NULL', 'التاريخ المطلوب'),
        array('initial_estimate', 'VARCHAR(190) NULL DEFAULT NULL', 'التقدير المبدئي'),
        array('request_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الطلب'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
    ),
    'proc_supplier_eval' => array(
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('supplier_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المورد'),
        array('its_value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'قيمتها'),
        array('schedule_adherence', 'VARCHAR(190) NULL DEFAULT NULL', 'الالتزام بالمواعيد'),
        array('average_delay', 'VARCHAR(190) NULL DEFAULT NULL', 'متوسط التأخير'),
        array('inspection_rejection_rate', 'DECIMAL(18,2) NULL DEFAULT NULL', 'نسبة رفض الفحص'),
        array('match_variances', 'VARCHAR(190) NULL DEFAULT NULL', 'فروق المطابقة'),
        array('composite_index', 'DECIMAL(18,2) NULL DEFAULT NULL', 'المؤشر المركب'),
        array('resulting_classification', 'VARCHAR(190) NULL DEFAULT NULL', 'التصنيف الناتج'),
    ),
    'proc_transfer' => array(
        array('order_date', 'DATE NULL DEFAULT NULL', 'تاريخ الأمر'),
        array('items_count_ref_kh09_2', 'VARCHAR(190) NULL DEFAULT NULL', 'عدد البنود تفصيلها خ09-2'),
        array('transfer_justification', 'VARCHAR(500) NULL DEFAULT NULL', 'مبرر التحويل'),
        array('transport_mode', 'VARCHAR(60) NULL DEFAULT NULL', 'وسيلة النقل'),
        array('gate_pass', 'VARCHAR(190) NULL DEFAULT NULL', 'سند الخروج'),
        array('receipt_note', 'VARCHAR(500) NULL DEFAULT NULL', 'سند الاستلام'),
        array('receipt_match', 'VARCHAR(60) NULL DEFAULT NULL', 'مطابقة الاستلام'),
        array('order_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الأمر'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'proc_warehouse' => array(
        array('warehouse_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المخزن'),
        array('warehouse_name', 'VARCHAR(190) NULL DEFAULT NULL', 'اسم المخزن'),
        array('warehouse_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع المخزن'),
        array('custodian_on_duty', 'VARCHAR(190) NULL DEFAULT NULL', 'الأمين النافذ اليوم'),
        array('custody_method', 'VARCHAR(190) NULL DEFAULT NULL', 'أسلوب العهدة'),
        array('special_licence', 'VARCHAR(190) NULL DEFAULT NULL', 'ترخيص خاص'),
        array('storage_capacity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'سعة التخزين'),
        array('safety_controls', 'VARCHAR(500) NULL DEFAULT NULL', 'ضوابط السلامة'),
        array('warehouse_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة المخزن'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('approval_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاعتماد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'proc_wh_close' => array(
        array('closing_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف الإقفال'),
        array('month', 'VARCHAR(190) NULL DEFAULT NULL', 'الشهر'),
        array('month_grn_notes', 'VARCHAR(500) NULL DEFAULT NULL', 'سندات إدخال الشهر'),
        array('month_issue_notes', 'VARCHAR(500) NULL DEFAULT NULL', 'سندات صرف الشهر'),
        array('month_transfers', 'VARCHAR(190) NULL DEFAULT NULL', 'تحويلات الشهر'),
        array('settled_count_variances', 'VARCHAR(190) NULL DEFAULT NULL', 'فروق جرد مسواة'),
        array('open_custodies_carried', 'VARCHAR(190) NULL DEFAULT NULL', 'عهد مفتوحة مرحلة'),
        array('closing_stock_value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'قيمة المخزون الختامية'),
        array('finance_match', 'VARCHAR(60) NULL DEFAULT NULL', 'مطابقة المالية'),
        array('closing_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الإقفال'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('approval_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاعتماد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'project' => array(
        array('project_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المشروع'),
        array('client_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم العميل'),
        array('client_name_search', 'VARCHAR(190) NULL DEFAULT NULL', 'اسم العميل (بحث)'),
        array('description', 'VARCHAR(500) NULL DEFAULT NULL', 'الوصف'),
        array('execution_scope_location', 'VARCHAR(190) NULL DEFAULT NULL', 'الموقع (نطاق تنفيذ)'),
        array('sector', 'VARCHAR(190) NULL DEFAULT NULL', 'القطاع'),
        array('project_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة المشروع'),
        array('start_date', 'DATE NULL DEFAULT NULL', 'تاريخ البداية'),
        array('commercial_officer', 'VARCHAR(190) NULL DEFAULT NULL', 'المسؤول التجاري'),
        array('estimated_value_usd', 'VARCHAR(190) NULL DEFAULT NULL', 'القيمة التقديرية ($)'),
        array('estimated_value_sdg', 'VARCHAR(190) NULL DEFAULT NULL', 'القيمة التقديرية (ج.س)'),
        array('contracts_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'عدد العقود'),
        array('notes', 'VARCHAR(500) NULL DEFAULT NULL', 'ملاحظات'),
        array('client_side_project_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المشروع لدى العميل'),
        array('region_state', 'VARCHAR(60) NULL DEFAULT NULL', 'الإقليم/الولاية'),
        array('client_project_sequence', 'DECIMAL(18,2) NULL DEFAULT NULL', 'تسلسل مشروع العميل'),
        array('service_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع الخدمة'),
        array('work_model', 'VARCHAR(60) NULL DEFAULT NULL', 'نموذج العمل'),
        array('naming_and_bounds_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس التسمية والحدود'),
        array('grouping_rule', 'VARCHAR(190) NULL DEFAULT NULL', 'قاعدة التجميع'),
        array('evidence_level', 'DECIMAL(18,2) NULL DEFAULT NULL', 'مستوى الحجية'),
    ),
    'risk_register' => array(
        array('risk_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'Risk_ID'),
        array('risk_title', 'VARCHAR(190) NULL DEFAULT NULL', 'عنوان الخطر'),
        array('classification_node', 'VARCHAR(190) NULL DEFAULT NULL', 'عقدة التصنيف'),
        array('family', 'VARCHAR(190) NULL DEFAULT NULL', 'العائلة'),
        array('identification_source', 'VARCHAR(190) NULL DEFAULT NULL', 'مصدر التحديد'),
        array('source_event_key', 'VARCHAR(80) NULL DEFAULT NULL', 'مفتاح الحدث/السجل الأصلي'),
        array('affected_entity', 'VARCHAR(190) NULL DEFAULT NULL', 'الكيان المتأثر'),
        array('entity_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع الكيان'),
        array('affected_operating_unit', 'VARCHAR(60) NULL DEFAULT NULL', 'الوحدة التشغيلية المتأثرة'),
        array('risk_description', 'VARCHAR(500) NULL DEFAULT NULL', 'وصف الخطر'),
        array('risk_owner', 'VARCHAR(190) NULL DEFAULT NULL', 'Risk_Owner'),
        array('identification_date', 'DATE NULL DEFAULT NULL', 'تاريخ التحديد'),
        array('last_assessment', 'VARCHAR(190) NULL DEFAULT NULL', 'آخر تقييم'),
        array('current_residual_level', 'DECIMAL(18,2) NULL DEFAULT NULL', 'المستوى المتبقي الحالي'),
        array('risk_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الخطر'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('approval_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاعتماد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'risk_treatments' => array(
        array('action_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف الإجراء'),
        array('risk_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'Risk_ID'),
        array('processing_route', 'VARCHAR(190) NULL DEFAULT NULL', 'مسار المعالجة'),
        array('action_description', 'VARCHAR(500) NULL DEFAULT NULL', 'وصف الإجراء'),
        array('owner_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المالك'),
        array('executing_department', 'VARCHAR(190) NULL DEFAULT NULL', 'الإدارة المنفذة'),
        array('target_level_after_action', 'VARCHAR(190) NULL DEFAULT NULL', 'المستوى المستهدف بعد الإجراء'),
        array('delay_days', 'DECIMAL(18,2) NULL DEFAULT NULL', 'أيام التأخير'),
        array('reassess_after', 'VARCHAR(190) NULL DEFAULT NULL', 'إعادة التقييم بعده'),
        array('action_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الإجراء'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'sal_client_needs' => array(
        array('request_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الطلب'),
        array('client_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم العميل'),
        array('client_name_search', 'VARCHAR(190) NULL DEFAULT NULL', 'اسم العميل (بحث)'),
        array('project_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المشروع'),
        array('opportunity_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الفرصة'),
        array('request_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع الطلب'),
        array('request_scope', 'VARCHAR(60) NULL DEFAULT NULL', 'نطاق الطلب'),
        array('requested_service', 'VARCHAR(190) NULL DEFAULT NULL', 'الخدمة المطلوبة'),
        array('required_work_model', 'VARCHAR(60) NULL DEFAULT NULL', 'نموذج العمل المطلوب'),
        array('unit', 'VARCHAR(190) NULL DEFAULT NULL', 'الوحدة'),
        array('requested_qty_or_volume', 'VARCHAR(190) NULL DEFAULT NULL', 'الكمية/الحجم المطلوب'),
        array('required_machine_types', 'VARCHAR(190) NULL DEFAULT NULL', 'أنواع الآليات المطلوبة'),
        array('machines_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'عدد الآليات'),
        array('expected_start', 'DATE NULL DEFAULT NULL', 'البداية المتوقعة'),
        array('expected_end', 'DATE NULL DEFAULT NULL', 'النهاية المتوقعة'),
        array('expected_start_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس البداية المتوقعة'),
        array('expected_end_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس النهاية المتوقعة'),
        array('dates_data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة بيانات التواريخ'),
        array('core_commercial_requirements', 'VARCHAR(500) NULL DEFAULT NULL', 'المتطلبات التجارية الأساسية'),
        array('receipt_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاستلام'),
        array('offer_response_due', 'DATE NULL DEFAULT NULL', 'موعد الرد بالعرض'),
        array('resulting_contract_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع العقد الناتج'),
        array('source_commitment_cycle_key', 'VARCHAR(80) NULL DEFAULT NULL', 'مفتاح دورة الالتزام المصدر'),
        array('evidence_level', 'DECIMAL(18,2) NULL DEFAULT NULL', 'مستوى الحجية'),
        array('residual_value_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس القيمة الرجعية'),
    ),
    'sal_quotation_lines' => array(
        array('item_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم البند'),
        array('offer_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم العرض'),
        array('contract_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع العقد'),
        array('item_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع البند'),
        array('service_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع الخدمة'),
        array('equipment_or_item_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع المعدة/البند'),
        array('work_model', 'VARCHAR(60) NULL DEFAULT NULL', 'نموذج العمل'),
        array('equipment_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'عدد المعدات'),
        array('monthly_unit_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس الوحدة الشهري'),
        array('duration_months', 'DECIMAL(18,2) NULL DEFAULT NULL', 'المدة (أشهر)'),
        array('quantity_or_target', 'VARCHAR(190) NULL DEFAULT NULL', 'الكمية/المستهدف'),
        array('measure_unit', 'VARCHAR(60) NULL DEFAULT NULL', 'وحدة القياس'),
        array('value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'القيمة'),
        array('price_version_effective_from', 'DATE NULL DEFAULT NULL', 'سريان النسخة السعرية'),
        array('price_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس السعر'),
        array('tax_as_stated', 'VARCHAR(190) NULL DEFAULT NULL', 'الضريبة كما وردت'),
        array('price_text_as_stated', 'VARCHAR(500) NULL DEFAULT NULL', 'نص السعر كما ورد بالمصدر'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('commercial_notes', 'VARCHAR(500) NULL DEFAULT NULL', 'ملاحظات تجارية'),
        array('source_commitment_cycle_key', 'VARCHAR(80) NULL DEFAULT NULL', 'مفتاح دورة الالتزام المصدر'),
        array('evidence_level', 'DECIMAL(18,2) NULL DEFAULT NULL', 'مستوى الحجية'),
        array('residual_value_basis', 'VARCHAR(190) NULL DEFAULT NULL', 'أساس القيمة الرجعية'),
    ),
    'scr_op_monthly' => array(
        array('plan_line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف سطر الخطة'),
        array('plan_month', 'VARCHAR(60) NULL DEFAULT NULL', 'شهر الخطة'),
        array('project_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم المشروع'),
        array('project_name', 'VARCHAR(190) NULL DEFAULT NULL', 'اسم المشروع'),
        array('client_contract_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود عقد العميل'),
        array('equipment_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المعدة'),
        array('equipment_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع المعدة'),
        array('work_model', 'VARCHAR(60) NULL DEFAULT NULL', 'نموذج العمل'),
        array('contractual_target', 'VARCHAR(190) NULL DEFAULT NULL', 'المستهدف التعاقدي'),
        array('plan_target', 'VARCHAR(190) NULL DEFAULT NULL', 'مستهدف الخطة'),
        array('measure_unit', 'VARCHAR(60) NULL DEFAULT NULL', 'وحدة القياس'),
        array('planned_work_days', 'DECIMAL(18,2) NULL DEFAULT NULL', 'أيام العمل المخططة'),
        array('day_shifts', 'DECIMAL(18,2) NULL DEFAULT NULL', 'ورديات اليوم'),
        array('available_hours_per_shift', 'VARCHAR(190) NULL DEFAULT NULL', 'الساعات المتاحة/وردية'),
        array('season_factor', 'DECIMAL(18,2) NULL DEFAULT NULL', 'معامل الموسم'),
        array('season_adjusted_target', 'VARCHAR(190) NULL DEFAULT NULL', 'المستهدف المعاير بالموسم'),
        array('contractual_variance_reason', 'VARCHAR(500) NULL DEFAULT NULL', 'مبرر الفارق عن التعاقدي'),
        array('line_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة السطر'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('approval_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاعتماد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'ticket_sla_policies' => array(
        array('line_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السطر'),
        array('report_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع البلاغ'),
        array('responsible_department', 'VARCHAR(190) NULL DEFAULT NULL', 'الإدارة المسؤولة'),
        array('response_sla', 'VARCHAR(190) NULL DEFAULT NULL', 'Response SLA'),
        array('resolution_sla', 'VARCHAR(190) NULL DEFAULT NULL', 'Resolution SLA'),
        array('escalation_ladder', 'VARCHAR(190) NULL DEFAULT NULL', 'سلم التصعيد'),
        array('matrix_effective_from', 'DATE NULL DEFAULT NULL', 'سريان المصفوفة'),
        array('line_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة السطر'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'timesheet' => array(
        array('record_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف السجل'),
        array('operating_day', 'DATE NULL DEFAULT NULL', 'يوم التشغيل'),
        array('equipment_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المعدة'),
        array('equipment_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع المعدة'),
        array('submitting_supplier', 'VARCHAR(190) NULL DEFAULT NULL', 'المورد المقدم'),
        array('project_contract_unit', 'VARCHAR(60) NULL DEFAULT NULL', 'وحدة عقد المشروع'),
        array('annual_container_key', 'VARCHAR(80) NULL DEFAULT NULL', 'مفتاح الحاوية السنوية'),
        array('monthly_container_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الحاوية الشهرية'),
        array('slot_code_and_occupancy', 'VARCHAR(190) NULL DEFAULT NULL', 'كود الخانة ونوع الإشغال'),
        array('outside_contract_window_flag', 'VARCHAR(60) NULL DEFAULT NULL', 'وسم خارج النافذة التعاقدية'),
        array('current_location', 'VARCHAR(190) NULL DEFAULT NULL', 'الموقع الحالي'),
        array('work_zone', 'VARCHAR(190) NULL DEFAULT NULL', 'منطقة العمل'),
        array('operator_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المشغل'),
        array('work_model', 'VARCHAR(60) NULL DEFAULT NULL', 'نموذج العمل'),
        array('default_change_reason', 'VARCHAR(500) NULL DEFAULT NULL', 'سبب تعديل الافتراضي'),
        array('available_hours', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الساعات المتاحة'),
        array('executed_quantity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'الكمية المنفذة'),
        array('measure_unit', 'VARCHAR(60) NULL DEFAULT NULL', 'وحدة القياس'),
        array('meter_start_of_shift', 'VARCHAR(190) NULL DEFAULT NULL', 'قراءة العداد أول الوردية'),
        array('meter_end_of_shift', 'VARCHAR(190) NULL DEFAULT NULL', 'قراءة العداد آخر الوردية'),
        array('meter_hours', 'DECIMAL(18,2) NULL DEFAULT NULL', 'ساعات العداد'),
        array('actual_total', 'DECIMAL(18,2) NULL DEFAULT NULL', 'إجمالي الفعلي'),
        array('standby_total', 'DECIMAL(18,2) NULL DEFAULT NULL', 'إجمالي الاستعداد'),
        array('downtime_total', 'DECIMAL(18,2) NULL DEFAULT NULL', 'إجمالي التوقف'),
        array('capacity_exceeded', 'TINYINT(1) NULL DEFAULT NULL', 'تجاوز الطاقة؟'),
        array('override_reason', 'VARCHAR(500) NULL DEFAULT NULL', 'سبب التجاوز'),
        array('field_reference', 'VARCHAR(190) NULL DEFAULT NULL', 'المرجع الميداني'),
        array('sync_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة المزامنة'),
        array('record_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة السجل'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'timesheet_approvals' => array(
        array('batch_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف الدفعة'),
        array('approval_day', 'DATE NULL DEFAULT NULL', 'يوم الاعتماد'),
        array('batch_scope', 'VARCHAR(60) NULL DEFAULT NULL', 'نطاق الدفعة'),
        array('records_count', 'DECIMAL(18,2) NULL DEFAULT NULL', 'عدد السجلات'),
        array('records_over_capacity', 'DECIMAL(18,2) NULL DEFAULT NULL', 'سجلات بتجاوز طاقة'),
        array('records_missing_reason', 'VARCHAR(500) NULL DEFAULT NULL', 'سجلات ناقصة السبب'),
        array('approval_stage', 'VARCHAR(60) NULL DEFAULT NULL', 'مرحلة الاعتماد'),
        array('site_approver', 'VARCHAR(190) NULL DEFAULT NULL', 'معتمد الموقع'),
        array('parties_approver', 'VARCHAR(190) NULL DEFAULT NULL', 'معتمد الأطراف'),
        array('contracts_approver', 'VARCHAR(190) NULL DEFAULT NULL', 'معتمد العقود'),
        array('match_result', 'VARCHAR(60) NULL DEFAULT NULL', 'نتيجة المطابقة'),
        array('excluded_records', 'VARCHAR(190) NULL DEFAULT NULL', 'سجلات مستثناة'),
        array('exception_reason', 'VARCHAR(500) NULL DEFAULT NULL', 'سبب الاستثناء'),
        array('batch_decision', 'VARCHAR(60) NULL DEFAULT NULL', 'قرار الدفعة'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'transfer_permits' => array(
        array('permit_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف التصريح'),
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('permit_scope', 'VARCHAR(60) NULL DEFAULT NULL', 'نطاق التصريح'),
        array('permit_attachment', 'VARCHAR(500) NULL DEFAULT NULL', 'مرفق التصريح'),
        array('permit_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة التصريح'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'transfer_requests' => array(
        array('requesting_party', 'VARCHAR(190) NULL DEFAULT NULL', 'الجهة الطالبة'),
        array('resource_move_order_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع أمر نقل الموارد'),
        array('cargo_type', 'VARCHAR(60) NULL DEFAULT NULL', 'نوع الحمولة'),
        array('equipment_or_item_code', 'VARCHAR(80) NULL DEFAULT NULL', 'كود المعدة/الصنف'),
        array('weight_or_dimensions', 'VARCHAR(190) NULL DEFAULT NULL', 'الوزن/الأبعاد'),
        array('from_location', 'VARCHAR(190) NULL DEFAULT NULL', 'من موقع'),
        array('to_location', 'VARCHAR(190) NULL DEFAULT NULL', 'إلى موقع'),
        array('loading_notes', 'VARCHAR(500) NULL DEFAULT NULL', 'ملاحظات التحميل'),
        array('request_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الطلب'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'tre_pay_batches' => array(
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('request_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الطلب'),
        array('approval_completeness_check', 'VARCHAR(60) NULL DEFAULT NULL', 'فحص اكتمال الاعتماد'),
        array('beneficiary', 'VARCHAR(190) NULL DEFAULT NULL', 'المستفيد'),
        array('value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'القيمة'),
        array('disbursing_vessel', 'VARCHAR(190) NULL DEFAULT NULL', 'الوعاء الصارف'),
        array('vessel_balance_check', 'VARCHAR(60) NULL DEFAULT NULL', 'فحص رصيد الوعاء'),
        array('first_location', 'VARCHAR(190) NULL DEFAULT NULL', 'الموقع الأول'),
        array('second_location', 'VARCHAR(190) NULL DEFAULT NULL', 'الموقع الثاني'),
        array('delegation_validity_check', 'VARCHAR(60) NULL DEFAULT NULL', 'فحص سريان التفويض'),
        array('bank_execution_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع التنفيذ البنكي'),
        array('execution_date', 'DATE NULL DEFAULT NULL', 'تاريخ التنفيذ'),
        array('receivables_effect', 'VARCHAR(190) NULL DEFAULT NULL', 'انعكاس الذمم'),
        array('order_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الأمر'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('approval_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاعتماد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'trp_closure' => array(
        array('closing_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف الإقفال'),
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('receipt_minutes_check', 'VARCHAR(60) NULL DEFAULT NULL', 'فحص محضر الاستلام'),
        array('closing_note', 'VARCHAR(500) NULL DEFAULT NULL', 'ملاحظة الإقفال'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('approval_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاعتماد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'trp_damage_claim' => array(
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('likely_cause_party', 'VARCHAR(190) NULL DEFAULT NULL', 'المتسبب المرجح'),
        array('estimated_claim_value', 'DECIMAL(18,2) NULL DEFAULT NULL', 'قيمة المطالبة المقدرة'),
        array('evidence_documents', 'VARCHAR(500) NULL DEFAULT NULL', 'مستندات الإثبات'),
        array('settlement_decision', 'VARCHAR(60) NULL DEFAULT NULL', 'قرار التسوية'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('approval_date', 'DATE NULL DEFAULT NULL', 'تاريخ الاعتماد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'trp_origin_handover' => array(
        array('item_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف البند'),
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('executor', 'VARCHAR(190) NULL DEFAULT NULL', 'المنفذ'),
        array('pre_transfer_photos', 'VARCHAR(500) NULL DEFAULT NULL', 'صور حالة ما قبل النقل'),
        array('route_risk_assessment', 'VARCHAR(190) NULL DEFAULT NULL', 'تقييم مخاطر المسار'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'trp_trip_leg' => array(
        array('stage_uid', 'VARCHAR(80) NULL DEFAULT NULL', 'معرف المرحلة'),
        array('order_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الأمر'),
        array('stage_sequence', 'DECIMAL(18,2) NULL DEFAULT NULL', 'تسلسل المرحلة'),
        array('assigned_carrier', 'VARCHAR(190) NULL DEFAULT NULL', 'الناقلة المكلفة'),
        array('driver', 'VARCHAR(190) NULL DEFAULT NULL', 'السائق'),
        array('estimated_distance', 'DECIMAL(18,2) NULL DEFAULT NULL', 'المسافة المقدرة'),
        array('stage_handover_to_next', 'VARCHAR(190) NULL DEFAULT NULL', 'تسليم المرحلة للتالية'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('created_date', 'DATE NULL DEFAULT NULL', 'تاريخ الإنشاء'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
    'worker_leave_absence' => array(
        array('employee_no', 'VARCHAR(80) NULL DEFAULT NULL', 'رقم الموظف'),
        array('supporting_attachment', 'VARCHAR(500) NULL DEFAULT NULL', 'مرفق مساند'),
        array('rotation_cycle_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع دورة التناوب'),
        array('request_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة الطلب'),
        array('creator_name', 'VARCHAR(190) NULL DEFAULT NULL', 'المنشئ'),
        array('reviewer', 'VARCHAR(190) NULL DEFAULT NULL', 'المراجع'),
        array('approver', 'VARCHAR(190) NULL DEFAULT NULL', 'المعتمد'),
        array('data_state', 'VARCHAR(60) NULL DEFAULT NULL', 'حالة البيانات'),
        array('source_ref', 'VARCHAR(80) NULL DEFAULT NULL', 'مرجع المصدر'),
    ),
);

$made = 0; $skip = 0; $fail = 0;
foreach ($SPEC as $tbl => $cols) {
    $have = ems_sm_cols($conn, $tbl);
    if (!$have) { echo "  \u{26D4} \u{62C}\u{62F}\u{648}\u{644} \u{63A}\u{627}\u{626}\u{628}: {$tbl}\n"; $fail += count($cols); continue; }
    $parts = array();
    foreach ($cols as $c) {
        if (isset($have[strtolower($c[0])])) { $skip++; continue; }
        $parts[] = "ADD COLUMN `" . $c[0] . "` " . $c[1]
                 . " COMMENT '" . $conn->real_escape_string($c[2]) . "'";
    }
    if (!$parts) { continue; }
    $sql = "ALTER TABLE `{$tbl}` " . implode(', ', $parts);
    if ($conn->query($sql)) {
        $made += count($parts);
        printf("  \u{2714} %-26s +%d\n", $tbl, count($parts));
    } else {
        $fail += count($parts);
        printf("  \u{26D4} %-26s %s\n", $tbl, $conn->error);
    }
}
printf("\n\u{623}\u{639}\u{645}\u{62F}\u{629}: \u{623}\u{646}\u{634}\u{626}\u{62A} %d \u{00B7} \u{642}\u{627}\u{626}\u{645}\u{629} %d \u{00B7} \u{641}\u{627}\u{634}\u{644}\u{629} %d\n", $made, $skip, $fail);
if ($fail > 0) { exit("\n\u{26D4} \u{633}\u{642}\u{637} \u{639}\u{645}\u{648}\u{62F} \u{2014} \u{644}\u{627} \u{64A}\u{064F}\u{639}\u{62A}\u{645}\u{62F}.\n"); }

require_once __DIR__ . '/_ledger.php';
ems_migration_recorded(__FILE__, $conn, (int) round((microtime(true) - $t0) * 1000));
echo "\u{2714} \u{62A}\u{645}\u{651} \u{2014} \u{62D}\u{642}\u{644}\u{064F} \u{627}\u{644}\u{648}\u{631}\u{642}\u{629} \u{635}\u{627}\u{631} \u{639}\u{645}\u{648}\u{62F}\u{064B}\u{627} \u{641}\u{064A} \u{62C}\u{62F}\u{648}\u{644} \u{634}\u{627}\u{634}\u{62A}\u{647}.\n";
