<?php
/**
 * 2028_02_16_dep02_suppliers_guide_columns_down.php — العكسُ المسوّى (GOV_EXEC §5)
 * @migration-objects: reverse tables for DEP-02
 * مولَّدةٌ من `tools/gov_exec_dept_build.php --emit` على مواصفةِ الإدارة —
 * وأسماءُ الأعمدةِ تعليقُها اسمُ الحقلِ في ورقةِ الدليلِ حرفًا.
 */
if (php_sapi_name() !== 'cli') { exit("CLI فقط\n"); }
error_reporting(E_ALL & ~E_DEPRECATED);
mb_internal_encoding('UTF-8');
$ROOT = dirname(dirname(__DIR__));
require_once $ROOT . '/includes/env.php';
require_once __DIR__ . '/_ledger.php';
$host = ems_env('DB_HOST'); $port = 3306;
if (strpos($host, ':') !== false) { list($host, $port) = explode(':', $host); $port = (int) $port; }
mysqli_report(MYSQLI_REPORT_OFF);
$u = ems_env('DB_MIGRATOR_USER') ?: ems_env('DB_USER');
$p = ems_env('DB_MIGRATOR_USER') ? ems_env('DB_MIGRATOR_PASS') : ems_env('DB_PASS');
$conn = new mysqli($host, $u, $p, ems_env('DB_NAME'), $port);
if ($conn->connect_errno) { exit("تعذّر الاتصال: {$conn->connect_error}\n"); }
$conn->set_charset('utf8mb4');
$t0 = microtime(true);

$SQL = array(
    <<<'SQL'
ALTER TABLE `sup_doc_guarantee`
    DROP COLUMN `doc_code`,
    DROP COLUMN `doc_scope`,
    DROP COLUMN `doc_state`,
    DROP COLUMN `record_basis`,
    DROP COLUMN `data_state`,
    ADD COLUMN `c7` varchar(60) NOT NULL DEFAULT '\'\'' COMMENT 'الحالة'
SQL,
    <<<'SQL'
ALTER TABLE `sup_allocation_payment_closure`
    DROP COLUMN `alloc_code`,
    DROP COLUMN `currency_ref`,
    DROP COLUMN `allocated_amount`,
    DROP COLUMN `allocation_rule`,
    DROP COLUMN `data_state`,
    DROP COLUMN `net_month_exceeded_flag`,
    ADD COLUMN `c5` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'العملة'
SQL,
    <<<'SQL'
ALTER TABLE `sup_closure`
    DROP COLUMN `slot_close_code`,
    DROP COLUMN `slot_code`,
    DROP COLUMN `business_model`,
    DROP COLUMN `line_type`,
    DROP COLUMN `uom`,
    DROP COLUMN `period_kind`,
    DROP COLUMN `period_start`,
    DROP COLUMN `period_end`,
    DROP COLUMN `period_end_month_tag`,
    DROP COLUMN `period_months`,
    DROP COLUMN `contracted_monthly_base`,
    DROP COLUMN `contracted_for_period`,
    DROP COLUMN `approved_executed`,
    DROP COLUMN `gap_or_surplus`,
    DROP COLUMN `achievement_pct`,
    DROP COLUMN `months_with_performance`,
    DROP COLUMN `last_unit_activity`,
    DROP COLUMN `supplier_unit_price`,
    DROP COLUMN `currency_ref`,
    DROP COLUMN `estimated_period_value`,
    DROP COLUMN `unit_state`,
    DROP COLUMN `closure_state`,
    DROP COLUMN `monthly_close_ref`,
    DROP COLUMN `reviewer`,
    DROP COLUMN `approved_by`,
    DROP COLUMN `approved_at`,
    DROP COLUMN `record_basis`,
    DROP COLUMN `derivation_rule`,
    DROP COLUMN `data_state`,
    ADD COLUMN `c6` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'نموذج العمل',
    ADD COLUMN `c8` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'وحدة القياس',
    ADD COLUMN `c10` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'بداية الفترة',
    ADD COLUMN `c11` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'نهاية الفترة',
    ADD COLUMN `c13` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'أشهر الفترة ◄',
    ADD COLUMN `month_14` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الأساس الشهري المتعاقد ◄',
    ADD COLUMN `c15` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المتعاقد عليه للفترة ◄',
    ADD COLUMN `c20` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'آخر نشاط بالوحدة التعاقدية ◄',
    ADD COLUMN `c22` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'العملة',
    ADD COLUMN `c23` decimal(18,2) NULL DEFAULT 'NULL' COMMENT 'قيمة الفترة التقديرية ◄',
    ADD COLUMN `c24` varchar(60) NOT NULL DEFAULT '\'\'' COMMENT 'حالة الوحدة التعاقدية (م10)'
SQL,
    <<<'SQL'
ALTER TABLE `sup_onbehalf_advance_deduction`
    DROP COLUMN `onbehalf_code`,
    DROP COLUMN `unit_or_equipment_code`,
    DROP COLUMN `onbehalf_kind`,
    DROP COLUMN `operator_code`,
    DROP COLUMN `description`,
    DROP COLUMN `currency_ref`,
    DROP COLUMN `recoverable`,
    DROP COLUMN `doc_evidence`,
    DROP COLUMN `disburse_approver`,
    DROP COLUMN `chain_state`,
    DROP COLUMN `offset_settlement_ref`,
    DROP COLUMN `recovered_amount`,
    DROP COLUMN `remaining_amount`,
    DROP COLUMN `source_text`,
    DROP COLUMN `source_row_ref`,
    DROP COLUMN `data_state`,
    ADD COLUMN `code_8` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'كود المشغل E###',
    ADD COLUMN `c9` text NULL DEFAULT 'NULL' COMMENT 'الوصف',
    ADD COLUMN `c11` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'العملة',
    ADD COLUMN `c15` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'قابل للاسترداد؟',
    ADD COLUMN `amount_20` decimal(18,2) NULL DEFAULT 'NULL' COMMENT 'المبلغ المسترد ◄',
    ADD COLUMN `c21` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المتبقي ◄'
SQL,
    <<<'SQL'
ALTER TABLE `sup_replacement_reserve`
    DROP COLUMN `event_code`,
    DROP COLUMN `obligation_cycle_key`,
    DROP COLUMN `slot_code`,
    DROP COLUMN `membership_test`,
    DROP COLUMN `business_model`,
    DROP COLUMN `event_date`,
    DROP COLUMN `event_name`,
    DROP COLUMN `unit_type`,
    DROP COLUMN `equipment_code`,
    DROP COLUMN `counterparty`,
    DROP COLUMN `from_reserve`,
    DROP COLUMN `value_before`,
    DROP COLUMN `value_after`,
    ADD COLUMN `c4` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'اختبار الانتماء ◄',
    ADD COLUMN `c5` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'نموذج العمل',
    ADD COLUMN `c8` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الحدث',
    ADD COLUMN `c13` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الطرف المقابل',
    ADD COLUMN `c14` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'من الاحتياطي؟',
    ADD COLUMN `c15` decimal(18,2) NULL DEFAULT 'NULL' COMMENT 'القيمة قبل',
    ADD COLUMN `c16` decimal(18,2) NULL DEFAULT 'NULL' COMMENT 'القيمة بعد'
SQL,
    <<<'SQL'
ALTER TABLE `sup_allocation_unit_equipment`
    DROP COLUMN `assign_code`,
    DROP COLUMN `slot_code`,
    DROP COLUMN `equipment_code`,
    DROP COLUMN `line_type`,
    DROP COLUMN `plate_as_written`,
    DROP COLUMN `plate_prefix`,
    DROP COLUMN `plate_number`,
    DROP COLUMN `unit_type`,
    DROP COLUMN `obligation_cycle_key`,
    DROP COLUMN `client_no`,
    DROP COLUMN `client_name`,
    DROP COLUMN `business_model`,
    DROP COLUMN `machine_no_client_contract`,
    DROP COLUMN `machine_no_supplier_contract`,
    DROP COLUMN `from_date`,
    DROP COLUMN `to_date`,
    DROP COLUMN `assign_kind`,
    DROP COLUMN `unit_role`,
    DROP COLUMN `change_reason`,
    DROP COLUMN `readiness_event_ref`,
    DROP COLUMN `active_months`,
    DROP COLUMN `work_days`,
    DROP COLUMN `executed_in_quota_unit`,
    DROP COLUMN `supplier_total_hours`,
    DROP COLUMN `agreed_monthly_hours`,
    DROP COLUMN `mine_site`,
    DROP COLUMN `continuity`,
    DROP COLUMN `operating_status`,
    DROP COLUMN `supplier_due_ref`,
    DROP COLUMN `supplier_contract_as_source`,
    DROP COLUMN `machine_assign_count`,
    DROP COLUMN `assign_state`,
    ADD COLUMN `c8` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'رمز اللوحة ◄',
    ADD COLUMN `no_9` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'رقم اللوحة (رقمي) ◄',
    ADD COLUMN `no_12` int(11) NULL DEFAULT 'NULL' COMMENT 'رقم العميل',
    ADD COLUMN `c14` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'نموذج العمل',
    ADD COLUMN `c17` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'من',
    ADD COLUMN `c18` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'إلى',
    ADD COLUMN `type_19` varchar(60) NOT NULL DEFAULT '\'\'' COMMENT 'نوع الإسناد',
    ADD COLUMN `c21` text NULL DEFAULT 'NULL' COMMENT 'سبب التغيير',
    ADD COLUMN `c23` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'أشهر النشاط ◄',
    ADD COLUMN `c24` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'أيام العمل ◄',
    ADD COLUMN `c25` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المنفذ بوحدة الحصة ◄',
    ADD COLUMN `c27` int(11) NULL DEFAULT 'NULL' COMMENT 'ساعات الاتفاق الشهرية',
    ADD COLUMN `c29` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الاستمرارية',
    ADD COLUMN `c30` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الوضع التشغيلي',
    ADD COLUMN `c34` varchar(60) NOT NULL DEFAULT '\'\'' COMMENT 'حالة الإسناد'
SQL,
    <<<'SQL'
ALTER TABLE `sup_handover_slot`
    DROP COLUMN `occupancy_code`,
    DROP COLUMN `unit_code_ref`,
    DROP COLUMN `obligation_cycle_key`,
    DROP COLUMN `line_type_ref`,
    DROP COLUMN `supplier_name_ref`,
    DROP COLUMN `occupancy_kind`,
    DROP COLUMN `from_date`,
    DROP COLUMN `to_date`,
    DROP COLUMN `occupancy_months`,
    DROP COLUMN `period_target`,
    DROP COLUMN `period_executed`,
    DROP COLUMN `period_achievement`,
    DROP COLUMN `handing_supplier`,
    DROP COLUMN `receiving_supplier`,
    DROP COLUMN `documented_vacancy`,
    DROP COLUMN `vacancy_reason`,
    DROP COLUMN `rotation_contribution_pct`,
    DROP COLUMN `decision_ref`,
    DROP COLUMN `occupancy_state`,
    ADD COLUMN `date_9` date NULL DEFAULT 'NULL' COMMENT 'إلى تاريخ',
    ADD COLUMN `c10` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'أشهر الإشغال ◄',
    ADD COLUMN `c12` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المنفذ في الفترة ◄',
    ADD COLUMN `supplier_15` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المورد المتسلم ◄',
    ADD COLUMN `c16` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'شغور موثق؟ ▼',
    ADD COLUMN `c17` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'مبرر الشغور',
    ADD COLUMN `c18` decimal(9,4) NULL DEFAULT 'NULL' COMMENT 'نسبة المساهمة عند اجتماع متناوبين ◄',
    ADD COLUMN `c20` varchar(60) NOT NULL DEFAULT '\'\'' COMMENT 'حالة الإشغال ▼'
SQL,
    <<<'SQL'
ALTER TABLE `sup_quota_supplier_unit`
    DROP COLUMN `dist_row_code`,
    DROP COLUMN `obligation_cycle_key`,
    DROP COLUMN `supplier_no_ref`,
    DROP COLUMN `supplier_name_ref`,
    DROP COLUMN `line_type_ref`,
    DROP COLUMN `monthly_unit_base`,
    DROP COLUMN `avg_monthly_executed`,
    DROP COLUMN `equivalent_units`,
    DROP COLUMN `granted_units`,
    DROP COLUMN `largest_remainder_gap`,
    DROP COLUMN `excess_machines`,
    DROP COLUMN `supplier_class`,
    DROP COLUMN `shared_slot_member`,
    DROP COLUMN `shared_contribution_pct`,
    DROP COLUMN `contractual_machines`,
    DROP COLUMN `actual_machines`,
    DROP COLUMN `contractual_vs_actual_gap`,
    DROP COLUMN `valid_from`,
    DROP COLUMN `dist_decision_ref`,
    DROP COLUMN `dist_state`,
    ADD COLUMN `c2` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'التسلسل الزمني للوحدة التعاقدية ◄',
    ADD COLUMN `c4` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'نموذج العمل',
    ADD COLUMN `c12` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'وحدة القياس',
    ADD COLUMN `c14` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'التصنيف (استمرارية)',
    ADD COLUMN `c19` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'أشهر منقضية ◄',
    ADD COLUMN `month_21` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'وحدات-شهر ◄',
    ADD COLUMN `c25` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الأساسية المتاحة ◄',
    ADD COLUMN `c26` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الاحتياطية ◄',
    ADD COLUMN `c27` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'فجوة الأساسية ◄',
    ADD COLUMN `c28` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'أساسية نشطة (حي) ◄',
    ADD COLUMN `equipment_30` decimal(9,4) NULL DEFAULT 'NULL' COMMENT 'نسبة تغطية المعدات ◄',
    ADD COLUMN `c32` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المنفذ ◄',
    ADD COLUMN `c34` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'سريان الحصة من',
    ADD COLUMN `c35` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'إلى',
    ADD COLUMN `supplier_36` decimal(18,2) NULL DEFAULT 'NULL' COMMENT 'سعر وحدة المورد (م08) ◄',
    ADD COLUMN `c37` decimal(18,2) NULL DEFAULT 'NULL' COMMENT 'سعر بيع الوحدة (قراءة) ◄',
    ADD COLUMN `c38` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'هامش الوحدة ◄',
    ADD COLUMN `c39` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'علم هامش سالب ◄',
    ADD COLUMN `c40` varchar(60) NOT NULL DEFAULT '\'\'' COMMENT 'حالة الوحدة التعاقدية',
    ADD COLUMN `c47` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'عملة البيع (قراءة) ◄',
    ADD COLUMN `c48` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'ملاءمة عملة الهامش ◄',
    ADD COLUMN `c49` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'علم حصة جارية بلا نشاط ◄',
    ADD COLUMN `c50` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'آخر نشاط بالوحدة التعاقدية ◄'
SQL,
    <<<'SQL'
ALTER TABLE `sup_responsibility`
    DROP COLUMN `matrix_code`,
    DROP COLUMN `business_model`,
    DROP COLUMN `doc_adaptation`,
    DROP COLUMN `evidence_level`,
    DROP COLUMN `fuel`,
    DROP COLUMN `oils`,
    DROP COLUMN `maintenance`,
    DROP COLUMN `spare_parts`,
    DROP COLUMN `operator`,
    DROP COLUMN `housing_food`,
    DROP COLUMN `mobilization`,
    DROP COLUMN `demobilization`,
    DROP COLUMN `damage`,
    DROP COLUMN `waiting`,
    DROP COLUMN `stoppage`,
    DROP COLUMN `breakdown`,
    DROP COLUMN `insurance`,
    DROP COLUMN `violations`,
    DROP COLUMN `decided_items_count`,
    DROP COLUMN `fill_state`,
    DROP COLUMN `filled_by`,
    DROP COLUMN `fill_date`,
    DROP COLUMN `data_state`,
    ADD COLUMN `c4` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'نموذج العمل',
    ADD COLUMN `c5` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'تكييف الوثيقة',
    ADD COLUMN `c7` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الوقود ▼',
    ADD COLUMN `c8` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الزيوت ▼',
    ADD COLUMN `c9` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الصيانة ▼',
    ADD COLUMN `c10` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'قطع الغيار ▼',
    ADD COLUMN `c11` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المشغل (السائق) ▼',
    ADD COLUMN `c12` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'السكن والإعاشة ▼',
    ADD COLUMN `migration_14` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'ترحيل العودة ▼',
    ADD COLUMN `c15` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الضرر ▼',
    ADD COLUMN `c16` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'الانتظار ▼',
    ADD COLUMN `c17` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'التوقف ▼',
    ADD COLUMN `c18` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'العطل ▼',
    ADD COLUMN `c19` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'التأمين ▼',
    ADD COLUMN `c20` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المخالفات ▼',
    ADD COLUMN `c22` varchar(60) NOT NULL DEFAULT '\'\'' COMMENT 'حالة تعبئة المصفوفة ◄',
    ADD COLUMN `c24` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'المعبئ'
SQL,
    <<<'SQL'
ALTER TABLE `sup_offer_supplier_negotiation`
    DROP COLUMN `offer_code`,
    DROP COLUMN `business_model`,
    DROP COLUMN `offer_kind`,
    DROP COLUMN `version_no`,
    DROP COLUMN `base_version`,
    DROP COLUMN `changed_what`,
    DROP COLUMN `proposed_by`,
    DROP COLUMN `change_date`,
    DROP COLUMN `negotiation_state`,
    DROP COLUMN `offered_line_types`,
    DROP COLUMN `line_count`,
    DROP COLUMN `offered_monthly_quota`,
    DROP COLUMN `min_unit_price`,
    DROP COLUMN `max_unit_price`,
    DROP COLUMN `currency_ref`,
    DROP COLUMN `payment_terms`,
    DROP COLUMN `execution_site`,
    DROP COLUMN `offer_precedes`,
    DROP COLUMN `competing_offers`,
    DROP COLUMN `required_guarantees`,
    DROP COLUMN `record_basis`,
    DROP COLUMN `derivation_rule`,
    DROP COLUMN `confidence`,
    DROP COLUMN `needs_review`,
    DROP COLUMN `data_state`,
    DROP COLUMN `src_ref`,
    ADD COLUMN `c5` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'نموذج العمل',
    ADD COLUMN `c8` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'النسخة الأساس',
    ADD COLUMN `c9` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'ما الذي تغير عن سابقتها',
    ADD COLUMN `c10` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'من اقترح التغيير',
    ADD COLUMN `c15` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'إجمالي الحصة الشهرية المعروضة ◄',
    ADD COLUMN `c16` decimal(18,2) NULL DEFAULT 'NULL' COMMENT 'أدنى سعر وحدة ◄',
    ADD COLUMN `c17` decimal(18,2) NULL DEFAULT 'NULL' COMMENT 'أعلى سعر وحدة ◄',
    ADD COLUMN `c18` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'العملة',
    ADD COLUMN `c19` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'شروط السداد المعروضة',
    ADD COLUMN `offer_22` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'العرض يسبق ◄',
    ADD COLUMN `offer_23` varchar(160) NOT NULL DEFAULT '\'\'' COMMENT 'عروض منافسة قورنت'
SQL,
);
$n = 0;
foreach ($SQL as $s) {
    if (!$conn->query($s)) {
        $msg = $conn->error;
        if (stripos($msg, "check that column") !== false || stripos($msg, "doesn't exist") !== false) { continue; }
        exit("⛔ {$msg}\n  في: " . substr($s, 0, 120) . "\n");
    }
    $n++;
}
echo "✔ {$n} جملةً نُفِّذت\n";
ems_migration_recorded(__FILE__, $conn, (int) round((microtime(true) - $t0) * 1000));
