<?php
/**
 * 2028_04_04_govui_dep11_fields.php — DEP-11 · أعمدةُ حقولٍ لا نظيرَ لها في المخزن
 * @migration-objects: columns for DEP-11
 * مولَّدةٌ من `tools/govui_field_close.php` على مواصفةِ الإدارة —
 * واسمُ العمودِ تعليقُه اسمُ الحقلِ في ورقةِ الدليل.
 */
if (php_sapi_name() !== 'cli') { exit("CLI فقط\n"); }
error_reporting(E_ALL & ~E_DEPRECATED & ~E_WARNING & ~E_NOTICE);
mb_internal_encoding('UTF-8');
$ROOT = dirname(dirname(__DIR__));
require_once $ROOT . '/includes/env.php';
require_once __DIR__ . '/_ledger.php';
$host = ems_env('DB_HOST'); $port = 3306;
if (strpos($host, ':') !== false) { list($host, $port) = explode(':', $host); $port = (int) $port; }
mysqli_report(MYSQLI_REPORT_OFF);
$u = ems_env('DB_MIGRATOR_USER') ?: ems_env('DB_USER');
$p = ems_env('DB_MIGRATOR_USER') ? ems_env('DB_MIGRATOR_PASS') : ems_env('DB_PASS');
$conn = new mysqli($host, $u, $p, ems_env('DB_NAME'), $port);
if ($conn->connect_errno) { exit("connect fail\n"); }
$conn->set_charset('utf8mb4');
$t0 = microtime(true);

$sql = 'CREATE TABLE IF NOT EXISTS `ops_timesheet` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g1` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السجل\',`g2` VARCHAR(190) NULL DEFAULT NULL COMMENT \'يوم التشغيل\',`g3` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود المعدة\',`g4` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع المعدة\',`g5` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المورد المقدم\',`g6` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم المشروع\',`g7` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وحدة عقد المشروع\',`g8` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مفتاح الحاوية السنوية\',`g9` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الحاوية الشهرية\',`g10` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود الخانة ونوع الإشغال\',`g11` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وسم خارج النافذة التعاقدية\',`g12` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الموقع الحالي\',`g13` VARCHAR(190) NULL DEFAULT NULL COMMENT \'منطقة العمل\',`g14` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود المشغل\',`g15` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الوردية\',`g16` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نموذج العمل\',`g17` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سبب تعديل الافتراضي\',`g18` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الساعات المتاحة\',`g19` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الكمية المنفذة\',`g20` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وحدة القياس\',`g21` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قراءة العداد أول الوردية\',`g22` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قراءة العداد آخر الوردية\',`g23` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ساعات العداد\',`g24` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي الفعلي\',`g25` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي الاستعداد\',`g26` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي التوقف\',`g27` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تجاوز الطاقة؟\',`g28` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سبب التجاوز\',`g29` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرجع الميداني\',`g30` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة المزامنة\',`g31` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السجل\',`g32` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g33` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g34` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g35` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g36` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g37` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g38` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_34f1302c_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'OPS-06 - سجل ساعات التشغيل اليومي\'';
if ($conn->query($sql)) { echo '+ جدول ops_timesheet
'; }
else { echo 'x ops_timesheet: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `ops_monthly_plan` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g39` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف سطر الخطة\',`g40` VARCHAR(190) NULL DEFAULT NULL COMMENT \'شهر الخطة\',`g41` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم المشروع\',`g42` VARCHAR(190) NULL DEFAULT NULL COMMENT \'اسم المشروع\',`g43` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود عقد العميل\',`g44` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود المعدة\',`g45` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع المعدة\',`g46` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نموذج العمل\',`g47` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المستهدف التعاقدي\',`g48` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مستهدف الخطة\',`g49` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وحدة القياس\',`g50` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أيام العمل المخططة\',`g51` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ورديات اليوم\',`g52` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الساعات المتاحة/وردية\',`g53` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معامل الموسم\',`g54` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المستهدف المعاير بالموسم\',`g55` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مبرر الفارق عن التعاقدي\',`g56` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السطر\',`g57` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g58` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g59` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g60` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g61` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g62` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g63` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_0413f280_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'OPS-03 - الخطة الشهرية للتشغيل\'';
if ($conn->query($sql)) { echo '+ جدول ops_monthly_plan
'; }
else { echo 'x ops_monthly_plan: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `ops_hours_approval` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g64` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الدفعة\',`g65` VARCHAR(190) NULL DEFAULT NULL COMMENT \'يوم الاعتماد\',`g66` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نطاق الدفعة\',`g67` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد السجلات\',`g68` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سجلات بتجاوز طاقة\',`g69` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سجلات ناقصة السبب\',`g70` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرحلة الاعتماد\',`g71` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معتمد الموقع\',`g72` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معتمد الأطراف\',`g73` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معتمد العقود\',`g74` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نتيجة المطابقة\',`g75` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سجلات مستثناة\',`g76` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سبب الاستثناء\',`g77` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قرار الدفعة\',`g78` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g79` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g80` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g81` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g82` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g83` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g84` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_5f43faab_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'OPS-08 - اعتماد الوحدات\'';
if ($conn->query($sql)) { echo '+ جدول ops_hours_approval
'; }
else { echo 'x ops_hours_approval: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `ops_monthly_close` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g85` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الإقفال\',`g86` VARCHAR(190) NULL DEFAULT NULL COMMENT \'شهر الإقفال\',`g87` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أيام الشهر\',`g88` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أيام معتمدة كاملا\',`g89` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أيام ناقصة\',`g90` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سجلات معلقة\',`g91` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قرارات توقف مفتوحة\',`g92` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي الوحدات المعتمدة\',`g93` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي ساعات الفعلي\',`g94` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي التوقف\',`g95` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نسبة تحقق الخطة\',`g96` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قائمة الاستثناءات المرحلة\',`g97` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الإقفال\',`g98` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g99` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g100` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g101` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g102` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g103` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g104` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_7adb719f_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'OPS-12 - الإقفال الشهري للتشغيل\'';
if ($conn->query($sql)) { echo '+ جدول ops_monthly_close
'; }
else { echo 'x ops_monthly_close: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `ops_worker_worklog` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g105` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الحدث\',`g106` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وقت الحدث\',`g107` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع الحدث\',`g108` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مصدره\',`g109` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المشروع\',`g110` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الموقع\',`g111` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعدة\',`g112` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ملخص الحدث\',`g113` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع السجل الأصلي\',`g114` VARCHAR(190) NULL DEFAULT NULL COMMENT \'درجة الأهمية\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_b71e0533_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'OPS-10 - سجل الأحداث التشغيلية\'';
if ($conn->query($sql)) { echo '+ جدول ops_worker_worklog
'; }
else { echo 'x ops_worker_worklog: ' . $conn->error . chr(10); }

ems_migration_recorded(__FILE__, $conn, (int) round((microtime(true) - $t0) * 1000));
