<?php
/**
 * 2028_02_16_dep02_suppliers_guide_columns.php — DEP-02 · إدارة الموردين — جداولُ مواضعِ الدليل (GOV_EXEC §5)
 * @migration-objects: tables for DEP-02
 * مولَّدةٌ من `tools/gov_exec_dept_build.php --emit` على مواصفةِ الإدارة —
 * وأسماءُ الأعمدةِ تعليقُها اسمُ الحقلِ في ورقةِ الدليلِ حرفًا.
 */
if (php_sapi_name() !== 'cli') { exit("CLI فقط\n"); }
error_reporting(E_ALL & ~E_DEPRECATED);
mb_internal_encoding('UTF-8');
$ROOT = dirname(dirname(__DIR__));
require_once $ROOT . '/includes/env.php';
require_once __DIR__ . '/_ledger.php';
$host = ems_env('DB_HOST'); $port = 3306;
if (strpos($host, ':') !== false) { list($host, $port) = explode(':', $host); $port = (int) $port; }
mysqli_report(MYSQLI_REPORT_OFF);
$u = ems_env('DB_MIGRATOR_USER') ?: ems_env('DB_USER');
$p = ems_env('DB_MIGRATOR_USER') ? ems_env('DB_MIGRATOR_PASS') : ems_env('DB_PASS');
$conn = new mysqli($host, $u, $p, ems_env('DB_NAME'), $port);
if ($conn->connect_errno) { exit("تعذّر الاتصال: {$conn->connect_error}\n"); }
$conn->set_charset('utf8mb4');
$t0 = microtime(true);

$SQL = array(
    <<<'SQL'
ALTER TABLE `sup_offer_supplier_negotiation`
    ADD COLUMN `offer_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود العرض · SupOffer_ID',
    ADD COLUMN `business_model` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نموذج العمل',
    ADD COLUMN `offer_kind` VARCHAR(255) NULL DEFAULT NULL COMMENT 'صفة العرض',
    ADD COLUMN `version_no` VARCHAR(40) NULL DEFAULT NULL COMMENT 'رقم النسخة',
    ADD COLUMN `base_version` VARCHAR(80) NULL DEFAULT NULL COMMENT 'النسخة الأساس',
    ADD COLUMN `changed_what` VARCHAR(255) NULL DEFAULT NULL COMMENT 'ما الذي تغيّر عن سابقتها',
    ADD COLUMN `proposed_by` INT NULL DEFAULT NULL COMMENT 'من اقترح التغيير',
    ADD COLUMN `change_date` DATE NULL DEFAULT NULL COMMENT 'تاريخ التغيير',
    ADD COLUMN `negotiation_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة التفاوض',
    ADD COLUMN `offered_line_types` VARCHAR(255) NULL DEFAULT NULL COMMENT 'أنواع البنود المعروضة ◄',
    ADD COLUMN `line_count` INT NULL DEFAULT NULL COMMENT 'عدد البنود ◄',
    ADD COLUMN `offered_monthly_quota` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'إجمالي الحصة الشهرية المعروضة ◄',
    ADD COLUMN `min_unit_price` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'أدنى سعر وحدة ◄',
    ADD COLUMN `max_unit_price` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'أعلى سعر وحدة ◄',
    ADD COLUMN `currency_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'العملة',
    ADD COLUMN `payment_terms` VARCHAR(255) NULL DEFAULT NULL COMMENT 'شروط السداد المعروضة',
    ADD COLUMN `execution_site` VARCHAR(255) NULL DEFAULT NULL COMMENT 'موقع التنفيذ',
    ADD COLUMN `offer_precedes` VARCHAR(255) NULL DEFAULT NULL COMMENT 'العرض يسبق ◄',
    ADD COLUMN `competing_offers` VARCHAR(255) NULL DEFAULT NULL COMMENT 'عروض منافسة قورنت',
    ADD COLUMN `required_guarantees` VARCHAR(255) NULL DEFAULT NULL COMMENT 'الضمانات المطلوبة',
    ADD COLUMN `record_basis` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Record_Basis',
    ADD COLUMN `derivation_rule` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Derivation_Rule',
    ADD COLUMN `confidence` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Confidence',
    ADD COLUMN `needs_review` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Needs_Review',
    ADD COLUMN `data_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة البيانات',
    ADD COLUMN `src_ref` VARCHAR(255) NULL DEFAULT NULL COMMENT 'المصدر',
    DROP COLUMN `c5`,
    DROP COLUMN `c8`,
    DROP COLUMN `c9`,
    DROP COLUMN `c10`,
    DROP COLUMN `c15`,
    DROP COLUMN `c16`,
    DROP COLUMN `c17`,
    DROP COLUMN `c18`,
    DROP COLUMN `c19`,
    DROP COLUMN `offer_22`,
    DROP COLUMN `offer_23`
SQL,
    <<<'SQL'
ALTER TABLE `sup_responsibility`
    ADD COLUMN `matrix_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود عقد المورد · Sup_Contract_ID',
    ADD COLUMN `business_model` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نموذج العمل',
    ADD COLUMN `doc_adaptation` VARCHAR(255) NULL DEFAULT NULL COMMENT 'تكييف الوثيقة',
    ADD COLUMN `evidence_level` VARCHAR(255) NULL DEFAULT NULL COMMENT 'مستوى الحجية',
    ADD COLUMN `fuel` DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'الوقود ▼',
    ADD COLUMN `oils` VARCHAR(80) NULL DEFAULT NULL COMMENT 'الزيوت ▼',
    ADD COLUMN `maintenance` VARCHAR(80) NULL DEFAULT NULL COMMENT 'الصيانة ▼',
    ADD COLUMN `spare_parts` VARCHAR(80) NULL DEFAULT NULL COMMENT 'قطع الغيار ▼',
    ADD COLUMN `operator` VARCHAR(80) NULL DEFAULT NULL COMMENT 'المشغل (السائق) ▼',
    ADD COLUMN `housing_food` VARCHAR(80) NULL DEFAULT NULL COMMENT 'السكن والإعاشة ▼',
    ADD COLUMN `mobilization` VARCHAR(80) NULL DEFAULT NULL COMMENT 'ترحيل الذهاب (Mobilization) ▼',
    ADD COLUMN `demobilization` VARCHAR(80) NULL DEFAULT NULL COMMENT 'ترحيل العودة (Demobilization) ▼',
    ADD COLUMN `damage` VARCHAR(80) NULL DEFAULT NULL COMMENT 'الضرر ▼',
    ADD COLUMN `waiting` VARCHAR(80) NULL DEFAULT NULL COMMENT 'الانتظار ▼',
    ADD COLUMN `stoppage` DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'التوقف ▼',
    ADD COLUMN `breakdown` VARCHAR(80) NULL DEFAULT NULL COMMENT 'العطل ▼',
    ADD COLUMN `insurance` VARCHAR(80) NULL DEFAULT NULL COMMENT 'التأمين ▼',
    ADD COLUMN `violations` VARCHAR(80) NULL DEFAULT NULL COMMENT 'المخالفات ▼',
    ADD COLUMN `decided_items_count` INT NULL DEFAULT NULL COMMENT 'عدد البنود المحددة ◄',
    ADD COLUMN `fill_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة تعبئة المصفوفة ◄',
    ADD COLUMN `filled_by` INT NULL DEFAULT NULL COMMENT 'المُعبِّئ',
    ADD COLUMN `fill_date` DATE NULL DEFAULT NULL COMMENT 'تاريخ التعبئة',
    ADD COLUMN `data_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة البيانات',
    DROP COLUMN `c4`,
    DROP COLUMN `c5`,
    DROP COLUMN `c7`,
    DROP COLUMN `c8`,
    DROP COLUMN `c9`,
    DROP COLUMN `c10`,
    DROP COLUMN `c11`,
    DROP COLUMN `c12`,
    DROP COLUMN `migration_14`,
    DROP COLUMN `c15`,
    DROP COLUMN `c16`,
    DROP COLUMN `c17`,
    DROP COLUMN `c18`,
    DROP COLUMN `c19`,
    DROP COLUMN `c20`,
    DROP COLUMN `c22`,
    DROP COLUMN `c24`
SQL,
    <<<'SQL'
ALTER TABLE `sup_quota_supplier_unit`
    ADD COLUMN `dist_row_code` VARCHAR(255) NULL DEFAULT NULL COMMENT 'معرّف سطر التوزيع',
    ADD COLUMN `obligation_cycle_key` VARCHAR(80) NULL DEFAULT NULL COMMENT 'مفتاح دورة الالتزام السنوية ◄',
    ADD COLUMN `supplier_no_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم المورد ◄',
    ADD COLUMN `supplier_name_ref` VARCHAR(255) NULL DEFAULT NULL COMMENT 'اسم المورد ◄',
    ADD COLUMN `line_type_ref` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نوع الآلية/البند ◄',
    ADD COLUMN `monthly_unit_base` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'أساس الوحدة التعاقدية الشهري ◄',
    ADD COLUMN `avg_monthly_executed` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'متوسط المنفَّذ الشهري ◄',
    ADD COLUMN `equivalent_units` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'الوحدات التعاقدية المكافئة (الاستحقاق) ◄',
    ADD COLUMN `granted_units` INT NULL DEFAULT NULL COMMENT 'الوحدات التعاقدية الممنوحة (أعدادًا صحيحة)',
    ADD COLUMN `largest_remainder_gap` DECIMAL(18,4) NULL DEFAULT NULL COMMENT 'فارق أكبر البواقي ◄',
    ADD COLUMN `excess_machines` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'آليات زائدة عن الوحدات التعاقدية ◄',
    ADD COLUMN `supplier_class` VARCHAR(80) NULL DEFAULT NULL COMMENT 'تصنيف المورد ▼',
    ADD COLUMN `shared_slot_member` VARCHAR(80) NULL DEFAULT NULL COMMENT 'عضو خانة مشتركة؟ ▼',
    ADD COLUMN `shared_contribution_pct` VARCHAR(80) NULL DEFAULT NULL COMMENT 'نسبة المساهمة في الوحدة التعاقدية المشتركة',
    ADD COLUMN `contractual_machines` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'آلات تعاقدية = المستهدف ÷ أساس الوحدة التعاقدية ◄',
    ADD COLUMN `actual_machines` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'آلات واقعية = المستهدف ÷ إنتاجية آلة المورد ◄',
    ADD COLUMN `contractual_vs_actual_gap` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'الفرق بين التعاقدي والواقعي ◄',
    ADD COLUMN `valid_from` DATE NULL DEFAULT NULL COMMENT 'ساري من تاريخ',
    ADD COLUMN `dist_decision_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'مرجع قرار التوزيع',
    ADD COLUMN `dist_state` VARCHAR(80) NULL DEFAULT NULL COMMENT 'حالة التوزيع ▼',
    DROP COLUMN `c2`,
    DROP COLUMN `c4`,
    DROP COLUMN `c12`,
    DROP COLUMN `c14`,
    DROP COLUMN `c19`,
    DROP COLUMN `month_21`,
    DROP COLUMN `c25`,
    DROP COLUMN `c26`,
    DROP COLUMN `c27`,
    DROP COLUMN `c28`,
    DROP COLUMN `equipment_30`,
    DROP COLUMN `c32`,
    DROP COLUMN `c34`,
    DROP COLUMN `c35`,
    DROP COLUMN `supplier_36`,
    DROP COLUMN `c37`,
    DROP COLUMN `c38`,
    DROP COLUMN `c39`,
    DROP COLUMN `c40`,
    DROP COLUMN `c47`,
    DROP COLUMN `c48`,
    DROP COLUMN `c49`,
    DROP COLUMN `c50`
SQL,
    <<<'SQL'
ALTER TABLE `sup_handover_slot`
    ADD COLUMN `occupancy_code` VARCHAR(255) NULL DEFAULT NULL COMMENT 'معرّف الإشغال',
    ADD COLUMN `unit_code_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود الوحدة التعاقدية (بادئة النوع + تسلسل) ◄',
    ADD COLUMN `obligation_cycle_key` VARCHAR(80) NULL DEFAULT NULL COMMENT 'مفتاح دورة الالتزام السنوية ◄',
    ADD COLUMN `line_type_ref` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نوع الآلية/البند ◄',
    ADD COLUMN `supplier_name_ref` VARCHAR(255) NULL DEFAULT NULL COMMENT 'اسم المورد ◄',
    ADD COLUMN `occupancy_kind` VARCHAR(80) NULL DEFAULT NULL COMMENT 'نوع الإشغال ▼',
    ADD COLUMN `from_date` DATE NULL DEFAULT NULL COMMENT 'من تاريخ',
    ADD COLUMN `to_date` DATE NULL DEFAULT NULL COMMENT 'إلى تاريخ',
    ADD COLUMN `occupancy_months` DECIMAL(8,2) NULL DEFAULT NULL COMMENT 'أشهر الإشغال ◄',
    ADD COLUMN `period_target` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'مستهدف الفترة (أساس الوحدة التعاقدية × أشهر الإشغال) ◄',
    ADD COLUMN `period_executed` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'المنفَّذ في الفترة ◄',
    ADD COLUMN `period_achievement` DECIMAL(8,2) NULL DEFAULT NULL COMMENT 'تحقق الفترة ◄',
    ADD COLUMN `handing_supplier` VARCHAR(255) NULL DEFAULT NULL COMMENT 'المورد المسلِّم ◄',
    ADD COLUMN `receiving_supplier` VARCHAR(255) NULL DEFAULT NULL COMMENT 'المورد المتسلِّم ◄',
    ADD COLUMN `documented_vacancy` VARCHAR(80) NULL DEFAULT NULL COMMENT 'شغور موثَّق؟ ▼',
    ADD COLUMN `vacancy_reason` VARCHAR(500) NULL DEFAULT NULL COMMENT 'مبرر الشغور',
    ADD COLUMN `rotation_contribution_pct` DECIMAL(8,2) NULL DEFAULT NULL COMMENT 'نسبة المساهمة عند اجتماع متناوبين ◄',
    ADD COLUMN `decision_ref` VARCHAR(500) NULL DEFAULT NULL COMMENT 'مرجع القرار',
    ADD COLUMN `occupancy_state` VARCHAR(80) NULL DEFAULT NULL COMMENT 'حالة الإشغال ▼',
    DROP COLUMN `date_9`,
    DROP COLUMN `c10`,
    DROP COLUMN `c12`,
    DROP COLUMN `supplier_15`,
    DROP COLUMN `c16`,
    DROP COLUMN `c17`,
    DROP COLUMN `c18`,
    DROP COLUMN `c20`
SQL,
    <<<'SQL'
ALTER TABLE `sup_allocation_unit_equipment`
    ADD COLUMN `assign_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم الإسناد · Assign_ID',
    ADD COLUMN `slot_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود الوحدة التعاقدية · Slot_ID',
    ADD COLUMN `equipment_code` VARCHAR(60) NULL DEFAULT NULL COMMENT 'كود المعدة · Equipment_ID',
    ADD COLUMN `line_type` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نوع الآلية/البند',
    ADD COLUMN `plate_as_written` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم اللوحة (كما ورد)',
    ADD COLUMN `plate_prefix` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رمز اللوحة ◄',
    ADD COLUMN `plate_number` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم اللوحة (رقمي) ◄',
    ADD COLUMN `unit_type` VARCHAR(80) NULL DEFAULT NULL COMMENT 'نوع الوحدة التعاقدية',
    ADD COLUMN `obligation_cycle_key` VARCHAR(80) NULL DEFAULT NULL COMMENT 'مفتاح دورة الالتزام · Key',
    ADD COLUMN `client_no` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم العميل',
    ADD COLUMN `client_name` VARCHAR(255) NULL DEFAULT NULL COMMENT 'اسم العميل (بحث)',
    ADD COLUMN `business_model` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نموذج العمل',
    ADD COLUMN `machine_no_client_contract` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم الآلية في عقد العميل',
    ADD COLUMN `machine_no_supplier_contract` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم الآلية في عقد المورد',
    ADD COLUMN `from_date` DATE NULL DEFAULT NULL COMMENT 'من',
    ADD COLUMN `to_date` DATE NULL DEFAULT NULL COMMENT 'إلى',
    ADD COLUMN `assign_kind` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نوع الإسناد',
    ADD COLUMN `unit_role` VARCHAR(255) NULL DEFAULT NULL COMMENT 'الدور (أساسية/احتياطية)',
    ADD COLUMN `change_reason` VARCHAR(255) NULL DEFAULT NULL COMMENT 'سبب التغيير',
    ADD COLUMN `readiness_event_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'مرجع حدث الجاهزية (م12)',
    ADD COLUMN `active_months` DECIMAL(8,2) NULL DEFAULT NULL COMMENT 'أشهر النشاط ◄',
    ADD COLUMN `work_days` INT NULL DEFAULT NULL COMMENT 'أيام العمل ◄',
    ADD COLUMN `executed_in_quota_unit` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'المنفَّذ بوحدة الحصة ◄',
    ADD COLUMN `supplier_total_hours` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'ساعات المورد الكلية ◄',
    ADD COLUMN `agreed_monthly_hours` DECIMAL(14,2) NULL DEFAULT NULL COMMENT 'ساعات الاتفاق الشهرية',
    ADD COLUMN `mine_site` VARCHAR(255) NULL DEFAULT NULL COMMENT 'الموقع (المنجم)',
    ADD COLUMN `continuity` VARCHAR(255) NULL DEFAULT NULL COMMENT 'الاستمرارية',
    ADD COLUMN `operating_status` VARCHAR(255) NULL DEFAULT NULL COMMENT 'الوضع التشغيلي',
    ADD COLUMN `supplier_due_ref` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'مستحق المورد $ (مرجعي) ◄',
    ADD COLUMN `supplier_contract_as_source` VARCHAR(255) NULL DEFAULT NULL COMMENT 'عقد المورد (كما بالمصدر)',
    ADD COLUMN `machine_assign_count` INT NULL DEFAULT NULL COMMENT 'عدد إسنادات الآلية ◄',
    ADD COLUMN `assign_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة الإسناد',
    DROP COLUMN `c8`,
    DROP COLUMN `no_9`,
    DROP COLUMN `no_12`,
    DROP COLUMN `c14`,
    DROP COLUMN `c17`,
    DROP COLUMN `c18`,
    DROP COLUMN `type_19`,
    DROP COLUMN `c21`,
    DROP COLUMN `c23`,
    DROP COLUMN `c24`,
    DROP COLUMN `c25`,
    DROP COLUMN `c27`,
    DROP COLUMN `c29`,
    DROP COLUMN `c30`,
    DROP COLUMN `c34`
SQL,
    <<<'SQL'
ALTER TABLE `sup_replacement_reserve`
    ADD COLUMN `event_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم الحدث · Event_ID',
    ADD COLUMN `obligation_cycle_key` VARCHAR(80) NULL DEFAULT NULL COMMENT 'مفتاح دورة الالتزام · Key',
    ADD COLUMN `slot_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود الوحدة التعاقدية · Slot_ID',
    ADD COLUMN `membership_test` VARCHAR(255) NULL DEFAULT NULL COMMENT 'اختبار الانتماء ◄',
    ADD COLUMN `business_model` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نموذج العمل',
    ADD COLUMN `event_date` DATE NULL DEFAULT NULL COMMENT 'التاريخ',
    ADD COLUMN `event_name` VARCHAR(255) NULL DEFAULT NULL COMMENT 'الحدث',
    ADD COLUMN `unit_type` VARCHAR(80) NULL DEFAULT NULL COMMENT 'نوع الوحدة التعاقدية',
    ADD COLUMN `equipment_code` VARCHAR(60) NULL DEFAULT NULL COMMENT 'كود المعدة',
    ADD COLUMN `counterparty` VARCHAR(255) NULL DEFAULT NULL COMMENT 'الطرف المقابل',
    ADD COLUMN `from_reserve` VARCHAR(255) NULL DEFAULT NULL COMMENT 'من الاحتياطي؟',
    ADD COLUMN `value_before` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'القيمة قبل',
    ADD COLUMN `value_after` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'القيمة بعد',
    DROP COLUMN `c4`,
    DROP COLUMN `c5`,
    DROP COLUMN `c8`,
    DROP COLUMN `c13`,
    DROP COLUMN `c14`,
    DROP COLUMN `c15`,
    DROP COLUMN `c16`
SQL,
    <<<'SQL'
ALTER TABLE `sup_onbehalf_advance_deduction`
    ADD COLUMN `onbehalf_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم الواقعة · OnBehalf_ID',
    ADD COLUMN `unit_or_equipment_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود الوحدة التعاقدية/المعدة (إن وجد)',
    ADD COLUMN `onbehalf_kind` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نوع الواقعة النيابية',
    ADD COLUMN `operator_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود المشغل E###',
    ADD COLUMN `description` VARCHAR(500) NULL DEFAULT NULL COMMENT 'الوصف',
    ADD COLUMN `currency_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'العملة',
    ADD COLUMN `recoverable` VARCHAR(255) NULL DEFAULT NULL COMMENT 'قابل للاسترداد؟',
    ADD COLUMN `doc_evidence` VARCHAR(255) NULL DEFAULT NULL COMMENT 'المستند/الإثبات',
    ADD COLUMN `disburse_approver` VARCHAR(255) NULL DEFAULT NULL COMMENT 'معتمد الصرف',
    ADD COLUMN `chain_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة السلسلة النيابية',
    ADD COLUMN `offset_settlement_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'مرجع التسوية الخاصمة (م17)',
    ADD COLUMN `recovered_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'المبلغ المسترد ◄',
    ADD COLUMN `remaining_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'المتبقي ◄',
    ADD COLUMN `source_text` VARCHAR(500) NULL DEFAULT NULL COMMENT 'نص المصدر (بيان الأستاذ)',
    ADD COLUMN `source_row_ref` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Source_Row_Ref',
    ADD COLUMN `data_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة البيانات',
    DROP COLUMN `code_8`,
    DROP COLUMN `c9`,
    DROP COLUMN `c11`,
    DROP COLUMN `c15`,
    DROP COLUMN `amount_20`,
    DROP COLUMN `c21`
SQL,
    <<<'SQL'
ALTER TABLE `sup_closure`
    ADD COLUMN `slot_close_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود الإقفال التعاقدي · SlotClose_ID',
    ADD COLUMN `slot_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود الوحدة التعاقدية · Slot_ID',
    ADD COLUMN `business_model` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نموذج العمل',
    ADD COLUMN `line_type` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نوع الآلية/البند',
    ADD COLUMN `uom` VARCHAR(80) NULL DEFAULT NULL COMMENT 'وحدة القياس',
    ADD COLUMN `period_kind` VARCHAR(255) NULL DEFAULT NULL COMMENT 'نوع الفترة',
    ADD COLUMN `period_start` DATE NULL DEFAULT NULL COMMENT 'بداية الفترة',
    ADD COLUMN `period_end` DATE NULL DEFAULT NULL COMMENT 'نهاية الفترة',
    ADD COLUMN `period_end_month_tag` VARCHAR(255) NULL DEFAULT NULL COMMENT 'شهر نهاية الفترة (وسم) ◄',
    ADD COLUMN `period_months` DECIMAL(8,2) NULL DEFAULT NULL COMMENT 'أشهر الفترة ◄',
    ADD COLUMN `contracted_monthly_base` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'الأساس الشهري المتعاقد ◄',
    ADD COLUMN `contracted_for_period` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'المتعاقد عليه للفترة ◄',
    ADD COLUMN `approved_executed` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'المنفَّذ المعتمد بالفترة ◄',
    ADD COLUMN `gap_or_surplus` DECIMAL(18,3) NULL DEFAULT NULL COMMENT 'الفجوة/الفائض ◄',
    ADD COLUMN `achievement_pct` DECIMAL(8,2) NULL DEFAULT NULL COMMENT 'نسبة التحقق ◄',
    ADD COLUMN `months_with_performance` INT NULL DEFAULT NULL COMMENT 'أشهر بها أداء ◄',
    ADD COLUMN `last_unit_activity` VARCHAR(80) NULL DEFAULT NULL COMMENT 'آخر نشاط بالوحدة التعاقدية ◄',
    ADD COLUMN `supplier_unit_price` VARCHAR(80) NULL DEFAULT NULL COMMENT 'سعر وحدة المورد (م08) ◄',
    ADD COLUMN `currency_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'العملة',
    ADD COLUMN `estimated_period_value` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'قيمة الفترة التقديرية ◄',
    ADD COLUMN `unit_state` VARCHAR(80) NULL DEFAULT NULL COMMENT 'حالة الوحدة التعاقدية (م10)',
    ADD COLUMN `closure_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة الإقفال التعاقدي ◄',
    ADD COLUMN `monthly_close_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'مرجع الإقفال الشهري (م17)',
    ADD COLUMN `reviewer` VARCHAR(255) NULL DEFAULT NULL COMMENT 'المراجع',
    ADD COLUMN `approved_by` INT NULL DEFAULT NULL COMMENT 'المعتمِد',
    ADD COLUMN `approved_at` DATETIME NULL DEFAULT NULL COMMENT 'تاريخ الاعتماد',
    ADD COLUMN `record_basis` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Record_Basis',
    ADD COLUMN `derivation_rule` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Derivation_Rule',
    ADD COLUMN `data_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة البيانات',
    DROP COLUMN `c6`,
    DROP COLUMN `c8`,
    DROP COLUMN `c10`,
    DROP COLUMN `c11`,
    DROP COLUMN `c13`,
    DROP COLUMN `month_14`,
    DROP COLUMN `c15`,
    DROP COLUMN `c20`,
    DROP COLUMN `c22`,
    DROP COLUMN `c23`,
    DROP COLUMN `c24`
SQL,
    <<<'SQL'
ALTER TABLE `sup_allocation_payment_closure`
    ADD COLUMN `alloc_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'رقم التخصيص',
    ADD COLUMN `currency_ref` VARCHAR(80) NULL DEFAULT NULL COMMENT 'العملة',
    ADD COLUMN `allocated_amount` DECIMAL(18,2) NULL DEFAULT NULL COMMENT 'المبلغ المخصص',
    ADD COLUMN `allocation_rule` VARCHAR(255) NULL DEFAULT NULL COMMENT 'قاعدة التخصيص',
    ADD COLUMN `data_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة البيانات',
    ADD COLUMN `net_month_exceeded_flag` VARCHAR(255) NULL DEFAULT NULL COMMENT 'علم تجاوز صافي الشهر ◄',
    DROP COLUMN `c5`
SQL,
    <<<'SQL'
ALTER TABLE `sup_doc_guarantee`
    ADD COLUMN `doc_code` VARCHAR(80) NULL DEFAULT NULL COMMENT 'كود المستند · Doc_ID',
    ADD COLUMN `doc_scope` VARCHAR(255) NULL DEFAULT NULL COMMENT 'النطاق (عقد/مورد)',
    ADD COLUMN `doc_state` VARCHAR(80) NULL DEFAULT NULL COMMENT 'الحالة',
    ADD COLUMN `record_basis` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Record_Basis',
    ADD COLUMN `data_state` VARCHAR(255) NULL DEFAULT NULL COMMENT 'حالة البيانات',
    DROP COLUMN `c7`
SQL,
);
$n = 0;
foreach ($SQL as $s) {
    if (!$conn->query($s)) {
        $msg = $conn->error;
        if (stripos($msg, 'Duplicate column') !== false) { continue; }
        exit("⛔ {$msg}\n  في: " . substr($s, 0, 120) . "\n");
    }
    $n++;
}
echo "✔ {$n} جملةً نُفِّذت\n";
ems_migration_recorded(__FILE__, $conn, (int) round((microtime(true) - $t0) * 1000));
