<?php
/**
 * 2028_04_07_govui_dep_15_fields.php — DEP-15 · أعمدةُ حقولٍ لا نظيرَ لها في المخزن
 * @migration-objects: columns for DEP-15
 * مولَّدةٌ من `tools/govui_field_close.php` على مواصفةِ الإدارة —
 * واسمُ العمودِ تعليقُه اسمُ الحقلِ في ورقةِ الدليل.
 */
if (php_sapi_name() !== 'cli') { exit("CLI فقط\n"); }
error_reporting(E_ALL & ~E_DEPRECATED & ~E_WARNING & ~E_NOTICE);
mb_internal_encoding('UTF-8');
$ROOT = dirname(dirname(__DIR__));
require_once $ROOT . '/includes/env.php';
require_once __DIR__ . '/_ledger.php';
$host = ems_env('DB_HOST'); $port = 3306;
if (strpos($host, ':') !== false) { list($host, $port) = explode(':', $host); $port = (int) $port; }
mysqli_report(MYSQLI_REPORT_OFF);
$u = ems_env('DB_MIGRATOR_USER') ?: ems_env('DB_USER');
$p = ems_env('DB_MIGRATOR_USER') ? ems_env('DB_MIGRATOR_PASS') : ems_env('DB_PASS');
$conn = new mysqli($host, $u, $p, ems_env('DB_NAME'), $port);
if ($conn->connect_errno) { exit("connect fail\n"); }
$conn->set_charset('utf8mb4');
$t0 = microtime(true);

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_order_form` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g1` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الأمر\',`g2` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الأمر\',`g3` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الطلب\',`g4` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع الحمولة\',`g5` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود المعدة\',`g6` VARCHAR(190) NULL DEFAULT NULL COMMENT \'من موقع\',`g7` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلى موقع\',`g8` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المسافة التقديرية\',`g9` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وسيلة النقل\',`g10` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الناقل\',`g11` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عقد الناقل\',`g12` VARCHAR(190) NULL DEFAULT NULL COMMENT \'السائق\',`g13` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رخصة السائق سارية؟\',`g14` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المسار المقرر\',`g15` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ المغادرة المخطط\',`g16` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الوصول المخطط\',`g17` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التصاريح المطلوبة\',`g18` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الأمر\',`g19` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g20` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g21` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g22` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g23` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g24` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g25` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_ed56a49c_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-04 - أمر الترحيل\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_order_form
'; }
else { echo 'x trp_transfer_order_form: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_fleet` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g26` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود الناقلة\',`g27` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النوع\',`g28` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم اللوحة\',`g29` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المالك\',`g30` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المورد عند التأجير\',`g31` VARCHAR(190) NULL DEFAULT NULL COMMENT \'السعة الوزنية (طن)\',`g32` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الطول والعرض المسموحان\',`g33` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد المحاور\',`g34` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رخصة السير وانتهاؤها\',`g35` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تأمين البضاعة وانتهاؤه\',`g36` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تصاريح المسار السارية\',`g37` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فحص المطابقة مع الحمولة\',`g38` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الناقلة\',`g39` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g40` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g41` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g42` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_b836ea0e_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-03 - اللوابد والمركبات الناقلة\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_fleet
'; }
else { echo 'x trp_transfer_fleet: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_in_transit` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g43` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الحدث\',`g44` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الأمر\',`g45` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع الحدث\',`g46` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وقت الحدث\',`g47` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الموقع الجغرافي\',`g48` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قراءة عداد الناقل\',`g49` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ملاحظة الحدث\',`g50` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرفق/صورة\',`g51` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مسجل دون اتصال؟\',`g52` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السطر\',`g53` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g54` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g55` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g56` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_3d4b04df_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-08 - تتبع الرحلة وأحداثها\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_in_transit
'; }
else { echo 'x trp_transfer_in_transit: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_dashboard_kpi` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g57` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف المؤشر\',`g58` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المؤشر KPI Catalog\',`g59` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القيمة\',`g60` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الوحدة\',`g61` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الحالة\',`g62` VARCHAR(190) NULL DEFAULT NULL COMMENT \'آخر تحديث\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_e292c6a9_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-01 - لا سطر مسجل بعد في لوحة النقل والترحيل\'';
if ($conn->query($sql)) { echo '+ جدول trp_dashboard_kpi
'; }
else { echo 'x trp_dashboard_kpi: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_requests` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g63` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الطلب\',`g64` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الطلب\',`g65` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الجهة الطالبة\',`g66` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع أمر نقل الموارد\',`g67` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع الحمولة\',`g68` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود المعدة/الصنف\',`g69` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الوزن/الأبعاد\',`g70` VARCHAR(190) NULL DEFAULT NULL COMMENT \'من موقع\',`g71` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلى موقع\',`g72` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التاريخ المطلوب\',`g73` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الأولوية\',`g74` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ملاحظات التحميل\',`g75` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الطلب\',`g76` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g77` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g78` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g79` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_bedd1f0e_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-02 - طلب الترحيل\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_requests
'; }
else { echo 'x trp_transfer_requests: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_trip_legs` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g80` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف المرحلة\',`g81` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الأمر\',`g82` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تسلسل المرحلة\',`g83` VARCHAR(190) NULL DEFAULT NULL COMMENT \'من نقطة\',`g84` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلى نقطة\',`g85` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الناقلة المكلفة\',`g86` VARCHAR(190) NULL DEFAULT NULL COMMENT \'السائق\',`g87` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المسافة المقدرة\',`g88` VARCHAR(190) NULL DEFAULT NULL COMMENT \'بدء المرحلة\',`g89` VARCHAR(190) NULL DEFAULT NULL COMMENT \'انتهاء المرحلة\',`g90` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تسليم المرحلة للتالية\',`g91` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أحداث المرحلة\',`g92` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة المرحلة\',`g93` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g94` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g95` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g96` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_def5a64e_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-07 - مراحل الرحلة\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_trip_legs
'; }
else { echo 'x trp_transfer_trip_legs: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_damage_claims` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g97` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم المطالبة\',`g98` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الأمر\',`g99` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع الواقعة\',`g100` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وصف التلف\',`g101` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المتسبب المرجح\',`g102` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيمة المطالبة المقدرة\',`g103` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مستندات الإثبات\',`g104` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مسار المطالبة\',`g105` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قرار التسوية\',`g106` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيمة التسوية\',`g107` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة المطالبة\',`g108` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g109` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g110` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g111` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g112` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g113` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g114` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_b84f35f3_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-10 - مطالبات التلف والحوادث\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_damage_claims
'; }
else { echo 'x trp_transfer_damage_claims: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_closure` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g115` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الإقفال\',`g116` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الأمر\',`g117` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فحص محضر الاستلام\',`g118` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد بنود التكلفة\',`g119` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي التكلفة\',`g120` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التوزيع بالمتحمل\',`g121` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ترحيل قراءة العداد\',`g122` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الإحالة للمالية\',`g123` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ملاحظة الإقفال\',`g124` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الإقفال\',`g125` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g126` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g127` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g128` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g129` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g130` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g131` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_a3879ba8_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-12 - إقفال أمر الترحيل\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_closure
'; }
else { echo 'x trp_transfer_closure: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_permits` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g132` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف التصريح\',`g133` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الأمر\',`g134` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع التصريح\',`g135` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الجهة المصدرة\',`g136` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم التصريح\',`g137` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإصدار\',`g138` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الانتهاء\',`g139` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نطاق التصريح\',`g140` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الرسوم\',`g141` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرفق التصريح\',`g142` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة التصريح\',`g143` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g144` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g145` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g146` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_b9d03144_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-05 - لا سطر مسجل بعد في تصاريح المسار والحمولة\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_permits
'; }
else { echo 'x trp_transfer_permits: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_origin_handover` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g147` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف البند\',`g148` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الأمر\',`g149` VARCHAR(190) NULL DEFAULT NULL COMMENT \'بند التجهيز\',`g150` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنفذ\',`g151` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النتيجة\',`g152` VARCHAR(190) NULL DEFAULT NULL COMMENT \'محضر التسليم الأصلي\',`g153` VARCHAR(190) NULL DEFAULT NULL COMMENT \'صور حالة ما قبل النقل\',`g154` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تقييم مخاطر المسار\',`g155` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وقت الإنجاز\',`g156` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البند\',`g157` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g158` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g159` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g160` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_8a19ac57_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-06 - تجهيز المغادرة والتسليم الأصلي\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_origin_handover
'; }
else { echo 'x trp_transfer_origin_handover: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `trp_transfer_orders_report` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g161` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g162` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g163` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد الأوامر\',`g164` VARCHAR(190) NULL DEFAULT NULL COMMENT \'منها مقفلة\',`g165` VARCHAR(190) NULL DEFAULT NULL COMMENT \'متوسط زمن الرحلة\',`g166` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الالتزام بالمواعيد\',`g167` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حوادث وتلفيات\',`g168` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي التكلفة\',`g169` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تكلفة الكيلومتر\',`g170` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التوزيع بالوسيلة\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_ce38e6e3_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'TRP-13 - تقرير أوامر الترحيل\'';
if ($conn->query($sql)) { echo '+ جدول trp_transfer_orders_report
'; }
else { echo 'x trp_transfer_orders_report: ' . $conn->error . chr(10); }

ems_migration_recorded(__FILE__, $conn, (int) round((microtime(true) - $t0) * 1000));
