<?php
/**
 * 2028_03_29_govui_dep05_fields.php — DEP-05 · أعمدةُ حقولٍ لا نظيرَ لها في المخزن
 * @migration-objects: columns for DEP-05
 * مولَّدةٌ من `tools/govui_field_close.php` على مواصفةِ الإدارة —
 * واسمُ العمودِ تعليقُه اسمُ الحقلِ في ورقةِ الدليل.
 */
if (php_sapi_name() !== 'cli') { exit("CLI فقط\n"); }
error_reporting(E_ALL & ~E_DEPRECATED & ~E_WARNING & ~E_NOTICE);
mb_internal_encoding('UTF-8');
$ROOT = dirname(dirname(__DIR__));
require_once $ROOT . '/includes/env.php';
require_once __DIR__ . '/_ledger.php';
$host = ems_env('DB_HOST'); $port = 3306;
if (strpos($host, ':') !== false) { list($host, $port) = explode(':', $host); $port = (int) $port; }
mysqli_report(MYSQLI_REPORT_OFF);
$u = ems_env('DB_MIGRATOR_USER') ?: ems_env('DB_USER');
$p = ems_env('DB_MIGRATOR_USER') ? ems_env('DB_MIGRATOR_PASS') : ems_env('DB_PASS');
$conn = new mysqli($host, $u, $p, ems_env('DB_NAME'), $port);
if ($conn->connect_errno) { exit("connect fail\n"); }
$conn->set_charset('utf8mb4');
$t0 = microtime(true);

$sql = 'CREATE TABLE IF NOT EXISTS `fina_acc_adjustments` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g1` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g2` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g3` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النوع\',`g4` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود الحساب\',`g5` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مركز التكلفة\',`g6` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الأساس/المستند\',`g7` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القيمة\',`g8` VARCHAR(190) NULL DEFAULT NULL COMMENT \'جدول الاستهلاك/العكس\',`g9` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القيد المتولد\',`g10` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيد العكس التالي\',`g11` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السطر\',`g12` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g13` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g14` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g15` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g16` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g17` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g18` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_36ac2c1c_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-17 - الاستحقاقات والمقدَّمات والمخصصات\'';
if ($conn->query($sql)) { echo '+ جدول fina_acc_adjustments
'; }
else { echo 'x fina_acc_adjustments: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_acc_reopen_governance` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g19` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الطلب\',`g20` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة المستهدفة\',`g21` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مبرر إعادة الفتح\',`g22` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الوحدات المفتوحة\',`g23` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النطاق الزمني للفتح\',`g24` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع اعتماد AAM\',`g25` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القيود الموسومة بعد الفتح\',`g26` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إعادة الإقفال\',`g27` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الطلب\',`g28` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g29` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g30` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g31` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g32` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g33` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g34` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_dabb06fe_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-25 - حوكمة إعادة فتح الفترات\'';
if ($conn->query($sql)) { echo '+ جدول fina_acc_reopen_governance
'; }
else { echo 'x fina_acc_reopen_governance: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_periods_fin` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g35` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الفترة\',`g36` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الشهر\',`g37` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيود الفترة\',`g38` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيود معلقة\',`g39` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مطابقة المخازن\',`g40` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مطابقة الخزينة\',`g41` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الإقفالات التشغيلية الواردة\',`g42` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فروق معالجة\',`g43` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قرار الإقفال\',`g44` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قرار إعادة الفتح\',`g45` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الفترة\',`g46` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g47` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g48` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g49` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g50` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g51` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g52` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_6d3cc422_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-23 - التقويم المحاسبي للفترات\'';
if ($conn->query($sql)) { echo '+ جدول fina_periods_fin
'; }
else { echo 'x fina_periods_fin: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_acc_trial_balance` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g53` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g54` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g55` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود الحساب\',`g56` VARCHAR(190) NULL DEFAULT NULL COMMENT \'اسم الحساب\',`g57` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رصيد افتتاحي مدين\',`g58` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رصيد افتتاحي دائن\',`g59` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حركة مدينة\',`g60` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حركة دائنة\',`g61` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ختامي مدين\',`g62` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ختامي دائن\',`g63` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التوازن الكلي\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_79705fa9_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-21 - ميزان المراجعة\'';
if ($conn->query($sql)) { echo '+ جدول fina_acc_trial_balance
'; }
else { echo 'x fina_acc_trial_balance: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_effect_map` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g64` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g65` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الواقعة الأصلية\',`g66` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الإدارة المصدر\',`g67` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الحدث الناشر\',`g68` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قاعدة الأثر بمصفوفة التكامل\',`g69` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القيد المتولد\',`g70` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ القيد\',`g71` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيمة الأثر\',`g72` VARCHAR(190) NULL DEFAULT NULL COMMENT \'زمن التأخر بين الواقعة والقيد\',`g73` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الاتساق\',`g74` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المعالجة\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_15a10a51_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-13 - تتبّع الأثر من الواقعة إلى القيد\'';
if ($conn->query($sql)) { echo '+ جدول fina_effect_map
'; }
else { echo 'x fina_effect_map: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_acc_credit_control` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g75` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g76` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم العميل\',`g77` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الحد الائتماني المعتمد\',`g78` VARCHAR(190) NULL DEFAULT NULL COMMENT \'العملة\',`g79` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع اعتماد الحد\',`g80` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المستهلك\',`g81` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المتاح\',`g82` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تجاوز؟\',`g83` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجراء التجاوز\',`g84` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الحد\',`g85` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g86` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g87` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g88` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_d2e6605f_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-15 - الرقابة الائتمانية وحدود العملاء\'';
if ($conn->query($sql)) { echo '+ جدول fina_acc_credit_control
'; }
else { echo 'x fina_acc_credit_control: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_tax_fin` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g89` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الإقرار\',`g90` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g91` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع الضريبة\',`g92` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ضريبة المخرجات\',`g93` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ضريبة المدخلات\',`g94` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الصافي المستحق\',`g95` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاستحقاق النظامي\',`g96` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع التقديم بالحوكمة\',`g97` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع السداد بالخزينة\',`g98` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الإقرار\',`g99` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g100` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g101` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g102` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_41db7241_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-18 - الضرائب والقيمة المضافة\'';
if ($conn->query($sql)) { echo '+ جدول fina_tax_fin
'; }
else { echo 'x fina_tax_fin: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_closing_checklist` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g103` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف البند\',`g104` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g105` VARCHAR(190) NULL DEFAULT NULL COMMENT \'بند الفحص\',`g106` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المسؤول\',`g107` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع الإنجاز\',`g108` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النتيجة\',`g109` VARCHAR(190) NULL DEFAULT NULL COMMENT \'استثناء موثق\',`g110` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وقت الإنجاز\',`g111` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البند\',`g112` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g113` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g114` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g115` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_0bb75839_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-22 - لا سطر مسجل بعد في قائمة إقفال الفترة\'';
if ($conn->query($sql)) { echo '+ جدول fina_closing_checklist
'; }
else { echo 'x fina_closing_checklist: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_acc_cost_centers` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g116` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود المركز\',`g117` VARCHAR(190) NULL DEFAULT NULL COMMENT \'اسم المركز\',`g118` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المركز الأب\',`g119` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع المركز\',`g120` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرجع المربوط\',`g121` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مسؤول المركز\',`g122` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة المركز\',`g123` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g124` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g125` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g126` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_e506da6b_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-03 - مراكز التكلفة\'';
if ($conn->query($sql)) { echo '+ جدول fina_acc_cost_centers
'; }
else { echo 'x fina_acc_cost_centers: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_reconciliations` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g127` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف المطابقة\',`g128` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g129` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود الحساب الرقابي\',`g130` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رصيد الأستاذ\',`g131` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رصيد المصدر التفصيلي\',`g132` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المصدر\',`g133` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفرق\',`g134` VARCHAR(190) NULL DEFAULT NULL COMMENT \'بنود الفروق\',`g135` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سبب الفرق\',`g136` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معالجة الفرق\',`g137` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفرق المتبقي\',`g138` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة المطابقة\',`g139` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g140` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g141` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g142` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_7512c9bb_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-20 - لا سطر مسجل بعد في مطابقات الحسابات\'';
if ($conn->query($sql)) { echo '+ جدول fina_reconciliations
'; }
else { echo 'x fina_reconciliations: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_collections` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g143` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g144` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم العميل\',`g145` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم المشروع\',`g146` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي الذمة\',`g147` VARCHAR(190) NULL DEFAULT NULL COMMENT \'شريحة العمر\',`g148` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيمة الشريحة\',`g149` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة التحصيل\',`g150` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إتاحة النقد للاستخدام\',`g151` VARCHAR(190) NULL DEFAULT NULL COMMENT \'آخر تحصيل\',`g152` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجراء المطالبة\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_dba465a3_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-14 - ذمم العملاء وأعمارها\'';
if ($conn->query($sql)) { echo '+ جدول fina_collections
'; }
else { echo 'x fina_collections: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_dashboard_kpi` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g153` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف المؤشر\',`g154` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المؤشر KPI Catalog\',`g155` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القيمة\',`g156` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الوحدة\',`g157` VARCHAR(190) NULL DEFAULT NULL COMMENT \'العملة\',`g158` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الحالة\',`g159` VARCHAR(190) NULL DEFAULT NULL COMMENT \'آخر تحديث\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_b0436877_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-01 - لا سطر مسجل بعد في لوحة المالية\'';
if ($conn->query($sql)) { echo '+ جدول fina_dashboard_kpi
'; }
else { echo 'x fina_dashboard_kpi: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_dues` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g160` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الاستحقاق\',`g161` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم فاتورة المورد\',`g162` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم المورد\',`g163` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مصدر الاستحقاق\',`g164` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`g165` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فحص البوابة\',`g166` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيمة الاستحقاق\',`g167` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الضريبة\',`g168` VARCHAR(190) NULL DEFAULT NULL COMMENT \'العملة\',`g169` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاستحقاق\',`g170` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المسدد\',`g171` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المتبقي\',`g172` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الاستحقاق\',`g173` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g174` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g175` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g176` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g177` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g178` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_199f8e6e_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-09 - لا سطر مسجل بعد في فواتير الموردين والمستحقات\'';
if ($conn->query($sql)) { echo '+ جدول fina_dues
'; }
else { echo 'x fina_dues: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_journal_form_fin` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g179` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم القيد\',`g180` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ القيد\',`g181` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المصدر\',`g182` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع الحدث\',`g183` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الوصف\',`g184` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد أسطر القيد تفصيلها م06-2\',`g185` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي المدين\',`g186` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي الدائن\',`g187` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التوازن\',`g188` VARCHAR(190) NULL DEFAULT NULL COMMENT \'العملة\',`g189` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سعر الصرف\',`g190` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g191` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيد عكسي ل\',`g192` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة القيد\',`g193` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g194` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g195` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g196` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g197` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g198` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g199` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_1bc14355_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-11 - القيود اليومية\'';
if ($conn->query($sql)) { echo '+ جدول fina_journal_form_fin
'; }
else { echo 'x fina_journal_form_fin: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_currencies` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g200` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g201` VARCHAR(190) NULL DEFAULT NULL COMMENT \'العملة\',`g202` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مقابل\',`g203` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع السعر\',`g204` VARCHAR(190) NULL DEFAULT NULL COMMENT \'السعر\',`g205` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ السريان\',`g206` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المصدر/التوثيق\',`g207` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السطر\',`g208` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g209` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g210` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g211` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_b923439e_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-06 - لا سطر مسجل بعد في أسعار الصرف\'';
if ($conn->query($sql)) { echo '+ جدول fina_currencies
'; }
else { echo 'x fina_currencies: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `fina_financial_statements_fin` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g212` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g213` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g214` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القائمة\',`g215` VARCHAR(190) NULL DEFAULT NULL COMMENT \'البند\',`g216` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القيمة\',`g217` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فترة المقارنة\',`g218` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التغير\',`g219` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ملاحظة إفصاح\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_ec99e754_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'ACC-24 - القوائم المالية\'';
if ($conn->query($sql)) { echo '+ جدول fina_financial_statements_fin
'; }
else { echo 'x fina_financial_statements_fin: ' . $conn->error . chr(10); }

ems_migration_recorded(__FILE__, $conn, (int) round((microtime(true) - $t0) * 1000));
