<?php
/**
 * 2028_03_27_govui_dep07_fields.php — DEP-07 · أعمدةُ حقولٍ لا نظيرَ لها في المخزن
 * @migration-objects: columns for DEP-07
 * مولَّدةٌ من `tools/govui_field_close.php` على مواصفةِ الإدارة —
 * واسمُ العمودِ تعليقُه اسمُ الحقلِ في ورقةِ الدليل.
 */
if (php_sapi_name() !== 'cli') { exit("CLI فقط\n"); }
error_reporting(E_ALL & ~E_DEPRECATED & ~E_WARNING & ~E_NOTICE);
mb_internal_encoding('UTF-8');
$ROOT = dirname(dirname(__DIR__));
require_once $ROOT . '/includes/env.php';
require_once __DIR__ . '/_ledger.php';
$host = ems_env('DB_HOST'); $port = 3306;
if (strpos($host, ':') !== false) { list($host, $port) = explode(':', $host); $port = (int) $port; }
mysqli_report(MYSQLI_REPORT_OFF);
$u = ems_env('DB_MIGRATOR_USER') ?: ems_env('DB_USER');
$p = ems_env('DB_MIGRATOR_USER') ? ems_env('DB_MIGRATOR_PASS') : ems_env('DB_PASS');
$conn = new mysqli($host, $u, $p, ems_env('DB_NAME'), $port);
if ($conn->connect_errno) { exit("connect fail\n"); }
$conn->set_charset('utf8mb4');
$t0 = microtime(true);

$sql = 'CREATE TABLE IF NOT EXISTS `hr_disciplinary` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g1` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم القضية\',`g2` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g3` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مصدر الواقعة\',`g4` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع الإحالة\',`g5` VARCHAR(190) NULL DEFAULT NULL COMMENT \'وصف الواقعة\',`g6` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الواقعة\',`g7` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المحقق المكلف\',`g8` VARCHAR(190) NULL DEFAULT NULL COMMENT \'محضر التحقيق\',`g9` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أقوال الموظف\',`g10` VARCHAR(190) NULL DEFAULT NULL COMMENT \'لجنة القرار\',`g11` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القرار\',`g12` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرجع اللائحي\',`g13` VARCHAR(190) NULL DEFAULT NULL COMMENT \'قيمة الجزاء المالي\',`g14` VARCHAR(190) NULL DEFAULT NULL COMMENT \'Deduction_Reference الناتج\',`g15` VARCHAR(190) NULL DEFAULT NULL COMMENT \'اعتراض الموظف\',`g16` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة القضية\',`g17` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g18` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g19` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g20` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g21` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g22` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g23` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_38521080_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-17 - القضايا التأديبية والتحقيق\'';
if ($conn->query($sql)) { echo '+ جدول hr_disciplinary
'; }
else { echo 'x hr_disciplinary: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_recruitment_pipeline` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g24` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الشاغر\',`g25` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الفتح\',`g26` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الإدارة الطالبة\',`g27` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المسمى الوظيفي\',`g28` VARCHAR(190) NULL DEFAULT NULL COMMENT \'سبب الشاغر\',`g29` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد المطلوبين\',`g30` VARCHAR(190) NULL DEFAULT NULL COMMENT \'اشتراطات الشاغر\',`g31` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرحلة\',`g32` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرشحون\',`g33` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرشح المقبول\',`g34` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نتيجة الاختبار العملي\',`g35` VARCHAR(190) NULL DEFAULT NULL COMMENT \'العرض المقدم\',`g36` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ المباشرة\',`g37` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الشاغر\',`g38` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g39` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g40` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g41` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g42` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g43` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g44` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_447c70c2_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-04 - التوظيف من الشاغر إلى المباشرة\'';
if ($conn->query($sql)) { echo '+ جدول hr_recruitment_pipeline
'; }
else { echo 'x hr_recruitment_pipeline: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_workforce_report` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g45` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g46` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الفترة\',`g47` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الإدارة\',`g48` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد الموظفين\',`g49` VARCHAR(190) NULL DEFAULT NULL COMMENT \'منهم مشروعيون\',`g50` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مباشرون جدد\',`g51` VARCHAR(190) NULL DEFAULT NULL COMMENT \'منتهية خدمتهم\',`g52` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معدل الدوران\',`g53` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نسبة الغياب\',`g54` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ساعات إضافية\',`g55` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كلفة العمالة\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_1a32fad1_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-24 - تقرير القوى العاملة\'';
if ($conn->query($sql)) { echo '+ جدول hr_workforce_report
'; }
else { echo 'x hr_workforce_report: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_job_movements` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g56` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الحركة\',`g57` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g58` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع الحركة\',`g59` VARCHAR(190) NULL DEFAULT NULL COMMENT \'من منصب/وحدة\',`g60` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلى منصب/وحدة\',`g61` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الموجب/المرجع\',`g62` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أثر الأجر\',`g63` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ النفاذ\',`g64` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الحركة\',`g65` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g66` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g67` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g68` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g69` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g70` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g71` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_b9dd3a29_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-12 - الحركات الوظيفية\'';
if ($conn->query($sql)) { echo '+ جدول hr_job_movements
'; }
else { echo 'x hr_job_movements: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_payroll_lines` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g72` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g73` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف المسير\',`g74` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g75` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الأساسي\',`g76` VARCHAR(190) NULL DEFAULT NULL COMMENT \'البدلات\',`g77` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حافز الإنتاج من أساس القوى\',`g78` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الخصومات بمرجع ب08\',`g79` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التأمينات بمرجع ب08-2\',`g80` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أقساط السلف بمرجع ب08-3\',`g81` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الصافي\',`g82` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السطر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_2353b9de_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-22 - أسطر مسيّر الرواتب\'';
if ($conn->query($sql)) { echo '+ جدول hr_payroll_lines
'; }
else { echo 'x hr_payroll_lines: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_payroll_runs` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g83` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف المسير\',`g84` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الشهر\',`g85` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نطاق المسير\',`g86` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد الموظفين\',`g87` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي الأساسي\',`g88` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي البدلات\',`g89` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حوافز الإنتاج\',`g90` VARCHAR(190) NULL DEFAULT NULL COMMENT \'أساس القوى للمشغلين\',`g91` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إجمالي الخصومات\',`g92` VARCHAR(190) NULL DEFAULT NULL COMMENT \'صافي المسير\',`g93` VARCHAR(190) NULL DEFAULT NULL COMMENT \'العملة\',`g94` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الإحالة للمالية\',`g95` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الإحالة للخزينة\',`g96` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة المسير\',`g97` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g98` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g99` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g100` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g101` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g102` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g103` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_2c826fdb_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-21 - مسيّر الرواتب\'';
if ($conn->query($sql)) { echo '+ جدول hr_payroll_runs
'; }
else { echo 'x hr_payroll_runs: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_performance` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g104` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف التقييم\',`g105` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g106` VARCHAR(190) NULL DEFAULT NULL COMMENT \'دورة التقييم\',`g107` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المقيم\',`g108` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مدخل أداء القوى و13\',`g109` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الدرجة\',`g110` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نقاط القوة\',`g111` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فرص التحسين\',`g112` VARCHAR(190) NULL DEFAULT NULL COMMENT \'خطة التطوير\',`g113` VARCHAR(190) NULL DEFAULT NULL COMMENT \'اعتماد المدير\',`g114` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إقرار الموظف\',`g115` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة التقييم\',`g116` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g117` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g118` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g119` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_ca3a8b9e_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-16 - تقييم الأداء الوظيفي\'';
if ($conn->query($sql)) { echo '+ جدول hr_performance
'; }
else { echo 'x hr_performance: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_project_contracts` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g120` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g121` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف العقد\',`g122` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g123` VARCHAR(190) NULL DEFAULT NULL COMMENT \'Project_ID المشروع الرابط الأساسي\',`g124` VARCHAR(190) NULL DEFAULT NULL COMMENT \'احتياج التوظيف المرجعي\',`g125` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عقد المورد محفزا لا رابطا\',`g126` VARCHAR(190) NULL DEFAULT NULL COMMENT \'محفز الانتهاء المتفق\',`g127` VARCHAR(190) NULL DEFAULT NULL COMMENT \'محفز الانتهاء الواقع\',`g128` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الوقوع\',`g129` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فترة الإخطار\',`g130` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع التصفية\',`g131` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة التصفية\',`g132` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g133` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g134` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g135` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_367fc7e8_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-11 - عقود المشاريع المؤقتة\'';
if ($conn->query($sql)) { echo '+ جدول hr_project_contracts
'; }
else { echo 'x hr_project_contracts: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_training` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g136` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السجل\',`g137` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g138` VARCHAR(190) NULL DEFAULT NULL COMMENT \'البرنامج\',`g139` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع التدريب\',`g140` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الجهة\',`g141` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإتمام\',`g142` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النتيجة\',`g143` VARCHAR(190) NULL DEFAULT NULL COMMENT \'صلاحية الشهادة\',`g144` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلزامي؟\',`g145` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السجل\',`g146` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g147` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g148` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g149` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_141ac8a1_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-15 - التدريب والكفاءة\'';
if ($conn->query($sql)) { echo '+ جدول hr_training
'; }
else { echo 'x hr_training: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_benefits` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g150` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g151` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g152` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع الميزة\',`g153` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الجهة/الوثيقة\',`g154` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حصة الشركة\',`g155` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حصة الموظف\',`g156` VARCHAR(190) NULL DEFAULT NULL COMMENT \'من تاريخ\',`g157` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلى تاريخ\',`g158` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المسير\',`g159` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السطر\',`g160` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g161` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g162` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g163` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_80215210_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-19 - المزايا والتأمينات\'';
if ($conn->query($sql)) { echo '+ جدول hr_benefits
'; }
else { echo 'x hr_benefits: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_employees` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g164` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g165` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الاسم الرباعي\',`g166` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الرقم الوطني\',`g167` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الميلاد\',`g168` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النوع\',`g169` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الحالة الاجتماعية\',`g170` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المؤهل\',`g171` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المسمى الوظيفي\',`g172` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الإدارة\',`g173` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الموقع\',`g174` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ المباشرة\',`g175` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مشغل تشغيلي؟\',`g176` VARCHAR(190) NULL DEFAULT NULL COMMENT \'كود المشغل بالقوى\',`g177` VARCHAR(190) NULL DEFAULT NULL COMMENT \'بيانات التواصل\',`g178` VARCHAR(190) NULL DEFAULT NULL COMMENT \'شخص الطوارئ\',`g179` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الحساب البنكي\',`g180` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الخدمة\',`g181` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g182` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g183` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g184` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g185` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g186` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g187` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_9236848a_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-07 - سجل الموظفين\'';
if ($conn->query($sql)) { echo '+ جدول hr_employees
'; }
else { echo 'x hr_employees: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_attendance` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g188` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السجل\',`g189` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g190` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التاريخ\',`g191` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رمز الحالة\',`g192` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ساعات إضافية\',`g193` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المأمورية\',`g194` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع الإجازة\',`g195` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مصدر التسجيل\',`g196` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ملاحظة\',`g197` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السجل\',`g198` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g199` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g200` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g201` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_cfb090e0_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-13 - الحضور والانصراف\'';
if ($conn->query($sql)) { echo '+ جدول hr_attendance
'; }
else { echo 'x hr_attendance: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_rec_applications` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g202` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الترشح\',`g203` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الشاغر\',`g204` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرشح\',`g205` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مصدر الترشح\',`g206` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المؤهل\',`g207` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الخبرة\',`g208` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نتيجة الفرز الأولي\',`g209` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرحلة الحالية\',`g210` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الترشح\',`g211` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g212` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g213` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g214` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_8dd52919_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-05 - طلبات الترشح\'';
if ($conn->query($sql)) { echo '+ جدول hr_rec_applications
'; }
else { echo 'x hr_rec_applications: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_onboarding` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g215` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف التهيئة\',`g216` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g217` VARCHAR(190) NULL DEFAULT NULL COMMENT \'بند التهيئة\',`g218` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المسؤول\',`g219` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع الإنجاز\',`g220` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النتيجة\',`g221` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنجاز\',`g222` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البند\',`g223` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g224` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g225` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g226` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_7601168f_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-09 - لا سطر مسجل بعد في التهيئة والمباشرة\'';
if ($conn->query($sql)) { echo '+ جدول hr_onboarding
'; }
else { echo 'x hr_onboarding: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_dashboard_kpi` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g227` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف المؤشر\',`g228` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المؤشر KPI Catalog\',`g229` VARCHAR(190) NULL DEFAULT NULL COMMENT \'القيمة\',`g230` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الوحدة\',`g231` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الحالة\',`g232` VARCHAR(190) NULL DEFAULT NULL COMMENT \'آخر تحديث\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_bd45548d_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-01 - لا سطر مسجل بعد في لوحة الموارد البشرية\'';
if ($conn->query($sql)) { echo '+ جدول hr_dashboard_kpi
'; }
else { echo 'x hr_dashboard_kpi: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_rec_stages` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g233` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف السطر\',`g234` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف الترشح\',`g235` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرحلة\',`g236` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المقيم\',`g237` VARCHAR(190) NULL DEFAULT NULL COMMENT \'التاريخ\',`g238` VARCHAR(190) NULL DEFAULT NULL COMMENT \'النتيجة\',`g239` VARCHAR(190) NULL DEFAULT NULL COMMENT \'ملاحظة التقييم\',`g240` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة السطر\',`g241` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g242` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g243` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g244` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_033f5771_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-06 - مراحل التوظيف\'';
if ($conn->query($sql)) { echo '+ جدول hr_rec_stages
'; }
else { echo 'x hr_rec_stages: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_employee_documents` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g245` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف المستند\',`g246` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g247` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع المستند\',`g248` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم المستند\',`g249` VARCHAR(190) NULL DEFAULT NULL COMMENT \'جهة الإصدار\',`g250` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإصدار\',`g251` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الانتهاء\',`g252` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلزامي؟\',`g253` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المرفق\',`g254` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة المستند\',`g255` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g256` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g257` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g258` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_4444250e_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-08 - لا سطر مسجل بعد في مستندات الموظف\'';
if ($conn->query($sql)) { echo '+ جدول hr_employee_documents
'; }
else { echo 'x hr_employee_documents: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_employee_contracts` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g259` VARCHAR(190) NULL DEFAULT NULL COMMENT \'معرف العقد\',`g260` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g261` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فئة العقد\',`g262` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع العقد\',`g263` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نموذج الأجر\',`g264` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الأجر الأساسي\',`g265` VARCHAR(190) NULL DEFAULT NULL COMMENT \'البدلات\',`g266` VARCHAR(190) NULL DEFAULT NULL COMMENT \'العملة\',`g267` VARCHAR(190) NULL DEFAULT NULL COMMENT \'من تاريخ\',`g268` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلى تاريخ\',`g269` VARCHAR(190) NULL DEFAULT NULL COMMENT \'فترة التجربة\',`g270` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المشروع\',`g271` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرفق العقد الموقع\',`g272` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة العقد\',`g273` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g274` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g275` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g276` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g277` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g278` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g279` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_7ee17aff_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-10 - لا سطر مسجل بعد في عقود الموظفين\'';
if ($conn->query($sql)) { echo '+ جدول hr_employee_contracts
'; }
else { echo 'x hr_employee_contracts: ' . $conn->error . chr(10); }

$sql = 'CREATE TABLE IF NOT EXISTS `hr_worker_leave_absence` (`id` INT NOT NULL AUTO_INCREMENT,`company_id` INT NOT NULL DEFAULT 0 COMMENT \'بوابة المستأجر\',`g280` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الطلب\',`g281` VARCHAR(190) NULL DEFAULT NULL COMMENT \'رقم الموظف\',`g282` VARCHAR(190) NULL DEFAULT NULL COMMENT \'نوع الإجازة\',`g283` VARCHAR(190) NULL DEFAULT NULL COMMENT \'من تاريخ\',`g284` VARCHAR(190) NULL DEFAULT NULL COMMENT \'إلى تاريخ\',`g285` VARCHAR(190) NULL DEFAULT NULL COMMENT \'عدد الأيام\',`g286` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الرصيد قبل\',`g287` VARCHAR(190) NULL DEFAULT NULL COMMENT \'الرصيد بعد\',`g288` VARCHAR(190) NULL DEFAULT NULL COMMENT \'البديل المكلف\',`g289` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرفق مساند\',`g290` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع دورة التناوب\',`g291` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة الطلب\',`g292` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المنشئ\',`g293` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الإنشاء\',`g294` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المراجع\',`g295` VARCHAR(190) NULL DEFAULT NULL COMMENT \'المعتمد\',`g296` VARCHAR(190) NULL DEFAULT NULL COMMENT \'تاريخ الاعتماد\',`g297` VARCHAR(190) NULL DEFAULT NULL COMMENT \'حالة البيانات\',`g298` VARCHAR(190) NULL DEFAULT NULL COMMENT \'مرجع المصدر\',`created_at` DATETIME NULL DEFAULT NULL,`created_by` INT NULL DEFAULT NULL,`updated_at` DATETIME NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `ix_3a6233a4_co` (`company_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT \'HR-14 - الإجازات والغياب\'';
if ($conn->query($sql)) { echo '+ جدول hr_worker_leave_absence
'; }
else { echo 'x hr_worker_leave_absence: ' . $conn->error . chr(10); }

ems_migration_recorded(__FILE__, $conn, (int) round((microtime(true) - $t0) * 1000));
