<?php
/**
 * includes/cmp03_registry.php — سجل تحرير الشاشات من المخزن البيني (الموجة ٢)
 * مولَّد آليًّا بـ tools/cmp03_wave2_generate.php — لا يُحرَّر يدويًّا.
 * canonical_file ← جدولها الأصلي + خريطة (تسمية مطبَّعة ← عمود).
 */
if (!function_exists('cmp03_registry')) {
function cmp03_registry() {
    return array (
  'asset_recon.php' => 
  array (
    'table' => 'scr_asset_recon',
    'map' => 
    array (
      'رقم المحضر' => 'no_minutes_doc',
      'الفترة' => 'period_ref',
      'كود المعدة' => 'code_equipment',
      'الساعات حسب سجل الأصول' => 'hours_per_asset_log',
      'الساعات حسب التايم شيت' => 'hours_per_timesheet',
      'الفرق' => 'variance',
      'نسبة الفرق' => 'pct_variance',
      'تصنيف الفرق' => 'classification_variance',
      'تفسير الفرق' => 'explanation_variance',
      'التصحيح المعتمد' => 'correction_approved',
      'أثر التصحيح على الإهلاك' => 'impact_correction_on_depreciation',
      'طابقه' => 'matched_by',
      'اعتمده' => 'approved_by',
      'تاريخ الإقفال' => 'date_closing',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_minutes_doc' => 'رقم المحضر',
      'period_ref' => 'الفترة',
      'code_equipment' => 'كود المعدة',
      'hours_per_asset_log' => 'الساعات حسب سجل الأصول',
      'hours_per_timesheet' => 'الساعات حسب التايم شيت',
      'variance' => 'الفرق',
      'pct_variance' => 'نسبة الفرق',
      'classification_variance' => 'تصنيف الفرق',
      'explanation_variance' => 'تفسير الفرق',
      'correction_approved' => 'التصحيح المعتمد',
      'impact_correction_on_depreciation' => 'أثر التصحيح على الإهلاك',
      'matched_by' => 'طابقه',
      'approved_by' => 'اعتمده',
      'date_closing' => 'تاريخ الإقفال',
      'status_label' => 'الحالة',
    ),
  ),
  'code_bridge.php' => 
  array (
    'table' => 'scr_code_bridge',
    'map' => 
    array (
      'رقم الجسر' => 'no_bridge',
      'الكود الموحد' => 'code_unified',
      'اسم المعدة' => 'name_equipment',
      'رقم اللوحة' => 'no_plate',
      'الكود القديم' => 'code_old',
      'كود المورد' => 'code_supplier',
      'كود الشركة المصنعة' => 'code_company_manufacturer',
      'الرقم التسلسلي' => 'no_serial',
      'مصدر الكود' => 'source_code',
      'حالة التطابق' => 'state_match',
      'تعارض مكتشف' => 'conflict_detected',
      'وصف التعارض' => 'description_conflict',
      'قرار الفض' => 'decision_resolution',
      'تاريخ الربط' => 'date_link',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_bridge' => 'رقم الجسر',
      'code_unified' => 'الكود الموحَّد',
      'name_equipment' => 'اسم المعدة',
      'no_plate' => 'رقم اللوحة',
      'code_old' => 'الكود القديم',
      'code_supplier' => 'كود المورد',
      'code_company_manufacturer' => 'كود الشركة المصنِّعة',
      'no_serial' => 'الرقم التسلسلي',
      'source_code' => 'مصدر الكود',
      'state_match' => 'حالة التطابق',
      'conflict_detected' => 'تعارض مكتشف',
      'description_conflict' => 'وصف التعارض',
      'decision_resolution' => 'قرار الفض',
      'date_link' => 'تاريخ الربط',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'status_label' => 'الحالة',
    ),
  ),
  'equipment_sourcing.php' => 
  array (
    'table' => 'scr_equipment_sourcing',
    'map' => 
    array (
      'كود المعدة' => 'code_equipment',
      'نمط المصدر' => 'pattern_source',
      'المورد أو الممول' => 'supplier_or_financier',
      'نموذج التمويل' => 'model_financing',
      'عملية التمويل' => 'operation_financing',
      'تاريخ الدخول' => 'date_entry',
      'تاريخ نقل الملكية المتوقع' => 'date_transfer_ownership_expected',
      'المالك القانوني الحالي' => 'owner_legal_current',
      'المنتفع الاقتصادي' => 'beneficiary_economic',
      'حامل الإهلاك' => 'holder_depreciation',
      'حامل الصيانة' => 'holder_maintenance',
      'حامل التأمين' => 'holder_insurance',
      'مرتهن الضمان' => 'pledgee_warranty',
      'قيمة الأصل' => 'value_asset',
      'العملة' => 'currency',
      'الالتزام القائم' => 'commitment_outstanding',
      'المعالجة المحاسبية' => 'handling_accounting',
      'درجة السرية' => 'grade_confidentiality',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'code_equipment' => 'كود المعدة',
      'pattern_source' => 'نمط المصدر',
      'supplier_or_financier' => 'المورد أو الممول',
      'model_financing' => 'نموذج التمويل',
      'operation_financing' => 'عملية التمويل',
      'date_entry' => 'تاريخ الدخول',
      'date_transfer_ownership_expected' => 'تاريخ نقل الملكية المتوقع',
      'owner_legal_current' => 'المالك القانوني الحالي',
      'beneficiary_economic' => 'المنتفع الاقتصادي',
      'holder_depreciation' => 'حامل الإهلاك',
      'holder_maintenance' => 'حامل الصيانة',
      'holder_insurance' => 'حامل التأمين',
      'pledgee_warranty' => 'مرتهن الضمان',
      'value_asset' => 'قيمة الأصل',
      'currency' => 'العملة',
      'commitment_outstanding' => 'الالتزام القائم',
      'handling_accounting' => 'المعالجة المحاسبية',
      'grade_confidentiality' => 'درجة السرية',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'status_label' => 'الحالة',
    ),
  ),
  'fin_assets.php' => 
  array (
    'table' => 'scr_fin_assets',
    'map' => 
    array (
      'رقم السجل' => 'no_log',
      'كود العين' => 'code_asset_item',
      'نوع الأصل' => 'type_asset',
      'عملية التمويل' => 'operation_financing',
      'الممول' => 'financier_name',
      'نموذج التمويل' => 'model_financing',
      'قيمة الشراء' => 'value_purchase',
      'رأس المال الممول' => 'capital_capital_financier',
      'تاريخ الربط' => 'date_link',
      'تاريخ فك الربط' => 'date_unlink_link',
      'في الأسطول المشغل؟' => 'in_active_fleet',
      'حامل الإهلاك' => 'holder_depreciation',
      'مرتهن الضمان' => 'pledgee_warranty',
      'درجة السرية' => 'grade_confidentiality',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرفق' => 'attachment',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
    ),
    'labels' => 
    array (
      'no_log' => 'رقم السجل',
      'code_asset_item' => 'كود العين',
      'type_asset' => 'نوع الأصل',
      'operation_financing' => 'عملية التمويل',
      'financier_name' => 'الممول',
      'model_financing' => 'نموذج التمويل',
      'value_purchase' => 'قيمة الشراء',
      'capital_capital_financier' => 'رأس المال المموَّل',
      'date_link' => 'تاريخ الربط',
      'date_unlink_link' => 'تاريخ فك الربط',
      'in_active_fleet' => 'في الأسطول المشغَّل؟',
      'holder_depreciation' => 'حامل الإهلاك',
      'pledgee_warranty' => 'مرتهن الضمان',
      'grade_confidentiality' => 'درجة السرية',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'attachment' => 'المرفق',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
    ),
  ),
  'fin_changes.php' => 
  array (
    'table' => 'scr_fin_changes',
    'map' => 
    array (
      'رقم المحضر' => 'no_minutes_doc',
      'عملية التمويل' => 'operation_financing',
      'تاريخ التغيير' => 'date_change',
      'نوع التغيير' => 'type_change',
      'الصيغة قبل' => 'formula_before',
      'الصيغة بعد' => 'formula_after',
      'رأس المال قبل' => 'capital_before',
      'رأس المال بعد' => 'capital_after',
      'عدد الأقساط قبل' => 'count_installments_before',
      'عدد الأقساط بعد' => 'count_installments_after',
      'قيمة القسط قبل' => 'value_installment_before',
      'قيمة القسط بعد' => 'value_installment_after',
      'سبب التغيير' => 'reason_change',
      'مستند التغيير' => 'doc_change',
      'اعتمده' => 'approved_by',
      'الحالة' => 'status_label',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
    ),
    'labels' => 
    array (
      'no_minutes_doc' => 'رقم المحضر',
      'operation_financing' => 'عملية التمويل',
      'date_change' => 'تاريخ التغيير',
      'type_change' => 'نوع التغيير',
      'formula_before' => 'الصيغة قبل',
      'formula_after' => 'الصيغة بعد',
      'capital_before' => 'رأس المال قبل',
      'capital_after' => 'رأس المال بعد',
      'count_installments_before' => 'عدد الأقساط قبل',
      'count_installments_after' => 'عدد الأقساط بعد',
      'value_installment_before' => 'قيمة القسط قبل',
      'value_installment_after' => 'قيمة القسط بعد',
      'reason_change' => 'سبب التغيير',
      'doc_change' => 'مستند التغيير',
      'approved_by' => 'اعتمده',
      'status_label' => 'الحالة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
    ),
  ),
  'fin_models.php' => 
  array (
    'table' => 'scr_fin_models',
    'map' => 
    array (
      'رمز النموذج' => 'code_model',
      'اسم النموذج' => 'name_model',
      'المالك القانوني' => 'owner_legal',
      'المنتفع الاقتصادي' => 'beneficiary_economic',
      'الاعتراف المحاسبي' => 'recognition_accounting',
      'حامل الإهلاك' => 'holder_depreciation',
      'مرتهن الضمان' => 'pledgee_warranty',
      'معالجة الالتزام' => 'handling_commitment',
      'معالجة العائد' => 'handling_return',
      'المرجع المحاسبي' => 'ref_accounting',
      'اعتمده المراجع' => 'approved_by_auditor',
      'تاريخ الاعتماد' => 'approved_date',
      'الحالة' => 'status_label',
      'مرجع التفويض' => 'authority_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'code_model' => 'رمز النموذج',
      'name_model' => 'اسم النموذج',
      'owner_legal' => 'المالك القانوني',
      'beneficiary_economic' => 'المنتفع الاقتصادي',
      'recognition_accounting' => 'الاعتراف المحاسبي',
      'holder_depreciation' => 'حامل الإهلاك',
      'pledgee_warranty' => 'مرتهن الضمان',
      'handling_commitment' => 'معالجة الالتزام',
      'handling_return' => 'معالجة العائد',
      'ref_accounting' => 'المرجع المحاسبي',
      'approved_by_auditor' => 'اعتمده المراجع',
      'approved_date' => 'تاريخ الاعتماد',
      'status_label' => 'الحالة',
      'authority_ref' => 'مرجع التفويض',
      'attachment' => 'المرفق',
    ),
  ),
  'ownership_links.php' => 
  array (
    'table' => 'scr_ownership_links',
    'map' => 
    array (
      'رقم العلاقة' => 'no_relation',
      'الكيان المالك' => 'entity_owner',
      'نوع المالك' => 'type_owner',
      'الكيان المملوك' => 'entity_owned',
      'نوع الملكية' => 'type_ownership',
      'النسبة' => 'pct',
      'من تاريخ' => 'date_from',
      'إلى تاريخ' => 'date_to',
      'تاريخ التخارج' => 'date_exit',
      'المالك المشتري' => 'owner_buyer',
      'مستند التخارج' => 'doc_exit',
      'مستند الملكية' => 'doc_ownership',
      'اكتمال الملكية' => 'completeness_ownership',
      'مجموع النسب النشطة' => 'active_pct_total',
      'حالة قيد المئة' => 'sum100_state',
      'تضارب مصالح مكتشف؟' => 'conflict_found_flag',
      'سجلها' => 'recorded_by',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'no_relation' => 'رقم العلاقة',
      'entity_owner' => 'الكيان المالك',
      'type_owner' => 'نوع المالك',
      'entity_owned' => 'الكيان المملوك',
      'type_ownership' => 'نوع الملكية',
      'pct' => 'النسبة',
      'date_from' => 'من تاريخ',
      'date_to' => 'إلى تاريخ',
      'date_exit' => 'تاريخ التخارج',
      'owner_buyer' => 'المالك المشتري',
      'doc_exit' => 'مستند التخارج',
      'doc_ownership' => 'مستند الملكية',
      'completeness_ownership' => 'اكتمال الملكية',
      'active_pct_total' => 'مجموع النسب النشطة',
      'sum100_state' => 'حالة قيد المئة',
      'conflict_found_flag' => 'تضارب مصالح مكتشف؟',
      'recorded_by' => 'سجّلها',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
    ),
  ),
  'access_review.php' => 
  array (
    'table' => 'scr_access_review',
    'map' => 
    array (
      'رقم الدورة' => 'no_cycle',
      'الفترة' => 'period_ref',
      'تاريخ الإطلاق' => 'date_launch',
      'الإدارة' => 'dept_name',
      'عدد الحسابات المراجعة' => 'count_accounts_review',
      'المؤكدة' => 'confirmed',
      'المطلوب سحبها' => 'required_revoke',
      'المسحوبة آليا' => 'revoked_auto',
      'الحسابات الخاملة' => 'accounts_dormant',
      'المعطلة' => 'disabled',
      'تعارضات واجبات مكتشفة' => 'conflicts_duties_detected',
      'استثناءات قائمة' => 'exceptions_standing',
      'نسبة الاستجابة' => 'pct_response',
      'مراجع الإدارة' => 'auditor_dept',
      'تاريخ الإقفال' => 'date_closing',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_cycle' => 'رقم الدورة',
      'period_ref' => 'الفترة',
      'date_launch' => 'تاريخ الإطلاق',
      'dept_name' => 'الإدارة',
      'count_accounts_review' => 'عدد الحسابات المراجَعة',
      'confirmed' => 'المؤكَّدة',
      'required_revoke' => 'المطلوب سحبها',
      'revoked_auto' => 'المسحوبة آليًّا',
      'accounts_dormant' => 'الحسابات الخاملة',
      'disabled' => 'المعطَّلة',
      'conflicts_duties_detected' => 'تعارضات واجبات مكتشفة',
      'exceptions_standing' => 'استثناءات قائمة',
      'pct_response' => 'نسبة الاستجابة',
      'auditor_dept' => 'مراجع الإدارة',
      'date_closing' => 'تاريخ الإقفال',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'status_label' => 'الحالة',
    ),
  ),
  'break_glass.php' => 
  array (
    'table' => 'scr_break_glass',
    'map' => 
    array (
      'رقم الطلب' => 'no_request',
      'التاريخ والوقت' => 'happened_at',
      'الطالب — الاسم والصفة' => 'requester_name_capacity_role',
      'الصلاحية المطلوبة' => 'permission_required',
      'الشاشة أو الفعل' => 'screen_or_action',
      'سبب الطوارئ' => 'reason_emergency',
      'الأثر المتوقع لو لم تمنح' => 'impact_expected_if_not_granted',
      'الموافق الأول' => 'approver_first',
      'الموافق الثاني' => 'approver_second',
      'وقت المنح' => 'time_grant',
      'مدة الصلاحية' => 'duration_permission',
      'وقت الانتهاء' => 'time_expiry',
      'عدد الأفعال المنفذة تحتها' => 'count_actions_executed_under_it',
      'تقرير المراجعة' => 'report_review',
      'تاريخ المراجعة' => 'date_review',
      'نتيجة المراجعة' => 'result_review',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_request' => 'رقم الطلب',
      'happened_at' => 'التاريخ والوقت',
      'requester_name_capacity_role' => 'الطالب — الاسم والصفة',
      'permission_required' => 'الصلاحية المطلوبة',
      'screen_or_action' => 'الشاشة أو الفعل',
      'reason_emergency' => 'سبب الطوارئ',
      'impact_expected_if_not_granted' => 'الأثر المتوقع لو لم تُمنح',
      'approver_first' => 'الموافق الأول',
      'approver_second' => 'الموافق الثاني',
      'time_grant' => 'وقت المنح',
      'duration_permission' => 'مدة الصلاحية',
      'time_expiry' => 'وقت الانتهاء',
      'count_actions_executed_under_it' => 'عدد الأفعال المنفَّذة تحتها',
      'report_review' => 'تقرير المراجعة',
      'date_review' => 'تاريخ المراجعة',
      'result_review' => 'نتيجة المراجعة',
      'status_label' => 'الحالة',
    ),
  ),
  'canonical_names.php' => 
  array (
    'table' => 'scr_canonical_names',
    'map' => 
    array (
      'رقم السجل' => 'no_log',
      'نوع الكيان' => 'type_entity',
      'الاسم المعتمد' => 'name_approved',
      'الاسم القانوني الكامل' => 'name_legal_full',
      'المرادفات المسجلة' => 'synonyms_registered',
      'عدد المرادفات' => 'count_synonyms',
      'الاسم في السجل التجاري' => 'name_in_log_commercial',
      'الرقم الضريبي' => 'no_tax',
      'كود الكيان الموحد' => 'code_entity_unified',
      'حالة الفحص' => 'state_check',
      'تكرار مكتشف' => 'duplicate_detected',
      'قرار الدمج' => 'decision_merge',
      'السجلات المحولة' => 'records_migrated',
      'تاريخ الدمج' => 'date_merge',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_log' => 'رقم السجل',
      'type_entity' => 'نوع الكيان',
      'name_approved' => 'الاسم المعتمد',
      'name_legal_full' => 'الاسم القانوني الكامل',
      'synonyms_registered' => 'المرادفات المسجَّلة',
      'count_synonyms' => 'عدد المرادفات',
      'name_in_log_commercial' => 'الاسم في السجل التجاري',
      'no_tax' => 'الرقم الضريبي',
      'code_entity_unified' => 'كود الكيان الموحَّد',
      'state_check' => 'حالة الفحص',
      'duplicate_detected' => 'تكرار مكتشف',
      'decision_merge' => 'قرار الدمج',
      'records_migrated' => 'السجلات المحوَّلة',
      'date_merge' => 'تاريخ الدمج',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'status_label' => 'الحالة',
    ),
  ),
  'doc_types.php' => 
  array (
    'table' => 'scr_doc_types',
    'map' => 
    array (
      'كود النوع' => 'code_type',
      'اسم المستند' => 'name_doc',
      'الإدارة المالكة' => 'dept_owning',
      'نمط الترقيم' => 'pattern_numbering',
      'بادئة الترقيم' => 'prefix_numbering',
      'دورية التسلسل' => 'periodicity_sequence',
      'آلة الحالة المرتبطة' => 'machine_state_linked',
      'يحتاج اعتمادا؟' => 'needs_approval_flag',
      'عدد حلقات الاعتماد' => 'count_loops_approval',
      'له أثر مالي؟' => 'has_fin_impact_flag',
      'قابل للعكس؟' => 'reversible_flag',
      'نمط العكس' => 'pattern_reversal',
      'مدة الحفظ النظامية' => 'duration_retention_statutory',
      'سياسة الأرشفة' => 'policy_archiving',
      'تاريخ السريان' => 'date_effective',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'code_type' => 'كود النوع',
      'name_doc' => 'اسم المستند',
      'dept_owning' => 'الإدارة المالكة',
      'pattern_numbering' => 'نمط الترقيم',
      'prefix_numbering' => 'بادئة الترقيم',
      'periodicity_sequence' => 'دورية التسلسل',
      'machine_state_linked' => 'آلة الحالة المرتبطة',
      'needs_approval_flag' => 'يحتاج اعتمادًا؟',
      'count_loops_approval' => 'عدد حلقات الاعتماد',
      'has_fin_impact_flag' => 'له أثر مالي؟',
      'reversible_flag' => 'قابل للعكس؟',
      'pattern_reversal' => 'نمط العكس',
      'duration_retention_statutory' => 'مدة الحفظ النظامية',
      'policy_archiving' => 'سياسة الأرشفة',
      'date_effective' => 'تاريخ السريان',
      'status_label' => 'الحالة',
    ),
  ),
  'exceptions.php' => 
  array (
    'table' => 'scr_exceptions',
    'map' => 
    array (
      'رقم الطلب' => 'no_request',
      'تاريخ الطلب' => 'date_request',
      'الحماية المستثناة' => 'protection_exempted',
      'الإدارة الطالبة' => 'dept_requesting',
      'سبب الاستثناء' => 'reason_exception',
      'المستندات المؤيدة' => 'docs_supporting',
      'درجة الخطورة' => 'grade_severity',
      'الأثر المتوقع' => 'impact_expected',
      'النطاق' => 'scope_ref',
      'المدة من' => 'period_from',
      'المدة إلى' => 'period_to',
      'الموافقات المطلوبة' => 'approvals_required',
      'الموافقون' => 'approvers',
      'تاريخ الاعتماد' => 'approved_date',
      'عدد مرات الاستعمال' => 'count_times_usage',
      'تاريخ الانتهاء' => 'date_expiry',
      'قرار الإقفال' => 'decision_closing',
      'الحالة' => 'status_label',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'no_request' => 'رقم الطلب',
      'date_request' => 'تاريخ الطلب',
      'protection_exempted' => 'الحماية المستثناة',
      'dept_requesting' => 'الإدارة الطالبة',
      'reason_exception' => 'سبب الاستثناء',
      'docs_supporting' => 'المستندات المؤيدة',
      'grade_severity' => 'درجة الخطورة',
      'impact_expected' => 'الأثر المتوقع',
      'scope_ref' => 'النطاق',
      'period_from' => 'المدة من',
      'period_to' => 'المدة إلى',
      'approvals_required' => 'الموافقات المطلوبة',
      'approvers' => 'الموافقون',
      'approved_date' => 'تاريخ الاعتماد',
      'count_times_usage' => 'عدد مرات الاستعمال',
      'date_expiry' => 'تاريخ الانتهاء',
      'decision_closing' => 'قرار الإقفال',
      'status_label' => 'الحالة',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
    ),
  ),
  'guards.php' => 
  array (
    'table' => 'scr_guards',
    'map' => 
    array (
      'رمز الحارس' => 'code_guard',
      'اسم الحماية' => 'name_protection',
      'الصنف' => 'category',
      'سبب التصنيف' => 'reason_classification',
      'الشاشات المتأثرة' => 'screens_affected',
      'الأفعال الممنوعة' => 'actions_denied',
      'رسالة المنع' => 'message_denial',
      'درجة الخطورة' => 'grade_severity',
      'الموافقات المطلوبة للاستثناء' => 'approvals_required_exception',
      'حالة العلم' => 'state_flag',
      'تاريخ قلب العلم' => 'date_flip_flag',
      'صنفها' => 'classified_by',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'code_guard' => 'رمز الحارس',
      'name_protection' => 'اسم الحماية',
      'category' => 'الصنف',
      'reason_classification' => 'سبب التصنيف',
      'screens_affected' => 'الشاشات المتأثرة',
      'actions_denied' => 'الأفعال الممنوعة',
      'message_denial' => 'رسالة المنع',
      'grade_severity' => 'درجة الخطورة',
      'approvals_required_exception' => 'الموافقات المطلوبة للاستثناء',
      'state_flag' => 'حالة العلَم',
      'date_flip_flag' => 'تاريخ قلب العلَم',
      'classified_by' => 'صنّفها',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
    ),
  ),
  'perm_explain.php' => 
  array (
    'table' => 'scr_perm_explain',
    'map' => 
    array (
      'الحساب' => 'account_ref',
      'الشاشة' => 'screen_ref',
      'الفعل' => 'action_ref',
      'النتيجة النهائية' => 'result_final',
      'مصدر المنح 1' => 'grant_source_1',
      'حكمه' => 'its_ruling_3',
      'مصدر المنح 2' => 'grant_source_2',
      'مصدر المنع' => 'source_denial',
      'قاعدة الدمج المطبقة' => 'rule_merge_applied',
      'النطاق الناتج' => 'scope_resulting',
      'السقف الناتج' => 'cap_resulting',
      'تاريخ الفحص' => 'date_check',
      'الفاحص' => 'inspector_name',
    ),
    'labels' => 
    array (
      'account_ref' => 'الحساب',
      'screen_ref' => 'الشاشة',
      'action_ref' => 'الفعل',
      'result_final' => 'النتيجة النهائية',
      'grant_source_1' => 'مصدر المنح 1',
      'its_ruling' => 'حكمه',
      'grant_source_2' => 'مصدر المنح 2',
      'its_ruling_2' => 'حكمه',
      'source_denial' => 'مصدر المنع',
      'its_ruling_3' => 'حكمه',
      'rule_merge_applied' => 'قاعدة الدمج المطبَّقة',
      'scope_resulting' => 'النطاق الناتج',
      'cap_resulting' => 'السقف الناتج',
      'date_check' => 'تاريخ الفحص',
      'inspector_name' => 'الفاحص',
    ),
  ),
  'portal_users.php' => 
  array (
    'table' => 'scr_portal_users',
    'map' => 
    array (
      'كود الحساب' => 'code_account',
      'نوع الطرف' => 'type_party',
      'الشخص' => 'person_name',
      'الصفة لدى الكيان' => 'capacity_role_at_entity',
      'نطاق الرؤية' => 'scope_visibility',
      'الأفعال المسموحة' => 'actions_allowed',
      'الأفعال المحجوبة' => 'actions_blocked',
      'مستند التخويل' => 'doc_authorization',
      'آخر دخول' => 'last_entry',
      'تاريخ الانتهاء' => 'date_expiry',
      'أنشأه' => 'created_by_f',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'code_account' => 'كود الحساب',
      'type_party' => 'نوع الطرف',
      'person_name' => 'الشخص',
      'capacity_role_at_entity' => 'الصفة لدى الكيان',
      'scope_visibility' => 'نطاق الرؤية',
      'actions_allowed' => 'الأفعال المسموحة',
      'actions_blocked' => 'الأفعال المحجوبة',
      'doc_authorization' => 'مستند التخويل',
      'last_entry' => 'آخر دخول',
      'date_expiry' => 'تاريخ الانتهاء',
      'created_by_f' => 'أنشأه',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
    ),
  ),
  'sensitive_fields.php' => 
  array (
    'table' => 'scr_sensitive_fields',
    'map' => 
    array (
      'رقم السياسة' => 'no_policy',
      'الجدول' => 'table_name',
      'الحقل' => 'field_name',
      'تصنيف الحساسية' => 'classification_sensitivity',
      'سبب التصنيف' => 'reason_classification',
      'من يراه' => 'from_visible_to',
      'سياسة الإخفاء' => 'policy_masking',
      'يسجل الاطلاع؟' => 'log_views_flag',
      'يصدر؟' => 'exportable_flag',
      'الأساس النظامي' => 'basis_statutory',
      'تاريخ السريان' => 'date_effective',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_policy' => 'رقم السياسة',
      'table_name' => 'الجدول',
      'field_name' => 'الحقل',
      'classification_sensitivity' => 'تصنيف الحساسية',
      'reason_classification' => 'سبب التصنيف',
      'from_visible_to' => 'من يراه',
      'policy_masking' => 'سياسة الإخفاء',
      'log_views_flag' => 'يُسجَّل الاطّلاع؟',
      'exportable_flag' => 'يُصدَّر؟',
      'basis_statutory' => 'الأساس النظامي',
      'date_effective' => 'تاريخ السريان',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'status_label' => 'الحالة',
    ),
  ),
  'state_machines.php' => 
  array (
    'table' => 'scr_state_machines',
    'map' => 
    array (
      'كود الآلة' => 'code_machine',
      'نوع المستند' => 'type_doc',
      'رقم الانتقال' => 'no_transition',
      'من حالة' => 'from_state',
      'إلى حالة' => 'to_state',
      'الفعل المطلق' => 'action_triggering',
      'رمز الفعل' => 'code_action',
      'المخول' => 'authorized_role',
      'الشرط المسبق' => 'condition_pre',
      'الحارس المطبق' => 'guard_applied',
      'الحدث المنشور' => 'event_published',
      'قابل للعكس؟' => 'reversible_flag',
      'فعل العكس' => 'action_reversal',
      'تاريخ السريان' => 'date_effective',
      'النسخة' => 'version_no',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'code_machine' => 'كود الآلة',
      'type_doc' => 'نوع المستند',
      'no_transition' => 'رقم الانتقال',
      'from_state' => 'من حالة',
      'to_state' => 'إلى حالة',
      'action_triggering' => 'الفعل المُطلق',
      'code_action' => 'رمز الفعل',
      'authorized_role' => 'المخوَّل',
      'condition_pre' => 'الشرط المسبق',
      'guard_applied' => 'الحارس المطبَّق',
      'event_published' => 'الحدث المنشور',
      'reversible_flag' => 'قابل للعكس؟',
      'action_reversal' => 'فعل العكس',
      'date_effective' => 'تاريخ السريان',
      'version_no' => 'النسخة',
      'status_label' => 'الحالة',
    ),
  ),
  'workshop.php' => 
  array (
    'table' => 'scr_workshop',
    'map' => 
    array (
      'رقم التكليف' => 'no_assignment',
      'أمر العمل' => 'order_work',
      'الفني' => 'technician_name',
      'الوظيفة' => 'job_title',
      'التخصص' => 'specialty',
      'الدور في الأمر' => 'role_in_order',
      'تاريخ البدء' => 'date_start',
      'تاريخ الانتهاء' => 'date_expiry',
      'الساعات الفعلية' => 'hours_actual',
      'تكلفة الساعة' => 'cost_hour',
      'إجمالي التكلفة' => 'total_cost',
      'الورشة' => 'workshop_name',
      'كلفه' => 'assigned_by',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
    ),
    'labels' => 
    array (
      'no_assignment' => 'رقم التكليف',
      'order_work' => 'أمر العمل',
      'technician_name' => 'الفني',
      'job_title' => 'الوظيفة',
      'specialty' => 'التخصص',
      'role_in_order' => 'الدور في الأمر',
      'date_start' => 'تاريخ البدء',
      'date_expiry' => 'تاريخ الانتهاء',
      'hours_actual' => 'الساعات الفعلية',
      'cost_hour' => 'تكلفة الساعة',
      'total_cost' => 'إجمالي التكلفة',
      'workshop_name' => 'الورشة',
      'assigned_by' => 'كلّفه',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
    ),
  ),
  'attendance.php' => 
  array (
    'table' => 'scr_attendance',
    'map' => 
    array (
      'الشهر' => 'month_ref',
      'كود الموظف' => 'code_employee',
      'التاريخ' => 'entry_date',
      'رمز الحالة' => 'code_state',
      'وصف الحالة' => 'description_state',
      'وقت الدخول' => 'time_entry',
      'وقت الخروج' => 'time_exit',
      'ساعات الدوام' => 'hours_attendance',
      'تأخير بالدقائق' => 'delay_minutes',
      'أثر الراتب' => 'impact_salary',
      'أثر الحافز' => 'impact_incentive',
      'أثر التواجد' => 'impact_presence',
      'أثر الفوترة' => 'impact_billing',
      'أثر استحقاق المورد' => 'impact_due_supplier',
      'المستند المؤيد' => 'doc_supporting',
      'سجله' => 'recorded_by',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
    ),
    'labels' => 
    array (
      'month_ref' => 'الشهر',
      'code_employee' => 'كود الموظف',
      'entry_date' => 'التاريخ',
      'code_state' => 'رمز الحالة',
      'description_state' => 'وصف الحالة',
      'time_entry' => 'وقت الدخول',
      'time_exit' => 'وقت الخروج',
      'hours_attendance' => 'ساعات الدوام',
      'delay_minutes' => 'تأخير بالدقائق',
      'impact_salary' => 'أثر الراتب',
      'impact_incentive' => 'أثر الحافز',
      'impact_presence' => 'أثر التواجد',
      'impact_billing' => 'أثر الفوترة',
      'impact_due_supplier' => 'أثر استحقاق المورد',
      'doc_supporting' => 'المستند المؤيد',
      'recorded_by' => 'سجّله',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
    ),
  ),
  'equipment_quota.php' => 
  array (
    'table' => 'scr_equipment_quota',
    'map' => 
    array (
      'رقم الحاوية' => 'no_container',
      'المورد' => 'supplier_name',
      'العقد العميل' => 'contract_client',
      'عقد المورد' => 'contract_supplier',
      'نموذج العمل' => 'model_work',
      'وحدة العمل' => 'unit_work',
      'نوع المعدة' => 'type_equipment',
      'كود المعدة' => 'code_equipment',
      'دور المعدة' => 'role_equipment',
      'حصة المورد الكلية' => 'share_supplier_total',
      'الحصة المخصصة للمعدة' => 'share_allocated_equipment',
      'عدد الورديات' => 'count_shifts',
      'وحدات الوردية' => 'units_shift',
      'الوحدات الشهرية للمعدة' => 'units_monthly_equipment',
      'مجموع حصص معدات المورد' => 'total_shares_equipment_supplier',
      'المتبقي من حصة المورد' => 'supplier_share_remaining',
      'المنفذ فعليا' => 'executed_actual',
      'الفارق' => 'variance',
      'سبب الفارق' => 'reason_variance',
      'تاريخ السريان' => 'date_effective',
      'تاريخ الانتهاء' => 'date_expiry',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_container' => 'رقم الحاوية',
      'supplier_name' => 'المورد',
      'contract_client' => 'العقد العميل',
      'contract_supplier' => 'عقد المورد',
      'model_work' => 'نموذج العمل',
      'unit_work' => 'وحدة العمل',
      'type_equipment' => 'نوع المعدة',
      'code_equipment' => 'كود المعدة',
      'role_equipment' => 'دور المعدة',
      'share_supplier_total' => 'حصة المورد الكلية',
      'share_allocated_equipment' => 'الحصة المخصَّصة للمعدة',
      'count_shifts' => 'عدد الورديات',
      'units_shift' => 'وحدات الوردية',
      'units_monthly_equipment' => 'الوحدات الشهرية للمعدة',
      'total_shares_equipment_supplier' => 'مجموع حصص معدات المورد',
      'supplier_share_remaining' => 'المتبقي من حصة المورد',
      'executed_actual' => 'المنفَّذ فعليًّا',
      'variance' => 'الفارق',
      'reason_variance' => 'سبب الفارق',
      'date_effective' => 'تاريخ السريان',
      'date_expiry' => 'تاريخ الانتهاء',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'status_label' => 'الحالة',
    ),
  ),
  'monthly_close.php' => 
  array (
    'table' => 'scr_monthly_close',
    'map' => 
    array (
      'رقم المحضر' => 'no_minutes_doc',
      'الشهر' => 'month_ref',
      'العقد' => 'contract_ref',
      'الموقع' => 'site_name',
      'الوحدة التعاقدية' => 'unit_contractual',
      'الساعات التعاقدية' => 'hours_contractual',
      'الساعات حسب سجلنا' => 'hours_per_our_log',
      'الساعات المعتمدة من العميل' => 'hours_client_approved',
      'الفرق' => 'variance',
      'سبب الفرق' => 'reason_variance',
      'الكمية المنفذة' => 'qty_executed',
      'الكمية المعتمدة' => 'qty_approved',
      'قيمة الاستحقاق' => 'value_due',
      'العملة' => 'currency',
      'أعده' => 'prepared_by',
      'اعتمده التشغيل' => 'approved_by_operations',
      'اعتمدته المالية' => 'approved_by_finance',
      'تاريخ الإقفال' => 'date_closing',
      'الحالة' => 'status_label',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
      'درجة الأثر' => 'impact_grade',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
    ),
    'labels' => 
    array (
      'no_minutes_doc' => 'رقم المحضر',
      'month_ref' => 'الشهر',
      'contract_ref' => 'العقد',
      'site_name' => 'الموقع',
      'unit_contractual' => 'الوحدة التعاقدية',
      'hours_contractual' => 'الساعات التعاقدية',
      'hours_per_our_log' => 'الساعات حسب سجلنا',
      'hours_client_approved' => 'الساعات المعتمدة من العميل',
      'variance' => 'الفرق',
      'reason_variance' => 'سبب الفرق',
      'qty_executed' => 'الكمية المنفَّذة',
      'qty_approved' => 'الكمية المعتمدة',
      'value_due' => 'قيمة الاستحقاق',
      'currency' => 'العملة',
      'prepared_by' => 'أعدّه',
      'approved_by_operations' => 'اعتمده التشغيل',
      'approved_by_finance' => 'اعتمدته المالية',
      'date_closing' => 'تاريخ الإقفال',
      'status_label' => 'الحالة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
      'impact_grade' => 'درجة الأثر',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
    ),
  ),
  'production.php' => 
  array (
    'table' => 'scr_production',
    'map' => 
    array (
      'رقم السجل' => 'no_log',
      'التاريخ' => 'entry_date',
      'الموقع' => 'site_name',
      'العقد' => 'contract_ref',
      'بند العقد' => 'line_contract',
      'نوع الإنتاج' => 'type_production',
      'جبهة العمل' => 'front_work',
      'نقطة التفريغ' => 'point_unloading',
      'طريقة القياس' => 'method_measure',
      'الكمية حسب سجلنا' => 'qty_per_our_log',
      'وحدة القياس' => 'unit_measure',
      'الكمية المعتمدة من العميل' => 'qty_client_approved',
      'الفرق' => 'variance',
      'سبب الفرق' => 'reason_variance',
      'المستند المرفق' => 'attached_doc',
      'المدخل' => 'entered_by',
      'معتمد العميل' => 'approved_client',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'درجة الأثر' => 'impact_grade',
    ),
    'labels' => 
    array (
      'no_log' => 'رقم السجل',
      'entry_date' => 'التاريخ',
      'site_name' => 'الموقع',
      'contract_ref' => 'العقد',
      'line_contract' => 'بند العقد',
      'type_production' => 'نوع الإنتاج',
      'front_work' => 'جبهة العمل',
      'point_unloading' => 'نقطة التفريغ',
      'method_measure' => 'طريقة القياس',
      'qty_per_our_log' => 'الكمية حسب سجلنا',
      'unit_measure' => 'وحدة القياس',
      'qty_client_approved' => 'الكمية المعتمدة من العميل',
      'variance' => 'الفرق',
      'reason_variance' => 'سبب الفرق',
      'attached_doc' => 'المستند المرفق',
      'entered_by' => 'المُدخِل',
      'approved_client' => 'معتمد العميل',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'impact_grade' => 'درجة الأثر',
    ),
  ),
  'shift_log.php' => 
  array (
    'table' => 'scr_shift_log',
    'map' => 
    array (
      'رقم السجل' => 'no_log',
      'التاريخ' => 'entry_date',
      'الموقع' => 'site_name',
      'الوردية' => 'shift_name',
      'وقت الفتح' => 'time_open',
      'وقت الإقفال' => 'time_closing',
      'عدد المعدات' => 'count_equipment',
      'عدد المشغلين الحاضرين' => 'count_operators_present',
      'الغياب' => 'absent_count',
      'قراءة العداد عند الفتح' => 'reading_meter_at_open',
      'قراءة العداد عند الإقفال' => 'reading_meter_at_closing',
      'الملاحظات' => 'notes',
      'المسلم' => 'handed_by',
      'المستلم' => 'received_by',
      'حالة السجل' => 'state_log',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'no_log' => 'رقم السجل',
      'entry_date' => 'التاريخ',
      'site_name' => 'الموقع',
      'shift_name' => 'الوردية',
      'time_open' => 'وقت الفتح',
      'time_closing' => 'وقت الإقفال',
      'count_equipment' => 'عدد المعدات',
      'count_operators_present' => 'عدد المشغّلين الحاضرين',
      'absent_count' => 'الغياب',
      'reading_meter_at_open' => 'قراءة العدّاد عند الفتح',
      'reading_meter_at_closing' => 'قراءة العدّاد عند الإقفال',
      'notes' => 'الملاحظات',
      'handed_by' => 'المسلِّم',
      'received_by' => 'المستلِم',
      'state_log' => 'حالة السجل',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
    ),
  ),
  'site_gate_equip.php' => 
  array (
    'table' => 'scr_site_gate_equip',
    'map' => 
    array (
      'رقم الإذن' => 'no_permit',
      'نوع الإذن' => 'type_permit',
      'الموقع' => 'site_name',
      'كود المعدة' => 'code_equipment',
      'نوع المعدة' => 'type_equipment',
      'مصدر المعدة' => 'source_equipment',
      'الجهة المرافقة' => 'party_escort',
      'سبب الحركة' => 'reason_movement',
      'المستند المرجعي' => 'doc_reference',
      'تاريخ الحركة المخطط' => 'date_movement_planned',
      'تاريخ الحركة الفعلي' => 'date_movement_actual',
      'قراءة العداد عند الحركة' => 'reading_meter_at_movement',
      'رحلة الترحيل' => 'trip_haulage',
      'حالة الجاهزية' => 'state_readiness',
      'حالة الوثائق' => 'state_documents',
      'اعتماد مدير الموقع' => 'approval_manager_site',
      'اعتماد مدير التشغيل' => 'approval_manager_operations',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_permit' => 'رقم الإذن',
      'type_permit' => 'نوع الإذن',
      'site_name' => 'الموقع',
      'code_equipment' => 'كود المعدة',
      'type_equipment' => 'نوع المعدة',
      'source_equipment' => 'مصدر المعدة',
      'party_escort' => 'الجهة المرافقة',
      'reason_movement' => 'سبب الحركة',
      'doc_reference' => 'المستند المرجعي',
      'date_movement_planned' => 'تاريخ الحركة المخطط',
      'date_movement_actual' => 'تاريخ الحركة الفعلي',
      'reading_meter_at_movement' => 'قراءة العدّاد عند الحركة',
      'trip_haulage' => 'رحلة الترحيل',
      'state_readiness' => 'حالة الجاهزية',
      'state_documents' => 'حالة الوثائق',
      'approval_manager_site' => 'اعتماد مدير الموقع',
      'approval_manager_operations' => 'اعتماد مدير التشغيل',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'status_label' => 'الحالة',
    ),
  ),
  'site_gate_person.php' => 
  array (
    'table' => 'scr_site_gate_person',
    'map' => 
    array (
      'رقم الإذن' => 'no_permit',
      'نوع الإذن' => 'type_permit',
      'الموقع' => 'site_name',
      'كود المشغل' => 'code_operator',
      'الاسم' => 'name_ar',
      'التبعية' => 'affiliation',
      'المورد التابع له' => 'supplier_belongs_has',
      'سبب الحركة' => 'reason_movement',
      'دورة التناوب' => 'cycle_rotation',
      'تاريخ بداية العمل' => 'date_start_work',
      'تاريخ نهاية العمل' => 'date_end_work',
      'رحلة الدخول أو الخروج' => 'trip_entry_or_exit',
      'السكن المخصص' => 'housing_allocated',
      'حالة الرخصة' => 'state_license',
      'حالة الفحص الطبي' => 'state_check_medical',
      'المصادقة الأمنية' => 'attestation_security',
      'اعتماد مدير الموقع' => 'approval_manager_site',
      'اعتماد مدير التشغيل' => 'approval_manager_operations',
      'تاريخ الاعتماد' => 'approved_date',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_permit' => 'رقم الإذن',
      'type_permit' => 'نوع الإذن',
      'site_name' => 'الموقع',
      'code_operator' => 'كود المشغّل',
      'name_ar' => 'الاسم',
      'affiliation' => 'التبعية',
      'supplier_belongs_has' => 'المورد التابع له',
      'reason_movement' => 'سبب الحركة',
      'cycle_rotation' => 'دورة التناوب',
      'date_start_work' => 'تاريخ بداية العمل',
      'date_end_work' => 'تاريخ نهاية العمل',
      'trip_entry_or_exit' => 'رحلة الدخول أو الخروج',
      'housing_allocated' => 'السكن المخصَّص',
      'state_license' => 'حالة الرخصة',
      'state_check_medical' => 'حالة الفحص الطبي',
      'attestation_security' => 'المصادقة الأمنية',
      'approval_manager_site' => 'اعتماد مدير الموقع',
      'approval_manager_operations' => 'اعتماد مدير التشغيل',
      'approved_date' => 'تاريخ الاعتماد',
      'status_label' => 'الحالة',
    ),
  ),
  'site_shift_plan.php' => 
  array (
    'table' => 'scr_site_shift_plan',
    'map' => 
    array (
      'رقم الجدول' => 'no_schedule',
      'الموقع' => 'site_name',
      'التاريخ' => 'entry_date',
      'الوردية' => 'shift_name',
      'من الساعة' => 'time_from',
      'إلى الساعة' => 'time_to',
      'كود المعدة' => 'code_equipment',
      'نوع المعدة' => 'type_equipment',
      'المشغل المكلف' => 'operator_assignee',
      'المشغل البديل' => 'operator_substitute',
      'فحص التأهيل' => 'check_qualification',
      'فحص الرخصة' => 'check_license',
      'فحص الجاهزية' => 'check_readiness',
      'جبهة العمل' => 'front_work',
      'الهدف الإنتاجي' => 'target_production',
      'نافذة الصيانة' => 'window_maintenance',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_schedule' => 'رقم الجدول',
      'site_name' => 'الموقع',
      'entry_date' => 'التاريخ',
      'shift_name' => 'الوردية',
      'time_from' => 'من الساعة',
      'time_to' => 'إلى الساعة',
      'code_equipment' => 'كود المعدة',
      'type_equipment' => 'نوع المعدة',
      'operator_assignee' => 'المشغّل المكلَّف',
      'operator_substitute' => 'المشغّل البديل',
      'check_qualification' => 'فحص التأهيل',
      'check_license' => 'فحص الرخصة',
      'check_readiness' => 'فحص الجاهزية',
      'front_work' => 'جبهة العمل',
      'target_production' => 'الهدف الإنتاجي',
      'window_maintenance' => 'نافذة الصيانة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'status_label' => 'الحالة',
    ),
  ),
  'site_work_calendar.php' => 
  array (
    'table' => 'scr_site_work_calendar',
    'map' => 
    array (
      'رقم الجدول' => 'no_schedule',
      'الموقع' => 'site_name',
      'المشروع' => 'project_name',
      'العقد' => 'contract_ref',
      'الشهر' => 'month_ref',
      'الأسبوع' => 'week_ref',
      'أيام العمل المخططة' => 'days_work_planned',
      'أيام التوقف المخطط' => 'days_stoppage_planned',
      'سبب التوقف' => 'reason_stoppage',
      'ساعات التشغيل اليومية' => 'hours_operations_daily',
      'عدد الورديات' => 'count_shifts',
      'الكمية المستهدفة الشهرية' => 'qty_target_monthly',
      'الكمية المستهدفة الأسبوعية' => 'qty_target_weekly',
      'المعدات المخصصة' => 'equipment_allocated',
      'المشغلون المطلوبون' => 'operators_required',
      'نوافذ الوقائية' => 'windows_preventive',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_schedule' => 'رقم الجدول',
      'site_name' => 'الموقع',
      'project_name' => 'المشروع',
      'contract_ref' => 'العقد',
      'month_ref' => 'الشهر',
      'week_ref' => 'الأسبوع',
      'days_work_planned' => 'أيام العمل المخططة',
      'days_stoppage_planned' => 'أيام التوقف المخطط',
      'reason_stoppage' => 'سبب التوقف',
      'hours_operations_daily' => 'ساعات التشغيل اليومية',
      'count_shifts' => 'عدد الورديات',
      'qty_target_monthly' => 'الكمية المستهدفة الشهرية',
      'qty_target_weekly' => 'الكمية المستهدفة الأسبوعية',
      'equipment_allocated' => 'المعدات المخصَّصة',
      'operators_required' => 'المشغّلون المطلوبون',
      'windows_preventive' => 'نوافذ الوقائية',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'status_label' => 'الحالة',
    ),
  ),
  'unbilled.php' => 
  array (
    'table' => 'scr_unbilled',
    'map' => 
    array (
      'رقم البند' => 'no_line',
      'العقد' => 'contract_ref',
      'الشهر' => 'month_ref',
      'الوحدة' => 'unit_name',
      'وصف العمل' => 'description_work',
      'الكمية' => 'qty',
      'القيمة' => 'amount',
      'العملة' => 'currency',
      'تاريخ التنفيذ' => 'date_execution',
      'سبب الاحتباس' => 'reason_retention',
      'عمر الاحتباس بالأيام' => 'age_retention_days',
      'احتمال الاعتماد' => 'likelihood_approval',
      'إجراء المتابعة' => 'procedure_followup',
      'تاريخ آخر مطالبة' => 'date_last_claim',
      'المسؤول' => 'responsible_name',
      'الحالة' => 'status_label',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
      'درجة الأثر' => 'impact_grade',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
    ),
    'labels' => 
    array (
      'no_line' => 'رقم البند',
      'contract_ref' => 'العقد',
      'month_ref' => 'الشهر',
      'unit_name' => 'الوحدة',
      'description_work' => 'وصف العمل',
      'qty' => 'الكمية',
      'amount' => 'القيمة',
      'currency' => 'العملة',
      'date_execution' => 'تاريخ التنفيذ',
      'reason_retention' => 'سبب الاحتباس',
      'age_retention_days' => 'عمر الاحتباس بالأيام',
      'likelihood_approval' => 'احتمال الاعتماد',
      'procedure_followup' => 'إجراء المتابعة',
      'date_last_claim' => 'تاريخ آخر مطالبة',
      'responsible_name' => 'المسؤول',
      'status_label' => 'الحالة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
      'impact_grade' => 'درجة الأثر',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
    ),
  ),
  'unit_perf.php' => 
  array (
    'table' => 'scr_unit_perf',
    'map' => 
    array (
      'الشهر' => 'month_ref',
      'العقد' => 'contract_ref',
      'الوحدة التعاقدية' => 'unit_contractual',
      'كود المعدة' => 'code_equipment',
      'الساعات التعاقدية' => 'hours_contractual',
      'ساعات التشغيل' => 'hours_operations',
      'ساعات الاستعداد المفوتر' => 'hours_standby_billable',
      'ساعات التوقف — عميل' => 'downtime_hours_client',
      'ساعات التوقف — مورد' => 'downtime_hours_supplier',
      'ساعات التوقف — نحن' => 'downtime_hours_ours',
      'فاقد غير منفذ' => 'loss_not_executed',
      'توقف صيانة' => 'stoppage_maintenance',
      'توقف موارد بشرية' => 'stoppage_hr_hr',
      'توقف تسويات' => 'stoppage_settlements',
      'قوة قاهرة' => 'force_majeure',
      'صيانة مجدولة' => 'maintenance_scheduled',
      'إجمالي التعطل' => 'total_downtime',
      'الطرف المتحمل الأغلب' => 'main_bearing_party',
      'نسبة الجاهزية' => 'pct_readiness',
      'العجز عن التعاقدي' => 'contract_shortfall',
      'بند الجزاء' => 'line_penalty',
      'قيمة الجزاء' => 'value_penalty',
      'الحالة' => 'status_label',
      'درجة الأثر' => 'impact_grade',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
      'نسخة القاعدة المستعملة' => 'version_rule_used',
    ),
    'labels' => 
    array (
      'month_ref' => 'الشهر',
      'contract_ref' => 'العقد',
      'unit_contractual' => 'الوحدة التعاقدية',
      'code_equipment' => 'كود المعدة',
      'hours_contractual' => 'الساعات التعاقدية',
      'hours_operations' => 'ساعات التشغيل',
      'hours_standby_billable' => 'ساعات الاستعداد المفوتر',
      'downtime_hours_client' => 'ساعات التوقف — عميل',
      'downtime_hours_supplier' => 'ساعات التوقف — مورد',
      'downtime_hours_ours' => 'ساعات التوقف — نحن',
      'loss_not_executed' => 'فاقد غير منفَّذ',
      'stoppage_maintenance' => 'توقف صيانة',
      'stoppage_hr_hr' => 'توقف موارد بشرية',
      'stoppage_settlements' => 'توقف تسويات',
      'force_majeure' => 'قوة قاهرة',
      'maintenance_scheduled' => 'صيانة مجدولة',
      'total_downtime' => 'إجمالي التعطل',
      'main_bearing_party' => 'الطرف المتحمل الأغلب',
      'pct_readiness' => 'نسبة الجاهزية',
      'contract_shortfall' => 'العجز عن التعاقدي',
      'line_penalty' => 'بند الجزاء',
      'value_penalty' => 'قيمة الجزاء',
      'status_label' => 'الحالة',
      'impact_grade' => 'درجة الأثر',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
      'version_rule_used' => 'نسخة القاعدة المستعملة',
    ),
  ),
  'business_models.php' => 
  array (
    'table' => 'scr_business_models',
    'map' => 
    array (
      'كود النموذج' => 'code_model',
      'اسم النموذج' => 'name_model',
      'وحدة العمل' => 'unit_work',
      'وحدة القياس' => 'unit_measure',
      'طريقة القياس الميدانية' => 'method_measure_field',
      'المستند المثبت' => 'doc_proving',
      'أساس التسعير' => 'basis_pricing',
      'أنواع المعدات المنطبقة' => 'types_equipment_applicable',
      'وحدة عداد المعدة' => 'unit_meter_equipment',
      'وحدة حاوية المورد' => 'unit_container_supplier',
      'وحدة تعاقد المورد' => 'unit_contracting_supplier',
      'أساس استحقاق المورد' => 'basis_due_supplier',
      'أساس أجر المشغل' => 'basis_wage_operator',
      'دورة الإقفال' => 'cycle_closing',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ السريان' => 'date_effective',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'code_model' => 'كود النموذج',
      'name_model' => 'اسم النموذج',
      'unit_work' => 'وحدة العمل',
      'unit_measure' => 'وحدة القياس',
      'method_measure_field' => 'طريقة القياس الميدانية',
      'doc_proving' => 'المستند المُثبت',
      'basis_pricing' => 'أساس التسعير',
      'types_equipment_applicable' => 'أنواع المعدات المنطبقة',
      'unit_meter_equipment' => 'وحدة عدّاد المعدة',
      'unit_container_supplier' => 'وحدة حاوية المورد',
      'unit_contracting_supplier' => 'وحدة تعاقد المورد',
      'basis_due_supplier' => 'أساس استحقاق المورد',
      'basis_wage_operator' => 'أساس أجر المشغّل',
      'cycle_closing' => 'دورة الإقفال',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'date_effective' => 'تاريخ السريان',
      'status_label' => 'الحالة',
    ),
  ),
  'contract_review.php' => 
  array (
    'table' => 'scr_contract_review',
    'map' => 
    array (
      'رقم الملاحظة' => 'no_note',
      'العقد' => 'contract_ref',
      'تاريخ الرصد' => 'date_observation',
      'نوع الملاحظة' => 'type_note',
      'درجة الملاحظة' => 'grade_note',
      'البند المتأثر' => 'line_affected',
      'وصف الملاحظة' => 'description_note',
      'الأثر المحتمل' => 'impact_potential',
      'القيمة المعرضة' => 'value_exposed',
      'العملة' => 'currency',
      'الجهة الراصدة' => 'party_observing',
      'الإجراء المطلوب' => 'procedure_required',
      'المسؤول' => 'responsible_name',
      'مهلة المعالجة' => 'deadline_handling',
      'تاريخ المعالجة' => 'date_handling',
      'مستند المعالجة' => 'doc_handling',
      'يحجب الاعتماد؟' => 'blocks_approval_flag',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الإقفال' => 'date_closing',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_note' => 'رقم الملاحظة',
      'contract_ref' => 'العقد',
      'date_observation' => 'تاريخ الرصد',
      'type_note' => 'نوع الملاحظة',
      'grade_note' => 'درجة الملاحظة',
      'line_affected' => 'البند المتأثر',
      'description_note' => 'وصف الملاحظة',
      'impact_potential' => 'الأثر المحتمل',
      'value_exposed' => 'القيمة المعرَّضة',
      'currency' => 'العملة',
      'party_observing' => 'الجهة الراصدة',
      'procedure_required' => 'الإجراء المطلوب',
      'responsible_name' => 'المسؤول',
      'deadline_handling' => 'مهلة المعالجة',
      'date_handling' => 'تاريخ المعالجة',
      'doc_handling' => 'مستند المعالجة',
      'blocks_approval_flag' => 'يحجب الاعتماد؟',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'date_closing' => 'تاريخ الإقفال',
      'status_label' => 'الحالة',
    ),
  ),
  'founding_mode.php' => 
  array (
    'table' => 'scr_founding_mode',
    'map' => 
    array (
      'رقم الوضع' => 'no_mode',
      'تاريخ الفتح' => 'date_open',
      'سبب الفتح' => 'reason_open',
      'النطاق المسموح' => 'scope_allowed',
      'الجداول المتأثرة' => 'tables_affected',
      'المدة المصرح بها' => 'duration_authorized',
      'تاريخ الإغلاق المخطط' => 'date_close_planned',
      'تاريخ الإغلاق الفعلي' => 'date_close_actual',
      'عدد السجلات المدخلة' => 'count_records_entered',
      'وسم السجلات' => 'tag_records',
      'المدخلون' => 'entered_by_list',
      'الموافق على الفتح' => 'open_approver',
      'الموافق على الإغلاق' => 'close_approver',
      'تقرير المراجعة بعد الإغلاق' => 'report_review_after_close',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_mode' => 'رقم الوضع',
      'date_open' => 'تاريخ الفتح',
      'reason_open' => 'سبب الفتح',
      'scope_allowed' => 'النطاق المسموح',
      'tables_affected' => 'الجداول المتأثرة',
      'duration_authorized' => 'المدة المصرَّح بها',
      'date_close_planned' => 'تاريخ الإغلاق المخطط',
      'date_close_actual' => 'تاريخ الإغلاق الفعلي',
      'count_records_entered' => 'عدد السجلات المُدخَلة',
      'tag_records' => 'وسم السجلات',
      'entered_by_list' => 'المُدخِلون',
      'open_approver' => 'الموافق على الفتح',
      'close_approver' => 'الموافق على الإغلاق',
      'report_review_after_close' => 'تقرير المراجعة بعد الإغلاق',
      'status_label' => 'الحالة',
    ),
  ),
  'release_stamp.php' => 
  array (
    'table' => 'scr_release_stamp',
    'map' => 
    array (
      'رقم الإصدار' => 'no_release',
      'بصمة الإصدار' => 'fingerprint_release',
      'تاريخ النشر' => 'date_publish',
      'نوع الإصدار' => 'type_release',
      'الشاشات المضافة' => 'screens_added',
      'الشاشات المعدلة' => 'screens_modified',
      'الأعمدة المضافة' => 'columns_added',
      'الأفعال المضافة' => 'actions_added',
      'القواعد المتغيرة' => 'rules_changed',
      'الهجرات المنفذة' => 'migrations_executed',
      'تقرير الاكتمال' => 'report_completeness',
      'الاختبارات المجتازة' => 'tests_passed',
      'الاختبارات الراسبة' => 'tests_failed',
      'علم الرجوع' => 'flag_rollback',
      'الناشر — الاسم والصفة' => 'publisher_name_capacity_role',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_release' => 'رقم الإصدار',
      'fingerprint_release' => 'بصمة الإصدار',
      'date_publish' => 'تاريخ النشر',
      'type_release' => 'نوع الإصدار',
      'screens_added' => 'الشاشات المضافة',
      'screens_modified' => 'الشاشات المعدَّلة',
      'columns_added' => 'الأعمدة المضافة',
      'actions_added' => 'الأفعال المضافة',
      'rules_changed' => 'القواعد المتغيرة',
      'migrations_executed' => 'الهجرات المنفَّذة',
      'report_completeness' => 'تقرير الاكتمال',
      'tests_passed' => 'الاختبارات المجتازة',
      'tests_failed' => 'الاختبارات الراسبة',
      'flag_rollback' => 'علَم الرجوع',
      'publisher_name_capacity_role' => 'الناشر — الاسم والصفة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'status_label' => 'الحالة',
    ),
  ),
  'consumption_rate.php' => 
  array (
    'table' => 'scr_consumption_rate',
    'map' => 
    array (
      'رقم السجل' => 'no_log',
      'الفترة' => 'period_ref',
      'كود المعدة' => 'code_equipment',
      'نوع المعدة' => 'type_equipment',
      'الموقع' => 'site_name',
      'الوحدة التعاقدية' => 'unit_contractual',
      'ساعات التشغيل' => 'hours_operations',
      'صنف الاستهلاك' => 'category_consumption',
      'الكمية المصروفة' => 'qty_disbursed',
      'الوحدة' => 'unit_name',
      'معدل الاستهلاك للساعة' => 'rate_consumption_hour',
      'المعدل المرجعي للموديل' => 'rate_reference_model',
      'الانحراف' => 'deviation',
      'نسبة الانحراف' => 'pct_deviation',
      'حد الشذوذ' => 'threshold_anomaly',
      'حالة الشذوذ' => 'state_anomaly',
      'السبب المرجح' => 'reason_probable',
      'البلاغ المفتوح' => 'ticket_open',
      'تكلفة الاستهلاك' => 'cost_consumption',
      'العملة' => 'currency',
      'مركز التكلفة' => 'cost_center',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_log' => 'رقم السجل',
      'period_ref' => 'الفترة',
      'code_equipment' => 'كود المعدة',
      'type_equipment' => 'نوع المعدة',
      'site_name' => 'الموقع',
      'unit_contractual' => 'الوحدة التعاقدية',
      'hours_operations' => 'ساعات التشغيل',
      'category_consumption' => 'صنف الاستهلاك',
      'qty_disbursed' => 'الكمية المصروفة',
      'unit_name' => 'الوحدة',
      'rate_consumption_hour' => 'معدل الاستهلاك للساعة',
      'rate_reference_model' => 'المعدل المرجعي للموديل',
      'deviation' => 'الانحراف',
      'pct_deviation' => 'نسبة الانحراف',
      'threshold_anomaly' => 'حد الشذوذ',
      'state_anomaly' => 'حالة الشذوذ',
      'reason_probable' => 'السبب المرجَّح',
      'ticket_open' => 'البلاغ المفتوح',
      'cost_consumption' => 'تكلفة الاستهلاك',
      'currency' => 'العملة',
      'cost_center' => 'مركز التكلفة',
      'status_label' => 'الحالة',
    ),
  ),
  'transfer_fleet.php' => 
  array (
    'table' => 'scr_transfer_fleet',
    'map' => 
    array (
      'كود الناقل' => 'code_carrier',
      'النوع' => 'kind',
      'الوصف' => 'description',
      'الملكية' => 'ownership_kind',
      'المالك' => 'owner_name',
      'السعة القصوى' => 'capacity_max',
      'رقم اللوحة' => 'no_plate',
      'الرخصة' => 'license_ref',
      'تاريخ انتهاء الرخصة' => 'date_expiry_license',
      'التأمين' => 'insurance_ref',
      'تاريخ انتهاء التأمين' => 'date_expiry_insurance',
      'السائق المكلف' => 'driver_assignee',
      'التعرفة' => 'tariff',
      'العملة' => 'currency',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'code_carrier' => 'كود الناقل',
      'kind' => 'النوع',
      'description' => 'الوصف',
      'ownership_kind' => 'الملكية',
      'owner_name' => 'المالك',
      'capacity_max' => 'السعة القصوى',
      'no_plate' => 'رقم اللوحة',
      'license_ref' => 'الرخصة',
      'date_expiry_license' => 'تاريخ انتهاء الرخصة',
      'insurance_ref' => 'التأمين',
      'date_expiry_insurance' => 'تاريخ انتهاء التأمين',
      'driver_assignee' => 'السائق المكلَّف',
      'tariff' => 'التعرفة',
      'currency' => 'العملة',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
    ),
  ),
  'transfer_permits.php' => 
  array (
    'table' => 'scr_transfer_permits',
    'map' => 
    array (
      'رقم التصريح' => 'no_permit',
      'أمر الترحيل' => 'order_haulage',
      'الجهة المصدرة' => 'party_issuing',
      'نوع التصريح' => 'type_permit',
      'المسار المصرح' => 'route_authorized',
      'الحمولة المصرحة' => 'load_authorized',
      'الوزن الإجمالي' => 'weight_total',
      'تاريخ الإصدار' => 'date_release',
      'تاريخ الانتهاء' => 'date_expiry',
      'الرسوم' => 'fees',
      'المرفق' => 'attachment',
      'استخرجه' => 'issued_by',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
    ),
    'labels' => 
    array (
      'no_permit' => 'رقم التصريح',
      'order_haulage' => 'أمر الترحيل',
      'party_issuing' => 'الجهة المصدِرة',
      'type_permit' => 'نوع التصريح',
      'route_authorized' => 'المسار المصرَّح',
      'load_authorized' => 'الحمولة المصرَّحة',
      'weight_total' => 'الوزن الإجمالي',
      'date_release' => 'تاريخ الإصدار',
      'date_expiry' => 'تاريخ الانتهاء',
      'fees' => 'الرسوم',
      'attachment' => 'المرفق',
      'issued_by' => 'استخرجه',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
    ),
  ),
  'deductions.php' => 
  array (
    'table' => 'scr_deductions',
    'map' => 
    array (
      'رقم القرار' => 'no_decision',
      'كود الموظف' => 'code_employee',
      'الشهر' => 'month_ref',
      'نوع الخصم' => 'type_deduction',
      'سبب الخصم' => 'reason_deduction',
      'بند السياسة المرجعي' => 'line_policy_reference',
      'المستند المؤيد' => 'doc_supporting',
      'الأساس' => 'basis',
      'المعادلة' => 'formula',
      'قيمة الخصم' => 'value_deduction',
      'العملة' => 'currency',
      'نسبة من الصافي' => 'pct_of_net',
      'اقترحه' => 'proposed_by',
      'راجعته الموارد' => 'reviewed_by_hr',
      'اعتماد الإدارة' => 'approval_dept',
      'الاعتماد المالي' => 'approval_financial',
      'اعتماد الإدارة العامة' => 'approval_dept_general',
      'المسير' => 'payroll_ref',
      'الحالة' => 'status_label',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'درجة الأثر' => 'impact_grade',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
      'نسخة القاعدة المستعملة' => 'version_rule_used',
    ),
    'labels' => 
    array (
      'no_decision' => 'رقم القرار',
      'code_employee' => 'كود الموظف',
      'month_ref' => 'الشهر',
      'type_deduction' => 'نوع الخصم',
      'reason_deduction' => 'سبب الخصم',
      'line_policy_reference' => 'بند السياسة المرجعي',
      'doc_supporting' => 'المستند المؤيد',
      'basis' => 'الأساس',
      'formula' => 'المعادلة',
      'value_deduction' => 'قيمة الخصم',
      'currency' => 'العملة',
      'pct_of_net' => 'نسبة من الصافي',
      'proposed_by' => 'اقترحه',
      'reviewed_by_hr' => 'راجعته الموارد',
      'approval_dept' => 'اعتماد الإدارة',
      'approval_financial' => 'الاعتماد المالي',
      'approval_dept_general' => 'اعتماد الإدارة العامة',
      'payroll_ref' => 'المسيّر',
      'status_label' => 'الحالة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'impact_grade' => 'درجة الأثر',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
      'version_rule_used' => 'نسخة القاعدة المستعملة',
    ),
  ),
  'op_codes.php' => 
  array (
    'table' => 'scr_op_codes',
    'map' => 
    array (
      'الرقم' => 'item_no',
      'حالة الرقم' => 'state_no',
      'المشغل السابق' => 'operator_previous',
      'تاريخ الإخلاء' => 'date_vacate',
      'سبب الإخلاء' => 'reason_vacate',
      'مدة الشغور بالأيام' => 'duration_vacancy_days',
      'المشغل الجديد' => 'operator_new',
      'تاريخ التخصيص الجديد' => 'date_allocation_new',
      'قرار الإدارة' => 'decision_dept',
      'خصصه' => 'allocated_by',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'item_no' => 'الرقم',
      'state_no' => 'حالة الرقم',
      'operator_previous' => 'المشغّل السابق',
      'date_vacate' => 'تاريخ الإخلاء',
      'reason_vacate' => 'سبب الإخلاء',
      'duration_vacancy_days' => 'مدة الشغور بالأيام',
      'operator_new' => 'المشغّل الجديد',
      'date_allocation_new' => 'تاريخ التخصيص الجديد',
      'decision_dept' => 'قرار الإدارة',
      'allocated_by' => 'خصّصه',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
    ),
  ),
  'op_monthly.php' => 
  array (
    'table' => 'scr_op_monthly',
    'map' => 
    array (
      'الشهر' => 'month_ref',
      'كود المشغل' => 'code_operator',
      'المعدة' => 'equipment_name',
      'الموقع' => 'site_name',
      'أيام العمل' => 'days_work',
      'أيام الإجازة' => 'days_leave',
      'أيام الغياب' => 'days_absence',
      'ساعات التشغيل' => 'hours_operations',
      'ساعات إضافية' => 'hours_overtime',
      'ساعات الاستعداد' => 'hours_standby',
      'الإنتاج المنسوب' => 'production_attributed',
      'نسبة الإنجاز' => 'pct_achievement',
      'أساس الحافز' => 'basis_incentive',
      'قيمة الحافز' => 'value_incentive',
      'العملة' => 'currency',
      'اعتمده' => 'approved_by',
      'الحالة' => 'status_label',
      'درجة الأثر' => 'impact_grade',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
      'نسخة القاعدة المستعملة' => 'version_rule_used',
    ),
    'labels' => 
    array (
      'month_ref' => 'الشهر',
      'code_operator' => 'كود المشغّل',
      'equipment_name' => 'المعدة',
      'site_name' => 'الموقع',
      'days_work' => 'أيام العمل',
      'days_leave' => 'أيام الإجازة',
      'days_absence' => 'أيام الغياب',
      'hours_operations' => 'ساعات التشغيل',
      'hours_overtime' => 'ساعات إضافية',
      'hours_standby' => 'ساعات الاستعداد',
      'production_attributed' => 'الإنتاج المنسوب',
      'pct_achievement' => 'نسبة الإنجاز',
      'basis_incentive' => 'أساس الحافز',
      'value_incentive' => 'قيمة الحافز',
      'currency' => 'العملة',
      'approved_by' => 'اعتمده',
      'status_label' => 'الحالة',
      'impact_grade' => 'درجة الأثر',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
      'version_rule_used' => 'نسخة القاعدة المستعملة',
    ),
  ),
  'op_qual.php' => 
  array (
    'table' => 'scr_op_qual',
    'map' => 
    array (
      'رقم التأهيل' => 'no_qualification',
      'كود المشغل' => 'code_operator',
      'نوع المعدة' => 'type_equipment',
      'الموديل' => 'model_ref',
      'مستوى التأهيل' => 'level_qualification',
      'جهة التأهيل' => 'party_qualification',
      'رقم الشهادة' => 'no_certificate',
      'تاريخ الإصدار' => 'date_release',
      'تاريخ الانتهاء' => 'date_expiry',
      'ساعات الخبرة على النوع' => 'hours_experience_on_type',
      'المقيم' => 'assessor_name',
      'تاريخ آخر تقييم' => 'date_last_evaluation',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
    ),
    'labels' => 
    array (
      'no_qualification' => 'رقم التأهيل',
      'code_operator' => 'كود المشغّل',
      'type_equipment' => 'نوع المعدة',
      'model_ref' => 'الموديل',
      'level_qualification' => 'مستوى التأهيل',
      'party_qualification' => 'جهة التأهيل',
      'no_certificate' => 'رقم الشهادة',
      'date_release' => 'تاريخ الإصدار',
      'date_expiry' => 'تاريخ الانتهاء',
      'hours_experience_on_type' => 'ساعات الخبرة على النوع',
      'assessor_name' => 'المقيِّم',
      'date_last_evaluation' => 'تاريخ آخر تقييم',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
    ),
  ),
  'project_contracts.php' => 
  array (
    'table' => 'scr_project_contracts',
    'map' => 
    array (
      'رقم العقد' => 'no_contract',
      'فئة العقد' => 'category_contract',
      'المتعاقد معه' => 'contracted_with',
      'التبعية' => 'affiliation',
      'المورد المرتبط' => 'supplier_linked',
      'عقد المورد' => 'contract_supplier',
      'المشروع' => 'project_name',
      'الموقع' => 'site_name',
      'المسمى' => 'position_title',
      'نموذج الأجر' => 'model_wage',
      'الأجر الشهري' => 'wage_monthly',
      'العملة' => 'currency',
      'تاريخ البدء' => 'date_start',
      'تاريخ الانتهاء المخطط' => 'date_expiry_planned',
      'محفز الانتهاء 1' => 'end_trigger_1',
      'محفز الانتهاء 2' => 'end_trigger_2',
      'محفز الانتهاء 3' => 'end_trigger_3',
      'المحفز الواقع' => 'end_trigger_hit',
      'تاريخ الانتهاء الفعلي' => 'date_expiry_actual',
      'مهلة التنبيه قبل الانتهاء' => 'expiry_alert_lead',
      'حالة التصفية' => 'state_liquidation',
      'إذن الخروج' => 'permit_exit',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'الحالة' => 'status_label',
    ),
    'labels' => 
    array (
      'no_contract' => 'رقم العقد',
      'category_contract' => 'فئة العقد',
      'contracted_with' => 'المتعاقَد معه',
      'affiliation' => 'التبعية',
      'supplier_linked' => 'المورد المرتبط',
      'contract_supplier' => 'عقد المورد',
      'project_name' => 'المشروع',
      'site_name' => 'الموقع',
      'position_title' => 'المسمى',
      'model_wage' => 'نموذج الأجر',
      'wage_monthly' => 'الأجر الشهري',
      'currency' => 'العملة',
      'date_start' => 'تاريخ البدء',
      'date_expiry_planned' => 'تاريخ الانتهاء المخطط',
      'end_trigger_1' => 'محفّز الانتهاء 1',
      'end_trigger_2' => 'محفّز الانتهاء 2',
      'end_trigger_3' => 'محفّز الانتهاء 3',
      'end_trigger_hit' => 'المحفّز الواقع',
      'date_expiry_actual' => 'تاريخ الانتهاء الفعلي',
      'expiry_alert_lead' => 'مهلة التنبيه قبل الانتهاء',
      'state_liquidation' => 'حالة التصفية',
      'permit_exit' => 'إذن الخروج',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'status_label' => 'الحالة',
    ),
  ),
  'rotation.php' => 
  array (
    'table' => 'scr_rotation',
    'map' => 
    array (
      'رقم الدورة' => 'no_cycle',
      'كود المشغل' => 'code_operator',
      'الموقع' => 'site_name',
      'المعدة' => 'equipment_name',
      'نمط التناوب' => 'pattern_rotation',
      'نوع الإجازة' => 'type_leave',
      'تاريخ الدخول' => 'date_entry',
      'تاريخ الخروج' => 'date_exit',
      'أيام العمل' => 'days_work',
      'أيام الإجازة' => 'days_leave',
      'المناوب المتبادل' => 'rotator_swapped',
      'حالة التبادل' => 'state_swap',
      'تاريخ تبادل المناوب' => 'date_swap_rotator',
      'البديل عند تعذر التبادل' => 'fallback_substitute',
      'رحلة الدخول' => 'trip_entry',
      'رحلة الخروج' => 'trip_exit',
      'رصيد الإجازة قبل' => 'balance_leave_before',
      'رصيد الإجازة بعد' => 'balance_leave_after',
      'جدولها' => 'scheduled_by',
      'الحالة' => 'status_label',
      'المعتمد — الاسم والصفة' => 'approver_name',
      'تاريخ الاعتماد' => 'approved_date',
      'مرجع التفويض' => 'authority_ref',
      'المرجع الأب' => 'parent_ref',
      'المرفق' => 'attachment',
      'مركز التكلفة' => 'cost_center',
      'سعر الصرف ومصدره' => 'fx_rate_source',
    ),
    'labels' => 
    array (
      'no_cycle' => 'رقم الدورة',
      'code_operator' => 'كود المشغّل',
      'site_name' => 'الموقع',
      'equipment_name' => 'المعدة',
      'pattern_rotation' => 'نمط التناوب',
      'type_leave' => 'نوع الإجازة',
      'date_entry' => 'تاريخ الدخول',
      'date_exit' => 'تاريخ الخروج',
      'days_work' => 'أيام العمل',
      'days_leave' => 'أيام الإجازة',
      'rotator_swapped' => 'المناوب المتبادل',
      'state_swap' => 'حالة التبادل',
      'date_swap_rotator' => 'تاريخ تبادل المناوب',
      'fallback_substitute' => 'البديل عند تعذّر التبادل',
      'trip_entry' => 'رحلة الدخول',
      'trip_exit' => 'رحلة الخروج',
      'balance_leave_before' => 'رصيد الإجازة قبل',
      'balance_leave_after' => 'رصيد الإجازة بعد',
      'scheduled_by' => 'جدولها',
      'status_label' => 'الحالة',
      'approver_name' => 'المعتمِد — الاسم والصفة',
      'approved_date' => 'تاريخ الاعتماد',
      'authority_ref' => 'مرجع التفويض',
      'parent_ref' => 'المرجع الأب',
      'attachment' => 'المرفق',
      'cost_center' => 'مركز التكلفة',
      'fx_rate_source' => 'سعر الصرف ومصدره',
    ),
  ),
);
}
}
