<?php
/**
 * خريطة أيقونات السايدبار — أيقونة معبِّرة لكل رابطٍ ورأسِ مرحلة
 * ─────────────────────────────────────────────────────────────────────────
 * المصدر الواحد لتخصيص الأيقونات: يستهلكه مستورد NAV-09 عند التوليد
 * (فيصمد التخصيص أمام كل --apply) والمصيّر الموحّد لرؤوس المراحل.
 * الترتيب: المسار الحرفي (بمرساته ثم بدونها ثم بلا استعلام) → كلمات
 * التسمية → مجلد المسار → الافتراضي القديم fa fa-circle-dot.
 * الأيقونات كلها من Font Awesome Free Solid (المحمَّلة 7.x).
 */

/** المسار الحرفي → الأيقونة (شاشات soon تُفهرس باسم الشاشة وحده) */
function ems_nav_route_icons() {
    return array(
        // ── العقود والعملاء ──
        'Contracts/contracts.php'            => 'fa fa-file-signature',
        'Contracts/contracts.php#coverage'   => 'fa fa-percent',
        'Contracts/contract_card.php'        => 'fa fa-file-contract',
        'Contracts/contract_coverage.php'    => 'fa fa-clipboard-list',
        'Contracts/price_terms.php'          => 'fa fa-money-bill-trend-up',
        'Contracts/penalties.php'            => 'fa fa-gavel',
        'Contracts/tax_invoices.php'         => 'fa fa-file-invoice-dollar',
        'Contracts/claims.php'               => 'fa fa-file-invoice',
        'Contracts/collections.php'          => 'fa fa-sack-dollar',
        'Contracts/client_statement.php'     => 'fa fa-receipt',
        'Contracts/plan_actual_link.php'     => 'fa fa-link',
        'Clients/clients.php'                => 'fa fa-user-tie',
        'Clients/quotations.php'             => 'fa fa-tag',
        'Clients/pricelists.php'             => 'fa fa-tags',
        'Clients/products.php'               => 'fa fa-store',
        'Clients/units_of_measure.php'       => 'fa fa-ruler',
        'Clients/contract_events.php'        => 'fa fa-timeline',
        'Clients/contract_amendments.php'    => 'fa fa-file-circle-plus',
        'Clients/commercial_risks.php'       => 'fa fa-triangle-exclamation',
        'Opportunities/opportunities.php'    => 'fa fa-lightbulb',
        // ── البلاغات ──
        'Tickets/tickets_list.php'                   => 'fa fa-list-ul',
        'Tickets/tickets_list.php?filter=admin_close'=> 'fa fa-circle-check',
        'Tickets/tickets_list.php?search=1'          => 'fa fa-magnifying-glass',
        'Tickets/dept_inbox.php'                     => 'fa fa-inbox',
        'Tickets/ticket_contextual_open.php'         => 'fa fa-circle-exclamation',
        'Tickets/admin_close.php'                    => 'fa fa-circle-check',
        'Tickets/ticket_types_config.php'            => 'fa fa-sliders',
        'Tickets/ticket_recurrence.php'              => 'fa fa-arrows-rotate',
        'Tickets/ticket_workstreams_board.php'       => 'fa fa-share-nodes',
        'Tickets/ticket_dashboard.php'               => 'fa fa-chart-line',
        'Tickets/ticket_escalation_config.php'       => 'fa fa-arrow-up-right-dots',
        // ── الإدارة والتنظيم والأمان ──
        'admin/org_permits.php'                  => 'fa fa-id-card-clip',
        'admin/org_assignments.php'              => 'fa fa-user-tag',
        'admin/org_structure.php'                => 'fa fa-sitemap',
        'admin/audit_log.php'                    => 'fa fa-ban',
        'admin/sec_governance.php'               => 'fa fa-user-shield',
        'admin/sec_governance.php?tab=review'    => 'fa fa-clipboard-check',
        'admin/sec_governance.php?tab=explain'   => 'fa fa-circle-question',
        'admin/sec_governance.php?tab=visibility'=> 'fa fa-eye',
        'main/users.php'                         => 'fa fa-user-gear',
        'main/all_assistants.php'                => 'fa fa-user-group',
        'Settings/roles.php'                     => 'fa fa-user-lock',
        'Settings/modules.php'                   => 'fa fa-window-restore',
        'ActivityLogs/activity_logs.php'         => 'fa fa-clock-rotate-left',
        // ── الموردون ──
        'Suppliers/suppliers.php'            => 'fa fa-industry',
        'Suppliers/suppliers.php#plan'       => 'fa fa-clipboard-list',
        'Suppliers/supplierscontracts.php'   => 'fa fa-file-signature',
        'Suppliers/supplier_capacity.php'    => 'fa fa-gauge',
        'Suppliers/settlements.php'          => 'fa fa-handshake',
        'Suppliers/supplier_closure.php'     => 'fa fa-file-circle-xmark',
        'Suppliers/supplier_evaluation.php'  => 'fa fa-star-half-stroke',
        'Suppliers/shares_coverage.php'      => 'fa fa-percent',
        'Suppliers/equipment_plan.php'       => 'fa fa-tractor',
        'Suppliers/supplier_advances.php'    => 'fa fa-hand-holding-dollar',
        'Suppliers/rfq_requests.php'         => 'fa fa-envelope-open-text',
        'Suppliers/supplier_rules.php'       => 'fa fa-scale-balanced',
        // ── المشتريات والمخازن ──
        'Procurement/master_data_proc.php'    => 'fa fa-warehouse',
        'Procurement/items_proc.php'          => 'fa fa-tags',
        'Procurement/requests_proc.php'       => 'fa fa-basket-shopping',
        'Procurement/orders_proc.php'         => 'fa fa-cart-shopping',
        'Procurement/rfq_compare_award.php'   => 'fa fa-ranking-star',
        'Procurement/stock_proc.php'          => 'fa fa-boxes-stacked',
        'Procurement/issue_proc.php'          => 'fa fa-dolly',
        'Procurement/receipt_custody_proc.php'=> 'fa fa-box-open',
        'Procurement/wh_transfer.php'         => 'fa fa-right-left',
        'Procurement/wh_count.php'            => 'fa fa-clipboard-list',
        // ── المالية ──
        'Finance/currencies_fin.php'            => 'fa fa-money-bill-transfer',
        'Finance/periods_fin.php'               => 'fa fa-lock',
        'Finance/cash_forecast_fin.php'         => 'fa fa-chart-line',
        'Finance/assets_fin.php'                => 'fa fa-arrow-trend-down',
        'Finance/accounts_fin.php'              => 'fa fa-vault',
        'Finance/financial_statements_fin.php'  => 'fa fa-file-invoice',
        'Finance/journal_form_fin.php'          => 'fa fa-book',
        'Finance/budget_master.php'             => 'fa fa-sack-dollar',
        'Finance/budget_dept.php'               => 'fa fa-coins',
        'Finance/bank_reconciliation_fin.php'   => 'fa fa-building-columns',
        'Finance/dues_fin.php'                  => 'fa fa-money-bill-wave',
        'Finance/cost_report_fin.php'           => 'fa fa-chart-pie',
        'Finance/funding_fin.php'               => 'fa fa-hand-holding-dollar',
        'Finance/entitlement_gate.php'          => 'fa fa-filter-circle-dollar',
        'Finance/payments_fin.php'              => 'fa fa-money-check-dollar',
        'Finance/approvals_inbox.php'           => 'fa fa-inbox',
        'Finance/supplier_statement_fin.php'    => 'fa fa-receipt',
        'Finance/operator_pay_policies_fin.php' => 'fa fa-money-check',
        'Finance/maintenance_provision_fin.php' => 'fa fa-piggy-bank',
        'Finance/variance_monitor_fin.php'      => 'fa fa-magnifying-glass-chart',
        'Finance/management_accounting_fin.php' => 'fa fa-book-open',
        'FinRequests/my_requests.php'           => 'fa fa-paper-plane',
        'FinRequests/effect_map.php'            => 'fa fa-arrows-turn-to-dots',
        'FinRequests/cycle_time_board.php'      => 'fa fa-stopwatch',
        'FinRequests/routing_admin.php'         => 'fa fa-signs-post',
        'FinRequests/accountant_desk.php'       => 'fa fa-calculator',
        // ── التمويل والملكية ──
        'Financing/financing_board.php'      => 'fa fa-table-columns',
        'Financing/installments.php'         => 'fa fa-calendar-days',
        'Financing/deviations.php'           => 'fa fa-triangle-exclamation',
        'Financing/owners_registry.php'      => 'fa fa-crown',
        'Financing/financiers_registry.php'  => 'fa fa-building-columns',
        'Financing/cost_allocation.php'      => 'fa fa-arrows-split-up-and-left',
        // ── المعدات والأسطول ──
        'Equipments/equipments.php'                  => 'fa fa-tractor',
        'Equipments/equipments_types.php'            => 'fa fa-shapes',
        'Equipments/fleet_models.php'                => 'fa fa-cubes',
        'Equipments/manage_failure_codes.php'        => 'fa fa-bug',
        'Equipments/meter_readings.php'              => 'fa fa-gauge',
        'Equipments/equipment_documents.php'         => 'fa fa-id-card',
        'Equipments/fleet_depreciation_profiles.php' => 'fa fa-arrow-trend-down',
        'Fleet/readiness_board.php'                  => 'fa fa-clipboard-check',
        'Employees/equipment_operators.php'          => 'fa fa-users-gear',
        'Employees/employees.php'                    => 'fa fa-users',
        'Employees/employee_contracts.php'           => 'fa fa-file-signature',
        // ── الصيانة ──
        'Maintenance/orders.php'           => 'fa fa-screwdriver-wrench',
        'Maintenance/inspections.php'      => 'fa fa-magnifying-glass',
        'Maintenance/preventive_plans.php' => 'fa fa-calendar-check',
        // ── الترحيل والحركة ──
        'Transport/transfer_requests.php'    => 'fa fa-truck-arrow-right',
        'Transport/transfer_orders_list.php' => 'fa fa-truck',
        'Transport/transfer_in_transit.php'  => 'fa fa-truck-fast',
        'Transport/transfer_close_cost.php'  => 'fa fa-truck-ramp-box',
        'Transport/transfer_tariffs.php'     => 'fa fa-money-bill',
        'movement/movement_operations.php'   => 'fa fa-user-clock',
        'movement/map_page.php'              => 'fa fa-map-location-dot',
        // ── العمليات والمواقع ──
        'Operations/operations_room.php'     => 'fa fa-tower-observation',
        'Operations/daily_plan.php'          => 'fa fa-calendar-day',
        'Operations/containers.php'          => 'fa fa-cubes-stacked',
        'Operations/distribution_space.php'  => 'fa fa-people-arrows',
        'Operations/stops_unattributed.php'  => 'fa fa-circle-pause',
        'Timesheet/timesheet.php'            => 'fa fa-clock',
        'Projects/projects.php'              => 'fa fa-diagram-project',
        // ── القوى العاملة ──
        'Workforce/recruitment_pipeline.php'  => 'fa fa-user-plus',
        'Workforce/contract_registry.php'     => 'fa fa-file-contract',
        'Workforce/worker_leave_absence.php'  => 'fa fa-umbrella-beach',
        'Workforce/worker_evaluation.php'     => 'fa fa-star-half-stroke',
        'Workforce/worker_movement.php'       => 'fa fa-person-walking-luggage',
        'Workforce/worker_worklog.php'        => 'fa fa-clock-rotate-left',
        'Workforce/housing_units.php'         => 'fa fa-house-user',
        'Workforce/employee_advances.php'     => 'fa fa-hand-holding-dollar',
        'Workforce/employee_settlements.php'  => 'fa fa-scale-balanced',
        'Workforce/employee_settlements.php?view=proposed' => 'fa fa-circle-minus',
        'Workforce/proposed_deductions.php'   => 'fa fa-circle-minus',
        'Workforce/final_settlement.php'      => 'fa fa-person-walking-arrow-right',
        'Workforce/payroll_runs.php'          => 'fa fa-money-check-dollar',
        // ── الحوكمة ──
        'Governance/entities_registry.php'    => 'fa fa-building',
        'Governance/licenses_guarantees.php'  => 'fa fa-certificate',
        'Governance/signing_authority.php'    => 'fa fa-signature',
        // ── البوابة والتقارير والمراسلات ──
        'Portal/my_portal.php'        => 'fa fa-id-badge',
        'Portal/my_achievement.php'   => 'fa fa-medal',
        'Portal/dept_achievement.php' => 'fa fa-trophy',
        'Portal/visibility_keys.php'  => 'fa fa-eye',
        'Reports/reports.php'         => 'fa fa-chart-column',
        'Reports/exceptions_report.php'                          => 'fa fa-triangle-exclamation',
        'Reports/exceptions_report.php?focus=unattributed_stops' => 'fa fa-circle-pause',
        'emsreports/index.php'        => 'fa fa-chart-column',
        'chats/index.php'             => 'fa fa-comments',
        // ── شاشات «قريبًا» (تُفهرس باسم الشاشة) ──
        'my_tasks.php'          => 'fa fa-list-check',
        'shift_log.php'         => 'fa fa-clipboard',
        'site_gate_person.php'  => 'fa fa-door-open',
        'site_gate_equip.php'   => 'fa fa-truck-moving',
        'site_shift_plan.php'   => 'fa fa-cloud-sun',
        'site_work_calendar.php'=> 'fa fa-calendar',
        'op_codes.php'          => 'fa fa-hashtag',
        'op_qual.php'           => 'fa fa-graduation-cap',
        'op_monthly.php'        => 'fa fa-chart-simple',
        'unit_perf.php'         => 'fa fa-chart-area',
        'unbilled.php'          => 'fa fa-file-circle-exclamation',
        'monthly_close.php'     => 'fa fa-lock',
        'production.php'        => 'fa fa-weight-scale',
        'consumption_rate.php'  => 'fa fa-gas-pump',
        'attendance.php'        => 'fa fa-fingerprint',
        'rotation.php'          => 'fa fa-rotate',
        'deductions.php'        => 'fa fa-circle-minus',
        'activation.php'        => 'fa fa-toggle-on',
        'workshop.php'          => 'fa fa-toolbox',
        'wh_receipt.php'        => 'fa fa-truck-ramp-box',
        'po_match.php'          => 'fa fa-check-double',
        'transfer_fleet.php'    => 'fa fa-trailer',
        'transfer_permits.php'  => 'fa fa-road',
        'equipment_quota.php'   => 'fa fa-chart-pie',
        'equipment_sourcing.php'=> 'fa fa-arrows-down-to-people',
        'code_bridge.php'       => 'fa fa-bridge',
        'asset_recon.php'       => 'fa fa-scale-balanced',
        'licenses.php'          => 'fa fa-certificate',
        'delegations.php'       => 'fa fa-signature',
        'entities.php'          => 'fa fa-building',
        'ownership_links.php'   => 'fa fa-circle-nodes',
        'founding_mode.php'     => 'fa fa-seedling',
        'fin_assets.php'        => 'fa fa-gem',
        'fin_models.php'        => 'fa fa-file-invoice',
        'fin_changes.php'       => 'fa fa-file-pen',
        'business_models.php'   => 'fa fa-ruler-combined',
        'margin.php'            => 'fa fa-arrow-trend-up',
        'project_charter.php'   => 'fa fa-folder-plus',
        'project_contracts.php' => 'fa fa-file-contract',
        'contract_review.php'   => 'fa fa-file-circle-question',
        'ceo_board.php'         => 'fa fa-gauge-high',
        'ceo_approvals.php'     => 'fa fa-stamp',
        'Approvals/hours_approval.php' => 'fa fa-stamp', // سلسلة اعتماد التايم شيت الرباعية
        'ceo_contracts.php'     => 'fa fa-pen-fancy',
        'ceo_risk.php'          => 'fa fa-scale-unbalanced',
        'exceptions.php'        => 'fa fa-hand',
        'guards.php'            => 'fa fa-shield-halved',
        'break_glass.php'       => 'fa fa-hammer',
        'sensitive_fields.php'  => 'fa fa-eye-slash',
        'access_review.php'     => 'fa fa-user-check',
        'perm_explain.php'      => 'fa fa-circle-question',
        'portal_users.php'      => 'fa fa-users-rectangle',
        'supplier_bank.php'     => 'fa fa-building-columns',
        'doc_types.php'         => 'fa fa-file-lines',
        'state_machines.php'    => 'fa fa-shuffle',
        'canonical_names.php'   => 'fa fa-spell-check',
        'release_stamp.php'     => 'fa fa-rocket',
    );
}

/** كلمات التسمية → الأيقونة (احتياط الشاشات الجديدة خارج الخريطة الحرفية) */
function ems_nav_label_icon_rules() {
    return array(
        'بلاغ'      => 'fa fa-bullhorn',
        'صيانة'     => 'fa fa-screwdriver-wrench',
        'عطل'       => 'fa fa-bug',
        'ترحيل'     => 'fa fa-truck',
        'مخزون'     => 'fa fa-boxes-stacked',
        'مخزن'      => 'fa fa-warehouse',
        'مخازن'     => 'fa fa-warehouse',
        'جرد'       => 'fa fa-clipboard-list',
        'شراء'      => 'fa fa-cart-shopping',
        'فاتورة'    => 'fa fa-file-invoice-dollar',
        'فواتير'    => 'fa fa-file-invoice-dollar',
        'مستخلص'    => 'fa fa-file-invoice',
        'رواتب'     => 'fa fa-money-check-dollar',
        'مسيّر'     => 'fa fa-money-check-dollar',
        'سلف'       => 'fa fa-hand-holding-dollar',
        'خصوم'      => 'fa fa-circle-minus',
        'جزاء'      => 'fa fa-gavel',
        'ميزانية'   => 'fa fa-coins',
        'موازنة'    => 'fa fa-sack-dollar',
        'خزينة'     => 'fa fa-vault',
        'بنك'       => 'fa fa-building-columns',
        'قيود'      => 'fa fa-book',
        'إقفال'     => 'fa fa-lock',
        'تقارير'    => 'fa fa-chart-column',
        'تقرير'     => 'fa fa-chart-column',
        'مؤشرات'    => 'fa fa-chart-line',
        'لوحة'      => 'fa fa-gauge-high',
        'عدّاد'     => 'fa fa-gauge',
        'وثائق'     => 'fa fa-file-lines',
        'ملاحق'     => 'fa fa-file-circle-plus',
        'عقود'      => 'fa fa-file-signature',
        'عقد'       => 'fa fa-file-contract',
        'عملاء'     => 'fa fa-user-tie',
        'العميل'    => 'fa fa-user-tie',
        'مورد'      => 'fa fa-industry',
        'مشغّل'     => 'fa fa-users-gear',
        'موظف'      => 'fa fa-users',
        'العاملين'  => 'fa fa-users',
        'حضور'      => 'fa fa-fingerprint',
        'إجاز'      => 'fa fa-umbrella-beach',
        'وردية'     => 'fa fa-clock',
        'ورديات'    => 'fa fa-clock',
        'توزيع'     => 'fa fa-people-arrows',
        'تكليف'     => 'fa fa-people-arrows',
        'إسناد'     => 'fa fa-people-arrows',
        'خريطة'     => 'fa fa-map-location-dot',
        'مشاريع'    => 'fa fa-diagram-project',
        'مشروع'     => 'fa fa-diagram-project',
        'أذون'      => 'fa fa-id-card-clip',
        'تصاريح'    => 'fa fa-road',
        'صلاحي'     => 'fa fa-user-shield',
        'تدقيق'     => 'fa fa-magnifying-glass',
        'مراجعة'    => 'fa fa-magnifying-glass',
        'اعتماد'    => 'fa fa-stamp',
        'توقيع'     => 'fa fa-signature',
        'تفويض'     => 'fa fa-signature',
        'حوكمة'     => 'fa fa-landmark',
        'كيانات'    => 'fa fa-building',
        'ملكية'     => 'fa fa-crown',
        'حصص'       => 'fa fa-percent',
        'تمويل'     => 'fa fa-hand-holding-dollar',
        'معدات'     => 'fa fa-tractor',
        'المعدة'    => 'fa fa-tractor',
        'أسطول'     => 'fa fa-tractor',
        'مخاطر'     => 'fa fa-triangle-exclamation',
        'انحراف'    => 'fa fa-triangle-exclamation',
        'تقييم'     => 'fa fa-star-half-stroke',
        'تسوي'      => 'fa fa-handshake',
        'مطابقة'    => 'fa fa-check-double',
        'مهام'      => 'fa fa-list-check',
        'إنجاز'     => 'fa fa-trophy',
        'مراسلات'   => 'fa fa-comments',
        'طلبات'     => 'fa fa-inbox',
        'سعر'       => 'fa fa-money-bill-trend-up',
        'أسعار'     => 'fa fa-tags',
        'دفع'       => 'fa fa-money-check-dollar',
        'سداد'      => 'fa fa-money-check-dollar',
        'ذمم'       => 'fa fa-money-bill-wave',
        'سجل'       => 'fa fa-folder-open',
    );
}

/** مجلد المسار → الأيقونة (آخر الاحتياطات قبل الافتراضي) */
function ems_nav_dir_icons() {
    return array(
        'Tickets'     => 'fa fa-bullhorn',
        'Maintenance' => 'fa fa-screwdriver-wrench',
        'Transport'   => 'fa fa-truck',
        'Procurement' => 'fa fa-cart-shopping',
        'Finance'     => 'fa fa-coins',
        'Financing'   => 'fa fa-hand-holding-dollar',
        'FinRequests' => 'fa fa-file-invoice-dollar',
        'Suppliers'   => 'fa fa-industry',
        'Contracts'   => 'fa fa-file-contract',
        'Clients'     => 'fa fa-user-tie',
        'Employees'   => 'fa fa-users',
        'Workforce'   => 'fa fa-users',
        'Equipments'  => 'fa fa-tractor',
        'Fleet'       => 'fa fa-tractor',
        'Operations'  => 'fa fa-helmet-safety',
        'Governance'  => 'fa fa-landmark',
        'Settings'    => 'fa fa-gear',
        'admin'       => 'fa fa-shield-halved',
        'Reports'     => 'fa fa-chart-column',
        'emsreports'  => 'fa fa-chart-column',
        'Portal'      => 'fa fa-id-badge',
        'Timesheet'   => 'fa fa-clock',
        'movement'    => 'fa fa-route',
        'chats'       => 'fa fa-comments',
        'Opportunities' => 'fa fa-lightbulb',
        'Projects'    => 'fa fa-diagram-project',
        'ActivityLogs'=> 'fa fa-clock-rotate-left',
    );
}

/**
 * أيقونة رابط السايدبار من مساره وتسميته.
 * @param string $label تسمية الرابط العربية
 * @param string $route المسار كما في nav_items (قد يحمل مرساةً أو استعلامًا)
 */
function ems_nav_icon_for($label, $route) {
    $map = ems_nav_route_icons();
    $r = (string) $route;
    if (isset($map[$r])) { return $map[$r]; }
    $r = preg_replace('/#.*$/u', '', $r);               // المرساة التوليدية n9g… وأخواتها
    if (isset($map[$r])) { return $map[$r]; }
    if (preg_match('/soon\.php\?screen=([^&#]+)/', $r, $m)) { $r = $m[1]; }
    if (isset($map[$r])) { return $map[$r]; }
    $bare = preg_replace('/\?.*$/u', '', $r);            // بلا استعلام
    if (isset($map[$bare])) { return $map[$bare]; }
    foreach (ems_nav_label_icon_rules() as $kw => $icon) {
        if (mb_strpos((string) $label, $kw) !== false) { return $icon; }
    }
    $dirs = ems_nav_dir_icons();
    $slash = strpos($bare, '/');
    if ($slash !== false) {
        $dir = substr($bare, 0, $slash);
        if (isset($dirs[$dir])) { return $dirs[$dir]; }
    }
    return 'fa fa-circle-dot';
}

/**
 * أيقونة رأس المرحلة من رقمها وعنوانها (المصيّر الموحّد — وضع المراحل).
 * 0 لوحة الانطلاق و99 ذيل «خارج الوثيقة» يحتفظان بأيقونتيهما الدلاليتين.
 */
function ems_nav_stage_icon($stageNo, $stageTitle) {
    if (intval($stageNo) === 0)  { return 'fa fa-gauge-high'; }
    if (intval($stageNo) === 99) { return 'fa fa-box-archive'; }
    $rules = array(
        'استقبال'   => 'fa fa-inbox',
        'استلام'    => 'fa fa-box-open',
        'توظيف'     => 'fa fa-user-plus',
        'ترسية'     => 'fa fa-ranking-star',
        'عروض'      => 'fa fa-tags',
        'تسعير'     => 'fa fa-tags',
        'توقيع'     => 'fa fa-signature',
        'تفويض'     => 'fa fa-signature',
        'تعاقد'     => 'fa fa-file-signature',
        'العقد'     => 'fa fa-file-contract',
        'العقود'    => 'fa fa-file-signature',
        'تمويل'     => 'fa fa-hand-holding-dollar',
        'الممول'    => 'fa fa-hand-holding-dollar',
        'ملكية'     => 'fa fa-crown',
        'الأعيان'   => 'fa fa-gem',
        'الكيانات'  => 'fa fa-building',
        'خطة'       => 'fa fa-calendar-days',
        'جدول'      => 'fa fa-calendar-days',
        'ترميز'     => 'fa fa-hashtag',
        'التكويد'   => 'fa fa-hashtag',
        'إيراد'     => 'fa fa-file-invoice-dollar',
        'فوترة'     => 'fa fa-file-invoice-dollar',
        'مستخلص'    => 'fa fa-file-invoice',
        'مستحق'     => 'fa fa-filter-circle-dollar',
        'اعتماد'    => 'fa fa-stamp',
        'أذون'      => 'fa fa-id-card-clip',
        'تصاريح'    => 'fa fa-road',
        'تصنيف'     => 'fa fa-filter',
        'جاهزية'    => 'fa fa-clipboard-check',
        'توزيع'     => 'fa fa-people-arrows',
        'تكليف'     => 'fa fa-people-arrows',
        'تخصيص'     => 'fa fa-people-arrows',
        'شراء'      => 'fa fa-cart-shopping',
        'صرف'       => 'fa fa-dolly',
        'عهدة'      => 'fa fa-dolly',
        'حضور'      => 'fa fa-fingerprint',
        'إجازات'    => 'fa fa-umbrella-beach',
        'قطع'       => 'fa fa-boxes-stacked',
        'مواد'      => 'fa fa-boxes-stacked',
        'مصروف'     => 'fa fa-money-check-dollar',
        'دفع'       => 'fa fa-money-check-dollar',
        'سداد'      => 'fa fa-money-check-dollar',
        'مسيّر'     => 'fa fa-money-check-dollar',
        'حسابات'    => 'fa fa-user-gear',
        'رقابة'     => 'fa fa-eye',
        'حركة'      => 'fa fa-truck-fast',
        'وردية'     => 'fa fa-clock',
        'الورديات'  => 'fa fa-clock',
        'تناوب'     => 'fa fa-rotate',
        'وقائية'    => 'fa fa-shield-halved',
        'تسجيل'     => 'fa fa-pen-to-square',
        'إقفال'     => 'fa fa-lock',
        'إغلاق'     => 'fa fa-lock',
        'الإخراج'   => 'fa fa-person-walking-arrow-right',
        'خزينة'     => 'fa fa-vault',
        'مطابقة'    => 'fa fa-check-double',
        'خصومات'    => 'fa fa-circle-minus',
        'الأقساط'   => 'fa fa-calendar-days',
        'التكلفة'   => 'fa fa-coins',
        'التأهيل'   => 'fa fa-graduation-cap',
        'نماذج'     => 'fa fa-ruler-combined',
        'التفريع'   => 'fa fa-share-nodes',
        'سلف'       => 'fa fa-hand-holding-dollar',
        'مخاطر'     => 'fa fa-triangle-exclamation',
        'انحراف'    => 'fa fa-triangle-exclamation',
        'تعثّر'     => 'fa fa-triangle-exclamation',
        'منع'       => 'fa fa-ban',
        'استثناء'   => 'fa fa-hand',
        'تدقيق'     => 'fa fa-magnifying-glass',
        'مراجعة'    => 'fa fa-magnifying-glass',
        'تسوية'     => 'fa fa-handshake',
        'تقييم'     => 'fa fa-star-half-stroke',
        'تصفية'     => 'fa fa-file-circle-xmark',
        'قيود'      => 'fa fa-book',
        'دفاتر'     => 'fa fa-book',
        'سرية'      => 'fa fa-user-secret',
        'قوالب'     => 'fa fa-arrows-rotate',
        'إهلاك'     => 'fa fa-arrow-trend-down',
        'مخازن'     => 'fa fa-warehouse',
        'مشتريات'   => 'fa fa-cart-shopping',
        'طلبات'     => 'fa fa-inbox',
        'أداء'      => 'fa fa-chart-line',
        'استحقاق'   => 'fa fa-filter-circle-dollar',
        'تأسيس'     => 'fa fa-seedling',
        'أساس'      => 'fa fa-flag-checkered',
        'مستندات'   => 'fa fa-file-lines',
        'بلاغات'    => 'fa fa-bullhorn',
        'صيانة'     => 'fa fa-screwdriver-wrench',
        'ترحيل'     => 'fa fa-truck',
        'عدّادات'   => 'fa fa-gauge',
        'القوى'     => 'fa fa-users',
        'موردين'    => 'fa fa-industry',
        'الموردين'  => 'fa fa-industry',
        'مبيعات'    => 'fa fa-chart-line',
        'المبيعات'  => 'fa fa-chart-line',
        'الفرصة'    => 'fa fa-lightbulb',
        'الأسطول'   => 'fa fa-tractor',
        'مالية'     => 'fa fa-coins',
        'المالية'   => 'fa fa-coins',
        'محاسب'     => 'fa fa-calculator',
        'حوكمة'     => 'fa fa-landmark',
        'الحوكمة'   => 'fa fa-landmark',
        'تشغيل'     => 'fa fa-gears',
        'الموقع'    => 'fa fa-map-location-dot',
        'البوابة'   => 'fa fa-id-badge',
        'الظهور'    => 'fa fa-eye',
        'المشاريع'  => 'fa fa-folder-plus',
        'متابعة'    => 'fa fa-chart-line',
        'إعدادات'   => 'fa fa-gear',
        'إدخال'     => 'fa fa-database',
        'الموارد'   => 'fa fa-boxes-stacked',
        'إصدار'     => 'fa fa-rocket',
    );
    foreach ($rules as $kw => $icon) {
        if (mb_strpos((string) $stageTitle, $kw) !== false) { return $icon; }
    }
    return 'fa fa-diagram-project';
}
